### ISSUE TITLE
Finalizing email re updating software 

### ISSUE THREAD

**Issue by shaghdoosti** [MozillaFoundation/Advocacy#10]
This email is schedule to go out on May 18, therefore needs to be finalized by May 11 and approved by May 15. 

@mmika is in charge of drafting the email with Sara and @valianttry as support. Draft email is below. @stephaniemcv for reference. 

https://docs.google.com/document/d/1j5E86fgAE3C3eM65s0S1ihGd3v79wnkeTxhzNRFSv9U/edit?ts=572ba5a5

**Comment by mmika** [comment]
new software update email draft: 
https://docs.google.com/document/d/1sWBgZZTj-9FrEzP3oX-pTCa48IqxkVNgQ776QqQ5Wc4/edit

@lovegushwa @natalieworth @stephaniemcv

**Comment by valianttry** [comment]
This work is being tracked in #19 (e.g. that ticket will simply be closed when final copy completes approvals)
