### ISSUE TITLE
EU Copyright campaign asset treatment(s)

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#100]
Creative direction for campaign assets

**Comment by brettgaylor** [comment]
We completed a really good first draft, but will need another week to finalize this.  New goal is July 29th.

**Comment by brettgaylor** [comment]
- [ ] Website wireframes #93
- [ ] 1st video treatment #156 
- [ ]

**Comment by damiankay** [comment]
Hey @brettgaylor - will this include timing for and a breakdown of what's required in V2 of the website? @ScottDowne and I are wondering about scope and bandwidth for integrating functionality discussed here #115 (I.e. customizing delivery of electronic signatures), among other features. If not, perhaps we should probably start documenting what's required for V2 soon. Thx!

**Comment by brettgaylor** [comment]
Yes, it will include V2

**Comment by brettgaylor** [comment]
Approved here
https://docs.google.com/a/mozillafoundation.org/presentation/d/1lbbCBRoUcCns5BdRyCTNKznh4p7h0kLY73qfjeM4Crk/edit?usp=drive_web&usp=slides_home&ths=true
