### ISSUE TITLE
Test and refine user journey

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1000]
There are a few aspects of the user journey we'll need to work out, including:
 - [ ] What are the CTAs during Beat 1 and Beat 2?
 - [ ] Where will the buyer's guide be hosted?
 - [ ] Whether to put some content behind an email sign-up form
   - [ ] Conduct A/B test
- [ ] If we do an email capture during Beat 1 (before the Buyer's Guide is released), how will we re-engage those folks during Beat 2 ( @ScottDowne to work with @stephaniemcv to see what's possible)

**Comment by beccaklam** [comment]
I just have to say, it's pretty awesome that this is ticket #1000.

**Comment by beccaklam** [comment]
Rough user journeys for Influencers and Consumers for Beat 1 & 2:
![beat 1 user journey](https://user-images.githubusercontent.com/20977376/28734646-fc0e87a2-73af-11e7-9c1f-749882d03f4f.png)
![beat 2 user journey](https://user-images.githubusercontent.com/20977376/28734647-fc14f128-73af-11e7-8361-d88a50b88bc8.png)

**Comment by hannahkane** [comment]
This visual reminded me about the free gift drawing idea. @caltrider - do we want to pursue that? If so, I'll file additional tickets.

@beccaklam - do you have thoughts about which pieces of the journey we can test?

**Comment by tlasadea** [comment]
Hey @beccaklam or @caltrider or @brettgaylor, do we know what content the microsite will hold? Esp foe consumer? Just thinking about the engagement piece - I guess the assumption is that people will really want the buyers guide, but incase they don't/are distracted, is there an easy win to get people to interact and get the buyers guide as a "reward." Is there a type of 'what xmas shopper are you?' (e.g.) quiz (offerpop/buzzfeed style) we could do? 🤔

Apols if this has been discussed already!

**Comment by beccaklam** [comment]
Rad idea @tlasadea ! I'll try to find some benchmarks (examples) for this kind of 'easy win'

**Comment by hannahkane** [comment]
All of the questions in the first comment feel either resolved or no longer relevant. @beccaklam - would you agree? Do you feel like we should do some kind of user testing on the UX before we begin the build? Are there any assumptions you want to test?

**Comment by hannahkane** [comment]
Closing this, but @beccaklam, feel free to re-open if you want to discuss testing further.
