### ISSUE TITLE
Editorial calendar

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1003]

**Comment by tlasadea** [comment]
Hey @hannahkane what is this? Is there anything I can help with this? Is it based on Fusion partnership?

**Comment by hannahkane** [comment]
I don't recall what this was a placeholder for, but I do think it has to do with the partnership. @caltrider - any insight into what the deliverable might be here?

We could close this for now, and open new tickets as the partnerships and content strategy demand.

**Comment by caltrider** [comment]
@hannahkane I think it's good to close this for now, your plan sounds good.
