### ISSUE TITLE
Channel plan

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1004]
Including social, snippet, etc.

Please file additional tickets for assets needed

**Comment by HPaulJohnson** [comment]
Took a quick pass at this here: https://docs.google.com/document/d/1KbtqKdftHftYmq8x3nmHymOvLgmRRnCAIEFSeeHK_Q4/edit

@tlasadea and I will discuss how to add necessary details to this over the coming month. I suspect most of the building of assets (at least for the big consumer part of the push) to happen upon my return in early Sept.

**Comment by hannahkane** [comment]
I'm moving this to In Progress. @tlasadea - are there any specific action items to work on this week?

**Comment by tlasadea** [comment]
Hey @hannahkane I would leave this in To Do for now - there's a few more bits of the puzzle that need to be completed before I can really start this.

**Comment by tlasadea** [comment]
Alright @caltrider @brettgaylor @hannahkane @lovegushwa @natalieworth @beccaklam it's here: https://docs.google.com/spreadsheets/d/1u21AWY4nhtNg1zJIquzrR6raDilpV-lcp1RpaoGpFhQ/edit#gid=759926306

Still things missing - like need to sync with @KevZawacki re pitching dates for press/press packs due date @brettgaylor when Fusion stuff is likely to go live given suggested launch date.

**Comment by hannahkane** [comment]
Awesome work, @tlasadea. Feel free to close this ticket, if you're confident in the plan. Would it be useful to file individual tickets for the milestones indicated in the spreadsheet?

**Comment by tlasadea** [comment]
Hmm think tickets need to be created for:

1. assets for the BG (fb cover page, twitter header, email headers - if necessary)
2. social content for the BG/campaignable moments (IG template posts, gifs, FB creative, Twitter creative for ads)
3. social content for the IoT survey/snippet creative

And for the milestone dates, maybe create calendar invites and add people to them so they're in our calendars also?
