### ISSUE TITLE
Rapid response

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1005]
I believe this issue is really just kind of a placeholder to indicate that @tlasadea and @caltrider will be looking for opportunities to capitalize on the news of the day and amplify successes

As opportunities arise, specific tickets should be filed.

**Comment by tlasadea** [comment]
The deliverable for this will be to define the process of Rapid Response (overall) for the Advocacy Media team.

Including:

- How do we communicate specifically as a team for RR opportunities? How do we decide/execute the content to publish - e.g. Is there a "template" we use?
- What keywords/topics does Mozilla have authority to respond to, and what tool(s) do we use to listen?
- How do we measure the effect of RR? What metrics do we use?

**Comment by tlasadea** [comment]
@hannahkane think this actually needs to sit in a separate project as it's not just for the safety campaign, but for advocacy media content overall?

**Comment by hannahkane** [comment]
Thanks for creating the new project, @tlasadea. I think this ticket can live in both projects!

**Comment by tlasadea** [comment]
- [ ] Identify process for content creation with design team @lovegushwa @natalieworth @caltrider 
- [x] Create RR slack channel
- [ ] Develop social listening plan

**Comment by tlasadea** [comment]
Quick update - there's been progress on the tiers of rapid response, but i'll share the deck once it's all done and dusted 🙂

**Comment by tlasadea** [comment]
@HPaulJohnson the deck we talked about today is [here](https://docs.google.com/presentation/d/10CNVQIPhz9EDPz9kHokJ-P_-kzON1PEd_5-hGNJj6ec/edit#slide=id.g2421d1ef9c_0_108)

**Comment by HPaulJohnson** [comment]
Let's revisit (and create a fresh ticket) in the new year, in the context of our new OKR's.
