### ISSUE TITLE
Stunty content

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1006]
@lovegushwa and Liz (github handle?) to work together to develop some "stunty content"

**Comment by tlasadea** [comment]
@lovegushwa do you mind if I get involved in this one too!? 😁

**Comment by tlasadea** [comment]
@hannahkane not sure how this ticket differs from the 'campaign-able moments' ticket, and/or what the outcomes are for both?

**Comment by hannahkane** [comment]
Let's close this one, as I'm not sure there is a meaningful difference. Thanks, @tlasadea!
