### ISSUE TITLE
Paid Media Plan

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1007]
Generating a list of websites, podcasts, etc where we can do some paid promotion

**Comment by HPaulJohnson** [comment]
@tlasadea - doing some ticket cleanup/organization. let's use this one to document all of our paid media activity on this campaign.

**Comment by tlasadea** [comment]
Sure @HPaulJohnson. [Here's](https://drive.google.com/open?id=0B7E0hJQDRYkbV29XN19idU5TQ0E) the assets specs for Future Media (T3, Lifehacker, TechRadar). Will update + share the finalised media plan once it comes through.

**Comment by tlasadea** [comment]
This is done. Just wrangling the contract with Future + legal now. @hannahkane
