### ISSUE TITLE
Formalize budget

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1010]

**Comment by hannahkane** [comment]
@brettgaylor - I saw that Paul proposed something. Should this be assigned to you to finalize and get approval on?

**Comment by tlasadea** [comment]
@hannahkane - I have the budget confirmed from Paul for paid media, direct buy & influencers on this spreadsheet: https://docs.google.com/spreadsheets/d/1tVhGr5VOHF6m__fvY0oDrZYJA0kdLwJtH1Lk_73SyEg/edit#gid=541124153 @brettgaylor not sure if makes sense to add the Fusion budget to this so it's all in one place?

**Comment by brettgaylor** [comment]
Thanks, Temi - yes let's add it there. You can find it in the email I forwarded you from Fusion.

**Comment by tlasadea** [comment]
Sweet! This is now completed @hannahkane so feel free to close!
