### ISSUE TITLE
Draft content strategy

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1011]
Should include a plan for:
 * product categories
 * a rating/review system
 * who will provide the reviews
 * guidelines for reviewers

- [ ] Get strategy approved by stakeholders, including Legal

**Comment by hannahkane** [comment]
Per Tuesday media team meeting, our tentative (needs final approval from higher-ups) plan is to produce a holiday guide featuring product reviews (of toys, game systems, fitness trackers, home assistants, smart TVs, and more) written by experts in our network. We will provide guidance to ensure reviews are standardized in terms of what privacy/security-related features they cover.

Additionally, we will provide opportunities for users to ask/answer questions, creating a crowd-sourced knowledge base. 

@caltrider @tlasadea  - does this capture the plan? ^

**Comment by caltrider** [comment]
Hey @hannahkane, yes this captures the gist of it.  We'll put some more flesh on this plan--finalized criteria, fleshed out product list to start with, user journey and UX ideas on the website, advocacy bits--by the end of the week so next week we will have something solid to run by the higher ups (and, gulp, legal) so we can hit the ground running.

**Comment by hannahkane** [comment]
@caltrider - I'm going to close this ticket, as I think we can consider the content plan complete.

Please feel free to file another ticket to track the progress of actually collecting and editing the reviews.
