### ISSUE TITLE
Recruit and manage reviewers staff/network 

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1012]
Dependent upon [Content strategy](#1011)

**Comment by hannahkane** [comment]
@brettgaylor @caltrider - given our focus on editorial partners, do you think we'll still tap staff/network members for the guide, or can we close this?

**Comment by hannahkane** [comment]
ping @caltrider ^

**Comment by hannahkane** [comment]
@caltrider - given the direction we've chosen, this feels like it's going to be important again. Is there a deliverable (or deliverables) we can articulate here? I know you have a vision in mind for how we might tap different folks to play different roles in this project. Can you link to some documentation around how you see us engaging people?

**Comment by caltrider** [comment]
Hey @hannahkane, my vision on this is still a bit blurry. I've got a couple conversations lined up tomorrow to talk to folks about how best to reach into the Network/Fellows for this sort of help.  I should have a better idea after those conversations and then I can get a doc going to make this happen.

**Comment by hannahkane** [comment]
@caltrider - would you say we've resolved this with our decision to work with the ET team?

**Comment by caltrider** [comment]
@hannahkane Yes, I think you can call this resolved.  I'm still talking to people about content they could help us create to help promote the guide.

**Comment by hannahkane** [comment]
OK, closing this then, as it was specifically about the reviews themselves.

@caltrider - Feel free to file tickets representing the work you're doing around promotional content. (and file in the [Buyer's Guide Promotion project](https://github.com/MozillaFoundation/Advocacy/projects/20))
