### ISSUE TITLE
Product research

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1013]
Find products to review!

**Comment by tlasadea** [comment]
@caltrider this was in the webinar I shared

<img width="561" alt="screen shot 2017-08-10 at 12 58 59" src="https://user-images.githubusercontent.com/30296602/29218596-31054a1a-7ead-11e7-9a2f-d662a6a68618.png">
<img width="561" alt="screen shot 2017-08-10 at 13 01 29" src="https://user-images.githubusercontent.com/30296602/29218595-3102cfce-7ead-11e7-94f2-77cc30d3dd49.png">
<img width="560" alt="screen shot 2017-08-10 at 12 51 40" src="https://user-images.githubusercontent.com/30296602/29218628-4dfef508-7ead-11e7-9933-6934aaf32ff8.png">

**Comment by hannahkane** [comment]
Moving this to In Progress, as we're partnering with the Emerging Tech team to build on research they've already started.

**Comment by hannahkane** [comment]
@caltrider - do we have all of the product review content now? Can we close this ticket?

**Comment by caltrider** [comment]
@hannahkane Yes, you can close this
