### ISSUE TITLE
Social media execution for survey

### ISSUE THREAD

**Issue by tlasadea** [MozillaFoundation/Advocacy#1018]
@tlasadea to write 

- [x] social  copy for promotion of survey on Social

- [x] email to Social Champions team for sharing of IoT survey on French, German, Brazilian, and Spanish Mozilla Twitter accounts.

**Comment by tlasadea** [comment]
@caltrider social copy: https://docs.google.com/document/d/12pkTenYbi44PlIqB2UWKrAzgUW8um9iWHMzsVAH0SB4/edit

**Comment by caltrider** [comment]
Thanks Temi. Looks good to me @tlasadea and @TheoChevalier .  And Temi, just double checking you linked out to the social link (https://www.surveygizmo.com/s3/3643927/c53b179d9f5b)?

**Comment by tlasadea** [comment]
Oui I did! I just bit.ly’d it!
〰️
Temi Lasade-Anderson
Social Media Specialist
Mozilla Foundation

slack: temi | twitter: @temilasade

**Comment by tlasadea** [comment]
@caltrider I had ideas re targeting for this incase there was any budget for paid promotion, but wasn't sure?

Think the promotion of the results is probably more exciting/worthwhile, though.

**Comment by tlasadea** [comment]
Brief to social champions is written, just waiting to send it on August 8th once I have @TheoChevalier's go ahead!

**Comment by caltrider** [comment]
@tlasadea Agreed that paid promotion of the results is more exciting.  I'll ask Brett if we have any money for a little paid on the survey.  Could be an interesting test of some small, targeted audiences that we're looking at for the Holiday Buyer's Guide.
