### ISSUE TITLE
World Emoji Day Email Image

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#102]
@natalieworth @lovegushwa 
Can I get an assist on an image for the email going out on 7/17? I need an image of 600 px width of the new emojis that say "Happy World Emoji Day"

Email copy in ticket #61

**Comment by natalieworth** [comment]
hey @stephaniemcv sorry for the delay! have the image here (one at 72 dpi and one @ 2x dpi):
https://drive.google.com/drive/folders/0B20-0lpP23c0b3UzX253bHIydHM
I changed the emoji so let me know if you or @KevZawacki want different ones and I can update tomorrow morning :D

**Comment by natalieworth** [comment]
@stephaniemcv files are also:
03codemoji_email_image_v2.jpg ( 72 dpi/ low res)
04codemoji_email_image_v2@ 2x.jpg (@ 2x or 144 dpi)
