### ISSUE TITLE
Campaignable moments

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1023]
Identify and play for "campaignable moments" - e.g. Black Friday, Cyber Monday, the "schlep"

**Comment by HPaulJohnson** [comment]
We have included 3 main phases in the marketing [plan](https://docs.google.com/document/d/1KbtqKdftHftYmq8x3nmHymOvLgmRRnCAIEFSeeHK_Q4/edit). We will be supplementing this plan with a week-by-week marketing calendar shortly. That work will show up in other tickets so closing this.
