### ISSUE TITLE
Copyright: Share copy

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1024]
We need EN copy variations for the Share feature:
 - [x] Twitter
 - [ ] Facebook
 - [x] email 

Per @TheoChevalier's comment below, we will ask team members and localizers to choose a variant to localize.

**Comment by hannahkane** [comment]
And a question for @ScottDowne - do you know if the script will be pulled from the Call Power API? Asking to better understand what the l10n workflow will be for the script. Will it be done in Pontoon like the rest of the front-end, or will we need to provide localized versions of the script to Call Power?

cc @TheoChevalier

**Comment by Melechuga** [comment]
Hey @hannahkane, I put in comments in the redpen for the call script. I don't know anything about copy for share...do you have insight?

**Comment by ScottDowne** [comment]
Script itself can and should be on our site thus fully localizable using
our normal methods.

**Comment by hannahkane** [comment]
@Melechuga - the copy we need for Share are short post for Twitter, Facebook, and email. So, it's what the user actually shares. e.g. "I just called my MEP to support copyright laws that protect innovation and creativity" or "I just stood up for copyright in the digital age." Each should include a link to the campaign site. [Here's an example](https://docs.google.com/document/d/1qSiHHO3talrhdr2HKI2LSnhazkcqE-1B94O7WA_MHmo/edit) from the last iteration of the copyright campaign (though the CTA was very different).

**Comment by Melechuga** [comment]
Tagging @tlasadea @jonmozilla 

**Links:**

 - [Redpen Design of the Site](https://redpen.io/gc9df697886f255dec)
-  [Site design ticket](https://github.com/MozillaFoundation/Advocacy/issues/1017)
- [Site copy ticket](https://github.com/MozillaFoundation/Advocacy/issues/1024)
- [Localisation Ticket](https://github.com/MozillaFoundation/Advocacy/issues/1028)
- [Current Copyright Site](https://changecopyright.org) (URL where this will live)

**Social needs (Temi):**

- User journey for awareness, civic engagement, and action.
- Copy for user journey.
- Copy for share (a few to test) for Twitter + FB >> collab w/ Jon for the email share.

**Comms needs:**

- Media outreach ( @KevZawacki )
- Email journey (Jon)

**Localisation needs ( @TheoChevalier ):**
- Working w/Federica + Toni to determine which of the socials/emails would resonate best with their communities.

**Questions:**
- @hannahkane : What resources are available for social design?

**Comment by hannahkane** [comment]
@Melechuga - if you don't mind, I'm going to pull some of these things into separate tickets, so this ticket can be specifically about site copy. New tickets coming shortly.

**Comment by hannahkane** [comment]
@tlasadea - changed the scope of this ticket to be about the Share copy specifically (and opened separate tickets for other copy/content-related items), and assigned to you! Let me know if I can help.

**Comment by hannahkane** [comment]
hey @TheoChevalier - I believe our plan is to test a few Share variations in EN using ShareProgress. What do you think is the best path forward for localizing these strings? Should we have all variations localized and ready to go, and then use whichever wins in EN for each of the other languages?

**Comment by tlasadea** [comment]
Hey Hannah - think it's also best to add Jon Lloyd also for ShareProgress tweets. I've never used the
tool before and he's a pro - so would v helpful to have him involved @jonmozilla

**Comment by TheoChevalier** [comment]
> hey @TheoChevalier - I believe our plan is to test a few Share variations in EN using ShareProgress. What do you think is the best path forward for localizing these strings? Should we have all variations localized and ready to go, and then use whichever wins in EN for each of the other languages?

@hannahkane Let’s say we have a few variants in English, the plan is to get them all localized, then:
- For Italian/German: Federica/Toni would pick the one they think would work best
- For French, I would pick it (or maybe Reagan)
- For Spanish/Polish, if localizers don’t have strong opinions, let’s go with what worked best in English

**Comment by hannahkane** [comment]
@TheoChevalier - sounds like a good plan. @Melechuga mentioned that Federica might be able to choose copy for Spanish as well as Italian. Otherwise, this sounds perfect.

@tlasadea will provide copy on Thursday, 24 August.

**Comment by TheoChevalier** [comment]
@hannahkane Roger! 
In wait mode for the copy.
@tlasadea just a note that we should prefer Members of European Parliament over MEPs, not sure how it will look in tweets :/

**Comment by tlasadea** [comment]
Oh :/ we  v limited character space @theochevalier we're gonna have to use
MEPs otherwise there'll be no space for anything else!

**Comment by tlasadea** [comment]
This is done, @hannahkane, can be closed.

[Here](https://docs.google.com/a/mozilla.com/document/d/12m4sc3mfxVHL-lM8_aQlBDhfek6q4WBdcsxAIiximMM/edit?usp=sharing).

**Comment by Melechuga** [comment]
@tlasadea This is awesome! Thanks. One suggestion: can we change where it says "copyright is under threat" to "the internet" or "memes" or "your blog" is under threat? Copyright itself is what we're debating; the outcome of the copyright law will determine the state of the internet. Appreciate it!

**Comment by TheoChevalier** [comment]
If we have more changes, I suggest we group them, German is already done with the current copy…

**Comment by tlasadea** [comment]
I did think that Melissa - but that's pretty much the exact message that
was used for NN, so I think it's too confusing.
Realise we're not debating copyright itself, but that's how much of the
message is being framed on social to separate the two. I also think "memes"
and "your blog" is too vague.

**Comment by Melechuga** [comment]
I'm confused about the parallel with NN; that's a US-based campaign, and this is EU so the audiences are different (though I understand that everyone following our social will see both). I'm fine with not using "memes" or "your blog"; those were just examples. However, in this case, copyright is actually not under threat; the current copyright laws are threatening the internet. Copyright itself is actually thriving and quite strong (^.^) Any other options?

**Comment by tlasadea** [comment]
Oui! This is resolved :)

*Temi Lasade-Anderson*
Social Media Specialist
Mozilla Foundation
Slack: tlasade | Twitter: @temilasade <http://www.twitter.com/temilasade>

**Comment by hannahkane** [comment]
Thanks, all! Closing this, and moving to an implementation ticket.

**Comment by TheoChevalier** [comment]
Just for the record:

Updated actual strings: https://github.com/mozilla/copyright/commit/f75ef476d18c71041d9c707b2c380c4d4c070089

Warned localizers: https://groups.google.com/d/msg/mozilla.dev.l10n.web/pvEGvI-3wxY/U2fx4Ri_AQAJ

Thanks everyone!
