### ISSUE TITLE
Redirect net neutrality pages to blog post

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1025]
We want to re-direct our NN actions to a blog post, once it's ready ( @levjoy to provide the url). This applies to a.m.o/net-neutrality, a.m.o/net-neutrality-comments, and advocacy.mozilla.org/net-neutrality-comments-simple/ (assuming it's no longer needed for the SHIELD experiment).

**Comment by brettgaylor** [comment]
Looping in @levjoy - we can co-ordinate here!

Looks like the FCC has extended the comment deadline till August 30th.  So need to change until then - plan of record at the moment will be to redirect to a blog which will be published August 29th.

**Comment by ScottDowne** [comment]
@hannahkane do we care about this link, or want to coordinate with the people that requested it to see what they want to do with it? advocacy.mozilla.org/net-neutrality-comments-simple/

**Comment by hannahkane** [comment]
@ScottDowne - I'm not aware of that page. Was that coordinated through @caltrider?

**Comment by caltrider** [comment]
Is that the link for the SHIELD experiment @ScottDowne ?  If so, we have a meeting with them tomorrow and I should have a better idea when that experiment will wrap and that simple comment page is no longer needed.

**Comment by hannahkane** [comment]
Per discussion with @levjoy today, we're going back to an earlier version of the plan where we will redirect these pages to a blog post as an interim step between when the comment period ends and when we have a revised version of the sign-on site up and running.

@levjoy - can you please confirm the date you want the redirect to go into effect?

@caltrider - can you please report back about the SHIELD experiment timeline?
