### ISSUE TITLE
Review first round of wireframes

### ISSUE THREAD

**Issue by tlasadea** [MozillaFoundation/Advocacy#1026]
A session to brainstorm the actual format for the guide/campaign site and interactive elements. 

Deliverables - 3 concepts/ideas that the creative team can work with?

**Comment by hannahkane** [comment]
Thanks for filing, @tlasadea! Anything I can do to help? Has this been scheduled?

**Comment by tlasadea** [comment]
@hannahkane it hasn't been scheduled, no. Think it should happen asap though, but there should ideally be some work that is done beforehand so we can use meeting time effectively (like looking for benchmarks & examples of interactive sites that blend content. I'm happy to do this.

**Comment by hannahkane** [comment]
@tlasadea - Would mid-next week be good? Or late next week?

Is this dependent on a final content strategy?

**Comment by tlasadea** [comment]
Hm maybe a tiny bit chicken & egg situation....would be beneficial to have an idea of what's needed for the site, though esp to suss out build times for an end of Oct launch. 
This week a meeting would be ideal to start the conversation based on Jen's draft of the content strategy she finished last week @hannahkane

**Comment by hannahkane** [comment]
Who needs to be there?

**Comment by tlasadea** [comment]
Jen, Jordan and I probably.

*Temi Lasade-Anderson*
Social Media Specialist
Mozilla Foundation
Slack: tlasade | Twitter: @temilasade <http://www.twitter.com/temilasade>

**Comment by hannahkane** [comment]
Per conversation at stand this morning, we likely won't be ready to have this brainstorming session until early next week.

**Comment by tlasadea** [comment]
Hi @jonmozilla @caltrider @natalieworth @beccaklam 

The purpose of this meeting is to get us one step closer to being able to wireframe (or at least a content matrix) for the site 😅.

So there's some pre-meeting work! For Friday's meeting, please can you come with FOUR benchmarks (you don't have to do this @ScottDowne) and add them [here](https://docs.google.com/spreadsheets/d/1ofPYPfvTnNDf8p0HDbPc-OwDGSGvX5UI-q6xpfU1FLw/edit#gid=0): 

- two that are good examples in your opinion
- two that are bad examples (what we should stay away from).

Also, think of any small interactive elements that could be added to the look & feel of the site, not the function of the site (surprise and delight!)

Things to keep in mind when doing the above
1) Our audience is parents *and* people in general, who are: a) excited about Christmas b) Want/need help finding a good gift. It's a fun time. We want to _inform and empower_ people at this stage!
2) Limitations in timing and resource
3) Buyer's Guides can be boring. How can we make ours..Mozilla Advocacy-ish, in the weird, odd and whimsical way that has been done for campaigns/content before?
4) It's on a Friday!! If you don't bring bants/joy/sparkles...smh 😒

CC @hannahkane

**Comment by tlasadea** [comment]
Hey @hannahkane @natalieworth @beccaklam @jonmozilla @caltrider 

I discussed this with Paul and he reminded me that I need to get a brief done for this. Also, he mentioned that we really ought to have everyone in this meeting as it's quite integral, and Rebecca & Natalie will need time after the meeting to come up with some options for design etc. SO-  I propose we move to Tuesday...(or Wednesday after looking at everyone's calendars)

**Comment by tlasadea** [comment]
@hannahkane so this will now be a workshop/review of the designs/wireframes that @beccaklam and @natalieworth come up with after the briefing session today (Tuesday).

**Comment by hannahkane** [comment]
Thanks, @tlasadea. Makes sense to me. I updated the issue title.

**Comment by hannahkane** [comment]
@tlasadea - this isn't scheduled yet, right?

**Comment by tlasadea** [comment]
@hannahkane nope! will do after meeting.

**Comment by tlasadea** [comment]
@hannahkane I've scheduled this on Thursday now.

**Comment by hannahkane** [comment]
Closing, as we did this!
