### ISSUE TITLE
Expose website strings to localizers

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/Advocacy#1028]
Checklist of all the content we need to expose to localizers. Checked items are exposed and localization is ongoing.

Website
- [x] Landing page
- [x] Impact page
- [x] Call Power prompt
- [x] Call script page
- [x] Sharing page

**Comment by hannahkane** [comment]
@Melechuga - good questions about comms assets needed raised above. Do you have a comms plan you can share?

**Comment by TheoChevalier** [comment]
All the strings have been exposed and are being localized, we can call it done.
Tracking progress here https://pontoon.mozilla.org/projects/copyright-campaign/
