### ISSUE TITLE
Callout box graphic for net neutrality fundraising email

### ISSUE THREAD

**Issue by WillatMozFdn** [MozillaFoundation/Advocacy#1029]
Detailed description of work: We need a standard callout-box-size graphic for a Net-Neutrality-themed email we'll be putting together on August 23rd.

Copy for that email is here: https://docs.google.com/document/d/1Z3kQ919WtMbMNYrZQqCgHDnMqjbq4xAMNZH3-RtqmUo/edit

I'm thinking the graphic should say "Donate to help save net neutrality" -- but am open to better suggestions.

I looked over our past NN emails and it looks like we really don't have a "theme" for our callout boxes on this topic?  We've done Ajit Pai with a phone on his ear ... a star wars theme ... a plain gray background for the poll ... and Foxy (who, unfortunately, can't be used for a fundraising message.)  So basically in terms of graphic design for this one, the floor is totally open.

*Start date: August 18, 2017* 
*Due date: August 22, 2017* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @hannahkane @lovegushwa @caltrider

**Comment by hannahkane** [comment]
Will add this to Monday's planning meeting agenda

**Comment by natalieworth** [comment]
Hey @WillatMozFdn I did a couple of different options that I will throw in Redpen here: https://redpen.io/p/wh15c43bf62ae68d36
The first 2 are a bit more conservative, and then the 3rd and 4th (gif) option are based off of some previous NN art direction that Jordan started.

**Comment by natalieworth** [comment]
Here's the gif if it doesn't load in redpen: 
![net-neutrality-callout-v1](https://user-images.githubusercontent.com/14876567/29542067-6df11ab6-868d-11e7-8344-5ec4712b4417.gif)

**Comment by WillatMozFdn** [comment]
Thanks @natalieworth !! I think these are awesome and am still vacillating between conservative and really flashy.  :-)  I also want to loop in @caltrider here as she's working on an different-text version that we're planning to test, and want to get her thoughts on which she thinks will work better with her version of the copy....

**Comment by caltrider** [comment]
Hey @natalieworth and @WillatMozFdn .  These are great.  I'm thinking maybe the non-flashing versions might work better for my version of the email.  Also, I noticed on the static image with the dollar amounts it's $5, $15, $27.  Are those the correct dollar amounts or are we doing $3, $9, $27?  I'll change the copy in my email draft accordingly.

**Comment by natalieworth** [comment]
I'm gonna close this, but re-open if needed.
