### ISSUE TITLE
Investigate how one would manage an rsvp to an event if not signed up

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#103]
Documentation: nothing yet

Sandbox test:

I setup an event: http://makerparty-mozillasandbox.nationbuilder.com/scott2
logged out, cleared cache, and did an rsvp.

I got a confirmation email which also included:

```
If you need to update or cancel your RSVP, use this link:

http://makerparty-mozillasandbox.nationbuilder.com/scott2/test?e=f4e1fb14a446ac62ef485d25084be511
```

The link kinda didn't work on sandbox. But the page still worked. Looked like it also created a cookie for me when I did the rsvp, so I could modify it. Kinda not great. Hoping that's a sandbox thing and it won't be like that in the real thing. We should answer that.

**Comment by damiankay** [comment]
Let's coordinate with @valianttry as she has contacts there.

**Comment by ScottDowne** [comment]
Closing this, as it's covered in #106
