### ISSUE TITLE
Marketing Assets for the Buyer's Guide

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1030]
TBD at a later date, but likely includes:

- fb cover page
- twitter header
- email headers

**Comment by HPaulJohnson** [comment]
updating tix associated with this campaign. let's use this one to track overall progress on deliverables needed to support the [marketing plan](https://docs.google.com/document/d/1KbtqKdftHftYmq8x3nmHymOvLgmRRnCAIEFSeeHK_Q4/edit).

**Comment by tlasadea** [comment]
Outlining list of assets required (TBC):

Update:  this will now be going out in phases, **so for phase 1, we need:**
cc @HPaulJohnson @beccaklam @natalieworth 

- [x] paid social assets across Facebook + Twitter formats - round 1 versions (1)
- [x] display media assets for T3, Lifehacker, TechRadar (2)
- [x] snippet icons (3)
- [x] email/blog toppers (3)
- [x] assets for influencer/media pack - but likely these should be taken/developed from the above. (4)

**For phase 2**, post launch date (mid November) 
- [ ] organic social assets to be used across Facebook + Twitter (1.5)
- [ ] paid social assets across Facebook + Twitter formats - round 2 versions

Also,  not sure if what @hannahkane wrote previously is still required? I'm not sure what the protocol is for campaigns & updating social profile creative, but we may _also_ still require:

- twitter header
- FB cover profile

The brief(s) for 1 + 1.5 are [here](https://drive.google.com/open?id=1A9afkg0XgtwVvTyFXOBxqDLftDFyud9iYNThDx5pkvQ) & [here](http://bugzilla.mozilla.org/show_bug.cgi?id=1403119). The brief for 2 is [here](https://docs.google.com/document/d/1TnYh-W-1Nc8RhrzjLQEyh9g_DyvBGHHfuh6l0J_4F2Q/edit). @HPaulJohnson am I to still brief KFann about no. 2? If so, can send him it today and catch up asynch on Monday. Brief(ings) for 3 + 4 have not yet happened / could be added to 3 or 1.5.

Likely we may need to bring in additional creative resource for ^^?

**Comment by tlasadea** [comment]
Round 1 iterations for social content here, from @natalieworth + @beccaklam 

Paid:https://redpen.io/p/eh2ea97cb47fa31b57
Share: https://redpen.io/p/hqaf796629b6697055

**Comment by tlasadea** [comment]
[Briefs ](https://docs.google.com/document/d/1rBSnmm6ilL6Bb7V2HpwjoRnza7hyN7lGEu6fGk3unbw/edit)for items 3 + 4 (from above).

**Comment by tlasadea** [comment]
Update from today's briefings:

P1 is buyers guide website + styling/branding + illustrations & (MozFest (this week only -ideally @beccaklam will finish on Friday))

Then: P2 is the rest of creative/promo content -
@natalieworth the priority for you is the video idea, then the creepy santa images
@beccaklam the priority for you is the awkward IOT snapshots, then flat lays.

And then assets for the rest, will open tickets for those individually. 
Kevin Fann is working on the display media brief, so resource has been allocated for all assets required above.

CC @hannahkane @HPaulJohnson @caltrider

**Comment by natalieworth** [comment]
Hey @tlasadea , I haven't had time to do anything visual on this yet. I've drafted a super rough outline of possible videos we could create here: https://docs.google.com/a/mozilla.com/spreadsheets/d/1uMXM0NvaYscAzHnFKRYXedN9ShNccWHcvzE2ZCXHWO4/edit?usp=sharing

I also added some links to the Santa style photos in here (that are CC-zero/ attribution) so we could use them on social:
https://docs.google.com/document/d/17qvkSbm6w-66BZiooS8ZQroyhHOGM5xmO95wHV5JMrQ/edit

Going to try and get time later this week to work more on it. Sorry been swamped this week with the site!

cc @beccaklam @HPaulJohnson

**Comment by tlasadea** [comment]
Hey @beccaklam the brief for this is [here](https://docs.google.com/document/d/1TnYh-W-1Nc8RhrzjLQEyh9g_DyvBGHHfuh6l0J_4F2Q/edit?ts=59ef685e) and the specific assets/specs we need is also included, but [here](https://drive.google.com/open?id=0B7E0hJQDRYkbV29XN19idU5TQ0E) is the spec sheet from the publisher.

**Comment by natalieworth** [comment]
Rough/ quick round 1 of social is here: https://redpen.io/p/dnce4b1863e965fe73
cc @tlasadea @HPaulJohnson @beccaklam

**Comment by beccaklam** [comment]
Round 1 Display Ads:

Billboards and Leaderboards: https://redpen.io/p/av7dc6cf725f97edd1
MPUs and DPMUs: https://redpen.io/p/mg42feba60537f1720
Skins: https://redpen.io/p/dt09a812715b68598f

CC: @tlasadea @HPaulJohnson @natalieworth

**Comment by natalieworth** [comment]
@tlasadea Updated the redpen here (V8 onward are latest changes) https://redpen.io/p/dnce4b1863e965fe73
cc @HPaulJohnson @beccaklam

**Comment by tlasadea** [comment]
Hey @HPaulJohnson @beccaklam and @natalieworth (just moving over this comment from the incorrect ticket it was in) here's the round 1 social assets update to final https://redpen.io/p/bseb9ca7649f8f90f4

and cc @ScottDowne as @natalieworth will be making one of these for share progress

**Comment by tlasadea** [comment]
Think this is closed @HPaulJohnson as we have them all bar phase 2, which has it's own ticket 
#1105
