### ISSUE TITLE
Social content for the IoT survey/snippet creative

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1032]
- [ ] Copy
- [ ] Localized copy
- [ ] Design assets

Share survey results via:
 - [ ] blog
 - [ ] social
 - [ ] email
 - [ ] hopefully snippet

**Comment by tlasadea** [comment]
Oui oui mon ami

It does! @caltrider and Vojtech will inform this, as it depends what the
results are/what's exciting & meaty to share.

**Comment by caltrider** [comment]
Hey @hannahkane and @tlasadea .  The survey is out now and will run though Labor Day (Sept 5th here in NA).  After that @vojtechmzl and I will work to pull together the best information we will create for the share out that will happen on blog, social, email (and hopefully snippet).  The goal is to have that share out content ready to go the week of Sept 19th (it might take longer for the localization, but hope to have all the EN versions done and approved and assets created by then).

**Comment by hannahkane** [comment]
Thanks! Updated the first comment, the milestone on this ticket, and the [roadmap](https://mzl.la/advocacy-roadmap) to reflect the deadline.

**Comment by hannahkane** [comment]
Duped by #1065
