### ISSUE TITLE
Social/Comms assets: NN comment period is ending

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1033]
- [x] Social: @tlasadea - will you need any assets for social around the end of the comment period?
- [ ] Email: @WillatMozFdn @levjoy - has the RASCI doc for this email been filed? Is a callout graphic needed?
- [ ] Blog: @levjoy - are any images/graphics needed?

**Comment by hannahkane** [comment]
Note: I'm pulling these items from the Aug-Sept NN action plan, for those who are curious.

**Comment by tlasadea** [comment]
Hey @hannahkane.

Ok so @lovegushwa said we have [these creative assets](https://drive.google.com/drive/folders/0B20-0lpP23c0NVh5MjdUbFJ0MUU) for NN, so we can use this for organic social posts I think. @lovegushwa please let me know if that's not the case!

Alex has already started/ is working on paid ads for the extended comment period, incl targeting the 55 congressional districts that Josh said we *really* need to hear from.

SO I think I just need to write copy for organic social posts!

**Comment by tlasadea** [comment]
Hi @levjoy 

Is there a campaign update? Re social - we focused on FB paid social targeting to congressional districts rather than a generalised blanket push on Twitter. Alex (not on git) will have reporting in a week or so. Is there anything else happening this week/next that we need to be abreast of?

**Comment by tlasadea** [comment]
@hannahkane this can be closed, if another ticket should be opened for 'NN slow down messaging creative?'

**Comment by hannahkane** [comment]
Thanks, @tlasadea. Good suggestion. Closing this, and let's discuss the slow down creative tomorrow (or feel free to file a ticket if you have specifics).
