### ISSUE TITLE
Revise copy on advocacy.m.o/net-neutrality

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1034]
Copy [here](https://docs.google.com/document/d/17uTW9infb5b0UUPHQfztvXKq7LS6sa0mR-Xo_CRdBFs/edit#)

- [x] copy changes, per @levjoy 
- [x] design and layout should match what's currently at /net-neutrality-comments, but form should match what's currently on /net-neutrality
- [x] url should be advocacy.m.o/net-neutrality 
- [x] advocacy.m.o/net-neutrality-comments and advocacy.mozilla.org/net-neutrality-comments-simple should redirect here

**Comment by hannahkane** [comment]
@ScottDowne - copy changes are good to go. Can we please aim to get this up as soon as we can tomorrow (Thursday)?

**Comment by ScottDowne** [comment]
It's live on staging: https://advocacy-mozilla-org-staging.herokuapp.com/en-US/net-neutrality/

And both of these should redirect:

https://advocacy-mozilla-org-staging.herokuapp.com/en-US/net-neutrality-comments/
https://advocacy-mozilla-org-staging.herokuapp.com/en-US/net-neutrality-comments-simple/

**Comment by hannahkane** [comment]
Thank you, @ScottDowne! Super awesome. A few things:

- [x] Please adjust ShareProgress copy, per @levjoy 
- [x] We can remove this field: "I’m okay with Mozilla using my comments for its net neutrality campaign, in accordance with the Mozilla Terms of Service" since we're not accepting comments
- [x] but we should have this field: "I'm okay with Mozilla handling my info as explained in this Privacy Notice"
- [x] We can remove this note: "Note: Mozilla will be filing this document on your behalf via https://www.fcc.gov/ecfs/filings/express into an official FCC proceeding. Per FCC guidelines, the FCC will make all information submitted, including names and addresses, publicly available via the web. Mozilla will otherwise manage your submitted information as explained in our Privacy Notice."
- [x]  we should change the button text to: "Sign our letter"

**Comment by ScottDowne** [comment]
🚀 🚢
