### ISSUE TITLE
Copyright: Metrics

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1035]
cc @vojtechmzl @Melechuga @ScottDowne 

Just want to make sure we're clear on the metrics we need to capture for the next phase of the copyright campaign, which aims to get people to call their MEP to tell them to support copyright laws that promote innovation (I assume this is considered a meaningful action?)

Check out the [Redpen](https://redpen.io/p/tjd37e069720f9308a).

We're using [CallPower](http://callpower.org/) to facilitate the phone calls. @Melechuga - can you provide any insight into what metrics we'll be able to capture from Call Power?

@vojtechmzl - any questions/thoughts about what, if any, additional metrics we should capture? Note: we have an email sign-up on a couple pages, and a Share step at the end of the Call flow.

**Comment by Melechuga** [comment]
Thanks for getting this started @hannahkane 
Per our vendor agreement, CallPower will provide:
- Number of calls placed;
- Number of calls placed from each language version of the Mozilla Site;
- Number of individuals who placed calls (or, number of unique phone numbers);
- Duration of calls (this one will tell us how many connected and spoke).

**Comment by vojtechsedlak** [comment]
Just to update the ticket, we decided to not implement GA on this campaign, in order to honor a request from our EU partners. We will still be able to evaluate the metrics mentioned above.

**Comment by ScottDowne** [comment]
@vojtechmzl so is it safe to say either in this ticket, or another, we should be removing all usage of GA from the front end site?

**Comment by Melechuga** [comment]
@ScottDowne @vojtechmzl Yes. Thanks!

**Comment by hannahkane** [comment]
@vojtechmzl @ScottDowne - can I close this ticket, since GA has been removed? Are there any other TODOs before we launch the site?
