### ISSUE TITLE
Copyright: social needs

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1036]
- [x] Copy for assets for social 
- [x] Copy for snippet
- [ ] Localization of assets
- [x] Design / deliver assets

**Comment by hannahkane** [comment]
cc @Melechuga who listed the above in another ticket, and asked about design resources. Would love to know what @tlasadea wants for social assets, and we'll see if we can accommodate. Ideally, the requests will be fairly limited, since the design team is juggling Safety and NN campaigns as well.

Note: I'm unclear on what copy for the user journey refers to. @Melechuga or @tlasadea - could you clarify? Thanks!

**Comment by Melechuga** [comment]
@hannahkane: these are deliverables that @tlasadea is working on for the campaign, including the user journey, which is the user's journey to taking action via social. Temi is wondering what design resources might be available.

**Comment by tlasadea** [comment]
Hi @hannahkane @melechuga

There's no user journey or user journey copy  for social - that action will
just be content -> driving people to site where they'll decide if they want
to call or not.

The social campaign (ideally) will be split into 3 phases:

Awareness
Consideration (aka Learn More about the 3 audiences - Technologists etc etc)
Conversion - strong messaging asking people to call now.

Resources will be required for creative assets for those three phases - if
possible. If not, they'll just be implemented by slight variations in copy.

I'll add the creative brief for this once I've finished it.

**Comment by tlasadea** [comment]
Hi @hannahkane [here's the brief](https://docs.google.com/document/d/17-zFfLaLWfkHf8AG2Q6BuiL4uI1N18NDU3Xz4yJZZ4c/edit) for creative @natalieworth have a read through but I'll talk through it on the call!

**Comment by hannahkane** [comment]
Assigning @natalieworth to create the six images needed (two per phase) and deliver assets meeting specs for FB, Twitter, and email, per locale.

(Noting there's mention of a snippet above. Is that a thing we need to address, @tlasadea @Melechuga?)

cc @lovegushwa

**Comment by hannahkane** [comment]
Assigning @TheoChevalier to manage translation of copy for social assets, which @tlasadea will provide on Thursday, 24 August.

**Comment by Melechuga** [comment]
@hannahkane Who usually handles Snippet requests? Wouldn't be a bad idea to put it in for our various EU locales...

**Comment by hannahkane** [comment]
@caltrider, please advise! ^

**Comment by TheoChevalier** [comment]
Someone has to get a copy deck ready with snippet copy + icons and pass it to Wes for approval by the Snippet team. Once it’s approved, I can go ahead with localization.
I think they review requests once a week, with the time to get them translated (and the other pieces that are piling up) we won’t have them ready by the 31st. But it shouldn’t be a problem to delay a little bit, I assume

**Comment by Melechuga** [comment]
@TheoChevalier Yea, no problem to delay. If we can line them up now, and get them out in mid-September, we can drive it home with urgency on our side.
@tlasadea Do you have time/space to also draft snippet copy? Let's assume we'll only have 2-3 wks for people to call at that time -- if that fits into the message. If not, don't hesitate to say so; we can get other hands on deck.

Thanks all!!

**Comment by caltrider** [comment]
Hey all, I'm happy to help get things through the snippet approval process with Wes.  @tlasadea , if you want to draft the copy, I can then introduce you to Wes and walk you through this process so you'll understand it. It's not that complicated.  We'll also need to find or create suggested icons for them to use in the snippet.
cc: @Melechuga @TheoChevalier @hannahkane

**Comment by tlasadea** [comment]
@hannahkane 
This will likely be 2 days work, so Friday EOD and Monday for @natalieworth. Totally forgot I was also drafting copy for the designs themselves & adding in amends time & snippet. 

@caltrider re Snippet - sure! Are there any specs (i.e character limits) to know of?

**Comment by TheoChevalier** [comment]
Hey @tlasadea, here some docs from the snippets team that I think will help

Snippet copy/tone guidelines https://docs.google.com/presentation/d/1-rR32aMK60u6EvHvRCyINI0J_KH0_shbD_jbPqF_VUI/edit#slide=id.g163b911a67_2_5 re: length “ the ideal snippet is between 80 and 130 characters. Think of a tweet. Omit needless words.”

General guidelines for snippets https://docs.google.com/document/d/1IwyfInYziHGR6TOGlLpglsoJDjU7Y0bzBuDLF2xA4zU/edit

**Comment by tlasadea** [comment]
@TheoChevalier @hannahkane [all copy for localisation](https://docs.google.com/a/mozilla.com/document/d/12m4sc3mfxVHL-lM8_aQlBDhfek6q4WBdcsxAIiximMM/edit?usp=sharing) (snippet, social, shareprogress)

NOTE no icons yet re snippet

**Comment by hannahkane** [comment]
Reminder: @tlasadea and @natalieworth to tackle this stuff together on Tuesday.

**Comment by TheoChevalier** [comment]
Snippet copy in the approval queue https://bugzilla.mozilla.org/show_bug.cgi?id=1394759

**Comment by hannahkane** [comment]
@natalieworth and @tlasadea - did you two have time to discuss this today? If not...tomorrow?

**Comment by natalieworth** [comment]
@hannahkane We did! Trying to get a start on these this afternoon

**Comment by natalieworth** [comment]
https://redpen.io/p/sf77bce0a6de9f4a2d

cc @hannahkane @tlasadea @TheoChevalier Hey! Got some options for social shares in the redpen link above. @tlasadea if there are any that are working/ you like, then we could translate those?

**Comment by TheoChevalier** [comment]
Thanks @natalieworth! I don’t have much more feedback than what Temi left on Redpen, in particular making the EU flag slightly more visible. But they look great!
Regarding the Paid Social campaign, Tuesday is a hard deadline so we don’t have much time left to translate assets, hand off the translations to you and have a QA check, especially considering Monday is Labor Day. I suggest we use assets without text, and keep the text for English only

**Comment by tlasadea** [comment]
@theochevalier totally on the same page :)

I'm writing paid social copy right now, so you'll be able to send that to
the localisers today.

Thank you!

*Temi Lasade-Anderson*
Social Media Specialist
Mozilla Foundation
Slack: tlasade | Twitter: @temilasade <http://www.twitter.com/temilasade>

**Comment by natalieworth** [comment]
Updated social for tomorrow is in here https://redpen.io/p/sf77bce0a6de9f4a2d
Original working files are here (photoshop and illustrator) if needed while I'm on PTO: https://drive.google.com/drive/folders/0B20-0lpP23c0dm1FUzFoY1R5QU0?usp=sharing

cc @beccaklam @lovegushwa @tlasadea @hannahkane

**Comment by hannahkane** [comment]
@tlasadea - are we good on these? Can we close?

**Comment by tlasadea** [comment]
@hannahkane um almost - but I didn't see any snippet designs in these. @natalieworth did you design these, or did you think the ones from the previous campaign were suitable to be re-used?

Other than that - I need the final design (black telephone on aqua) re-sized to
1200x628. @natalieworth can you do this?

**Comment by tlasadea** [comment]
And also I need the final design (black telephone on aqua) re-sized to
1200x628

*Temi Lasade-Anderson*
Social Media Specialist
Mozilla Foundation
Slack: tlasade | Twitter: @temilasade <http://www.twitter.com/temilasade>

**Comment by natalieworth** [comment]
@tlasadea Got a start on some snippets here https://redpen.io/p/xf129c5c75e2e599b3 Let me know what you think. I've got them in EU colours right now..

**Comment by natalieworth** [comment]
@tlasadea Final snippet icons are here https://drive.google.com/drive/folders/0B20-0lpP23c0RlZhemJ3OGQ5TkE?usp=sharing
cc @hannahkane

**Comment by tlasadea** [comment]
@natalieworth legend. thanks!

**Comment by TheoChevalier** [comment]
The animated gif is a great idea

**Comment by hannahkane** [comment]
Closing, but please re-open if this isn't complete.
