### ISSUE TITLE
Copyright: Comms needs

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1037]
- [x] Media outreach ( @KevZawacki )
- [ ] Email journey ( @jonmozilla )

**Comment by hannahkane** [comment]
@Melechuga or @KevZawacki - can you clarify the deliverables here (pulling this from Melissa's related email and ticket)? Is what's needed a media outreach and email journey plan, or is it specific materials/content?

**Comment by Melechuga** [comment]
@hannahkane This refers to the plan. Kevin and I connected today, and we've decided a blog post about 1-2 weeks from the vote (10 Oct) including a quote from Raegan would be fine.

The email journey is the plan + content that Jon will be creating to send out to our EU-based email community. Neither of these require design/dev resources.

**Comment by TheoChevalier** [comment]
@Melechuga We will localize the email, but what about the blog post? If it’s only targeting press are we good with English only? I assume it won’t be linked from the email

**Comment by KevZawacki** [comment]
@TheoChevalier @Melechuga 

I'd really like to localize the blog post if possible, ideally into DE, FR and ES. Having localization versions greatly increases our chances of press pick-up.

**Comment by TheoChevalier** [comment]
@KevZawacki Sounds good, Kevin. Do you know if we can get this through Mozilla Press Center, like we did for Paperstorm? https://blog.mozilla.org/press-fr/2017/05/09/paperstorm-des-flyers-pour-venir-en-aide-a-la-legislation-europeenne-sur-le-droit-dauteur/
I’m not sure what’s the process

**Comment by KevZawacki** [comment]
@TheoChevalier Yep, I can ensure it's published on all relevant press centers.

**Comment by TheoChevalier** [comment]
Awesome, thanks Kevin! That will greatly help getting the other pieces localized on time.
@jonmozilla You can copy this template for the email, should help getting all the pieces together https://docs.google.com/document/d/1aEzfTaqUPbzA4kwnIIcfGNT2FOTf9msp0c1JNk8pw3g/edit
For the locales, I would go with DE, FR, ES, IT, PL

IT is ~500 people, but I think this is a typical case where reaching few but engaged people is worth our (and volunteers) time, since it could lead to “high quality calls” @WillatMozFdn Do you agree or should we skip it?

**Comment by Melechuga** [comment]
@TheoChevalier Yea, IT would be great. I think we should try to do everything in the 6 languages (DE, FR, ES, IT, PL and of course EN). Thanks!

**Comment by KevZawacki** [comment]
@hannahkane Communications plan is **[here](https://docs.google.com/document/d/1tqxTbQisinH4gp2y5z3PkQ5QED82v3Deznh3g_zyVsY/edit#)**; I've asked @Melechuga and Raegan to weigh in.

**Comment by KevZawacki** [comment]
Hi @TheoChevalier,

Our copyright blog has been approved by Melissa and Raegan. You can find the final version [here](https://docs.google.com/document/d/14-3s2zjtBB42vpzcjdB-_R0T3e1Cx__548Ata8xQitQ/edit).

Are we able localize into French, German, Spanish, Italian and Polish this week?

**Comment by TheoChevalier** [comment]
@KevZawacki Hm, I think there’s been a misunderstanding, I was asking above if we could use the Mozilla Press Center agency to localize the blog post, like we did for Paperstorm, but I don’t know what’s the process

**Comment by KevZawacki** [comment]
@TheoChevalier Oh, I see. It is unlikely MoCo's agencies will be able to localize the blog for us, unfortunately. Perhaps we can prioritize 2 languages for our volunteers?

**Comment by TheoChevalier** [comment]
Alright, I’ve sent the copy to everyone, and suggested to get it localized if they have time. I will jump in to get at lest French this weekend if no one starts in French team

**Comment by KevZawacki** [comment]
Thank you, @TheoChevalier.

**Comment by KevZawacki** [comment]
Hi @TheoChevalier, checking in briefly: Do you know what localized blog versions we'll have ready by Tuesday, Sept. 5?

**Comment by TheoChevalier** [comment]
@KevZawacki German is ready, French will be for sure.
We should get Polish too, but nothing sure.
Italian: probably yes
Spanish: probably no
I will update this ticket as I get translations

**Comment by KevZawacki** [comment]
@TheoChevalier Excellent! Thank you, Theo. 

If it's possible to share the final localized versions on Monday evening, that works best. Then MoCo's agencies can publish them first-thing Tuesday morning.

**Comment by TheoChevalier** [comment]
Sounds good, anyone in particular I should send those to, or just you?

**Comment by KevZawacki** [comment]
@TheoChevalier Just me is fine.

**Comment by hannahkane** [comment]
@KevZawacki - is this work all done? Should we close?

**Comment by KevZawacki** [comment]
Yep! [Here's the media coverage](https://docs.google.com/spreadsheets/d/18lV3jXKh9fv-ZWNrcjwZKt0IDLgh3wOlDkj_S2z7uzM/edit#gid=0).
