### ISSUE TITLE
Refine approval process for emails

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#104]
Objective: define a clear process for QA reviews and approvals for emails, snippet copy, + other copy assets.

**Comment by damiankay** [comment]
@valianttry you can see our initial draft here: https://docs.google.com/document/d/1s8Ru5bOZf-i00v3fehjgpGfjRwdqyJm5kGX5rasvKCo/

Feel free to add any feedback you may have to the document. Stephanie and I can take another go at refining and making edits.

**Comment by shaghdoosti** [comment]
Just a question here - is this in reference to all emails? MP emails? Copyright emails? Do we mean approvals ie (policy/legal) or do we mean QA?

**Comment by damiankay** [comment]
Damian to update documentation and share by July 29

**Comment by shaghdoosti** [comment]
This is out of date but could be useful: https://docs.google.com/document/d/1qkvVTxcp0-md4_ACNUXJZWXhbqT-Rq5d6Jha7RG6Z0A/edit

**Comment by stephaniemcv** [comment]
Good questions/thoughts @shaghdoosti

I was working off building a general process for all emails with specific details to be filled out based on individual campaigns.

And I agree, we should define and separate an approvals (policy/legal) round/group and a QA round/group.

**Comment by valianttry** [comment]
@stephaniemcv can you update the milestone on this one?

**Comment by Matt-Holland** [comment]
We now do have an approval process for EOY emails, and the new digital director will no doubt want to make her own. Closing this ticket.
