### ISSUE TITLE
Safety: Evaluate off-the-shelf tools for user reviews/ratings

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1040]
Let's research and evaluate off-the-shelf tools we can integrate into the Buyer's Guide to allow users to add their subjective comments via reviews and/or ratings.

Perhaps we could consider a few options, and weigh the pros and cons as they relate to:
 - Product design (e.g. features, usability, mobile-friendliness)
 - Tech specs (e.g. ease of integration, security and vendor review)
 - Cost
 - Values (e.g. open source—ideal, but I suspect we're highly unlikely to find something)

**Comment by hannahkane** [comment]
@caltrider @tlasadea @lovegushwa @beccaklam @natalieworth @ScottDowne - do these seem like the right things to be evaluating? What would you add?

**Comment by hannahkane** [comment]
Some tools to look at:
 - [Yotpo](https://www.yotpo.com/lp/better-results/)
- Coral Project's [Ask](https://coralproject.net/products/ask.html)
- [Get Satisfaction](https://getsatisfaction.com/corp/)
- [Typeform](https://www.typeform.com/)

Please add others

**Comment by caltrider** [comment]
Thank you for leading this @hannahkane.  It would be amazing to be able to use the Coral Project's tools, wouldn't it.  Would save on security reviews and things like that.  Could we set up a time next week to meet and work through these and pick the best solution to start moving forward?

**Comment by hannahkane** [comment]
Send an invite.

**Comment by hannahkane** [comment]
Sorry, I meant that I just sent an invite. It wasn't an imperative. :)

**Comment by tlasadea** [comment]
Hmm - I hope this is the right place to voice these, but I have concerns about this approach, largely:

- Asking people to review products on sites where they don't purchase them isn't user behaviour. This occurs usually where people buy the products

- Previous experiences tells me it will be difficult to get cut through with this approach during the holiday period (it's really just too big of an ask)

- It perhaps makes more sense for me for this to be pre-populated when the BG launches, ideally from the Network (and influencers?) so the gen. public have things to read while making purchase decisions.

**Comment by hannahkane** [comment]
Closing, per earlier discussion with @caltrider and @tlasadea. In lieu of this, will open a ticket about allowing users to leave comments/questions on product pages.
