### ISSUE TITLE
QA: phone number field default text gets cut off

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1042]
Happens in a few languages:
![screen shot 2017-08-28 at 4 34 28 pm](https://user-images.githubusercontent.com/8389648/29797941-dc72166c-8c0e-11e7-8b7f-f012e6234e74.png)

**Comment by hannahkane** [comment]
@ScottDowne - should I assign these to you?

**Comment by ScottDowne** [comment]
Should be good now.
