### ISSUE TITLE
QA: broken "Learn more" links missing on homepage

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1045]
Each of the three sections under "How will this impact me?" have a "Learn more" link that should go to the appropriate anchor link on the Impact page

**Comment by ScottDowne** [comment]
You mean the "For more detail, read LIBER’s explanation (in English)." like links?

I'm not sure where they are supposed to go, actually.

**Comment by ScottDowne** [comment]
If this is covered in https://github.com/MozillaFoundation/Advocacy/issues/1049, I'm happy to close this one.

**Comment by ScottDowne** [comment]
Oh, these are the links in the home page, not the impact page.

I got it! (and missed that bit in the issue title)

**Comment by ScottDowne** [comment]
Building on staging now. Closing.
