### ISSUE TITLE
Copyright: country list

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/Advocacy#1046]
Let’s make sure where we’re sending comms in each language. This would be for emailing, paid social and snippets.

Here’s what I’m assuming:
en: UK
fr: France
de: Germany
it: Italy
pl: Poland
es: Spain

So, only targeting MEPs’ countries.

For emails we don’t always have the country info, so we may want to do as usual? @WillatMozFdn

CC: @tlasadea

**Comment by WillatMozFdn** [comment]
Are we targeting only the countries with a representative on the JURI Committee?  That seems to be the most logical.

Someone (like @jonmozilla who I think is Jon Lloyd?) should double-check me on this to see if it's still current, but a few months ago I did a list of those countries -- that's here: https://docs.google.com/spreadsheets/d/1MUssSqnuh3uMj7dIga8MDF2Qgq0XfVg5gZ1C-jXD8QE/edit#gid=0 (the numbers are probably a bit out of date at this point, but that doesn't really matter.

So, we would publish in those six languages, to those 16 countries, according to the language and country info that we have on file.

**Comment by jonmozilla** [comment]
Checked and added substitute member countries as well.

**Comment by Melechuga** [comment]
@WillatMozFdn @jonmozilla 
No, we are not doing this by member country -- it doesn't matter which MEP the citizens speak to, as this committee is meant to balance out the representation of the political parties of the EU, not the countries. Users will decide who they speak to dependent on language that the MEPs speak -- we chose these 6 languages, as they are spoken in the most influential countries in the committee. 

So email send wise, we should send this to everyone who put:
- English
- German
- French,
- Italian,
- Spanish, or 
- Polish 

as their preferred language. Does that make sense? Happy to clarify further if needed.

**Comment by hannahkane** [comment]
I'm a bit confused by this ticket. Do we need any more information? Can we close?

**Comment by TheoChevalier** [comment]
We can close! Thanks for the clarification on countries
