### ISSUE TITLE
Copyright: when switching languages, the new language is not kept when opening some links

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/Advocacy#1047]
Let’s say I’m using an English browser but feel more confident to speak in French.
- I use the language switcher to get the homepage in French.
- I click on Call Now from the nav menu

Actual: I’m redirected to https://changecopyright-org-staging.herokuapp.com/en-US/call-now

Expected: I’m accessing to https://changecopyright-org-staging.herokuapp.com/fr/call-now

This is because some internal links don’t contain the current locale code, so we’re doing the language negotiation again.
Let’s add the locale code to all internal links, like in the CALL NOW button.
But let’s not touch external links like https://www.mozilla.org/privacy/websites/

**Comment by ScottDowne** [comment]
Fixed in https://github.com/mozilla/copyright/pull/116
