### ISSUE TITLE
QA: Impact page

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1049]
- [x] "technologist" "creator/innovator" and "scientist/librarian" sections should link to the respective sections
- [x] None of the "For more detail..." links go to the appropriate site
- [x] Under the Creator/Innovator section, the "For more detail..." link says "For more details..." -- should not have the s.
- [ ] In one of the design mockups, there was a comment about making the questions "What does this mean?" and "What are we fighting for?" bold or in someway more visibly catchy; is this still the case? At the very least, if we could bold them that would be helpful.

**Comment by ScottDowne** [comment]
@hannahkane do we know where the "for more details" on the impact page are supposed to link to?

**Comment by hannahkane** [comment]
Article 11: http://copyright4creativity.eu/wp-content/uploads/2017/01/DCDSM-Article11-C4CFactsheet.pdf

Article 13: http://copyright4creativity.eu/wp-content/uploads/2016/12/DCDSM-Article13-C4CFactsheet.pdf

Communia's analysis on UGC: http://www.communia-association.org/2017/06/15/keeping-eye-fine-print-ugc-exception-juri-committee/

Liber's explanation: http://libereurope.eu/text-data-mining/

**Comment by hannahkane** [comment]
Closing this. Will file non-blocking remaining issue as a separate ticket.
