### ISSUE TITLE
World Emoji Day Email Reivew

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#105]
Please review the email copy, test the links and note any feedback in this ticket.
Audience: Remaining engaged list who has NOT gotten either of the 2 previous Codemoji emails ~700,000

**Comment by valianttry** [comment]
I have no copy writing edits. +1 from me.

Real talk tho: There will be a few days between the Nice attack in France and this email campaign, but (help us) if there is another attack, how easily is it for us to put on the breaks @stephaniemcv ? With these "lighter fun" type of emails, we really need to keep on top of a launch moment that could be interpreted as "tone deaf" in light of a major attack or other moment where the world is witness to something awful.

**Comment by HPaulJohnson** [comment]
Reviewed and no comments/edits on email. 

+1 to @valianttry's comments and keeping a close eye on what happens in the next 48-hours given the lighter tone of this communication.

**Comment by stephaniemcv** [comment]
I will do some digging, I am unsure if there is an alert system for scheduled emails. I do know SFMC is has released/is releasing some new capabilities. 
-Email recall
-Mobile App that lets you see even scheduled emails (IOS is out, Android is coming this fall)

Because of events, I'm willing to not put the email on auto pilot and just do a manual send on Sunday.

**Comment by damiankay** [comment]
@stephaniemcv this might be too nitpicky, but should there be some padding between "Connect with us" and the white div above? Otherwise looks great. 
![screen shot 2016-07-15 at 11 10 36 am](https://cloud.githubusercontent.com/assets/19785709/16884302/785708a0-4a7d-11e6-8325-451ff0737f6d.png)

**Comment by stephaniemcv** [comment]
@damiankay Super easy fix!

**Comment by valianttry** [comment]
@damiankay, nit picky is SO GOOD. LIKE, DO NOT APOLOGIZE FOR DOING AWESOME QA EVER AGAIN. ?? 

![nitpicky](https://cloud.githubusercontent.com/assets/9830371/16885111/df371336-4a81-11e6-995e-2cab026697ad.jpg)

[--- Commented from Asana.com
#commenter Damian Kuehn
---[aa]

**Comment by damiankay** [comment]
Yes master Yoda! ??

[--- Commented from Asana.com
#commenter Damian Kuehn
---[aa]

**Comment by damiankay** [comment]
Assuming this one is done - please reopen if I'm mistaken!
