### ISSUE TITLE
Holiday Buyers Guide website: allow people to ask/answer questions

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1050]
Goals: provide a forum for people who may be new to the issue of privacy/security to ask questions of others; allow community members to share their knowledge/insights about products and the issue of privacy/security overall

Requirements:
- if we use a third-party tool, must pass our security and vendor reviews
- must be available in EN/ES
- must allow for threaded conversations
- must have basic moderation tools, ideally with user upvote/downvote, and ability to give certain users moderator privileges
- must be able to embed specific topics/threads onto product pages

To consider:
- Discourse
- Coral tools ?
- What else ?

**Comment by hannahkane** [comment]
@caltrider @tlasadea  - does this capture what we discussed? Any goals/requirements to add?

**Comment by caltrider** [comment]
Yes @hannahkane, those requirements look good to me.  Thanks!

**Comment by hannahkane** [comment]
Background for @cadecairos @alanmoo and @ScottDowne:

The Advocacy team is working on an online Holiday Buyer's Guide which will feature product reviews written through the lens of privacy and security. We don't have a mockup of what the Guide will look like yet, but we imagine that there will be separate pages for each product. We're wanting to include some kind of threaded comments forum on each product page, where users can post comments and questions about the specific product. See first comment in this ticket for feature requirements.

We are aiming to build the website in early October, and have it ready for a beta release Nov 1.

I'm wondering if there's a tool we already use—one that has already passed vendor/security review—that could meet our requirements. I'm thinking specifically of Discourse, but perhaps there are other forum/threaded comment tools we could use. (I know Discourse doesn't have the upvote/downvote feature, but perhaps the favorite feature would be adequate.)

Questions for the three of you?
- Do you have any suggestions for what tools we should investigate? 
- Any concerns or requirements to add to the list?
- What role would each of you like to play in this decision? (acceptable answers range from "None" all the way to "Please let me be the decider" :))

**Comment by alanmoo** [comment]
@LeoMcA are these things Discourse can do for us?

@hannahkane:
It sounds a lot like Disqus does what we need, but I have no idea what the implications of using that are and frankly I'm afraid to ask unless we already happen to have it approved. If Discourse can come close enough, I think that'd be the best solution simply so we don't have to get stuck in approval limbo.
As for decision-making: I'll voice my opinion if I see something going down a bad path but otherwise will probably just back whatever @ScottDowne thinks.

**Comment by LeoMcA** [comment]
> @LeoMcA are these things Discourse can do for us?

>    if we use a third-party tool, must pass our security and vendor reviews

✔️ 

>    must be available in EN/ES

✔️ 

>    must allow for threaded conversations

Discourse uses a flat format, with posts shown chronologically. A single level of threading is, in effect, possible: [see "Simple, but with context"](https://www.discourse.org/features).

>    must have basic moderation tools, including user upvote/downvote,

@hannahkane as you already mentioned, Discourse doesn't have upvote/downvote, but does have likes. As a downvote equivalent, uses can flag a post which is spam/offensive/etc. which is then hidden once a flag threshold is reached, if a moderator hasn't dealt with it before then.

Discourse doesn't, however, support reordering the post stream based on likes.

> and ability to give certain users moderator privileges

✔️

>    must be able to embed specific topics/threads onto product pages

✔️ but users go to Discourse to comment. You can see this feature in action [on Coding Horror's blog](https://blog.codinghorror.com/welcome-to-the-internet-of-compromised-things/#discourse-comments).

**Comment by alanmoo** [comment]
Thanks, Leo. 

@hannahkane, I think that even with these small shortcomings it's incredibly valuable to have everything in one spot- it's a good way for curious visitors to be able to discover what else Mozilla is doing, instead of being a silo'ed advocacy campaign.

**Comment by ScottDowne** [comment]
Who would be best to supply the same sort of info for Coral tools? Is this something we think can come close to Discourse? And what about Disqus? Could it come close? @alanmoo do you have any experience with Disqus?

I'm leaning towards Discourse. It's very much the bar to beat at the moment. Vendor review being done is HUGE.

**Comment by alanmoo** [comment]
I have no dev experience with Disqus, which is why I hesitate to suggest it as a real possibility; It merely feels from a user standpoint like it'd fit our needs. Having slept on it, I'm feeling rather strongly about Discourse.

@losowsky Would you be able to chime in with thoughts on if Coral's tools might be able to meet the needs laid out by Hannah in her first and third post of this thread?

**Comment by ScottDowne** [comment]
I think my experience tells me the important questions to ask for each potential product is.
1. Does it have the features we need?
2. Has it gone through vendor review?
3. Has anyone we know used it, and would they use it again?

It looks like Coral might have 2 and 3 covered, given it's a mozilla project. Does it have the features we need?

It looks like Discourse has 1 and 2, but my guess given that it's gone through 2, it means someone has used it, so we should talk with them.

No info on Disqus, but I think we should give it a shot too.

**Comment by losowsky** [comment]
Hi all!

Coral's Talk platform might have what you need.

1. Our features: 

- We don't have downvote, as there is indicatory evidence that downvotes can increase poor behavior and mobbing (there's a new study being conducted on this using Reddit right now, but I digress). However, you can build any reaction plugin you want. We currently have plugins for Like, Love, and Respect. We also allow users to sort by 'Most loved' etc.
- We have threaded comments for as many levels as you want. We use 4 levels on our blog, the Washington Post has gone for 5.
- We have multilingual capabilities, and an easy flow for adding new languages
- We have moderator and other roles
- "must be able to embed specific topics/threads onto product pages" - not sure what this is. If it's simply "a new comment space on each page" then we have it. 

2. We've completed an RRA and basic security review.

3. We use it on our blog :D It's in use on The Washington Post, The Brisbane Times, O Estado de Sao Paulo with more to come soon.

Thanks for thinking of us, and any questions, let me know!

**Comment by caltrider** [comment]
Thank you @losowsky @alanmoo @ScottDowne @hannahkane for the great information.  I'd love to dig into Coral's Talk platform more as it sounds great and would love to jump on the bandwagon.  @ScottDowne, if you have time to dig into it more, I'd love your thoughts on using it for this project.

**Comment by losowsky** [comment]
Sure thing! Let me know when you'd like a demo. Ping me on Slack!

**Comment by hannahkane** [comment]
@caltrider - @natalieworth @beccaklam @ScottDowne and I got a great demo from Andrew yesterday. I think Talk will meet all of our requirements, so if you'd like to go forward, we likely can. (I think it will be a p2 in that we wouldn't start this part until we've built out the rest of the functionality.)

We need some clarity from you on how the comments should be framed. For example, should it be set up as a generic comments forum on each product page (I imagine people would use that to, for example, leave their own personal reviews of the product), or do we want to set it up more as a "Ask a question and one of our experts will reply" kind of thing. If the latter, we should discuss how we're going to manage that - e.g. seeding with some questions, ensuring we have experts on hand to provide answers, etc.

**Comment by ScottDowne** [comment]
I set this up locally to see what kinds of issues I'll hit.

This is roughly what the default looks like

![coral-talk](https://user-images.githubusercontent.com/197334/31564029-6e0bfa22-b02f-11e7-911d-6079836c1cfc.png)

Next step is likely to get this setup: https://github.com/MozillaFoundation/mofo-devops/issues/551

Once that's setup I can go through the steps I did today to integrate with the prod instance.

My advice is we roll with the default look given this is a p2, but if by the end everything is working and we have time to fidget with it, we can do some style stuff.

We'll also need people experienced with this service to moderate comments.

I think it makes sense if I build in an easy way to turn this one and off.

**Comment by cadecairos** [comment]
Lucie and I will prepare a deployment plan next week, and get it running.

**Comment by hannahkane** [comment]
@ScottDowne @cadecairos  - can we close this, or is there more work to do?

**Comment by cadecairos** [comment]
I've set up a talk instance, but we need to tweak some of the configuration settings for our needs.

**Comment by ScottDowne** [comment]
Talk instance has been integration, but I havn't figured out any of the plugins or configs we may want. Keeping open in case we decide to do that.

**Comment by hannahkane** [comment]
Does #1099 cover the above, @ScottDowne?

**Comment by HPaulJohnson** [comment]
we did this- yay!
