### ISSUE TITLE
Copyright: share icons are black on Safari iOS

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/Advocacy#1051]
Safari, iOS 10.3.3 (Works fine in Firefox for iOS)

![img_1418](https://user-images.githubusercontent.com/1294206/29973327-1913981e-8f27-11e7-9949-3303df2860b6.PNG)

**Comment by hannahkane** [comment]
Good eye. Thanks! Assigning to @ScottDowne

**Comment by ScottDowne** [comment]
Having a hard time reproducing.

**Comment by hannahkane** [comment]
I can't reproduce either.

**Comment by ScottDowne** [comment]
@TheoChevalier mind trying again? I suspect maybe it was a cache issue around the stylesheet or maybe the font itself?

Also, does this work for you? https://changecopyright.org/en-US/share It's basically the same thing.

**Comment by TheoChevalier** [comment]
Hm, doesn’t work here either :/

**Comment by TheoChevalier** [comment]
Not sure how I can help debugging

**Comment by TheoChevalier** [comment]
LOL ok, I’ve found what that was… I’ve enabled Focus blocking for Safari…

**Comment by ScottDowne** [comment]
focus blocking? *googles*

**Comment by TheoChevalier** [comment]
I mean, tracking protection from Firefox Focus

**Comment by TheoChevalier** [comment]
And I had “Block web fonts” enabled, that was the offender. Didn’t actually realize that was on, because I just played with it to QA French translations. Ok, we should be safe to close this issue! Sorry about that
