### ISSUE TITLE
Test videos on donate page

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1053]
To consider:

Could we test the effect of having videos on the Donate page? As discussed with @WillatMozFdn, we might have a control video featuring Mark Surman as a talking head, drawing on existing footage we have of him speaking about the Foundation's work and/or internet health, as well as another, less traditional video (perhaps similar in style to the pop culture-y Safety First videos)? The message of both should simply be calling attention to the many projects and initiatives the nonprofit Foundation works on.

Let's discuss early next week, though testing of this video wouldn't happen until late September.

**Comment by WillatMozFdn** [comment]
Update ... I chatted with Lotta on Friday and she's open to having Mark do something custom for us for the "control" version.  I'll develop a script outline this week and then let her & Mark polish up to something that sounds natural for him.

**Comment by hannahkane** [comment]
Thanks for the update. Did you discuss who would produce the videoshoot?

**Comment by hannahkane** [comment]
Next step here (I believe) was for @HPaulJohnson or @brettgaylor to schedule a briefing with @natalieworth and potentially @caltrider

**Comment by WillatMozFdn** [comment]
Thanks @hannahkane !  Also just wanted to throw this doc into the mix to give a general sense of the "control" version of the video ... I wrote it as a script just to give a general sense of the flow, but there is absolutely no need to stick to "the script" -- it's really just a braindump.  https://docs.google.com/document/d/1tVD7y2u9WHKVJ2c76aL0qpbaAWQ68gIJEPQFqpix5wk/edit

**Comment by gideonthomas** [comment]
do we have any progress updates on this?

**Comment by alanmoo** [comment]
Work is being tracked in #1082
