### ISSUE TITLE
Add Mozilla copyright video

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#1054]
Lets add a link to this video on youtube:
https://www.youtube.com/watch?v=Exc9PAXhOd0

Title: A Meme is born
Learn how outdate copyright laws threaten online creativity
by: Mozilla

It looks like these "learn more" pages aren't localized, so not sure if translation required cc @TheoChevalier 

Lets make this the first entry in "watch"

**Comment by TheoChevalier** [comment]
Hey @brettgaylor which website/pages are we talking about?

**Comment by brettgaylor** [comment]
Oops!

Copyright website. The "more resources" section.

**Comment by TheoChevalier** [comment]
Oh, ok :) Yeah this page https://www.changecopyright.org/en-US/resources is hidden in other languages than English

**Comment by ScottDowne** [comment]
Fix should be on prod soon.

**Comment by ScottDowne** [comment]
Fixed: https://changecopyright.org/en-US/resources closing.
