### ISSUE TITLE
Provide useful error messages

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1055]
UPDATED Sept 12:

We need to serve up a couple of specific, useful error messages.
429 message: "Thanks for your calls! You've reached the hourly limit. Please try again in an hour."
400 message: "We can't call that number. Please choose a country code from the list."

**Comment by ScottDowne** [comment]
@Pomax You think just limiting this on the client is enough?

Would be easy to just limit it to number with area codes, but I don't know if that's the right approach.

A safer way, if possible, might be to get a usable error back from callpower telling us if and why the number was rejected.

**Comment by Pomax** [comment]
We can quite easily say "hey you need to pick a country code from that country picker, you haven't done that or you're using a non-EU number which isn't supported", which automatically gives us a whitelisted number.

**Comment by ScottDowne** [comment]
So yeah, I take that as doing this client side is probably acceptable.

**Comment by Pomax** [comment]
I would say so.

**Comment by hannahkane** [comment]
From Josh in Slack:

at the moment CallPower will return an error like this:
```
{
  "description": "Unable to create record: Account not authorized to call +38970139220. Perhaps you need to enable some international permissions: https://www.twilio.com/user/account/settings/international", 
  "error": "Bad Request", 
  "status": 400
}
```

it would be up to the frontend site to detect that and display a friendlier message

if a number tries to call that’s been specifically blocked (not just the entire country code) a different error will be returned:
```
{
  "description": {
    "kthx": "bai"
  }, 
  "error": "Too Many Requests", 
  "status": 429
}
```

My (Hannah) original error message copy was wrong. It's not that the user can't call from outside the EU; it's that we've blocked some countries. So perhaps more accurate to say, "We can't call that number. Please choose a country code from the list." (As Pomax suggested.)

**Comment by Pomax** [comment]
ah, in that case the server will need to deal with the 400 and 429 errors, hand something sensible back to the client, and have the client show that to the user. This will probably require new strings. That said, "too many people in your region called your MEP already" seems... unacceptable? That's the whole point of the campaign >_> 

Is this rate limiting for "from a single number" or "to a single number"?

**Comment by hannahkane** [comment]
My understanding of the rate limit is that it's per user. So, a single user cannot call more than twice in an hour, but an MEP can receive many calls in an hour.

So, I think the 429 message is something like, "Thanks for your calls! You've reached the hourly limit. Please try again in an hour."

**Comment by hannahkane** [comment]
Updated original comment to reflect what I think is the correct ask.

**Comment by Pomax** [comment]
@TheoChevalier would you be able to recommend keys for these two new messages?

**Comment by Pomax** [comment]
@TheoChevalier I've written code atm that uses the keys `hourly_limit_reached` and `we_cannot_call`, let me know if those feel off to you.

https://github.com/mozilla/copyright/pull/139/files#diff-7e4736ba3d554e4ab112aae52fcde494

**Comment by Pomax** [comment]
The PR has landed, but it won't "look good" until the locale strings have been committed too =)

**Comment by hannahkane** [comment]
@TheoChevalier - did the locale strings get committed? Can we close this ticket?

**Comment by TheoChevalier** [comment]
Yup, all good!
