### ISSUE TITLE
Create Social Assets for Net Neutrality/Paperstorm Launch

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#1056]
Detailed description of work: For Paperstorm launch, create ~5 images/.gif/screengrabs for promotion on social 

*Start date: September 13, 2016* 
*Due date: September 18, 2016* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:
@beccaklam @tlasadea

**Comment by HPaulJohnson** [comment]
Draft copy here: 
https://docs.google.com/spreadsheets/d/122mcF0eIGzdutrGY8Y9v9ZcEL-In1QUfdCGQNvIxNxQ/edit#gid=265127269

**Comment by hannahkane** [comment]
@beccaklam - are we done with this? Can we close?

**Comment by beccaklam** [comment]
@hannahkane Should be done!
