### ISSUE TITLE
Add business hours logic to copyright call tool 

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1058]
Two problems to solve:
- Users who call outside of normal business hours will not be connected to MEP—not a great user experience
- We get charged for the call, even if the caller doesn't get to speak with anyone

Proposed solution:
- [ ] Add a new first step to the "Here's how to make the call" description on the call page: "Step 1: Please note, the call tool is only available between the hours of 9:00-18:00 CEST." (change numbering on other steps accordingly)
- [ ] Add front-end logic that replaces the form with the phone number field with a message, during non-business hours: "Please visit this page between 9:00-18:00 CEST to access the calling tool."
- [ ] Localize the above

**Comment by hannahkane** [comment]
@melechuga - you ok with the copy and suggestions above? Do we need to specify Monday through Friday?

cc @TheoChevalier

**Comment by Melechuga** [comment]
@hannahkane 
I like the idea of putting it as step 1. I was also thinking we could put "Please note, calling is only available during business hours (Monday-Friday, 9:00-18:00 CEST.)" it right in the call box, and gray-out the "call now" button. 

If we just want to add text (i.e. no logic), then adding that line right below the "Enter your phone number and get a call back immediately" could work.

Does that sound ok?

**Comment by ScottDowne** [comment]
@TheoChevalier mind taking a look at this pull request? https://github.com/mozilla/copyright/compare/master...ScottDowne:date-stuff?expand=1

**Comment by TheoChevalier** [comment]
@ScottDowne Looks good to me :) I’ve moved the string here https://github.com/mozilla/copyright/pull/140/files

**Comment by hannahkane** [comment]
I'm a bit confused about the UX around this now. @ScottDowne - maybe it would be helpful if you posted a screenshot of what you have so @Melechuga and I can respond?

**Comment by ScottDowne** [comment]
@hannahkane @Melechuga Instead of the form, display this:

![form](https://user-images.githubusercontent.com/197334/30486244-ea084a6a-99fd-11e7-8225-a6f6ea15497a.png)

It's easier for me to just remove the form.

**Comment by ScottDowne** [comment]
@hannahkane I'm now a bit confused about the string(s).

Initially I thought it was just "Please note, calling is only available during business hours (Monday-Friday, 9:00-18:00 CEST.)" as defined in @Melechuga 's comment.

Now I'm seeing your initial comment with a slightly different string, and a new string, and not sure which one was first as the initial comment has an edit.

**Comment by Melechuga** [comment]
@ScottDowne Hoping this is helpful -- string should be what you have in there ("Please note, calling is only available during business hours (Monday- Friday, 9:00-18:00 CEST)"). 

- Is it possible to move the (Monday-Friday, 9:00-18:00 CEST) to the next line?

Also, keep in mind that on Oct. 29, 2017 we'll have to change this to "9:00-18:00 CET" which coincides with UTC +1.

**Comment by ScottDowne** [comment]
@Melechuga do you want the additional step in the call instructions saying "Step 1: Please note, the call tool is only available between the hours of 9:00-18:00 CEST."

**Comment by hannahkane** [comment]
I think the suggestion in the first comment is the most clear. It's adding the "Step 1" to the instructions AND replacing the form/button with a note that clarifies that during business hours a call tool will appear. My concern with replacing the form with "Please note, calling is only available during business hours" is that it's not as clear as "Please visit this page between 9:00-18:00 CEST to access the calling tool."

**Comment by ScottDowne** [comment]
I'm cool with the new step 1, and replacing the call tool with more copy.

So if I got all this, and to be clear, we want:

1. A new step 1 in the instructions that says "1. Please note, the call tool is only available between the hours of 9:00-18:00 CEST." Which I want to point out does not mention Mon-Fri. It probably should include "Monday- Friday" Like this "1. Please note, the call tool is only available between the hours of Monday-Friday, 9:00-18:00 CEST" or something.
2. Replace the call tool with copy, right now it's: "Please note, calling is only available during business hours: Monday-Friday, 9:00-18:00 CEST"
3. Move Monday-Friday, 9:00-18:00 CEST to the next line in the call tool replacement text.
4. On on Oct. 29, 2017 update the CEST to CET.

@Melechuga @hannahkane Does that sounds right? Can we just get clarify step 1?

**Comment by Melechuga** [comment]
@hannahkane @ScottDowne 
Yes to all the steps. Let's figure out the copy, which should be the same in the instruction and in the replacement copy outside of 9-1800 CEST.

I think saying that it's only available during business hours makes it clear that it's because the MEPs only work then, and not some arbitrary decision Mozilla has made. Sure, let's work on clarity; I prefer not to call it a "calling tool" as a regular user wouldn't really understand what that means. How about:
- Please visit this page during business hours to connect your call (Monday - Friday, 9:00 - 18:00 CEST)
- Please connect your call during business hours (Monday - Friday, 9:00 - 18:00 CEST).

**Comment by hannahkane** [comment]
To clarify further (!), does the first bullet point in your last comment refer to the copy in the box, and the second bullet point refer to the new instruction to add to the list?

**Comment by Melechuga** [comment]
@hannahkane 
Haha no, sorry. Those are options I'm suggesting. I think the copy we choose for the instructions and the copy to replace the tool should be the same. Thoughts?

**Comment by hannahkane** [comment]
In that case, I'd vote for the first. "Please visit this page during business hours to connect your call (Monday - Friday, 9:00 - 18:00 CEST)"

**Comment by hannahkane** [comment]
This is done, so closing.
