### ISSUE TITLE
Bugs: Paperstorm Net Neutrality

### ISSUE THREAD

**Issue by tlasadea** [MozillaFoundation/Advocacy#1059]
To compile bugs found on staging

**Comment by tlasadea** [comment]
I couldn't get the flashing bug to happen again but two today:

1) Mid storming, one of the notifications popped up without me clicking anything
![screen shot 2017-09-19 at 18 21 49](https://user-images.githubusercontent.com/30296602/30600297-bee75548-9d67-11e7-9c8a-f291f5f9caf8.png)
2) I had just hit about 800 flyers when the whole site crashed. 

Software: Safari vs 10.1.1, on a Macbook Air, (13inch, 2017) running macOS Sierra 10.12.6 @brettgaylor

**Comment by hannahkane** [comment]
@brettgaylor - can you pass this along to the Paperstorm team?

**Comment by hannahkane** [comment]
Closing, as I assume this has been addressed
