### ISSUE TITLE
questions for nationbuilder/fission

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#106]
Making a place for us to put all our questions for nationbuilder together.

**Comment by ScottDowne** [comment]
From me:
1. How does someone manage their rsvp to an event without signup. I tried to do this on the sandbox, and it was kinda broken. https://github.com/MozillaFoundation/Advocacy/issues/103
2. Any suggested solutions for l10n, and what are our options?
3. We need to setup SSO and not able to test that in the sandbox, seems to be disabled.
4. Can we add, remove, or change fields in a signup or petition?

**Comment by ScottDowne** [comment]
@valianttry status on our contact? I would like answers to these ASAP.

**Comment by ScottDowne** [comment]
I asked this in a generic support form from their support page.

**Comment by ScottDowne** [comment]
Another thing we can ask them once we're setup.

How do we link a custom field to a petition. I tried, and I get this:

![screenshot from 2016-07-26 11-23-02](https://cloud.githubusercontent.com/assets/197334/17147934/f12efa90-5332-11e6-9312-b783122459d8.png)

Link example: https://mozillasandbox.nationbuilder.com/admin/sites/1/pages/40/preview

**Comment by ScottDowne** [comment]
With the agency taking on the bulk of this, I highly doubt it's a priority for me to have answers to this.

We should consider this tasks for our training. Punting to next milestone, and we'll figure out where that is then.

**Comment by ScottDowne** [comment]
Slightly related: https://github.com/MozillaFoundation/Advocacy/issues/169

**Comment by damiankay** [comment]
@ScottDowne I'm following up with Fission shortly with some detailed questions. Do you need me to include any of these questions?

**Comment by ScottDowne** [comment]
I don't think there is anything pressing here that hasn't already been answered.

l10n was my biggest concern, and that's done via bablic, and there are other issues to deal with that at a finer level.

I couldn't get the custom fields to work on the sandbox, and I also couldn't figure out how to modify my rsvp without creating an account, but I suspect that's not a specific question, but likely caused by a bug in my test for the custom fields, and the sandbox messing with the rsvp.

I'm actually fine with closing this, and if something new comes up, just creating a new ticket.
