### ISSUE TITLE
Callout graphic for NN Paperstorm email

### ISSUE THREAD

**Issue by levjoy** [MozillaFoundation/Advocacy#1060]
We'd like to test an animated gif (of leaflets dropping on the FCC) in Friday's email. Brett should have assets we can use.

**Comment by hannahkane** [comment]
Assigning to @beccaklam

**Comment by beccaklam** [comment]
![fcc-paperstorm-emailcallout](https://user-images.githubusercontent.com/20977376/30605570-94f075f6-9d3c-11e7-8720-bd65709ce6c0.gif)
Will this work, @levjoy?

**Comment by hannahkane** [comment]
cc @WillatMozFdn

**Comment by WillatMozFdn** [comment]
I think it will, yes! Copying @stephaniemcv so she knows where this file is (in prep for building the email).

**Comment by stephaniemcv** [comment]
wow! that looks amazing!

**Comment by hannahkane** [comment]
This happened. Closing.
