### ISSUE TITLE
Wireframes for Desktop

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1061]
Provide desktop treatment, based on mobile wireframes

**Comment by beccaklam** [comment]
Wireframes are here: https://redpen.io/p/aw8488cb9ac1ccc0c7

**Comment by hannahkane** [comment]
@beccaklam - do you expect you'll need to do add'l work on the desktop wireframes? Or will final changes in the mobile version suffice?

**Comment by beccaklam** [comment]
@hannahkane I'll probably need to make changes to the desktop wireframes too.

**Comment by hannahkane** [comment]
@beccaklam - what's your plan for closing this out?

**Comment by beccaklam** [comment]
@hannahkane Oops, forgot to say that Natalie said she didn't need the desktop wireframes so we can close this ticket!
