### ISSUE TITLE
Social Strategy

### ISSUE THREAD

**Issue by tlasadea** [MozillaFoundation/Advocacy#1062]
Write the social strategy for MozFest

**Comment by tlasadea** [comment]
Social strategy lives [here](https://docs.google.com/presentation/d/19VHRoFMKEtlvAya2YQ5PkJY5Au0hbV2Tcuw6vCBgGM0/edit?pli=1#slide=id.g20012d5435_0_45)

**Comment by hannahkane** [comment]
Closing, as this is done!
