### ISSUE TITLE
Design: Assets for MozFest

### ISSUE THREAD

**Issue by tlasadea** [MozillaFoundation/Advocacy#1063]
This ticket is for the design of assets for MozFest. As it gets clearer what the specifics are, I'll update this.

**Comment by tlasadea** [comment]
[Here](https://drive.google.com/open?id=1iU1KLFgWHFBWWZCzd3KIU5cr09PCtD80kHgDhJ23goM) is the brief for this work. I'm accounting for 2 rounds of amends on the social assets @HPaulJohnson @beccaklam. CC @hannahkane.

- [x] Brief Rebecca
- [ ] Review first round of assets
- [ ] Review second round of assets & have Erika D oversee to check for any branding inconsistencies
- [ ] Choose which assets to use for paid social, and ensure specs are adhered to.

**Comment by hannahkane** [comment]
Moving to "In progress" as it sounds like this work has begun

**Comment by tlasadea** [comment]
Hey @hannahkane not sure if this should be closed as there are other tickets in the [MozFest 2017 Design Repo](https://github.com/MozillaFoundation/mozfest-design-2017/issues/8) ?

**Comment by hannahkane** [comment]
Let's close it, if the work is being tracked elsewhere!
