### ISSUE TITLE
Research SEO Methods For Buyer's Guide

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Advocacy#1064]
Research basic guidelines for search engine optimization for driving traffic to the Buyer's Guide.
CC: @hannahkane @HPaulJohnson

**Comment by hannahkane** [comment]
Are we still planning to do this?

**Comment by beccaklam** [comment]
@hannahkane I think we should! Not sure if we have time though :(

**Comment by HPaulJohnson** [comment]
closing this one and will not do.
