### ISSUE TITLE
IoT Survey Report Out

### ISSUE THREAD

**Issue by caltrider** [MozillaFoundation/Advocacy#1065]
**To Dos for the IoT Survey Report Out:** 
(aiming to have the survey read to share back out by November 1st)
- [x] Draft Blog (Jen)
- [x] Draft Email (Jen)
- [x] Draft Snippet Copy (Jen)
- [x] Get final approvals on all (Jen)
- [x] Prepare raw data to be linked out from blog (remove personal info & open comments) (Vojtech)
- [x] Start localization in the same 5 languages we did the survey in (Theo)
- [x] Create Social Content & Paid Plan (Temi)
- [x] Design & Create Blog Graphics (Rebecca or Natalie?)
- [x] Design & Create Social Content (Rebecca or Natalie?)
- [x] Create & Post Blogs (Rebecca did this last time & did a great job integrating the sign-up into it)

CC:  @vojtechmzl @hannahkane @tlasadea @natalieworth @beccaklam @TheoChevalier @HPaulJohnson

**Comment by hannahkane** [comment]
Greatest. Ticket. Of. All. Time.

**Comment by caltrider** [comment]
9/29/2017 Update:
Blog, Email, and Snippet copy are all drafted and in the pipe for approvals. I will update the doc and here when I get final approvals on things.
You can find everything in this doc: [IoT Survey Report Out](https://docs.google.com/document/d/1h9g3XnBfZPXYZjww0ZwstKMF8j21N6Qc7BWTg-n6iQw/edit)

While I'm out next week, I've asked if @vojtechmzl could help out as the resource working with the designers to answer any questions they might have as they create the data visualization graphics for the blog/social.

@TheoChevalier has been updated about localization and as soon as we have final approvals is ready to get that going.  

@tlasadea, I was thinking it might be cool to try doing some embedded tweets in the blog post so if people wanted to tweet a tidbit from it, we'd have tweets made and embedded there already and easy to tweet.  I'm not sure we've done this before, so not sure what tweaks we might need to make to the medium blog to put those in.

cc: @hannahkane @HPaulJohnson

**Comment by tlasadea** [comment]
Hey @natalieworth do you have versions of the data visualisations that I can see?

**Comment by natalieworth** [comment]
Have a rought draft of these here https://redpen.io/p/oj074db279cd03c2b4 @tlasadea 
cc @beccaklam for design review
cc @HPaulJohnson @caltrider @vojtechmzl If y'all want to weigh in too

**Comment by caltrider** [comment]
Thanks @natalieworth! These are looking great. I left some quick, initial end of day thoughts. @vojtechmzl I grabbed 30 minutes on your calendar tomorrow for us to chat through them and get final feedback to Natalie.  cc: @beccaklam @HPaulJohnson

**Comment by tlasadea** [comment]
@TheoChevalier [social copy](https://docs.google.com/document/d/1R4pO2GQ2UAHVcD7kViwaj8CLLGi0nZQsgyObdupkXRE/edit) for localisation.

Only 2 strings - kept it super simple. Not sure if this has been flagged but are the survey visuals being localised too, or are we just gonna do a generic graphic to accompany? (as mentioned in Slack already) @caltrider

**Comment by caltrider** [comment]
The survey visuals will be localized too and we'll do the blog in all 6 languages @tlasadea

**Comment by TheoChevalier** [comment]
As discussed, Temi will get a few more variants early next week, and I will send the social strings + visualization text to localization next Wednesday.

**Comment by natalieworth** [comment]
@caltrider @vojtechmzl updated redpen here based on your feedback: https://redpen.io/p/oj074db279cd03c2b4

**Comment by natalieworth** [comment]
@TheoChevalier I have the English version for these finished and up on Redpen here: https://redpen.io/p/fk577a8639ece03c40

**Comment by natalieworth** [comment]
For my reference, design and exported files are here https://drive.google.com/drive/u/0/folders/0B20-0lpP23c0bGt1akRsUjJFZHM

**Comment by natalieworth** [comment]
cc @hannahkane Should we make a new ticket for design of the localized content from Theo or tack it onto this one?

**Comment by hannahkane** [comment]
@TheoChevalier - what would you prefer? (See Natalie's question above)

**Comment by hannahkane** [comment]
Oh sorry, re-reading question. @natalieworth - whatever *you'd* prefer if the ticket would be for you!

**Comment by tlasadea** [comment]
@TheoChevalier social copy for localisation is finished, [here](https://docs.google.com/document/d/1R4pO2GQ2UAHVcD7kViwaj8CLLGi0nZQsgyObdupkXRE/edit).

**Comment by natalieworth** [comment]
@tlasadea Social version w/ text is here https://redpen.io/fz4be2939df3ce44fd

**Comment by TheoChevalier** [comment]
Thanks everyone, strings are being translated! (Social + graphics in RedPen)

Should be fine to use this ticket for l10n tracking, but @natalieworth may want a separate one for graphics QA?

If we could avoid updating the images in the current RedPen, that’d be rad, as I’m linking to them in Pontoon https://pontoon.mozilla.org/fr/engagement/other/2017/iot_results_assets.lang/?string=172862
But if we have to, let me know and I can update the links (or maybe we can use a new RedPen project?)

L10n tracking: https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=other/2017/iot_results_assets.lang

**Comment by TheoChevalier** [comment]
To give everyone an idea about where we are with the translation of the different parts:

Special Spanish email (with buyer’s guide mention) ✅ https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=emails/2017/iot_results_a.lang

Other emails in French, German, Portuguese ✅ https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=emails/2017/iot_results_b.lang

Snippets (all locales) ✅ https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=snippets/2017/iot_results.lang

Graphics strings + Social: **all ready, but Italian** https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=other/2017/iot_results_assets.lang Filed issue #1091 for the production and QA of the localized graphic assets

Blog posts: **received final versions of German, French, Italian**. Spanish is in final review, pt-BR is not yet done but the team is confident to finish on time.

**Comment by caltrider** [comment]
Thanks for the update @TheoChevalier.  Looks like we're on track to have everything for @beccaklam and I to set up the blogs next Wednesday. @natalieworth, in yesterday's staff meeting we forgot to talk about time on your schedule to make the localized graphics and it seems we should have.  What are you thoughts on what's needed to get those done by next Wednesday?  
cc: @hannahkane

**Comment by TheoChevalier** [comment]
Spanish blog post is now final, graphic strings are in review for Italian.
Should get the pt-BR blog post tomorrow.

And with that, we should be done! The last task will be QAing the localized assets

**Comment by TheoChevalier** [comment]
@beccaklam Here are the final versions of the blog posts in all languages:

French: https://docs.google.com/document/d/12uRaz8NjW-2Y888JdwEEd7dCB3RP6vKA0rjrtDvJM9Y/edit?usp=sharing
Italian: https://docs.google.com/a/mozilla.com/document/d/16ud9l-rV7O97wG_hPFPjpYXd1pKU2RCy1PFTQzRNtZ4/edit?usp=sharing
German: https://docs.google.com/document/d/1doV2HZpxfDYLX19Q_bQ_ItQ_kcvVnftY3wyZ7Kt83Ws/edit?usp=sharing
Portuguese: https://docs.google.com/a/mozilla.com/document/d/1puKAH49SbzDXjrFX_u_4u5L67Ye19wkBMmO2BzLwclo/edit?usp=sharing
Spanish: https://docs.google.com/a/mozilla.com/document/d/1UzswByISWewDxgZjAiz4y-OjzpIl7VkuaUxc144uwsM/edit?usp=sharing

Links to add to the English versions:

French: Lire cet article en français
Italian: Leggi questo articolo in italiano
German: Diesen Artikel auf Deutsch lesen
Portuguese: Leia esse artigo em português do Brasil
Spanish: Leer este artículo en español

**Comment by TheoChevalier** [comment]
@beccaklam Forgot to mention, but for French only you will need to either:
- Copy the document from Chrome
- Download the document as .docx and copy from Word

Otherwise you will loose all the non-breaking spaces and the text layout might become chaotic

**Comment by beccaklam** [comment]
Got it. Thanks @TheoChevalier!
