### ISSUE TITLE
Buyer's Guide localization

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1066]
This is essentially a placeholder ticket. I believe @caltrider, @TheoChevalier, and @ScottDowne are going to meet this week to discuss localizing the Buyer's Guide into Spanish.

Perhaps an output of that meeting could include updating this ticket with a checklist of ToDos?

**Comment by caltrider** [comment]
9/29/2017 Update:
@TheoChevalier, @ScottDowne and I meet this morning to get the ball rolling on localization to Spanish for the guide. Theo is updated on things and will work to get a vendor quote back to us early to mid next week. @HPaulJohnson, Theo knows I'll be out so will copy you in on things while i'm away.  Theo has the best idea of word volume we could give him today and knows we're working toward a launch data of the week of November 6th. We have vendors we've already worked with, so paperwork on that end won't be a blocker.

A few questions to keep us moving forward:
1. Will we have any promo, social or video material on our end we'll need localized in addition to the website?
2. Who will do QA? The vendor or the community?  (I think we will rely on your recommendation on this one Theo).
3.  Scott raised the question of making sure Pontoon worked on the advocacy.mozilla.org site (I might have not phrases your concern here very well Scott, so feel free to update if you want to make it clearer)

cc: @hannahkane

**Comment by TheoChevalier** [comment]
@caltrider Confirmed a first cost estimate with the vendor:
With the currently expected volume and deadlines, the Spanish translation would cost around 650 / 700 USD.
Adding L10N QA is 59 USD per hour. I think an hour or two would be enough for the website.

Regarding Pontoon, still looking into our options.

**Comment by caltrider** [comment]
Thanks for the quote @TheoChevalier .  CC @hannahkane @HPaulJohnson

**Comment by HPaulJohnson** [comment]
thanks, @TheoChevalier. this cost is totally reasonable so let's move forward with this approach.

**Comment by TheoChevalier** [comment]
@ScottDowne Would you be able to store both the `en-US` and `es` properties files *outside* the `locales` folder? https://github.com/mozilla/advocacy.mozilla.org/tree/master/locales

I.e. Would it be easy to tell `properties2json` to pick an alternate path just for the Buyer’s Guide when building the JSON files?

This would allow me to store the .properties in an external repo, hook up Pontoon to that, and regularly merge back here. The only thing is that we have to stay outside the `locales` folder.

**Comment by ScottDowne** [comment]
I think so. I should also try to get this out of the way asap. One
question. While I suspect it's easy to store the properties outside the
locales dir. Is it necessary that it builds this new json only for buyers
guide? Ie we would still build one json blob that's the same for all sites?
Pontoon doesn't have a concept of the json blob it builds, right?

**Comment by TheoChevalier** [comment]
Yeah, no need to build the JSON only for Buyer’s Guide, totally fine to include the strings for all the pages. Pontoon doesn’t even look what’s in /public, it only cares about .properties in /locales

**Comment by TheoChevalier** [comment]
Ok, setting things up here: https://github.com/mozilla-l10n/buyers-guide

My plan is to just copy the en-US folder from advocacy.m.o repo into the buyers-guide repo to expos new strings.
And copy the es folder from buyers-guide into advocacy.m.o repo to import back translations.

**Comment by TheoChevalier** [comment]
Extracted for localization, and sending to vendor:

- “Why we made this” page
- Reviewed blurbs as of this morning
- UI strings from RedPen (a few are still missing like the footer), including category names and product page strings (review script)

**Comment by TheoChevalier** [comment]
First batch now fully exposed: https://github.com/mozilla-l10n/buyers-guide/tree/master/locales/en-US
Waiting for a formal quote (probably tomorrow morning)

**Comment by caltrider** [comment]
Thank you so much @TheoChevalier. Here's the list of remaining things I can think of that will need to be localized:

- [x] Remaining product blurbs 
- [x] Janice's product reviews (mostly yes/no so the biggest thing for l10n will be the one sentence "what could happen"
- [x] Social copy
- [x] Snippet copy
- [x] Email #1 Copy
- [x] Email Call Out Box copy
~~- [ ] Email #2 (a short kicker) Copy~~
- [ ] Janice's Methodology Blog
- [ ] Possibly a blurb about our use of Coral Talk for the comment system
- [x] Logo https://redpen.io/p/uz6c7f8b5519ab96a6

If I think of anything else, I'll ping you as soon as I think of it.

**Comment by ScottDowne** [comment]
Is there stuff that still needs to happen here?

I figure a lot of those checkboxes can probably be checked off?

**Comment by TheoChevalier** [comment]
Updated the items with what is localized/being localized

**Comment by tlasadea** [comment]
Can this be closed @TheoChevalier?

**Comment by TheoChevalier** [comment]
Depends if we’re still doing a Methodology blog post, do you know @caltrider ?

**Comment by HPaulJohnson** [comment]
I think we have all this covered for this campaign so closing this ticket in an effort to clean up before end of year. Feel to reopen if needed.
