### ISSUE TITLE
Hero graphic for some Firefox emails

### ISSUE THREAD

**Issue by WillatMozFdn** [MozillaFoundation/Advocacy#1068]
Detailed description of work: Add some verbage to an existing graphic, and optimize it for hero image use in an email (600 px wide on screen but 1200 for retina).

1. Mockup of what the final should (basically -- but artistic discretion welcomed!) look like is here:
https://image.e.mozilla.org/lib/fe9915707361037e75/m/3/mozimageresizedFPO.jpg (but, that's just a crappy screen grab, and will look bad on a retina display.)

2. Original photo is here:
https://www.mozilla.org/media/img/home/2016/intro/intro-learning-2000.jpg

3. So, we need to put a text overlay on that photo in #2 there, and then optimize under 200K so that it can be uploaded to SFMC and used in an email.

Hopefully that all makes sense?  Ping me if not, of course!  (This is the little project I mentioned yesterday.)

*Start date: September 28, 2017* 
*Due date: October 6, 2017* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @hannahkane 
@natalieworth

**Comment by hannahkane** [comment]
@natalieworth - do you think you'd have time to do this?

**Comment by natalieworth** [comment]
@WillatMozFdn Should the text be the same as the original example? ("Internet for people, not profit")

**Comment by WillatMozFdn** [comment]
Yes please!

**Comment by natalieworth** [comment]
Hey Will,
Have 3 colour options here: https://redpen.io/p/wxad7914871a74ee16

**Comment by WillatMozFdn** [comment]
Hey Natalie, seems to me like the color overlay is too heavy and makes very hard to decipher what's going on.  Can you do one like option 4 there ... no color overlay ... but with a lighter shade over the photo?

**Comment by natalieworth** [comment]
Hey @WillatMozFdn Let me know if this works? https://redpen.io/az89d95ee371a184a5

**Comment by WillatMozFdn** [comment]
yep, that works great -- thanks Natalie!!!

**Comment by natalieworth** [comment]
![firefox-email-callout- 2x-v4](https://user-images.githubusercontent.com/14876567/31033522-42db2ffa-a515-11e7-9f23-d20f38ce0662.jpg)
@WillatMozFdn Original jpg file is here ^
I can upload to google drive too if that's easier for you

**Comment by WillatMozFdn** [comment]
I already uploaded it to SFMC so we are locked and loaded.  :-)  Many thanks!
