### ISSUE TITLE
Finalize Vojtech Sedlak's onboarding plan

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#107]
Onboarding is important! Our work is complex. Mozilla is fun, interesting, and sometimes a whacky world that's hard to grasp. This is our opportunity to help someone get their sea legs faster ?? 

Rough DRAFT here based on @damiankay 's onboarding plan:
https://docs.google.com/spreadsheets/d/12iRVs_gIfVKOU36mE22fxdDEeYAfMo6qcBTchOcSnLQ/edit#gid=0
- [X] Andrea takes a first pass at edits 
- [x] @damiankay takes 2nd pass
- [x] @stephaniemcv takes 3rd pass
- [ ] @HPaulJohnson takes 4th pass
- [ ] Full team reviews

**Comment by damiankay** [comment]
Hi @valianttry ,

Just a few notes based on my very recent onboarding (arranged by line number):
16: The IRC client of choice in the Vancouver office seems to be IRC cloud, although Adium will work as well. 
23: The glossary of terms is missing an explanation for "MLN" which had me stumped for a little while (well, a few days), esp as the meaning has changed.
29: Added a note about deadline for form submission
50: Added link to Q2 Program Review
70: Invalid link - Matt's blog is now the Story Engine site
81: Invalid link - Couldn't find this blog post
89: Invalid link - Repeated from line 35
98: Invalid link - Presentation have been removed
100: This link is out of date. Perhaps update to this? https://mozillafestival.org/

**Comment by stephaniemcv** [comment]
Cool! His on-boarding is looking good!

25: I've found that I mostly use Airmo now for the weekly project meeting, https://wiki.mozilla.org/WeeklyUpdates   

28: I would call out specifically attending Foundation Demos (Fridays) on the MoFo events calendar, great way to see what's going on around Foundation

68 & 69: These can be merged, there's only one email calendar now

87: Warn him that Mark is really hard to get a hold of and it might not happen :-P

-A service now ticket will need to be submitted so Andrew can get Vojtech a SalesForce login and get him into the training pipeline per Michele/Jess

**Comment by stephaniemcv** [comment]
Also added http://mofo.build/ to the onboarding doc, since it looks like a great resource even though it's in "soft launch"
