### ISSUE TITLE
buyers guide website product page

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#1074]
Build this page: https://redpen.io/ncbea1ceace44f2489

Similar to the category page.

Url would be similar to "/en-US/buyers-guide/category/toys/product"

**Comment by hannahkane** [comment]
@ScottDowne - would you consider the Coral integration part of this ticket?

**Comment by ScottDowne** [comment]
I considered it, but I decided to keep that work here: https://github.com/MozillaFoundation/Advocacy/issues/1050

They are different enough in problem space that it's easy to split up the work.

This ticket is pretty much just front end work. Which is considerably different than a service integration (although there might be CSS work in Coral, it'll likely be dependent on the coral system).

**Comment by ScottDowne** [comment]
I think I can close this.

There are some css QA changes happening, but I think we're starting to track that in the QA ticket, and were out of scope of the comps anyway.
