### ISSUE TITLE
Automatic monthly donation ask after a one-time donation

### ISSUE THREAD

**Issue by WillatMozFdn** [MozillaFoundation/Advocacy#1077]
Detailed description of work: Based on https://cstage-zz.trilogyinteractive.com:10444/test-upsell.html?show_amount=true ... ("give" $50 there with the pre-loaded dummy data, and see what happens) ... we need an automatic ask for a monthly donation to pop up right after a one-time donation.

General parameters:
 - the one-time donation is processed first, so we know we have that transaction processed already

 - if someone donates 0-14.99$, we do not fire the ask for a monthly.
 - if someone donates $15 to $34.99, we suggest $5 monthly
 - if someone donates $35-59.99, we suggest $10 monthly
 - $60-119.99, suggest $15 monthly
 - $120-$250, suggest $20 monthly
 - above $250 suggest $30 monthly

Ideally, we would set the monthly to start not immediately, but one month from today.  (If that's not possible, we just start the monthly right away.)

*Start date: October 3, 2017* 
*Due date: November 28, 2017* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @alanmoo @ScottDowne @shaghdoosti

**Comment by alanmoo** [comment]
Presumably we'll edit the [thank you page](https://donate.mozilla.org/en-US/thank-you) to tell it how much the user donated so it can present recurring options as appropriate?

**Comment by ScottDowne** [comment]
It currently passes in, via query string:

payment type, amount, currency, frequency, email, and country. It also passes in anything needed by stripe or paypal like temporary transaction ids.

I think we're good on that front.

**Comment by alanmoo** [comment]
Ah, great. I was just looking at the page but not the whole flow.

**Comment by alanmoo** [comment]
@ScottDowne Does the fact that the person could have paid with Stripe or Paypal mean we have to do this work twice? If so, should we prioritize one over the other?

**Comment by alanmoo** [comment]
From @Pomax in Slack:
> it looks like Stripe can't do 'don't pay until next month', but we _can_ do a refund that gives people the amount they donated back as part of their new payment from what I can tell. [Meaning our option can be] the "hey, do you want to upgrade your one-time donation to a monthly?" route, making it clear it's an upgrade rather than 'another' donation

@WillatMozFdn, do we want to do that or simply ask for a monthly donation that starts immediately? My instinct is to go monthly immediately because it'll be simpler to implement, and then if we want to pursue it later on, we can A/B the "upgrade" behavior. Does that sound good?

**Comment by WillatMozFdn** [comment]
Thanks Alan, yep, agree with you.  Monthly immediately is the right way to
go, let's do that.

 - Will

**Comment by alanmoo** [comment]
There was a thread, possibly in Slack, that we should solidify for future reference:

This monthly ask should only happen in a few locales to start: US, UK, Germany and France.

**Comment by ScottDowne** [comment]
Working implementation up on review apps now: https://donate-mozilla-org-us--pr-1864.herokuapp.com/en-US/thank-you/?payment=Stripe&str_amount=300&str_currency=usd&str_id=ch_1BNmhOG8Mmx3htnxcnENnlqH&str_frequency=one-time&customer_id=cus_BlJK8zST6kp9GX&email=fsegs@gg.com&country=United%20States

It's lacking lots of little things, but you can test the actual flow end to end now.

Main page link here:https://donate-mozilla-org-us--pr-1864.herokuapp.com/en-US/

**Comment by ScottDowne** [comment]
Things I'm still doing in the above demo:

- [ ] Delay the first donation by a month.
- [ ] Some styling on the error validation messages.
- [ ] Proper upsell amounts.
- [ ] Proper upsell targets. (en-US, eur, etc)
- [ ] Refactor some reusable functions for amount validation.
- [ ]  Some sort of tests.

**Comment by ScottDowne** [comment]
I think we can close this now.
