### ISSUE TITLE
Enable SEPA direct debit donations through Stripe

### ISSUE THREAD

**Issue by WillatMozFdn** [MozillaFoundation/Advocacy#1078]
Detailed description of work: Based on direct experience of one of our staff members while working for another organization, enabling SEPA transfers directly in Stripe is known to provide a significant lift in donations from Europeans (a prime target market for us, especially Germany.)  Donors do not have to leave the donation page, and are presented with a very familiar way of making payments.

Stripe documentation is here: https://stripe.com/docs/sources/sepa-debit

Chris reports that this will require a rebuild of our Stripe form (moving away from Stripe Checkout), so let's get moving on this as soon as we can in the hopes that it's in place for our heaviest period of fundraising in December.

*Start date: October 5, 2017* 
*Due date: December 1, 2017* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:   @shaghdoosti  @stephaniemcv 

--------------------
### Technical notes (added by Alan):
We’re currently using Stripe Checkout for credit/debit card transfers, but Checkout doesn’t support SEPA. So we’ll need to build a custom form to accept this. We probably want to A/B test this to make sure it doesn’t negatively impact non EU donation amounts.

Design requirements: Form design, UI changes on main donation page

**Comment by ScottDowne** [comment]
I think the worry of a rebuild is less about time to implement, and more about moving away from something stable to something new. So the risk here is we ship a bug just before our heaviest period.

**Comment by WillatMozFdn** [comment]
Right, I hear you there Scott.  Let's build it and see how we feel about the risks.  Perhaps with an easy rollback option to the previous state, so if we see problems, we can flip back to our previous setup.  We may decide it's not ready for prime time, and we want to hold off shipping it to production until January.  But we'll never be able to evaluate those risks until we actually build it out, right?

**Comment by ScottDowne** [comment]
I think our best bet is another page, and we can sent a percentage of de traffic to it.

**Comment by WillatMozFdn** [comment]
Parallel systems -- that works for me.  Send 5% over there for a day and see what happens.  We just gotta keep a close eye on it.

**Comment by cadecairos** [comment]
Yeah, so after a conversation with Scott earlier today, I realized we should keep the tried and true Stripe Checkout / Paypal form and build a new page specifically for SEPA donations (might be a good time to try out [Stripe Elements](https://stripe.com/docs/elements) when building the form components - but also might not be.)

Rebuilding the whole form from scratch to support all three donation strategies is pretty crazy :)

I can provide support on the back end, by helping ensure that data is properly flowing into the CRM

**Comment by alanmoo** [comment]
This wasn’t in the conversation we had the other day, was it? I’m going to need to line these all up next week and get a better sense of priority for each of them.

**Comment by WillatMozFdn** [comment]
Correct, @alanmoo -- this project (and the potential benefit) came to the surface for us on Wednesday, after we met.

**Comment by gideonthomas** [comment]
This project has been deemed out-of-scope for this years campaign due to us not being able to acquire a creditor ID (see https://github.com/mozilla/donate.mozilla.org/issues/1869).

For future reference all the pending work for the SEPA integration is ticketed under the SEPA label in the donate.mozilla.org repository (see https://github.com/mozilla/donate.mozilla.org/labels/SEPA)

**Comment by alanmoo** [comment]
Seems like this isn't happening this year either. Let's re-open when it is.
