### ISSUE TITLE
Build a donations pop-up modal for EOY fundraising

### ISSUE THREAD

**Issue by WillatMozFdn** [MozillaFoundation/Advocacy#1079]
Detailed description of work: Similar to our current modal that asks site visitors for an email subscription, we need to build one to ask site visitors to donate to Mozilla.

Initial placement will be on landing pages (such as copyright campaign at www.changecopyright.org or net neutrality "slow it down" page at https://advocacy.mozilla.org/en-US/net-neutrality/ ) ... then, in December, moving to the mozilla.org home page.

Suggested format: very close to what a long-form snippet looks like, i.e. ....
![image](https://user-images.githubusercontent.com/23637882/31242361-cdad383a-a9d4-11e7-881f-d588468ca34b.png)
(with specific donation button amounts TBD; likely, will be higher than the amounts shown there.)

Nice-to-have but not required: The ability to turn this off (i.e., not have it displayed) with a URL querystring of "?donated=1".

*Start date: October 5, 2017* 
*Due date: November 28, 2017* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

----------------------------
### Technical notes by Alan

Turning this off could also mean making it a sticky footer element for users who _have_ donated, be it triggered by a query param or localstorage.

Design requirements: Modal design

**Comment by alanmoo** [comment]
What sites are we considering putting this on? I'm still skeptical of this being a valuable use of our time given the work MoCo is doing for the mozilla.org homepage. I just checked the analytics, and in the month of October, advocacy.mozilla.org/net-neutrality has had <1200 hits, and changecopyright.org has had a single visitor.

**Comment by WillatMozFdn** [comment]
Hey Alan, 

Can you check your numbers on the changecopyright.org visitors?  That just can't be right; on October 12 we sent an email to most of our European subscribers that linked to changecopyright.org ... I see more than 7,100 unique clicks on those messages.  So I gotta think a few of them actually landed on the site, yeah?

**Comment by alanmoo** [comment]
Ah, it looks like analytics was turned off at some point for changecopyright. We can take a look at the logging to get actual numbers from it, but my real concern here is this: Building a single plugin that can be dropped on a bunch of sites is incredibly time-consuming. If there are specific sites on which we want to turn on something simple, let's get a list of them and sort for impact, then see if we have options for building a minimum-viable-modal, and what kind of lift they'd require.

**Comment by gideonthomas** [comment]
@vojtechmzl, would you be able to advise us here? Any suggestions on which sites we should target to add the modal?

**Comment by vojtechsedlak** [comment]
I think advocacy.mozilla.org, changecopyright.org and internethealthreport.org are the most relevant sites, where the modal could appear. Particularly advo will receive substantial traffic in the next bit for the Privacy Not Included campaign (~100k a month).

**Comment by WillatMozFdn** [comment]
That seems correct to me, as well, thanks Vojtech!

 - Will

**Comment by alanmoo** [comment]
What parts of the advocacy site do you anticipate receiving high traffic? The PNI campaign already has a modal on it, so we can't realistically add a second one.

**Comment by WillatMozFdn** [comment]
Plan is to turn off the PNI email subscription ask module on or about Giving Tuesday Nov. 28th; the fundraising one would replace it.  The other area would be https://advocacy.mozilla.org/en-US/net-neutrality ... FCC may take a vote on that in December so we'll likely have decent traffic there too.

**Comment by alanmoo** [comment]
We ended up doing something for this last year. If more needs to happen, let's open new tickets.
