### ISSUE TITLE
Salesforce Migration: Plan for connecting Stripe Data

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#108]
About 40% of all donations to Mozilla come through Stripe. Donors using credit cards interface with our Stripe donation flow. We do have some limited donor data already in Salesforce. 

We need to put an integration in place so that donor information is regularly added to Salesforce records. This is important so that:
- We can personalize outgoing email to donors based on their donation history. For example, if a donor regularly gives $100, we want to customize the donation emails we send to that donor so we don't undercut ourselves by asking for $10, we want to ask them for $100 or more.
- We can exclude donors from donation asks if they've recently given (thereby annoying them less);
- We can personalize outgoing email based on their giving profile, for instance recency (whether they haven't given for 6 months or gave last week), whether they are a 1x or monthly donor, or whether they are a higher-average donor vs. lower. 

@stephaniemcv can you provide some info on what is in Salesforce now about our donors, specifically:
- What donor data / fields currently exist on contact records in Salesforce? 
- Whether donor data is regularly updated in Salesforce (e.g. new donations are appended to existing contact records / new donors are added to Salesforce)?

Stripe recommends Zapier for integration. Our contact at Stripe is Christian DiCarlo and to quote him:

> - Salesforce integration: I checked with our team and the Zapier integration is one that we've seen others use. If you need a more customized integration with Salesforce, your development team would have to build that. You can learn more about the Zapier integration here: https://zapier.com/zapbook/salesforce/stripe/

cc @cadecairos and @ScottDowne

**Comment by stephaniemcv** [comment]
- Currently there is no donor data or any donor related fields in SalesForce. (we get to start from scratch!)
- Therefore there is no regular updating of any donor data (no new donor accounts are being created and no data is being appended to current contacts).
