### ISSUE TITLE
Paid Social for Buyer's Guide

### ISSUE THREAD

**Issue by tlasadea** [MozillaFoundation/Advocacy#1081]
This is for everything that needs to be done for all paid social + snippet for the guide, including:

- [x] audience segments for Facebook + Twitter
- [x] matrix for Facebook + Twitter
- [x] copy deck for paid ads
- [x] copy deck for social content that will be localised into Spanish

**Comment by tlasadea** [comment]
@HPaulJohnson the updated audience segments for Facebook & Twitter are [here](url). You'll notice that I also included a 'Conscious Chooser' audience, this I think will be v interesting to test with strong advocacy copy than with the general shopper/parent audience. We can also use this stronger advocacy copy with the frequently used - 'Mozilla Supporters' audience too. 

Will replicate for Twitter.

**Comment by tlasadea** [comment]
@TheoChevalier - when would it be ideal to have social copy for Spanish localisation for? Launch date is Nov 6th, so working backwards would Oct 23rd be the latest date?

**Comment by TheoChevalier** [comment]
@tlasadea, @caltrider plans to have most of the content ready for the vendor by October 13th, and hopefully everything by the 18th. So the 18th would be ideal, but we can probably try to accommodate for the 23rd. Note that social was not part of the initial request I submitted to the vendor, but I don’t expect this to drastically increase the price

**Comment by tlasadea** [comment]
@TheoChevalier where are we with the paid social translations? Did you see the copy deck ([here](https://docs.google.com/spreadsheets/d/1nXLPHQt_z8Bp5gbLWVWgo_z7SQCKEyHU0NbvnYxuY8U/edit#gid=1021378335))?

**Comment by TheoChevalier** [comment]
@tlasadea Sorry, didn’t see any ping about this, looking now

**Comment by TheoChevalier** [comment]
Just left a couple questions in the doc, but I should be able to send those to the vendor today

**Comment by TheoChevalier** [comment]
@tlasadea Took a bit more time than expected, but those are ready to go https://docs.google.com/spreadsheets/d/1B2JYfVc-t6qhgcZXrbUpcoE7OadPJP4UesABwhbJBmI/edit?usp=sharing

**Comment by tlasadea** [comment]
Think this ticket is finished, as there's another ticket with phase 2 social. Will close this.
