### ISSUE TITLE
Privacy Not Included Stickers for Mozfest/Glassroom

### ISSUE THREAD

**Issue by caltrider** [MozillaFoundation/Advocacy#1083]
As of Friday the 13th (October), this is a P3 but wanted to get it filed so it's not forgotten.

Would love to have something to hand out at Mozfest and at some of the upcoming Glassrooms that promotes the buyer's guide.  Thinking is a sticker.

Here's what I'm thinking for the sticker, feel free to tweak or add in to the idea:

Sticker is a simple " *Privacy Not Included" in the buyers guide style with a small URL under.  We talked about creating the URL for the guide as:  mzl.la/privacynotincluded .  @tlasadea I think that's something you'll have to do when we've got a URL.  

One question, if we hand these out at MozFest and the website isn't live yet, we'll likely need a "Coming Soon" placeholder.

CC: @hannahkane @HPaulJohnson @natalieworth @tlasadea @beccaklam

**Comment by tlasadea** [comment]
@caltrider by 'something you'll have to do' you just mean bit.ly it right?
Or is there something else..

Re stickers - you should speak to Erika Drushka/Sabrina Ng to see what the
due date is for things being printed for MozFest, as this will impact
design deadlines.
