### ISSUE TITLE
Create text to describe relationship w/ sponsored/granted content

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#1084]
Hello - @caltrider and I spoke with Legal today regarding language we should use to describe nature of our relationship with Univision, and the sponsored/influencer content came up as well.

A solution discussed was the creation of a paragraph on an about page that described the nature of our relationship with Univision (we granted them but they have editorial independence) and the influencer content (we've paid them to look into these issues and educate their audience).

I wasn't sure if we have an about page in the buyer's guide already. In any case we should create this language, and @caltrider said she'd take the lead there.  Legal + Univision will need to approve.

cc @hannahkane @tlasadea @HPaulJohnson

**Comment by caltrider** [comment]
Oh god, not another github ticket! ;-)

I've got it on my to-do list to draft this "Why We Made This Guide" language.  Natalie has a spot for it already in the UI.  After talking with Abigail and Jishnu, the goal of that language is to explain our approach to the guide and provide transparency on the project and our partnerships. I have some tidbits from them to include in this from our discussions this morning.

My goal is to have this written this week to go into the queue with all the other localization needs. I told Abigail I'd have something to her for review as soon as I've got it written.  It's on her radar for sometime this week.

@brettgaylor Why does Univision need to sign off on this?  If they have specific language they'd like included about the partnerships, I'm happy to include that. Feels a bit weird to let them sign-off on our "Why We Made this Guide" transparency piece though.

**Comment by brettgaylor** [comment]
To make sure no one has a heart attack, i just changed this so that the requirement is only that we describe the relationship.  Seems like there's places to do this in the landing page of the buyer's guide, and in the "discover more" portion of the individual reviews.

@caltrider sign off might be too strong, but I'll want them to understand how we're describing the relationship.  They might have specific (legal) ways they need to describe the editorial partnership.

**Comment by caltrider** [comment]
@brettgaylor Whoo...sounds good.  The fewer people who have to officially sign off now, the better. I'm hoping to get final sign-off from Abigail and Marshall on the reviews tomorrow and some of copy tomorrow so I can move on and focus on blurb writing which doesn't require sign offs. I'll prioritize writing all the website copy and our "why we made this guide" tomorrow so you'll have to run by the Univision folks. And if you have time to reach out and see if they have any language for the partnership description in mind already, that'd be great.  Thanks.

**Comment by hannahkane** [comment]
@caltrider - is this ticket done?

**Comment by caltrider** [comment]
@hannahkane Yes, it's done.  It's here under ["Why we made this"](https://docs.google.com/document/d/1FOvs7w0HLpMcYSXXCdX3uNilKDx8Zd-3Sj1EMj2ikEQ/edit)

**Comment by hannahkane** [comment]
Awesome. Closing!
