### ISSUE TITLE
Create a graphic for use in Gizmodo/Univision articles

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#1085]
The articles they write will need to have some callout around the partnership, and a link to either the buyer's guide or to a landing page they create that holds all of their partnership content.

We need to design a banner with our/their logo that links to this page.

**Comment by hannahkane** [comment]
What's the deadline for this, @brettgaylor?

**Comment by brettgaylor** [comment]
Will find out Thursday and update here

**Comment by brettgaylor** [comment]
We need this by 10/27.  Is that possible @beccaklam ?

Will add dimensions here as I have them

**Comment by brettgaylor** [comment]
3 items:
- [ ] end card for video 1920x1080. Privacy Not Included campaign logo, included logos of Mozilla and Riseup
Item 2
- [ ] graphic for bottom of articles. Spanish translation of text to come
- [ ] graphic for shared landing page header. dimensions and wording to come.

@TheoChevalier do we have a spanish translation yet for "Privacy Not Included"?

**Comment by TheoChevalier** [comment]
@brettgaylor Not yet, but this is part of the first batch of content that we are sending on Monday. I should know more next week about when this will be ready, but will mention the UI strings are a priority.

**Comment by HPaulJohnson** [comment]
@brettgaylor any specific size for the two footer/header graphics. 

we are working on some general brand assets that will say 

*privacy not included
a holiday buyer's guide from moz://a

We can easily export in any size/format you prefer. just let us know.

**Comment by beccaklam** [comment]
@brettgaylor Sorry for the late reply! Yeah that should be possible. I'm still a little fuzzy on what exactly you're looking for, just a graphic with logos?

**Comment by brettgaylor** [comment]
So the only exact size requirements are the one for the video, which is above.  Basically, we want a "Logo" for the project - is there a wordmark or graphic that we are using that includes "Privacy Not Included?"  It should also have the mozilla wordmark.

They let me know that they can just use the video asset for the other needs they have, and adapt it themselves.  So we should give them a .PSD file and fonts?

**Comment by beccaklam** [comment]
@brettgaylor I'm developing the logo here: https://redpen.io/p/uz6c7f8b5519ab96a6 When it's gotten approval from (Paul? Temi? Jen?) I can give you the psd file and jpgs? i outlined the typeface so it's not really a font anymore if that makes sense.

**Comment by TheoChevalier** [comment]
“*Privacy Not Included” should be localized in Spanish by tomorrow.

Once the logo are approved, I will include “a holiday buyer's guide from moz://a” in the next batch to the vendor (hopefully sent by the end of the week)

**Comment by brettgaylor** [comment]
@beccaklam I saw the google drive of logos - these are great.

However I'm wondering if we could also create a version of the logo without the tagline that also includes the Mozilla wordmark?

Let me know!
Brett

**Comment by beccaklam** [comment]
Hey @brettgaylor I made these yesterday they should be in the same folder:
https://drive.google.com/drive/folders/0BzuBOR2VJQqURWd0OEdiMng0elE?usp=sharing
The images are looking a bit funky on my screen, can you download them and let me know what you see?

**Comment by TheoChevalier** [comment]
After some delays on the vendor side, finally have some Spanish translations for the logo:
`*Privacidad no incluida`
`GUÍA PARA EL COMPRADOR EN DÍAS FESTIVOS DE mozilla`

Exposed the initial version with all caps, but here it should be safe to just use the same capitalization as English.

**Comment by HPaulJohnson** [comment]
@brettgaylor can we close this one?

**Comment by brettgaylor** [comment]
yes!
