### ISSUE TITLE
Gather all images for Buyer's Guide product pages

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1087]
- [ ] Choose images
- [ ] Size appropriately

Anything else, @beccaklam @natalieworth @HPaulJohnson?

**Comment by hannahkane** [comment]
@beccaklam - are we done with this task?

**Comment by beccaklam** [comment]
@hannahkane Hey Hannah, not yet. We are still waiting on two images, one from Osmo and one from Parrot Pot though I do have some not so nice looking photos of those if we can't get better ones.

**Comment by beccaklam** [comment]
@hannahkane This is done.

**Comment by ScottDowne** [comment]
Is there an open ticket for resizing them? Images are on the site, but the load time is significant, also don't open staging on a data plan if you have a limit for now.

**Comment by beccaklam** [comment]
@ScottDowne I don't think there's a ticket yet, not sure if Paul worked on them? I think we'll talk about it during stand today. If it hasn't been done I can do it this afternoon.
