### ISSUE TITLE
Salesforce Migration: Plan for connecting PayPal Data

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#109]
About 70% of all donations to Mozilla come through PayPal. We do have some limited donor data already in Salesforce.

We need to put an integration in place so that PayPal donor information is regularly added to Salesforce records. SEE #108 and it looks like Zapier also offers a PayPal integration in addition to Stripe: https://zapier.com/zapbook/paypal/salesforce/. 

cc @cadecairos and @ScottDowne

**Comment by valianttry** [comment]
Important note: I believe any software like Zapier or other SF Marketplace Add Ons all have to be vetted by security + legal. (We need to confirm this process with Andrew Morales.)

**Comment by valianttry** [comment]
cc @drewmoto as an FYI

**Comment by damiankay** [comment]
Moved to private repo
