### ISSUE TITLE
Buyer's Guide domain

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#1090]
Will be advocacy.m.o/privacynotincluded

@HPaulJohnson to confirm, please!

**Comment by ScottDowne** [comment]
Should be on staging in a few mins: https://advocacy-mozilla-org-st-pr-395.herokuapp.com/en-US/privacynotincluded

Taking my name off assignees, leaving on Paul to confirm this change then we can close.

**Comment by HPaulJohnson** [comment]
works for me.
