### ISSUE TITLE
IoT survey: Produce localized graphics

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/Advocacy#1091]
Hey @natalieworth,

Italian is not yet ready, but you can go ahead with all the other languages. In case there are translations that are way too long for the design, please flag me and we can check with localizers if a shorter version is doable.

Translations are here: https://l10n.mozilla-community.org/langchecker/?website=6&file=other/2017/iot_results_assets.lang&action=translate&show

Also, this string is just here as a template for you to see how percentages have to be formatted for each language: https://l10n.mozilla-community.org/langchecker/?website=6&file=other/2017/iot_results_assets.lang&action=translate&show#string22

**Comment by TheoChevalier** [comment]
Italian is now ready!

**Comment by natalieworth** [comment]
Have the localized versions here: https://drive.google.com/drive/folders/0B20-0lpP23c0bGt1akRsUjJFZHM?usp=sharing
Data Viz, Email, and Social files contain the localized content.
Please proofread if you are able to/ have time.
cc @TheoChevalier @caltrider @beccaklam

**Comment by TheoChevalier** [comment]
Thanks @natalieworth ! The only issue I can spot is that in Data Viz, we’re missing images 06 and 08 in the FR folder (those are in Spanish)

**Comment by caltrider** [comment]
Thank you @natalieworth for cranking those out yesterday!!!!  @beccaklam and I have all the blogs created.  Natalie, if you can send the #6 and #8 graphics in French, we'll update those and then be close to good. Thank you too @TheoChevalier and @beccaklam !

**Comment by caltrider** [comment]
Hey @TheoChevalier @WillatMozFdn @tlasadea @KevZawacki @beccaklam @natalieworth 
Here are all the links to all the IoT survey blogs and the link to the drive folder with all the localized graphics including email and social.

**Graphics Folder:** https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0bGt1akRsUjJFZHM

**Blogs:**
EN: https://medium.com/mozilla-internet-citizen/10-fascinating-things-we-learned-when-we-asked-the-world-how-connected-are-you-2c9601c36ef0

FR: https://medium.com/mozilla-internet-citizen/10-d%C3%A9couvertes-int%C3%A9ressantes-gr%C3%A2ce-aux-r%C3%A9ponses-au-questionnaire-%C3%A0-quel-point-%C3%AAtes-vous-connect%C3%A9-e-ef8d761ec2dd

IT: https://medium.com/mozilla-internet-citizen/10-interessanti-scoperte-dal-sondaggio-quanto-sei-connesso-13ebaff39def

German: https://medium.com/mozilla-internet-citizen/10-faszinierende-dinge-die-wir-erfahren-haben-als-wir-die-welt-gefragt-haben-wie-vernetzt-sind-bc0a8b4c9ae3

PT-BR:  https://medium.com/mozilla-internet-citizen/10-coisas-fascinantes-que-aprendemos-quando-perguntamos-ao-mundo-o-quanto-voc%C3%AA-est%C3%A1-conectado-c06b2fe7b39

Spanish: https://medium.com/mozilla-internet-citizen/10-cosas-fascinantes-que-aprendimos-cuando-le-preguntamos-al-mundo-y-t%C3%BA-est%C3%A1s-conectado-1feef03e4c0b
