### ISSUE TITLE
Landing Page Variations for Fundraising Test w/ Paid Ads

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#1094]
Detailed description of work: We are launching a series of paid ads on Facebook to test messages and general donation behavior within that platform. Work on those ads is happening in #1057.

Since many of the people we reach with this channel will have less context about Mozilla, we'd like to do custom copy versions on the donate.moz.org landing page for each ad set. 

We will need a total of 3 landing page versions to test against the existing control and we will be supplying copy. 

*Start date: November 1, 2017* 
*Due date: November 6, 2017* 

CC: @WillatMozFdn @tlasadea @alanmoo @ScottDowne

**Comment by HPaulJohnson** [comment]
@tlasadea when you have final copy for the landing page versions can you please drop it in here?

**Comment by tlasadea** [comment]
[Here's the spreadsheet with the copy.](https://docs.google.com/spreadsheets/d/18_9IPhiB8SC9mtViBvkLCI1kV8LTJbdJzfLHFpITEPk/edit#gid=538597580)

The copy is in the tab labelled "Copy for Landing Pages" and the three varients are labelled at the top. 

CC @ScottDowne @HPaulJohnson

**Comment by HPaulJohnson** [comment]
this is done.
