### ISSUE TITLE
Localize new strings for monthly ask

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/Advocacy#1095]

**Comment by TheoChevalier** [comment]
@alanmoo anything I need to know?

**Comment by gideonthomas** [comment]
@TheoChevalier, I'm not sure if a ticket is needed for this (unless we use it to track a deadline for localizing the strings), but this is currently blocked on copy and implementation. This should be going into Pontoon once that's done. Feel free to suggest the right approach to track the work that will be done for this.

@alanmoo correct me if I misunderstood the purpose of this ticket.

**Comment by alanmoo** [comment]
This probably should have gone in the Donate repo (in fact, I'm going to move it there now), where we're tracking the rest of the fundraising work at a more detailed level. This was pretty much meant to be a placeholder of the work that needs to be done, so it's visible to us as we review our progress.

**Comment by alanmoo** [comment]
Moved to https://github.com/mozilla/donate.mozilla.org/issues/1843
