### ISSUE TITLE
Set Up Coral Talk Moderation

### ISSUE THREAD

**Issue by caltrider** [MozillaFoundation/Advocacy#1099]
Mostly for @ScottDowne @HPaulJohnson 

- [x] Add Paul and Jen as admins
- [x] Set up Janice as a STAFF EXPERT (Jen will talk to Janice)
- [ ] Add other members of the team as STAFF
- [ ] As a P2 when there is time, set up the Slack plug-in to allow moderation in Slack

**Comment by ScottDowne** [comment]
I made Paul an admin so he can do add people as mods and staff too.
