### ISSUE TITLE
QA / Feedback for Privacy Not Included buyer's guide website

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#1100]
This is a general ticket for bugs, comments and suggested enhancements (for future consideration) on https://advocacy.mozilla.org/en-US/privacynotincluded/

For items deemed to be bugs, please note if you feel like an item is urgent and tag me (@hpauljohnson) in the ticket to be triaged. 

Happy testing!

**Comment by alanmoo** [comment]
- [ ] The "Return to top" text at the bottom of [the main page](https://advocacy.mozilla.org/en-US/privacynotincluded/) doesn't do anything
- [ ] Product images are way too big and slow down page loading

**Comment by WillatMozFdn** [comment]
Home page, typo in this sentence: "Because Santa should be the only on watching you this holiday season."

**Comment by HPaulJohnson** [comment]
@WillatMozFdn are you sure that's a typo? i think that's the idea - Santa does watch you but your products shouldn't. Can you clarify? 

cc: @caltrider

**Comment by WillatMozFdn** [comment]
There's an "e" missing ... "the only on" is incorrect; "the only one" is what we need to say.

**Comment by HPaulJohnson** [comment]
ah, got it! thx- we'll fix

**Comment by TheoChevalier** [comment]
Fixed, thanks guys :)

**Comment by HPaulJohnson** [comment]
Carried over from old QA ticket, fix the hamburger menu on mobile version of site. Works only intermittently. cc @ScottDowne

**Comment by brettgaylor** [comment]
Hello - the Univision content should link to different pages depending on language.

Spanish:
http://www.univision.com/seguridad-online

English:
http://www.univision.com/onlinesafety

cc @ScottDowne

**Comment by TheoChevalier** [comment]
- [x] Share progress is empty in Spanish. (I think I’ve seen it working earlier, but right now sharing by email or Twitter from the Spanish page shares an empty string)
cc @ScottDowne

**Comment by TheoChevalier** [comment]
- [x] On https://share.mozilla.org/352/184298 , Back to the guide redirects to the English guide, the link should be https://advocacy.mozilla.org/es/privacynotincluded/ or just https://advocacy.mozilla.org/privacynotincluded/ for both locales if it can’t be a custom link.
cc @HPaulJohnson

**Comment by ScottDowne** [comment]
@brettgaylor the english link seems to redirect to spanish anyway.

**Comment by ScottDowne** [comment]
This we can close this now.

We have a post launch enhancement ticket here: https://github.com/MozillaFoundation/Advocacy/issues/1102
