### ISSUE TITLE
Email and Blog Graphic for Buyer's Guide

### ISSUE THREAD

**Issue by caltrider** [MozillaFoundation/Advocacy#1101]
We need an email call out graphic for the email that will go first thing on Tuesday.
It can be our branded/social stuff with the "See the guide" on it and "see the guide" should already be localized.

We also need a Medium blog header for the Medium blogs we'll post about this. I'm fine with the simple *privacy not included banner graphic.

@natalieworth @beccaklam @WillatMozFdn

**Comment by natalieworth** [comment]
Blog graphic is here https://drive.google.com/drive/folders/13hE5ng5hcoEEnYFj5eXvcwWpYCiAmz0t

**Comment by natalieworth** [comment]
Email callout is here https://drive.google.com/drive/folders/1EaORt_lJ5tEOyVJ-gJ8swVRH7uLpilKo (we went with option 3)
