### ISSUE TITLE
Suggested Enhancements for Buyer's Guide

### ISSUE THREAD

**Issue by caltrider** [MozillaFoundation/Advocacy#1102]
Some things for the site, after we've gotten it launched and caught our breath. Everyone feel free to add to this list. @HPaulJohnson @natalieworth @ScottDowne @TheoChevalier 

- [ ] Add "How we made this guide" in more visible places throughout the guide
- [ ] Add link out to the Methodology blog post from Janice (EN and ES)
- [ ] Add Slack integration for Coral Talk
- [x] Change the footer/donate language that's duplicate
- [ ] Add in a section for learning apps (as a post-Thanksgiving boost)

**Comment by natalieworth** [comment]
@ScottDowne @alanmoo I have a couple design changes left for the landing page if anyone gets time. 🙏 I posted them specifically in the redpen here:https://redpen.io/p/dk65305577d065880f
- [ ] reduce spacing between the '*privacy not included' and the subheading text on the landing page
- [x] change landing page background image to this https://drive.google.com/file/d/0B20-0lpP23c0TnFBdUlXWFFuVkE/view
- [x] Make the landing page illustration full page (get rid of the white space at the bottom)
- [x]  add this arrow at the bottom of the landing page illustration:https://drive.google.com/drive/u/0/folders/0B20-0lpP23c0NE9NRTRQVWhOTFE
- [x] Update the 'See this Guide' area to look like this (with the line) https://redpen.io/rj29d71ef4806d9f06
- [ ] I think under the 'See this Guide' we could add the 'Scroll to begin' back and it could solve our issue that some people were having with the UI @caltrider ? What do you think?

**Comment by alanmoo** [comment]
What's the Slack integration piece? Do you want notifications in #advocacy when people post comments or something like that?

**Comment by caltrider** [comment]
@alanmoo Right now @HPaulJohnson and I are the two moderators on Talk comments in the buyer's guide. We have to remember to login and keep an eye on the moderation panel in Talk. If we could set up a Slack channel (like #talkmod or something like that) where we would get slack notifications as the comments come in and can moderate from there, that would be super helpful.
cc: @ScottDowne

**Comment by alanmoo** [comment]
Thanks. We'll investigate what's possible with Talk and the way we have it installed.

**Comment by caltrider** [comment]
@natalieworth @ScottDowne @HPaulJohnson 
Thinking about how we make the "Why We Made This Guide" more prominent in the guide.
I'm open to suggestions.  Here's a couple of ideas:

1.  Would it be possible to put a floating link to on the landing page that stays up through the scroll?
2. Could we put it some how on the landing page so people would see a link to it before they started their scroll?

What other ideas do people have?

**Comment by nataliejworth** [comment]
I would +1 having a bar possibly at the bottom that floats as people read. I prefer that over a link in the copy at the top as I don’t want people to click on a link right away and be taken to a different page without getting a chance to scroll down? 
I’m thinking though we could have a small bar along the bottom (that is possible to dimiss) and maybe reads “find out why we made this guide” as a link? @caltrider @ScottDowne

**Comment by caltrider** [comment]
@nataliejworth @ScottDowne I like that idea a lot! Scott, can we do that?

**Comment by ScottDowne** [comment]
Dunno about my priorities, or who manages cross project priorities like this, so I don't know when I can get to this, or if I'll be able to even keep it on my radar for very long.

But yes, this is possible, but feels a bit like overkill with it being dismiss able and floating stuff.

If we want with something more static, I would be more willing and able to do this outside of my normal prioritization without impacting other projects.

**Comment by cadecairos** [comment]
There's a plugin for Talk that can integrate comments into a Slack channel via a WebHook. There is not a plugin for enabling Moderation from Slack. If we want a feature like that, we'll need to make it a project and assign a couple engineers to build it - But I'm not sure that's it's worth the investment.

**Comment by alanmoo** [comment]
If the comments to slack channel integration is easy, that sounds like it would achieve the goal of making it easier to stay on top of comments. Is that right @caltrider?

**Comment by caltrider** [comment]
Yes @alanmoo, it would make it easier if we got a slack notification. Although, right now the comment volume isn't so big this is a huge problem. However, if it is easy, it would be a help to get notifications in slack instead of having to login and remember to check the admin page for Talk.

**Comment by caltrider** [comment]
Quick update here: @alanmoo @ScottDowne @HPaulJohnson 
With the guide being mentioned in the NY Times Op-Ed this Saturday, it would be great to get the "Why we made this guide" made more prominent before then if we can.  There are a couple ideas above. I'm open to which ever we can do before the weekend.
Also, Janice's Methodology post is in legal review and then will get posted. That would also be something good to stick back in the footer (I think it was there at one point) so if we can questions from the (hopeful) bump in traffic this week we can point to it. I'll share that link as soon as I have it.

**Comment by natalieworth** [comment]
@caltrider @alanmoo What about either of these? Do you have copy suggestions too Jen?
<img width="1140" alt="screen shot 2017-11-30 at 1 37 20 pm" src="https://user-images.githubusercontent.com/14876567/33456645-d830a478-d5d4-11e7-862d-626f54eac962.png">
<img width="1150" alt="screen shot 2017-11-30 at 1 43 03 pm" src="https://user-images.githubusercontent.com/14876567/33456646-d84659f8-d5d4-11e7-884c-07f97cd09cf7.png">

**Comment by natalieworth** [comment]
added them on redpen here too https://redpen.io/fjac2703ae9bab4ad2

**Comment by alanmoo** [comment]
Is the first one a fixed white box when you scroll? If so, I'd prefer the second, if only because it doesn't complicate things and would be painless to add in.

**Comment by caltrider** [comment]
@alanmoo @natalieworth While I do like the the idea of it being sticky, I'm down for whatever doesn't complicate things. I think the second one could be the least confusing. In the first option the arrow points to it and could lead folks to believe scrolling will take them to that.  

As for copy, let's just keep it simple and have it read: "Why We Made This Guide"

**Comment by natalieworth** [comment]
Sweet I'm good with second option too! Less invasive than following people down the page too as they scroll.

**Comment by HPaulJohnson** [comment]
checking in on the status of implementing this change? @alanmoo do you know when we might fit this in?

**Comment by alanmoo** [comment]
It was on staging, I just deployed and it should be live momentarily. (Assuming you're talking about the "Why we made this guide" change. It's hard to track multiple tasks like this in one ticket)

**Comment by natalieworth** [comment]
@alanmoo @ScottDowne I have the 2018 updated illustrations for the Buyer's Guide landing page here: https://drive.google.com/drive/folders/1zfwGqBfS6n3y-z6UTQSvSuQ3f5GWycNU?usp=sharing

(is there a better ticket to put this in?)

**Comment by natalieworth** [comment]
added some share progress updates here too: https://redpen.io/p/cu46f0e5a29060a93c
cc @HPaulJohnson @tlasadea @beccaklam @caltrider

**Comment by beccaklam** [comment]
@alanmoo @ScottDowne @nataliejworth @HPaulJohnson @tlasadea @caltrider Here are the UI mockups for desktop and mobile. There's a couple options for desktop and a couple for mobile: https://redpen.io/p/ajf2da463e476f3864

**Comment by alanmoo** [comment]
Tracking v2 engineering updates at https://github.com/mozilla/advocacy.mozilla.org/projects/1

This ticket seems to be growing well beyond the scope of the original item- how do come to resolution on these types of things?
