### ISSUE TITLE
Change default amounts on donate.mozilla.org for EN-US, DE, and FR

### ISSUE THREAD

**Issue by WillatMozFdn** [MozillaFoundation/Advocacy#1103]
Detailed description of work:  Based on some testing in the snippet channel, we've realized that a set of default donation buttons with HIGHER amounts will actually raise us more in donations in the US, Germany and France.  The current default buttons (for both Euros and US dollars) are 3, 5 (selected), 10, and 20.  We need to change those to 3, 10 (selected), 25 and 50 ....in the locales/languages of EN-US, DE, and FR.

*Start date: November 7, 2017* 
*Due date: November 14, 2017* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @alanmoo @TheoChevalier

**Comment by TheoChevalier** [comment]
At first glance, this will require some engineering efforts, as we can’t simply update the presets here: https://github.com/mozilla/donate.mozilla.org/blob/master/src/data/currencies.js#L188-L200

Those are shared with all locales having EUR set as default currency, so all EU countries.
But it would be possible with the data structure used on bedrock, here I can update values for French only, for instance https://github.com/mozilla/bedrock/blob/master/bedrock/settings/base.py#L906-L911

**Comment by ScottDowne** [comment]
Theo is right. Currently we can only change this for each currency not
based on the locale. So without a bit of engineering it would be updated
for all euros. If that's acceptable for all euros to have the increased
amount this is an easy deal. Otherwise to keep other EU locales at the
current amount we would need something like bedrock has. Which isn't
unreasonable if valuable to us.

**Comment by WillatMozFdn** [comment]
OK, let's do it for US dollars and Euros then, I'm good with that. (Same amounts in both.) We didn't specifically test in let's say, Finland ... but, I'm pretty confident that a French + German result will hold up well in other EU countries too.

**Comment by ScottDowne** [comment]
Great

**Comment by TheoChevalier** [comment]
Updated in https://github.com/mozilla/donate.mozilla.org/commit/02e3e84e1dba1c276526bded929283eeb94b5c10
