### ISSUE TITLE
Add Device & App clarifying language to product pages

### ISSUE THREAD

**Issue by caltrider** [MozillaFoundation/Advocacy#1104]
Problem:  There is some confusion from people that things like the Fitbit Surge device doesn't have a camera but we say it has a camera because the app uses the camera on the device it is install in.

Solution: Let's a this short line of text (below) right under the "Can it spy on me?" question on each product review.  The text should be smaller than the "Can it spy on me" so it's not too intrusive.

TEXT:  *Includes both the device and the device's app

- [x] Add text on each product page under "Can it spy on me?" that reads: *Includes both the device and the device's app

@TheoChevalier Not sure how long this will take to get localized. Or if we can add this on the EN version now and then add in to ES version when it is localized.

cc: @ScottDowne @natalieworth @HPaulJohnson

**Comment by TheoChevalier** [comment]
@caltrider Should be okay to go with English first and catch up with Spanish. The Spanish team might be able to have a look as early as tonight

**Comment by TheoChevalier** [comment]
@caltrider Should be okay to go with English first and catch up with Spanish. The Spanish team might be able to have a look as early as tonight

**Comment by TheoChevalier** [comment]
@ScottDowne Added the string here https://github.com/mozilla/advocacy.mozilla.org/blob/master/buyers-guide-locales/en-US/review.properties#L13

**Comment by HPaulJohnson** [comment]
this looks done.
