### ISSUE TITLE
Round 2 creative for promoting buyer's guide

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#1105]
Let's use this new ticket to develop ideas for the next wave of creative assets to be used, primarily in social. 

We currently have 6 concepts we are developing in this doc: https://docs.google.com/document/d/1CM9bbIgvf6Z0DGqav6AMMogkbaERlRbejzbVvw03-cQ/edit

cc: @caltrider @natalieworth @tlasadea

**Comment by HPaulJohnson** [comment]
Updated list and timing per conversation this a.m. with @natalieworth, @caltrider, @tlasadea & Kfann. 

**This week (11/17):** 

1. _Old-timey xmas memes creative_

- [x] Purchase photos
- [x] Add type treatment
- [x] Export as static images for use on FB, TW and IG

2.  _Creepy Teddy Bear & Spying Santa creative_

- [x] Reformat creative from display ad campaign for use in social.
- [x] Export as .gif's for use on FB, TW and IG

**Next week (11/24)**

3. _Black Friday/Cyber Monday_ 

- [x] Capture in-product screenshots of Edwin the Duck, BB-8 and Hello Barbie
- [x] Write copy for Black Friday/Cyber Monday feature
- [x] Export as static images for use on FB, TW and IG 
- NOTE: we will need these by 11/23 as Black Friday is 11/24. 

4. _Onion-esque Fake Product Quotes_

- [x]  Create 6 short blurbs from the voice of various connected devices. Ex. "Wifi Baby Monitor Vows, “After This One, I’m Done”"
- [x] Identify 6 generic product shots for each
- [x] Apply quote as type treatment on image
- [x] Export as static images for use on FB, TW and IG

5. _Then vs. Now Creative_

- [x] Identify 6 popular toys from 1980's and 6 popular toys from 2017.
- [x] Apply type treatment to product photos, i.e. "1985. Batteries Not Included" "2017. Privacy Not Included"
- [x] Export as .gif's for use on FB, TW and IG. 

**Week after Next (12/1)**

6. _Holiday Guide Jingle_

- [x] Finalize lyrics for IoT days of xmas
- [x] Identify soothing images for video backdrop
- [x] Applying bouncing ball karaoke treatment
- [x] Export as videos for use on FB, TW and IG. 

- NOTE: Alt version of this is Kfann's suggestion of a more straightforward reading of actual 12 days of xmas, as sung by a home assistant. 

**TBD, pending time, need and capacity**

7.  _Commercial Parody_

- [ ] Kfann to write a script
- [ ] Pending availability find suitable video footage as backdrop
- [ ] Would be used as a 2nd video on FB, TW and IG. 

More notes on these creative concepts [here](https://docs.google.com/document/d/1CM9bbIgvf6Z0DGqav6AMMogkbaERlRbejzbVvw03-cQ/edit?ts=5a0b1220)

**Comment by tlasadea** [comment]
Red pen for numbers 1, 2, & 4 are [here](https://redpen.io/p/xrbfbfd99f07cf51e0)

**Comment by natalieworth** [comment]
1 (old Santa) and 2 (Display Ads) are uploaded in here and have been added to the Redpen https://drive.google.com/drive/folders/1PF14d4tPwOF1errRm05lizSv8eE8mCeA?usp=sharing

cc @tlasadea @HPaulJohnson

**Comment by tlasadea** [comment]
@natalieworth @HPaulJohnson Number 3 (Black Friday) has also been added to the above and here: https://drive.google.com/drive/folders/1x2uKdyigW6swXCBEjlEucGMQKWUKMTw6 can you @natalieworth please look lol I just did what was simple/easiest.

**Comment by natalieworth** [comment]
@tlasadea Sweet! Yah those are cool. Only thing is maybe the little yellow toy looks stretched. Not sure if it's a google folder view issue or in the original file?
<img width="1222" alt="screen shot 2017-11-21 at 11 59 58 am" src="https://user-images.githubusercontent.com/14876567/33094064-a8f7df28-ceb3-11e7-81fd-ca752a734a64.png">

**Comment by tlasadea** [comment]
@natalieworth updated.

I saw in Slack that you said you were gonna finish the jingle video, but think no. 4 - have all the images I sourced been edited as you were gonna do? Would be good to have that done so KFann can finish when he's back...actually not sure what he needs to do? We already have the headlines so could you just apply the type treatment - we need it for probably Cyber Monday at this point @HPaulJohnson @natalieworth

**Comment by beccaklam** [comment]
@tlasadea @HPaulJohnson @natalieworth Here are the mockups for the onion-esque social, i've only done the IG format so far, not sure if we wanted to do a landscape option for facebook and twitter? The first three photos Nat has already bought, the latter three (the ones tagged with 'option') are images i'm suggesting once i get the ok (from temi?) i can buy them. let me know if you think they work! https://redpen.io/p/zdf7f98b57baa51aba

**Comment by HPaulJohnson** [comment]
Left some comments in the redpen but these are very close. With a few tweaks I think we can call them done. 

In terms of buying the pics, go ahead and do that at your discretion assuming any one image is not ridiculously expensive. If you have questions ping me but don't let it be a blocker.

**Comment by beccaklam** [comment]
@HPaulJohnson @tlasadea Onion social here: https://drive.google.com/drive/folders/17RU-vPYmTuC1EBfM-s-vSi6MH5Y850ky?usp=sharing

**Comment by natalieworth** [comment]
@HPaulJohnson @tlasadea 12 Days of IoT video here here https://drive.google.com/drive/u/0/folders/17aoQotGWYEdLiGPPRoZ-PfnmG5RV62e8

**Comment by tlasadea** [comment]
I think, with the Then & Now video & 12 Days of IoT video - this is the last of the work done.

Truly terrific werk, team. Closing this - but feel free to re-open if I've missed something @HPaulJohnson @natalieworth @beccaklam

**Comment by beccaklam** [comment]
@tlasadea @HPaulJohnson Just adding in the advent calendar creative! https://drive.google.com/drive/folders/1hIfNPSUNFzzQFT2o7GTJ5HHQCz8-WDq-?usp=sharing
Temi, yesterday Paul and I talked about changing the it from the "12 days of Christmas" song to just products from the gift guide. The copy can just be what Jen wrote in the gift guide. We don't have to use this just wanted to give us another option if we wanted to test instagram.
Also just to put it in the ticket here is the link to the Then Vs Now vid: https://drive.google.com/a/mozilla.com/file/d/1Oh9lX40rVhaYeWlXHf3xIDRnM-4ZU0gh/view?usp=sharing
