### ISSUE TITLE
Buyer's Guide Snippet

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#1106]
Copy and icons for promoting the buyer's guide in the snippet. 

Scheduled to go-live week of 11/13.

cc: @caltrider

**Comment by HPaulJohnson** [comment]
Copy here: https://docs.google.com/document/d/1rOCmuJ9mF9y_e1OochGNEZgJWYituoztv3WUTbYeryk/edit

@natalieworth looks like we still need icons for these. can we prioritize this work tomorrow (11/9)

**Comment by natalieworth** [comment]
Rough snippet icon options are here: https://redpen.io/p/xd1975f1fc5fad313c
cc @HPaulJohnson @tlasadea @caltrider

**Comment by caltrider** [comment]
Update on snippet after a quick chat with Wes.  He says he'll run snippet this week Thursday-Friday and then next week Wednesday through the following Tuesday (all day on Cyber Monday).  Asked him about doing some snippet targeted at Black Friday or Cyber Monday. He says that those day targeted snippets don't always increase engagement that much but always worth a try.  I think I'll draft a couple targeted at Cyber Monday and send them along. If the work, great, if not, we'll still be up on those days.

And then he said he'll find some time to work us in in December. I'll follow up with him after our cyber monday push.

cc: @HPaulJohnson @natalieworth

**Comment by HPaulJohnson** [comment]
I think we are good to go on this ticket, so going to close. 

We've been in snippet at various point during campaign and will continue to show up there sporadically over the next few weeks. 

All the design/copy versions needed to support are complete.
