### ISSUE TITLE
Update share images/copy in OG tags on donate.mozilla.org

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#1108]
Detailed description of work: Update OG tags on donate.mozilla.org with updated copy and graphics. 

FB image: https://drive.google.com/a/mozilla.com/file/d/1xlUEsjyw6RQDPgcKq2Jt_lQWNFOY0XXn/view?usp=sharing
TW image: https://drive.google.com/a/mozilla.com/file/d/1VvswfOHMoBn7Qi6Wn9Z2VcoGR9IgckmC/view?usp=sharing

All share OG tag info (above images need to be hosted and links below updated): 

`<meta` property="og:description" content="I donated to @mozilla today because I #lovetheweb. Join me and help fight for a better and healthier internet, for all"/>

`<meta` property="og:image" content=“[INSERT IMAGE LINK“/>

`<meta` name="twitter:card" content="summary_large_image"/>

`<meta` name="twitter:site" content="@mozilla"/>

`<meta` name="twitter:title" content="Support Mozilla"/>

`<meta` name="twitter:description" content="I donated to @mozilla today because I #lovetheweb. Join me & help fight for a better & healthier internet, for all"/>

`<meta` name="twitter:image" content=“[INSERT IMAGE LINK HERE]“/>

cc: @alanmoo @ScottDowne @WillatMozFdn

**Comment by HPaulJohnson** [comment]
Also, we are still using Share Progress for the post donate CTA. We'd like to test some new images there and to do so will need all of the images in this folder hosted somewhere we can link to via URL. 

https://drive.google.com/drive/folders/166r2cB5jzmdLd1qB1ikDJ4vCX3CWpGnd

NOTE: if an alternate image from this testing emerges as a winner we would want to update the OG image tag as well. TBD based on results.

**Comment by alanmoo** [comment]
@gvn Scott's got some other stuff he's working on, this seems like the kind of thing I think you might have some time for. Feel free to ask if you've got any questions.

**Comment by TheoChevalier** [comment]
@HPaulJohnson I’ve been thinking about what we could do for other languages, and got some ideas.

- Once we know which image performs best in English, localize it in, say, French and German
- Create a generic image for other locales (without text)
- Tweets/FB desc can be localized in all languages (just need to expose the new copy)

How does this sound to you? Doable?

**Comment by HPaulJohnson** [comment]
Good call, @TheoChevalier. I'll have the a version of these initial images stripped of text with just a Moz logo. 

We've used this copy previously (last year I think) so we might already have it localized?

**Comment by HPaulJohnson** [comment]
Here are some generic share images we can use for non-English locales:

FB: https://drive.google.com/a/mozilla.com/file/d/1q0iLRZzljyx_FTjGUeRaxIsSxKT-vyJL/view?usp=sharing
TW: https://drive.google.com/a/mozilla.com/file/d/1AVWs8pdUWY62Z6iwiVkuZZroHiBM-Zt9/view?usp=sharing

**Comment by TheoChevalier** [comment]
Hm, I don’t remember this copy, maybe you used it only in ads?

It looks like we are still using this one on the website for social sharing, for all locales
![eoy_facebook_v1 a152496406bad899d1a920f6d6b9f507](https://user-images.githubusercontent.com/1294206/33481337-f4cb4b12-d68b-11e7-903b-86ad16f2f6da.png)

**Comment by HPaulJohnson** [comment]
sorry for the delayed response, @TheoChevalier 

The image you referenced is the one we are aiming to update with this ticket. Not complete yet as far as I know. 

For copy- did we have any localized social share copy we used last year that might still work? Otherwise, we could send these strings through for translation now. I'm fine either way.

**Comment by HPaulJohnson** [comment]
@ScottDowne do you have the images on a mozilla URL yet so that I can update Share Progress images?

**Comment by ScottDowne** [comment]
@HPaulJohnson I'm working on getting them on a cdn for once.

**Comment by ScottDowne** [comment]
@HPaulJohnson images should be here https://assets.mofoprod.net/fundraising/2017/ example https://assets.mofoprod.net/fundraising/2017/EOY-FB-Share-fist.png
