### ISSUE TITLE
Produce fundraising video in German

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/Advocacy#1109]
The script is being localized in German, it will be probably ready by the end of the week.

@natalieworth @brettgaylor Since German will be quite longer than English, do you think it would be possible to display the text screens slightly longer? That may be too much work, so maybe on a case by case once we have the translations?

For audio parts, we can go with simple built-in subtitles, unless you think we should do something else.

CC @WillatMozFdn @alanmoo

**Comment by TheoChevalier** [comment]
@natalieworth Translations are ready, earlier than expected https://docs.google.com/document/d/1_rut5iS7zxArU4NlNToGCtuneszXIF5KzINYsqAkKio/edit
Let me know if you see issues

**Comment by natalieworth** [comment]
@TheoChevalier Thanks! I'll do this tomorrow morning

**Comment by natalieworth** [comment]
@TheoChevalier German version of the video is here [Fundraising-video-DE.mp4](https://drive.google.com/file/d/15rkzzJ2nnzWcgPt5NusWjqSoFQCKD8Kp/view)

**Comment by TheoChevalier** [comment]
@natalieworth Thanks!
It looks like the subtitles for the voices and the newspaper headlines are missing, any chance you can add that?
When there are headlines + voices at the same time, let’s add subtitles for the voice only

**Comment by TheoChevalier** [comment]
@natalieworth Does it look doable this week? I would like to avoid seeking approvals during holidays

**Comment by natalieworth** [comment]
@TheoChevalier Sorry! Just saw this message! I've updated the file to include the subtitles here: https://drive.google.com/file/d/1zW03tHre_2TlYV2lKzEFeKXdCvvxJ3N2/view

Thanks!

**Comment by TheoChevalier** [comment]
Thanks, video approved, we’re good to close this one :)
