### ISSUE TITLE
Update Facebook & Twitter Social Share Creative

### ISSUE THREAD

**Issue by tlasadea** [MozillaFoundation/Advocacy#1110]
The OpenGraph images for sharing post-donation need to be updated.

The copy can stay the same for consistence of the use of the hashtag. The images are [here](https://drive.google.com/open?id=166r2cB5jzmdLd1qB1ikDJ4vCX3CWpGnd). 

CC @alanmoo @HPaulJohnson

**Comment by alanmoo** [comment]
There's a bunch of images in there. Can you clarify what use case they individually have?

**Comment by tlasadea** [comment]
@alanmoo well the ones there are for FB & for Twitter — there are four different versions for share progress... @HPaulJohnson is share progress not used for the donate LP or does there only need to be one image for FB or Twitter?

**Comment by HPaulJohnson** [comment]
I think we have duplicate tickets on this. Details about what specific images we should use for donate site are in #1108

**Comment by gvn** [comment]
If this is a dupe can we please close it?

**Comment by alanmoo** [comment]
Yup, didn't realize #1108 existed when I asked for this ticket in #1107
