### ISSUE TITLE
Add Methodology Blog Post Link to the Buyer's Guide

### ISSUE THREAD

**Issue by caltrider** [MozillaFoundation/Advocacy#1111]
Janice has her research methodology blog post for the buyer's guide up on Medium. Legal folks wanted us to include this in the guide. 

Couple ways we could add this to the guide. I'm happy to do whatever is easiest.  
1. Add it to the footer using the copy "Research Methodology" and link out to the blog post
2. Add it to the product pages at the bottom using the copy "Research Methodology". 

@natalieworth @beccaklam @alanmoo @ScottDowne I'll let you guys decide what's the best/easiest way to pop this in.

Link to the Methodology blog post: (https://medium.com/@harraton/evaluating-the-products-in-privacy-not-included-b83f88691342)

**Comment by alanmoo** [comment]
I think the footer is easiest, though we'd probably want an icon next to it. This will be a quick add, just let us know what you think is best @natalieworth or @beccaklam.

**Comment by natalieworth** [comment]
@alanmoo we gotta icon! :) File for it is here:
https://drive.google.com/file/d/1hIx9VxKQn9ALJK0xD0BEXKo-G75EUie1/view

**Comment by alanmoo** [comment]
This happened.
