### ISSUE TITLE
Localized share images on donate.mozilla.org

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/Advocacy#1112]
Hey @kristinashu could you please create two localized versions of this graphic in French and German? https://raw.githubusercontent.com/mozilla/donate.mozilla.org/e5b927dd23af5bfef1ad8c282659e7df1b686e78/assets/images/twitter-card.png

I’m including the copy below

English: `Fight for a Healthy Internet`
German: `Kämpfe für ein gesundes Internet`
French: `Défendez un Internet sain`

English: `Donate to Mozilla`
German: `Spende an Mozilla`
French: `Faites un don à Mozilla`

**Comment by TheoChevalier** [comment]
(Just made a slight change in French)

**Comment by kristinashu** [comment]
@TheoChevalier thanks for the translations! Here are the images:

![eoy-share-french](https://user-images.githubusercontent.com/1068783/34179179-c942e87e-e4be-11e7-9db4-7acd8a022f3b.png)
![eoy-share-german](https://user-images.githubusercontent.com/1068783/34179180-c9572334-e4be-11e7-9f02-46e463a6d254.png)

**Comment by TheoChevalier** [comment]
Thanks @kristinashu ! Working on the implementation, we can close this one
