### ISSUE TITLE
Add Discover card logo (along with Amex/Visa/MC) on Stripe donate button for EN-US

### ISSUE THREAD

**Issue by WillatMozFdn** [MozillaFoundation/Advocacy#1113]
Detailed description of work: We have a handful of cases in the donate@ queue of people confused and wanting to donate using their Discover cards, but our blue donate button on https://donate.mozilla.org/en-US/ does not show the Discover logo.  However, in the US, we do in fact take Discover cards through Stripe!

So this project will add the Discover logo underneath (?) the Amex/MC/Visa logos (which will likely have to be shifted up just a nudge to make room) -- same approximate size & style.  Or, if it works better in some other layout style or pattern, totally open to that too.  Main thing is just approximate size parity.

Discover logos are here to download & adapt: 
https://www.discovernetwork.com/en-us/business-resources/free-signage-logos

Let me know if any questions?  Thanks!

*Start date: December 5, 2017* 
*Due date: December 12, 2017* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @HPaulJohnson

**Comment by cadecairos** [comment]
@WillatMozFdn I'm not the developer to take on this task - we should loop in @alanmoo to find someone to make the changes to the front end.

**Comment by WillatMozFdn** [comment]
OK thanks Chris.  @alanmoo can we get this quickie project in the pipeline soon-ish?  (Sorry, meant to mention this today during our meeting, but just plain forgot.)

**Comment by HPaulJohnson** [comment]
@beccaklam has offered to update button design tomorrow a.m.

**Comment by alanmoo** [comment]
There's potentially some additional logic around this. Are Amex and Discover mutually bound together in acceptance, or are there some countries where we accept Amex/Discover but not the other one? What about countries where we don't accept Amex, do we accept Discover there? (Choose BRL from the dropdown on donate.mozilla.org to see an example of why I'm asking).

**Comment by beccaklam** [comment]
@WillatMozFdn @HPaulJohnson @alanmoo Here is the updated design, let me know if you think the logos are too small?
![cc selected copy](https://user-images.githubusercontent.com/20977376/33670793-e3057d94-da73-11e7-9897-3b04e264ff1b.jpg)
![donate-mockup](https://user-images.githubusercontent.com/20977376/33670796-e737a3c4-da73-11e7-94e6-02ae63919183.jpg)

**Comment by WillatMozFdn** [comment]
@beccaklam I think that looks great!

@alanmoo -- yep, I chatted with @cade about this yesterday.  (Amex and Discover are two totally different systems, btw.)  He checked Stripe documentation; we can only accept Discover in USD, and he believes it's do-able to show this new graphic only when USD is selected.

**Comment by cade** [comment]
If you put all the images in separate `iframe`s, you can swap out the `src` attribute with Javascript when the dropdown value changes... You might need React for that though. Not sure.

**Comment by alanmoo** [comment]
👏 Nice. (@WillatMozFdn the person you're looking for is @cadecairos. This gentleman here is simply the best of sports)

@ScottDowne Can you point @beccaklam to the right files that need graphic updates so they're easier for someone to drop in the logic? I can't tell if at a quick glance how the sprites are generated.

**Comment by ScottDowne** [comment]
@beccaklam this is the payment logo file: https://github.com/mozilla/donate.mozilla.org/blob/master/assets/images/payment_logos_updated.4ca531c0b90d3635aef0c1fc78d5967e.png

Right now it's in a sprite sheet and not sure if we should separate them now, or land the Discover patch, then fix the sprite sheet issue.

**Comment by beccaklam** [comment]
@ScottDowne @alanmoo @WillatMozFdn @HPaulJohnson Sorry, did I miss something here? Am I making this change? Or am I suppose to direct these to someone?

**Comment by alanmoo** [comment]
Someone on my team will make the actual change in the code, but for getting the design into the code we need an update version of the graphic that Scott linked to above. (Note the colored and white versions with transparent background.) It can be posted here and we’ll put it in the repo. If that’s not something that you can do, please correct me, I thought that’s what Paul meant in his comment though.

**Comment by beccaklam** [comment]
@alanmoo Ah yes I get it now. I'll post in this ticket soon. Thanks!

**Comment by beccaklam** [comment]
@alanmoo @ScottDowne @WillatMozFdn @HPaulJohnson Updated payment logo file here: 
![payment-logos](https://user-images.githubusercontent.com/20977376/33734331-13a1c098-db5a-11e7-9026-3396f3fa7c9a.png)
