### ISSUE TITLE
Create shorter cuts of EOY Fundraising Video

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#1114]
We have a great EOY video, compliments of @natalieworth and @brettgaylor. 

The video clocks in at just under 2 mins and since we've consistently seen shorter perform better on social (and early results from our testing with this video indicate the same), we'd like to make some quick cuts of :15-:20 secs for use in FB and TW paid ad campaigns. 

I have 3 cuts that should work which I'll detail below. 

@natalieworth hoping you can tackle these (or at least 1 of them) this week before all hands?

cc: @tlasadea as an FYI for planning future paid fundraising ads.

**Comment by HPaulJohnson** [comment]
Version 1: Sydette

Opening Frame: 
<img width="929" alt="screen shot 2017-11-29 at 1 50 26 pm" src="https://user-images.githubusercontent.com/10078715/33634764-3ad64ba2-d9ca-11e7-90d5-551a39a6663b.png">

Middle Frame(s): 
Sydette's talking on camera from :31-:41

Outro Frame: 
<img width="921" alt="screen shot 2017-11-29 at 1 52 05 pm" src="https://user-images.githubusercontent.com/10078715/33634842-761fa578-d9ca-11e7-8a1f-b670b6629c45.png">

Final frame: 
Mozilla logo + donate.mozilla.org URL

**Comment by HPaulJohnson** [comment]
Version 2: Jennifer

Intro Frame:
<img width="919" alt="screen shot 2017-12-05 at 2 25 57 pm" src="https://user-images.githubusercontent.com/10078715/33634890-a063af0a-d9ca-11e7-90fb-7cf5a144277c.png">

Middle Frame(s):
Jennifer Helsby talking on camera from :42-:53

Outro Frame: 
<img width="921" alt="screen shot 2017-11-29 at 1 52 05 pm" src="https://user-images.githubusercontent.com/10078715/33634916-c03647f2-d9ca-11e7-9fd5-135d550c8667.png">

Final frame:
Mozilla logo + donate.mozilla.org URL

**Comment by HPaulJohnson** [comment]
Version 3: Gigi

Intro Frame: 
<img width="920" alt="screen shot 2017-12-05 at 2 28 05 pm" src="https://user-images.githubusercontent.com/10078715/33634936-d3c97f78-d9ca-11e7-89bd-c87e729dc638.png">

Middle Frame(s):
Gigi Sohn talking on camera from 1:05-1:11

Outro Frame: 
<img width="921" alt="screen shot 2017-11-29 at 1 52 05 pm" src="https://user-images.githubusercontent.com/10078715/33634957-ecc7fa5e-d9ca-11e7-96d5-68fec92d8401.png">

Final frame:
Mozilla logo + donate.mozilla.org URL

**Comment by natalieworth** [comment]
@HPaulJohnson Got these done today! Let me know if you have any changes: https://drive.google.com/drive/folders/1u-NVXkvDKmghzHF9vCQ0qHQFsaiAzoZq

**Comment by tlasadea** [comment]
​Do we have cover images for these @natalieworth?

**Comment by tlasadea** [comment]
Once we have cover images for Facebook @natalieworth, this ticket can be closed CC @HPaulJohnson

**Comment by HPaulJohnson** [comment]
@natalieworth is on PTO today so let's just use FB tool to choose defaults for this.
