### ISSUE TITLE
Call Your Reps (Importance of civic engagement) Promo Video

### ISSUE THREAD

**Issue by tlasadea** [MozillaFoundation/Advocacy#1116]
This is for the work to do be done to develop a script + video that compells people to call their reps, to be used to drive people to call using our call tool.

**Comment by tlasadea** [comment]
@natalieworth [I've added example videos](https://docs.google.com/document/d/16kKXlwk7MMIiQEXL7z8Nu-Mf4eeG6c6UpjIQ4izLN7k/edit?ts=5a614773) for us to pull inspiration from in terms of the tone. 

[This is the calling tool](https://advocacy.mozilla.org/en-US/net-neutrality/), we can also use this for copy @natalieworth 

CC @HPaulJohnson

**Comment by natalieworth** [comment]
Copy document is here: https://docs.google.com/document/d/16kKXlwk7MMIiQEXL7z8Nu-Mf4eeG6c6UpjIQ4izLN7k/edit?ts=5a6a0812

**Comment by natalieworth** [comment]
Revised copy document (sent to Ashley/ policy) is here https://docs.google.com/document/d/1M8t09fbcnJpyN1t7h3F0GlPkPvI4gKgHBsF634rFgEc/edit

**Comment by tlasadea** [comment]
[Final videos are here.](https://drive.google.com/drive/folders/1TMal1fmIct6gmOVmJc_pNpcxfgTp2c9i)
