### ISSUE TITLE
Add Andrew Morales to GH repo

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#112]
Hi @cadecairos ,

Can you please add Andrew Morales to our Advocacy Github repo? Mostly to cc him on occasional requests related to Salesforce.

He currently has a handle in Github: 'drewmoto’. His email is drewmoto@gmail.com

Thanks!

CC @ScottDowne

**Comment by cadecairos** [comment]
done

**Comment by damiankay** [comment]
Thanks!
