### ISSUE TITLE
Nationbuilder template research 

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#113]
Hey @natalieworth, 

As per our meeting today, can you please: 
1. Look at existing themes to see if any of them match our needs
2. Look at common design elements that can be re-used across campaigns, and what can/should be customized for each campaign

Due: July 29

CC @lovegushwa

**Comment by damiankay** [comment]
Hey @natalieworth @lovegushwa - Andrea posted some examples of localized sites here #116

**Comment by natalieworth** [comment]
Created a google slide deck for this here: https://docs.google.com/presentation/d/1X31GHF9SclchaMY-K4Lo2XvUEAmmGrUjGHht-IHt0Q4/edit#slide=id.gd58133b56_0_69
I've been continually adding to it to help with making the wireframes and eventually also assisting with the UI, so going to keep this ticket open for now if that works @damiankay :)
