### ISSUE TITLE
Nationbuilder template elements

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#114]
Hey @ScottDowne,

Can you please identify for the design team which elements can be easily changed on a campaign by campaign basis? 

CC @lovegushwa @natalieworth

**Comment by ScottDowne** [comment]
Short answer is, from what I have seen, any element changed on a campaign by campaign basis is going to have a cost, but anything can be changed.

I'm starting to think blocking on this isn't useful. Let's just priorities for the needs of making an awesome campaign, and we'll figure out the technology. Right now all we got is nationbuilder, so we're doing this campaign in nationbuilder no matter what. Let's make a good campaign and push nationnbuilder to it's limits.
