### ISSUE TITLE
Define petition delivery method

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#115]
Hey @ScottDowne,

Can you please keep on your radar that we need to define where the petition data is being stored? 
- Salesforce?
- Nationbuilder?
- both?

CC @valianttry @shaghdoosti

**Comment by ScottDowne** [comment]
Hey @shaghdoosti I'm just trying to understand what is needed for delivery of petition signatures, and how that works.

I can ensure it gets into nationbuilder (or bsd in the past) but I've always been in the dark with what happens to it, when the time comes. I think knowing this is going to help me make better decisions.

**Comment by valianttry** [comment]
Notes on our choices:

Based on theory of change, decide optimum delivery method (real-time 1:1 delivery (email from citizen directly to target), bulk delivery (electronic version sent to target), bulk delivery (in-person printouts), other (?)

**Comment by ScottDowne** [comment]
@valianttry 

You may have indirectly answered my question? Not talking about salesforce, for this discussion let's assume salesforce is all hunky-dory.

I'm trying to figure out the place that data lives in when it's sent, like is a spreadsheet all we need? As long as we can export the thing as data, we can do delivery? Does it need to be through a third party like nationbuilder or BSD(as an example of a previous one) or someone else? Can we do it on our own?

Example, if we had a bunch of signatures in google sheets, could we do delivery, or would we need to import them into nationbuilder first?

**Comment by a-kilroy** [comment]
There is two parts of this question:
1) Petition signatures and related data (user comments, etc) that need to reach a target. 
2) Related User Identity Information - Things like name, address etc that are asked for (some times required) when a user 'signs' a petition.

For #1  @valianttry outlines the different delivery methods. Nationbuilder should have options for all three built into it. It's actually a (the?) main feature in any advocacy software.
For #2 we'd want to have this sync with Salesforce. 

This help? Did I make it more confusing?

**Comment by ScottDowne** [comment]
Yeah, salesforce is a given.

Maybe if I ask it this way, my confusion is where CAN we, not where should we, put that data before we deliver it. What are our options and how do these systems work.

**Comment by a-kilroy** [comment]
Well for #1 we'd most likely want it stored in Nationbuilder at least in the short term. We'll likely have some attributes we'll want to have in salesforce but past that, I don't think there is a need to move delivery data over.

**Comment by valianttry** [comment]
This ticket was confusing. We should have 2: 1 for making a campaign strategy decision about how we send signatures to the target(s). There should also be a 2nd ticket about how we collect / store data. @a-kilroy we send our email using SFMC and ExactTarget, so if we store data in Nationbuilder we don't have a way of identifying signers or signer segmentations, correct? Or is that what you meant by "some attributes we'll want in salesforce"?

**Comment by a-kilroy** [comment]
That's what I meant with "some attributes we'll want in salesforce"!

**Comment by damiankay** [comment]
Sorry guys - this was meant to help us decide on a delivery method for the signatures (and potentially other notes that are collected). I'll open a separate issue to track our decisions around now to collect / store data (user data plan). Thanks

**Comment by valianttry** [comment]
@shaghdoosti just affirmed the signature delivery strategy for Phase I and II of the campaign:

Phase I: We need to be able to build and download a list of signatures for either electronic delivery in bulk (PDF) or for printing. Signatures should include First name, last name, country (minimally) and optimally also include date of signature if possible. 

Phase II: We need to be able to send signatures in real-time electronically between a signor and their own elected official. (Target locales are critical to know in order to determine whether our systems are set up for this. For example, can UK signers send their letters directly to their own MP using Nationbuilder?)

This is what an in-person, printed out signature delivery looks like (often in partnership with media outreach team):
![signatures_delivered_-_google_search](https://cloud.githubusercontent.com/assets/9830371/17111436/6431cb72-5256-11e6-8b74-3c59b152020f.png)

**Comment by damiankay** [comment]
Easy to see how delivering actual pledges can be powerful!

@ScottDowne can you begin looking into whether it's possible to target signatures based on location within Nationbuilder?

**Comment by ScottDowne** [comment]
@damiankay I think you might need to unpack that question a bit.

It sounds like you're saying we only want signatures based on certain locations, but you might be asking if we can store their locale(address?) in the signatures so we can filter them later and give them to the proper places?

**Comment by damiankay** [comment]
Hi @ScottDowne - I would think that if there is no target selected for a particular locale, we would have a fallback solution (potentially just store the data). 

@valianttry @shaghdoosti - in addition to sending signatures in real-time electronically in phase 2, I'm assuming that we'll also want to store them.

**Comment by ScottDowne** [comment]
I think I got what I needed out of this. Salseforce is ideal, but it could also be done in anything else.

@damiankay There should always be a locale set, so we can always depend on that. That's how l10n should work.

There are unanswered questions in here, though, that are not to me, and it's been opened for a few days now. I'm going to close this, questions around phase 2 should be asked in https://github.com/MozillaFoundation/Advocacy/issues/160 or filed in a new issue specifically around phase 2.
