### ISSUE TITLE
Share examples of localized sites

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#116]
Hey @valianttry 

Would you mind checking in with your contacts at Nationbuilder to see if they can provide examples of localized sites, an potentially a contact to speak to about setting up advanced L10n? 

CC @ScottDowne

**Comment by valianttry** [comment]
Yes, our nationbuilder contacts sent this: 

Some awesome sites (some in other languages):
http://genun.unausa.org/
http://www.dci-palestine.org/
http://www.northeastcarpenters.org/
http://www.changeonsensemble.com/
http://www.joyeuxanniversaireabo.com/
http://www.plaidcymruarfon.org/

An example of a petition in another language is:
http://www.plaidcymruarfon.org/deiseb_prisiau_ynni_energy_prices_petition

Some information on the theme documentation is at http://nationbuilder.com/theme_documentation. This should walk through many of the questions they have surrounding theme editing, liquid within NationBuilder, and many other design questions.

Unfortunately, I don't think we have modal implementation explicitly documented anywhere - typically it involves another javascript or jquery library. A good example of this though is http://www.bravelove.org with the signup form being rendered via a modal.

**Comment by damiankay** [comment]
Thanks @valianttry!

@ScottDowne @lovegushwa @natalieworth can you please have a look at the references that Andrea shared above?

**Comment by ScottDowne** [comment]
Those links show sites in english and other languages, which is not the same as having a site in multiple languages, or am I not seeing the way to change languages?

**Comment by damiankay** [comment]
@natalieworth @lovegushwa do you have examples of location switchers?

**Comment by ScottDowne** [comment]
It's not a huge issue for ui lang switcher. We target our users and already
know the locale for the significant amount of people. My 2 cents is a
locale switcher isn't worth it.

**Comment by damiankay** [comment]
Ok cool. I'm going to close this one then.
