### ISSUE TITLE
Salesforce migration: Obtain data records from Blue State Digital

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#117]
As BSD has by now received their termination letter, we need to get a data dump of our records. 

@cadecairos are you the one to manage the data dump? 

Here are some things to consider: 
- Are there multiple steps in the process? 
- What options/formats does BSD provide for data dump?

CC @valianttry @stephaniemcv @drewmoto

**Comment by valianttry** [comment]
@damiankay there are some security sensitivities as we discuss moving this amount of PII (personally identifiable information). I have an update from Blue State Digital on next steps but don't want to put them in a public repository unless we're 100% certain that's the route we want to go. @simonwex might have thoughts on this.

**Comment by valianttry** [comment]
See @cadecairos 's email -- all the BSD >> SFMC migration tickets should live in a secure repo. He's sending invites. ??

[--- Commented from Asana.com
#commenter Damian Kuehn
---[aa]

**Comment by damiankay** [comment]
Perfect - thanks for flagging @valianttry

**Comment by damiankay** [comment]
This has moved to a private repo
