### ISSUE TITLE
Salesforce Migration: Correlate existing records from BSD and SFDC

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#118]
We need to engage with DEG to get some background on existing contact records, as contacts may be in both SFMC and SFDC, as well as existing records in BSD. 
- Was ALL data moved over incl. Meta data? 
- What data lives where? 

CC @valianttry @drewmoto

**Comment by valianttry** [comment]
Please cc @stephaniemcv on all tickets about BSD >> SFMC as she knows our data best in both BSD and Salesforce ATM.

**Comment by damiankay** [comment]
Sure thing - I'd actually assigned this to Stephanie 👍
