### ISSUE TITLE
Salesforce Migration: Create project plan

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#119]
What does success look like?
When do we launch? I.e. define dates

CC @valianttry

**Comment by damiankay** [comment]
@valianttry - can you help me with success metrics for this project? I'd like to tie them in with testing if possible.

**Comment by valianttry** [comment]
I would start with these as success metrics, but invite @stephaniemcv or @simonwex or @cadecairos to add / edit these:

-- Data stored in BSD is analyzed and categorized as "essential" vs. "non-essential"
-- Data we prioritize as "essential" for migration is successfully appended to corresponding records in SFMC (matched by email address)
-- Data that is deemed NOT essential and that are NOT migrated from BSD >> SFMC are deleted per our responsible data protocols

**Comment by damiankay** [comment]
Sorry @valianttry - I think that's a copy/paste error. I've removed those points. 

@stephaniemcv @simonwex do you have any input on what we should flag as success metrics for data migration from BSD to SF? Please see Andrea's notes above.

**Comment by simonwex** [comment]
I think @valianttry nailed it. Nothing to add.

**Comment by stephaniemcv** [comment]
Nothing to add here either.

**Comment by damiankay** [comment]
Great - thanks everyone. I'll log these in the project plan.

**Comment by damiankay** [comment]
Project plan can be found here: https://docs.google.com/document/d/1qV58fefef_hNbqsvla7SZXK8H3WuCfnrdwTsqA1C--I/edit#
