### ISSUE TITLE
Promotional Plan for Codemoji

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#12]
The goal is to have Codemoji in-market by end of Q2. This includes a testing phase and a wider promotional phase which we will be working on in conjunction with MoCo social and durable teams. 

Kevin has already drafted a Comms plan to support a public launch: 

https://docs.google.com/document/d/1iY6OkuVDSJgUx0QSuvjbIQpeRrb0SjPr81Kwyyd4jOA/edit

We should revisit as the tool as developed and look to finalize the overall promotional plan by 5/25. 

cc: @KevZawacki

**Comment by HPaulJohnson** [comment]
Codemoji will be live soon! To begin promotion we are actually going to run a few small scale tests to get feedback from users before rolling out with wider promotion. 

This "soft launch" will tentatively begin next week, 6/2. The following items are being worked on to support this launch: 

Building Codemoji on learning. domain #38 
Landing Page for Codemoji traffic #11 
Email copy and design #26 and #27
Social Media promo #42 

After testing and collecting feedback we'll evaluate next phase/rollout, ideally ahead of London. Post-London we can work with durable and social teams on a wider promotion plan + @KevZawacki's comms plan above.

**Comment by KevZawacki** [comment]
@HPaulJohnson Laura Napoli raised the idea of sharing Codemoji with a few friendly consumer tech reporters next week. I believe she / Issues Durable would drive that outreach. 

The pitch would be, "Mozilla is experimenting with educational advocacy games -- and we're inviting a small group of reporters to share their thoughts on this beta." 

Your thoughts?

**Comment by HPaulJohnson** [comment]
@KevZawacki what's the upside/benefit of doing this?

**Comment by KevZawacki** [comment]
@HPaulJohnson A few possible upsides: gauging press reaction; seeding a few early, positive stories; and deepening relationships with the select reporters. 

Of course, we also risk kicking off a bigger news cycle (which we want to avoid right now), or simply getting bad reviews. Maybe we await email test feedback first.

**Comment by valianttry** [comment]
+1 on waiting for email feedback before sharing more publicly. Given this is such a new strategy, my gut says we should play it safe... and address any UX challenges / feedback before unleashing on the world. My .02.

But generally i think a press push is interesting! I also wonder if any "cultural" or art or education media would be interested, like Colossal or Mental Floss.

**Comment by KevZawacki** [comment]
@valianttry Duly noted. When the time comes, there are a lot of neat educational resources (NYT Learning Network, for example) that would be interested.

**Comment by valianttry** [comment]
??

[--- Commented from Asana.com
#commenter Damian Kuehn
---[aa]

**Comment by HPaulJohnson** [comment]
Wave 1 of promotion complete. 
Wave 2 of promotion being planned around World Emoji Day. Those promos are being planned in individual tickets elsewhere so I'm closing his one for now.
