### ISSUE TITLE
Sign service agreement with Nationbuilder

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#123]
Will need to work with Mozilla legal and finance departments. 

Due August 1

CC @a-kilroy @simonwex

**Comment by valianttry** [comment]
I've already launched the needed bugs in bugzilla to facilitate this work: 

Vendor review bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1288546

Contract bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1288139

Security review bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1277667

**Comment by damiankay** [comment]
How are these going @valianttry ? Anything I can do?

**Comment by valianttry** [comment]
Current hangup: Waiting for Nationbuilder to send back the contract with markups (edits). 🐢

**Comment by valianttry** [comment]
Currently waiting for Nationbuilder to send back a markup from their legal team.

**Comment by valianttry** [comment]
Received markup. Mozilla legal team has markup and I'm hoping to schedule a quick call so our legal teams can just hammer out final details.

**Comment by valianttry** [comment]
Contract is fully executed and on file.
