### ISSUE TITLE
Secure external Nationbuilder resources / contractors

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#124]
Arielle has posted an RFQ for external Nationbuilder resources. 

The posting can be found here: https://docs.google.com/document/d/1k7k3-p3vGBbHhB-oVbtUYTlalMHaF9sbMDcUrMT9ums/edit?usp=sharing

Can you please keep us up to date on submissions and a shortlist here? 

We've identified July 29th as the due date for final contract approval. 

CC @simonwex @valianttry

**Comment by a-kilroy** [comment]
I've already gotten one proposal. I am expecting at least 2 more today. How are we moving forward with these? I can do a summary write up tomorrow morning my time, but I'd like to know who is the final decider on agency and how we get to that decision. Is it @valianttry or George? Also do we want to add George to this repo?

**Comment by damiankay** [comment]
I've asked George about that, esp. seeing that he's away this week (however he said that he'll check email Mon-Wed). I'll follow up to get a clear answer. 

I'll also try to have George added to the repo - I was thinking the same thing. 

Thanks!
