### ISSUE TITLE
Define required features for Maker Party events 

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#125]
Can we build a "features and requirements" document for MP events? I took an initial try at this in the project brief linked below, but I'm sure that we should add more detail: 
https://docs.google.com/document/d/1g8wXqtjg52I8w8dkyRBKCwS-mjguNO6xidYeCirspY4/edit#

See user stories document: https://docs.google.com/spreadsheets/d/1hs5ULg3671t7c7DS7mmjrg4jPvmSC6RjU12p5palI8Q/edit#gid=0

Due July 27

CC @a-kilroy @ScottDowne @simonwex @valianttry

**Comment by simonwex** [comment]
@shaghdoosti could you share what conclusions you came to in today's call?

**Comment by simonwex** [comment]
@shaghdoosti could you share what conclusions you came to in today's call?

**Comment by damiankay** [comment]
Here's what I came up with (with input from @a-kilroy): https://docs.google.com/spreadsheets/d/1v6hU6ggrAlTCABRc67Fcg3CExI9x3v1lL1BL7gbtk5M/edit#gid=0

We can use this document for testing purposes. 

CC @geroter @shaghdoosti
