### ISSUE TITLE
List pages required for Maker Party website

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#126]
As part of this task we need to identify which pages live in Nationbuilder, and which live in learning.mozilla.org.

The key deliverable should be a site map. 

Due: July 27

CC @simonwex @a-kilroy @ScottDowne @lovegushwa @natalieworth

**Comment by damiankay** [comment]
@hannahkane - do you have a site map from 2014 that might help identify which pages we'll need? I understand that last year's Maker Party was more limited in scope and may not reflect the full functionality that we're creating this year. Thx!

**Comment by hannahkane** [comment]
hmmm...not sure I have anything from 2014. 

@sabrinang - did you design the Maker Party 2014 website? Do you have mockups somewhere?

**Comment by damiankay** [comment]
@hannahkane - I probably shouldn't have been so prescriptive. Assets from 2015 would be helpful as well, esp. when we get into design.

**Comment by hannahkane** [comment]
2015 site is still available here:
https://learning.mozilla.org/events (landing page)
https://learning.mozilla.org/events/resources (additional resources page)

Hope this helps!

**Comment by damiankay** [comment]
Thanks @hannahkane - that will be helpful from a design standpoint ??

[--- Commented from Asana.com
#commenter Damian Kuehn
---[aa]

**Comment by sabrinang** [comment]
I found the old maker party site archived on http://web.archive.org/web/20140718144348/http://party.webmaker.org/? there are a few missing images and broken links here and there but I hope it helps for reference.

**Comment by sabrinang** [comment]
I have a lot of Maker Party 2014 assets located here too: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_eRXdQRkVjaVJNNHM&usp=sharing 
and I can dig up any specific design files if needed just let me know

**Comment by damiankay** [comment]
Thanks so much @hannahkane @sabrinang !! That will be a huge help. ??

[--- Commented from Asana.com
#commenter Damian Kuehn
---[aa]

**Comment by damiankay** [comment]
@shaghdoosti will update by July 29 with more information on what pages / assets will be required.

**Comment by damiankay** [comment]
@shaghdoosti @lovegushwa let's reconnect to confirm the approach to creating the design for the MP site

**Comment by damiankay** [comment]
Here's a link to the initial straw dog that we created today:
https://docs.google.com/document/d/1driaq40M1b085sbyDoJSQAFkMsvEPvhnux3E-ZIkHN8/
