### ISSUE TITLE
Create systems to measure Maker Party data

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#127]
The following success metrics have been identified for this project: 
1. Number of events created
2. Number of returning event leaders
3. Number of new event leaders
4. Number of support requests
5. User paths started / completed
6. General UX satisfaction of platform (User survey results show a 7+ rating on feedback  on a scale of 1-10)

We need to plan how we will measure each of these items. 

Due: July 29

**Comment by a-kilroy** [comment]
Have the numbers for each been established yet? If not, would be good to get those asap.

**Comment by damiankay** [comment]
Not yet - I've requested them from the Maker Party project leads. 

@shaghdoosti do you have any insights you can share on our targets or who can help define them?

**Comment by damiankay** [comment]
@shaghdoosti - who should take the lead on this?

**Comment by damiankay** [comment]
Hi @vojtechmzl - assigning this one over to you. If you've covered this in other tickets please feel free to close.

**Comment by valianttry** [comment]
@vojtechmzl just lifting this up -- you working on a dashboard or metrics? If yes, please update and close 👍

**Comment by vojtechsedlak** [comment]
Yup, tracking system is being put in place and we will use the Data Studio for visualization. Closing this issue.
