### ISSUE TITLE
Maker Party: Complete User Data Plan

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#128]
We need to identify what data we're collecting, where it will be stored, security, etc. 

Due August 5

CC @simonwex @ScottDowne @valianttry @drewmoto

**Comment by damiankay** [comment]
Hi @a-kilroy - just checking to see if this was completed yet.

**Comment by a-kilroy** [comment]
Tentative yes. Reviewing with Andrew later before I can say it's 'done'. Also done here just means my very rough first version is done so that we have something to start with in time for this campaign.

**Comment by damiankay** [comment]
Right - totally makes sense. 

Can you please link to the rough version here when it's ready? 

Thanks!

**Comment by damiankay** [comment]
Hey @a-kilroy - any progress on this? Any blockers?

**Comment by a-kilroy** [comment]
v0.5 has gotten a pass of comments. Needs to be reconciled and set next steps. My biggest blocker is getting time from Marketing. I'll be working with Vojtech and Andrew to map the relevant field asap. @vojtechmozilla  has already done an amazing first pass that handle our immediate needs if needed. Though I think him and I both agree we'd love to have a bit more done by event launch.

**Comment by damiankay** [comment]
@a-kilroy Let me know if I can help wrangle a meeting with Marketing. I imagine it's hard from your time zone. Thx!

**Comment by damiankay** [comment]
Hey @a-kilroy - any chance we'll have this in place before we begin QA on the Maker Party site?

**Comment by damiankay** [comment]
@drewmoto is this a requirement for Copyright campaign > SFDC integrations? If not, I'd like to close this issue, as it seems like it's more of a general user data document. 

CC @a-kilroy @vojtechmzl
