### ISSUE TITLE
Maker Party: Audit graphic / media assets

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#129]
We should start with an audit of existing assets and create / update assets as required.

See Maker Party asset audit for reference: https://docs.google.com/document/d/13mbofkesyawRqWeCAX3AhExRRz7VZWqGbnQXNiiu3iM/edit#

Due: August 5

CC @lovegushwa @ScottDowne

**Comment by damiankay** [comment]
See  #126 for past instances of Maker Party that we can reference when building new assets. 

@a-kilroy can you please confirm whether design will fall under the integration agency's scope of work?

**Comment by a-kilroy** [comment]
seems like the SOW has been set with them so we should have an answer now?
