### ISSUE TITLE
Design landing page for filevault/bitlocker email 

### ISSUE THREAD

**Issue by shaghdoosti** [MozillaFoundation/Advocacy#13]
This email is scheduled to go out on May 25. 

It would be good to have a button that says I did it. Aside from that this page is mostly instructional. Draft copy is below: 

https://docs.google.com/document/d/1jJE28HGJWEXWo45rgy6dJBSq7jNcO_a2oVI8xu5YlEE/edit

@lovegushwa

**Comment by natalieworth** [comment]
Moved content from this ticket: https://github.com/MozillaFoundation/encryption_campaign/issues/241
To follow up our discussion our first encryption tip is for people to use FileVault and the PC version. Right now -- we want to send them to a landing page that has instructions for a PC and Mac as well as a button that says 'I did it'.

If people press the button they will then land on a share page. Ideally this email would go out a few days after the encryption email goes out. In other words aiming for a 4th of April send.

**Comment by ScottDowne** [comment]
Build ticket is here https://github.com/MozillaFoundation/Advocacy/issues/14

**Comment by natalieworth** [comment]
@shaghdoosti Is it possible to get the draft content for this by Friday afternoon. I'm wanting to ship designs sooner for Scott so it's not too last minute for him to develop.

I thinking we will just need the step by step instructions for the filevault/ bitlocker installations? Even a draft by Friday would be great and then can update content on Monday.

**Comment by shaghdoosti** [comment]
Let me see what I can do!

**Comment by shaghdoosti** [comment]
Friends -- Here is the email copy (Currently going through approval not locked -- but please don't comment in the docs) 
https://docs.google.com/document/d/1jJE28HGJWEXWo45rgy6dJBSq7jNcO_a2oVI8xu5YlEE/edit

Here is the landing page copy  (Currently going through approval not locked -- but please don't comment in the docs) 

https://docs.google.com/document/d/16A0riwe6stAOPWCM5dYFqZt118Cn6WnDaAhhsnLhneU/edit?ts=56f978e4

The landing page copy doc should have everything you need.

**Comment by natalieworth** [comment]
@shaghdoosti @mmika We'll also need heading content and a question at the bottom for the 2nd page link to Shared Progress. This is the examples from the previous one:
<img width="590" alt="screen shot 2016-05-20 at 12 06 41 pm" src="https://cloud.githubusercontent.com/assets/14876567/15438924/565e3924-1e83-11e6-91bb-9f56d6598542.png">

**Comment by shaghdoosti** [comment]
Friends -- Copy for landing page and email is approved. (Ping @stephaniemcv @natalieworth @lovegushwa )

**Comment by ScottDowne** [comment]
Is this still targeted to go out tomorrow? If so, is there anything I can get started on? I don't need a whole day to implement, so this is still doable.

**Comment by stephaniemcv** [comment]
Tomorrow would be great, but we can flex to Thursday if needed.

**Comment by natalieworth** [comment]
Final designs for this are here @ScottDowne https://redpen.io/qj0b362b649e3776b0 
@shaghdoosti I still need the content for FAQ's section if we are still adding that? And any updates for the 2nd page (for sharing) if needed?

**Comment by shaghdoosti** [comment]
Hey -- So it's not really an FAQ, more like links to the software troubleshooting sites: 

FilveVault Entire hard drive: https://support.apple.com/en-us/HT204837

Selected drives: https://support.apple.com/en-us/HT201599

BitLocker
http://windows.microsoft.com/en-us/windows/protect-files-bitlocker-drive-encryption#1TC=windows-8

**Comment by natalieworth** [comment]
<img width="1026" alt="screen shot 2016-05-24 at 3 11 44 pm" src="https://cloud.githubusercontent.com/assets/14876567/15521686/ebb0e1fc-21c1-11e6-85cb-a4312660fbcc.png">
A: I'd just match the type to the previous list style.
cc @ScottDowne 
We'll have to do a Q + A with everyone tomorrow morning if you're out of time :)

**Comment by ScottDowne** [comment]
@shaghdoosti @natalieworth @HPaulJohnson @stephaniemcv This is where I got at end of day Tuesday:

https://warm-harbor-75615.herokuapp.com/encrypt-hard-drive/

and https://warm-harbor-75615.herokuapp.com/encrypt-hard-drive/thank-you/

All we need, as far as I can tell, until we're good to go is:
- [x] copy for thank you page
- [x] share progress buttons
- [x] og/twitter tags for share description
- [ ] any QA for design or copy.

(sorry if you got any of the above to me already, but turns out I'm only remembering things recorded in the ticket)

This is still doable for tomorrow, especially if you get back to me before tomorrow EST.

**Comment by HPaulJohnson** [comment]
@ScottDowne OG tags in ticket #14

**Comment by shaghdoosti** [comment]
@mimka wrote some copy for the share progress sharing -- @HPaulJohnson. Here: 

https://docs.google.com/document/d/1jGFDEnpVJje3sOfkNOPyKy_flsx0LyeGWdtyI1jpeZg/edit?pli=1

@natalieworth Which thank you page copy do you need?

**Comment by HPaulJohnson** [comment]
Thanks @mmika and @shaghdoosti. Buttons are setup (just need to switch to live URL when site goes live). 

Also, we are re-using the FB/Twitter (image) cards from software update page. I think it's ok for this too but you should verify: https://advocacy.mozilla.org/assets/01_SoftwareUpdateImage-Facebook.png

**Comment by ScottDowne** [comment]
So I just took an initial stab at the copy for the thank you page: https://warm-harbor-75615.herokuapp.com/encrypt-hard-drive/thank-you/

I just switched it from the stay secure copy that was "Tell others why updating is important!" to "Tell others why encryption is important!"

We can update it, but I kinda wanted it to at least match the content topic.

**Comment by natalieworth** [comment]
@shaghdoosti No worries, we're keeping the 2nd copy for the thank-you page the same as the previous one. I believe all that is left is design and copy Q+A for the landing page

**Comment by ScottDowne** [comment]
It's on staging now: https://advocacy-mozilla-org-staging.herokuapp.com/encrypt-hard-drive/

**Comment by natalieworth** [comment]
<img width="1001" alt="screen shot 2016-05-25 at 11 08 17 am" src="https://cloud.githubusercontent.com/assets/14876567/15551055/016a7f10-2269-11e6-8ba6-e40b429138e4.png">
*A: Can you make the padding on each side equal (so the text on the right doesn't go as far to the edge)
*B: Add a bit more of a margin at the bottom (about 10px should be good so there's a little more separation between the links and the button.

**Comment by ScottDowne** [comment]
@natalieworth ok, updated, and on staging.

**Comment by KevZawacki** [comment]
@natalieworth @shaghdoosti 

Hello! My QA:

Change subhead to "check out **these** step**-**by**-**step guides"

Mac instructions, step 5: Remove quotations around "Turn on FireVault" (we don't use quotes anywhere else in the copy)

PC instructions, step 3: Captilizate the "L" in the second instance of "BitLocker"

Change "FAQ Troubleshooting" to "FAQ and Troubleshooting"

Beneath, is there a reason we write "FireVault Entire hard drive" rather than just "FireVault"?

Change lower banner copy to: "Did this information help you install **the** software? Yes, **it** did!"

**Comment by ScottDowne** [comment]
@KevZawacki I made these copy changes, but if someone responds and doesn't agree with any of them, we can always make more changes.

**Comment by mmika** [comment]
@natalieworth Would you please add this copy to the BitLocker part of the landing page? Thanks! 

"Note: This is for Windows Vista or later. With earlier versions of Windows, BitLocker was not a built-in option. Don’t worry! You can still use BitLocker by downloading the software first."

**Comment by natalieworth** [comment]
@ScottDowne The copy can be found from Maryam above. I'd just add in italics and a slightly smaller font the copy like this:
<img width="633" alt="screen shot 2016-05-26 at 2 29 17 pm" src="https://cloud.githubusercontent.com/assets/14876567/15590878/c043a35e-234e-11e6-9500-dcc75ba87682.png">

**Comment by ScottDowne** [comment]
@natalieworth done and it's live.

**Comment by ScottDowne** [comment]
https://advocacy-mozilla-org-prod.herokuapp.com/encrypt-hard-drive/ should show it if it's not showing up because of cache.

**Comment by mmika** [comment]
thanks @natalieworth @ScottDowne
