### ISSUE TITLE
Maker Party website: Create wireframes

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#130]
Once we've completed the site map and documented required functionality, we should create wireframes.

References:
List required pages #126
Site map #158
List of features #75

First draft July 29

CC @lovegushwa @ScottDowne

**Comment by damiankay** [comment]
@a-kilroy will this fall under the integration agency's scope of work? If not we should get started right away. 

CC @lovegushwa @simonwex @ScottDowne

**Comment by lovegushwa** [comment]
@valianttry @shaghdoosti ... based on IA work in this ticket: 
https://github.com/MozillaFoundation/Advocacy/issues/158

@HPaulJohnson and I developed learning.mozilla.org as a modification of these two pages:
https://learning.mozilla.org/en-US/events
https://learning.mozilla.org/en-US/events/resources/#event-guides

We still need to identify appropriate page for Maker Party activities, @chadsansing is this the correct style page, or would you recommend something else?? : 
http://mozilla.github.io/webmaker-curriculum/ProtectingYourData/session02-secure-passwords.html 

All other event related pages will set on Nation Builder (see IA https://docs.google.com/document/d/1driaq40M1b085sbyDoJSQAFkMsvEPvhnux3E-ZIkHN8/edit# )

<img width="1342" alt="screen shot 2016-08-03 at 6 12 06 pm" src="https://cloud.githubusercontent.com/assets/12228435/17387153/ec8b6126-59a5-11e6-9b45-daa89ffd1c7e.png">
 wire-frames:

**Comment by chadsansing** [comment]
@lovegushwa - this page illustrates the current curriculum template:

http://chadsansing.github.io/curriculum-testing/color-picker-challenge/session01-color-picker-challenge.html#overview

Not sure the Maker Party activities need all of what we do here, so a different design might work, or we can try this template. I can put a sample together the week of 8/8/16.

**Comment by lovegushwa** [comment]
@chadsansing excellent. I think this template will do nicely. Looking forward to the sample. Thank you!

**Comment by a-kilroy** [comment]
Not sure how you all usually do it, but I'd love to see mobile wireframes too. Do you do them after desktop is approved? Or in relative parallel?

**Comment by chadsansing** [comment]
We use a template, @a-kilroy, that has a mobile stylesheet, as well. If the sample worked up next week doesn't fit the bill, happy to work w/ other designs.

**Comment by chadsansing** [comment]
@lovegushwa, @a-kilroy: sample activity built from the curriculum template here:

https://chadsansing.github.io/eu-maker-party-sample-activites/02-06-dont-break-the-net.html#overview

Also shared over on #184.

**Comment by lovegushwa** [comment]
Calling this one closed. Next step UI.

**Comment by a-kilroy** [comment]
Cool. If we can put the left side menu on the 'items to test', I'd love that. If we ever want to expand into languages without left alignment, we'll want an alternative layout.

**Comment by lovegushwa** [comment]
@a-kilroy great point, we are working within the existing learning.mozilla.org site constraints.  @HPaulJohnson do you know where we're at with MLN localization efforts?

**Comment by HPaulJohnson** [comment]
According to @ScottDowne learning.mozilla.org is fully localizable at this point.

**Comment by ScottDowne** [comment]
Yup,  :100: %

https://learning.mozilla.org/en-US/   :point_left: locale code   :+1:

**Comment by a-kilroy** [comment]
Well that's awesome! To be clear though, what I was referring to was the User Experience with those languages compared to the ability to present the content in those languages. For example, we'd never have a right aligned main menu for English because it would just feel wrong (or at least I'm assuming as such).
