### ISSUE TITLE
Integrate Nationbuilder with Mozilla systems

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#132]
Not sure what specific requirements are here yet. Will update asap. 

Due August 19

CC @simonwex @ScottDowne @a-kilroy

**Comment by ScottDowne** [comment]
Question, what do we need to integrate that's not part of https://github.com/MozillaFoundation/Advocacy/issues/80

**Comment by damiankay** [comment]
@ScottDowne I'm not sure yet! I think this will become more clear after discussions with the integration agency.

**Comment by ScottDowne** [comment]
Works for me. (I was mostly making sure I wasn't missing anything ;) )

**Comment by damiankay** [comment]
Closing this as the discussion is taking place here:  #80
