### ISSUE TITLE
Maker Party: Create email list for invites

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#134]
We need to decide whether we'll use Nationbuilder communicator or Salesforce to send these emails. This may be affected by the progress of the Foundation data migration, however not sure as the list may belong to Participation. 

Due: August 19

CC @valianttry @shaghdoosti @HPaulJohnson

**Comment by damiankay** [comment]
@stephaniemcv - I believe we're clear to send emails through Salesforce. Perhaps the only blocker is proper list segmentation. Can you confirm?

**Comment by stephaniemcv** [comment]
Currently in SF we have a MakerParty list of approx ~16,000

**Comment by damiankay** [comment]
@stephaniemcv @drewmoto are we in a position to use Salesforce to email Maker Party hosts / attendees? 

I believe there are two types of emails we would like to send: 
1. An invite to our list to participate in this year's Maker Party
2. A confirmation email to users who have signed up as hosts, with links to resources

CC @valianttry @shaghdoosti

**Comment by stephaniemcv** [comment]
@ldecoursy has provided a spreadsheet of contacts to me. There were 76 unique emails in the file.
Of those, there are 54 emails already in SalesForce but only 8 emails are in SalesForce AND marked as subscribed to the Maker Party list. 

Because the 54 are in SF we should have their opt-in/opt-out preferences and because they have a history of Maker Party I can subscribe them to the current list. For the other 22, we'd probably have to reach out to them and get their permission to add.

To send to just this group of 54 in SF, I'll need to do some fancy querying, but it is possible to send only to them rather than the full ~1600 Maker Party list.

**Comment by valianttry** [comment]
Let's set up a different bug for "transactional" emails (automated emails for registrants and hosts). Let's keep this bug for "invitations and calls for hosts and registration".

@stephaniemcv are you saying you can target an existing list in SFMC of ~1600 Maker Party people? We shouldn't go through the pain to add 22 individuals to Salesforce, it's really too much work for limited gain. @ldecoursy can you just send them a personal email asking them to sign up for Maker Party possibly? You'll likely get a higher response rate that way anyway. And if they register, they will be captured in Salesforce.

@stephaniemcv is there a larger segment that is also "learning" or "MLN"? We can talk about targeting that list as well with Maker Party invitation -- and inserted into the monthly newsletter? (I suspect there's a lot of overlap).

**Comment by stephaniemcv** [comment]
Yes, there is an existing list of ~1600. These are emails that came from
BSD and were assigned MakerParty as their subscription based on probably
even associated as decided by Adam and Jess.

MLN has a seperate list of ~129,000. This audience has gotten used to the
monthly newsletter, I would be interesting to see how they react to a
one-off email. In terms of communication we should also put the invite in
the monthly newsletter.

 I can put together a query to verify what crossover there is between MLN
and MP.

**Comment by ldecoursy** [comment]
@stephaniemcv If you can share the 22 emails I can reach out :)

**Comment by stephaniemcv** [comment]
FYI - There are currently ~14,600 email address who are subscribed to both MLN list and MakerParty list.

**Comment by stephaniemcv** [comment]
@ldecoursy Just shared a sheet with the emails. 2nd tab

**Comment by ldecoursy** [comment]
Got it! I'll send to those folks directly when we have the final invite copy. I'll just add a note referencing their past involvement ;)

**Comment by stephaniemcv** [comment]
The 54 hosts from the file that were also in SalesForce, now have Maker Party associated with their email subscriptions.
