### ISSUE TITLE
Maker Party website: Create a maintenance plan

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#138]
Details TBD

Due: August 31

CC @simonwex @a-kilroy @ScottDowne

**Comment by valianttry** [comment]
@ScottDowne do you recall what this was about? Please close this if it's no longer needed or fixed. If not, can you add some details on what this is?

**Comment by ScottDowne** [comment]
Yeah, happy to close until we have an issue with more details. I wasn't sure who was pushing for this, but it wasn't me.
