### ISSUE TITLE
Build landing page for filevault/bitlocker email

### ISSUE THREAD

**Issue by shaghdoosti** [MozillaFoundation/Advocacy#14]
This email is scheduled to go out on May 25. 

Drafts are here: 

https://docs.google.com/document/d/1jJE28HGJWEXWo45rgy6dJBSq7jNcO_a2oVI8xu5YlEE/edit

Would be good to look at this with fresh eyes. @mmika @valianttry @stephaniemcv

**Comment by natalieworth** [comment]
cc @ScottDowne

**Comment by HPaulJohnson** [comment]
@ScottDowne here's the info for updating the og tags on this page: 

`<meta` property="og:type" content="website"/>
`<meta` property="og:title" content=“Encrypt Your Hard Drive“/>
`<meta` property="og:site_name" content=“Learn about encryption - Mozilla Advocacy"/>
`<meta` property="og:url" content="https://advocacy.mozilla.org/encrypt-hard-drive/“/>
`<meta` property="og:description" content="Keep all that personal data safer: Take a few minutes encrypt your hard drive. The web will thank you. @Mozilla has a step-by-step guide to help.”/>
`<meta` property="og:image" content="https://advocacy.mozilla.org/assets/01_SoftwareUpdateImage-Facebook.png "/>
`<meta` name="twitter:card" content="summary_large_image"/>
`<meta` name="twitter:site" content="@mozilla"/>
`<meta` name="twitter:title" content=“Encrypt Your Hard Drive“/>
`<meta` name="twitter:description" content="Help safeguard privacy+security by encrypting your hard drive. @mozilla’s has a step-by-step guide to help.”/>
`<meta` name="twitter:image" content="https://advocacy.mozilla.org/assets/02_SoftwareUpdateImage-Twitter.png"/>

**Comment by ScottDowne** [comment]
@HPaulJohnson thanks! I just noticed I was doing my work in the design ticket.

**Comment by HPaulJohnson** [comment]
Share Progress code for share buttons on thank you page: 

Facebook:
`<div class='sp_168554 sp_fb_small' ></div>`

Twitter: 
`<div class='sp_168555 sp_tw_small' ></div>`

I'll just need to go in an update with the advocacy.moz.org URL once that's live.

**Comment by ScottDowne** [comment]
@HPaulJohnson cool, updated with share progress buttons, seems to be working: https://warm-harbor-75615.herokuapp.com/encrypt-hard-drive/thank-you/

**Comment by ScottDowne** [comment]
http://advocacy.mozilla.org/encrypt-hard-drive/

This was done, forgot to close this. Closing.
