### ISSUE TITLE
Maker Party website Privacy review

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#141]
Please log issues related to the website privacy review here. 

Due September 7

**Comment by a-kilroy** [comment]
What is the process here?

**Comment by damiankay** [comment]
Hey @a-kilroy - just getting everything into Github for now. I'll update as soon as I have more details. Thx

**Comment by valianttry** [comment]
Review was completed by Abigail -- details are in an email thread.
