### ISSUE TITLE
Maker Party website: Deploy to production

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#146]
Any notes relating to go-live can be shared here. 

Due: September 9

CC @simonwex @a-kilroy @cadecairos

**Comment by damiankay** [comment]
Planning for afternoon EST Sep 20th

**Comment by ScottDowne** [comment]
@damiankay dunno if we need a ticket for this, and also don't know if there is anything actionable on my end. I have issues that I need resolved before we can launch on the 20th, but those are tracked separately. So can we either close or reassign this to someone if there is something actionable on for example @cadecairos 's end?

**Comment by cadecairos** [comment]
I've got an open Bugzilla bug to purchase the domain BZ link here: MozillaFoundation/mofo-devops-private#28

**Comment by damiankay** [comment]
Sounds good. Let's close this one.
