### ISSUE TITLE
Write the petition body text signers are endorsing

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#149]
In close partnership with policy, write the message that will be sent from citizens to the target recipient. Or, the petition language that citizens will be “endorsing” or signing on to support.

Reference: Mozilla’s 5 Points for Copyright Reform in the EU
Promoting innovation, competition, and reinforcing the Digital Single Market
https://docs.google.com/document/d/1CuZF12jLkm-98DIw70VCHR-D3sGAz8iavrIAHGNyDJQ/edit

Due August 5

**Comment by shaghdoosti** [comment]
Working on this - Will touch base with Brett. Hoping to have this finalized by tomorrow COB.

**Comment by shaghdoosti** [comment]
We have the locked petition copy. It is below: 

https://docs.google.com/document/d/1SirP8cG_33HqEsnN-xizFpQBZvjv5pG7r51TlwxW_V8/edit
