### ISSUE TITLE
Confirm target locales for petition site (primary audience)

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#151]
We must confirm target locales for the petition site itself. This will influence both the design and site development choices. NOTE: This is a list growth opportunity for Mozilla. We want to build our supporter base in the EU as much as we can. 

Reference document: Strategic Engagement Plan for Copyright (prepared by Raegan for Policy)
https://docs.google.com/document/d/1sTBvsfQCC-D6Q31auuChup--P3_JtIbUd8nSEbfaV2A/edit

Petition targets are the following:
**EU Institutions:**
European Commission:
Commissioners Andrus Ansip & Gunter Oettinger; 
DG CONNECT & DG GROWTH (key units including Copyright) 
**European Parliament:**
Committee for Legal Affairs (JURI) in particular (list of members can be found here), but also Consumer Rights and Internal Market (IMCO), Industry and Research (ITRE), and Cultural Affairs (CULT); and the Parliament’s Copyright Working Group.

**Comment by valianttry** [comment]
I recommend we focus localization on the top 5 EU countries by population, with the goal of localizing the site to as many EU locales as we can. We are launching a simple V 1.0 of the site initially and we should localize to at least 2 locales in V 1.0. For V 2.0 we should focus on expanding locales. Here is a list of EU countries sorted by population size (source: [Wikipedia](https://en.wikipedia.org/wiki/List_of_European_Union_member_states_by_population)):

![list_of_european_union_member_states_by_population_-_wikipedia__the_free_encyclopedia](https://cloud.githubusercontent.com/assets/9830371/17079425/eb041abc-50c4-11e6-8f3a-84c48b807656.png)

**Comment by valianttry** [comment]
cc @shaghdoosti

**Comment by a-kilroy** [comment]
Is there an engagement plan for non English speakers we acquire during this time?

**Comment by valianttry** [comment]
@a-kilroy not yet on paper, no. We have two open JDs that will majorly influence this:
Email Strategist
https://careers.mozilla.org/position/oFzv3fww
and Localization PM:
https://careers.mozilla.org/position/o4zy3fwY

**Comment by a-kilroy** [comment]
Cool. This was a much discussed topic in my calls with marketing people. What do you think the timeline is for hiring those roles? From my perspective, how we try to engage with people has some dependency on our ability to follow up.

**Comment by valianttry** [comment]
@a-kilroy let's discuss Wed. Agree on all fronts. Realities of resources makes it difficult to do all this right and in the right order.

**Comment by damiankay** [comment]
Aiming to complete by Aug 5

**Comment by shaghdoosti** [comment]
Hey everyone - 

Just had a chat with Raegan, our recommendation is that we go for: 

Tier 1: English, French, German, Spanish, Polish 

Tier 2: Italian, Dutch, Czech, Bulgarian, 

For the other languages, we'll have them translated based on the passion/energy of those localisation communities.

**Comment by valianttry** [comment]
This is helpful @shaghdoosti -- questions:
- Are these for the petition only, or also maker party events?
- When you say "for the other languages" are you referring to unlisted languages (Teir 3+)? I just want to make certain

**Comment by shaghdoosti** [comment]
These are for petitions, videos, social and maker party. 

Yes - 'other languages' refers to unlisted languages which would be tier 3. (ie: most scandanavian speakers speak english so those languages are tier 3)

**Comment by shaghdoosti** [comment]
Target countries for maker party events are slightly different: Germany, France, Spain, Poland, Italy and the UK. (happy to dig into this more but it's worth noting the difference.)

**Comment by HPaulJohnson** [comment]
@shaghdoosti I can put in request to snippet team for petition promo (assuming you haven't already talked to them about this). want to clarify which languages we'll want to start with for 8/24? tier 1, tier 1+2? Let me know.

**Comment by shaghdoosti** [comment]
I think lets focus on tier 1 languages.

**Comment by ScottDowne** [comment]
This looks like a decision was made, and that we should close this.
