### ISSUE TITLE
Submit final EN petition copy to L10N for localization

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#152]
EN petition text ticket: #149 
Target locales #151

**Comment by shaghdoosti** [comment]
Updated on ticket #149 - aiming for this to happen on Tuesday COB.

**Comment by valianttry** [comment]
FYI I've given L10N a heads up, and we may be engaging with Kontextor as a backup vendor for this work as well.

**Comment by valianttry** [comment]
DONE localization is happening in pontoon here:
https://pontoon.mozilla.org/en-GB/mozilla-advocacy/Copyright/?string=154356
