### ISSUE TITLE
Define email channel plan

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#155]
Please change the name of this ticket as necessary :)

We should define a "channel plan" so that we understand the intersection between the cadence and strategy of emails, and content pieces of the public education campaign.

**Comment by shaghdoosti** [comment]
We have a first draft of this - waiting to confirm once we have more solid dates on website/makerparty.

**Comment by valianttry** [comment]
@shaghdoosti @stephaniemcv and myself spent some quality time on this schedule:

https://docs.google.com/spreadsheets/d/13qqXEY-6Spbol0ZaKs41saikYoNOPwFDlJRa5lvZGJA/edit#gid=4

**Comment by stephaniemcv** [comment]
One question I have is about auto responders - thanking them for signing the petition and if they sign up for the newsletter (confirm.welcome), currently in SalesForce we only have EN and DE.

**Comment by valianttry** [comment]
@stephaniemcv can you fire up a ticket for localizing that content? And can you drop the current language we have for confirm.welcome into that ticket?

**Comment by valianttry** [comment]
I'm going to close this ticket, we have a solid email plan!
