### ISSUE TITLE
Maker Party website: Create site map 

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#158]
@a-kilroy has started this process, however we need confirmation on which pages are required. 
https://docs.google.com/drawings/d/1Bo9V90cnRJXKaE0nV3Wr6KbghFtD6Mx2HKdIj0NFc7Y/edit

In parallel, @shaghdoosti has been working with @ldecoursy on website requirements. 

Let's connect and sync up our findings

Ideally we can nail this down by July 29

CC @ScottDowne @lovegushwa @natalieworth

**Comment by a-kilroy** [comment]
One thing not noted on my sitemap is any footer links. I _assume_ that we have a standard footer we use for most things and that those links can be included in design but not in the site since they _probably_ link to a central location. @damiankay can you confirm that this is the case? Otherwise we'll need to add pages for whatever footer links are needed.

**Comment by damiankay** [comment]
Will do - thanks for flagging

**Comment by ScottDowne** [comment]
We don't really have a standard footer design for advocacy related or foundation stuff. There are common themes, but it changes a bit from site to site.

The links however are a bit more common, but still a few differences.

A simple fairly generic footer example: https://advocacy.mozilla.org/en-US
-  contact us link: https://www.mozilla.org/contact/
-  twitter link: https://twitter.com/Mozilla
-  legal link: https://www.mozilla.org/about/legal.html
-  privacy link: https://www.mozilla.org/privacy/
-  donate link: https://donate.mozilla.org/

Then sometimes we add a link or two specific to the campaign, or change the twitter link to something specific to the campaign: https://advocacy.mozilla.org/en-US/encrypt/codemoji/1

My guess is we'll want to do something similar, but copying https://advocacy.mozilla.org/en-US is a great starting point.

**Comment by valianttry** [comment]
I'm assigning this to myself until we know who manages the relationship with Fission.

**Comment by lovegushwa** [comment]
@valianttry worked with @HPaulJohnson to refine, you will find the site map on the 2nd page under "Maker Party IA" ... Paul and I will own the content and design learning.mozilla part of this. 

https://docs.google.com/a/mozilla.com/document/d/1driaq40M1b085sbyDoJSQAFkMsvEPvhnux3E-ZIkHN8/edit?usp=sharing

**Comment by valianttry** [comment]
This appears to be done -- let's close this and make sure this get's shared with Fission @HPaulJohnson and @lovegushwa
