### ISSUE TITLE
Define Activities for Maker Party Events

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#161]
Develop a proposed plan for the activities to be featured during Maker Party. Discussion happening within the Maker Party Leads weekly check-ins with a goal of finalizing by next week. 

Initial ideas can be found here: 

https://docs.google.com/document/d/1kCV76zHYpldiEAtHgSZtZU599vmuhCjCZ-isSE4MOgo/edit

**Comment by HPaulJohnson** [comment]
@chadsansing did an awesome job of taking these from idea stage to detail here: 

https://docs.google.com/document/d/1Fg-iuFrNmm6tTbm917mlSdsZQTHI-8e--VmbY8aBygY/edit?ts=579f527d

We'll be looking for feedback from the larger MP Leads group on Thursday before finalizing this part. 

On track for 8/5 deadline.

**Comment by HPaulJohnson** [comment]
Meeting this week with MP leads to finalize/approve these activities. On track but moving to next milestone

**Comment by HPaulJohnson** [comment]
Final set of activities finalized and available here: 

 https://drive.google.com/drive/u/1/folders/0B0RBD2BW-srIdUV5d0NEVzNJY00

Meeting on Monday with @lovegushwa @chadsansing @flukeout to discuss design across landing page, activity templates and events platform.

**Comment by damiankay** [comment]
Going to close this as it looks like the 6 activities have been finalized. Thx!
