### ISSUE TITLE
Codemoji wrap report

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#162]
Can we create a report to summarize activity around Codemoji to-date? 

I'm thinking this would consist of:
- [ ] Social @HPaulJohnson 
- [ ] Email @stephaniemcv 
- [x] PR/Comms @KevZawacki 

Let me know if you have any concerns or think that other information should be included. 

Is there a template / format that has worked in the past? 

_Start date: September 1, 2016_
_Due date: October 31, 2016_

**Comment by KevZawacki** [comment]
Hi @damiankay, our coverage report for media can be found [here](https://docs.google.com/spreadsheets/d/1seVzFajQEwRiGUb7eHbirCk2aPcDH87J5jJerjQI5ak/edit#gid=0).

There's also [this blog post](https://mofokz.wordpress.com/2016/07/07/codemoji-comms-dissected/) I wrote reflecting on the comms aspect of the campaign.

**Comment by damiankay** [comment]
Awesome - thanks @KevZawacki 

I'll link out to those docs.

**Comment by stephaniemcv** [comment]
I don't know if there's been a unified report in the past. But it might be interesting to build a template of one. 
I need to finish researching if I can add action data to my Email Performance reports. I'll have it finished by or before due date.

**Comment by damiankay** [comment]
Thanks @stephaniemcv - I can probably just link to the three reports to for now, so that's perfect.

**Comment by stephaniemcv** [comment]
Passing this on to @vojtechmozilla re: finding action data in Google Analytics to associate with emails
