### ISSUE TITLE
Figure out how to ship multiple localized sites via nationbuilder

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#163]
Related: https://github.com/MozillaFoundation/Advocacy/issues/116

Right now the solution I'm aware of is multiple pages with different urls, one for each locale, code copied and pasted in each, and the translated strings manually placed in there.

The issue here is this is not scalable. I'm going to be spending a lot of pasting in changes times the number of locales we have. If we have 3 locales, my workload is times three. If we have 25 locales...

It' also highly prone to weird bugs, where I paste something in wrong because of human error, and there is a strange error on a random locale, but all the others are fine. Making me need to QA every feature per locale. Again, work times locales.

Short term (copyright petition and makerparty) I don't mind doing this process, because we're short on time and have very little options.

For anything after copyright, we need this fixed. It's not an acceptable flow.

**Comment by damiankay** [comment]
CC @valianttry @lovegushwa @natalieworth

**Comment by ScottDowne** [comment]
I think the actionable solution to this is to simply ask nationbuilder what they think about a scalable way to ship multiple locales.

**Comment by ScottDowne** [comment]
I heard back from my general support query.

They provided this link: http://nationbuilder.com/how_i_create_multilingual_websites

Which I already had. What concerns me about this all can be pointed out in that link with this text:

"Do all of the customization that you want to the theme. Any changes you make after you clone this theme and start translating it will be twice as much work so I recommend you go crazy now."

This means we need to get things right the first time, and then don't make any changes. They say twice as much work, but that's only with TWO languages. Just imagine 25... That's 25 times the work. Does not scale at all.

**Comment by damiankay** [comment]
Thanks for calling that out @ScottDowne. That's the definite downside to these types of integrations. We'll have to be very careful with our English / MVP quality assurance and also making sure that ALL stakeholders have signed off before we start to localize.

**Comment by ScottDowne** [comment]
I'm hoping Fission can include this in any training they give us. Closing.
