### ISSUE TITLE
Update Medium link on encryption site footer

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/Advocacy#164]
Hi there,

We've changed the URL of the [Mozilla Advocacy Medium page](https://medium.com/mozilla-advocacy), from /encryption-matters to /mozilla-advocacy.

Currently, the old URL is redirecting -- but that's won't always be the case. As such, can we update the Medium icon in the footer of https://advocacy.mozilla.org/encrypt to link to https://medium.com/mozilla-advocacy?

![screen shot 2016-07-27 at 2 57 47 pm](https://cloud.githubusercontent.com/assets/11045250/17188304/70ba4756-540a-11e6-9d90-1531da3d52b5.png)

cc @ScottDowne & @damiankay 

Thank you kindly, and pardon the disruption!

**Comment by damiankay** [comment]
Thanks for catching that @KevZawacki 

@ScottDowne - is this something we can do during the current sprint, or should we push it to the next one?

**Comment by ScottDowne** [comment]
This is super easy change, but I'm not actually following the request 100%. I'm still parsing though, just not super obvious yet.

**Comment by ScottDowne** [comment]
OK, I get it now, fixing.

**Comment by ScottDowne** [comment]
Done, and on prod.

You can test it here: https://advocacy-mozilla-org-prod.herokuapp.com/en-US/encrypt/codemoji/1

That's the prod link that doesn't have cache, actual production pulls it's content every few hours from the above link.

**Comment by KevZawacki** [comment]
Lightning fast -- thanks, @ScottDowne
