### ISSUE TITLE
Treatments for #copyfail micro-videos

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#165]
We'll aim to have at least 3 inserted into the treatment.

@KevZawacki can you assist in wrangling? 

 Due July 29th.

**Comment by KevZawacki** [comment]
Hi @brettgaylor. Can give a bit more clarity? Are we looking for a certain number of micro-treatments total? And where will they be inserted?

**Comment by brettgaylor** [comment]
I think we will be at 6 total, so 3 ready for tomorrow.

They'll be inserted into this deck:

https://docs.google.com/presentation/d/1lbbCBRoUcCns5BdRyCTNKznh4p7h0kLY73qfjeM4Crk/edit#slide=id.gd58133b56_0_69

And given a page each.

So how about:
GIF CSI
Tourist fail
Meme Jail

**Comment by KevZawacki** [comment]
@brettgaylor We now have seven treatments total, [here](https://docs.google.com/document/d/1IAQcju2LFJa10s7OOL4AikvM49PZylaY_kRkcO0xDUs/edit#). 

Here are the specific ones you mention above:

-- [CSI: GIF](https://docs.google.com/document/d/1IAQcju2LFJa10s7OOL4AikvM49PZylaY_kRkcO0xDUs/edit#bookmark=id.chfex3mkvnq8)

-- [Tourist Fail](https://docs.google.com/document/d/1IAQcju2LFJa10s7OOL4AikvM49PZylaY_kRkcO0xDUs/edit#bookmark=id.h0lmjqe6nvjw)

-- [Meme Jail](https://docs.google.com/document/d/1IAQcju2LFJa10s7OOL4AikvM49PZylaY_kRkcO0xDUs/edit#bookmark=id.4nho8rpusdiw)

If they need any edits, just let me know.

**Comment by brettgaylor** [comment]
Initial treatments approved!
