### ISSUE TITLE
Review "Gutcheck" for helping to assess campaigns for EU

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#168]
@HPaulJohnson - The brand durable team mentioned this resource for assessing campaigns in Europe: 
http://www.gutcheckit.com/ 

Let's see if it might be helpful assessing the effectiveness of our campaigns / messaging. 

CC @brettgaylor @lovegushwa

**Comment by damiankay** [comment]
@HPaulJohnson do you think it's worthwhile looking into this service? Or should we be using our community for this?

**Comment by HPaulJohnson** [comment]
@damiankay I think in certain cases Gutcheck can be a great solution for quantitative and qualitative feedback. That said, it's pretty costly (~$15K per project) and I'd only recommend we do when we've built in sufficient time to iterate and incorporate feedback. I'm not sure that's the case this time around with our media schedule. 

We have setup an informal panel of some EU-based colleagues how are willing to do some gut-checking for us and I'm hopeful we utilize them.

**Comment by brettgaylor** [comment]
Agreed.  I don't think we can realistically incorporate this for this round.

**Comment by damiankay** [comment]
$15K! Yikes. That certainly does not sound worthwhile. 

Great to hear that there are some EU contacts to help with this.
