### ISSUE TITLE
Confirm data transfer requirements

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#169]
Just setting up a bug to ensure that we don't lose track of this question. 

We need to confirm with the integration agency whether our data is going to move from Salesforce into Nationbuilder 

CC @valianttry @cadecairos @ScottDowne 

Due Aug 5

**Comment by ScottDowne** [comment]
Nothing is going to live in nationbuilder that needs to go to Salesforce. The current plan is to put data coming through nationbuilder into salesforce.

There is no functional reason to have salesforce data in nationbuilder.
