### ISSUE TITLE
Implement React-intl in advocacy.mozilla.org for localization page

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#17]
The page we'll need to localize is this one:
https://advocacy.mozilla.org/encrypt/hybrid/4

So that's the page we should set up L10N for

**Comment by ScottDowne** [comment]
Splitting this into two sub tasks: https://github.com/MozillaFoundation/Advocacy/issues/21

**Comment by ScottDowne** [comment]
@brettgaylor I forget, did you put the links for encrypt we need to translate into a ticket? This is the primary ticket on my radar, so any info you have should be added here. (I'm making the whole site localizable anyway, I was just wondering which links are MVP)

Related to l10n and encrypt: https://github.com/MozillaFoundation/Advocacy/issues/15 https://github.com/MozillaFoundation/Advocacy/issues/3 https://github.com/MozillaFoundation/Advocacy/issues/45

**Comment by ScottDowne** [comment]
@brettgaylor another question we need to consider/find some advice for. The big animated encrypt header, should we translate it? @alicoding says it's not a simple yes or no, and needs to consider branding more so than a direct translation. Example, there is usually no translation for the words "mozilla", "facebook", "coca-cola", etc. So, we need to figure out where the category that the word "encrypt" falls under.

If we're not promoting those links, then it's a question we don't need to answer now.

**Comment by ScottDowne** [comment]
Prod is now using react-intl and proper locale codes in the url with redirects.
