### ISSUE TITLE
Nationbuilder integration agency: define scope of work

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#170]
As part of the contract negotiation process, we need to define the scope of work for the integration agency. In internal discussions we seem to have agreed that we'd like them to handle back-end set up as well as design and front-end development, but we should confirm this internally and with the agency. 

Reference:
Functional scope (from project brief): https://docs.google.com/document/d/1g8wXqtjg52I8w8dkyRBKCwS-mjguNO6xidYeCirspY4/edit#heading=h.vdhcyxegi4ht
Required pages: https://docs.google.com/document/d/1driaq40M1b085sbyDoJSQAFkMsvEPvhnux3E-ZIkHN8/edit#

CC @simonwex @ScottDowne @cadecairos @lovegushwa

**Comment by valianttry** [comment]
@a-kilroy is out of pocket this week so I'm picking this up. I'm hoping Fission sends over at least an outline to help us get going but I'll start outlining the essentials here:
https://docs.google.com/document/d/1iikRekTFuQRFuklUcuZnldTUYr6ckbuhiS1MGhBhb4Q/edit

**Comment by valianttry** [comment]
Marking this done. Thanks everyone!
