### ISSUE TITLE
Add template to Advocacy issues

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#171]
Hi @cadecairos & @ScottDowne 

Can one of you please add the following items to new issues created in the Advocacy repo? 

Instructions on setting this up are here: https://help.github.com/articles/creating-an-issue-template-for-your-repository/

This is what I'm hoping to include in the issue description for new issues: 
"Detailed description of work:"
"Due date:"
"CC:"

Thanks!

Due: Aug 5

CC @valianttry

**Comment by damiankay** [comment]
@cadecairos is this done? Looks like it might not be on production?

**Comment by ScottDowne** [comment]
I missed this. Chris put a pull request and I just need to look at it. Thanks for the ping :)

**Comment by ScottDowne** [comment]
Oh, never mind, three days ago + weekend, makes it a fairly recent addition :)

Either way, looking now :)

**Comment by damiankay** [comment]
Very cool - thanks @ScottDowne & @cadecairos !
