### ISSUE TITLE
Collaborate with contractor on Copyright Explainer video script

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#172]
Please use this issue to track progress on the Copyright Explainer video for V1 of the petition website. 

We should aim to have a first draft of the script by Aug 5th, as it will need approvals from Policy, and will need to be shared with Legal and Marketing (I think). 

CC @brettgaylor @lovegushwa @KevZawacki @HPaulJohnson

**Comment by brettgaylor** [comment]
Script in progress here:
https://docs.google.com/document/d/1XwH-IJYKNBW2leiOc_kmtIlI4u4VM0sFoCAmjmst9dE/edit

**Comment by brettgaylor** [comment]
This script is now in approval process

**Comment by brettgaylor** [comment]
Script is now approved, contract signed!
