### ISSUE TITLE
Add Zenhub badge to README

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/Advocacy#174]
Zenhub is allowing us usage of their product under a non-profit license, and to show our thanks, we will add this badge to our README here:

[![](https://raw.githubusercontent.com/ZenHubIO/support/master/zenhub-badge.png)](https://zenhub.com)

```
[![](https://raw.githubusercontent.com/ZenHubIO/support/master/zenhub-badge.png)](https://zenhub.com)
```

**Comment by Startouf** [comment]
This badge no longer works
