### ISSUE TITLE
Build landing page for software update email

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Advocacy#18]
Build ticket for the 1st email landing page (softare update)

cc @ScottDowne

**Comment by ScottDowne** [comment]
@shaghdoosti or @valianttry Who if not either of you would be the one to decide on the url for this?

Example: `http://advocacy.mozilla.org/update` or `http://advocacy.mozilla.org/campaign/update` or something less generic like `http://advocacy.mozilla.org/stay-secure`

**Comment by HPaulJohnson** [comment]
@ScottDowne can you make sure this code snippet is included on the final landing page: 

 `<script` `src="//c.shpg.org/352/sp.js"></script>`

This will allow for us to use Share Progress to be used on this page. Once the the final URL is settled upon, I can generate the button code (which will also need to be included).

**Comment by ScottDowne** [comment]
@HPaulJohnson done, however, is it something I can include on the page globally even if it's not being used?

**Comment by HPaulJohnson** [comment]
@ScottDowne yea- that code snippet can and should be used globally on all the advocacy pages.

**Comment by ScottDowne** [comment]
perfect

**Comment by ScottDowne** [comment]
Tracking a list of things I still need to do. I already started to get a head start.

P1 items:
- [x] hook up ga tracking. Super important and critical to this page.
- [x] thank you page and share...
- [x] design qa
- [ ] copy qa
- [ ] og tags

P2 items:
- [x] mobile, it's actually pretty good out of the box, but could be optimized if time permits.
- [x] finish and test share progress
- [x] get final url, right now it's going to be advocacy.mozilla.org/stay-secure/
- [x] sticky button

@HPaulJohnson how hard is it to create the share progress buttons under the "advocacy.mozilla.org/stay-secure/" url then change it later if the url changes (I suspect it might not)

**Comment by ScottDowne** [comment]
@natalieworth @lovegushwa I put this together as a quick copy of the current designs so we can get a better sense what it's like when built: https://warm-harbor-75615.herokuapp.com/stay-secure/

**Comment by HPaulJohnson** [comment]
@ScottDowne i created buttons using the generic /encrypt URL. I'll need to go back and edit with the final URL before we go live. Also, we'll need a URL where we are hosting the Facebook share graphic so I can update Share Progress with that as well. Here's the FB/Twitter button snippets: 

Twitter: 
`<div` class='sp_167697 sp_tw_small' `></div>`

Facebook
`<div` class='sp_167698 sp_fb_small' `></div>`

**Comment by ScottDowne** [comment]
@HPaulJohnson the url is going to be https://advocacy.mozilla.org/stay-secure/

**Comment by natalieworth** [comment]
@ScottDowne A few design updates for the build site:
<img width="1168" alt="screen shot 2016-05-17 at 11 47 36 am" src="https://cloud.githubusercontent.com/assets/14876567/15335985/35bc5ed2-1c29-11e6-9639-f9dcd3f0406e.png">
- A: Increase pt/px size to 18 and increase weight to 400 for update titles
- B: Change +'s to #f16160 colour
- C: Is it possible to remove the extra white space at the bottom?
- D: Increase the heading font of 'Tell us you updated' to 28px (do you work in em's? I can give you em's if it's easier?)
- E: 1) Update font to Fira Sans (with 400 weight), 2) Change the hover state colour to #e24949 instead of white

**Comment by natalieworth** [comment]
@ScottDowne And just some changes for the drop down list too:
<img width="1169" alt="screen shot 2016-05-17 at 12 20 44 pm" src="https://cloud.githubusercontent.com/assets/14876567/15336118/cfa8ca1c-1c29-11e6-9036-f374f6b5ccb6.png">
- 1) Change font weight to 300, 2) If it's possible, could you also add a bit more spacing between the number list and where the text starts:
  <img width="696" alt="screen shot 2016-05-17 at 12 26 50 pm" src="https://cloud.githubusercontent.com/assets/14876567/15336274/af6da280-1c2a-11e6-9dc1-39cf0e1b4827.png">

**Comment by HPaulJohnson** [comment]
@ScottDowne here's the metadata for this page (for FB/Twitter defaults):

`<meta` property="og:type" content="website"/>
`<meta` property="og:title" content=“Update Your Software“/>
`<meta` property="og:site_name" content=“Learn about encryption - Mozilla Advocacy"/>
`<meta` property="og:url" content="https://advocacy.mozilla.org/stay-secure/"/>
`<meta` property="og:description" content="Keep all that personal data safer: Take a few minutes and update the software on all your devices -- including phones, tablets, and computers. The web will thank you. Update today with @Mozilla’s help."/>
`<meta` property="og:image" content="https://advocacy.mozilla.org/assets/01_SoftwareUpdateImage-Facebook.png "/>
`<meta` name="twitter:card" content="summary_large_image"/>
`<meta` name="twitter:site" content="@mozilla"/>
`<meta` name="twitter:title" content=“Update Your Software“/>
`<meta` name="twitter:description" content="Help safeguard privacy+security by updating your software. Update with @mozilla’s help. #iupdated"/>
`<meta` name="twitter:image" content="https://advocacy.mozilla.org/assets/02_SoftwareUpdateImage-Twitter.png"/>

**Comment by natalieworth** [comment]
Page 2 of the software email needs updated design and copy. Here is the original:
<img width="1439" alt="screen shot 2016-05-17 at 12 30 06 pm" src="https://cloud.githubusercontent.com/assets/14876567/15338090/344887ba-1c33-11e6-8b5a-baeb389c4b70.png">

This is the one I have updated so far:
<img width="890" alt="screen shot 2016-05-17 at 1 13 04 pm" src="https://cloud.githubusercontent.com/assets/14876567/15338099/3bfb75ee-1c33-11e6-88c4-ec0828252995.png">

cc @valianttry

**Comment by natalieworth** [comment]
@ScottDowne Page 2 design here:
<img width="983" alt="screen shot 2016-05-17 at 1 35 27 pm" src="https://cloud.githubusercontent.com/assets/14876567/15338360/6bc51f68-1c34-11e6-87cd-541bc7b72814.png">

**Comment by lovegushwa** [comment]
QA update your software:
- [ ] Windows
- [x] Mac
- [x] GNU/Linux
- [x] iPhone
- [x] Android
- [ ] Browsers

**Comment by lovegushwa** [comment]
Android:

@shaghdoosti I would change the language for part 2 and 3 of the Android update instructions to the following:
1. Tap the Menu icon (three horizontal line icon in the top left) and go to My apps and games.
2. Tap Update all, or update apps individually. Apps with an update available are labeled "Update."

**Comment by natalieworth** [comment]
Tested the Mac and iPhone updates on my own devices and both sets of instructions worked for me. I'm assuming since the browser links all open to independent instructions for each application, that we can't have that much control over it other than making sure the links are up to date.

**Comment by lovegushwa** [comment]
@shaghdoosti about Browsers, not sure this IE link is about updating:
http://pcsupport.about.com/od/browsers/fl/internet-explorer-version.htm

**Comment by KevZawacki** [comment]
Just reviewed. Copyedits and QA for [this page](https://warm-harbor-75615.herokuapp.com/stay-secure/) include:

**Right box**:
- First sentence: Change "makes" to "would make"
- Third sentence: Change "Letter" to "Letting"
- Third sentence: I suggest removing "in the end"
- Fourth sentence: I suggest breaking it into two sentence. So, it would read, "Mozilla cares about your privacy and security everywhere, not just on Firefox. The safer Internet is, the easier it is to create and keep it open"

**Left box (instructions)**:
- Linux instructions are in a different font
- This may be a design tweak, but can we differentiate the normal text from the commands? Like so:
  In the left pane, click "Check for updates" or In the left pane, click _**Check for updates**_
- iPhone instructions, number 2: Change "Click Updates on the bottom right corner" to "Click Updates in the bottom right corner"

**Footer**:
- Capitalize "Web"

**Comment by shaghdoosti** [comment]
@lovegushwa I'm happy with the copy edits you suggested.

**Comment by natalieworth** [comment]
@ScottDowne A few adjustments for page 2 here:
<img width="1358" alt="screen shot 2016-05-17 at 3 08 25 pm" src="https://cloud.githubusercontent.com/assets/14876567/15341061/4e074746-1c41-11e6-8e28-435dcd4fdb91.png">
- A: Increase the top padding (or margin?) to 90px. I think it feels a bit too heavy at the top right now
- B: 1) Is is possible to change so the facebook box is on the left side and twitter on the right?, 2) Apply the hover states for the boxes (twitter is #44c6f2 and facebook is #3b6db4)
- C: Increase padding here too, about 20px. It would be ideal if the spacing between the header and the white bounding box was the same as the bounding box and the lower text.
- D: Increase padding here too a bit. Possibly only to 70px. It doesn't have to be as much as the top, but it would be nice for a bit more space at the bottom.
- E: 1) Link font can be changed to the same size as 'Want to learn more about encryption?'

**Comment by ScottDowne** [comment]
This is where I got by the end of the day: https://warm-harbor-75615.herokuapp.com/stay-secure/

I think I got everything found above, but if I missed something, let me know!

**Comment by natalieworth** [comment]
@ScottDowne Thanks, this is looking great. Just one update would be the type underneath the title links:
<img width="373" alt="screen shot 2016-05-17 at 1 43 36 pm" src="https://cloud.githubusercontent.com/assets/14876567/15342787/ecb80258-1c4c-11e6-995f-5fb75dd35114.png">
Can we change the numbers and list to a lighter weight (300 would work). Like how it is here:
<img width="382" alt="screen shot 2016-05-17 at 4 33 14 pm" src="https://cloud.githubusercontent.com/assets/14876567/15342823/2483c5be-1c4d-11e6-8457-f517989026c2.png">

**Comment by natalieworth** [comment]
@ScottDowne One additional thing if you have time would be to also have the +'s change colour to #e24949 on hover? It's a just a minimal UX, but I'm thinking would be good to have the pink +'s consistent with the button. :)

**Comment by HPaulJohnson** [comment]
@ScottDowne I think there's something broken on one of the og tags. See this screenshot from Twitter where the headline is broken on the Twitter card.

https://www.evernote.com/shard/s46/sh/1e507a7c-de5d-41bd-ad1d-f2b104869fad/fcec6f61a7c0a921c96e65d58b9ad5b6

**Comment by ScottDowne** [comment]
@HPaulJohnson good catch, I think it's fixed. Was just some busted quotes being pasted from another place.

@natalieworth I can do those tweaks tomorrow I think.

**Comment by ScottDowne** [comment]
@natalieworth the bits of design feedback you had are done.

**Comment by natalieworth** [comment]
@ScottDowne Awesome, thank-you! Just a couple last things that I noticed with the type:
<img width="629" alt="screen shot 2016-05-18 at 9 41 55 am" src="https://cloud.githubusercontent.com/assets/14876567/15367229/fb296814-1cdc-11e6-9ef9-644f4a6ee43a.png">
<img width="1289" alt="screen shot 2016-05-18 at 9 42 09 am" src="https://cloud.githubusercontent.com/assets/14876567/15367231/fe349542-1cdc-11e6-9c11-4ea66c598e35.png">
- A: 1) Could we increase the spacing between the numbered list? (about 10px), 2) On the accordian tab's right side, can you increase padding to 20 px to reduce the line length:
  <img width="409" alt="screen shot 2016-05-18 at 9 51 47 am" src="https://cloud.githubusercontent.com/assets/14876567/15367496/2dbe3aa6-1cde-11e6-9dd1-ffc9ddd12be0.png">
- B: The line spacing (leading) in the Linux drop down seems a bit larger than the other. Could we make it the same as the other drop downs.
- C: Tighten up spacing between the lines here (reduce about 5px)

I can post to our Advocacy channel after for a group Q + A, but other than those minor things I think these pages are looking great

**Comment by ScottDowne** [comment]
It's alive! https://advocacy.mozilla.org/stay-secure/

**Comment by natalieworth** [comment]
👏 👏 👏 👏 👏  @ScottDowne

**Comment by natalieworth** [comment]
@ScottDowne A couple Q+A's for mobile:
<img width="508" alt="screen shot 2016-05-18 at 1 54 39 pm" src="https://cloud.githubusercontent.com/assets/14876567/15374669/353614a8-1d00-11e6-97d7-07a85643fe8e.png">
<img width="472" alt="screen shot 2016-05-18 at 1 54 43 pm" src="https://cloud.githubusercontent.com/assets/14876567/15374667/35353b14-1d00-11e6-9f01-434658e46bb3.png">
<img width="559" alt="screen shot 2016-05-18 at 1 54 47 pm" src="https://cloud.githubusercontent.com/assets/14876567/15374668/3535638c-1d00-11e6-8207-19705c6bacc7.png">
- A: Decrease the spacing between the line breaks.
- B: Is it possible to add a dark box behind this so it doesn't overlap the text as much? (Not a huge deal though if too hard to add)
- C: Decrease the spacing between the line breaks on page 2.
- D: Decrease the spacing between the line breaks.
- E: Can we make the text scale slightly smaller so it's still in the device margins?

**Comment by natalieworth** [comment]
@ScottDowne So button could have a background like this:
<img width="350" alt="screen shot 2016-05-18 at 2 00 03 pm" src="https://cloud.githubusercontent.com/assets/14876567/15374813/f23f193c-1d00-11e6-90d3-5ec751c6556b.png">

**Comment by ScottDowne** [comment]
@natalieworth question about that button. Like, the red circle is still visible inside the red box?

**Comment by natalieworth** [comment]
@ScottDowne Yeah, so the background would be the darker colour #e24949

**Comment by ScottDowne** [comment]
@natalieworth cool, so hovering would blend them, making the circle hidden, right?

**Comment by natalieworth** [comment]
@ScottDowne Yeah, but that would just be for mobile devices right?

**Comment by ScottDowne** [comment]
@natalieworth yeah, true, which wouldn't care about hover.

**Comment by ScottDowne** [comment]
This launched.
