### ISSUE TITLE
Update our Github Estimation levels 

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#180]
Can you change the current menu to our new estimation levels?

E.g. this:

![build_our_gantt_chart_for_advocacy_repo_ _issue__179_ _mozillafoundation_advocacy](https://cloud.githubusercontent.com/assets/9830371/17349316/81288e10-58d1-11e6-8065-95b1dd1dde34.png)

I've checked with @lovegushwa @HPaulJohnson @ScottDowne  and they think this is a good set of levels to try out. We can always change it later.

**Comment by valianttry** [comment]
I put a description of these in our wiki:
https://github.com/MozillaFoundation/Advocacy/wiki/Estimation-Callibration-(what-does-XS,-S,-M,-L,-and-XL-mean%3F)

**Comment by cadecairos** [comment]
I'd love to do this, but the Story Points must be numbers...

**Comment by valianttry** [comment]
ah. OK, let's do 1, 2, 3, 4, 5 then?

**Comment by valianttry** [comment]
Updated the wiki for our numeric estimations: https://github.com/MozillaFoundation/Advocacy/wiki/Estimation-Callibration-(what-does-1,-2,-3,-4,-and-5-mean%3F)

**Comment by valianttry** [comment]
@cadecairos ETA?

**Comment by cadecairos** [comment]
I've applied the requested story point values, and it appears they persist across issues. marking closed!

**Comment by valianttry** [comment]
whoohoo! thanks @cadecairos !! 🚀  💯
