### ISSUE TITLE
Add Fission team to Github

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#183]
Hey @cadecairos - can you please add the following Fission team  members to our Github repo? We'll want to be able to CC them on issues throughout the Nationbuilder events / petition projects. 

George Holmes: gholme4
Walter Lau: imagerwalt
Anna Hovland: annahov
Jennifer O'Reilly Mott: jendc123

Thx!

Due Aug 5

CC @valianttry

**Comment by cadecairos** [comment]
I don't think we need to add them just to mention them in issues. 

Will they need to manipulate the state of issues at all? I.E. Changing assignees, adding labels etc?

**Comment by valianttry** [comment]
Let's not add them for now and see how it goes just cc'ing them. They're tracking their own work in their own system.

**Comment by cadecairos** [comment]
Sounds good to me. Closing as a wont-fix-yet!
