### ISSUE TITLE
Finalize Maker Party Activites 

### ISSUE THREAD

**Issue by shaghdoosti** [MozillaFoundation/Advocacy#184]
We have a great first draft of Maker Party activities. We're meeting next week to go through these and get them finalized by the end of the week. 

Here is the drive: https://drive.google.com/open?id=0B0RBD2BW-srIdUV5d0NEVzNJY00

@HPaulJohnson @chadsansing

**Comment by chadsansing** [comment]
As shared in #130, here's a sample activity built out in our curriculum template - open for discussion, etc.

https://chadsansing.github.io/eu-maker-party-sample-activites/02-06-dont-break-the-net.html#overview

cc @shaghdoosti, @HPaulJohnson

**Comment by shaghdoosti** [comment]
@chrislarry33 @geroter

**Comment by damiankay** [comment]
Closing this as it seems to have been completed. Also logged here: #161
