### ISSUE TITLE
Maker Party: Finalizing the partnership pack

### ISSUE THREAD

**Issue by shaghdoosti** [MozillaFoundation/Advocacy#185]
We have a draft of the partnership pack - the copy is still being finalized. 

Here it is: 

https://docs.google.com/presentation/d/1Ibb0WgTwdXBON1UxYjQMu3DftK2PcwNiiCCKgkuibZs/edit

Next steps: 

@ldecoursy , lucy, @Melechuga and Sara jamming on this on Monday. 
Has been sent to Raegan for review 
Once locked will need some light design.

**Comment by shaghdoosti** [comment]
Hey @lovegushwa 

We have a close to final partnership pack here: 
https://docs.google.com/presentation/d/1Ibb0WgTwdXBON1UxYjQMu3DftK2PcwNiiCCKgkuibZs/edit#slide=id.p

Any chance this could have some design love before Friday COB? A few things - it would be awesome if it's a template we can use for other decks - and also, we're going to need to edit the document for various partners so it would be great to have it remain in a slide format as opposed to a pdf. Let me know if that works. Thanks.

@ldecoursy @lucyeoh

**Comment by lovegushwa** [comment]
Updated the Maker Party identity this week (added the Mozilla wordmark), I need a little time Monday morning to get this into the partnership deck.

<img width="774" alt="screen shot 2016-08-17 at 3 27 49 pm" src="https://cloud.githubusercontent.com/assets/12228435/17818694/86b07b38-65f9-11e6-96c0-51fc89035dd1.png">
<img width="514" alt="screen shot 2016-08-17 at 3 26 20 pm" src="https://cloud.githubusercontent.com/assets/12228435/17818698/8a6fc332-65f9-11e6-910f-2ccc6a27f329.png">

**Comment by LucyeoH-zz** [comment]
Hey @lovegushwa 

Flagging that there's a slightly altered version for communities [here](https://docs.google.com/presentation/d/11HAMhPOHv4VKJ04nDvsdv2Dko7sFSwMwwsRARG6jpzc/edit#slide=id.g116deb4a8b_2_19) that could also use some design love!

Lucy

**Comment by lovegushwa** [comment]
@LucyeoH ok thank you!

**Comment by lovegushwa** [comment]
@shaghdoosti making some progress here, I will need some time in the morning to wrap this up.

**Comment by lovegushwa** [comment]
@shaghdoosti the Maker Party deck is ready! 
https://docs.google.com/a/mozilla.com/presentation/d/1Ibb0WgTwdXBON1UxYjQMu3DftK2PcwNiiCCKgkuibZs/edit?usp=sharing

**Comment by lovegushwa** [comment]
@LucyeoH your deck it ready!
I realize there are small changes to wording for a slightly different audience, I tried to catch it all but double check before deleting the old slides!

https://docs.google.com/presentation/d/11HAMhPOHv4VKJ04nDvsdv2Dko7sFSwMwwsRARG6jpzc/edit#slide=id.g1177f349bb_4_92
