### ISSUE TITLE
Online recruitment plan locked

### ISSUE THREAD

**Issue by shaghdoosti** [MozillaFoundation/Advocacy#186]
We want to create a calendar and plan for recruitment online. This includes: 

-Moco channels 
-Social/Media 
-Mofo emails 

@HPaulJohnson is working with Maura on the first two and Myself and @valianttry are working on the mofo email calendar.

**Comment by damiankay** [comment]
Hi @shaghdoosti @HPaulJohnson @valianttry - can we update or close?
