### ISSUE TITLE
Maker Party: Network recruitment plan 

### ISSUE THREAD

**Issue by shaghdoosti** [MozillaFoundation/Advocacy#187]
We have an intial list of organizations we want to reach out to. Next week Lucy, Lainie, Sara, Mel and Raegan will jam on how many groups we think we should aim to be involved in Maker Party.

**Comment by shaghdoosti** [comment]
@melechuga

**Comment by damiankay** [comment]
This is related to issue #242 

Is this work done already? @shaghdoosti @Melechuga

**Comment by Melechuga** [comment]
Hey @damiankay, 
Yea, we have a list of partners we're reaching out [to here](https://docs.google.com/spreadsheets/d/1D5n0VXQwrMpB2aqCqGtkw1U7eUq_lwhrG_ZFSlz2524/edit#gid=0).

**Comment by damiankay** [comment]
Fantastic - closing this down then. Thx!
