### ISSUE TITLE
EU Copyright Campaign: promotional assets for phase 1 marketing/comms

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#188]
For 8/24 petition launch what are the marketing/comms assets that require design and copy in this sprint. 

@lovegushwa and I to meet today (8/8) to develop final list of deliverables and plan.

**Comment by HPaulJohnson** [comment]
cc @KevZawacki

**Comment by HPaulJohnson** [comment]
Confirmed snippet availability for 8/23 petition launch. 

We should start working on copy for this (@KevZawacki) while we wait for feedback on deadlines and localization. We'll also need some icons to accompany the text (@lovegushwa / @natalieworth)

**Comment by KevZawacki** [comment]
@HPaulJohnson Will do.

**Comment by HPaulJohnson** [comment]
Closing this in favor of channel specific tickets here: 

Email: #197 
Snippet: #198 
Social: #199
