### ISSUE TITLE
Maker Party: Finalize reporting expectations for partners 

### ISSUE THREAD

**Issue by shaghdoosti** [MozillaFoundation/Advocacy#189]
We need to figure out what we want partners to report out after doing events. 

@Melechuga

**Comment by damiankay** [comment]
@shaghdoosti will connect @vojtechmozilla with 270 strategies.

**Comment by shaghdoosti** [comment]
We have a meeting about this on Friday.

**Comment by valianttry** [comment]
@shaghdoosti can you please update this milestone? Maybe this is done and if so please close 👍
