### ISSUE TITLE
DRAFT copy for software email for encryption campaign

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Advocacy#19]
Email production and content for software email for encryption campaign:
Design is here: #16 
Build is here: #18 

cc @valianttry @shaghdoosti @mmika

**Comment by valianttry** [comment]
Updated draft is here:
https://docs.google.com/document/d/1j5E86fgAE3C3eM65s0S1ihGd3v79wnkeTxhzNRFSv9U/edit?ts=572ba5a5

**Comment by natalieworth** [comment]
@valianttry Thanks, I'm also wondering which template you were wanting to use for the software update email?

**Comment by mmika** [comment]
software update email draft: 
https://docs.google.com/document/d/1sWBgZZTj-9FrEzP3oX-pTCa48IqxkVNgQ776QqQ5Wc4/edit

@lovegushwa @natalieworth @stephaniemcv

**Comment by valianttry** [comment]
@KevZawacki and @brettgaylor can you review this draft as soon as you can?
https://docs.google.com/document/d/1j5E86fgAE3C3eM65s0S1ihGd3v79wnkeTxhzNRFSv9U/edit?ts=572ba5a5

**Comment by KevZawacki** [comment]
@valianttry Looking good! Made only a few minor changes, like ensuring dashes are consistent.

**Comment by natalieworth** [comment]
@stephaniemcv I'll post the 600 x 300 image tomorrow morning! Just working on it this afternoon and have a few adjustments.

**Comment by stephaniemcv** [comment]
@natalieworth Sounds good!

**Comment by natalieworth** [comment]
@stephaniemcv I have the email image here:
One is 600x300 at 72 dpi, and the other is 600x300 @2x for retina. Let me know if you need anything additional for the email. Thanks :)
72dpi: https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0ZVpZR1draUUtN2c/view
144dpd (@2x): https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0RjdZNHlJczRadkE/view

**Comment by ScottDowne** [comment]
This is quite old and looks like it might have been done.

Closing, feel free to reopen or refile.
