### ISSUE TITLE
Draft of Maker Party KPIS 

### ISSUE THREAD

**Issue by shaghdoosti** [MozillaFoundation/Advocacy#190]
Key next steps from our meeting today:

Finalize activities - build in action that can be tracked ([see issue 184](https://github.com/MozillaFoundation/Advocacy/issues/184)) 
Finalize reporting expectations for partners ([see 189](https://github.com/MozillaFoundation/Advocacy/issues/189)) 
Finalize MP KPIs by next Wed 8/17

Key document: https://docs.google.com/presentation/d/1dD92Qa7SkFkP_mvw3G6MCui843qcvUcvEH5kq4qdpvA/edit#slide=id.p

@geroter @chrislarry33

**Comment by damiankay** [comment]
Hi @shaghdoosti - can we update or close?

**Comment by shaghdoosti** [comment]
These are done.
