### ISSUE TITLE
KPIs for the copyright campaign

### ISSUE THREAD

**Issue by shaghdoosti** [MozillaFoundation/Advocacy#191]
What are our KPIs for the Copyright campaign. @sarahaghdoosti @valianttry @brettgaylor to have initial conversation and then work with various stake holders to get a good draft done by next week.

**Comment by damiankay** [comment]
@shaghdoosti - can you link documents / update when you have a second?

**Comment by damiankay** [comment]
Hi @shaghdoosti - can we update or close?
