### ISSUE TITLE
EU Copyright Campaign: Paid Media plan and assets

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#193]
Design and copy to support the Paid Media portion of our phase 2 Copyright Campaign promotion beginning on 9/8. This channel will primarily support updated version of petition site and leverage media assets (video) and UGC experience (memeland).

cc @lovegushwa @KevZawacki

**Comment by HPaulJohnson** [comment]
Schedule: 
- This week: finalize test plan. 
- Next week: Define specific list of design and copy deliverables needed to support test plan. 
- Week(s) of 8/22-9/2: Design assets and setup targeting/tests in platforms.

**Comment by HPaulJohnson** [comment]
Working with a consultant and tentative plan and scope of work approved. Next week paperwork and campaign briefing to start building test plan and campaign. 

@vojtechmozilla I will setup a meeting for us early next week to discuss.

**Comment by vojtechsedlak** [comment]
+1 @HPaulJohnson

**Comment by HPaulJohnson** [comment]
Contract for Alex Geidt drafted and submitted for signature. Setting up a kickoff meeting for this week to begin this work.

**Comment by HPaulJohnson** [comment]
Contract signed and kick off held yesterday. Final test plan to be ready next week.

**Comment by HPaulJohnson** [comment]
Adwords portion of this to begin by Friday, 9/9.

Facebook and other ads to begin in conjunction with media asset/v2 website launch on 9/20 (adjusting milestone as a result).

**Comment by HPaulJohnson** [comment]
This is running and will be optimized this week. I'm going to close and create a new ticket for reporting.
