### ISSUE TITLE
Scope of work: Localization for Copyright education campaign content

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#194]
I'm building a scope of work to detail our localization needs. Please report content you believe we will need to localize for this campaign. I will be coordinating with L10N as well as a vendor (Kontextor) to translate and localize campaign content. 

**Petition and Education Campaign languages:**
    Tier 1: English, French, German, Spanish, Polish
    Tier 2: Italian, Dutch, Czech Bulgarian

**Web page copy / rough word count estimation (in EN - original):**
- Petition text (250 words)
- Petition form fields (20)
- Headers, footers, titles, subtitles (250)
- Share copy post-signature (20)
- Donation copy post-signature (100)

**Email:**
- Petition promotion to Foundation List -- "Sign on!" emails (300x 5 emails = 1500)
- Auto-reply for petition signers -- "Thanks for signing!" (200x 2 test emails = 400)

Social @HPaulJohnson 
- 

Video @brettgaylor 
-

**Comment by HPaulJohnson** [comment]
Also, Snippet (@hpauljohnson)

**Comment by brettgaylor** [comment]
Estimates:
Explainer video: 200 words
Subsequent contet: approx 100 words, x 6
Total: 800 words

I'm not sure Polish should be considered a P1 for video localization, however.

**Comment by valianttry** [comment]
@HPaulJohnson when you have a moment can you drop in estimates like @brettgaylor and I did? They can be guesses, but it'll help me estimate costs roughly for the Kontextor contract.
