### ISSUE TITLE
Rapid response creative strategy

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#195]
Create a deck/plan that outlines a strategy for rapid response. Deck will be a work in progress, thing's to include: 
- [ ] benchmarks
- [ ] what a rapid response brief looks like
- [ ] kinds of media, types of channels
- [ ] copy writing
- [ ] templates
- [ ] collaboration (how stuff gets built)
- [ ] rapid response approval
- [ ] pressure test

**Comment by lovegushwa** [comment]
Will sprint on this Thursday / Friday, we need to do a little prep work beforehand, will post here.

**Comment by lovegushwa** [comment]
Had a sprint on this last Friday: https://docs.google.com/a/mozilla.com/presentation/d/1rmPqMlMOuteMe_15E82-qYKrI_HMOXpceaaVFzYZKnc/edit?usp=sharing

https://public.etherpad-mozilla.org/p/Rapid-response-creative-strategy

@damiankay took notes on next steps. Damian should we list steps, close this ticket and make any tickets we need for next steps?

**Comment by damiankay** [comment]
@lovegushwa - yes, I'll add the tasks to GH today. Thx
