### ISSUE TITLE
Campaign Identity

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#196]
Design the copyright campaign identity. Will show up on petition pages + possibly video bumpers, email and social. Start with #copyfail + straightforward tagline. 

Audience: EU content creators / Conscious choosers  
Constraint: Tagline will be localized, so language needs to be descriptive and direct.

Variant 1:
Lead with tagline, support with #copyfail 

Variant 2: 
Lead with #copyfail, support with tagline

**Comment by lovegushwa** [comment]
@HPaulJohnson @KevZawacki let's connect and choose final tagline copy.

**Comment by KevZawacki** [comment]
I like Variant 1 (Lead with tagline, support with #copyfail .)

Initial brainstorm doc [here](https://docs.google.com/document/d/15tf0zJjPvIbpcDDVk3mWhXFP-W0qhp86Wv1OLMhKEX8/edit), + newer suggestions in the [website copy doc](https://docs.google.com/document/d/1C49mUWIe5tPHdaLfr5-NkjeizWEh5NRXeP8C-57HgzA/edit).

**Comment by lovegushwa** [comment]
just to get this moving: Let’s bring EU copyright law into the 21st Century #copyfail

**Comment by lovegushwa** [comment]
Here are a few copy directions / they don't express final visual design direction. 

<img width="688" alt="screen shot 2016-08-10 at 9 45 28 am" src="https://cloud.githubusercontent.com/assets/12228435/17562346/54d8f520-5edf-11e6-84aa-5f6899e3cb43.png">
- Positive tone of voice overall. 
- Strong economic argument tie in. 
- Needs localization. 
- Needs a hastag (#copyfail does not work well with this copy.)

<img width="643" alt="screen shot 2016-08-10 at 9 50 39 am" src="https://cloud.githubusercontent.com/assets/12228435/17562488/fa02bc84-5edf-11e6-8af0-d06cc763aaa2.png">
- Negative tone of voice
- Expresses outrage / absurdity of bad/outdated laws
- Headline will not need localization 
- Is a hastag (already in use.)

**Comment by KevZawacki** [comment]
@lovegushwa @HPaulJohnson 

I like the first option ("Make, Create..."). The positive tone seems in-line with Mozilla's brand. Alternatively, the negative tone of the second option seems off-brand, and more like something FFTF or EFF would write. Further, Lucile of MoCo comms -- a European and copyright expert both -- advised we take a positive tone.

**Comment by lovegushwa** [comment]
Thanks @KevZawacki any ideas about what hashtag we might use with "Make, Create, Innovate" ?

**Comment by HPaulJohnson** [comment]
First, adding a few pros/cons to Jordan's list above:

"Make. Create. Innovate."
pros: 
- positive
- "it's not ok to regulate imagination." has broad appeal
  cons:
- a bit generic
- don't speak to absurdity of current laws, which is the idea much of our content is built around. 
- doesn’t spark any outrage or have much urgency

#copyfail
pros: 
- has urgency and feels more action-oriented
- can be applied to any point made in petition
- works as a hashtag for campaign

cons: 
- already in use
- negative in tone
- doesn't really speak to creativity/imagination angle 

Ultimately I'd be ok with the more positive "make/create/innovate" positioning - it has a lot of strengths - but want to gut-check that it works if the content we are using to drive traffic is all about highlighting the absurdities of current regulations. For example, if I engage with a piece of content on social about the absurdities of current copyright and click through to this version of the site, am I compelled to take action? Maybe it's a matter of just amplifying the "regulating imagination" part of the message to add some urgency.

**Comment by lovegushwa** [comment]
@HPaulJohnson @KevZawacki @natalieworth 
I think we should lead with #copyfail based on Paul's points around it being a bit harder call to action. 
If we can swing it, would be great to test both when we launch.

@vojtechmozilla what's your thoughts about running this as a test?

**Comment by HPaulJohnson** [comment]
I know timelines are a thing but I love the idea of testing if we can swing it. Can we use Optimizely with Nation Builder to make things a bit easier here?

**Comment by vojtechsedlak** [comment]
We can use Optimizely in the NB platform and it would, I think, be fairly straightforward to set up a test that swaps the top image. Would there be any other implications for the page design for each test? Any copy changes?

**Comment by HPaulJohnson** [comment]
@vojtechmozilla @lovegushwa I think we could run this test by just swapping the main/top image. I think either works with the rest of the copy which is centered around the petition copy itself.

**Comment by lovegushwa** [comment]
Will update the identity after v1 AB test runs, and will probably wait for v2 to push it out.
For now campaign assets should follow the color and type styles here: https://redpen.io/p/hre3576c177f54748c

**Comment by damiankay** [comment]
Just confirming this is for after V1 launches
