### ISSUE TITLE
EU Copyright: Design email for 8/24 petition launch

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#197]

**Comment by lovegushwa** [comment]
@HPaulJohnson @shaghdoosti @stephaniemcv 
What email template are we using (so we know what size image to make.)
Any updates on the content here :) ?

**Comment by stephaniemcv** [comment]
Couple of Qs:
- Is the image compelling enough to warrant a 600px width? (template full size images tend to scale better for mobile. Call outs are tricky because they are not truly 2 columns and it can shift text weirdly).
- Is the copy long? My concern would be the image pushing too much copy below the fold if we don't have a CTA in the image.
- What about a nice, eye catching button? (I would just need hex number, buttons are made of code not images)

**Comment by lovegushwa** [comment]
@valianttry @stephaniemcv I think this is the template we need (but with updated colors) ... 600x300px image

We can do with a smaller centered image (could be an emoji, we are using them in the v1 petition)
https://redpen.io/yd7e08c52343b4c0d3 

What do you think?

![screen shot 2016-08-16 at 10 01 41 am](https://cloud.githubusercontent.com/assets/12228435/17708630/ae4e962c-639a-11e6-9dec-b67495316e0a.png)

**Comment by stephaniemcv** [comment]
@lovegushwa Just to clarify, when you say "smaller centered image" do you mean the emoji **and** text? 

Overall, I like this design. In terms of email coding this is a simple alternate image blocks with copy blocks. The image alt text can be css styled to look like bold font so the header "text" is not lost if images are turned on in a recipient's email box.

![issue197](https://cloud.githubusercontent.com/assets/11812272/17724565/66213fec-6400-11e6-837e-835bd63de6be.jpg)

**Comment by lovegushwa** [comment]
@stephaniemcv @valianttry do we have a draft of the email copy?

**Comment by valianttry** [comment]
Cristina Moon is due to send first draft email copy today.

**Comment by valianttry** [comment]
@cristina-moon is in the house!

**Comment by cristina-moon** [comment]
I have a _first_ draft but as it's my first email ever for Mozilla, I assume it needs to go through the ringer. I'm not sure by whom, though? https://docs.google.com/document/d/1wJ3spmPItKW5HjthHhWuPEO3hqAd5G9eNy45LhsL80s/edit

**Comment by natalieworth** [comment]
Image for email is here (exported at 600x300 with 144dpi):
https://drive.google.com/drive/folders/0B20-0lpP23c0NmVock13NlNGZWM
![copyright_email 2x](https://cloud.githubusercontent.com/assets/14876567/17902084/ae1bb25e-691a-11e6-9b2e-b7c08c7429fc.jpg)
cc @lovegushwa if you want to review before going in the email

**Comment by natalieworth** [comment]
We'll have to add the copyright information/ attribution within the email if that works? @cristina-moon . I'm just sourcing that right now and will post asap.
cc @valianttry

**Comment by lovegushwa** [comment]
@natalieworth yes this is great! ship it!

**Comment by valianttry** [comment]
hey @natalieworth ! Any way to turn this into a callout box like we used during EOY? There's already Callout copy in the email text document. I am super worried this design at the top will bump down the link to the petition and hurt conversion. 💓

**Comment by natalieworth** [comment]
Updated the email image to a more discreet call-out:
<img width="398" alt="screen shot 2016-08-23 at 12 54 33 pm" src="https://cloud.githubusercontent.com/assets/14876567/17907912/de118660-6932-11e6-953b-73c665b34a06.png">
Exported files are here (one is 144/ @ 2x and the option is just 72dpi):
https://drive.google.com/drive/folders/0B20-0lpP23c0NmVock13NlNGZWM
Ping/ @ me if there are any additional changes—know timing is tight with the email schedule :)
cc @valianttry

**Comment by natalieworth** [comment]
Closing for now—but reopen or create a new ticket when localized files come in. Final EN versions are in link above ^
