### ISSUE TITLE
EU Copyright Campaign: Design snippet for 8/24 petition launch

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#198]
Design and copy for snippet promotion of Copyright petition on 8/24. Plan is to have 3 versions for testing.

**Comment by HPaulJohnson** [comment]
Discussed with @lovegushwa. We'll likely keep the visuals/icon pretty basic, leveraging the (C) symbol. We can work on some copy ideas for up to 3 versions here: 

https://docs.google.com/a/mozilla.com/document/d/1Ubbn_GTyMibSxRoQ4Kxul26fgdBOE1P6Q2JkCCYAI_I/edit?usp=sharing

cc @KevZawacki

**Comment by HPaulJohnson** [comment]
Aim to have initial concepts/copy to snippet team for feedback/review by 8/17.

**Comment by lovegushwa** [comment]
@HPaulJohnson on this today. Will post UI this afternoon.

**Comment by HPaulJohnson** [comment]
Sent to snippet team for creative review: 

 https://redpen.io/p/dn5a9dd25dd4e29f19

Feedback to be posted here this afternoon before moving these through approval/localization processes.

**Comment by HPaulJohnson** [comment]
Feedback from snippet team: everything is awesome! They are going to do a quick pass at the copy tonight to tighten/shorten where possible. We gave them 5 ideas and they have requested we pick 3 for testing. 

Here are my picks: 1 (simple/straightforward), 2 (button test) and 4 or 5 (creativity/imagination/pop). 

To test the button (2 or 3 versions in redpen above), we will need to build a new template. @ScottDowne is that something you can do by end of day 8/22?

**Comment by lovegushwa** [comment]
@HPaulJohnson I'm good with that, can we close this ticket?

**Comment by HPaulJohnson** [comment]
Yep, design complete. Closing.

(approval and localization being tracked in #245)
