### ISSUE TITLE
EU Copyright Campaign: Design social promos for 8/24 petition launch

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#199]
Design and copy assets need for initial social posts on Mozilla Facebook and Twitter profiles. Should cover a bi-weekly cadence between 8/24 petition launch and phase 2 launch on 9/8.

**Comment by HPaulJohnson** [comment]
Discussed with @lovegushwa. We will come up with 3-5 posts for initial wave of petition promotion. Here some initial ideas: 
- copy only: pretty straight-forward, sign the petition stuff. 
- copy + static image: using wikimedia screenshot with copyrighted images censored/blacked-out.
- copy + gif: use some giphy content to build a post around
- copy + image/gif: if it still feels relevant on the heels of the closing ceremony, something olympic-themed to show some of the absurdities of current copyright restrictions around anything using official olympic logos/etc.

**Comment by HPaulJohnson** [comment]
We can start working on copy in this doc: 

https://docs.google.com/a/mozilla.com/document/d/1-CGBBcJL40LwGwT_5AhquXiK84W6Sz7biHsM-KGRm-I/edit?usp=sharing

cc @KevZawacki

**Comment by natalieworth** [comment]
@beccaklam test :)

**Comment by natalieworth** [comment]
@brettgaylor @HPaulJohnson @lovegushwa @KevZawacki Started illustrative styles here of collage images gathered from Creative Commons: https://redpen.io/p/gq3de9ff962d05c391
I'm currently looking at gifs that could accompany the other social content written in the doc above. :D

**Comment by KevZawacki** [comment]
@natalieworth These are awesome! 🎆

**Comment by brettgaylor** [comment]
These are very great!

@natalieworth don't forget to provide CC attribution when you use these ;)

**Comment by natalieworth** [comment]
@brettgaylor Ah yes! I was going to ask you about that. Should I still provide CC if it's under a public domain/ CC 0 license (which doesn't require accreditation to the author). Or would we be able to provide credits within the facebook/ twitter post instead of on the image itself.

**Comment by natalieworth** [comment]
Brainstormed additional copy ideas/ visual variants here during our sprint last week:
https://docs.google.com/document/d/1asqVyUSKBhclMJ1y0WSQyltJb-bB16tv11eYEHwWN10/edit
Will update this afternoon.

**Comment by HPaulJohnson** [comment]
@natalieworth we narrowed down the brainstormed list to these final 9 for this initial phase. A few on this list could still use some images/design. Otherwise, I'm sending the copy for approval shortly. 

https://docs.google.com/document/d/1iRQEB1we2gDUX7vWi7eyYk9q7L930gz9tOOtCP6LiD0/edit

The other ideas from the brainstorm should continue to be worked on but we won't need those until early September.

**Comment by HPaulJohnson** [comment]
Feedback received from policy. Pushed initial set of social/copy to localization. We still have a few graphics to add but we have enough to get us started at launch (pending localization) and have a bit more time for additional graphics.

**Comment by natalieworth** [comment]
@HPaulJohnson Linked the final image exports in this file: https://docs.google.com/document/d/1iRQEB1we2gDUX7vWi7eyYk9q7L930gz9tOOtCP6LiD0/edit
Just working on adding/ updating Raegan's Nokia phone comment for the 1st one with the altered copy—and then still have to add images for 8-10 copy ideas if needed.

**Comment by HPaulJohnson** [comment]
Thanks, @natalieworth. Left a note in the doc too but if possible can we remove the brand on the phones so it's more generic "old phone."

**Comment by natalieworth** [comment]
@HPaulJohnson Final facebook/twitter files for these are here: https://docs.google.com/document/d/1iRQEB1we2gDUX7vWi7eyYk9q7L930gz9tOOtCP6LiD0/edit 
Closing, but reopen if any changes are needed. Can also reopen in future if more images are needed for initial push..

**Comment by natalieworth** [comment]
Image for the social link on the nationbuilder site is here:
https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0ZXh1TTZvSjMtSlE/view
To replace this:
<img width="613" alt="screen shot 2016-08-24 at 10 51 42 am" src="https://cloud.githubusercontent.com/assets/14876567/17941636/0b8916d8-69e9-11e6-8320-81377a5b6034.png">
