### ISSUE TITLE
DRAFT copy for filevault/bitlocker email for encryption campaign

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Advocacy#20]
Email production and content for software email for encryption campaign:
Design is here: #13 
Build is here: #14 

cc @valianttry @shaghdoosti @mmika

**Comment by natalieworth** [comment]
@stephaniemcv I was going to start on this earlier if that works for you. Do you have an idea yet of the template we're going to be using?

**Comment by natalieworth** [comment]
@valianttry @shaghdoosti Do we have copy yet too for the landing page? If this is a bit shorter (with only filevault/ bitlocker) it could be interesting to explore instructional illustrations paired with the content if I get time?
Is it possible to get content by this Thursday or Friday? Was hoping to ship the final design a bit earlier so Scott has more time for the build if we're shipping next Wednesday (May 25th)

**Comment by mmika** [comment]
https://docs.google.com/document/d/16A0riwe6stAOPWCM5dYFqZt118Cn6WnDaAhhsnLhneU/edit?ts=56f978e4 
@natalieworth

**Comment by natalieworth** [comment]
@stephaniemcv What's the template or design assets we'll need for the 2nd upcoming email?

**Comment by stephaniemcv** [comment]
Template will be the same as the last email. No design assets at this time.

**Comment by shaghdoosti** [comment]
Friends -- landing page copy and email is approved. 

Also -- here is a set of links thanks to @mimka for the landing page (for support resources) 

FilveVault
Entire hard drive: https://support.apple.com/en-us/HT204837

Selected drives: https://support.apple.com/en-us/HT201599

BitLocker
http://windows.microsoft.com/en-us/windows/protect-files-bitlocker-drive-encryption#1TC=windows-8

**Comment by damiankay** [comment]
Can we close this issue?

**Comment by stephaniemcv** [comment]
Yup.

**Comment by damiankay** [comment]
Thanks!
