### ISSUE TITLE
EU Copyright Campaign: Design social promos for phase 2 launch

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#200]
Design and copy assets need for 2nd wave of social posts on Mozilla Facebook and Twitter profiles, plus other platforms tbd (Youtube, Instagram, Snapchat, etc). Assets should cover a bi-weekly cadence between 9/8 media launch (videos + memeland), feature a variety of content/types and run through the end of September. 

cc/ @lovegushwa @KevZawacki

**Comment by HPaulJohnson** [comment]
We can get started on these after we complete work on phase 1 deliverables, in ticket #199

**Comment by HPaulJohnson** [comment]
Kicked this off today. Initial ideas here: 
https://docs.google.com/document/d/1Ozel0ogJS9ow-nok9B2T_5-x3rv_vpnvmRMN4hLDy3M/edit

We'll reconvene next week to start developing ~5 of these concepts for phase 2 social to support both organic and paid promotion.

**Comment by KevZawacki** [comment]
Dropped some comments / research into the doc

**Comment by HPaulJohnson** [comment]
Phase 2 now scheduled for 9/20 so we will build back from that schedule.

**Comment by HPaulJohnson** [comment]
Update: Final Testing plan reviewed with @vojtechmzl and @lovegushwa @beccaklam @natalieworth  today. Details are here: 

https://docs.google.com/document/d/11FnCZ1gkWNRuLCIxMMk-AsABbgSTxWUnEC0uO8Dr7Dk/edit

NOTE: anything in red still has outstanding deliverables. 

We are have everything we need for YouTube tests and Facebook tests A-G so we are going to ship those off for localization today and start the Ad setup on Monday. 

We'll aim to ship a second batch of content - for the additional new creatives/deliverables still outstanding - along with Maker Party promos at the end of next week or the beginning of the week of 9/26.

**Comment by damiankay** [comment]
These have been sent out for localization @HPaulJohnson

**Comment by HPaulJohnson** [comment]
Final testing plan for this phase is here: https://docs.google.com/spreadsheets/d/1Exj4Zi70DhFDBt6f9qEtCWgyFTFH50EsG-4M1gWb99g/edit#gid=0

Working to setup audience segments now. If localizations come back by Thursday, aiming to have the first of these tests launched by Friday.

**Comment by damiankay** [comment]
Hi @HPaulJohnson - localizations are complete and in the spreadsheet. I'll send you the link in chat.

**Comment by HPaulJohnson** [comment]
thanks, @damiankay. we will start setting up the paid media ads with these versions now. Hopefully we'll launch the first of these Friday. 

There are a few, small outstanding designs to accompany the final posts for phase 2 and we are aiming to have those by the end of the week. We'll finally close this ticket then. (But, we'll also be opening a new one for Maker Party promos).

**Comment by valianttry** [comment]
@HPaulJohnson cool to close this ticket yet?

**Comment by HPaulJohnson** [comment]
yes
