### ISSUE TITLE
EU Copyright Campaign: Design snippet phase 2 launch

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#201]
Design and copy assets need for 2nd wave of promotion on snippet. Content to feature could include media (videos), experiences (memeland), petition (optimized from phase 1) or Maker Party. 

cc/ @lovegushwa @KevZawacki

**Comment by HPaulJohnson** [comment]
Work on this phase doesn't need to start until phase 1 tickets are complete (#199, #198).

**Comment by HPaulJohnson** [comment]
Phase 2 now scheduled for 9/20, so we'll work back from that timeline.

**Comment by lovegushwa** [comment]
@working on this today. Will post some designs this afternoon.

**Comment by lovegushwa** [comment]
v2 snippet designs: https://redpen.io/p/rz561278e5fb3ca36f
updating a few details as per @HPaulJohnson feedback.

**Comment by lovegushwa** [comment]
updated designs here: https://redpen.io/p/vj5adf39fbc68618a4

**Comment by HPaulJohnson** [comment]
Submitted to snippet team for feedback. I'll let you know what they think! Thanks, all.

**Comment by HPaulJohnson** [comment]
snippet team has approved. waiting for policy approval in the a.m. and then shipping to localization. 

final designs here: https://redpen.io/p/cu6dd2535dbbb1f1d8

**Comment by HPaulJohnson** [comment]
Submitted for localization. Go-live timing will depend on how quickly we get these back. Probably Friday at the earliest, more likely Monday (9/26)

**Comment by HPaulJohnson** [comment]
v2 snippets all localized in tier 1 locales and submitted to snippet team. we'll track a launch date in #346. calling this one complete!
