### ISSUE TITLE
Nationbuilder template components

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#202]
Wireframe template modules based on template research in #113 and additional advocacy website bench marking going on here: https://www.pinterest.com/lovegushwa/design-for-progress/

**Comment by lovegushwa** [comment]
Starter list of modals we will need:
- Hero banner
- Hero slider 
- Hero video
- Content (h1) 
- Content (p)
- Content (side bar)
- Video (multiple)
- Donate 
- Sign a petition 
- Join our email list
- Share 
- Promo

**Comment by beccaklam** [comment]
**Visuals/Content**
Hero banner
Hero slider 
Carousels
- Quotes
- Images

Hero video
Hero Image
Pull quotes
Video embedding
Tags?
Article divs? Covers? (Like ‘make it work page’) Blog Posts?
Partnership Logo Display? (images within a table within a div?)
Photo Gallery
Column Layout? (One column, two, three?)
Footer with copyright and company information

**Styling**
Headers
Subhead
Paragraph
Buttons
Hover states
Selected states
Pull quotes

**Widgets**
Counter (Petition progress, fundraising progress, etc)
Twitter Feed? (Social Media Reaction)
Filter? (For people to sort reactions, causes, tags?)
Read Thermometer (how much of the webpage/article have I read/scrolled through)
Loading widget?

**Navigation**
Standard Nav Bar?
Search?
Drop Down Nav?
Back To Top Button
Paging?

**Buttons**
Share (Facebook, twitter, e-mail)
Get Involved
Button overlays on top of hero content (button on top of img, button on top of video, etc)

**Forms**
Donate 
Sign a petition 
Join our email list

**Comment by beccaklam** [comment]
Image references: https://drive.google.com/a/mozilla.com/folderview?id=0BzuBOR2VJQqUZjY3bUZLYjFUTFk&usp=sharing

Notes are in the img names... Ask me if you have questions about what I was making note of!

**Comment by damiankay** [comment]
Damian to follow up: Do we need to build these into V1? Are they V2 features?

**Comment by lovegushwa** [comment]
@damiankay this is a wish list of features. Or you can think of it as a lego set to build future campaigns. So we don't need all these things for v2 (v2 will include some of them.) ... We should talk through this and get clear on how much Fission can do (what our budget is) and when we need it delivered (after v2 would be fine.)

**Comment by damiankay** [comment]
Sounds good @lovegushwa. I flagged this for Fission, and they'll be ready to review this with us after the Petition site V1 launch (right now they're all hands on deck to meet our deadlines). 

I'll set up a meeting to discuss in the meantime. Thx!

**Comment by beccaklam** [comment]
Some research notes. I looked at past campaigns and other organizations broke down what they had on their campaign pages:

Nationbuilder Components

**Encryption Campaign**
(https://advocacy.mozilla.org/en-US/encrypt/codemoji/1)
Home Page/Landing Page:
- header
- video
- video gallery, video thumbnails
- form (fields: country, name, e-mail, privacy disclaimer, sign up button)
- footer with applicable links and blurb about mozilla
- article div (h1, p, img, links)

**America Votes With Cards Against Humanity**
(https://americavoteswithcardsagainsthumanity.com/)
Home Page/Landing Page:
- header
- counter
- article div
- two column article
- ‘Add to Cart’ button
- video (full page)

**charity:water/personal campaign pages**
(https://my.charitywater.org/londoninamerica/londons-birthday-wish)
Campaign Page:
- header (customizable picture, user icon, Facebook and twitter share buttons)
- donation box (progress of campaign, button to donate, button to ‘see what happens next’)
- list of donors (sortable by amount/time given), multi-page div (navigated by pre, next buttons)
- letter about campaign
- video
- updates and comments feed
- footer with applicable links including contact info, social media links and CTA for e-mail sign up
- nav links back to charity:water main website, why water, our work, about us, donate button, fundraise button (we could do maker party button?), sign in

**Dadaab Stories** 
(http://www.dadaabstories.org/)
One page site
- landing page: video gallery navigated by tabs, videos play automatically
- buttons within the video gallery in the landing page link to stories further down the page
- photo galleries
- articles (each article accompanied by share buttons)

**ONE (runs multiple campaigns like us)**
https://www.one.org/canada/take-action/education-for-refugees/?source=homepage
- short letter about the campaign
- petition form on left (has progress bar at top, name, e-mail, postal code, country, phone number, disclaimer check boxes, and recent signer feed)
- join our mailing list bar and field input at the bottom
- one website nav at top
  https://www.one.org/canada/take-action/girls-everywhere/
- video background with text overlay
- letter sign form (name, email, postal code, country, sign button, signer feed)
- letter about the campaign
- read their stories article thumbnail
- twitter feed about the campaign
  https://www.one.org/canada/take-action/poverty-is-sexist/?source=subnav
- video header with text overlay
- links to pdf download
- ‘Spread the word’ section (shareable (Facebook or Twitter) designs/graphics
- link to articles, article thumbnails (like to their blog, we could like it to our medium?)
- twitter feed
- back to top button
  http://connecttheworld.one.org/
- unique page that is complete departure from their usual treatment
- back to top button

**change.org**
(https://www.change.org/)
- thermometer of campaign’s progress
- sign this petition form (first name, last name, e-mail, country drop down, street address, postal code, comments, Facebook share, sign button, display name disclaimer, privacy disclaimer)
- article with inline media
- tags
- update section (articles, supporter benchmarks)
- Supporters (comments)
- leading to other petitions
- footer

**kickstarter**
https://www.kickstarter.com/
- header: video, project stats, button to back project, project summary, share buttons, profile of creator
- tabs of page sections (campaign (breakdown of design, basically all information regarding project, FAQ at bottom), updates, comments, community)
- footer

**indiegogo**
https://www.indiegogo.com/#/picks_for_you
 (basically same as kickstarter and change.org

**gofundme**
https://ca.gofundme.com/
- left side dedicated to campaign details (picture, article), share buttons through out
  - comments
- donate box
- creator profile
- recent donation feed

**Styles that I like:**
https://www.vera.org/
http://hyperakt.com
http://www.gene.com/breakthrough/

**Comment by beccaklam** [comment]
Thoughts after research:
The strength of working with a cms like Nationbuilder is that our design wouldn't change too much but have customizable aspects. This could be limiting if we want to be super creative. The key will be to design a system we can use over and over again but allow for creative innovation.

**Comment by beccaklam** [comment]
Question: Do we want all of our campaigns to live on one website (that way it becomes a sort of resource?)

**Comment by beccaklam** [comment]
**Recommendations**

Campaign Page Essentials
- Customizable Header (We would need to design this. [Kickstarter](https://www.kickstarter.com/projects/xercyn/slow-dance-a-frame-that-slows-down-time?ref=home_potd) does a good job of having customizable aspects like a video and project stats. What would we need for our header?)
- Campaign Thermometer (I think these are good for tracking progress and empowering users to see their impact)
- Forms (What are the forms we can see ourselves needing? Petition Form, Donation Form, ??? What are the fields we would need on these forms? Ideally these forms wouldn't change that much so we can reuse them again and again)
- Standardized Footer (with applicable links)
- Standardized Campaign Explanation Format that can be media rich
- Campaign 'extras' (thumbnails that can link out to micro-sites we build for specific campaigns)

Campaign Page Extras:
- Social Media Feed
- Update Feed
- Comments Section
- Supporter/Donation Feed (shows most recent signatures or donations, time-stamped)

**Comment by damiankay** [comment]
@beccaklam - yes, I believe the goal is that most of our sites will live on Nationbuilder, thus benefiting from shared modules and functionality.

**Comment by beccaklam** [comment]
Added recommendations (slides with blue background) with benchmark images to the deck Natalie started in #113. Here's the link to the google doc: https://docs.google.com/presentation/d/1X31GHF9SclchaMY-K4Lo2XvUEAmmGrUjGHht-IHt0Q4/edit#slide=id.g15c71e0009_0_0
@valianttry @lovegushwa Can you let me know if you think we are missing any essential template components?

**Comment by damiankay** [comment]
@lovegushwa @beccaklam @natalieworth did you guys get what you wanted from the meeting with Fission? Do you have a clear sense of what's possible for v2? 

I sent them a link to the Redpen. Anything else I can do to help move things forward?

**Comment by beccaklam** [comment]
Hello @valianttry @brettgaylor @shaghdoosti @damiankay @lovegushwa! I made a deck that outlines components for a Nationbuilder Template. Would you be able to take a look and see if you think there are any important components missing? Also, if you see something you would like in the Copyright Campaign v2 Website please let me know as well. Here is the link to the google slides: https://docs.google.com/presentation/d/1X31GHF9SclchaMY-K4Lo2XvUEAmmGrUjGHht-IHt0Q4/edit#slide=id.g15c71e0009_0_0 (Read the ones on the blue background, starting at #22)

**Comment by brettgaylor** [comment]
This looks great, @beccaklam !  Particularly like the idea of having a place for us to update supporters.  +1 to the general idea of templating, with a method of allowing us to customize for microsites and additional creative content outside of the petition page.

**Comment by valianttry** [comment]
I'm going to close this, but the research done here was super useful and we'll be able to reference it for future!
