### ISSUE TITLE
 EU Copyright Campaign: v2 wireframes

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#203]
Design v2 wireframes. Use the v1 petition final UI as a starting point. Add one feature video, three "micro" videos and two meme generator promotions (click through to meme generator micro-site.)

Campaign treatment deck summary of content (pages 15 -17, 19-21):
https://docs.google.com/presentation/d/1lbbCBRoUcCns5BdRyCTNKznh4p7h0kLY73qfjeM4Crk/edit#slide=id.g15fbb3dc95_1_0

petition v1 redpens:
https://redpen.io/p/hre3576c177f54748c

Due date:
August 26th

CC:
@natalieworth @damiankay

**Comment by lovegushwa** [comment]
@beccaklam this should help you get started. We have some older low fidelity wireframes but they don't get across idea of integrating the petition text and additional v2 videos + meme generator promos. 

Articles on https://medium.com/ could be a benchmark. Also http://www.bloomberg.com/graphics/2015-paul-ford-what-is-code/

You can grab updated form fields from the final v1 UI here:
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvWUNyOFo5T2JXbDA/view?usp=sharing

<img width="959" alt="screen shot 2016-08-16 at 12 09 05 am" src="https://cloud.githubusercontent.com/assets/12228435/17690817/e9f6332e-6345-11e6-9b86-f234616a51b3.png">

**Comment by beccaklam** [comment]
https://drive.google.com/open?id=0BzuBOR2VJQqUZ1I5RjhjYWFMU0k
^ First iteration of V2 wireframes (1 mobile, 3 desktop versions)

**Comment by lovegushwa** [comment]
@damiankay we are getting closer on the v2 wireframes, can we set up a meeting with Fission to review options late Friday or early Monday? We can also do so asynchronously. We just need to confirm our wireframes options are going to be possible to build in Nation Builder so we can move ahead with UI next week.

**Comment by damiankay** [comment]
Yes - I'll set that up. Perhaps we can share on Friday and set up a call on Monday to discuss?

**Comment by lovegushwa** [comment]
@damiankay that's perfect. We should have @valianttry @HPaulJohnson @brettgaylor @shaghdoosti take a look. We can present internally on Friday if helps clarify our intent. CC @beccaklam

**Comment by beccaklam** [comment]
Just updating with a link to the redpen with all the wireframe iterations for documentation: https://redpen.io/p/og6892caada79f518d

**Comment by beccaklam** [comment]
Most updated redpen: https://redpen.io/p/on1ab9b0775c2e772b

**Comment by beccaklam** [comment]
@lovegushwa Hi Jordan, I've made some changes to the V2 wireframes. Added a new wireframe here with the step-by-step form, and change the landing page to have the sticky horizontal form. https://redpen.io/yj45e578bc1ba1b4dc I'll also tackle a tablet version this afternoon. Are there any other changes we need?

**Comment by damiankay** [comment]
@beccaklam @lovegushwa Can you guys please ping me when this is ready for Fission to review? They're hoping to see the revisions today. Thx!

**Comment by beccaklam** [comment]
https://redpen.io/fnf0c1163d66ff1fd1 @lovegushwa @damiankay Here are the updated copyright website v2 wireframes for Fission. I made notes through out the red pen. Let me know if it needs any changes.

**Comment by damiankay** [comment]
Thanks @beccaklam - are we still undecided about which direction we want for the form? I.e. step by step or side by side?

**Comment by beccaklam** [comment]
@damiankay @lovegushwa  We've decided to go with the step-by-step. The side-by-side wireframe is there if we have enough time/resources to build and do an A/B test.

**Comment by damiankay** [comment]
Thanks @beccaklam - that totally makes sense. 

@lovegushwa @brettgaylor any final comments before I send these off to Fission?

**Comment by damiankay** [comment]
Sent to Fission Aug 24
