### ISSUE TITLE
Coordinate testing and analytics for the Copyright Campaign

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#207]
Write-up an analytics & testing plan that summarizes the following components of the Copyright Campaign:
- KPIs
- data collection
  - channel identification
  - GA implementation
  - NB/SF integration
- analytics plan
  - dashboard plan
- testing plan
  - priorities

As part of the process, identify any questions or items that need clarification and liaise with the broader team.

Once completed, consult with the team.

**Comment by vojtechsedlak** [comment]
Here is a draft of the analytics plan: https://docs.google.com/document/d/1hunFxU8jrAc744iUWsS68E9_8ASXsQ6lxIZBhbPKDPc/edit

**Comment by lovegushwa** [comment]
@vojtechmozilla @HPaulJohnson @valianttry regarding the V1 petition AB test: 

I think we should test three headlines:
1. something super direct like "reform copyright" 
2. our more aggressive but not necessarily descriptive like "# copyfail"
3. friendly and hopeful "make, create, innovate"

<img width="1397" alt="screen shot 2016-08-15 at 3 51 29 pm" src="https://cloud.githubusercontent.com/assets/12228435/17682488/c1939e52-6300-11e6-87e2-3bf2f914b2ea.png">

In addition we could test several subheads:
1. "It's time our laws caught up with our technology"
2. something more descriptive like "Let’s bring EU copyright law into the 21st Century"

I'm very curious how open ended headlines like "#copyfail" and "make, create, innovate" are effected by more or less open ended subheads.

Feel free to propose alternate version of the copy. **I know "copyright" is not exactly compelling, but I'm also worried not knowing what the petition is about at a glance could effect conversion negatively, particularly on mobile. The makings of a good test I think.**  

The copy deck is here: https://docs.google.com/document/d/1C49mUWIe5tPHdaLfr5-NkjeizWEh5NRXeP8C-57HgzA/edit

*not clear at a glance what I'm about.
<img width="358" alt="screen shot 2016-08-15 at 3 46 14 pm" src="https://cloud.githubusercontent.com/assets/12228435/17682722/5bc50ca8-6302-11e6-976c-400336e7e08b.png">

**Comment by HPaulJohnson** [comment]
@vojtechmozilla I started to braindump some possible things we'd want to test in this doc:

https://docs.google.com/document/d/1aKJPFx8Ef7teBfmEZ3BWBWJIRmbHcI_obC7WNn7PAos/edit

I'll continue to add to that list but hopefully we can meet to hack and prioritize.

**Comment by vojtechsedlak** [comment]
Hey @HPaulJohnson, I fleshed out some of the ideas you listed in the following spreadsheet: https://docs.google.com/spreadsheets/d/1jGE88R9wJBVqwawOObWNS8mB2OmecWGUAKk-cFzgN5M/edit#gid=0

I adapted a template that Adam Lofting put together for EOY test sprint. It should help us prioritize the testing ideas.

Looking forward to chatting in a bit.

**Comment by vojtechsedlak** [comment]
Update as of August 22nd:
- Testing summary write-up will be completed today and all required tickets will be created and assigned. 
- Conversations are taking place around specific analytics-related items.
- Google Analytics implementation will be fleshed out and executed this week

**Comment by damiankay** [comment]
Hi @vojtechmozilla - do we have GA code yet? I'm going to send an email to you and the Fission devs now - you can work with them directly to get it set up today. 

Thanks!

**Comment by vojtechsedlak** [comment]
Hi @damiankay, we can actually implement GA tracking through the Nation Builder control panel, so no dev work should be needed on that piece. I will be putting together an additional event-tracking script, which will need to be inserted into the page, but I should be able to do that through the UI as well. If you can give me emails for relevant stakeholders on Fission's side, I can follow up with them directly. Thanks!

**Comment by damiankay** [comment]
That all sounds perfect @vojtechmozilla - thanks! 

I'll send you contact emails via chat.

**Comment by a-kilroy** [comment]
Can you all make sure I have access to your GA?

**Comment by valianttry** [comment]
@vojtechmozilla here are a few suggestions for the metrics spreadsheet: 

**Summary Tab:**
- Does "community growth" = new opt-ins in Salesforce? We should track that conversion % at each step of opting in: Sign petition > check the box to join the list > click "confirm" in the confirmation email. Understanding the success at each step of this funnel for each locale would be very helpful. 
- At the bottom of the "summary" tab can you provide some definitions of terms, such as "Active Advocates"?
- I recommend bumping the "signatures by country" chart below the table in the "Summary" tab -- i didn't scroll so I missed it! 

**Other:**
- Can we add a tab for email performance? Perhaps this can be the toplines vs. our averages, with a strong caveat that our baseline is primarily U.S.
- It would be good to see "In what ways is our list growing / improving in target locales during the campaign?" For instance, can we also see a "start of campaign" table of country / language makeup for our list -- and see a periodic "update" column of growth for each language / locale?

**Comment by vojtechsedlak** [comment]
Thanks for these great suggestions @valianttry! I have added the category definitions as comments and will work on expanding the scope of the document. I've modified the 'Community Growth' category to only include people who confirmed their subscription. I agree the full funnel picture is important, so will try to prioritize that. 

Let me know if you have any further suggestions! Thanks.

**Comment by damiankay** [comment]
Hey @vojtechmzl - can we close this or move it to another milestone (perhaps "bluesky" if there's no particular due date?)

**Comment by damiankay** [comment]
Hey @vojtechmzl - as per #346 we are launching Petition V2 in two stages. 

Sep 20 we launch initially with new content, but the existing form design
Sep 22 we add the new form and additional complex animations

Is it possible to add testing around the two forms to compare how they perform?

**Comment by vojtechsedlak** [comment]
Hey @damiankay, would it be possible for both versions of the v2 action page to exist concurrently after the 22nd, so we can split the traffic in between them and thus evaluate the difference in their performance? Otherwise we will have to compare the results asynchronously, which is not ideal, but should be fine, as long as we have enough of a sample for each variant.

**Comment by damiankay** [comment]
Hi @vojtechmzl - I'm don't think that's possible, but I'll check with Fission. 

With a service like Nationbuilder, they only give us one instance to work with (not even a staging version), so I'd be surprised if we can run two instances of the site, but I'll see if this is possible.

**Comment by vojtechsedlak** [comment]
According to Fission it will be possible to have both versions of the v2 petition page running concurrently, which means we can set up an Optimizely test. This will need to happen on Thursday or as soon as the new form is launched.

**Comment by damiankay** [comment]
Hi @jendc123 - FYI, we're going to want to set up a second instance of the website to A/B test the forms. Our thinking is that the production URL will use the new form when it's live, and the staging URL will have use the current form. Do you foresee any problems with this?
