### ISSUE TITLE
Need a Method to Preview Nationbuilder Pages for localizers

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#208]
We will be using volunteer localizers and a vendor to support our Tier 1 and 2 localization. Ideally we should be able to share with them the localized text "in context" for them to review. 

According to @ScottDowne, we can use Pontoon for "out of context" localization. However, we will need some way to preview the localized pages.

Is there a test server or some other arrangement that would allow the pages to be viewed before public launch?

**Comment by valianttry** [comment]
Update from Scott:

> The TLDR as I know it is we can have our localization data on pontoon without in-page editing, and using out of context editing instead. Looks like this https://pontoon.mozilla.org/en-GB/firefox-input/LC_MESSAGES/django.po/?string=60560 Then we manually put these strings into nationbuilder.
> 
> The long story as I know it is.
> 
> The majority of sites on pontoon are done without in-page editing, it's only a select few that take the time to integrate fully with pontoon, as it has special requirements, and isn't as straight forward as it looks.
> 
> Pontoon currently only reads and writes localization data from a github repo.
> Pontoon reads and writes localization data in a certain file format.
> Nationbuilder doesn't give us enough control of the server to consume content from this file format.
> Nationbuilder is not built from content in a github repo.
> 
> With those limitations in mind, we ultimately have two blockers. We need a github repo to point pontoon to, and we need to manually move localization data into nationbuilder, manually.
> 
> I can create a repo, with the copy we need translated in the correct format, and point pontoon at that repo. This is a fairly low amount of work, and gives us out of context translations in pontoon.
> 
> There is a hacky way we could get around all this, but it basically ends up with me creating an actual webpage that looks and acts like whatever is on nationbuilder, and keep those in sync, which, at that point, why not just build it out ourselves?
> 
> I don't have a better answer at this moment, given the time, we should go with out of context editing on pontoon and manually add those to nationbuilder.

**Comment by valianttry** [comment]
cc @ScottDowne 

@gholme4
@imagerwalt
@annahov
@jendc123

**Comment by damiankay** [comment]
@ScottDowne @valianttry  - @jendc123 indicated that they can spin up temp staging sites for review of translations (not true staging sites though - they can't deploy directly to production).

**Comment by valianttry** [comment]
@damiankay THIS IS SO EXCELLENT! Kontextor is loading up the Tier 1 translations tomorrow, so if we can get those staged for L10N to review that would be outstanding.
