### ISSUE TITLE
Benchmarks for CSI Gif

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#210]
Let's add some good benchmarks for:

-Procedural crime shows
-Show openers
-Cable TV advertisements for cheesy dramas

**Comment by brettgaylor** [comment]
One of my favs:
Incredible Hulk opening:
https://www.youtube.com/watch?v=YOXpKUu6pUg

So awesome and ahead of its time!  A lot of backstory and exposition packed in there.

The trailers for the show are pretty dope, too
https://www.youtube.com/watch?v=oY5vxacjDgE

https://www.youtube.com/watch?v=JhlDaOW42FE

**Comment by brettgaylor** [comment]
Looking at this opener:
https://www.youtube.com/watch?v=X-LZWMc-OEY

We could totally do a :30, and it might be fun to pull out a few key characters from the stock footage and give them names.

"Sheila Sharesalot:

"Reaction Richard"

**Comment by natalieworth** [comment]
I think this is my favourite ticket yet.

**Comment by KevZawacki** [comment]
@brettgaylor @natalieworth 

Report-out from my favorite Mozilla homework assignment yet: **[CSI: GIF Benchmarks](https://docs.google.com/document/d/1ltBwtg33zQSjcMLhYluYUvLZwQyuC6C_aa8AreYRSjE/edit)**.

This Google Doc includes links to and notes on 9 procedural crime drama opening sequences and 4 procedural crime drama trailers.

**Comment by KevZawacki** [comment]
My initial thoughts:

We should do a trailer -- the narration allows us to give the skit a bit more context, and also more tropes to play around with.

The best benchmarks, IMO, are the trailer for [CSI Cyber](https://www.youtube.com/watch?v=cWMcSiRcbC8) and the intros for [Criminal Minds](https://www.youtube.com/watch?v=BicBp_HyoOw) and [CSI Las Vegas](https://www.youtube.com/watch?v=3NzgPNpQkno)

Specific traits we should use: 
- Rollicking music
- Limited narration at the beginning to provide clarity: "Coming fall of 2016 -- a new crime drama about illegal gifs in the EU and the criminals who make them..."
- Expository soundbites from characters: "I knew this gif was illegal the moment I saw it"  
- Ken Burns effect on newspaper headlines: "12 arrested in illegal gif ring" ... "Hundreds of illegal gifs discovered on grandmother's harddrive"
- Zoom effect on a gif -- up close, all the pixels say "Copyrighted! Do not remix!"
- Need an explosion at some point
- Lots and lots of cliche stock footage :-)

@natalieworth @brettgaylor thoughts?

**Comment by natalieworth** [comment]
These are great @KevZawacki @brettgaylor. I've started a google sheet to keep track of mine here: https://docs.google.com/spreadsheets/d/1-3iFLs4ho9VBn86sCXTErmaIeiQTLCJdUk9yY5eU6i4/edit
Would be awesome to identify some favourites as our benchmarks and then pull out the traits (like Kevin's already done) to include in our video and develop the narration?

**Comment by KevZawacki** [comment]
Benchmark'd
