### ISSUE TITLE
Localization strategy for videos

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#212]
Now that we are live on Pontoon, we're starting to see lots of locales translate the site and ask for it to be on production.

When we have videos on our site, it presents a bit of a problem: not all of our videos are localized either with audio (dubbing - as we did in spanish and german for encryption2), or with subtitles.

It would be great if we could somehow indicate to localizers that they can localize the video on Amara (when applicable), and that this would be a requirement for a locale being considered localized. This would also require us hosting videos in a way that is compliant with Amara (eg youtube).

Migrated from: https://github.com/mozilla/advocacy.mozilla.org/issues/209

**Comment by ScottDowne** [comment]
@mathjazz thoughts on this?

FYI, Amara is a tool for subtitling a video.

I'm thinking, we have a link in pontoon that's a link to a video. The localizer would then use a tool, like amara, and translate the video, and it creates a new link? (Brett, is that correct)

Then paste that link back into pontoon for the desired language?

**Comment by mathjazz** [comment]
That sounds like an elegant solution to notify users about localizing video. A string which is a link to the English video should also have a detailed comment explaining how to translate the video and what to do with the link.

@flodolo @peiying2 Thoughts?

**Comment by flodolo** [comment]
I'd need more details on how this would work (what's the string localizers would see? Link to Amara should be the same for all languages), but it seems confusing. A link in the video's description on YouTube seems more visible, we just need to let people know they can localize subtitles if they want.

**Comment by ScottDowne** [comment]
We don't yet know how it would work, first trying to figure out what's possible.

**Comment by ScottDowne** [comment]
I think the general idea is the string is a link to the translatable video in amara, and a comment to help with the confusion?

I think what we're trying to solve is an easy way to get a video to the l10n community so they can add subtitles.

**Comment by flodolo** [comment]
The problem is that a link to Amara is not a string, and it's not localizable, hence the confusion. If it's a comment to an existing string that would make more sense, but I'm not sure there always be a string for a video.

**Comment by ScottDowne** [comment]
I'm not following.

Say we didn't want to put a link to amara with a comment in the string. Do you have anything else in mind? Just exploring options, not set on anything yet.

I hear you though, that putting it in the string is confusing, and we're not dead set on that.

**Comment by flodolo** [comment]
I think there's a misunderstanding: I'm saying that having a string like `http://amara.org/en/videos/9uT23JBpJeQW/info/masterfirefoxoscom-marketplace/` doesn't make sense (that's how I interpreted Matjaz comment).

If instead is a normal string, like "Look this video about XYZ", and the link to Amara is in the related comment, it makes sense. But we might not always have such a string, e.g. if the video is displayed embedded.

**Comment by brettgaylor** [comment]
@mathjazz Is there a capacity for notes/instructions on Pontoon?

**Comment by brettgaylor** [comment]
@flodolo could we not use "look at video xyz" as a 'string', and mark it complete when the task it references is complete?  We're trying to find a social hack like this that would make sense within a pontoon workflow.

**Comment by flodolo** [comment]
No, that wouldn't work. It's a string, the "task" is complete when the string is translated, it can't be logically tied to an external resource.

**Comment by valianttry** [comment]
We should cc Peiying Mo on this ticket, so we don't have 2 separate conversations. @flodolo can you cc her? I'm not sure what her Github is.

**Comment by flodolo** [comment]
She was already CCed above (@peiying2)

**Comment by brettgaylor** [comment]
Is there a chance this could just be covered by existing features that give instruction to localizers? ie we can give the instruction " this page is special - it has a video you need to localize here".  

And as a follow up, could our process be to mail localizers from within the Pontoon platform if this task is missed?

**Comment by mathjazz** [comment]
> @mathjazz Is there a capacity for notes/instructions on Pontoon?

Yes.

You can add a comment in the file above the string it belongs to like this:
http://hg.mozilla.org/releases/mozilla-aurora/file/c16b845d2080/browser/locales/en-US/chrome/browser/accounts.properties#l9

And Pontoon will display this as a comment:
https://pontoon.mozilla.org/sl/firefox-aurora/browser/chrome/browser/accounts.properties/?string=135741

## 

I talked about this issue with @flodolo on IRC. As much as I like the idea of using a localizable string with URL to the video and a comment explaining what to do with it, I share @flodolo's concerns that it's quite brittle, because some localizers won't read comments.

I suggest we set up video localization on Amara and notify localizers how to participate via our standard communication channel (mailing list). We can also add these instructions to the project information in Pontoon.

It will probably make things less automated for you when deciding which video localization to deploy for which site localization, but we sadly don't have a good video subtitle l10n in place.
