### ISSUE TITLE
List of content that needs approval. 

### ISSUE THREAD

**Issue by shaghdoosti** [MozillaFoundation/Advocacy#213]
Have put together a spreadsheet - please fill out friends: 

https://docs.google.com/spreadsheets/d/1wQt_Em7DkEWprx-bFHqV8CpHJub3T5Gf9YCKqbMA1XE/edit#gid=0

@brettgaylor @valianttry @HPaulJohnson @KevZawacki

**Comment by KevZawacki** [comment]
@shaghdoosti Thanks! I've just added blog 1 and our op-ed

**Comment by brettgaylor** [comment]
I think we can close this, as it was meant to describe just the creation of the sheet, right?
