### ISSUE TITLE
Question: What do we mean by Launch Sep 15

### ISSUE THREAD

**Issue by shaghdoosti** [MozillaFoundation/Advocacy#214]
I realized I don't have complete clarity on this - when we say we want the technology to be ready on Sept 15. What do we mean? Does that mean that on Sept 15 - hosts have already populated the site with events and it's ready for RSVPs? Or do we mean that then it will be ready to share with hosts? 

@a-kilroy @damiankay would love your thoughts on this.

**Comment by a-kilroy** [comment]
Well we can't have a public launch without at least some seed data (events in this case). With all the changes in the schedule I am unclear if this is the internal launch (allowing us to add data) or the external launch.

**Comment by damiankay** [comment]
I'll have a look at the dates today and will clarify whether this date is internal launch of public. Thx!

**Comment by damiankay** [comment]
Still waiting to meet with Fission, but I think it's safe to say that Sep 15 is our "soft launch". After this date we'll need hosts to seed their events. Would be great to work out exactly what is required and timing for onboarding hosts, promotion, and signing up attendees.

**Comment by damiankay** [comment]
Confirming that Sept. 15 is our soft launch date. I'll start a separate issue to create a roll out plan.
