### ISSUE TITLE
Complete Fission discovery survey for Maker Party

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#215]
Hi Arielle,

I'm not 100% clear on whether this has been completed. If not, I'm hoping you and I can complete this discovery survey from Fission asap: 
https://docs.google.com/a/mozillafoundation.org/forms/d/e/1FAIpQLSe_NCN5gVXyn7aytaDznkdsK4ekhfU2vF1Pz7xA68fPgaVAzQ/viewform?c=0&w=1

I'll see if I can set up a time for us to go through it together. Would be great to complete this tomorrow (Aug 16) if possible, as I believe it's a blocker for Fission. 

CC @geroter

**Comment by damiankay** [comment]
@a-kilroy - it looks like there has been some discussion in the following docs: 
Responses: https://docs.google.com/document/d/1MSxvSLngHl1_9yyxjsajE4zTFZ5zvb6iJbFm9mqxImk/edit
Reference (user stories): https://docs.google.com/document/d/1driaq40M1b085sbyDoJSQAFkMsvEPvhnux3E-ZIkHN8/edit#heading=h.fx6wqxf7zyya

Let's refine our responses and send to Fission.

**Comment by a-kilroy** [comment]
Sure but I think we need at least one of the advocacy team to join us. There is a lot of campaign strategic language asks in there and I'm not deep enough in this to feel comfortable making that call.

**Comment by damiankay** [comment]
Ok - let's tackle what we can due to the time difference, and I'll complete with @shaghdoosti. 

Thanks

**Comment by damiankay** [comment]
This has been completed and shared with Fission. The revised discovery document can be found here: https://drive.google.com/open?id=1jQqTBKRQebVz7DV0dbDsmsknTPMXnPCQyHsUA154ycE

**Comment by damiankay** [comment]
Thanks @a-kilroy - FYI, I talked through this with Jennifer from Fission and asked her to flag if it will be out of scope. She thought that they would be able to fit it in as the functionality should be built into Nationbuilder already. Thx!
