### ISSUE TITLE
Maker Party Slide Template

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#216]
To support various content used within activities and with outreach, develop a simple slide template that includes Maker Party branding. 

@lovegushwa @chadsansing

**Comment by lovegushwa** [comment]
@HPaulJohnson I think we can adapt this template: https://docs.google.com/presentation/d/1Ibb0WgTwdXBON1UxYjQMu3DftK2PcwNiiCCKgkuibZs/edit#slide=id.g165eabf55d_2_173

Can we connect on the exact kinds of pages and styles needed?

**Comment by HPaulJohnson** [comment]
I think the main intent was to build a template for host and partner packs,  which you've already done. Might be nice to create a blank deck that we can supply to hosts if they want to create any of their own, event-specific slides. For that we could use this same template/style. I wouldn't put too much work into it however, given the big applications have already been designed for.

**Comment by damiankay** [comment]
@HPaulJohnson Can we close this?

**Comment by HPaulJohnson** [comment]
yes. closing.
