### ISSUE TITLE
Maker Party Activity Template

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#217]
Updated style and branding on existing activity templates to match Maker Party landing page and other assets. 

@flukeout @lovegushwa @chadsansing

**Comment by HPaulJohnson** [comment]
@flukeout @lovegushwa 

Just wanted to bump this one back up. Sounds like @chadsansing has some cycles to migrate all the final activities, clean up formatting, etc this week if we can finalize the template design.

**Comment by lovegushwa** [comment]
We can use this template:
http://chadsansing.github.io/curriculum-testing/color-picker-challenge/session01-color-picker-challenge.html#overview

@chadsansing if I remember correctly you can build these curriculum pages and put them on staging, I think the content is done so green light to start building them!

@flukeout Do you have cycles to design some kind of interesting graphic for the 5 different activities?
https://drive.google.com/drive/u/1/folders/0B0RBD2BW-srIdUV5d0NEVzNJY00 
I can help figure out a way to incorporate the maker party graphic, but I imagine it would work something like this: 

Makerparty logo here ( https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvckRfM2kxSVVNc3M&usp=sharing )

<img width="1336" alt="screen shot 2016-08-29 at 9 42 22 pm" src="https://cloud.githubusercontent.com/assets/12228435/18076289/8bfa4dd6-6e31-11e6-9581-d4110aa10d9d.png">

**Comment by HPaulJohnson** [comment]
If we could also add a CTA to the bottom of each activity that links to Events Platform for event hosts. Can say something like "Manage Your Event"

**Comment by chadsansing** [comment]
@HPaulJohnson - preferred CTA link?

**Comment by chadsansing** [comment]
@HPaulJohnson et al. - I think at one point we discussed dropping the 21st C and Web Lit skills from the template for Maker Party; is that right, or is it better to keep those from a #onemozilla perspective and for discoverability in whatever curriculum database we build?

**Comment by chadsansing** [comment]
@HPaulJohnson, @lovegushwa - how would you like Meme-Land to show up in [this activity](https://docs.google.com/document/d/1bA_w9iFnZBHkXReadQ6mBqHwitn-czD2_YmfVpbJ484/edit#heading=h.f7ep9jqhayw0)?

**Comment by HPaulJohnson** [comment]
@chadsansing I think the 21c/Web lit skill section might be confusing without any context. I'd suggest we drop. 

RE: link, we'll have to use a placeholder for now as we don't have the site (or know the URL's) ready yet. 

I will let @lovegushwa answer the meme-land question as he know more about it's current status.

**Comment by chadsansing** [comment]
Alright, but you owe me a web lit campaign ;)

**Comment by lovegushwa** [comment]
@chadsansing has evolved into "postcrimes" which is really not about making memes, so I'm not sure how it will (or if it needs to) fit into the activity.

<img width="901" alt="screen shot 2016-08-30 at 3 08 32 pm" src="https://cloud.githubusercontent.com/assets/12228435/18108964/c0259196-6ec3-11e6-803d-267dfe30ad57.png">

Current UI here:
https://redpen.io/p/nh27685702875c9bf8

**Comment by damiankay** [comment]
Hi @chadsansing - have you rolled out localized versions of activities in the past? We're wondering how we might handle localization for this year's Maker Party activities. 

CC @lovegushwa @HPaulJohnson @valianttry

**Comment by chadsansing** [comment]
@lovegushwa - okay; got it.

@damiankay, when we've rolled out activities localized by language in the past, we did so after a campaign to recruit volunteer contributors to translate content for their communities (and sent them swag, such as t-shirts, I believe). We identified languages for localization by looking at traffic on the original pages we localized. 

![screen shot 2016-08-31 at 6 16 20 am](https://cloud.githubusercontent.com/assets/4128600/18124975/77862c32-6f42-11e6-82cd-406751f8018a.png)

When we've localized by affinity, we've changed small pieces of content (such as images or examples) to reflect the interests of our audience members.

![screen shot 2016-08-31 at 6 17 58 am](https://cloud.githubusercontent.com/assets/4128600/18125037/b3bee5ae-6f42-11e6-9cf4-0b736910799b.png)

In both cases, we've relied on input and/or contributions from community members inside local spaces.

One way to go for Maker Party might be to host source activities wherever we host them, but also to provide copies in Thimble for easy remix by anyone. Otherwise, I think we'd need a team of staffers and community volunteers identifying what should be localized and how best to localize that content for whichever places we choose.

**Comment by damiankay** [comment]
Hi @chadsansing - thanks for the detailed response. 

Your suggestion to provide copies of activities in Thimble for hosts to remix with their own language / local cultural references sounds like a great one to me. 

I'm adding @chrislarry33 @shaghdoosti @geroter > would love to hear your thoughts on this recommendation. It seems like a great alternative to front-loading localization while we're also trying to get the Maker Party site out the door.

**Comment by damiankay** [comment]
@chadsansing - what work needs to be done to create Thimble versions of these activities? I think that's the solution that we're going to go with. Thanks

CC @geroter @ScottDowne

**Comment by geroter** [comment]
Great idea.

**Comment by chadsansing** [comment]
@damiankay - copy and paste the code into one Thimble project or several and then publish for the URLs. If you put all of the activities into one project as separate pages, the URL for each will be the stem + /nameofthefile. If you put each activity into its own project, the URL for the overview will be the stem + /#overview.

**Comment by damiankay** [comment]
Super - thanks @chadsansing ! 

@ScottDowne - is this something you could take on this week?

**Comment by ScottDowne** [comment]
@damiankay I think so, yes. Which would you consider a higher priority, this or https://github.com/MozillaFoundation/Advocacy/issues/145

**Comment by damiankay** [comment]
@scottdowne I think your assessment of priorities is bang on: 
#81
#217
#326
#145

**Comment by ScottDowne** [comment]
I created a new issue with something a bit more actionable, as I felt this was more of a meta ticket to discuss what we should do, a lot of which isn't going to be done. So to reduce confusion, we've dumped this history and now moving us to https://github.com/MozillaFoundation/Advocacy/issues/342
