### ISSUE TITLE
Access / Create Advocacy YouTube channel

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#218]
Hi @cadecairos @ScottDowne 

Do either of you know the status of the Advocacy YouTube channel? I believe this was an issue with the Encryption videos, and we ended up hosting them. Can you please provide some background and suggest a plan of action (I.e. should we continue trying to access the account)? 

Please feel free to re-assign / CC anyone else who might have more information. 

We'll need to resolve this issue by Aug 26. 

CC @valianttry @brettgaylor

**Comment by brettgaylor** [comment]
I believe this was created.  cc @HPaulJohnson @KevZawacki . Or maybe we just started using main Mozilla channel?

**Comment by KevZawacki** [comment]
Everyone -- MoFo and MoCo -- was locked out of the previous Mozilla YouTube channel. 

During the encrpytion campaign, we created a Mozilla Advocacy channel to host our videos: https://www.youtube.com/channel/UCltqjpqVd-IowlC-iLp91eg

That channel is now simply "Mozilla," and will continue to house Advocacy videos.

**Comment by damiankay** [comment]
Thanks for clarifying @KevZawacki - I'll close this issue.
