### ISSUE TITLE
Secure contract with DEG for email production backup

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#219]
When @stephaniemcv is on PTO or at capacity, we would like to have backup support. DEG is a firm that already does this work under contract with Mozilla Marketing. 

I have launched a legal bug here for a new contract addendum with DEG:
https://bugzilla.mozilla.org/show_bug.cgi?id=1293574

I am hoping to have this contract secured this week, and have DEG help asap.

**Comment by valianttry** [comment]
DEG should send over draft language and markup today on SOW and MSA amendments. (Bugzilla bug has details.)

**Comment by damiankay** [comment]
I believe this is done - please re-open if not!
