### ISSUE TITLE
Survey results: Encryption

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#22]
Hi @adamlofting and @shaghdoosti  --- I was sharing the results of our before/after survey in our "New Hire Onboarding" presentation with Policy. I think it would be a great blog post to: 1) Share this, and put it in context that helps understand if these data are something to celebrate or if we have a lot more work to do; and 2) reinforce our thinking about KPIs and how important measurement is for advocacy success. Either of you feel like writing this blog post or have something already you could repurpose?

![policy-advocacy_for_new_hires_may_2016_pptx_-_google_slides](https://cloud.githubusercontent.com/assets/9830371/15198531/cc51752c-178c-11e6-92bd-03ffc8aff2f4.png)

cc @msurman

**Comment by damiankay** [comment]
Hey @valianttry - is there an action we need to take for this. Did someone end up writing a blog post? Is it still relevant?

**Comment by valianttry** [comment]
It could be a good blog post in the future, but I don't believe anyone wrote anything. I'll close.
