### ISSUE TITLE
Script for CSI GIF

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#221]
Based on the benchmarks, lets write a :30 script for CSI GIF.

We should have this EOD Wednesday so that we can move to editing on Thursday.

**Comment by KevZawacki** [comment]
@brettgaylor Sounds good! I'm on it.

**Comment by KevZawacki** [comment]
@brettgaylor [CSI: GIF script, take 1](https://docs.google.com/document/d/1ltBwtg33zQSjcMLhYluYUvLZwQyuC6C_aa8AreYRSjE/edit)

**Comment by brettgaylor** [comment]
cc @natalieworth

**Comment by KevZawacki** [comment]
I believe we're all set here. Re-open if I'm wrong!
