### ISSUE TITLE
Sign up for Bablic for Nationbuilder localization

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#222]
I've asked Alexei to help sign up for Bablic, a new service that will help us integrate L10N localizations into Nationbuilder. 

https://www.bablic.com/pricing

NOTE: This is a stop-gap solution until we can integrate Pontoon with Nationbuilder.

cc @damiankay @ScottDowne

**Comment by valianttry** [comment]
@cadecairos is setting this up now.

**Comment by cadecairos** [comment]
This is set up. @valianttry and @ScottDowne are Admins. 

Teir 1 and 2 languages are enabled for localization (but none are published, and none are using machine translation)
