### ISSUE TITLE
Determine: Integration for Bablic (Pontoon or Github?)

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#223]
This software integrates with Nationbuilder:
https://www.bablic.com/pricing

L10N will continue to provide localization support for Advocacy. L10N is most comfortable with Pontoon, and asking them to learn yet another tool is prohibitive.

We need a way to move translated strings into Nationbuilder.

**Comment by ScottDowne** [comment]
The issue, as I understand it is we need to get translation data from github, created via Pontoon, into nationbuilder, via bablic.

I think doing this manually is the short term.

This ticket is about long term use, and to automate it? So it doesn't need to be manual, correct?

If so, I'm first going to figure out what's involved, how much work is involved.

Then, if it's a significant amount of work, I want to make sure our commitment to this flow (pontoon+nationbuilder) is long term.

**Comment by damiankay** [comment]
Hi @ScottDowne - as we're committed to shipping Maker Party via Nationbuilder, can you please scope the work required to integrate Pontoon with Nationbuilder? We're having so many problems with Bablic on the Petition site, it makes me shudder to think what will happen if we're dependent on it for Maker Party which has many more moving pieces. 

Can you prioritize this for early next week please? Let me know if you'd like to discuss.

**Comment by damiankay** [comment]
Let's revisit this after we launch Maker Party and discuss work required with Matjaz.
