### ISSUE TITLE
Copyright Petition: Design email template

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#224]
Hi @lovegushwa 

Starting a ticket to track the email template for copyright petition.

@valianttry suggests reusing the template from the Encryption campaign. Are you OK with that approach? 

I can set the milestone depending on whether a new template is required (we can also create an estimate). 

Thanks!

**Comment by valianttry** [comment]
We could consider just using the existing email template. Here's a screengrab for reference (@lovegushwa this isn't a critical task IMHO, but I defer to you re: your team's capacity / prioritization here):

![_test__celebrate__worldemojiday__-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/17682546/25e24b42-6301-11e6-829a-ce2c58c0a6bb.png)

**Comment by lovegushwa** [comment]
@valianttry I think this is the one we want right? (but with updated colors) ... 600x300px image
![screen shot 2016-08-16 at 10 01 41 am](https://cloud.githubusercontent.com/assets/12228435/17708136/8308def2-6398-11e6-97ff-2aff87ca10b6.png)

**Comment by lovegushwa** [comment]
Oh I think we should close this ticket in favor of #197 , don't think we are going to design a new template.
