### ISSUE TITLE
Create internal FAQ document for copyright campaign

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#225]
We will be fielding many questions in this campaign, it might make sense to have an internal document that we can use when speaking with media or other folks about the campaign.  Example questions:

-If taking pictures of the eiffel tower at night is illegal, but people do it anyway, what is the harm? 
-As above with GIFs/memes
-So are you saying that people should be allowed to do whatever they want with images they find online?

These sorts of questions we should have some standard answers to.

**Comment by KevZawacki** [comment]
@brettgaylor FAQ taking shape [here](https://docs.google.com/document/d/1Rma9qCpPWQPSKPvMhmYbNnsVAobV7TKvwRBlWs_drjI/edit). Feel free to poke holes / add additional questions. 

cc @HPaulJohnson

**Comment by KevZawacki** [comment]
We'll continue to add to this throughout the campaign, but we're in good shape. It was valuable during Katharina's interview with TechCrunch today.
