### ISSUE TITLE
Create title sequences for CSI GIF

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#226]
Based on our benchmarks, create a title sequence that has the show title, cast, etc

**Comment by natalieworth** [comment]
Brett and I were able to work on this during our 2 day sprint last week. Created some benchmarks here:
https://docs.google.com/presentation/d/1prB8NGsEz0aNOgDXSg7aLUcp0oaPFw9CWhOQJw91-dA/edit#slide=id.g1647c9113b_0_12

And started exploring title design here:
<img width="637" alt="screen shot 2016-08-22 at 9 25 02 am" src="https://cloud.githubusercontent.com/assets/14876567/17862510/7d52f126-684a-11e6-9eca-fed94bcb9198.png">
<img width="635" alt="screen shot 2016-08-22 at 9 24 54 am" src="https://cloud.githubusercontent.com/assets/14876567/17862502/6d3e0c1c-684a-11e6-8db4-5090979e6cb3.png">
<img width="637" alt="screen shot 2016-08-22 at 9 24 44 am" src="https://cloud.githubusercontent.com/assets/14876567/17862504/6eacb828-684a-11e6-8794-0a4be709eeb9.png">

**Comment by natalieworth** [comment]
All final exported files for CSI:GIF are here: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0dEJSM3A5U0VNUjg

**Comment by natalieworth** [comment]
All final exported files for CSI:GIF are here: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0dEJSM3A5U0VNUjg
