### ISSUE TITLE
Tweaks needed to social share for "update your software" email

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#23]
Minor updates needed to the social share stuff for this campaign:

@KevZawacki I suggest we tweak this copy so it says "Protect yourself and safeguard privacy+security on the Web - update your software. I just did with @mozilla’s help: http://mzl.la/update"

![share_a_link_on_twitter](https://cloud.githubusercontent.com/assets/9830371/15204985/9327e538-17c8-11e6-9802-79c22d1f24b4.png)

cc @HPaulJohnson

**Comment by valianttry** [comment]
@KevZawacki For Facebook, I suggest we remove the Firefox logo, the rest of it seems OK. Thoughts?:

![post_to_facebook](https://cloud.githubusercontent.com/assets/9830371/15205045/f22282d2-17c8-11e6-9f43-8ee40d9f8b02.png)

cc @HPaulJohnson

**Comment by valianttry** [comment]
@HPaulJohnson is it possible to setup ShareProgress for this?

**Comment by KevZawacki** [comment]
@valianttry 👍 to both updates

**Comment by HPaulJohnson** [comment]
I'd love to use Share Progress here. I'm talking to @ScottDowne later to bring him up to speed on the tool so I'll discuss this specific implementation.

Will this page live on advocacy.mozilla.org site?

**Comment by HPaulJohnson** [comment]
Talked to @ScottDowne and we can implement Share Progress for this. I will work with @KevZawacki to come up with a few copy variations for testing and then add the final Share Progress code in ticket #18

**Comment by HPaulJohnson** [comment]
Good news: we'll be able to do some message optimization here with Share Progress. I drafted a few variations for FB and Twitter. @KevZawacki can you take a look, make edits and add additional ideas? I'll plan on creating the buttons for tomorrow. 

https://docs.google.com/a/mozilla.com/document/d/14kZnFlcMb3mwaaJPgViNsYOKMrR9XWKyhfiIEmKOEn0/edit?usp=sharing

One question: we probably want a hashtag. DPD campaign (existing page) used #privacyaware? Do we like that or are there other suggestions? We used #encryption in most of the shares from the main campaign but don't think it makes sense in the context of this communication.

**Comment by valianttry** [comment]
thoughts:
#iupdated
#besafeupdate
#updated

**Comment by valianttry** [comment]
#dontwaitupdate << WINNER 😄 j/k

 but IT RHYMES

**Comment by HPaulJohnson** [comment]
thanks, @valianttry 

I really like #besafeupdate but doing a twitter search for all of these, it looks like #iupdated was used in the jan/feb campaign. Since there's quite a few tweets (related to mozilla/software updates) already out there using it, I say we just build off it. 

So, my vote is #Iupdated unless someone comes up with a clever ryhme ;)

**Comment by KevZawacki** [comment]
@HPaulJohnson Just added thoughts and edits to the doc.

**Comment by HPaulJohnson** [comment]
thanks, @KevZawacki - I think we are good to go here. @natalieworth we will need updated graphics for FB/Twitter cards and then we can create buttons.

**Comment by HPaulJohnson** [comment]
also, @valianttry or @ScottDowne do we know the URL of the page we want shared? I'll need that to setup the Share Progress buttons too.

**Comment by natalieworth** [comment]
@HPaulJohnson Are there any share progress design assets we need for this?

**Comment by natalieworth** [comment]
@HPaulJohnson Have updated fb/ twitter card illustrations for this share here (based off the email illustration):
https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0bVlrZkcwODVNc1k&usp=drive_web&ddrp=1#

cc @ScottDowne @lovegushwa

**Comment by natalieworth** [comment]
Closing and final illustrations posted in the comment above for this.
