### ISSUE TITLE
Email Performance Action Data 

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#230]
Detailed description of work: @vojtechmozilla  to assist with pulling any historical action data out of Google Analytics to complete Email Performance reports
- [Q1 Email Performance](https://docs.google.com/spreadsheets/d/17QiSIDWzs0WG9BqBYOfAacG59J2fuj_sSId2fNyO7QM/edit#gid=478614526)
- [Q2 Email Performance](https://docs.google.com/spreadsheets/d/1lC--r1dm-TwosxIjiFWarTwsR_xkC-6VFKWfjysIbbQ/edit#gid=478614526)
- [Q3 Email Performance](https://docs.google.com/spreadsheets/d/1ataiSQkBHZ8ceMd7ptJnSadcHcIZCVo5tXYgSm2Xxvs/edit#gid=863353512)

Due date:

CC:

**Comment by vojtechsedlak** [comment]
Hey @stephaniemcv, sorry it took me a while to get to this. I've just reviewed the three docs and filled in the missing Codemoji action data. Please let me know if there is anything else that I missed. Otherwise we can close this ticket. Thanks!
