### ISSUE TITLE
Confirm approvals for localized petition

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#236]
Detailed description of work:
Hi @shaghdoosti - can you please update when you have an idea of whether we need a trusted policy resource to approve each localized version of the petition? 

Due date:
August 19

CC: @valianttry

**Comment by valianttry** [comment]
Sara confirmed: She spoke to Raegan and she would like for there to be a policy review of the tier 1 languages for the petition. 

I'm setting them in Pontoon and documenting process.
