### ISSUE TITLE
Vendor reviews for UGC microsites

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#239]
Evaluate the 3rd parties that will be needed to create the microsite experiences.

We should aim to have this completed August 24th.

**Comment by cadecairos** [comment]
@brettgaylor does this just cover the Cloudinary RRA?

**Comment by brettgaylor** [comment]
This should cover privacy as well as RRA, for Cloudinary as well as Lob.com

We have privacy review completed for both platforms, and an RRA scheduled for 8/22

**Comment by damiankay** [comment]
What's the status of this? Can we close? @brettgaylor

**Comment by brettgaylor** [comment]
Yes!
