### ISSUE TITLE
Finalize URLs for Copyright campaign petition page

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#240]
Detailed description of work:
We need to make a decision about the URLs for the Copyright campaign / Petition page. 
suggestion: advocacy.mozillafoundation.org/copyright
question: does this work for Nationbuilder? 

Due date: August 19

CC: @valianttry @brettgaylor @shaghdoosti @HPaulJohnson @KevZawacki @natalieworth @beccaklam

**Comment by damiankay** [comment]
Just got confirmation from Fission that we can indeed use a sub-directory if that's desired. 

FYI, they need to know our desired URL by Aug 19. 

Who outside of Advocacy (if anyone) needs to be consulted before we finalize this decision? 

CC @simonwex

**Comment by ScottDowne** [comment]
The petition should definitely live on nationbulder, as a sub directory..

I think the technical hurdle of having it live anywhere else is actually out of scope. Petition has to live on nationbuilder in order for it to function, so advocacy.m.o is not an option.

My suggestion is https://mozillafoundation.nationbuilder.com/petition or variants like https://mozillafoundation.nationbuilder.com/copyright-petition https://mozillafoundation.nationbuilder.com/petition-copyright

**Comment by damiankay** [comment]
We can't point to another URL? Does nationbuilder not support that?

**Comment by valianttry** [comment]
George at fission shared this, might be useful:
http://nationbuilder.com/how_to_connect_a_custom_domain

Many sites use Nationbuilder and also have custom domains, like http://www.dci-palestine.org/.

**Comment by ScottDowne** [comment]
I'm not sure though if that works in a subdirectory, though. We obviously need to keep the main page of advocacy.mozilla.org the same, and just have advocacy.mozilla.org/petition point to another page.

@cadecairos ^^ you know if that's possible in AWS?

**Comment by ScottDowne** [comment]
@valianttry I'll dig into those docs and see if it'll work with a subdirectory...

**Comment by ScottDowne** [comment]
Example, a usual way to accomplish this is with CNAME, but that happens for the whole domain, so we would lose everything existing on advocacy.mozilla.org, which would now be what's on nationbuilder.

**Comment by ScottDowne** [comment]
The method in that link would be a whole site "redirect" as well, not a subdirectory.

I just noticed the above proposal was advocacy.mozillafoundation.org. Is that different than advocacy.mozilla.org on purpose? Or just a typo?

**Comment by cadecairos** [comment]
If we wanted to use `advocacy.mozilla.org/copyright` the petition would need to live on `mozillafoundation.nationbuilder.com/copyright`

This is beacuse I'd have to set up a custom behaviour on our CDN to forward requests for  "/copyright" to the nationbuilder hostname, which preserves the path of the original request.

**Comment by damiankay** [comment]
@brettgaylor here are some options for the Copyright URL that have been floated to this point. 

**1. Nationbuilder** 
https://mozillafoundation.nationbuilder.com/petition 
or variants like 
https://mozillafoundation.nationbuilder.com/copyright-petition https://mozillafoundation.nationbuilder.com/petition-copyright

**2. Advocacy**
advocacy.mozilla.org/copyright (the petition would need to live on mozillafoundation.nationbuilder.com/copyright)

**3. Custom URL**
? (more of a strategic questions with regards to naming)

CC @ScottDowne @cadecairos @simonwex

**Comment by brettgaylor** [comment]
I think we should go with advocacy.mozilla.org/copyright

**Comment by ScottDowne** [comment]
OK, so for this url to work, the url structure needs to be the same.

https://mozillafoundation.nationbuilder.com/copyright
https://advocacy.mozilla.org/copyright

is what we can setup.

**Comment by damiankay** [comment]
Great - thanks @brettgaylor 

@ScottDowne I'll ping Fission and ask them to change the directory to "copyright"

Just to confirm, will language be defined via URL variable? I'm assuming we don't require separate directories for each language.

**Comment by ScottDowne** [comment]
@damiankay correct, the language is defined in a query string, not a url directory.

**Comment by damiankay** [comment]
Perfect. Message sent to Fission RE URL. Thanks!

**Comment by ScottDowne** [comment]
Might be good to go. https://advocacy.mozilla.org/copyright/ seems to work once cache is busted. Closing this.

Create a new issue for any more specific issues you find around the url.
