### ISSUE TITLE
Determine site launch time on 8/24

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/Advocacy#241]
Detailed description of work: We need to determine the precise hour the petition site will be fully accessible, so we can coordinate blog posting, press pitching, and social media accordingly.

We should optimize for GMT+2, since those are our target markets.

Proposal: Flip the switch at 10 p.m. PT on 8/23. Kevin can then begin comms at 11:30 a.m. GMT+2 on 8/24.  

Due date: Friday, August 19

CC: @HPaulJohnson

**Comment by damiankay** [comment]
@KevZawacki Fission has indicated that the launch would need to be in the evening. I'll follow up for a specific time.

**Comment by damiankay** [comment]
Confirmed with Fission that the site launch time will be 9pm-12am Central, Wednesday August 24.
