### ISSUE TITLE
Maker Party: Develop global activity

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#244]
Detailed description of work:
We need to develop an activity that will tie all of the elements of the copyright campaign together. This would be something that people do at every event, and that we could potentially share widely for maximum impact. 

Questions:
- Is this possible?
- If so, what’s the budget? 

Due date: 
Need to finalize quickly. Does anyone have an idea of the dependencies to help fix a due date? 

CC: @brettgaylor @lovegushwa @HPaulJohnson @shaghdoosti @geroter @chrislarry33

**Comment by damiankay** [comment]
@shaghdoosti is this still something that we hope to do? If so, would @caltrider be a good person to lead the discussion?

**Comment by chrislarry33** [comment]
Any reason why we dont just use existing activities?
