### ISSUE TITLE
EU Copyright Campaign: Snippet approval and localization

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#245]
Detailed description of work: We have approved snippets/designs from Firefox team. Final copy sent for approval and will then be submitted to l10n.

Due date: 8/22

CC: @KevZawacki

**Comment by HPaulJohnson** [comment]
final copy submitted for approval: https://docs.google.com/document/d/1usPAb3S0kE7nn88kOH2YEs4rGVHvVzbHc7hRo9lhSdA/edit

**Comment by HPaulJohnson** [comment]
Approved by policy. 

Submitted for localization through regular process. @valianttry, can you confirm this is right and there's not a separate process for snippet localization?

**Comment by shaghdoosti** [comment]
Question: Are we aiming to launch on the snippet on the 25th as well?

**Comment by HPaulJohnson** [comment]
Sorry for not seeing this earlier @shaghdoosti - we originally requested 8/24 so easy to push this out a day until 8/25 if that's the target date for pushing everything live. 

We have German and Spanish translated and we're still waiting on French and Polish.

**Comment by shaghdoosti** [comment]
Ignore the 25th - that's a typo from my end. Plan is to go live on the 24th. :)

**Comment by valianttry** [comment]
Just remember the EU is ~8-9 hours ahead of us, so it'll likely actually be the 25th for Firefox users 🕐

**Comment by lovegushwa** [comment]
@HPaulJohnson see v1 snippet icons here:
https://drive.google.com/drive/folders/0B2qu3ExKWIlvbkM4ckt1N2tKM1E?usp=sharing

**Comment by HPaulJohnson** [comment]
Polish complete (available here: https://github.com/mozilla/advocacy.mozilla.org/tree/master/locales/pl)

Just waiting for FR localization to come through and Tier 1 will be complete. 

Also, communicated site launch timing and we'll adjust snippet go-live timing accordingly (tentatively, Thurs a.m. 8/25)

**Comment by HPaulJohnson** [comment]
French localization complete. This done. Closing. 

(Snippet will be set to go live tomorrow at midnight PST, and will be live Thursday morning for EU users).
