### ISSUE TITLE
EU Copyright Campaign: Build snippet template for button test

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#246]
Detailed description of work: Proposed test for upcoming snippet campaign includes use of embedded buttons which require custom template to be developed

Due date: 8/22

CC:

**Comment by ScottDowne** [comment]
Here is the pull request for the snippet template, it's in review, https://github.com/mozmar/snippets/pull/82

I'll update here when that pull request is gone through review, and when it is merged into the snippet repo.

@damiankay @HPaulJohnson

**Comment by damiankay** [comment]
Hey @HPaulJohnson & @ScottDowne - can we move this to another milestone please?

**Comment by HPaulJohnson** [comment]
This is done on our end (closing).  We didn't get it in time to test during this last run but the plan is to incorporate it into the 9/20 snippet flight.
