### ISSUE TITLE
Design 'Case to Give' page

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/Advocacy#248]
Detailed description of work: @valianttry is seeking to build a 'Case to Give' page for 2016 fundraising -- a page that describes how donors' dollars are spent, and what they're enabling.

Overview and rough copy can be found [here](https://docs.google.com/document/d/1YXEooaZfMO3jQoBTzgoLqWmVXQYKNnNkoUXjhiFJqtM/edit). (Being tracked in ticket #247.)

In this ticket, we're hoping to determine design's bandwidth and ideas. The page will likely live at mozilla.org/foundation/xx, so we have to play by those rules. Andrea suggested this might be a project for Becca.  

Due date: tbd

CC: @lovegushwa

**Comment by TheoChevalier** [comment]
@KevZawacki Have we decided where this page will be displayed? I’ve seen Medium mentioned, and unfortunately this is not an option for l10n. However mozilla.org or the donate website will work perfectly

**Comment by KevZawacki** [comment]
@TheoChevalier Still being decided, but Medium seems unlikely.

Mozilla.org and the donate site are likely, so heartening to hear they'll work perfectly!

@valianttry, any updates from your end?

**Comment by beccaklam** [comment]
@TheoChevalier @valianttry @lovegushwa 
Hoped for launch date is: Dec 1st
Allowing two weeks for l10n, web page UI needs to be done by: Nov 17
@TheoChevalier would we be able to get the [Case To Give language](https://docs.google.com/document/d/1YXEooaZfMO3jQoBTzgoLqWmVXQYKNnNkoUXjhiFJqtM/edit) in French by EOD Nov 14? If we need more time to add in Jen Caltrider's quotes and edits, EOD Nov 15 works too. Let me know if these timelines seem feasible.

**Comment by TheoChevalier** [comment]
@beccaklam Yes, I can do that.
What we will need to build by Nov 17 in addition to a mockup or draft UI, is the source strings file like https://github.com/mozilla/donate.mozilla.org/blob/master/locales/en-US/messages.properties 
If you’re not familiar with that, Scott and I can help you. It’s important we get it right, because once it’s exposed to localizers, we can’t change anything without asking them to retranslate.

I’m not sure I’ve seen the quotes you’re mentioning, is this somewhere else?

**Comment by beccaklam** [comment]
@TheoChevalier No they're not in the google doc yet. @valianttry mentioned them to @KevZawacki during the meeting today so I think the text is still not finalized yet.

**Comment by KevZawacki** [comment]
Correct -- sounds like Jen C. may be adding these quotes this week or next.

**Comment by TheoChevalier** [comment]
@beccaklam Here is the French translation of the current version https://docs.google.com/document/d/1TSiU93yaYFN9wj_l0Ozd9AcRh6LQ730k3hzs5QwkvbI/edit?usp=sharing
Please shoot if I can do anything else to help

**Comment by beccaklam** [comment]
@TheoChevalier Thank you!

**Comment by lovegushwa** [comment]
@ScottDowne
