### ISSUE TITLE
Enable donation by Bank Transfer (P1: DE, FR)

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#25]
@stephaniemcv wrote an awesome case for making bank transfer happen, including estimated revenue loss without it:
https://docs.google.com/document/d/1TXQOQk7VsLctDWaRtq-nESoH5GS55X1MPmGKfbdv7Yc/edit

**Comment by ScottDowne** [comment]
Worth reading material:
1. https://support.stripe.com/questions/accepting-ach-payments-with-stripe
2. https://stripe.com/ach-payments/terms
3. https://stripe.com/blog/accept-ach-payments

The third one is just a blog, but it goes into some detail. I also included it because of the date, Jan 2016, which means ach payments might be a new thing for stripe.

**Comment by ScottDowne** [comment]
This is the dev doc for ach payment processing: https://stripe.com/docs/ach

Doesn't `*look*` like it's integrated with stripe checkout, so maybe we'll need to do a bit of dev on this.

It's also probably worth asking a stripe rep for advice on this?

**Comment by damiankay** [comment]
@valianttry any word from Stripe RE whether they have added support for bank transfers?

**Comment by ScottDowne** [comment]
I forgot to follow through with this. They have bank transfer but only for
USA... not super helpful.

**Comment by valianttry** [comment]
I'm meeting with them in 8 minutes and it's on my agenda. I'm going to ask if it's on their roadmap (int'l vs. just US). Will report back.

**Comment by valianttry** [comment]
Update from Stripe:
- ACH Payments: Accepting ACH payments in the US may be an effective way to reduce the volume of checks you receive each month. The following example from Charity Water demonstrates how they accept both credit cards and bank transfers via Stripe: https://donate.charitywater.org/donate/home -- and you can learn more about Stripe ACH payments here: https://stripe.com/blog/accept-ach-payments
- European bank transfers: This is something we're certainly working on, and I suspect we'll have more to share with you by the time you've completed integrating ACH payments for the US.

**Comment by damiankay** [comment]
RE European bank transfers: that's better than "No"

**Comment by valianttry** [comment]
?? true!
I still suspect we may need an entity to accept donations somewhere in the EU (it's mostly difficult because we are a us-based nonprofit, not nec. the tech that is difficult)

[--- Commented from Asana.com
#commenter Damian Kuehn
---[aa]

**Comment by valianttry** [comment]
Moving to Blue Sky as this is an accounting issue and will not be resolved anytime soon.
