### ISSUE TITLE
Restructure copyright campaign localization files 

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#253]
Restructuring the files where we store localization strings related to the copyright campaign.

https://pontoon.mozilla.org/bg/mozilla-advocacy/copyright-petition (can you add "-petition" to the current main folder to serve this purpose?)
https://pontoon.mozilla.org/bg/mozilla-advocacy/copyright-snippets
https://pontoon.mozilla.org/bg/mozilla-advocacy/copyright-email1
https://pontoon.mozilla.org/bg/mozilla-advocacy/copyright-social
https://pontoon.mozilla.org/bg/mozilla-advocacy/copyright-video1

I'm going to create .properties files in the repo to mimic this structure.

Then I'm going to request this structure to be added to pontoon.

There is going to be a moment of disruption if I move these files, until pontoon is updated. One idea to mitigate this is to keep copyright-petition as is, until the other files are on pontoon, then we can remove any duplication in copyright-petition so there is no disruption. I'll double check this method with matjaz, and see if he has a better idea.

Due date: target is Aug 22nd, 24th is final date.

CC: @valianttry @damiankay

**Comment by ScottDowne** [comment]
I also need to remember to move any already localized files in non English files to match the new structure.

**Comment by ScottDowne** [comment]
I figure I should update this...

We have everything but email1, as we don't yet have any email1 strings yet.

What we have is listed as:
https://pontoon.mozilla.org/en-GB/mozilla-advocacy/Copyright Petition/
https://pontoon.mozilla.org/en-GB/mozilla-advocacy/Copyright Snippet/
https://pontoon.mozilla.org/en-GB/mozilla-advocacy/Copyright Social/
https://pontoon.mozilla.org/en-GB/mozilla-advocacy/Copyright Video 1/

which maps to files in here:
https://github.com/mozilla/advocacy.mozilla.org/tree/master/locales/en-US

I'll update and close this once email1 is added.

**Comment by damiankay** [comment]
@ScottDowne don't forget to add labels please! :-)

**Comment by ScottDowne** [comment]
https://pontoon.mozilla.org/en-GB/mozilla-advocacy/Copyright Email 1/

Closing this, as it happened days ago, and I just forgot.

If there are other structures we want setup, we should file a new ticket :)
