### ISSUE TITLE
Q&A for Petition: Feedback for Fission

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#254]
Detailed description of work: Provide detailed edits or changes needed to the petition page and translated versions.

Due date: August 23, 2016

CC: @jendc123 @damiankay 

The petition is looking great! As we start thinking about Q&A I wanted to start a ticket and a list of some tweaks needed.

**Comment by damiankay** [comment]
Link to QA is here: https://mozillafoundation.nationbuilder.com/copyright 

Link for localizers to check copy: https://mozillafoundationstaging-mozillafoundation.nationbuilder.com/

**Comment by brettgaylor** [comment]
Is the form meant to be flush right?  On the nation builder sandbox, I saw that it was flush right in both FF and Chrome.  In link above, it is it the bottom in FF and Chrome.  Screenshot attached

<img width="1280" alt="chrome petition" src="https://cloud.githubusercontent.com/assets/345974/17874309/a659e1ee-687f-11e6-9324-a233452c14ef.png">

**Comment by valianttry** [comment]
Form fields and checkbox updates:

![mozilla_foundation_-_staging](https://cloud.githubusercontent.com/assets/9830371/17874341/e014d2e0-687f-11e6-809d-1611cea7bd4e.png)

**Comment by brettgaylor** [comment]
Also, the Bablic interface for me covers part of the CTA at the bottom of the page, and is generally distracting, on my setup.

Could it be moved?

**Comment by valianttry** [comment]
Tried to fill out form, got this error, but there's no last name field (though we should have one) -- is last name truly required?
![mozilla_foundation_-_staging](https://cloud.githubusercontent.com/assets/9830371/17874468/a60d94e6-6880-11e6-84b9-27fead3f9dc0.png)

**Comment by valianttry** [comment]
The little progress animation that starts below the button after you click sign says "Saving ...." in black text, which is hard to see (perhaps change it to white or light blue? Or just the animation without the word "Saving"?

**Comment by vojtechsedlak** [comment]
Here are my two cents, in addition to the items mentioned above:
- there is no thank you page modal that shows up for me, upon submitting the page simply reloads
- there is no hidden field on the form to capture source URL. I've checked with Gareth and Jessilyn and it is a standard practice to capture the URL so that we know where people come from and save that data in SFDC (using window.location.href)

**Comment by valianttry** [comment]
oh.... German..... sigh. Does not resize to fit the button width.

![mozilla_foundation_-_staging](https://cloud.githubusercontent.com/assets/9830371/17874521/05b05b18-6881-11e6-8883-4f33d132dbc8.png)

**Comment by shaghdoosti** [comment]
I'm looking at it in Chrome - and the petition link is all the way down the bottom - it should be on the right hand side? 

<img width="813" alt="screen shot 2016-08-22 at 3 59 12 pm" src="https://cloud.githubusercontent.com/assets/13626384/17874588/7e1cc29e-6881-11e6-8dee-2b8c4a6e5f23.png">

**Comment by natalieworth** [comment]
Q+A from me:
1) Could we remove one of the arrows? There seems to be the white one and the one embedded in the form in Firefox:
<img width="329" alt="screen shot 2016-08-22 at 3 41 06 pm" src="https://cloud.githubusercontent.com/assets/14876567/17874564/576c2608-6881-11e6-8eee-95b6fc61950c.png">
2) Update this to the giphy .gif file, pull the image from giphys server on page load (liability reasons): http://giphy.com/gifs/pokemon-adorable-gif-k7SZLGTPmEEN2
<img width="742" alt="screen shot 2016-08-22 at 3 41 58 pm" src="https://cloud.githubusercontent.com/assets/14876567/17874571/5d4b675a-6881-11e6-8702-0851255baa69.png">
3) Can we use the .svg versions of these icons to avoid pixelation and get rid of the white background:
https://drive.google.com/drive/folders/0B2qu3ExKWIlvSHJnRElKUnRodzQ?usp=sharing
<img width="77" alt="screen shot 2016-08-22 at 3 43 22 pm" src="https://cloud.githubusercontent.com/assets/14876567/17874589/7ec95bda-6881-11e6-8467-42783c3b6647.png">
https://drive.google.com/folderview?id=0B2qu3ExKWIlvSHJnRElKUnRodzQ&usp=sharing
4) The Mozilla logo in the footer is showing up pretty low res on my screen. We could export one @ 2x or could we use a .svg?
<img width="257" alt="screen shot 2016-08-22 at 3 45 22 pm" src="https://cloud.githubusercontent.com/assets/14876567/17874611/9fa90fd0-6881-11e6-9b98-d67ad9416c3f.png">

**Comment by HPaulJohnson** [comment]
we should drop the "share this page" from the footer. we don't have a dedicated sharing page setup for this (encryption used share progress for this). 

copy for the "please share this buttons" is being localized now but @natalieworth it would be great to design a new general graphic that we can include for FB/Twitter sharing. We can also use this in the OG tags on the page as the default.

**Comment by HPaulJohnson** [comment]
Also, the placement of the language selector is problematic/distracting for me. Especially if the petition is (eventually) pinned to the right hand side this interferes visually.

**Comment by valianttry** [comment]
Also re: footer, can we have the horizontal row of nav links open in a new tab / page?

**Comment by lovegushwa** [comment]
Update to share and footer we discussed today (I'm not sure why squares wont work here? The square icon on blue if my preference. We can use images if needed.)

<img width="1253" alt="screen shot 2016-08-22 at 6 48 41 pm" src="https://cloud.githubusercontent.com/assets/12228435/17878031/b65f3c7a-689c-11e6-8782-616e7cc2fe2f.png">
<img width="1279" alt="screen shot 2016-08-22 at 7 15 45 pm" src="https://cloud.githubusercontent.com/assets/12228435/17878055/e55ae7b8-689c-11e6-91a5-ee100445214d.png">

<img width="356" alt="screen shot 2016-08-22 at 7 17 44 pm" src="https://cloud.githubusercontent.com/assets/12228435/17878084/325c6604-689d-11e6-8990-cd2ccae2230b.png">

<img width="357" alt="screen shot 2016-08-22 at 6 54 03 pm" src="https://cloud.githubusercontent.com/assets/12228435/17878028/b172bac0-689c-11e6-8cea-1f3b5f50c0de.png">

**Comment by damiankay** [comment]
Adding earlier feedback from @valianttry:
- On the country selection drop down, can we limit the countries to ONLY EU countries and "other"? Hopefully 99 - 100% of people signing will be in those ~27 countries, so we don't need to list every country on earth and make it harder to select. Please add "other" to capture any signatures from outside the EU.
- Is it possible to make last name field optional vs. required? 

From @HPaulJohnson:
- Use share copy for OG and meta tags

**Comment by beccaklam** [comment]
Hi team! I agree with all these messages. The design happening between 640px-900px is not working (the form is too skinny and it also covers text and the text is way too close to the margins). But I think Fission is already aware and working on a fix (Re: 13" screens). 

Oh one more thing. The form at large screen sizes is really far away from the rest of the content. Wonder if there is a way to fix it so that it stops after a certain distance away from the article.
![screen shot 2016-08-23 at 10 24 42 am 2](https://cloud.githubusercontent.com/assets/20977376/17895609/a7e88e1a-691b-11e6-8367-28327cbaf2b3.png)

**Comment by lovegushwa** [comment]
We need to include a sticky sign the petition button for 13" and tablet screens (similar to what we are doing on mobile). 

PSD file here:
https://drive.google.com/file/d/0B2qu3ExKWIlvT2FYc3BOUzdTcTg/view?usp=sharing
![screen shot 2016-08-23 at 10 06 14 am](https://cloud.githubusercontent.com/assets/12228435/17901702/6d0b3826-6919-11e6-9fa2-8426e2d39f24.png)

**Comment by lovegushwa** [comment]
Change how the h4 text breaks so we don't get a weird wrap / large line spacing. 
![screen-shot-2016-08-23-at-9 27 16-am](https://cloud.githubusercontent.com/assets/12228435/17904659/0be9e04a-6925-11e6-8a16-16026f16e177.png)

**Comment by damiankay** [comment]
Hi team,

Fission has a few questions RE our feedback above: 
1. Where would the design team like the Bablic button to reside? 
2. For the German button we have two options - A) Wrap text. B) Shrink font size of all button text.
3. Based on Jordan's last item in GitHub it's not clear what he's suggesting for the footer
4. It's also not clear whether we need to remove or keep the social share option (based on Brett's comments?)

@lovegushwa, I think these are really your call to make. I'd say this is our biggest P1 right now. Let me know if you want to jump on a call. Thanks!

**Comment by valianttry** [comment]
Update from Fission: Last Name is a required field.

**Comment by lovegushwa** [comment]
preferred Bablic placement 

![screen shot 2016-08-23 at 1 05 13 pm](https://cloud.githubusercontent.com/assets/12228435/17907803/56a307ee-6932-11e6-8ebb-3716084bd999.png)

![screen shot 2016-08-23 at 1 03 42 pm](https://cloud.githubusercontent.com/assets/12228435/17907840/7ff9b642-6932-11e6-872f-9c133fea3806.png)

**Comment by lovegushwa** [comment]
Mozilla logo .svg https://drive.google.com/file/d/0B2qu3ExKWIlvb01JaW5TM2x5T0E/view?usp=sharing

**Comment by lovegushwa** [comment]
Please add this Twitter Emoji attribution to the HTML (does not need to be visible on the page).

"The small images on this site are Twitter Emoji [CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], you can find them here [ https://github.com/twitter/twemoji ] "

**Comment by HPaulJohnson** [comment]
Comments re: post petition signing, the share overlay:
- Copy and image still look to be the default from the meta data on the page, not prepopulated copy that we've provided. 
- For the "link" share option, it pops a blank window when clicked. I think the desired behavior here is a short notification to appear that says "link copied" (and for the link to be copied to your clipboard, or whatever they call that).

**Comment by lovegushwa** [comment]
We need to update the share image, please use the image here:
 https://drive.google.com/file/d/0B20-0lpP23c0ZXh1TTZvSjMtSlE/view?usp=sharing

Share copy is here (we will add polish when it's avalable @valianttry ):  
https://docs.google.com/document/d/1itsvIJ3KLvBXhKYDa0EAyyeAa0vA6_jCM_6yDIPaviY/edit

![screen shot 2016-08-24 at 9 28 11 am](https://cloud.githubusercontent.com/assets/12228435/17939969/c197673e-69e1-11e6-9430-eceea98e4423.png)

**Comment by HPaulJohnson** [comment]
Note/to clarify, copy/image above to be embedded in the share buttons in the "Please Share This" section at the bottom so that our messaging prepopulates and avoids default messaging like you see in Jordan's screenshot.

We can also use this copy for the OG tags in the metadata for the page, if possible. Not sure how OG tags work by locale? Also, if there are other OG tags/metadata needed (og:title, og:url, og:description,etc) please let me know.

**Comment by lovegushwa** [comment]
Currently the mobile version, particularly german is not working well. I adjusted the type sizes of the header and the stick button to fix this. We can also reduce the heigh of the light red area behind the header type if needed.

The goals of this fix should be:
1. read the german headline
2. make sure the sign the petition sticky button does not cover up the down arrow under "it's time our laws caught up with our technology." 

![screen shot 2016-08-24 at 12 13 55 pm](https://cloud.githubusercontent.com/assets/12228435/17944357/48953e5c-69f4-11e6-9f10-4c27e3e4f3b4.png)

**Comment by damiankay** [comment]
Should "User Language" in the form be changed to "Preferred language"? "User" feels like jargon. 
![screen shot 2016-08-24 at 2 53 28 pm](https://cloud.githubusercontent.com/assets/19785709/17949558/d1fe276a-6a0a-11e6-98b2-a012fee87203.png)

@lovegushwa @valianttry @HPaulJohnson

**Comment by gholme4** [comment]
@damiankay Please ignore the language field. It's only there temporarily for testing.
