### ISSUE TITLE
Final edit of CSI GIF

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#257]
Detailed description of work: Final edit of CSI gif with English narration

Due date: Aug 26th

CC: @natalieworth

**Comment by brettgaylor** [comment]
-start immediately at shot of lab - remove shot of arc de triomphe
-remove “ a new drama about cops…” text
-replace with “coming to television” text
-think you could do something more exciting with the timelapse split screens of europe - make some bigger than others etc  - make this a more interesting composition
-cut immediately after “the people who do”
-immediately after this, start the transition that creates the CSI: GIF logo - don’t sit for more than 1 sec on the shot of cop and lab technician
-follow with text that says:

1) Think this is ridiculous? So do we
2) Let’s bring EU copyright into the 21st century.  changecopyright.org
^ same bumper we’ll use on other two

**Comment by natalieworth** [comment]
hey @brettgaylor —when you download the final music file, can you post/ link to it here and I'll add it to the next final/draft update for export :)

**Comment by brettgaylor** [comment]
@natalieworth voila https://drive.google.com/open?id=0B0bF99sa1fRJSDNSRHl3dWJJSGc

**Comment by brettgaylor** [comment]
get high rez images for the texture elements

FOR NATALIE
:01 fade sound in
:07 - timelapse images are too static / too square of a composition- jazz this up!
:15 - zoom (scale) the laptop and ipad shots
keep CTA on screen till :36 and change to mozilla with the note

FOR BRETT
:19 “gif”
:25 sound goes down

**Comment by brettgaylor** [comment]
Also - his "track down the people who do" should occur over his face - so don't cut to the next shot till :25.

**Comment by brettgaylor** [comment]
Jordan suggested we needed a little bit more punch to proceed the "ridiculous" line, so we should add the shot of the woman being arrested.

Start that clip at the :02 mark so you see the cop arriving, and have it last till at least :05.  Then start the CSI: GIF animation over top of that.  Just cut the scene of the scientists in the lab.

**Comment by natalieworth** [comment]
All final exported files for CSI:GIF are here: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0dEJSM3A5U0VNUjg
