### ISSUE TITLE
8/24 Email 1: Finalize EN copy in preparation for policy review

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#259]
Detailed description of work:  DRAFT is coming together here: https://docs.google.com/document/d/1wJ3spmPItKW5HjthHhWuPEO3hqAd5G9eNy45LhsL80s/edit 

Due date: 8/22

CC: @shaghdoosti

**Comment by shaghdoosti** [comment]
Done! Locked copy.
