### ISSUE TITLE
DRAFT Codemoji email: Initial test to advocacy list segment

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#26]
Audience Segmentation: 50% active advocates; 50% nonAA 
Audience size = 100,000
Audience exclusions: "Inactives" on the list
Signor: Sara Haghdoosti
Launch Date: 6/2/2016
Final Copy Due: Monday 5/3 
Base URL: 
ExactTarget Template:
Approvers:  Andrea W /   Kevin Z  /   Chris R /  Brett G /  Mark S /  Stephanie M 

**This ticket will be closed once the draft is approved**

**Comment by KevZawacki** [comment]
@valianttry @shaghdoosti 

Happy to lend a hand here, if needed! 

I can draw from the Codemoji [key messages](https://docs.google.com/document/d/1iY6OkuVDSJgUx0QSuvjbIQpeRrb0SjPr81Kwyyd4jOA/edit#bookmark=id.gkkwelfaa2ha) and [draft blog post](https://docs.google.com/document/d/1LR4cnKrMjRh8Ht2_t0AJQzjrXruFg3x-UHVPjOxqLN0/edit).

**Comment by KevZawacki** [comment]
Hopefully helpful: A [first-draft Codemoji email](https://docs.google.com/document/d/1r7g1u2YQitqbs3OE7FRxOhYzh5cv3mmPdFnuhqt4Qls/edit). @valianttry @lovegushwa

**Comment by HPaulJohnson** [comment]
@natalieworth it's likely we'll also need some sort of graphic for this email. just flagging it so you can add to the design queue for all things codemoji.

**Comment by shaghdoosti** [comment]
Hey friends --

I've looked over the draft and left a few comments -- a few things: 
1. Once we're all happy with the copy we need to take it through approval (Marshall, policy, Abby) -- happy to help with that but also happy for someone else ie: @HPaulJohnson or @KevZawacki to own it. 
2. This could be a great email to send under a new name (ie Brett or Andrea)

If possible -- would be great to prioritize this today so that we can make the send this week.

**Comment by natalieworth** [comment]
@stephaniemcv Do we know which template we'll be using for this and I can adjust one of the codemoji designs to fit if we do need an image for this email?

**Comment by KevZawacki** [comment]
Thanks for the review, @shaghdoosti. I'm happy to own approvals. What are the next steps? Share with remaining MoFo stakeholders and then ship to Policy + Legal at MoCo?

If you can let me know who we need a thumbs up from, I can move it forward.

**Comment by shaghdoosti** [comment]
Next steps are: Andrea to sign off, then approval by: Abby, Marshall and Chris R -- they just need an email with a deadline about when to do the review (usually they need a day's notice -- ie: 9am email for approval by COB is fine) would be good to CC either me or Andrea so we can give you back up in case there are any dramas.

**Comment by valianttry** [comment]
tiny comments -- looks great.

**Comment by KevZawacki** [comment]
Thanks, all! Just sent an approval request email.

**Comment by natalieworth** [comment]
@stephaniemcv @valianttry Here's the updated 'encryption power' header based on the email template:
There are 2 versions in here (one at 72dpi and one @2x or 144dpi) https://drive.google.com/open?id=0B20-0lpP23c0b3UzX253bHIydHM

**Comment by KevZawacki** [comment]
@stephaniemcv  [Email copy](https://docs.google.com/document/d/1r7g1u2YQitqbs3OE7FRxOhYzh5cv3mmPdFnuhqt4Qls/edit) approved and finalized. 

Launch has been pushed to 6/6 or 6/7 due to pesky jury duty.

@stephaniemcv If you need anything else from my end, let me know!

**Comment by KevZawacki** [comment]
Closing this ticket! Will open more Codemoji comms tickets as we approach the planned public launch in late June.
