### ISSUE TITLE
8/24 Email 1: Get policy team approval of EN text

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#260]
Detailed description of work: Get policy team approval of EN text

Due date: 8/23

CC: @shaghdoosti

**Comment by shaghdoosti** [comment]
@valianttry do you mind dropping the link to the email here?

**Comment by damiankay** [comment]
Hi @valianttry - can we close this one?

**Comment by valianttry** [comment]
Yes! Here is the final approved language:
https://docs.google.com/document/d/1wJ3spmPItKW5HjthHhWuPEO3hqAd5G9eNy45LhsL80s/edit
