### ISSUE TITLE
Nationbuilder > SFDC: Create language field

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#262]
Detailed description of work:
We need to create a field on either the Campaign object or the Contact object to capture language data. 

Due date: Aug 23

CC:

**Comment by damiankay** [comment]
Hi @valianttry & @drewmoto - I thought a ticket might be a good way to start this discussion. I'm assuming we'll need an answer early today for Fission.

**Comment by valianttry** [comment]
This discussion is happening in an email thread. We should just update this ticket with the notes and outcome once that conversation concludes.

**Comment by valianttry** [comment]
This is the path as @drewmoto recommended in the email thread:
![nationbuilder___salesforce_integration_-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/17912653/b4b32410-6949-11e6-90b1-be3bda0ee433.png)
