### ISSUE TITLE
Petition thank you email: QA 

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#263]
Detailed description of work: Please see screen shots below for the confirmation email sent via Nationbuilder and add comments where required. 

Due date: Aug 23

CC: @valianttry @natalieworth @beccaklam

**Comment by damiankay** [comment]
Sorry, the screen shots don't line up perfectly!

**Comment by beccaklam** [comment]
<img width="632" alt="screen shot 2016-08-23 at 4 27 25 pm" src="https://cloud.githubusercontent.com/assets/20977376/17908381/41404c92-694e-11e6-80d5-1c5734384be1.png">
^ Can we make it so that the text sits under the picture instead of being inline with it?

**Comment by damiankay** [comment]
Sorry @beccaklam - I don't have any image editing software to stitch these properly. that's just a screen shot issue!
