### ISSUE TITLE
Choose a URL for postcard site

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#264]
Detailed description of work:
So far the site has been described as (redacted by cade) Settle on a name

Due date: Aug 26

CC:

**Comment by damiankay** [comment]
Do you want to start an etherpad for name suggestions, or keep it to a tighter group meeting?

**Comment by cadecairos** [comment]
⚠️ Please don't mention potential domains on public channels ⚠️

**Comment by damiankay** [comment]
Shoot! Yes, of course. For Maker Party I started a Google doc with limited access.

**Comment by brettgaylor** [comment]
chosen!
