### ISSUE TITLE
Copyright campaign page loads a gif over http

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/Advocacy#265]
This causes a mixed content warning and should be fixed.

```
Loading mixed (insecure) display content “http://i.giphy.com/k7SZLGTPmEEN2.gif” on a secure page[Learn More]
```

**Comment by damiankay** [comment]
@gholme4 can you please look into this? 

@cadecairos any suggestions for a fix?

**Comment by damiankay** [comment]
CC @ScottDowne @jendc123

**Comment by cadecairos** [comment]
add an 's' to the giphy URL :)

**Comment by gholme4** [comment]
Hi. Christopher is correct. The URL has been changed to the secure version.

**Comment by damiankay** [comment]
Thanks @gholme4 !
