### ISSUE TITLE
Maker party: Create onboarding webinar and supporting materials

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#266]
Detailed description of work:
Scope, plan and deliver a webinar explaining how to add events to Nation Builder, plus other tips and tricks to get the most from the platform. 

Nation Builder offers some support guides on their site:
http://nationbuilder.com/getting_started

It may just be a case of pulling out what is most relevant for Maker Party hosts into a 30 minute run-through. This can be based on the user stories identified here: 
https://docs.google.com/spreadsheets/d/1cyZOpYl97mzWQDTQs-up6HE_-oPEr3wrSYai766bKlA/edit#gid=0
https://docs.google.com/spreadsheets/d/1hs5ULg3671t7c7DS7mmjrg4jPvmSC6RjU12p5palI8Q/edit#gid=0

Reference: https://docs.google.com/document/d/1SYRhODRvbA1IRtNfgH5i9JCAuumday9LnwdeP85s3eI/edit#

*Start date: \* August 25, 2016
*Due date: \* September 14, 2016

CC: @ldecoursy @shaghdoosti @Melechuga @lucyoh

**Comment by a-kilroy** [comment]
Lets talk through this. I have loads of tips from doing lots of onboarding
materials and could probably save us some time.

**Comment by damiankay** [comment]
I'd love that - thanks @a-kilroy!

**Comment by ldecoursy** [comment]
Hi - Checking back on this. Think it's feasible to plan a 10-15 minute webinar sometime between Sept 15 and 21? Defer to you on what you think will be most useful for people to run-through and get started.

**Comment by a-kilroy** [comment]
I'm back next week and think we should have a short kickoff to talk through
items and timing so we can put together a mini project plan for it.

**Comment by damiankay** [comment]
@a-kilroy sure that sounds great. I haven't not been able to touch this yet with our Copyright campaign requiring much more time and attention than expected. 

@ldecoursy I think that's reasonable. I would plan for Sep 21 - launch has been pushed to Sep 20th.

**Comment by damiankay** [comment]
@a-kilroy I started a skeleton for this document here: https://docs.google.com/a/mozilla.com/document/d/185kqVSpu21DB8RVzJ3METBa9cSjosUrtXLXITMN4XN0/edit?usp=sharing

Please have a look and rearrange as you see fit. 

The resources on the Nationbuilder site don't seem to align with what we have in mind (they focus on users with admin access), so I'll likely have to go through the motions myself and take notes along the way. 

One big question that I'm not sure how to resolve is the question of which hosts we're targeting with these webinars, and access will be different depending on the user's permissions.

**Comment by damiankay** [comment]
The script for the onboarding webinar can be found here: https://docs.google.com/document/d/1L75MdBQrUzJenD72CB1SBUXzn1T4zrFv4S9-8N05oTs/edit#heading=h.hv0xjutl7osi
