### ISSUE TITLE
Copyright Petition: QA Feedback (pre-launch)

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#267]
Detailed description of work:
Please add detailed QA feedback with screenshots and browser specified below. 
https://changecopyright.org/

CC: @lovegushwa @valianttry @brettgaylor @HPaulJohnson

**Comment by Melechuga** [comment]
![screen shot 2016-08-24 at 5 33 57 pm](https://cloud.githubusercontent.com/assets/5815317/17952654/72b5b1da-6a21-11e6-842d-bde8d62f109b.png)

The English bit is missing an "in" -- "as explained IN this..."

**Comment by Melechuga** [comment]
![screen shot 2016-08-24 at 5 39 11 pm](https://cloud.githubusercontent.com/assets/5815317/17952681/cba89154-6a21-11e6-8fd7-f58f39f006b4.png)

The countries aren't in alphabetical order in Spanish, so "España" shows up at the bottom. Is it possible to resort the countries once they're localized?

**Comment by valianttry** [comment]
@Melechuga +1 after translating the country lists, they should be resorted to alpha order.

**Comment by HPaulJohnson** [comment]
Hopefully not jumping the gun, but gotta catch a boat in a few minutes. 

The share buttons, or more specifically the share messages that are pre-populated when you click those buttons, is still not functioning properly. 
- Facebook looks better, but it's still pulling from the og tags in the meta data, not from messages embedded in the button code. 
- Twitter and email are both not working because there are no og tags for them nor are the messages embedded in the button code.
- Share messages - I believe because they are defaulting to site meta data - are not translated into languages.

Separately, for the og:title tag and og:site_name tag we should change from "Mozilla Foundation" to "Mozilla Advocacy: Reform Copyright"

**Comment by Melechuga** [comment]
![screen shot 2016-08-24 at 5 42 42 pm](https://cloud.githubusercontent.com/assets/5815317/17952735/36fe3490-6a22-11e6-9475-0b5b8b00884c.png)

Privacy notice needs a space: "se indica en esta declaración..."
Also, privacy notice link is localized to us-en; change link to https://www.mozilla.org/es-ES/privacy/websites/

**Comment by Melechuga** [comment]
(Spanish version) 
In the petition, error notices aren't localized.

**Comment by valianttry** [comment]
Privacy notice link next to the checkbox has an "en-US" locale assigned, it should match the URL in the footer so it is localized by IP:

![mozilla_foundation](https://cloud.githubusercontent.com/assets/9830371/17952801/a689bef6-6a22-11e6-8d18-e77b0f81e868.png)

**Comment by brettgaylor** [comment]
French version - two asterix in the privacy notice link
![image](https://cloud.githubusercontent.com/assets/345974/17952848/134b4b04-6a23-11e6-92ec-f792d80dcd16.png)

**Comment by brettgaylor** [comment]
French and German "why do we ask for this info" isn't localized
![image](https://cloud.githubusercontent.com/assets/345974/17952902/4b69baca-6a23-11e6-8fd4-6a22864cf18a.png)

**Comment by brettgaylor** [comment]
German needs a space in privacy policy link
![image](https://cloud.githubusercontent.com/assets/345974/17952923/6fc82488-6a23-11e6-8a0c-34cbbdf75803.png)

**Comment by brettgaylor** [comment]
Polish as well
![image](https://cloud.githubusercontent.com/assets/345974/17952943/999a705e-6a23-11e6-932d-6045e52c6e90.png)

**Comment by lovegushwa** [comment]
The first three fields are darker than "country" in firefox (also in chrome but less noticeable.) 
Match the look of "country."

<img width="293" alt="screen shot 2016-08-24 at 5 46 40 pm" src="https://cloud.githubusercontent.com/assets/12228435/17952921/6a51f0ba-6a23-11e6-90fb-70cadd8d6992.png">

**Comment by Melechuga** [comment]
![screen shot 2016-08-24 at 5 53 21 pm](https://cloud.githubusercontent.com/assets/5815317/17952948/afd4ea20-6a23-11e6-9d37-53aa04dbb19d.png)

On the Polish site, the last "Please share this " isn't translated.

**Comment by brettgaylor** [comment]
French countries are in all caps
![image](https://cloud.githubusercontent.com/assets/345974/17952978/fcc0f4fa-6a23-11e6-8fda-6542d1bc31c0.png)

**Comment by damiankay** [comment]
There should be an option for "other" at the bottom of the country drop down list (for signers outside of the EU)

![screen shot 2016-08-24 at 6 02 46 pm](https://cloud.githubusercontent.com/assets/19785709/17953075/09d300a6-6a25-11e6-97fa-3df4638b8e14.png)

**Comment by vojtechsedlak** [comment]
The GA tracking code needs to be updated with a new ID:  UA-49796218-44 
I've emailed George directly, but just putting it here for tracking purposes.

**Comment by jendc123** [comment]
@HPaulJohnson can you share the Twitter language you would like to use. Also, can you provide more detail on the Facebook issue. I'm not sure what you mean by embedded in the button.  

cc @gholmes4

**Comment by lovegushwa** [comment]
@jendc123 the share copy is here (end of the doc):
https://docs.google.com/document/d/1itsvIJ3KLvBXhKYDa0EAyyeAa0vA6_jCM_6yDIPaviY/edit

**Comment by valianttry** [comment]
If I refresh the URL, it drops me back to the Thank You state -- with the popup. 

![mozilla_foundation](https://cloud.githubusercontent.com/assets/9830371/17954137/a7bb69c2-6a2d-11e6-8ead-0150f09c65d0.png)

**Comment by HPaulJohnson** [comment]
@jendc123 copy is in the doc @lovegushwa provided above. 

By embed code, I meant controlling the share messaging within the href of the button itself. I think we can address the FB share message by updating the og:title tag. But for Twitter and Email, I think we will need to embed copy in buttons as follows: 

For email: 
`<a` href="mailto:?Subject=LOCALIZEDSUBJECTCOPY&Body=LOCALIZEDBODYCOPYhttps://URL”>

For twitter embed: 
`<a` class="twitter-share-button" href="https://twitter.com/intent/tweet?text=LOCALIZEDCOPY">

It's also probably best to add the following twitter tags to the meta data as well: 

`<meta` name="twitter:card" content="summary_large_image"/>
`<meta` name="twitter:site" content="@mozilla"/>
`<meta` name="twitter:title" content=“Mozilla Advocacy: Reform Copyright“/>
`<meta` name="twitter:description" conten=“LOCALIZEDCOPY”/>
`<meta` name="twitter:image" content=IMAGEURL”/>

**Comment by valianttry** [comment]
@jendc123 noticed the email error message is not the same design as the others, and it says "Email and phone is required". Should say "Email is required"

![banners_and_alerts_and_mozilla_foundation](https://cloud.githubusercontent.com/assets/9830371/17955010/cf2bce9c-6a33-11e6-9438-14a328eea8b5.png)

**Comment by valianttry** [comment]
There is no error shown if I submit without entering anything into the first name field. That should be required.

ADDITION: I also don't get an error if i don't enter last name.

**Comment by HPaulJohnson** [comment]
can we also change the title tag for the site to "Mozilla Advocacy: Reform Copyright"

(og:site_name should also be "Mozilla Advocacy: Reform Copyright" / currently it's "Mozilla Foundation: Reform Copyright")

**Comment by valianttry** [comment]
NOTE: @jendc123 confirmed most / all of the above bugs have been fixed.
