### ISSUE TITLE
Copyright Petition: QA Feedback (post-launch)

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#270]
Detailed description of work:
Please add detailed QA feedback with screenshots and browser specified below.
https://mozillafoundation.nationbuilder.com/

**Comment by natalieworth** [comment]
@damiankay Not sure if this is intentional but the language tab is display strangely at the top:
<img width="673" alt="screen shot 2016-08-25 at 9 13 13 am" src="https://cloud.githubusercontent.com/assets/14876567/17976902/4aa7e428-6aa4-11e6-9490-78e3045f7f3d.png">

Is it possible to just switch the rounded corners to the bottom so it looks like the tab is attached to the top of the page?

**Comment by Melechuga** [comment]
![screen shot 2016-08-25 at 9 14 07 am](https://cloud.githubusercontent.com/assets/5815317/17976915/5bf677da-6aa4-11e6-983f-f9883a5014e4.png)

In all the localized languages the text here is in English except for the link to the privacy statement.

**Comment by Melechuga** [comment]
Also, all the localized privacy statements still link to English; can we localize that link?

**Comment by Melechuga** [comment]
On the Polish site, the description of Mozilla in the footer is in English: 
![screen shot 2016-08-25 at 9 16 59 am](https://cloud.githubusercontent.com/assets/5815317/17976989/ba2e6a2e-6aa4-11e6-8c87-b36b418d06eb.png)

**Comment by ScottDowne** [comment]
Yeah, we should switch the privacy link to https://www.mozilla.org/privacy/websites/

It'll fix the locale to be whatever the browser is set to.

**Comment by Melechuga** [comment]
Not sure if this is intentional, but the share buttons link to tweets/fb/emails written in English. Is that content also localized?

![screen shot 2016-08-25 at 9 18 23 am](https://cloud.githubusercontent.com/assets/5815317/17977055/f8d1b9e8-6aa4-11e6-9788-4b5cc5aeaec4.png)

**Comment by Melechuga** [comment]
Can't remember if I mentioned this yesterday, but error messages on localized sites are in English:

![screen shot 2016-08-25 at 9 21 20 am](https://cloud.githubusercontent.com/assets/5815317/17977141/5e5ed656-6aa5-11e6-886c-2d04fb7b6e44.png)

**Comment by Melechuga** [comment]
Possible to re-alphabetize country list on localized pages?

**Comment by HPaulJohnson** [comment]
Polish translations for social share CTA and social share messages now available in this doc: 
https://docs.google.com/document/d/1itsvIJ3KLvBXhKYDa0EAyyeAa0vA6_jCM_6yDIPaviY/edit

Also, all of the share messages are still all in English and should be in locale-specific language.

**Comment by damiankay** [comment]
Closing in favour of individual tickets
