### ISSUE TITLE
"Thank you" string in share modal not localized

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#271]
@valianttry 

The "Thank you" string in share modal is not localized. I think it's all languages, but ran out of browsers to test (even in private mode, the petition still knows you signed and wont let you sign again.)

![screen shot 2016-08-26 at 3 16 13 pm](https://cloud.githubusercontent.com/assets/12228435/18022115/16727134-6ba1-11e6-8d6e-3d03bb6efbc5.png)
<img width="1081" alt="screen shot 2016-08-26 at 3 14 49 pm" src="https://cloud.githubusercontent.com/assets/12228435/18022116/1898bd7e-6ba1-11e6-84c9-77c118937334.png">

**Comment by valianttry** [comment]
Fixed in all locales 

![fundacion_mozilla](https://cloud.githubusercontent.com/assets/9830371/18022530/709cabb8-6ba4-11e6-8085-aeff0ce116d3.png)
