### ISSUE TITLE
Icons in share modal are tiny

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#272]
Icons in share modal are tiny. Not the end of the world but would be nice to fix:

![screenshot_20160826-150941](https://cloud.githubusercontent.com/assets/12228435/18022306/8c8e0134-6ba2-11e6-8c80-ec4061956df3.png)

**Comment by damiankay** [comment]
CC: @damiankay @valianttry @jendc123

**Comment by jendc123** [comment]
@damiankay @valianttry @lovegushwa - this has been updated. However, @lovegushwa let me know if you would like a specific size.

**Comment by lovegushwa** [comment]
@jendc123 the desktop view is a good reference for the proportion of the icon to the square (they look good here) ... but as long as the icons are not tiny in the squares I'm happy !
