### ISSUE TITLE
Can't submit form when selecting "other" in country drop down

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#273]
Mac/Desktop/Firefox 48

I'm getting an error message to select a country after I've selected "other" from the list. It won't submit form as result. 

![mozilla_foundation](https://cloud.githubusercontent.com/assets/10078715/18022593/0421a5d2-6ba5-11e6-8ca8-ca12dcf6ef79.jpg)

**Comment by brettgaylor** [comment]
Confirmed on Chrome 52

**Comment by damiankay** [comment]
CC: @damiankay @valianttry @jendc123

**Comment by damiankay** [comment]
Also confirmed on Firefox for Windows, and for French "autres"

**Comment by valianttry** [comment]
I believe #282 is a duplicate ticket.

**Comment by jendc123** [comment]
Hi @damiankay @valianttry @HPaulJohnson @brettgaylor ,

This has been resolved.
