### ISSUE TITLE
Share by Email post-petition signature isn't working

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#274]
Mac/Desktop/Chrome 52 

After submitting petition signature, on the share modal/pop-up, the email share link doesn't function (nothing happens). 

NOTE: Same use case on Firefox works fine.

**Comment by HPaulJohnson** [comment]
Also worth nothing that the share by email functionality works fine on chrome in the "Share This" footer bottom at the bottom of the page. It's just the pop-up that's broken

**Comment by damiankay** [comment]
CC: @damiankay @valianttry @jendc123

**Comment by jendc123** [comment]
Hi @valianttry @damiankay  @HPaulJohnson ,

This has been resolved.
