### ISSUE TITLE
"Thank you for signing" message isn't localized

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#275]
Mac/Desktop and Mobile/Firefox/Chrome

After submitting petition signature, the persistent "Thank you for signing!" message is in English.

![fullscreen_8_26_16__4_14_pm](https://cloud.githubusercontent.com/assets/10078715/18022948/876f7e20-6ba8-11e6-8fd4-dae4666b5d42.jpg)

**Comment by damiankay** [comment]
CC: @damiankay @valianttry @jendc123

**Comment by valianttry** [comment]
Support at Bablic has indicated this issue was resolved. This does need to go through one additional round of QA to make certain. @Melechuga can you help out?

**Comment by Melechuga** [comment]
@valianttry "thanks you" on the pop-up message immediately after you sign is localized, but the persistent msg that @HPaulJohnson screen-shot is still in English.

**Comment by valianttry** [comment]
ah i see -- I think Fission has to help with that.

**Comment by jendc123** [comment]
Hi @HPaulJohnson @Melechuga @valianttry ,

The "Thanks for signing" field is ready to translate in Bablic.  

<img width="701" alt="thanks for signing up" src="https://cloud.githubusercontent.com/assets/6034476/18067224/d102b17a-6e09-11e6-8106-0732a7a13bf5.PNG">

**Comment by valianttry** [comment]
Updated this phrase in all Tier 1 languages + Czech, Italian, and Bulgarian in Bablic.
