### ISSUE TITLE
Problem submitting form on Chrome on iPhone

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#276]
This is a weird one but finally able to recreate on iOS / Chrome. 

Mobile chrome suggests content for standard form fields. For example, when I click into the last name box, it suggest "Johnson" and if I click on that it auto-populates that field. Everytime I used this feature to complete the form, it got stuck with a rotating "saving" message upon submit and never completed. It just got hung. 

If I submit the form on chrome by typing out every form field from scratch, it seems to work fine and the form submits as expected. 

This one is a head scratcher but I have been able to recreate consistently.

**Comment by damiankay** [comment]
CC: @damiankay @valianttry @jendc123

**Comment by gholme4** [comment]
@HPaulJohnson did you confirm this behavior is not present in iOS Safari?

**Comment by damiankay** [comment]
Not confirmed @gholme4 - we don't have autofill set up.

**Comment by HPaulJohnson** [comment]
I do not have auto-fill options on my iOS Safari so I cannot confirm.

**Comment by jendc123** [comment]
@HPaulJohnson and @damiankay we are not sure how to tackle and test this one - it may not get closed today.

**Comment by damiankay** [comment]
Hi @jendc123 - we thought that might be the case. I think it's ok to de-prioritize this one. Let's leave it open for now, however, in case we're able to find a solution.

**Comment by HPaulJohnson** [comment]
closing this for now in the new year's purge. doesn't look to be an issue with the v2 of the petition form anyway.
