### ISSUE TITLE
On mobile, share buttons open up in browser window not in native apps.

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#277]
iOS/Chrome and Firefox. Might not be a bug but definitely will detract from sharing on mobile. 

When clicking Facebook or Twitter share options on mobile it opens those applications within the browser, instead of launching the app. Because I (and most people) only use the app for social, it asks me to login and I just abandon. I'd assume most users would do the same. 

Desired behavior is for the share messages to launch the app, not in a browser window.

**Comment by damiankay** [comment]
@ScottDowne - is there a way to open in the app instead of in the browser on mobile? 

CC: @damiankay @valianttry @jendc123

**Comment by ScottDowne** [comment]
I did a bit if research on this this morning and have yet to find any info
on someone doing this successfully. It seems to be fairly requested feature
though. My guess is it's not possible or the Twitter login page would
already have this functionally.

**Comment by damiankay** [comment]
Yeah that's what I thought. I've been annoyed by this in the past on many sites... I figured I couldn't be the only one. I'll leave this open for a bit in case anyone from Fission has an insight.

**Comment by ScottDowne** [comment]
I'm having some luck with `twitter://mentions` in the url under my browser. Not sure exactly yet how far this can get us.

**Comment by jendc123** [comment]
@ScottDowne @damiankay - I believe this has been resolved with the localization of share.

**Comment by ScottDowne** [comment]
That would be a nice bonus.

I just tried on an android with firefox, and it didn't work. I suspect maybe it's an ios only thing?

**Comment by damiankay** [comment]
@jendc123 when clicking the social share buttons in the footer, the links still open the web pages, not the app. Tested in iOS Chrome / iPhone 5s.

**Comment by jendc123** [comment]
@damiankay - this is not something we can control because that behavior is for apps and not browsers.

**Comment by damiankay** [comment]
Thanks @jendc123. We wondered if that might be the case. I'll close this one.
