### ISSUE TITLE
Replace with high resolution versions of movie files

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#278]
Detailed description of work:
All of the movie files are at an offline resolution.  I have downloaded these files and shared them with you via google drive.

You'll need to replace all of the files on the timeline with these clips, and make the sequence match the resolution of the new clips (852 X 480)

**Comment by natalieworth** [comment]
This is complete, but high res file for 4060174.mp4 is missing:
<img width="609" alt="screen shot 2016-09-01 at 1 04 42 pm" src="https://cloud.githubusercontent.com/assets/14876567/18182410/c63da7c6-7044-11e6-8566-5b2e915255a5.png">

**Comment by natalieworth** [comment]
I also updated the green screen (desktop and tablet) to high res/ tweaked the lighting and green screen issues:
<img width="582" alt="screen shot 2016-09-01 at 1 06 06 pm" src="https://cloud.githubusercontent.com/assets/14876567/18182466/f46e0938-7044-11e6-850a-413ec2018d71.png">
<img width="584" alt="screen shot 2016-09-01 at 1 06 13 pm" src="https://cloud.githubusercontent.com/assets/14876567/18182465/f465fe00-7044-11e6-9c54-1aa81746c001.png">

**Comment by natalieworth** [comment]
All final exported files for CSI:GIF are here: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0dEJSM3A5U0VNUjg
