### ISSUE TITLE
Create transitions and CGI effects

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#279]
-Replace the split screens/zooms with something better/jazzier.
-Saturate the hell out of everything
-Do a non shitty version of the green screening
-make everything amazing.

**Comment by natalieworth** [comment]
All final exported files for CSI:GIF are here: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0dEJSM3A5U0VNUjg
