### ISSUE TITLE
Add CTA text at end

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#281]
Use the CTA from the script to add a text CTA at the end of the video

This might be a good opportunity to create an ident/bumper we would use for all of the videos, too.

We could use #fixcopyright if it tests well in the intial paid media run.  cc @HPaulJohnson and @lovegushwa

**Comment by lovegushwa** [comment]
@natalieworth @HPaulJohnson this is a good place place to loop in the end title work k-fann asked for.

**Comment by natalieworth** [comment]
All final exported files for CSI:GIF are here: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0dEJSM3A5U0VNUjg
