### ISSUE TITLE
Bablic bounding box has defaulted back to version with rounded corners

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Advocacy#283]
Browsers: Firefox, Safari, and Chrome.
Description: Bablic needs to have rounded corner styling removed or flipped so the tab appears to be from the top.

CC: @damiankay @valianttry @jendc123

<img width="243" alt="screen shot 2016-08-27 at 10 23 06 pm" src="https://cloud.githubusercontent.com/assets/14876567/18031810/faf1b820-6ca4-11e6-9dd3-1d8ea91a4611.png">

**Comment by jendc123** [comment]
@natalieworth @damiankay - this has been updated.

**Comment by damiankay** [comment]
Fix confirmed
