### ISSUE TITLE
Spanish/Polish translation of 'make, create, innovate' does not stack

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Advocacy#285]
Browser: Firefox, Chrome, and Safari (desktop and mobile)
Description: 3 descriptive words of Spanish translation are not stacking like in all other translations:
<img width="523" alt="screen shot 2016-08-27 at 10 35 41 pm" src="https://cloud.githubusercontent.com/assets/14876567/18031839/4a0576a8-6ca6-11e6-99b1-97b8711263ba.png">

CC: @damiankay @valianttry @jendc123

**Comment by Melechuga** [comment]
Same issue as https://github.com/MozillaFoundation/Advocacy/issues/302 for Opera; closing that ticket now.

**Comment by Melechuga** [comment]
Same for Polish on FF for iOS btw:

![img_9348](https://cloud.githubusercontent.com/assets/5815317/18065809/5fd8ca58-6dea-11e6-9c2f-74018d0f7e7e.PNG)

**Comment by damiankay** [comment]
Resolved in V2
