### ISSUE TITLE
Email input error copy displays twice

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Advocacy#286]
Browser: Firefox, Chrome, and Safari
Description: There are 2 similar error messages if an incorrect email address is submitted on the form:
<img width="317" alt="screen shot 2016-08-27 at 10 40 28 pm" src="https://cloud.githubusercontent.com/assets/14876567/18031849/ed2e8fe0-6ca6-11e6-89f4-193ac95f1514.png">

CC: @damiankay @valianttry @jendc123

**Comment by jendc123** [comment]
@natalieworth @damiankay - This has been resolved.

**Comment by damiankay** [comment]
Confirmed
