### ISSUE TITLE
Translation text goes out of screen viewing area on 'share' page for mobile

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Advocacy#287]
Browser: Firefox, Chrome, and Safari
Description: Text goes outside of readable area on the 'share'/ thank-you page:
![img_4302](https://cloud.githubusercontent.com/assets/14876567/18031862/ad0e1ff6-6ca7-11e6-89b2-c57924ea908e.PNG)
CC: @damiankay @valianttry @jendc123

**Comment by jendc123** [comment]
@natalieworth @damiankay - this issue has been resolved

**Comment by damiankay** [comment]
Confirmed
