### ISSUE TITLE
Titles covered by form

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#288]
Detailed description of work:
iPad mini / Chrome
The header and footer title text is covered by the form in portrait mode. 

CC: @damiankay @valianttry @jendc123

![img_0010](https://cloud.githubusercontent.com/assets/19785709/18042011/d48d3140-6d72-11e6-874a-35ac25015d93.jpg)
![img_0011](https://cloud.githubusercontent.com/assets/19785709/18042010/d44541a0-6d72-11e6-907d-d2226ea1ff55.jpg)

**Comment by jendc123** [comment]
Hi @damiankay - this has been resolved.
