### ISSUE TITLE
Traffic with JS disabled sees nothing on the action page

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#291]
Detailed description of work: 
Users who have JavaScript disabled don't see anything on the action page. There is no straightforward way for us to track how prevalent this issue. The suggestion is to include a <noscript> message on the site, indicating that to display the content, JS needs to be enabled.

CC:
@damiankay @valianttry

**Comment by ScottDowne** [comment]
Bablic relies on JavaScript to do all the translations. This isn't something we can support with our current setup.

**Comment by vojtechsedlak** [comment]
Yeah makes sense. Let's just add a `<noscript>` with some kind of message so that people without JS don't just see a blank page.

**Comment by ScottDowne** [comment]
Sorry, didn't initially read the comment, just the title :(

Yeah, `<noscript>` is a reasonable solution.

**Comment by valianttry** [comment]
Seems like an easy solution, made this a P1

**Comment by damiankay** [comment]
CC @a-kilroy who logged the issue

**Comment by ScottDowne** [comment]
@damiankay I suspect this is something I think we should ask Fission for, if possible.

**Comment by gholme4** [comment]
@vojtechmozilla I did what you suggested and added a notice in a <noscript>tag.

**Comment by vojtechsedlak** [comment]
Great, thanks @gholme4!
