### ISSUE TITLE
redirect from advocacy.mozilla.org/copyright/ cannot change language

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#292]
Detailed description of work: If someone goes directly to http://advocacy.mozilla.org/copyright/ language dropdown doesn't function.

CC: @damiankay @gideonthomas @valianttry 

This is likely an issue with the redirect, more so than the form.

The redirect is dropping us here: https://mozillafoundation.nationbuilder.com// which has those two trailing slashes? Which is messing with the language changer query string.

http://changecopyright.org/ does not have this issue.

So, unless we have a lot of people using the initial advocacy.mozilla.org redirect, this is probably low priority.

**Comment by cadecairos** [comment]
This can be fixed pretty easily by changing the S3 bucket redirect policy that's handing the redirect.

**Comment by ScottDowne** [comment]
This is fixed now. Thanks @gideonthomas and @cadecairos
