### ISSUE TITLE
Check box for Privacy Statement in English on localized sites

### ISSUE THREAD

**Issue by Melechuga** [MozillaFoundation/Advocacy#294]
![screen shot 2016-08-29 at 10 48 05 am](https://cloud.githubusercontent.com/assets/5815317/18061359/50f27920-6dd7-11e6-8576-a224e064e577.png)

Currently, I see that this is an issue on French and Spanish sites.

**Comment by valianttry** [comment]
I just QAd French and it is correctly localized:

![fondation_mozilla](https://cloud.githubusercontent.com/assets/9830371/18062389/87f7674c-6ddb-11e6-8d16-10df29504703.png)

**Comment by valianttry** [comment]
I corrected the translation for Spanish. That should update in Bablic shortly.

**Comment by valianttry** [comment]
Spanish has now updated:

![fundacion_mozilla](https://cloud.githubusercontent.com/assets/9830371/18062490/ea87bdd0-6ddb-11e6-9821-b5b539da617f.png)
