### ISSUE TITLE
Change site title in metadata

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#297]
Currently, the site title is showing up as "Mozilla Foundation." We don't use "Foundation" in our public facing branding/campaigns so this should be "Mozilla Advocacy: Reform Copyright"

**Comment by damiankay** [comment]
CC @valianttry @jendc123

**Comment by damiankay** [comment]
@gholme4 this still needs to be fixed from V1

**Comment by jendc123** [comment]
@damiankay this has been updated #readyforreview.

**Comment by HPaulJohnson** [comment]
verified. fixed. closing.
