### ISSUE TITLE
Errors on localized sites in English

### ISSUE THREAD

**Issue by Melechuga** [MozillaFoundation/Advocacy#299]
![screen shot 2016-08-29 at 10 51 40 am](https://cloud.githubusercontent.com/assets/5815317/18062099/37ea353c-6dda-11e6-9b53-b3eb0c97d367.png)

Error messages for individual fields still showing up in English on localized sites.

**Comment by Melechuga** [comment]
This is for Spanish, French, German, and Polish.

**Comment by jendc123** [comment]
@Melechuga The error messages are set via the browser so in the US we see English.  Here's a screenshot from our colleague in Argentina and he gets the errors in Spanish. This will be replicated for all languages. 
<img width="512" alt="spanish" src="https://cloud.githubusercontent.com/assets/6034476/18065378/a5b00458-6e01-11e6-83be-3020a41665f5.PNG">

cc @valianttry, @damiankay

**Comment by Melechuga** [comment]
@jendc123 Awesome; thanks for following up!
