### ISSUE TITLE
Acquire voice talent for localized languages

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#3]

**Comment by brettgaylor** [comment]
Thinking of using this guy:

https://www.voices.com/people/jordi

Can't seem to find a spanish sam gregory sound on voices.com.  Will keep looking.

**Comment by brettgaylor** [comment]
https://voicebunny.com/search/samples/DC3EP4/6819/
https://voicebunny.com/search/samples/17ADDC8/1239/
https://voicebunny.com/search/samples/17ADDC8/68265/

**Comment by valianttry** [comment]
For reasons I can't articulate well, i like this one: https://voicebunny.com/search/samples/17ADDC8/1239/#
He's closest to "silly grandpa" which is how I think about the guy that did the EN version.

Also, my opinion should not matter much. ??

[--- Commented from Asana.com
#commenter Damian Kuehn
---[aa]

**Comment by brettgaylor** [comment]
Andrea (fellow) shot my choices  down as being too old and boring :sob:

 She likes this one:
https://voicebunny.com/search/samples/3CH0UPK/66702/

**Comment by ScottDowne** [comment]
@brettgaylor Is this an ongoing thing, or can we close?

**Comment by brettgaylor** [comment]
closed!
