### ISSUE TITLE
Codemoji user journys for test

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#30]

**Comment by HPaulJohnson** [comment]
next step: build out a few prototype journeys from promotion to codemoji to landing page. See slide 4 from this overview deck: 

https://docs.google.com/presentation/d/1hEwLZNS_b-XnRGmtqyTGzB9zzZN-VX8neFO85mmRHMo/edit#slide=id.gd58133b56_0_69

**Comment by lovegushwa** [comment]
@HPaulJohnson will dig into 2 journeys: snippet and social.

**Comment by lovegushwa** [comment]
I'll done!
