### ISSUE TITLE
Cached sites go to "thanks for signing" site

### ISSUE THREAD

**Issue by Melechuga** [MozillaFoundation/Advocacy#301]
![screen shot 2016-08-29 at 11 28 20 am](https://cloud.githubusercontent.com/assets/5815317/18062448/c41a71ba-6ddb-11e6-9cae-b064ef490abe.png)

I'm not sure if this is something we can control, but when I got back to the site after I've signed, I get the "Thanks for signing" site that's cached (I assume). Is there a way to go back to a "fresh" petition site? Even if I change languages, it goes to the "thanks for signing" site.

PS this is in Chrome, if that matters.

**Comment by ScottDowne** [comment]
This is NationBuilder, and is intended. Can we leave this?

If for debugging purposes, you want to see a fresh page, just clear cache or load a private tab.
