### ISSUE TITLE
Country list in French is a hodge-podge of ALL CAPS and Normal

### ISSUE THREAD

**Issue by Melechuga** [MozillaFoundation/Advocacy#303]
![screen shot 2016-08-29 at 11 45 40 am](https://cloud.githubusercontent.com/assets/5815317/18063152/bc92bc24-6dde-11e6-867a-264b4f32d410.png)

**Comment by jendc123** [comment]
@Melechuga and @valianttry , This can be edited in Bablic under the text editor.  The list in Bablic is the same one showing on the front-end.

**Comment by damiankay** [comment]
Resolved in V2
