### ISSUE TITLE
In French, the Thank You Notice is repeated

### ISSUE THREAD

**Issue by Melechuga** [MozillaFoundation/Advocacy#304]
![screen shot 2016-08-29 at 11 53 01 am](https://cloud.githubusercontent.com/assets/5815317/18063375/8c3c13e4-6ddf-11e6-82c6-a5c67126db0c.png)

Not sure if this is intentional, but in English is says "Thank you! Please share this." but in French is says "Thank you! Thank you for sharing."

**Comment by jendc123** [comment]
@Melechuga @Melechuga - This can be updated in the Bablic text editor.

**Comment by damiankay** [comment]
Do you mind updating @valianttry ?

**Comment by damiankay** [comment]
This was resolved
