### ISSUE TITLE
[Mobile] Page under "thank you" comes and goes

### ISSUE THREAD

**Issue by Melechuga** [MozillaFoundation/Advocacy#307]
Weird one for Firefox for iOS:

![img_9347](https://cloud.githubusercontent.com/assets/5815317/18065667/bc264714-6de9-11e6-8bcf-2eb7ab18438e.PNG)

After signing, the page shows through the bottom when you're scrolling for a hot second, then disappears.

**Comment by damiankay** [comment]
Closing as the design as been updated
