### ISSUE TITLE
Localized copy for twitter share exceeds character limits. 

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#308]
Now that localized versions of share are working for Twitter we are seeing that they exceed Twitter's character length. Fixed with copy below: 

German:
Parodie und Remix im Internet sollten nicht rechtswidrig sein. Befreien wir unsere Fantasie in der EU. mzl.la/copyright

Spanish:
La parodia y la remezcla no pueden ser ilegales en Internet. Es el momento de liberar nuestra imaginación en la UE. mzl.la/copyright

French:
Les parodies et les remixes ne devraient pas être illégaux en ligne. Libérons notre imagination dans l’UE. mzl.la/copyright

Polish:
Parodia i remiks w sieci nie powinny być nielegalne. Uwolnijmy wyobraźnię w całej Unii – podpisz petycję: mzl.la/copyright

**Comment by damiankay** [comment]
@HPaulJohnson  can you update the Share Message Google doc? Thx! @valianttry

**Comment by HPaulJohnson** [comment]
Updated here: https://docs.google.com/document/d/1itsvIJ3KLvBXhKYDa0EAyyeAa0vA6_jCM_6yDIPaviY/edit

**Comment by HPaulJohnson** [comment]
fixed. closing
