### ISSUE TITLE
Test Idea: Alternative GIF for the v1 petition page

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#309]
Detailed description of work: The gif has a fairly prominent role on the page, so let's see if it has an impact on how people engage with the petition.

CC: @lovegushwa @HPaulJohnson Let's gather some ideas in this ticket!

**Comment by natalieworth** [comment]
@HPaulJohnson Do you have any suggestions about possible themes I could look for that would relate to the content on the first petition?

**Comment by HPaulJohnson** [comment]
I think something with the Eiffel Tower at night might be worth trying. 

Also, something with bold copy, like the idea of stamping "illegal in some parts of Europe" or "#copyfail" on top of a landmark or other well known meme. 

Might be worth trying something from your social media assets as well, like the brain graphic. 

Lastly, I wonder if there's something more earnest, with an education theme might work well given the placement next to the "classroom" copy. Maybe a classroom photo w/ teachers and students? Teachers and students looking at some media - like YouTube or other video content.

**Comment by natalieworth** [comment]
@HPaulJohnson Are there any restrictions on the gif size? (Not sure if we're using optimizely and if this affects the sizes I should crop the gif to?)

**Comment by natalieworth** [comment]
Eiffel Tower Giphy options:
V1
![1](https://cloud.githubusercontent.com/assets/14876567/18101275/e35f3ca0-6ea2-11e6-87a2-d46739acf9c8.gif)
V2
![2](https://cloud.githubusercontent.com/assets/14876567/18101278/e51b2f7c-6ea2-11e6-96bc-84abf6d4fd7c.gif)
V3
![3](https://cloud.githubusercontent.com/assets/14876567/18101280/e7009a0c-6ea2-11e6-9a0c-e41a8a6d42ab.gif)
V4
![4](https://cloud.githubusercontent.com/assets/14876567/18101286/e9d7d984-6ea2-11e6-9c79-506799848f3e.gif)
Link sources:
http://giphy.com/gifs/amazing-beautiful-Ft6yweEdwXmJW
http://giphy.com/gifs/tower-eiffel-princeofparis-c0dw5TujYWAAE
http://giphy.com/gifs/night-fireworks-vXEeRBP3QeJ2w
http://giphy.com/gifs/night-paris-Ds8hTFJJmhoDS

Teaching/ Alternate options:
V5
![5](https://cloud.githubusercontent.com/assets/14876567/18101593/2e8cc4f8-6ea4-11e6-9681-4f6dd157c686.gif)
V6
![6](https://cloud.githubusercontent.com/assets/14876567/18101854/2e519e7c-6ea5-11e6-9ae7-720a4f66b6fc.gif)

Link sources:
http://giphy.com/gifs/bored-nickelodeon-spongebob-squarepants-HlqvH9JrahLZ6
http://giphy.com/gifs/eiffel-BYFoyObZtwgZa

*Going to create a quick #copyfail option too and will post this afternoon.

**Comment by HPaulJohnson** [comment]
Whoa- these look awesome. 

RE: size question, I don't think there's a size limit but @vojtechmozilla can answer better as he is managing the Optimizely setup for LP testing. 

Also, we should test a non-gif image, given our existing "control" is already a .gif. We can/should be able to test more than 1 thing so another .gif (like the ideas above) vs. non-.gif would be great.

**Comment by HPaulJohnson** [comment]
BTW, I love the last one that goes from check mark to nope. Makes the absurdity really clear. "Nope" would need to be localized so wonder if we could achieve the same effect with "X"

**Comment by vojtechsedlak** [comment]
There are amazing! It would be great if we could categorize the options, so as to formulate a hypothesis. For instance, the current gif is animate, humorous, abstract, thematically-unrelated. We could try that against say the eiffel tower with checkmark, which is not animated, straight to the msg of the campaign. The still image option could be some combo of both.

As for the size, ideally we would want to stick as close to the original format as possible (500x377), just so we don't mess up the layout too much.

**Comment by natalieworth** [comment]
@HPaulJohnson @vojtechmozilla Great, thanks! This is helpful. I'll refine 2 options and post this afternoon.

**Comment by natalieworth** [comment]
@HPaulJohnson I made these options:
V1- Eiffel Tower
![9](https://cloud.githubusercontent.com/assets/14876567/18106113/0aede758-6eb7-11e6-868f-2a069d39dc0d.gif)
Testing description: static, sarcastic, informative, iconographic, before/after, immediate, strong visual messaging related to the content (possibly applicable to more audiences through iconic imagery and easily understood icons), also doesn't rely on social media/ hashtag/ trends understanding

V2- #copyfail
![10](https://cloud.githubusercontent.com/assets/14876567/18106161/4cd17b62-6eb7-11e6-9e29-a6f94ab8bc4f.gif)

V3 (alternate of V2)- #copyfail
![11](https://cloud.githubusercontent.com/assets/14876567/18106165/513801f8-6eb7-11e6-961e-da87aafe8186.gif)
Testing description: campaign relative, promotional, sarcastic, social media relative, (hashtag or social promotion could also be applicable to a certain audience and generation), animated, disruptive, typographic, bold colours with black and white

My Youtube links (for reference):
https://youtu.be/YJCBPLTObLA
https://youtu.be/t-Z5B0cNAlA
https://youtu.be/RWVvVrYT6Ao

My giphy links:
http://giphy.com/gifs/mwPqJcaQ2UduE
http://giphy.com/gifs/copyright-copyfail-eJXP82K6anb8Y
http://giphy.com/gifs/InHzFeq5iOu8E

cc @brettgaylor When you're back, if you could provide copyright help on the remade image from giphy (they don't have authors for each gif listed). Wondering if it is okay to repurpose existing content and make gifs based off of Youtube videos and remix already existing gifs to have the text #copyfail overtop of them (which is what I did to make the 3 posted above). Here are the original content links that I used to create the above 2 remixes:
https://www.youtube.com/watch?v=cB9ZOaPKPCw
http://giphy.com/gifs/qMt3OMaml00Ja

**Comment by natalieworth** [comment]
We could test some of the above to @vojtechmozilla 's point of having more descriptive imagery. We can test against the original which felt more positive, niche(?), nostalgic, fun, cute, learning, animated, ambiguous (maybe on relative to certain generations)

**Comment by natalieworth** [comment]
cc @lovegushwa @beccaklam

**Comment by lovegushwa** [comment]
@natalieworth great work here!

**Comment by brettgaylor** [comment]
Sorry to check in from vacay, but just need to say: these are great!!!!

**Comment by vojtechsedlak** [comment]
Thanks @natalieworth, these are perfect! I've created a test in Optimizely with all of the variants above and will run it once there is traffic heading to the page. Will keep you all posted on the results.

**Comment by natalieworth** [comment]
Pokemon won! Closing, but feel free to reopen if any needs to be added/ changed.
