### ISSUE TITLE
Share graphic for encryption landing page social (Share progress)

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Advocacy#31]
Create a graphic for the share image on social media (twitter and facebook).

**Comment by natalieworth** [comment]
Facebook and Twitter share progress assets here: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0bVlrZkcwODVNc1k&usp=drive_web&ddrp=1#

**Comment by HPaulJohnson** [comment]
This is live
