### ISSUE TITLE
Maker Party: editing events / bulk uploads / RSVPs

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#310]
Detailed description of work:
1. Fission needs a response on the question below immediately: 
Editing events: Nationbuilder does not by default have a user with the access that we would like for our hosts; specifically, there is no way to add the ability to edit events without proper access to the control panel, which is currently only granted to admins.

Fission is looking into workarounds/hacks, but they feel that adding this functionality may cause significant delays.

Other campaigns mitigate this issue by having event hosts simply update event information over email when necessary.

There are two smaller (I think) issues with regards to our desired functionality:
2. It is not possible to do bulk uploads of contacts. This is simply not possible within Nationbuilder
3. A request came from our team to display number of RSVPs at a variety of thresholds. Within Nationbuilder only one such threshold is supported as a goal (ex: if RSVP hits 25, then…)

Can you please let me know whether you think any of these features are critical to launch? If so, we may need to look at extending our timeline. 

*Due date: \* August 29, 2016

CC: @geroter @simonwex @a-kilroy @lovegushwa

**Comment by damiankay** [comment]
CC @shaghdoosti @valianttry

**Comment by lovegushwa** [comment]
@damiankay solving issue 1 seems critical if we want Makerparty to be self service. Do we have examples of how the email work around would work (what's the user flow here?)

I'm not clear on the implications of issue 2 and 3.

**Comment by damiankay** [comment]
@lovegushwa I believe that for other Nationbuilder events, hosts have simply emailed RSVPs with any changes or updates. 

If we need to add this functionality Fission thinks that it is possible, but will require significant custom code and will delay launch.

**Comment by damiankay** [comment]
@geroter can you please indicate whether you feel it's preferable to: 
1. Eliminate the ability for hosts to edit an event after it's created (requiring them to instead email RSVPs of any changes and/or updates).
or 
2. Extend the timeline to allow Fission to find a solution (I.e. create a custom user type that can edit events without accessing the entire control panel).

This is a blocker for Fission and will affect the overall timeline if we don't provide an answer tomorrow. 

Thanks!

**Comment by damiankay** [comment]
As we haven't received any feedback, we're moving ahead with Fission's recommendations: 
1. Hosts will not be able to edit events (this is not supported by Nationbuilder)
2. Hosts will not be able to bulk upload contacts (also not supported by Nationbuilder)
3. Only 1 threshold level for RSVPs will be displayed (another Nationbuilder limitation)

CC @geroter @jendc123

**Comment by a-kilroy** [comment]
Hey everyone,

This was a know and planned for. In the scope of work we asked for custom
permissions for trusted event hosts to be able to use the control panel to
edit their events.
External partners or outside/new event hosts will not.

This is big priority for our people so let me know if we need to talk it
through.

**Comment by damiankay** [comment]
Hi @a-kilroy - Fission's problem is that they attempted to create this functionality, and were unsuccessful. They think that they could find a work around, but it would not be within our timeline. So our options are: 
A) Launch with this functionality, but delay launch until they've found a solution
B) Launch withouth this functionality, and expect hosts to either email their RSVPs with updates, or request an admin to change their event details (there are only 300 projected events this year)
C) Launch without this functionality, but expect Fission to keep working on a solution post-launch. Until a solution is found, expect hosts to either email their RSVPs with updates, or request an admin to change their event details (there are only 300 projected events this year)

This functionality = ability to edit events after they've been created. 

Our deadline for wireframes feedback has passed, and I don't think we want to delay launch any longer (it's already pushed to Sep 20), so I think B or C are our only options, but happy to defer. In the end I think it's up to @geroter but happy to talk it through! 

CC @simonwex

**Comment by a-kilroy** [comment]
Can we set up a call with NB on Tuesday when I am back? This was part of
the functionailty we were told exists in our assessment and I believe it is
documented in their support. This one was supposed to be easy because it
was native functionaily. If their are issues with it I'd like to push them
to resolve.

**Comment by damiankay** [comment]
@a-kilroy yes - sounds good. I'll set that up for Tuesday. Thx!

**Comment by damiankay** [comment]
@a-kilroy - do you remember who you spoke with about hosts being able to edit events? Probably best to have them on the call. 

CC @valianttry (as you signed the deal)

**Comment by a-kilroy** [comment]
Nathan so not much help. That said I think we should be talking about them in two different groups: First time new hosts, trusted Mozilla hosts, since we'll be handling the two groups differently.

**Comment by jendc123** [comment]
Hi @a-kilroy, @damiankay, @valianttry ,

For some reason I don't see my earlier comment, but we connected with NationBuilder and found a light weight option for hosts to edit events.  We can include the functionality within our current timeline. 

Bulk uploading still doesn't seem to be an option.

**Comment by a-kilroy** [comment]
That's great! I still think we need to address the two different host
groups: Trusted Mozillian hosts, New User Hosts. I believe the permissions
needed for them are different (the first being control panel users, the
second not being) and should be planned for as such.

**Comment by damiankay** [comment]
That's amazing @jendc123! Thanks very much! We'll confirm the details for the two host types and I'll follow up later today.

**Comment by damiankay** [comment]
This is resolved. Following up with @jendc123 Re user permissions.
