### ISSUE TITLE
EU Copyright Petition V2: Copy deck

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#311]
Detailed description of work:
Fission requires the copy deck for Petition V2 by September 6 in EN and German. Please let me know how close we are with EN. I can help with localizing into German. 

Please let me know if you anticipate any trouble hitting these deadlines. 

_Start date: August 29, 2016_
_Due date: September 6, 2016_

CC: @HPaulJohnson @KevZawacki @valianttry

**Comment by HPaulJohnson** [comment]
Draft here: https://docs.google.com/document/d/1M0ptw1CWD2040IlxNRqZiA_fiVvv5MMjkfp96bI7Rg0/edit

I've asked @KevZawacki to take a quick pass and work his magic so hopefully we can finalize/close this one out tomorrow once he has had a chance to edit.

**Comment by KevZawacki** [comment]
@HPaulJohnson Just dropped in my edits!

**Comment by HPaulJohnson** [comment]
@damiankay this is good to go. re: approvals, not sure how that's been handled for website copy thus far. 

@beccaklam final copy for v2 above. includes some ideas for the dynamic messages on petition form, ideas for pullquotes and a blurb for the postcrimes promo.

**Comment by HPaulJohnson** [comment]
updated postcrimes promo copy per some feedback from design. i'm calling this one complete.

**Comment by damiankay** [comment]
Hey @HPaulJohnson - can you please highlight the copy that is new / edited so that we can flag it for L10n in Pontoon? Otherwise, @ScottDowne needs to go through line by line and compare with the V1 website. 
[V2 Copy deck](https://docs.google.com/document/d/1M0ptw1CWD2040IlxNRqZiA_fiVvv5MMjkfp96bI7Rg0/edit)

Scott is hoping to tackle this tomorrow morning EST.

**Comment by damiankay** [comment]
@ScottDowne - sorry, all of the copy in the V2 deck is net new. It's not combined with the V1 copy, so it should be fairly clear. Please ping @HPaulJohnson with any questions.
