### ISSUE TITLE
Design localized versions of Email 1 callout image

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#313]
Detailed description of work:

@natalieworth already created an English version of the callout graphic for the Copyright email 1. (See: https://github.com/MozillaFoundation/Advocacy/issues/197) I now have localized copy for the image so that @natalieworth can create a localized callout for the other audiences.

In this spreadsheet:
https://docs.google.com/spreadsheets/d/1xLBTGrTMYZh-cDEdWwSugRbt1A7MckpUyDWNsoYdIHI/edit#gid=2056061813

Tab "Email 1" and row 2 = localized callout copy for each language that is needed.

*Start date: 8/30/3016 \* 
*Due date: 8/31/3016 \* 

CC: @stephaniemcv

**Comment by natalieworth** [comment]
@stephaniemcv working on these this morning and will post asap

**Comment by natalieworth** [comment]
@stephaniemcv Here are the final localized images for email:
@ 1 x: https://drive.google.com/drive/folders/0B20-0lpP23c0QVpwTzY3UXVkdHM
@ 2 x: https://drive.google.com/drive/folders/0B20-0lpP23c0aThGYjVxZEVOS1E
Let me know if you need anything else for these!
