### ISSUE TITLE
Email Confirmation Triggers firing EN for all Languages

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#314]
Detailed description of work: When signing up for email on the petition page, in any language the English version of the confirmation is sent, rather than the preferred language. 

Per email thread from Jessilyn Davis:  "It's a issue for Walter then to figure out order of operations and if language isn't passing through the same time as the contact record is created. If there's not language being passed through _at_ the time that the record is created, it'd default to null, be updated with EN, and the English trigger would fire."

*Start date: \* August 30, 2016
*Due date: \*  August 31, 2016

CC: @valianttry @damiankay @drewmoto @imagerwalt

**Comment by damiankay** [comment]
@jendc123 - can you please make this a top priority?

**Comment by damiankay** [comment]
CC @cadecairos

**Comment by damiankay** [comment]
@stephaniemcv - Fission believes this has been fixed. Would you be able to run some tests please?

**Comment by stephaniemcv** [comment]
DE, FR, ES, and PL - Confirms are now working!

**Comment by damiankay** [comment]
Fantastic! Thanks @stephaniemcv 

CC @jendc123
