### ISSUE TITLE
Add Fission dev to Github

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#315]
Detailed description of work: Please add Fission Dev Julien to our Github repo. He'll be covering on Thurs/Fri while George and Walter are OOO. 
Github handle is: julienburns

*Start date: \* August 30, 2016
*Due date: \* August 31, 2016

CC: @valianttry @simonwex @jendc123

**Comment by damiankay** [comment]
@simonwex can you please do this or reassign if Chris isn't back tomorrow?

**Comment by cadecairos** [comment]
Julien has been sent an invite to collaborate on this repo

**Comment by damiankay** [comment]
Great - thanks Chris

**Comment by damiankay** [comment]
@cadecairos - Julien says that he hasn't received the invite yet. Are you able to re-send?

**Comment by cadecairos** [comment]
@damiankay might have gone to spam? 

Ask them to visit this: https://github.com/MozillaFoundation/Advocacy/invitations

**Comment by damiankay** [comment]
He's in - thanks @cadecairos
