### ISSUE TITLE
Identify why Bablic translation are being lost

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#316]
Detailed description of work:
We've now had to re-enter translations in Bablic numerous times. This is obviously very innefficient. @jendc123, can you shed some light on why this is happening? Could it be because multiple people are in Bablic at the same time? Perhaps code is being deployed while translations are being entered? Maybe it's just a matter of improving our workflow to support multiple editors. 

*Due date: \* September 1, 2016

CC: @valianttry @ScottDowne

**Comment by jendc123** [comment]
@damiankay we can work on a better work flow. Any time the theme is updated  i.e. the typo fix to get the email share to work it ends up overwriting that piece in Bablic.  We can discuss more next week.

**Comment by damiankay** [comment]
Thanks @jendc123. I'm working on the localization plan for Maker Party which I'm hoping to have a draft of on Tuesday. If it's possible to chat sometime on the 6th that would be great.

**Comment by jendc123** [comment]
Hi @damiankay any time we make a change on the Nationbuilder theme i.e. text edits it causes Bablic to re-crawl the site and takes the new string.

**Comment by damiankay** [comment]
Thanks @jendc123. So, how can we improve our workflow to avoid this in the future?
