### ISSUE TITLE
Meme Video Title Cards/ Bumpers

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Advocacy#317]
Detailed description of work: Create end bumpers for meme video/ video 2. Final copy is:
CARD 1
Memes of all things 
should not be illegal.

CARD 2
Let’s bring E.U. copyright law 
into the 21st century.

CARD 3/END
mzl.la/copyfail
Mozilla logo

Proposing to use impact font to match the meme content.

CC:

**Comment by brettgaylor** [comment]
@natalieworth we may need to also create the opening shot of this video with text in the same style, too

**Comment by brettgaylor** [comment]
Also - the first card should read
Memes
of all things
should not be illegal

Or
Memes, of all things, should not be illegal

Right now it feels like "memes of all the things"

**Comment by natalieworth** [comment]
Impact (still need to work out colours):
<img width="1058" alt="screen shot 2016-08-31 at 3 40 42 pm" src="https://cloud.githubusercontent.com/assets/14876567/18149173/957c9b12-6f93-11e6-9451-a921b2b9f916.png">

Other options (my preference):
<img width="1298" alt="screen shot 2016-08-31 at 3 28 10 pm" src="https://cloud.githubusercontent.com/assets/14876567/18149182/9e2e0a52-6f93-11e6-9d3a-029c4f54de11.png">
<img width="1288" alt="screen shot 2016-08-31 at 3 31 17 pm" src="https://cloud.githubusercontent.com/assets/14876567/18149183/a139de92-6f93-11e6-805e-c12756e680d6.png">
<img width="319" alt="screen shot 2016-08-31 at 3 39 02 pm" src="https://cloud.githubusercontent.com/assets/14876567/18149186/a5f4688a-6f93-11e6-9fe8-1d0c3dda63ec.png">
<img width="317" alt="screen shot 2016-08-31 at 3 39 11 pm" src="https://cloud.githubusercontent.com/assets/14876567/18149480/2396a05e-6f95-11e6-8885-48bb8c9bdd11.png">
<img width="320" alt="screen shot 2016-08-31 at 3 39 17 pm" src="https://cloud.githubusercontent.com/assets/14876567/18149481/2397d4f6-6f95-11e6-8303-a240b511faa3.png">
<img width="320" alt="screen shot 2016-08-31 at 3 39 21 pm" src="https://cloud.githubusercontent.com/assets/14876567/18149482/23c97baa-6f95-11e6-9b4f-ec079c723edd.png">

**Comment by natalieworth** [comment]
Thanks @brettgaylor will update language too in new/ revised versions

**Comment by natalieworth** [comment]
I'm leaning more toward something typographic that visually could relate to the website and identity/ brand of the campaign vs. using 'Impact':
- I think it would be good to visually differentiate between the ridiculousness of the parody video and the actual informed content we’re presenting?
- systemic ident/ bumper text and staying that could be placed across all videos and still relate back to the campaign and landing page content
- could be something that we use across social
- I think mimicking the video too much in our messaging could take away from the identity/ brand of the campaign
- the end/ bumper should disassociate with the parody in order to provide a visual link to our identity and establish the message as something authoritatively relative to our campaign (rather than the humour of the video)

**Comment by brettgaylor** [comment]
Loving this treatment, especially if we could animate it - reminscent of
70s Sesame Street!

https://www.youtube.com/watch?v=__48P1Fbjm8

https://cloud.githubusercontent.com/assets/14876567/18149186/a5f4688a-6f93-11e6-9fe8-1d0c3dda63ec.png

**Comment by natalieworth** [comment]
Final export for these are here: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0RTI4cnVmQ0JSM3M
Closing but reopen if any adjustments

**Comment by natalieworth** [comment]
Updated file (containing the end card designs) for this is here:
After Effects: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0ZWhkTlpvTnBVX2s
Illustrator: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0U3pUeGlnQTg1NVE
