### ISSUE TITLE
Fundraising email review

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#32]
We'll be comparing conversion across three segments -
- Active Advocates who opened at least one
- Opened at least one & joined prior to February 17
- Anyone who joined the list after February 17

Please review the email copy, test the link and survey and note any feedback in this ticket.

**Comment by lovegushwa** [comment]
@stephaniemcv can you add a little more padding around the call-out image? (left and bottom)
Even just the bottom of the image might be enough. It's a little tight to the text.

<img width="1051" alt="screen shot 2016-05-17 at 12 02 58 pm" src="https://cloud.githubusercontent.com/assets/12228435/15337390/58a038a4-1c30-11e6-9001-961c41ccb8c4.png">

**Comment by valianttry** [comment]
1. Update all URLs to:
   https://donate.mozilla.org/en-US/?presets=100,50,25,15&amount=25
   (These will be higher-average donors, and we should always try to have a present until we test it and find that's not a good thing :)
2. Add Mark's title (check old emails to see how we've treated his signature before. We should stay consistent.)
3. There's a lot of space between the salutation and line 1 -- this could be correct, but just pointing out that the loose leading really bumps down content in email. We may want to revisit and tighten the leading up a bit. (Not nec. for this email)

**Comment by valianttry** [comment]
Oh, why doesn't it say it's from Mark Surman, Mozilla? vs. just "Mozilla Foundation" in my inbox:

![_test_the_numbers_don t_lie_-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/15337483/dffc2970-1c30-11e6-900e-5b528096f571.png)

**Comment by stephaniemcv** [comment]
@lovegushwa - added padding
@valianttry  - 1-3 is done.
Actually none of our sender profiles have Mark's name. Do you want me to build one?

**Comment by valianttry** [comment]
@stephaniemcv not critical... but i wonder if it would increase open rate. Let's send as is now, but let's look into it?

**Comment by stephaniemcv** [comment]
@valianttry added a note to build and test a Sender profile with Mark's name. Closing case.
