### ISSUE TITLE
Copyright Email 1 QA

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#320]
Detailed description of work: Please review copy, links, images and rendering in emails. GB,DE,ES,FR,PL and put comments/edits in this ticket.

*Start date: \* 9-2-16
*Due date: \* 9-2-16

CC: @valianttry

**Comment by valianttry** [comment]
Image wrapping leaves too much white space underneath:

![_test-de_das_ist__im_prinzip__illegal_-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/18211469/971f0652-70f2-11e6-8f81-ad8aa69a22b8.png)

**Comment by valianttry** [comment]
The spacing issue in my earlier comment is my only edit @stephaniemcv in both the en-GB and DE versions. I checked the copy, clicked all URLs. 

If you fix that I don't need a 2nd set of tests for review. Really great work! 👍 💯

**Comment by stephaniemcv** [comment]
And it's an issue that can't be fixed really. The text and image are in two separate table cells, side by side. The gap is because the left cell with the text is longer than the image. It's coded this way to mobile responsive, the cell with the image stacks itself under the cell with the text when the screen is less than a certain size. Any time we just drop an image in the same cell with text, yes the text will wrap, but it also won't shift to fit small screens forcing you to right to left scroll on a device. 

Mobile Preview with Non Mobile Responsive Code
![not-mobile-responsive](https://cloud.githubusercontent.com/assets/11812272/18212122/8cac2e14-70fe-11e6-98c9-d9b8eae23353.jpg)

Mobile Preview with Mobile Responsive Code
![mobile-responsive](https://cloud.githubusercontent.com/assets/11812272/18212129/95b74d18-70fe-11e6-8cc2-4570f05519b3.jpg)

**Comment by valianttry** [comment]
@stephaniemcv Polish is 👍 no edits. Nicely done!

**Comment by valianttry** [comment]
@stephaniemcv Spanish is 👍 no edits. 💃

**Comment by valianttry** [comment]
@stephaniemcv French is 👍 no edits. 🍷
