### ISSUE TITLE
Review postcrimes copy

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#321]
Detailed description of work: Review copy on postcrimes to make sure it is as engaging and clear as possible

https://docs.google.com/spreadsheets/d/1gj-izvaiouvc7MPHESgtFlHXZE5Kx8eLOrsfKKc7iv0/edit

_Start date: September 6, 2016_
_Due date: September 7, 2016_

CC: @KevZawacki @HPaulJohnson

**Comment by KevZawacki** [comment]
@brettgaylor Just reviewed -- mostly small tweaks.

**Comment by KevZawacki** [comment]
@brettgaylor Per yesterday's discussion, I've toned down the Post Crimes language. So:

"In some European Union countries, photographing public buildings and posting the pictures on social media is illegal. It's just one example of how copyright law in the EU is out of touch with modern life.

**This is an absurb law. We're going to help you prove it -- with a rebellious selfie! Create a photo of yourself in front of one of these landmarks.**

If you like what you make, send it to a friend. Or, send a physical postcard to your Member of European Parliament!"

**Comment by brettgaylor** [comment]
This is approved
