### ISSUE TITLE
Typekit error

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#322]
I saw someone tweeting that the page isn't rendering due to a TypeKit error:
https://twitter.com/aeris22/status/772908800646971392/photo/1

**Comment by ScottDowne** [comment]
Looks like the service Typekit is being used, and it isn't aware or the new domain, and needs to be.

We should see if Fission knows what this is.

**Comment by ScottDowne** [comment]
That error is unrelated to the font not rendering.

Not sure what the typekit error is. Seems to be related to an adobe service, and not sure what if any symptom it's causing.

The page not rendering is an issue with fira font and Linux. There is a parsing error in the font  hosted on google fonts, and Linux refuses to render a potentially broken font. There may also be other systems that react to this font in this way.

I solved it for myself by downloading a better version of Fira on my system ages ago. Up to this point not enough people use Linux to warrant us fixing whatever is on google fonts, but it does bug thee heck out of me. I would be happy look at what's involved in fixing google fonts.

**Comment by ScottDowne** [comment]
Here is the bug on fira not loading: https://bugzilla.mozilla.org/show_bug.cgi?id=1100658

**Comment by ScottDowne** [comment]
If we moved what's built on nation builder from google fonts to a Mozilla hosted font `<link rel="stylesheet" href="https://code.cdn.mozilla.net/fonts/fira.css"/>` the font the renders correctly in Linux.

**Comment by gholme4** [comment]
@ScottDowne @brettgaylor @damiankay I updated according to Scott's suggestion.

**Comment by ScottDowne** [comment]
So that should fix the font not rendering for some. Dunno what the typekit thing is about.

**Comment by gholme4** [comment]
@ScottDowne Typekit authorizes by domain and the domain name recently changed. Typekit is packaged with NationBuilder.

**Comment by ScottDowne** [comment]
Is this something we can fix in NationBuilder? or how bad is it if we don't fix it? Looks to be just a random error, and doesn't seem to have any visible side effects.

I think maybe we can just close this issue now.

**Comment by gholme4** [comment]
@ScottDowne To resolve the error, we need to create a custom kit and enter a new Typekit key in the NationBuilder site settings.

**Comment by damiankay** [comment]
@ScottDowne is this still an issue? If so, who needs to action this?

**Comment by ScottDowne** [comment]
Page is rendering now, but the typekit error persists. Means they are not connected. And the font fix worked.

I would say, close this as it doesn't look like typekit is causing any rendering issues. If we find any issues around the typekit, we should file a new issue.
