### ISSUE TITLE
High number of 503 response codes on moz-nationbuilder-salesforce app

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/Advocacy#323]
Detailed description of work: 
This app handles nationbuilder hooks and syncs that data to salesforce. It seems like when it syncs with nationbuilder (every ten minutes) it may take >30 seconds, depending on the amount of traffic. Heroku does not allow requests to hang for longer than that, so we should consider returing a response immediately upon receiving the sync request, and process the sync in the background.

*Start date: \* 
*Due date: \* 

CC: @ScottDowne @valianttry @damiankay

**Comment by ScottDowne** [comment]
I'm fine with the solution @cadecairos suggested, I think we just need to figure out who should do this work.

**Comment by damiankay** [comment]
It sounds like Heroku time outs were causing quite a few issues with additional API calls. Based on that info, I'd say it's worth doing this work. 

How much time do you think is require @cadecairos ? 

Who needs to approve this? 

CC @ScottDowne @valianttry

**Comment by cadecairos** [comment]
this is still an issue: ![](https://pageshot.net/images/94aee8f0-2158-4170-aebe-bfd4d2ef4d7c)

@valianttry should we ask fission to investigate this?

**Comment by hannahkane** [comment]
Can I close this?
