### ISSUE TITLE
Build new fundraising snippet UX for testing

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#326]
Detailed description of work:
We are working with the Firefox UX team to conform the fundraising snippet design with the snippet design guidelines. We want to test new designs by @lovegushwa #70 . The Firefox UX team has approved the test designs. The designs need to be built and prepared for snippet service by @ScottDowne 

Then, @vojtechmozilla will design tests.

_Start date: September 6, 2016_ 
_Due date: September 13, 2016_ 

CC:

**Comment by ScottDowne** [comment]
For context and reference (and so I don't need to have two issues on my radar) I'm putting the comps in here too.

1 blue
<img width="1236" alt="test variant-snippet-blue-01" src="https://cloud.githubusercontent.com/assets/12228435/17917806/8d7435e4-6974-11e6-89c4-99b3ac76e9c8.png">

2 blue
<img width="1236" alt="test variant-snippet-blue-02" src="https://cloud.githubusercontent.com/assets/12228435/17917811/936db466-6974-11e6-853e-b6cb0b6c4880.png">

3 blue
<img width="1236" alt="test variant-snippet-blue-03" src="https://cloud.githubusercontent.com/assets/12228435/17917814/988f1aa2-6974-11e6-8dab-9fe975fa5f48.png">

4 blue
<img width="1236" alt="test variant-snippet_01-05" src="https://cloud.githubusercontent.com/assets/12228435/18059902/15c580f6-6dd0-11e6-9a89-5f8aa285e83c.png">


1 green
<img width="1236" alt="test variant-snippet-green-01" src="https://cloud.githubusercontent.com/assets/12228435/17917815/9ea53c00-6974-11e6-8fd8-d9e59e2873e6.png">

2 green
<img width="1236" alt="test variant-snippet-green-02" src="https://cloud.githubusercontent.com/assets/12228435/17917824/a3284074-6974-11e6-9c94-9bc6ff2f8c37.png">

3 green
<img width="1236" alt="test variant-snippet-green-03" src="https://cloud.githubusercontent.com/assets/12228435/17917827/a7a66586-6974-11e6-842e-6937babefb84.png">

4 green
<img width="1236" alt="test variant-snippet_01-03" src="https://cloud.githubusercontent.com/assets/12228435/18059913/253399ec-6dd0-11e6-9dd2-d1f90810b84a.png">


1 red
<img width="1236" alt="test variant-snippet-red-01" src="https://cloud.githubusercontent.com/assets/12228435/17917899/22a737c4-6975-11e6-9a5e-582a7188113a.png">

2 red
<img width="1236" alt="test variant-snippet-red-02" src="https://cloud.githubusercontent.com/assets/12228435/17917903/275bdb1c-6975-11e6-89f6-e7924f322fac.png">

3 red
<img width="1236" alt="test variant-snippet-red-03" src="https://cloud.githubusercontent.com/assets/12228435/17917910/2d108c1a-6975-11e6-9554-7e25d65da259.png">

4 red
<img width="1236" alt="test variant-snippet_01-04" src="https://cloud.githubusercontent.com/assets/12228435/18059921/357060ec-6dd0-11e6-9d48-5728aba6f43c.png">

gray - one button
<img width="1236" alt="test variant-snippet_01-02" src="https://cloud.githubusercontent.com/assets/12228435/18059929/3ede080a-6dd0-11e6-9fb0-0cb28e25b456.png">

FOR CONTEXT, Last years optimized design we are testing a few of the above options against:
![screen shot 2016-08-24 at 2 31 31 pm](https://cloud.githubusercontent.com/assets/12228435/18060008/b8d71ab6-6dd0-11e6-8309-07c3de0ebfd2.png)

**Comment by ScottDowne** [comment]
Here is the reference to the updated opt out http://people.mozilla.org/%7Eshorlander/about-home-snippet-opt-out/about-home-test-02.html

**Comment by ScottDowne** [comment]
I'm going to number the tests off with the template variables in a table, so it's easy for me to reference them.

### Simple Template:

| number | button color | icon | preview |
| :-- | :-- | :-- | :-- |
| 1 | blue | heart | <img width="100" alt="test variant-snippet_01-05" src="https://cloud.githubusercontent.com/assets/12228435/18059902/15c580f6-6dd0-11e6-9a89-5f8aa285e83c.png"> |
| 2 | green | heart | <img width="100" alt="test variant-snippet-green-03" src="https://cloud.githubusercontent.com/assets/12228435/18059913/253399ec-6dd0-11e6-9dd2-d1f90810b84a.png"> |
| 3 | red | heart | <img width="100" alt="test variant-snippet-green-03" src="https://cloud.githubusercontent.com/assets/12228435/18059921/357060ec-6dd0-11e6-9d48-5728aba6f43c.png"> |
| 4 | grey | heart | <img width="100" alt="test variant-snippet-green-03" src="https://cloud.githubusercontent.com/assets/12228435/18059929/3ede080a-6dd0-11e6-9fb0-0cb28e25b456.png"> |

### Fundraising Template:

| number | buttons scale | button color | icon | preview |
| :-- | :-- | :-- | :-- | :-- |
| 1 | small | blue | heart | <img width="100" alt="test variant-snippet-blue-01" src="https://cloud.githubusercontent.com/assets/12228435/17917806/8d7435e4-6974-11e6-89c4-99b3ac76e9c8.png"> |
| 2 | small | blue | heart | <img width="100" alt="test variant-snippet-blue-02" src="https://cloud.githubusercontent.com/assets/12228435/17917811/936db466-6974-11e6-853e-b6cb0b6c4880.png"> |
| 3 | large | blue |  | <img width="100" alt="test variant-snippet-blue-03" src="https://cloud.githubusercontent.com/assets/12228435/17917814/988f1aa2-6974-11e6-8dab-9fe975fa5f48.png"> |
| 4 | small | green | heart | <img width="100" alt="test variant-snippet-green-01" src="https://cloud.githubusercontent.com/assets/12228435/17917815/9ea53c00-6974-11e6-8fd8-d9e59e2873e6.png"> |
| 5 | large | green | heart | <img width="100" alt="test variant-snippet-green-02" src="https://cloud.githubusercontent.com/assets/12228435/17917824/a3284074-6974-11e6-9c94-9bc6ff2f8c37.png"> |
| 6 | large | green |  | <img width="100" alt="test variant-snippet-green-03" src="https://cloud.githubusercontent.com/assets/12228435/17917827/a7a66586-6974-11e6-842e-6937babefb84.png"> |
| 7 | small | red | heart | <img width="100" alt="test variant-snippet-green-03" src="https://cloud.githubusercontent.com/assets/12228435/17917899/22a737c4-6975-11e6-9a5e-582a7188113a.png"> |
| 8 | large | red | heart | <img width="100" alt="test variant-snippet-green-03" src="https://cloud.githubusercontent.com/assets/12228435/17917903/275bdb1c-6975-11e6-89f6-e7924f322fac.png"> |
| 9 | large | red |  | <img width="100" alt="test variant-snippet-green-03" src="https://cloud.githubusercontent.com/assets/12228435/17917910/2d108c1a-6975-11e6-9554-7e25d65da259.png"> |

So we'll have two templates, and these are the variables they can take. button scale, button color, and icon. Along with existing previous variables like button text and paragraph text.

**Comment by vojtechmzl** [comment]
Hey @ScottDowne , sorry for the late notice, but I put together the[ following spreadsheet](https://docs.google.com/spreadsheets/d/1q-ZpNzeds_090hzyLPxY_PQPWwRxFcTRcWjpo-TlKys/edit#gid=0) with the different variants late yesterday. Was hoping to pass it along today, but you beat me to it. Could we combine both into a single list? There is also a testing plan [here](https://docs.google.com/document/d/1ubkwri1d8WEwySIooxXSfY2y61GHKVRR1FWFcOR8_jY/edit#). 

Please let me know if it would be easier to hop on a call and chat about this.

Thanks!

**Comment by ScottDowne** [comment]
I'm happy to hope on a call, and explain my goal. The above table is the variables I'm building into the templates, and not a master list of the tests. It's totally build related. I can remove it if it's confusing the situation.

**Comment by ScottDowne** [comment]
A lot of times I'm asked to build multiple templates for things that are just variables. I'm trying to clear that up.

**Comment by ScottDowne** [comment]
@lovegushwa no monthly checkbox?

**Comment by vojtechsedlak** [comment]
hey @ScottDowne, I am just coordinating with Wes the timeline for launching this test, so I wanted to check in on how things are looking with the building of the snippet variables. When do you think you will be able to complete the build? Thanks!

**Comment by ScottDowne** [comment]
@vojtechmzl I don't have a time for you, I'm just doing it asap, but secondary to maker party and petition work.

If things go the way they are, probably by the end of the week.

If you need it by a certain time, let me know, and we can talk.

For how things are looking, I have a good stab at it, but it's not done yet, needs QA, and needs to go through review still.

**Comment by vojtechsedlak** [comment]
Thanks for the update @ScottDowne, this is naturally less of a priority than the campaign stuff. End of the week would be great, but if this gets pushed to next week, that's fine as well.

Thanks!
