### ISSUE TITLE
Video 2 [meme jail] - versioning

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#328]
- [x] English pre/post cards
- [x] English subtitles
- [x] Spanish pre/post cards
- [x] Spanish subtitles
- [x] French pre/post cards
- [x] French subtitles
- [x] German pre/post cards
- [x] German subtitles

**Comment by natalieworth** [comment]
Final MOV and MP4 files for the meme jail video are here (with subtitles: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0UUJteGlkRUlpUVE

English/ Version with no subtitles: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0QVVleDItT1V2ckU
