### ISSUE TITLE
Video 3 [CSI GIF] - versioning

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#329]
- [x] on screen text English
- [x] pre/post text English
- [x] Subtitling English
- [x] on screen text French
- [x] pre/post text French
- [x] Subtitling French
- [x] on screen text German
- [x] pre/post text German
- [x] Subtitling German
- [x] on screen text Spanish
- [x] pre/post text Spanish
- [x] Subtitling Spanish

**Comment by natalieworth** [comment]
Final Files for the subtitled versions are here in MOV and MP4 format (852x480/ 16:9 aspect ratio):
https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0eHNLMGFCSVh6NUE
