### ISSUE TITLE
Test: Fundraising Snippet Format - September 2016

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#333]
Detailed description of work: Execute a test of multiple design variants of the fundraising snippet to arrive at an optimal solution that combines high CTR with UX principles. This ticket will be used to track progress of the test set up and evaluation. 

_Start date: September 8, 2016_ 
_Due date: October 14, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @ScottDowne @lovegushwa @valianttry 

Existing Tickets:
- Designing the snippet #70 
- Building the snippet #326

**Comment by vojtechsedlak** [comment]
See results for this test [here.](https://docs.google.com/document/d/1ubkwri1d8WEwySIooxXSfY2y61GHKVRR1FWFcOR8_jY/edit#) The next step is to run a test in new target locales to further optimize the new design (see #590 for further info)

**Comment by valianttry** [comment]
@vojtechmzl can you calculate the total impact on EOY fundraising totals in the tables? We will have roughly 1 billion impressions. For instance, if I calculate the performance difference during the life of the campaign based on the control EOY 2015 vs. the winning new design I find that we will raise $1.5 million less. That is very significant. I know there are further tests underway to mitigate, but I want to make certain we are communicating overall impact along the way.

**Comment by vojtechsedlak** [comment]
Hi @valianttry, I've updated the [slides](https://docs.google.com/presentation/d/1oamWrdjZbO0w6ml_m8xSgscWVxtAvC8VhfFQfPFpnLQ/edit#slide=id.g16df6e186e_1_0) with actual projections of impressions, based on the snippet calendar. As you can see, we are projected to get around 1B impressions, which should get us to the target of 3M for snippet donations. Let me know if we can chat about in more detail. Thanks!

**Comment by Matt-Holland** [comment]
This test has been run, and the results reported. Although we will continue to test new variants of the snippet during the rest of the campaign, this ticket for the original test can be closed.
