### ISSUE TITLE
Design Vote.org icons for snippet promotion

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#334]
**Detailed description of work:**
We will be promoting voter registration in the Firefox snippet via simple text + icon combination. Users will see something like this:

![firefox](https://cloud.githubusercontent.com/assets/9830371/18369136/ad15a3d6-75d8-11e6-9249-32d7d423dc68.png)

We need a few icon variations, say, 5 that somehow scream AMERICA!!!! And symbolize the flag, voting, democracy, bald eagles, bison, mustang horses, apple pie, mom jeans, etc. (sort of kidding, but you get the picture)

Imagery to avoid (this is important): Anything relating to legislators, candidates, or legislation (no pics of the White House); anything related to specific issues or laws (such as copyright or net neutrality).

Draft copy is in this document:
https://docs.google.com/document/d/1nQACMOf1jquvePx7_O2nMVJbfHzKZM1jF-QiVGmvWG0/edit?usp=sharing

_Start date: September 9, 2016_ 
_Due date: September 13, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @lovegushwa @natalieworth

**Comment by brettgaylor** [comment]
![image](https://cloud.githubusercontent.com/assets/345974/18370106/52cfd05c-75df-11e6-8f5c-34db8bcdd16b.png)

**Comment by valianttry** [comment]
![Image of the most awesome patriot ever](https://pbs.twimg.com/media/Brj1cV1CIAAriD2.png)

**Comment by valianttry** [comment]
![fuck yeah](https://www.princecharlescinema.com/wp-content/uploads/2016/04/Team-America-LARGE-1280x480.jpg)

**Comment by valianttry** [comment]
![I voted sticker](http://www.politicspa.com/wp-content/uploads/2013/11/I-Voted-Sticker.png)

**Comment by valianttry** [comment]
![Uncle Sam](http://www.prescott.va.gov/images/uncle-sam-600.jpg)

**Comment by valianttry** [comment]
![star](http://www.clipartbest.com/cliparts/Rcd/gEe/RcdgEe89i.gif)

**Comment by valianttry** [comment]
![Lady Liberty](http://www.rownyc.com/wp-content/uploads/2014/02/Statue_liberty_1100x530.jpg)

**Comment by valianttry** [comment]
@lovegushwa these were due today, but we have a little whiggle room. Do you know when you might be able to share some designs?

**Comment by lovegushwa** [comment]
@valianttry ... @natalieworth has some time tomorrow. We have 7 other v2 petition snippets were knocking out today so glad Natalie can provide some assistance.

**Comment by natalieworth** [comment]
@valianttry @lovegushwa Was able to get a start on these with rough ideas mocked up in the redpen here: https://redpen.io/p/ohb3c000d278d82b8a

**Comment by beccaklam** [comment]
@valianttry @lovegushwa @natalieworth Here are some more ideas! https://redpen.io/p/wa90946297a316bcae I also put my files up on the drive here: https://drive.google.com/drive/folders/0B20-0lpP23c0ODlsUk15d3g0LVE?usp=sharing

**Comment by beccaklam** [comment]
@valianttry @lovegushwa @natalieworth I've added the Natalie's designs to the redpen: https://redpen.io/p/wa90946297a316bcae for you to share with the snippet team Andrea!

**Comment by beccaklam** [comment]
@valianttry @lovegushwa @natalieworth Hi Andrea, I've exported the icons of the redpens above ^. You can find them in a folder here: https://drive.google.com/drive/folders/0BzuBOR2VJQqUeElxWWVueGRpMnc?usp=sharing

**Comment by natalieworth** [comment]
@beccaklam Thanks so much for taking this over! Going to close this issue—but feel free to reopen if you need to make any changes :D 👍 💯

**Comment by valianttry** [comment]
@beccaklam there are guidelines for the icons (pasted a deck slide below with specs). Can you resave them in this format in the same drive and let me know when you have them ready? I can then send to Wes on the snippet team.

cc @lovegushwa @natalieworth 

![snippet_copy_tone_and_icon_guidelines_-_google_slides](https://cloud.githubusercontent.com/assets/9830371/18695484/3395122e-7f80-11e6-8a48-42859b373777.png)

**Comment by beccaklam** [comment]
Hi @valianttry you can find the updated PNGs and .AI file in this google drive folder: https://drive.google.com/drive/folders/0BzuBOR2VJQqUeElxWWVueGRpMnc?usp=sharing
