### ISSUE TITLE
Write vote.org snippet promotion text

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#335]
Detailed description of work:

We will be promoting vote.org in the Firefox snippet to help people register to vote or check their registration status ahead of the November 8 election. The snippet promotions will run intermittently from Sept 15 - October 15 as the schedule allows. We need some simple, creative snippet copy that screams AMERICA!!!!

Here is the icon and text arrangement on the snippet for reference:

![firefox](https://cloud.githubusercontent.com/assets/9830371/18373604/56f5466a-75fa-11e6-9b8a-b17518c0240a.png)

Icon design bug is here: #334 

_Start date: September 8, 2016_ 
_Due date: September 13, 2016_ 

CC: @KevZawacki @HPaulJohnson

**Comment by valianttry** [comment]
Draft copy is in this document:
https://docs.google.com/document/d/1nQACMOf1jquvePx7_O2nMVJbfHzKZM1jF-QiVGmvWG0/edit?usp=sharing

**Comment by KevZawacki** [comment]
Hi @valianttry. Thanks for sharing. The draft copy is clever! I proposed just a few small tweaks. (If we need more variants, just let me know -- happy to write some.)

Would we be comfortable sharing this news on Twitter, too? I can adapt snippet copy for twitter.com/mozilla. twitter.com/firefox may be interested, too.

**Comment by valianttry** [comment]
awesome @KevZawacki I accepted your edits. I've confirmed with legal that we won't be promoting vote.org in any channels other than snippet.

**Comment by valianttry** [comment]
closing this. approval bug is #343
