### ISSUE TITLE
Some people don’t understand what a meme is

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/Advocacy#338]
Hi,

We’ve got feedback from French-speaking Firefox users who’ve seen the snippet on about:home and did not understand what a meme (mème in French) is and thought we made a typo. I figured you might be interested in knowing that or would have ideas on how we can improve the situation.
Or maybe we’re okay if those people don’t get it? I don’t know.

mème is an anglicism, and the only translation possible in French. Other locales might be affected the same way, and I’m also wondering what’s the number of English speakers that don’t understand what a meme is (you would know better than me).

So far in the French community, we’ve had few ideas to mitigate the issue:
- Replace meme with internet meme (in the French translation), to help people get the context
- Add a link to https://fr.wikipedia.org/wiki/M%C3%A8me_Internet on the word meme
- Add a section “What’s a meme?” with examples somewhere on the website

wdyt?

**Comment by brettgaylor** [comment]
I like "Internet meme", which we actually use in the "meme jail" video.  This also helps from a legal perspective as it covers both the uses of creation and distribution of those images.

**Comment by TheoChevalier** [comment]
Thanks, Brett 👍  I’ve updated a few strings on Pontoon. That should be enough to close this
