### ISSUE TITLE
Arrange press embargo

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/Advocacy#339]
This ticket will help us get everything in order for the TC / Phase 2 embargo opportunity.

Current plan of action + dates below. @brettgaylor, let me know if something seems amiss.
- [x] EOD Tuesday, Sept. 13: Send links + pws for all three videos to reporter. 
- [ ] EOD Wednesday, Sept. 14: Settle on time (before end of week) for Brett and Kevin to screenshare Post Crimes with reporter
- [x] Clearly communicate publication timeframe. Currently, planning to stage content on Sept. 19 but not publicly share anything until Sept. 20 at 8 a.m. GMT. <-- @brettgaylor, sound about right? 

cc @HPaulJohnson 

This ticket is a child of #319 dependent upon work in #330.

**Comment by KevZawacki** [comment]
Hi @brettgaylor, I believe we have all our videos ready to share? :-)

[Explainer](https://vimeo.com/181158635)
[CSI: GIF](https://vimeo.com/182474169)
[Meme Jail](https://vimeo.com/181569229)

If the above linked versions are the latest, I'll go ahead and share with our reporter this morning / afternoon.

**Comment by brettgaylor** [comment]
CSI: GIF still has more work to do.  We'll try and get you a cut by this
aft.

**Comment by KevZawacki** [comment]
Latest: All videos sent to Natasha. We've asked her to confirm whether or not she's interested in the embargo by COB.

**Comment by KevZawacki** [comment]
No word from TechCrunch -- we're free to do as we like.
