### ISSUE TITLE
Maker Party: Set up SSL for Nationbuilder pages

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#340]
Detailed description of work:
@cadecairos - Nationbuilder has requested that we follow the steps on the following pages to set up our SSL for the Maker Party pages on NB. Can you please have a look and confirm that these are the correct steps when using a custom domain? 
- https://3dna.nationbuilder.com/saml_with_nationbuilder_sso
- http://nationbuilder.com/integrate_single_sign_on_with_your_nation

Please let me know if we need any direct support from NB on this. 

_Start date: September 12, 2016_ 
_Due date: September 16, 2016_ 

CC: @simonwex @ScottDowne @valianttry

**Comment by cadecairos** [comment]
I got in contact with NationBuilder last Friday and had them enable SSO for our nation.

I've gotta file a servicenow request to continue setting it to work with OKTA. My understanding is that once it's set up, all mozillafoundation and mozilla emails in the system will require SSO for login. other accounts will use regular nationbuilder account logins.

**Comment by cadecairos** [comment]
... But I don't see what that has to do with SSL on maker party? did you mean SSO?

**Comment by damiankay** [comment]
You're amazing - thank you @cadecairos ! 

I imagine we'll need an SSL cert for our custom domain that will point to the Maker Party pages living on Nationbuilder. Please ping me if I'm confused (wouldn't be surprised). 

Thanks

**Comment by a-kilroy** [comment]
Can we change the name of this ticket to SSO?

**Comment by cadecairos** [comment]
> I imagine we'll need an SSL cert for our custom domain that will point to the Maker Party pages living on Nationbuilder. Please ping me if I'm confused (wouldn't be surprised).

So this ticket doesn't have anything to do with the SSO stuff I'm trying to set up. As for SSL for makerparty, once I have the domain I'm waiting on I  will point it at NationBuilder, then we need to ask them to set it up with SSL.

**Comment by damiankay** [comment]
Awesome - thanks @cadecairos 

Any updates on the domain purchase? Would you mind checking in on progress?

**Comment by cadecairos** [comment]
@damiankay It's been purchased!

**Comment by cadecairos** [comment]
@damiankay just an FYI, we can share out `makerparty.community` as the url, but because of the limitations of NationBuilders custom domain capabilities, the site will ultimately need to live at `www.makerparty.community`

**Comment by cadecairos** [comment]
Also, I'm ready to get in touch with NationBuilder to set up the URL for makerparty with SSL, I'll do that tomorrow.

**Comment by damiankay** [comment]
That's great! Thanks @cadecairos 

So, I'm guessing that we'll just redirect `makerparty.community` to `www.makerparty.community`

Seems so strange that NB doesn't support the URL without a subdomain.

**Comment by cadecairos** [comment]
I've emailed Dana asking her to kickoff the setup process for SSL on the custom domain.

**Comment by damiankay** [comment]
Done - thanks @cadecairos
