### ISSUE TITLE
Copyright Email 1 KICKER QA

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#341]
Detailed description of work: Please review copy, links, images and rendering in emails. GB,DE,ES,FR,PL and put comments/edits in this ticket.

_Start date: September 12, 2016_ 
_Due date: September 13, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by valianttry** [comment]
@stephaniemcv I noticed a couple of issues:
- We didn't update the number of signatures in the English version to be translation, so it has been literally translated from "X amount of people signed on" in our target locales.
- The sentence "Please click here to sign the petition." and the correspondending translations should be linked to the petition. 

I'll ask Kontextor to fix the "X amount of people" issue now.

**Comment by valianttry** [comment]
@stephaniemcv is it hard to make the header images clickable to the petition? If we can let's do that. No need for a resend because all messages are approved!

PL is 👍 
FR is 👍 
ES is 👍 
EN is 👍

**Comment by valianttry** [comment]
DE is 👍

**Comment by stephaniemcv** [comment]
Excellent! I will schedule this to send tonight, at midnight PST
