### ISSUE TITLE
Copy activities to Thimble so they can be easily forked and localized

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#342]
Detailed description of work: Filed from https://github.com/MozillaFoundation/Advocacy/issues/217

I believe I need to copy the code from a bunch of maker party activities and put it into thimble.

_Start date: September 13, 2016_ 
_Due date: September 14, 2016_ 

CC: @HPaulJohnson @chadsansing @damiankay 

I also don't have a list of the activities in one spot. Could that be clearly defined in one reference point so I don't get confused or miss something?

**Comment by chadsansing** [comment]
@ScottDowne - how's this?
- https://chadsansing.github.io/eu-maker-party-sample-activites/activity01-meme-around.html
- https://chadsansing.github.io/eu-maker-party-sample-activites/activity02-contribute-to-the-commons.html
- https://chadsansing.github.io/eu-maker-party-sample-activites/activity03-startup-salon.html
- https://chadsansing.github.io/eu-maker-party-sample-activites/activity04-dont-break-the-internet.html
- https://chadsansing.github.io/eu-maker-party-sample-activites/activity05-copyright-forum.html

**Comment by ScottDowne** [comment]
@chadsansing amazing! thank you.

**Comment by chadsansing** [comment]
@ScottDowne - cool. Conversely: https://github.com/chadsansing/eu-maker-party-sample-activites

**Comment by ScottDowne** [comment]
@chadsansing @HPaulJohnson @damiankay Done.

The source lives here:
https://thimble.mozilla.org/en-US/user/scott/499655

Links to the actual projects are here:
https://thimbleprojects.org/scott/99495/activity01-meme-around.html
https://thimbleprojects.org/scott/99495/activity02-contribute-to-the-commons.html
https://thimbleprojects.org/scott/99495/activity03-startup-salon.html
https://thimbleprojects.org/scott/99495/activity04-dont-break-the-internet.html
https://thimbleprojects.org/scott/99495/activity05-copyright-forum.html

**Comment by damiankay** [comment]
Awesome! Thanks @ScottDowne (& @chadsansing )

**Comment by damiankay** [comment]
@ldecoursy I'm guessing you'll need these links to the Thimble-based activities for the Maker Party host pack. 

CC @HPaulJohnson

**Comment by ldecoursy** [comment]
@damiankay I think we'll just link to the Maker Party landing page - the activities will live there, right?

**Comment by damiankay** [comment]
Yes they will @ldecoursy - sounds good
