### ISSUE TITLE
Poster Images for v2 petition site

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#344]
Detailed description of work:
Create larger hero poster image for explainer video. 
Create poster images for CSI gif and meme jail. All images should be @ 1x and @ 2x.

_Start date: September 13, 2016_ 
_Due date: September 14, 2016_ 

CC: @brettgaylor @beccaklam @natalieworth  @damiankay

**Comment by lovegushwa** [comment]
@beccaklam can you add the 1x and 2x dimensions for the hero poster and inline content poster images here:

**Comment by lovegushwa** [comment]
@natalieworth you are the poster master. Can you create posters OR if you don't have time provide links to high res videos and @beccaklam can make them?

**Comment by natalieworth** [comment]
@lovegushwa @beccaklam  I can do this while I'm working on exporting the videos! 👍

**Comment by beccaklam** [comment]
@lovegushwa @natalieworth 
The Desktop/Tablet inline video dimensions: 
1X - 240 x 150
2X - 480 x 300
The Mobile inline video dimensions:
1X - 290 x 200
2X - 580 x 400

Hero Poster Dimensions:
1X -
Mobile: 320 x 439
Tablet: 768 x 896
Desktop: 1200 x 612

2X:
Mobile: 640 x 878
Tablet: 1536 x 1792
Desktop: 2400 x 1224

I'll work on the hero posters this morning :)

**Comment by beccaklam** [comment]
@lovegushwa @natalieworth I put the files and exports on the drive in this folder: https://drive.google.com/drive/folders/0BzuBOR2VJQqUaWFmM1JzeVZuakE?usp=sharing. I did the hero image posters and the inline posters for _A Meme Is Born_ (not sure if the crop is what we're looking for though maybe @natalieworth should take a look and see if it can be improved).

**Comment by natalieworth** [comment]
poster options for CSI:GIF are here: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0dkN0ZG56QWpZMzQ

**Comment by damiankay** [comment]
Great! Can I share this link with Fission @natalieworth ?

**Comment by natalieworth** [comment]
@damiankay hey sorry just saw this, yes! @lovegushwa should we confirm the one your using?

**Comment by damiankay** [comment]
It's ok @natalieworth - I think I should wait until all of the assets are ready

**Comment by natalieworth** [comment]
poster options for MEME:JAIL are here: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0WGhiYTNuZlhDd3c

**Comment by natalieworth** [comment]
And final poster options for the 1st video are here: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0c2hUaVNMQTNOaWs

**Comment by natalieworth** [comment]
https://redpen.io/p/urf0c9384cfd0967dc

**Comment by lovegushwa** [comment]
@damiankay https://drive.google.com/drive/folders/0B2qu3ExKWIlveERLaXdDM1RULWc?usp=sharing
Not super happy with how these work under the large play button so we may need to tweak in QA (probably give the play button some transparency or change the scale.) ... Should be good enough to get Fission building.

**Comment by damiankay** [comment]
Thanks @lovegushwa - sorry you're not happy with them! We'll figure it out.
