### ISSUE TITLE
Maker Party: Launch plan

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#345]
Detailed description of work:
Align on launch plan and make sure resources are in place across teams to ensure synchronized launch of the following:
1. Maker Party pages on learning.mozilla.org
2. Maker Party pages on Nationbuilder
3. Activities in Thimble pages
4. On-boarding materials & Host pack

The common understanding is that we will deploy all of these to production / public-facing pages on the afternoon of September 20th (EST). 2pm EST might be a good time to aim for in case there are last minute fixes or changes required by the dev teams.  

_Start date: September 13, 2016_ 
_Due date: September 20, 2016_ 

CC: @hannahkane @ldecoursy @ScottDowne @simonwex @cadecairos @valianttry @geroter @jendc123

Reference: #332

**Comment by hannahkane** [comment]
cc @alanmoo

**Comment by damiankay** [comment]
CC @KevZawacki

**Comment by damiankay** [comment]
[Updated campaign milestones](https://docs.google.com/spreadsheets/d/1sHNiPi3Gzv3p55c_av9lW31Qp_r10TJmK9w8KXdP2_g/edit#gid=0)

Soft launch and pre-populating with trusted hosts: Sep 29
- dependent on localization being complete. [Localization schedule](https://docs.google.com/spreadsheets/d/1dBARa2Pr9NB_Q5ZdPOV1Jx9NOLbATSPk3etSfCWHTkk/edit#gid=0)

Launch for general public: Oct 3
