### ISSUE TITLE
Petition V2: Confirm snippet launch date

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#346]
Detailed description of work:
Fission is behind schedule, and needs some additional time to integrate all of our V2 designs. I've discussed this with @brettgaylor and @lovegushwa and they are OK with the following staged rollout plan: 
- Sep 20: We launch with new styling and content, including media
- Sep 22: We launch the updated form and complex animations

Snippet launch date is not confirmed yet. Do we want to delay snippet until the 22nd or stay with Sep 20th as planned? Will this affect other comms? 

The good news is we can use this as a test to compare the original form with the new form style. 

CC: @HPaulJohnson @shaghdoosti @valianttry @KevZawacki

**Comment by KevZawacki** [comment]
Comms isn't dependent on snippet, so OK by me if they launch separately. 

@damiankay, to clarify: The videos + Post Crimes would be live on changecopyright.org late PT on Tuesday, Sept. 20, and we could pitch Wednesday, Sept. 21? Thanks!

**Comment by damiankay** [comment]
@KevZawacki yes, that's correct RE videos and Post Crimes live on the 20th. I'm going to have another conversation with Fission today and will provide a more detailed update / explanation & solid assurance, but that's what they communicated to me.

**Comment by damiankay** [comment]
@KevZawacki Fission has confirmed that we'll be able to start our QA on the morning of Sep 19. It's much tighter than I'd hoped (QA was supposed to start tomorrow), but all of the new content and media should be live on Sep 20.

**Comment by KevZawacki** [comment]
@damiankay Sounds good! Thanks for the updates.

**Comment by damiankay** [comment]
@HPaulJohnson can you update and close this ticket when we've settled on a snippet launch date with the snippet team? Thx

**Comment by HPaulJohnson** [comment]
Still waiting for final feedback from snippet team on these: 

https://redpen.io/p/rz561278e5fb3ca36f

Pressing to have this in by Monday (9/19) and shipped to localizers. May need to adjust the launch by a day or so to accommodate these delays.

**Comment by HPaulJohnson** [comment]
@damiankay @valianttry can i get a final lists of locales that we will be launching v2 petition in? i need this to do the asset handoff to the snippet team.

**Comment by damiankay** [comment]
@HPaulJohnson - I mis-spoke in our meeting today. DE, ES, FR, PL, BG & IT are complete. CS and NL communities have said they will be done by this evening, but Kontextor will still need to paste these into Bablic. 

FYI, I've added the localization tracking spreadsheets to our Wiki page for easy access.

**Comment by HPaulJohnson** [comment]
Great, thank you. We'll get all of these queued up then. Except, PL - doesn't look like they are working on the new versions of the snippet so we won't have anything for that locale this round.

**Comment by HPaulJohnson** [comment]
Snippet launched on Thurs 9/27.
