### ISSUE TITLE
EU Websites: EU Cookie law compliance

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#348]
Detailed description of work:
EU websites are required to gain permission from users to set cookies in their browser. This can be 'implied consent' which may be covered by our privacy policy, but we should at least mention "cookies" in our privacy link. With our public stance on privacy and tracking, we should probably be more explicit about it. 

[Read more here](http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm)
[and here](https://econsultancy.com/blog/63118-17-useful-examples-of-eu-cookie-law-compliance/) < includes references

@lovegushwa how would you feel about adding a banner of some sort? 

Flagged by @a-kilroy 

_Start date: September 14, 2016_ 
_Due date: October 03, 2016_ 

CC: @valianttry @brettgaylor @HPaulJohnson

**Comment by valianttry** [comment]
@damiankay can you link to the ticket where we are documenting the cookies and changes we plan to make? Related work i suspect.

**Comment by damiankay** [comment]
@valianttry it's here: https://github.com/MozillaFoundation/mofo-devops-private/issues/30#issuecomment-247099205

It's a private repo, so not sure that everyone has access

**Comment by valianttry** [comment]
I have sent this question to our legal team. Will update with their response.

**Comment by lovegushwa** [comment]
@valianttry any design work needed here?

**Comment by valianttry** [comment]
Closing, next steps are in #545
