### ISSUE TITLE
iFrame embed of form only

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#349]
Detailed description of work:
We are building a microsite for this campaign that needs to embed the form for our petition.

It feels like it will be burdensome and bad UX to embed the entire site at changecopyright.org - is it possible to embed only the petition via a URL?

Or, within the CMS, is it easy for us to spin up a page that _just_ has the petition?

Any help appreciated here!

**Comment by damiankay** [comment]
Flagging this for @jendc123 and @gholme4

**Comment by gholme4** [comment]
@damiankay @brettgaylor Hi. We could accomplish this using the same page with some creative JavaScript and CSS.

**Comment by brettgaylor** [comment]
Thanks for the fast response, @gholme4 !

Could you help me co-ordinate tomorrow w/ the developers building that site?  Would we use a standard `<iframe>`embed?

**Comment by gholme4** [comment]
@brettgaylor Of course. I can talk to those developers. What I have in mind involves JavaScript inserting an iframe dynamically.

**Comment by brettgaylor** [comment]
We've decided not to take this approach.
