### ISSUE TITLE
Write rapid response video script

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/Advocacy#351]
Draft script [here](https://docs.google.com/document/d/1pXMKnwTUkoOtmMSIYtBJrHR2sOqZf0sxtMrYmjZPh3s/edit). 

Includes copy, possible graphics, suggested music. Currently localized into EN, DE, FR, and ES. (Polish agency only translated select portions of the blog, so we don't have PL source material.)

If we need to shorten, we can drop scene 6.

@brettgaylor @natalieworth

**Comment by natalieworth** [comment]
Thanks @KevZawacki . I'm just working on putting together a really rough (rapid? :D) cut with images this afternoon.

**Comment by KevZawacki** [comment]
Next steps:  Approval. 
- [x] Sign off from Chris & Raegan
- [x] Sign off from Mika (Kevin has sent)

cc @brettgaylor

**Comment by KevZawacki** [comment]
@brettgaylor @natalieworth 

All approvals in order! Let me know if I can help with anything further.
