### ISSUE TITLE
Maker Party: Engage DEG to set up email triggers

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#353]
Detailed description of work:
Hi @stephaniemcv - could you please contact DEG to see if they can set up the email triggers for Maker Party as per our meeting today? 

[Email triggers reference](https://docs.google.com/spreadsheets/d/1GWc5r4ughhsnlw_YVuZeo-CPMl9m2xaXUVCkPYeLEEA/edit#gid=543547330)

_Start date: September 15, 2016_ 
_Due date: September 22, 2016_ 

CC: @valianttry @shaghdoosti

**Comment by damiankay** [comment]
CC @a-kilroy @geroter

**Comment by stephaniemcv** [comment]
Need some specifics to kick off the project with DEG. Are these expected to be text or html emails? If html, has there been a template designed that we can create code around? ETA when text would be finalized?

**Comment by damiankay** [comment]
I think @shaghdoosti might know the answers to those questions...

**Comment by geroter** [comment]
1) HTML

2) We don't have a design for these -- @damiankay  ... should be super-simple. Could you get a designer to spend a bit of time on this?

**Comment by damiankay** [comment]
@stephaniemcv - does DEG also usually create the designs? Or do we give them a basic template and they take it from there?

**Comment by stephaniemcv** [comment]
We usually give them a PSD file. Then they build the code around that. If it's just some logo or color change to something we already have, I can do that.

**Comment by stephaniemcv** [comment]
Here is some documentation DEG recently put together: https://docs.google.com/presentation/d/1CVrg7W7p_PLStQnlM8uLi-AN2ogZgzXedl5Ez2fCbCY/edit#slide=id.p

**Comment by damiankay** [comment]
Thanks very much @stephaniemcv . 

@lovegushwa - do any of our designers have bandwidth for this today / early next week?

**Comment by cristina-moon** [comment]
@shaghdoosti assigned me to write the first drafts of the triggered email copy and I'm to deliver them by COB on Monday 9/19. Does that work for you @stephaniemcv @damiankay ?

**Comment by damiankay** [comment]
Yes, thanks @cristina-moon . We can start working on the templates independent of the copy.

**Comment by stephaniemcv** [comment]
👍

**Comment by valianttry** [comment]
Triggered emails are beingi sent using Nationbuilder. Closing.
