### ISSUE TITLE
Copyright: create copy for postcard emails

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#354]
Detailed description of work: @cristina-moon
Will create email based around collateral provided by @brettgaylor with CTA to watch video
**Send Date: 10/13**
_Start date: September 16, 2016_ 
_Due date: September 30, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by cristina-moon** [comment]
First draft of email copy is [here!](https://docs.google.com/document/d/1by3nYfSlPGQhbw_EsMZouO7itLjokYuGqB3aSy3WkiY/edit)

**Comment by cristina-moon** [comment]
Postcard email draft approved by Brett. @valianttry @shaghdoosti ready for your approvals/feedback, too!

**Comment by brettgaylor** [comment]
@cristina-moon @stephaniemcv I'm wondering if we should update this to have some urgency when we send - we'll be pretty close to our target and this email will likely push us over the edge, which could also give us a mini "victory" which might be nice to celebrate somehow.

cc @valianttry

**Comment by valianttry** [comment]
@brettgaylor or @stephaniemcv can you close this if this email drafting is completed?

**Comment by stephaniemcv** [comment]
It looks like it never made it through review. Since we're doing the postcard mailing at MozFest, we've probably run out of time to finish review, get through localization and send by MozFest. 

Based off our email convo @brettgaylor, I'm ok with removing this email completely from our calendar, and not pushing back to an alternate send date as we're running into Maker Party and EOY. 

@brettgaylor, thoughts?

**Comment by brettgaylor** [comment]
Yes, we have passed target and are having challenges with delivering what we have.  Lets cancel this send.

**Comment by cristina-moon** [comment]
Did I drop the ball on updating the email copy?

www.cristinamoon.com
917.488.0302

**Comment by stephaniemcv** [comment]
No. No one was explicitly named to walk the email through policy/advocacy
review. I assumed it was Brett since he's the signor, and that's what Sara
does when she's the signor. I should have confirmed that.

Also, Brett's having trouble with the postcard site and didn't to direct a
lot of traffic there.
