### ISSUE TITLE
Scope work required to move SF integrations to Basket

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#355]
Detailed description of work:
Investigate whether it makes sense to move to Basket by first scoping work required. 

Damian to set up a scoping meeting with the following stakeholders:
@pmclanahan has been identified as the most knowledgeable Re Basket
@ScottDowne to represent Advocacy
@drewmoto to represent Lifecycle Marketing

See #80 for background reading

_Start date: September 19, 2016_ 
_Due date: September 30, 2016_ 

CC: @valianttry @stephaniemcv

**Comment by valianttry** [comment]
@ScottDowne OK to close this?

**Comment by ScottDowne** [comment]
Yeah, we can close. Things don't seem to be blowing up without basket right now anyway, so we might not even need this anymore.
