### ISSUE TITLE
Maker Party: Build basic HTML email template

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#356]
Detailed description of work:
We need to build an HTML email template for the triggered emails that will be sent to Maker Party hosts and attendees. We can just use placeholder copy as it's still being developed. 

Here is some documentation DEG recently put together: https://docs.google.com/presentation/d/1CVrg7W7p_PLStQnlM8uLi-AN2ogZgzXedl5Ez2fCbCY/edit#slide=id.p

See #353 for reference

_Start date: September 16, 2016_ 
_Due date: September 20, 2016_ 

CC: @lovegushwa @stephaniemcv @beccaklam @natalieworth @shaghdoosti

**Comment by lovegushwa** [comment]
I recommend we use one of these templates. We can add some maker party branding to the images OR add the maker party logo to the header. I'll mock something up. 
<img width="796" alt="screen shot 2016-09-18 at 8 58 56 pm" src="https://cloud.githubusercontent.com/assets/12228435/18622374/1f4d000e-7de3-11e6-8bcf-d5c9766ba840.png">
<img width="797" alt="screen shot 2016-09-18 at 8 57 42 pm" src="https://cloud.githubusercontent.com/assets/12228435/18622373/1f4856d0-7de3-11e6-8b28-72981849621a.png">

**Comment by damiankay** [comment]
I think these will be great for the Maker Party emails @lovegushwa 

Are you able to Maker Party-ify these today (Monday)?

CC @shaghdoosti

**Comment by lovegushwa** [comment]
@damiankay yes, I can sort these out today.

**Comment by lovegushwa** [comment]
@stephaniemcv here are my recommended templates:

<img width="921" alt="screen shot 2016-09-19 at 2 58 54 pm" src="https://cloud.githubusercontent.com/assets/12228435/18650470/0f262b50-7e7a-11e6-9582-acafce3d159d.png">

<img width="689" alt="screen shot 2016-09-19 at 3 02 57 pm" src="https://cloud.githubusercontent.com/assets/12228435/18650485/2be3f75e-7e7a-11e6-8664-59e101e58315.png">

**Comment by lovegushwa** [comment]
@stephaniemcv ok here are the assets you need to build the template, I'm including a general maker party branded banner image for both templates: 

https://drive.google.com/drive/folders/0B2qu3ExKWIlvOVlyTkRDTXE2cVE?usp=sharing

CC @damiankay @shaghdoosti
