### ISSUE TITLE
Maker Party: Setup email for press and support inquiries

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#357]
Detailed description of work:
The "Press" and "Contact Us" links on the new Maker Party pages need somewhere to point to. In each case, we'll point to email addresses.

In the case of support/contact us, we have an existing email makerparty@mozilla.org. Just need to hunt down credentials and hook it into Desk.com. @shaghdoosti & @chrislarry33 to figure out who will be managing this support queue during the campaign.

For press, I need to have a new alias created via service now and will update here when that's available. @KevZawacki and I can monitor that email directly and it doesn't need to go through desk.

_Start date: September 15, 2016_ 
_Due date: September 21, 2016_

**Comment by ldecoursy** [comment]
cc @lucyeoh 

@HPaulJohnson can you confirm if it's @mozilla.org or @mozillafoundation.org? We'll list that email in the host pack.

**Comment by HPaulJohnson** [comment]
@ldecoursy unless you know, i'm trying to track down confirmation from Amira. In blog posts from 2015, it is listed as makerparty@mozilla.org so that's what i'm assuming it is. 

For press inquiries we are going to use the main press@ for all of Mozilla, which is press@mozilla.com

**Comment by ldecoursy** [comment]
@HPaulJohnson I don't - I sent a test email to it on Friday but haven't heard back that anyone has received it.

**Comment by LucyeoH-zz** [comment]
So at some point I believe that address went to my foundation email which
is no longer active.

Lucy

**Comment by ldecoursy** [comment]
@shaghdoosti @chrislarry33 Any decisions about who should manage general support queue per @HPaulJohnson's comment above? We should get the email setup ASAP.

**Comment by HPaulJohnson** [comment]
@amirad was able to help locate access to email distro for makerparty@mozilla.org

@damiankay we should update the links on the site for both this and press using: 

Press: press@mozilla.com
Contact Us: makerparty@mozilla.org

In both cases, these links should be a mailto: link and open up email window with these addresses prepopulated. 

@ldecoursy we still need to identify who will monitor contactus box and be responsible for support. When that's figured out I can provide credentials for email alias.

**Comment by damiankay** [comment]
CC @jendc123 gholme4

Please see the updated email addresses for the Maker Party site:
- Press: press@mozilla.com
- Contact Us: makerparty@mozilla.org

**Comment by HPaulJohnson** [comment]
We should also update the "Partner with Us" link on https://learning.mozilla.org/en-US/events to point to this: 

https://drive.google.com/file/d/0B3P4kAmkrxtCXzVMZG5qUDVhX3c/view

**Comment by damiankay** [comment]
@hpauljohnson would you mind adding those to the UAT spreadsheet if you're logging other comments there? Thanks!

**Comment by ldecoursy** [comment]
Instead of makerparty@mozilla.org another option is pointing people to the Maker Party thread on the Mozilla Learning forum - see https://forum.learning.mozilla.org/t/maker-party-2016/1116

Thoughts @chrislarry33 @shaghdoosti @LucyeoH ?

**Comment by jendc123** [comment]
@damiankay we have updated Contact Us with makerparty@mozilla.org.  Currently we don't have a "Press" or "Partner with Us" footer item. 

<img width="881" alt="footer" src="https://cloud.githubusercontent.com/assets/6034476/18649118/c7017606-7e8b-11e6-971e-6c64431e1b28.PNG">

**Comment by HPaulJohnson** [comment]
@jendc123 "Press" and "Contact Us" are in the footer/bottom section on these pages:

https://learning.mozilla.org/en-US/events

and 

https://learning.mozilla.org/en-US/events/resources

These pages don't have the same footer but need those links updated.

**Comment by HPaulJohnson** [comment]
makerparty@mozillafoundation.org and press@mozilla.org should be implemented everywhere.
