### ISSUE TITLE
Copyright Petition: Optimize for faster load times

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#358]
Detailed description of work:
Our Petition page on Nationbuilder is currently rating very poorly in terms of load times. Some of this is no doubt due to Bablic, but we should take any measures possible to reduce load times, as it affects the effectiveness of our paid social and organic search

@cadecairos @ScottDowne - can you identify what measures can be taken to optimize the page load? 

_Start date: September 16, 2016_ 
_Due date: September 21, 2016_ 

CC: @HPaulJohnson @valianttry

**Comment by ScottDowne** [comment]
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.changecopyright.org%2F&tab=desktop

So, based on that, we're getting an 80/100 for desktop and 59/100 on mobile. It's also a list of things that can speed up our page.

So we should consider fixing red for desktop and/or our mobile, depending on our metrics.

Figuring out which red tasks are reasonable in NationBuilder is probably the next step, and that's a lot harder to answer. I'll need to dig, and it's also likely FIssion gets pulled in for some of these, once I have specific tasks.

@damiankay does the above sound like a plan?

**Comment by ScottDowne** [comment]
For Desktop:

Below the fold page blocking resources. This may be huge. A thing I notice almost right away is this page's above the fold is nothing but CSS to make the whole page grey, while it translates. So all css and js can be loaded in async (or at the bottom of the page), which should shave off quite a bit of time. It means we'll get to the act of loading the translations much sooner.

We should optimize images, as I don't think that's blocked by anything. Just run them through compression, and reupload, where applicable.

The browser cache and compression might be harder, and less valuable. I probably would P2 those. However, if NationBuilder can minifiy stuff, we should. If not, let's not worry either.

For mobile, it's pretty much the same deal, apparently.

**Comment by damiankay** [comment]
Hey @ScottDowne - do you have time to work on this today? I'm not sure if you're able to make changes, or simply make a list of recommendations for Fission / NB, but either way, it would be great to get started on this work because our load times are much too long. Thx!

**Comment by brettgaylor** [comment]
This score seems to now have gotten worse  - we are now 56/100 on desktop

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.changecopyright.org%2F&tab=mobile

@ScottDowne is the above the fold issue related to nation builder?  The template?

**Comment by ScottDowne** [comment]
Optimize images has moved from consider fixing, to should fix. This is likely the cause of our new score.

v2 probably uses more images than v1, or more un optimized images, and is now considered a significant gain if optimized. Note, this has to be done for every image, and every new image. It's not something we can turn on and off. "Optimize the following images to reduce their size by 262.2KiB (82% reduction)." There is a clear list of the images that we should optimize in the google speed test. That gain however, is less than a MB.

@brettgaylor @valianttry me and damian talked to Fission about minification and below the fold css Tuesday, and they were both implemented some time between now and then by Fission.

**Comment by brettgaylor** [comment]
@lovegushwa @natalieworth @beccaklam do y'all thing we can optimize the images?

@ScottDowne @jendc123 @gholme4 - Still seeing some warnings from Google related to above the fold content here:

"Eliminate render-blocking JavaScript and CSS in above-the-fold content" - page requires all those resources to load before displaying content.  Any further optimization possible?  Those scripts and CSS seems to need load before Bablic can localize the page.

**Comment by gholme4** [comment]
@brettgaylor @ScottDowne I spent time today and yesterday working on this. Now there is only one file I have control over that is render-blocking because it helps the ATF content appear quickly. I also replaced the images with the optimized versions @lovegushwa provided.
