### ISSUE TITLE
Add user's name to thank you page

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#362]
Detailed description of work: Migrated from https://github.com/mozilla/donate.mozilla.org/issues/1052

When we submit a donation, we have the user's name, and we can easily enough display it in the thank you page: "thank you Scott for your donation"

_Start date: September 16, 2016_ 
_Due date: Jan 1, 2016_

**Comment by valianttry** [comment]
@ScottDowne is this something design needs to help out with? This could also be a part of our improved "thank you page experience". #407

**Comment by ScottDowne** [comment]
It's probably pretty simple and I think design is not needed.

**Comment by lovegushwa** [comment]
@ScottDowne I believe @beccaklam addressed this in #623 ... can we close this?
