### ISSUE TITLE
A/B Test: move frequency radio buttons above amount buttons

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#363]
Detailed description of work:

Migrated from: https://github.com/mozilla/donate.mozilla.org/issues/1033

Possibly related: https://github.com/mozilla/donate.mozilla.org/issues/1090

We should run a test for this: https://donate.mozilla.org/en-US/?test=frequency-move-test

_Start date: September 16, 2016_ 
_Due date: Jan 1, 2016_

**Comment by ScottDowne** [comment]
@vojtechmzl how likely is it that we could run this test soon?

**Comment by valianttry** [comment]
Assigning to @vojtechmzl to triage against other tests we want to do.

**Comment by ScottDowne** [comment]
This test should help with our auto downgrading issue. I consider it high
priority.

**Comment by vojtechsedlak** [comment]
Now that the snippet test is complete, I can set this up in Optimizely and we can run it asap. I will loop you in for QA @ScottDowne

**Comment by vojtechsedlak** [comment]
The results of this test are inconclusive, although there is a UX preference for having the frequency selectors above amount buttons. A ticket is being filed on the donate.mozilla.org repo to make this happen.
