### ISSUE TITLE
Setup Paypal micropayments account

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#367]
Detailed description of work:

Migrated from https://github.com/mozilla/donate.mozilla.org/issues/870

Status, we should have the account good to go, but it never got setup in time.

We have a breakpoint, where the charge on a donation is higher or lower, depending on which account to go to.

So figure out that breakpoint, by looking at historical data.

Then implement the breakpoint in our donation platform.

_Start date: September 16, 2016_ 
_Due date: Jan 1, 2016_

**Comment by ScottDowne** [comment]
I need to get historic transactional data, and our current account fees. Once I have those, I can figure out our breakpoint, which is where we determine which account, regular or micro, to send the payment.

I'm also going to need the micro payment account ids. Once I have micro payment account ids, and the breakpoint, I can plug them into some logic I need to write, that handles this. This is going to be configurable, so we can change and tweak the breakpoint, so for now, I'm not blocked on this.

I suspect I need a bit of help from @cadecairos getting some of the data. At the very least he can point me in the direction of some of this.
- [x] Create logic that switches between accounts depending on the breakpoint value.
- [x] Get some transactional history.
- [x] Get current account fees for both our standard account and our micro payments account.
- [x] Run the transactional history through these account fees, and tweak the breakpoint until we get a good idea as to what breakpoint saves the most.
- [x] Get micro payments account ids
- [x] Plug the micro payments account ids and breakpoint into the configuration data.
- [x] profit. literally.

**Comment by ScottDowne** [comment]
Updates:

I have a pull request here: https://github.com/mozilla/donate.mozilla.org/pull/1624 that adds this, it needs review. My guess is early next week.

Me and @cadecairos ran the history through this logic, and the numbers are solid.

**Comment by valianttry** [comment]
@cadecairos this will save us lots of monies. 😸

**Comment by valianttry** [comment]
@cadecairos and @ScottDowne can you finish and close this asap? Time is running out.

**Comment by ScottDowne** [comment]
Just an update. The first half landed today. It doesn't change anything, it's a refactor that reduces the complexity of this by a lot. The other half "pulls the switch" so to speak, and should land tomorrow if nothing blows up in the first half. Landing them sequentially like this is a bit easier if something goes wrong. I'll update this tomorrow and hopefully we can close this!

**Comment by valianttry** [comment]
I will connect with Alexei and Pamela today. As a heads up.

**Comment by ScottDowne** [comment]
This is now live and everything seems to be running smooth, I'm confident we can close
:rocket: :moneybag: :money_with_wings: :money_mouth_face:
