### ISSUE TITLE
Decision: Re-use Dapper Fox for EOY branding, or send him to an island paradise far far away?

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#369]
Detailed description of work:
I already started this conversation with @lovegushwa but we need to make decisions soon about EOY branding and design aesthetic. 

_Start date: September 1, 2016_ 
_Due date: October 14, 2016_ 

![pino_berrocal_on_twitter___i_just_donated_to__mozilla__because__ilovetheweb__how_about_you__https___t_co_8eloy3qnwe_https___t_co_lnwxrtqp6u_](https://cloud.githubusercontent.com/assets/9830371/18601024/a141fb8e-7c2e-11e6-99a3-9e16ab64a41a.png)

**Comment by lovegushwa** [comment]
@valianttry I need to have another conversation with Tim, he already said something like you should have a new brand to work with and won't need dapper fox. I wont be convinced until I see it. 

We need to pin down some dates, ideally when we would need to start seeing something like dapper (not until december? ... Social, spectacular snippet, email, and mozilla.org is where dapper starts showing up I believe.)

And then I need to get a commitment from Tim on the rebrand timeline if possible. We might even ask the branding agency to create some assets for us, with a bit of our guidance on whats worked best in the past.

**Comment by lovegushwa** [comment]
@valianttry so the word from Tim is "no foxes." ... A bit of a shame, cute stuff works well, but cute foxes also tie into the brand bank nicely. 

Let's talk about this, I have an idea about how we might do a bit of character design without dapper but will need to develop a reason why folks are seeing characters that are not foxes.
