### ISSUE TITLE
Codemoji graphics for external comms

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/Advocacy#37]
When we put the [Codemoji comms plan](https://docs.google.com/document/d/1iY6OkuVDSJgUx0QSuvjbIQpeRrb0SjPr81Kwyyd4jOA/edit) into action, we'll need a few images that capture the tool's essence, for use in blogs / pitching media.

@lovegushwa @natalieworth Do we have any snazzy screenshots? Ones that are both colorful + explanatory?

**Comment by natalieworth** [comment]
@KevZawacki @lovegushwa I was hoping too if we get time to experiment a bit with designs/ tools that we were hoping to improve on. This could be a good project to explore the DIY or short explanatory video style with simple type and music (w/o voice over), motion graphics, gifs, etc.?

**Comment by HPaulJohnson** [comment]
@natalieworth I love the idea of creating a very short "onboarding" .gif or video that shows off the joys of using codemoji. Could be 15 secs or so. 

Maybe not for the soft launch next week but would be good to have when we roll out more broadly. We can track this in #42 as it will likely be used in social media promos most heavily.

**Comment by KevZawacki** [comment]
Onboarding .gif would be awesome!

In the short-term, are we still on track for a basic, static image for next week's soft launch?

**Comment by KevZawacki** [comment]
@natalieworth Realizing we actually don't need this for soft launch -- only public launch. So, no rush!

**Comment by natalieworth** [comment]
@KevZawacki @HPaulJohnson Just to confirm, are social assets only needed for the public launch? Or are we needing anything for the soft launch next week? I've definitely got time to create some assets if needed :)

**Comment by KevZawacki** [comment]
@natalieworth We will need 1-2 social assets for the soft launch. The majority, though, can wait until the public launch.

**Comment by KevZawacki** [comment]
Hey there -- checking in to see if we're on track to have 1-2 basic social assets for the Thr./Fri. soft launch. Let me know if I can help.

**Comment by natalieworth** [comment]
@KevZawacki For sure! Just working on these today and will discuss with @lovegushwa when he's back tomorrow and then I'll post here :)

**Comment by KevZawacki** [comment]
??

[--- Commented from Asana.com
#commenter Damian Kuehn
---[aa]

**Comment by KevZawacki** [comment]
@natalieworth Hey! A couple developments.

-- With the soft launch postponed to next week, we don't need to rush these
-- We're also postponing social promotion in general to correspond with the public launch. So, we have another couple weeks to work on these :-)

**Comment by KevZawacki** [comment]
Hey @natalieworth @lovegushwa,

Looks like public launch will be Tuesday, June 28 -- think we're on track to have this ticket wrapped up before then?

**Comment by natalieworth** [comment]
I think this is a repeat of #42 —so going to close, but reopen if anything different is needed for this ticket.
