### ISSUE TITLE
Improve the IT donation form

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#373]
Migrated from https://github.com/mozilla/donate.mozilla.org/issues/816

In order to do this, we have some UI or l10n issues.

![snippet17](https://cloud.githubusercontent.com/assets/197334/11225221/05367e94-8d47-11e5-867d-1a8802fe1ff1.png)

The currency dropdown falls to the next line, and the text is pretty long.
![snippet18](https://cloud.githubusercontent.com/assets/197334/11225252/2c4657f2-8d47-11e5-8f89-3bb57f91a1aa.png)

The secure bit is too close to the text.
![snippet19](https://cloud.githubusercontent.com/assets/197334/11225265/39e54f9e-8d47-11e5-92d4-4dec4b145eaf.png)

![snippet20](https://cloud.githubusercontent.com/assets/197334/11225292/6b324214-8d47-11e5-93de-2405556b76b0.png)

_Start date: September 16, 2016_ 
_Due date: January 1, 2017_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by valianttry** [comment]
@ScottDowne since Italy is a priority locale, I'm cc @TheoChevalier and assigning this to @lovegushwa

**Comment by TheoChevalier** [comment]
Looks like flod found a potential solution for the title:

> Even something like this would look nicer (`padding.right: 115px` on the `<h3>`, `position: absolute; top: 0; right: 0;` for the `<span>`)
> 
> ![screenshot 2016-11-08 21 22 50](https://cloud.githubusercontent.com/assets/3644868/20115704/9429d29c-a5f9-11e6-8e2e-88d7bba3743d.png)

The secure bit seem fixed.

For the newsletter button, we can easily try allowing two lines + adding a horizontal padding?

For the snippet, if we can’t increase the width nor the height, that’s tricky.

**Comment by ScottDowne** [comment]
Two lines of text for all three of the unsolved issues works for me.

**Comment by TheoChevalier** [comment]
Alright, giving it a try
