### ISSUE TITLE
compare supported stripe currencies and paypal currencies

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#374]
If there is anywhere they don't match, consider disabling the paypal or stripe button, depending.

PayPal: https://developer.paypal.com/docs/classic/api/currency_codes/

PayPal supported currencies, we already accept most of these.

We are already pretty much using this list.

Stripe: https://support.stripe.com/questions/which-currencies-does-stripe-support

From there, US can accept Group 1 and Group 2

group 1: https://support.stripe.com/questions/which-currencies-does-stripe-support#currencygroup1
group 2: https://support.stripe.com/questions/which-currencies-does-stripe-support#currencygroup2

This is actually a pretty massive list of acceptable currencies.

With Stripe being much larger than PayPal, and our list being based on PayPal currently, we're likely in the position of missing out of currencies and not the opposite where we're accepting currencies we are not.

Migrated from https://github.com/mozilla/donate.mozilla.org/issues/456

_Start date: September 1, 2016_ 
_Due date: September 2, 2016_

**Comment by ScottDowne** [comment]
There are LOTS of stripe only currencies we're not currently supporting that PayPal does not. Supporting them would mean a stripe only form, which is what we're currently doing for https://donate.mozilla.org/en-US/?currency=inr, https://donate.mozilla.org/en-US/?currency=cny, and https://donate.mozilla.org/en-US/?currency=idr.

I suggest we go through Stripes group 1 and 2, and find any currencies we want to enable. Nothing new though.

group 1: https://support.stripe.com/questions/which-currencies-does-stripe-support#currencygroup1
group 2: https://support.stripe.com/questions/which-currencies-does-stripe-support#currencygroup2

It looks like paypal supports the Singapore dollar and we do not. I dunno if this is new, or we decided to not add it, but enabling it looks to be trivial.

The ones we add that are in countries we don't have locales for, likely offer very little.

If the list gets too long for usability reasons, we need to get some UX on it, but other than that, adding new currencies for Stripe only or Singapore dollar is super duper easy, I just need a list.

**Comment by valianttry** [comment]
adding @TheoChevalier as there will likely be additional L10N needed for new forms in new locales, even if they are Stripe only.

**Comment by TheoChevalier** [comment]
@valianttry We should be enabling new locales in #609 (more or less all the locales we can enable), I guess it should cover the need here? Or you’re talking about adding new strings?

**Comment by valianttry** [comment]
@ScottDowne can you add milestone here and next steps? I recommend prioritizing locales based on potential revenue, e.g. : 

![donations_by_country_2013_v_2014_-_google_sheets](https://cloud.githubusercontent.com/assets/9830371/20047208/c5b8046c-a466-11e6-973b-dd42bb3e7cdb.png)

**Comment by Matt-Holland** [comment]
I see that currently the donation page accepts:
$	usd
$	aud
$	ars
R$	brl
$	cad
CHF	chf
$	clp
¥	cny
Kč	czk
kr	dkk
€	eur
£	gbp
$	hkd
Ft	huf
Rp	idr
₪	ils
₹	inr
¥	jpy
$	mxn
kr	nok
$	nzd
₱	php
zł	pln
₽	rub
kr	sek
฿	thb
NT$	twd

... and in cases where the currency is not accepted by PayPal, the PayPal option disappears. 

@ScottDowne : can this ticket be closed?

**Comment by roseregina** [comment]
FYI, we've gotten several requests to support ZAR.

**Comment by ScottDowne** [comment]
We can add Zar via stripe.

**Comment by Matt-Holland** [comment]
I've opened ticket #674 for adding the ZAR currency, it seems like the original work for this ticket #374 is complete. Closing.
