### ISSUE TITLE
Custom thank you email for Paypal donors

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#376]
Migrated from: https://github.com/mozilla/donate.mozilla.org/issues/359

On our old system we send a thank you email for Credit Card donors via BSD, and the majority of donors using PayPal only receive the PayPal default transaction email.

We should use Salesforce for this, ideally.

_Start date: September 1, 2016_ 
_Due date: September 2, 2016_

**Comment by valianttry** [comment]
@ScottDowne related to #612 ? I think this might have to wait until next year given that the Salesforce email functionality is more involved.

**Comment by ScottDowne** [comment]
Yeah, we should do this in https://github.com/MozillaFoundation/Advocacy/issues/395
