### ISSUE TITLE
DRAFT EOY Fundraising email series for EU audience

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#377]
Detailed description of work:
Given all the outgoing communications about the Copyright Campaign in the EU, we should at least mention Copyright in our EOY fundraising appeals to that audience.

_Start date: November 1, 2016_ 
_Due date: November 10, 2016_

**Comment by valianttry** [comment]
**Examples of past fundraising appeals**

Encryption Campaign Fundraising email 1 of 1:
https://docs.google.com/document/d/1n7PkKT75hLcNzfwkb1ljaWESXSKI96Utn2vqgVOj-Ms/edit

EOY 2015 Fundraising Email Appeals Series:
https://docs.google.com/document/d/18eaF4c0eFR-5kyMGNIAQXRhCTIzprDWooWuoXYfRQO0/edit

**Comment by stephaniemcv** [comment]
EOY Production Schedule
https://docs.google.com/spreadsheets/d/1lCpUiBe5B19SASA53CRpkzTK7hrBnxRANTT0kkRZDGo/edit?ts=57e1f3b0#gid=4

**Comment by Matt-Holland** [comment]
Closing this ticket since the Email campaign is well underway and there are separate tickets for various email blasts.
@WillatMozFdn
