### ISSUE TITLE
 Build codemoji web app on learning.mozilla.org/codemoji 

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#38]
We expect delivery of final app from TODO early next week (week of 5/23) and we'll need to make it live on learning.mozilla.org/codemoji and do appropriate QA. We are aiming to send initial tests (via email) around 6/1. 

cc/ @ScottDowne @lovegushwa

**Comment by lovegushwa** [comment]
@cadecairos @ScottDowne this is the final codemoji hand off ticket

**Comment by cadecairos** [comment]
DevOps TODO:
- [x] ~~Add CNAME file to codemoji gh-pages branch - Value of `learning.mozilla.org`~~ Not needed.
- [x] Add a new Origin to the learning.mozilla.org cloudfront distibution, pointing at the github pages codemoji site
- [x] Add a behaviour to the learning.mozilla.org cloudfront distribution that serves the new origin as `/codemoji`
- [x] cheers

**Comment by abusedmedia** [comment]
Hi @cadecairos let me know when I can push the CNAME into gh-pages.

**Comment by cadecairos** [comment]
@abusedmedia you should be able to add it any time, it won't break anything to have it there.

**Comment by abusedmedia** [comment]
I've tried it few hours ago then removed since the app wasn't be reachable anymore replaced by the learning.mozilla.org website

**Comment by cadecairos** [comment]
Oh, interesting... I guess gh-pages is pretty agressive on this front. okay then..

What's the final gh pages endpoint URL? `https://mozilla.github.io/codemoji`?

**Comment by abusedmedia** [comment]
Actually is https://todotoit.github.io/codemoji/ because is under our github account... Do we need to transfer it?

**Comment by cadecairos** [comment]
@abusedmedia I spoke with @HPaulJohnson and we think a transfer is the way to go forward here.

Can you initiate a transfer of the codemoji repo to the "mozilla" Github organization?

**Comment by abusedmedia** [comment]
Sure, this account https://github.com/Mozilla right?
Btw I'd ask write access in case we should fixing something :)

**Comment by cadecairos** [comment]
yup, that's the one.

If we do transfer the repo, we'd need to update the mozilla version via pull requests. If that's too much I can just fork the repo and pull from your upstream repo if/when things get updated.

**Comment by abusedmedia** [comment]
pull requests are ok. 

On transfer I got an error. It looks like to transfer from org to org I need admin rights also on the receiving org.
This is their suggestion:

> "You can arrange this by asking the receiving organization to create a team with admin privileges with no repositories in it."

https://help.github.com/articles/transferring-a-repository/

**Comment by simonwex** [comment]
Hey @abusedmedia and @cadecairos it might be easier to give @cadecairos admin access to the original repo since we're transferring it anyway.

**Comment by cadecairos** [comment]
I've transferred the repo to mozilla!

**Comment by cadecairos** [comment]
https://learning.mozilla.org/codemoji/ is up and running. \o/

Thanks for the help @abusedmedia :+1: 

@HPaulJohnson shall we call this closed?

**Comment by abusedmedia** [comment]
💯

**Comment by HPaulJohnson** [comment]
So awesome, thanks all! @cadecairos you can close it up!

**Comment by cadecairos** [comment]
:tada:
