### ISSUE TITLE
Secure a vendor for tax receipting for every check donation

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#382]
Migrated from: https://github.com/mozilla/donate.mozilla.org/issues/1204

See complaint here:

![welcome____firefox_input](https://cloud.githubusercontent.com/assets/9830371/12062403/d5cf8df4-af50-11e5-9ba1-c1f1cd5a0692.png)

_Start date: September 1, 2016_ 
_Due date: September 2, 2016_

**Comment by WillatMozFdn** [comment]
Closing this one, we solved this Q3 of 2017.  Checks received via mail are scanned by MTV MoCo accounting staff, data is then input from those scans by Donor Care Coordinator Stephanie Lowry, acknowledgment letters merged and transmitted electronically to SFO WPR/Mailroom staff, and sent from there.  Entire process takes about a week.
