### ISSUE TITLE
Test Idea: Try 2 amounts + "donate" button vs. 3 amounts on the snippet

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#384]
Detailed description of work:
We floated the idea to reduce the options for amount on the snippet donation UX. Could be awesome 🚀 

_Start date: September 19, 2016_ 
_Due date: November 10, 2016_ 

CC: @ScottDowne

**Comment by vojtechsedlak** [comment]
Not ran due to low prioritization.
