### ISSUE TITLE
Test idea: Add the word "Donate" to the payment method buttons

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#386]
Detailed description of work:
@stephaniemcv gets some emails from people who say "Where's the donate button?" on our form because they don't intuitively know to click on the "Credit Card" or "PayPal" button. 

﻿﻿
![cursor_and_donate_mozilla_org___give_to_mozilla_today](https://cloud.githubusercontent.com/assets/9830371/18602079/b9bea508-7c34-11e6-8e8e-e92501491f2e.png)

_Start date: September 25, 2016_ 
_Due date: November 22, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by beccaklam** [comment]
@lovegushwa @valianttry @stephaniemcv 
https://redpen.io/p/udd5f886b8ac992340 <-- link to some donate button ideas

**Comment by beccaklam** [comment]
@lovegushwa @valianttry @stephaniemcv 
https://redpen.io/p/udd5f886b8ac992340 <-- added new designs based on feedback

**Comment by lovegushwa** [comment]
@vojtechmzl can we close this ticket?

**Comment by vojtechsedlak** [comment]
We haven't run these tests yet, so let's leave this ticket open @lovegushwa

**Comment by vojtechsedlak** [comment]
Adding the word donate by itself improved conversion rate by 3.5%. Further optimization was achieved by decluttering the buttons by removing the words paypal and credit/debit cards. Changing the color of the buttons to blue also improved conversion rate. Overall, all of the tested optimizations resulted in 8% improvement, from 10.48% to 11.32%.
