### ISSUE TITLE
Test idea: Surface "donate by check" on the form more

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#388]
Detailed description of work:
We received over 2000 checks during EOY 2015. We still get Qs in Desk.com about it. If it doesn't hurt conversion we should test to see if it's helpful / reduces this inbox question frequency.

![cursor_and_donate_mozilla_org___give_to_mozilla_today](https://cloud.githubusercontent.com/assets/9830371/18602188/6b34ef68-7c35-11e6-9a40-655432e71aed.png)

_Start date: September 19, 2016_ 
_Due date: October 13, 2016_ 

CC: @stephaniemcv

**Comment by valianttry** [comment]
We also talked about making the wording more friendly, e.g. "Want to know about other ways to give?" vs. "Problems donating?"

**Comment by vojtechsedlak** [comment]
Not ran during EOY 2016 due to low prioritization.
