### ISSUE TITLE
Review UX for L10N

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#389]
Detailed description of work:
Go through donor support UX from FAQ (https://wiki.mozilla.org/Donate ) to emailing for assistance for Tier One languages

Start date: September 19, 2016
Due date: September 30, 2016
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @valianttry

**Comment by valianttry** [comment]
@stephaniemcv is this something Rose Regina can do? Can you update the ticket and milestone?

**Comment by stephaniemcv** [comment]
Working on qa doc for this and #385 to hand off to @roseregina end of day

**Comment by Matt-Holland** [comment]
@roseregina has this been handed off to you?

**Comment by roseregina** [comment]
Not exactly/ kind of? I have some QA stuff, but I think there is more than one process that gets QA'd in terms of staging versus live.

**Comment by stephaniemcv** [comment]
Rose has only a part of the QA process. The FAQ and the integration wasn't completed, so we started on what we could. @Matt-Holland I'm fine with closing or moving to p2 since EOY is live.

**Comment by Matt-Holland** [comment]
Closing, based on @stephaniemcv 's comment.
