### ISSUE TITLE
Social share graphic for filevault/bitlocker

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Advocacy#39]
@ScottDowne I also have a new image for the filevault/bitlocker share on facebook:
https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0S0Y4akxUandoZlE/view

**Comment by natalieworth** [comment]
![filevault_illustration](https://cloud.githubusercontent.com/assets/14876567/15553901/3735f3b0-2276-11e6-904a-24a669af5c20.png)

**Comment by HPaulJohnson** [comment]
thanks, @natalieworth.

BTW, for future reference these graphics are something we can test within Share Progress platform. So if you have additional ideas in mind for the graphics we should test/optimize. cc/ @lovegushwa

**Comment by lovegushwa** [comment]
@HPaulJohnson good point. Let's do that.

**Comment by ScottDowne** [comment]
It lives https://advocacy.mozilla.org/assets/filevault_illustration.png
