### ISSUE TITLE
Design a dev edition snippet

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#392]
As part of the Spectacular Snippet https://github.com/mozilla/donate.mozilla.org/issues/560 design work, we came up with a couple fun options for a dev edition snippet. This is out of scope for EOY 2015, but parking it here in Bluesky in case a future opportunity arises. 

*\* Note that everything in the 2 designs below is conceptual only. We did not polish the copy or design.**
![screenshot 2015-12-04 13 53 50](https://cloud.githubusercontent.com/assets/4515662/11602363/8b808072-9a8e-11e5-944d-04464d873575.png)
![screenshot 2015-12-04 13 53 32](https://cloud.githubusercontent.com/assets/4515662/11602364/8d8f2044-9a8e-11e5-9816-322dbed1bbbb.png)

Migrated from https://github.com/mozilla/donate.mozilla.org/issues/1060

**Comment by ScottDowne** [comment]
@lovegushwa I wonder if running our normal snippet in dev edition as a test first, to see if it's viable, would make sense before building the fancy version? I mention this because I worry building a new snippet without a pretty good idea is a bit risky.

**Comment by jkt230** [comment]
@valianttry Listing your questions here:
1. What are average daily impressions for dev edition snippet? (EN US only) This will help us come up with some projections.
   Wes will pull this for you.
2. Who would be the key person(s) who would participate in approving the dev edition fundraising snippet design? Is that also Stephen Horlander? Or someone from MDN? Your advice on this process would be really appreciated :)
   In this case, would love to get together with Stephen Horlander (product UX team), Arcadio (PMM for developer marketing), Tim Murray (creative), Jordan, Michele, and I!

**Comment by WesWinton** [comment]
Hey All, 

Ballpark 320K impressions a day.

**Comment by ScottDowne** [comment]
Cool, thanks @WesWinton 

So that helps my concern a bit, that I mentioned in my last comment, about testing this with our regular snippet before building a fancy template. Maybe we still do that, though?

Based on @lovegushwa 's initial designs, it looks fairly static, which would make the build quite easy. That said, I'm willing to add a bit of interaction if @lovegushwa wants to scope something with me, and if we think it'll be worth it. No doubt it'll be fun! :rocket:

**Comment by WesWinton** [comment]
I am fine with testing our current fundraising snippet within the Dev edition, as long as its cool with the Dev edition key holders. What kind of number are we looking for with the test? Is there a number of donations we have to hit in order to justifying building out the unique snippet templates?

I love the idea if making the templates interactive, @ScottDowne. So fun!

**Comment by ScottDowne** [comment]
I think it depends on what value we see in this, but we can certainly add in something fun.

Easiest is something static, that has classic terminal look and some ascii art.

With a bit more work we can scale up, and add some interaction or animations.

For animations, we can do some load in stuff like this: https://youtu.be/JDWvGgot11o?t=59s

Can also add a blinking effect like this: https://youtu.be/JDWvGgot11o?t=1m19s

That's the sort of stuff we can do. Within a day of work for stuff like this.

If we want to scale up even more, we can add some interactions, my guess is it works like a terminal, and you input commands. I have a faily solid idea how this would work if we go down it, but it would be a significant amount of work. My guess is a week would be fast for something like this. Think along the lines of the eyeball snippets and http://scottdowne.github.io/surveillance-interstitial/public/ which was built roughly from Apr 29, 2015 to May 8, 2015.

**Comment by valianttry** [comment]
hey @ScottDowne -- A"standard" snippet is not going to appeal to this audience nearly as much as a snippet experience specifically designed for Developers. Is there something specific you're worried about that a test with the standard snippet will clarify? Are you worried about a low response from the users, or is there something about the code that you want to test to make sure things work the same as in Release? 

I would rather launch a donation ask to this audience with an experience that's awesome, vs. a ho-hum ask with a very low ROI. As I've said before -- I don't expect to raise much money with the Dev snippet. It's primarily an outreach / education / fun and personalized experience for that highly engaged audience vs. a "money making" endeavor for us.

**Comment by ScottDowne** [comment]
@valianttry yeah, I was just worried about building a new snippet for an untested audience. If we wanted to see how willing they were to give before building this, we could run the standard snippet for a day to see if it's worth it.

The actual scope of the snippet still feels pretty experimental, and not very specific. Something about terminals, ascii art and animations. I have those two existing comps Jordan made, but beyond that, it looks very open ended.

**Comment by valianttry** [comment]
@WesWinton who are the dev edition key stakeholders? We could set up a brainstorm meeting with them, you, and Jean along with our design / dev team and finalize approach / get on same page soon.

**Comment by WesWinton** [comment]
@valianttry I'll set up a meeting between all of us. Feel free to add anyone else to the invite when it comes your way

**Comment by michelewarther** [comment]
@WesWinton - ping me into the session too. what about the copy/creative for the takeover in the release channel?

**Comment by valianttry** [comment]
Meeting is scheduled for Monday Nov 7

**Comment by valianttry** [comment]
Notes from our meeting:
-- General enthusiasm for the idea! We will move forward. 

UX ideas:
-- Make sure we mitigate confusion, and that users don't think their browser is "broken" or offline with the design
-- Ask developers to enter a line command to launch the design
-- Make sure the message gets across our <3 for developers
-- Create a "broken" experience and ask developers to "de-bug" which then reveals the special snippet design;
-- Offer Bitcoin as a priority donation method
-- Use higher gift amounts than normal

NEXT STEPS:
-- Andrea will reach out to Potch to see if he'd like to help
-- Jordan will connect with Tim Murray and Stephen Horlander about the design concepts
-- Jordan and Natalie will work on a few concepts for the group to review / give feedback before Thanksgiving.
-- We will conduct a small test to make sure the user experience isn't harmed

attendees:
"Ali Spivak" aspivak@mozilla.com,
"Arcadio Lainez" alainez@mozilla.com,
"Danielle Vincent" dvincent@mozilla.com,
"Jordan Gushwa" jordan@mozillafoundation.org,
"Michele Warther" mwarther@mozilla.com,
"Natalie Worth" natalie@mozillafoundation.org,
"Scott Downe" scott@mozillafoundation.org,
"Wes Winton" wwinton@mozilla.com,
"jcollings" jcollings@mozilla.com

**Comment by HPaulJohnson** [comment]
Per our discussion this morning, let's decide in the next few days whether we have capacity to pull this off and, if so, share some designs with snippet team before Hawaii. 

@lovegushwa @beccaklam

**Comment by Matt-Holland** [comment]
Testing whether I can add a date in a comment

*Start date: November 29, 2016* 
*Due date: December 2, 2016*

**Comment by lovegushwa** [comment]
@HPaulJohnson I'm waiting for a response on spectacular snippet. I think we should prioritize building and testing for general release since its likely to have more impact. If some options get cut and @ScottDowne builds less varients for general release he will have time to build a dev addition snippet.

![dev-edition](https://cloud.githubusercontent.com/assets/12228435/20847533/6868a826-b883-11e6-8b3a-21ff956d748f.jpg)

**Comment by natalieworth** [comment]
Closing this for now—but could bring it up again for next years EOY campaign.
