### ISSUE TITLE
Localize updated FAQ text

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#394]
From https://github.com/mozilla/donate.mozilla.org/issues/437

We link to https://wiki.mozilla.org/Donate which is in all English in the German form.

**Comment by valianttry** [comment]
Working on updating the text here:
#586

**Comment by TheoChevalier** [comment]
After discussing with @ScottDowne:
- Scott will build a static webpage and extract the strings in a .properties file, which will be then exposed on Pontoon & GitHub
- We will expose the page to all locales enabled on donate.mozilla.org. I will let localizers know that  this page is targeting our top 10 locales (those on the brief), and is good to have for other locales.

Also, this is content that is not so much exciting to translate, should we offer our top 10 locales the possibility to get the initial translation done by Kontextor?

@valianttry  Does that sound good to you?

**Comment by valianttry** [comment]
@TheoChevalier that sounds OK, but possibly a bit expensive. It's a lot of words! Can you check in with Kontextor and scope the work with them?
