### ISSUE TITLE
Test idea: Re-order donate form elements based on channel

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#399]
Detailed description of work:
Given the snippet audience already selects "amount" on the snippet, can we create a donate form for that audience especially that has the payment method buttons at the top of the form instead of amount?

![cursor_and_donate_mozilla_org___give_to_mozilla_today](https://cloud.githubusercontent.com/assets/9830371/18602451/3b498136-7c37-11e6-87cf-22b0b7bf9691.png)

_Start date: September 19, 2016_ 
_Due date: October 13, 2016_ 

CC: @lovegushwa

**Comment by vojtechsedlak** [comment]
Not ran due to low prioritization during EOY 2016.
