### ISSUE TITLE
FileVault Email Review

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#40]
Please review the email copy, test the link and note any feedback in this ticket.
 Audience: Anyone who clicked in an Encryption email ~172,000

**Comment by lovegushwa** [comment]
@stephaniemcv 

one little bug: 

<img width="333" alt="screen shot 2016-05-26 at 12 05 15 pm" src="https://cloud.githubusercontent.com/assets/12228435/15586691/8fce32a2-233a-11e6-907d-0fc05fc94363.png">

**Comment by KevZawacki** [comment]
My QA below -- mostly language tweaks to improve the flow:

Change first paragraph, second sentence to: "But computers can get lost, stolen, or hacked — putting our sensitive information at risk."

Change second paragraph, first sentence to: "There's good news. One of the most effective ways to safeguard sensitive information is probably available right now on your machine — you may just have to turn it on."

Change second paragraph, second sentence to: "On both a Mac or PC, you can turn on the built-in encryption option and encrypt the contents of your hard drive."

Button: Hyphenate "STEP-BY-STEP"

Change third paragraph, third sentence to: "If your computer is a bit slower and prone to tantrums, you can install the software at night so it's less disruptive to your day."

Change fourth paragraph, second sentence to: "This is a great first step toward protecting your sensitive information." 

Link: Hyphenate "step-by-step"

Change fifth paragraph, second sentence to: "And when more of us use encryption, it's easier to explain it to others and build a community to keep encryption strong."

Valediction: I'm seeing some HTML:
![screen shot 2016-05-26 at 3 05 35 pm](https://cloud.githubusercontent.com/assets/11045250/15586627/6db3152a-2353-11e6-8255-019a70b073ef.png)

Change P.S., first sentence to: "Feel like this email is different from others you've received from us?"

**Comment by mmika** [comment]
edited a few typos on the doc: https://docs.google.com/document/d/1jJE28HGJWEXWo45rgy6dJBSq7jNcO_a2oVI8xu5YlEE/edit

@stephaniemcv

**Comment by stephaniemcv** [comment]
Edits made! Thanks for the feedback!
