### ISSUE TITLE
Build Spectacular Snippet

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#400]
Detailed description of work:
For the last few days of the year we normally "interrupt" Firefox users with a more robust donation ask in the snippet. It's more like a "takeover". We've done quite a bit of testing and optimization work on this and have a pretty good idea of what works. We do need to come up with early concepts, and then involve the Firefox UX team to make sure we are all happy.

We should come up with a few variants to test, like last year. Here is the design ticket for last year:
https://github.com/mozilla/donate.mozilla.org/issues/1096 

Example from 2015:
![about_home_snippet_preview](https://cloud.githubusercontent.com/assets/9830371/18602552/1800c576-7c38-11e6-877e-8f23c51dc1d2.png)

_Start date: October 1, 2016_ 
_Due date: November 10, 2016_

**Comment by valianttry** [comment]
@TheoChevalier we must decide if we want to localize this spectacular snippet design. It will only be live the last few days of the year in each locale. I think we should!

**Comment by TheoChevalier** [comment]
@valianttry  Yes, I think we should — we localized it last year.
- If we can/want to test different variants _per locale_, we should localize each variant (variants have been localized last year, but I have no idea if they were tested or if localization started before the final snippet was picked)
- If we are going to test different variants only in en-US, let’s start localization once the winning snippet has been picked. But let’s keep  at least two weeks for l10n.

We can create a similar file to this one for this year, it was a good thing to have a demo server and placeables, so we should continue doing that :) https://github.com/mozilla/donate.mozilla.org/blob/master/locales/en-US/snippet.properties

**Comment by HPaulJohnson** [comment]
Discussed copy needs with @lovegushwa and we'll come up with two variations to get feedback on from Snippet team this week:

1) Longer copy using last year's spectacular copy
2) Shorter version using the existing copy as placeholder for now. I'll be working on some other short variations for testing in the coming weeks and we can swap in winners after we get feedback on overall design from snippet team.

**Comment by Matt-Holland** [comment]
Last update was @lovegushwa to have a meeting with MoCo marketing to review/approve his set of designs. Is that meeting set?

**Comment by HPaulJohnson** [comment]
No meeting scheduled, snippet team decided to review asynchronously. I talked to Wes last night and the snippet team had signed off on the proposed designs. Wes is doing a final review with Tim Murray - the creative director - before giving the final feedback/greenlight.

@lovegushwa you should follow-up with Wes today if you have a chance to check-in on status.

**Comment by lovegushwa** [comment]
spectacular snippet designs are in creative review here: https://redpen.io/p/ab8e1558934aa8718b

**Comment by ScottDowne** [comment]
@beccaklam or @natalieworth few quick questions about the designs.

1. The animated bits, are they gifs?
2. The picture version does not have any animations, right?
3. The picture versions, is that one large background image, or are each image a separate image? Would be easier with one large background image. Just keep in mind some screen sizes are larger than the comps, so the photos need to be complete and not cropped to fit the comps.
4. Are all the hearts animated, or just a few or one random heart/s? They animate a few seconds after page load or when the donate button is clicked?
5. For the emoji version, are the emojis animated any special way or similar to the hearts? Are the location and emojis random or intended? Example, on every load, do I see the same background? (it's easy to randomize it, but might not actually look good in most cases)
6. I noticed the close button isn't on the photo snippet. Intended?
7. I noticed the close button is outside the snippet container. This usually doesn't happen, and gets reverted and put back inside the snippet container during code review.

I think that's all. In the end, this snippet looks like a few days work, if that.

**Comment by beccaklam** [comment]
@ScottDowne 
1. Yes, they're gifs. 
4. The decision was made that none of the hearts animate on page load, only when the user hovers or clicks (we can decide which) the donate button do *all* the hearts animate. For a demo the way I built it was on page load the hearts load a static PNG but on mouseover/click on the donate button I changed the src to the animated gif. I'll upload the static and the gif and then add the link to this ticket.
5. I think the emojis should load in the same spot every time. We currently don't have the emojis animating though that's something we could do... but for now just build it as static and if we can make the assets in time we would just swap out the src like how we did with the hearts when the donor hovers/clicks on the donate button. Does that make sense?

**Comment by beccaklam** [comment]
@ScottDowne 
Here is the link to the assets you'll need to build the heart version: https://drive.google.com/open?id=0BzuBOR2VJQqUTTJpd08yX2VGaFk I've included my old code from the demo in the 'hearts-svg' folder if you wanted to reference it. You'll probably need hearts in different colours... I'll get those to you soon.

**Comment by beccaklam** [comment]
@ScottDowne Okay, the red and blue hearts are in this folder now in their own respective folders labeled 'red hearts' and 'blue hearts': https://drive.google.com/open?id=0BzuBOR2VJQqUTTJpd08yX2VGaFk

**Comment by beccaklam** [comment]
@ScottDowne Some annotation for the designs:
Purple background: #624964 (use baseline/pink heart)
Blue background: #706ee0 (use blue heart)
Orange background: #ffb626 <-- includes emoji background (use red heart)
Red background: #e63e2f (use baseline/pink heart)

**Comment by natalieworth** [comment]
Hey @ScottDowne I exported the emoji icons as svg's too based on this design:
https://redpen.io/ks320a39e4a296b36b
https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0T1RHLWJjOEE1QWc

**Comment by lovegushwa** [comment]
@ScottDowne so start by building the three color variants of the heart pixel heart spectacular snippet. We are going to AB test these three variants. I'll post more details on the emoji design tomorrow, we are not going to build the polaroid version. You can get download jpgs of the designs here:
https://drive.google.com/drive/folders/0B2qu3ExKWIlvQzJibzF1OHZCTDA?usp=sharing

CC @Matt-Holland @HPaulJohnson 

Some notes:
- get the hearts from @beccaklam 's link above
- hearts should animate on hover over donate button
- hearts should continue to tile infinitely as user expands the browser window

![spectacular-snippet-jordan-final-b-04](https://cloud.githubusercontent.com/assets/12228435/21302297/8913ca9e-c56a-11e6-8f61-79098943072a.jpg)

![_updated-01](https://cloud.githubusercontent.com/assets/12228435/21333028/6f6400cc-c601-11e6-8d40-1f6940e0ce42.jpg)
Use pink hearts for purple backrgound: https://drive.google.com/open?id=0BzuBOR2VJQqUb21FM2FlS2NYSG8

![_updated-02](https://cloud.githubusercontent.com/assets/12228435/21333029/71615726-c601-11e6-9bcf-94b1beaa15af.jpg)
Use blue hearts for blue background: https://drive.google.com/open?id=0BzuBOR2VJQqUbFlKSi1RalAtczA

![_updated-03](https://cloud.githubusercontent.com/assets/12228435/21333031/7580ba18-c601-11e6-9181-03f04a857857.jpg)
Use yellow heart for emoji background: https://drive.google.com/open?id=0BzuBOR2VJQqUXzVCOFNYTVFzc1E

**Comment by lovegushwa** [comment]
And finally @ScottDowne for emoji:
@beccaklam added yellow hearts to the hearts folder above. 

![emoji-town-05](https://cloud.githubusercontent.com/assets/12228435/21335112/2b11a072-c611-11e6-96a3-24716b3e2ee8.jpg)

![emoji-town-06](https://cloud.githubusercontent.com/assets/12228435/21335115/34fabe8e-c611-11e6-8025-728c6ebc440e.jpg)

**Comment by beccaklam** [comment]
@ScottDowne Ok, I updated the gifs:
blue-sparkle.gif: https://drive.google.com/open?id=0BzuBOR2VJQqUVVV4NjU2V3Vjdjg
pink-sparkle.gif: https://drive.google.com/open?id=0BzuBOR2VJQqUcExfbG45RVNNRkE
Let me know if they work!

**Comment by ScottDowne** [comment]
This is done.
