### ISSUE TITLE
Create a detailed QA process for donate form front-end

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#403]
Detailed description of work:
We don't have a rigorous process for QA for the donate.mozilla.org form. We need one!

@damiankay made one for websites that we might rif on.

_Start date: September 19, 2016_ 
_Due date: October 7, 2016_

**Comment by Matt-Holland** [comment]
This list is sufficient for now:
https://github.com/mozilla/donate.mozilla.org/blob/master/docs/QA_Checklist.md
Closing.
