### ISSUE TITLE
Get list of languages Saw Mill is currently creating receipts for

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#404]
Detailed description of work: @ScottDowne Can you pull a list for me of all the languges Saw Mill is supporting. And if possible what the EN text is that has been localized? Lifecycle Marketing team has requested this

_Start date: September 19, 2016_ 
_Due date: September 23, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by ScottDowne** [comment]
@stephaniemcv yay, looks like these are the locales:

  'az',
  'ca',
  'cs',
  'de',
  'es',
  'es-ES',
  'es-MX',
  'fr',
  'fy-NL',
  'it',
  'ja',
  'ko',
  'nl',
  'pt-BR',
  'pt-PT',
  'ro',
  'sl',
  'sq',
  'sv-SE',
  'zh-CN',
'zh-TW'

from: https://github.com/mozilla/sawmill/blob/master/worker/stripe_charge_succeeded.js#L21-L41

**Comment by ScottDowne** [comment]
@stephaniemcv Here is the text that we use for translated emails: https://github.com/mozilla/webmaker-mailroom/blob/master/locale/en_US/stripe_charge_succeeded_2014.json

**Comment by ScottDowne** [comment]
English uses this template: https://github.com/mozilla/webmaker-mailroom/blob/master/templates/stripe_charge_succeeded_2015/index.html

Which is different than the localized one.

**Comment by Matt-Holland** [comment]
@stephaniemcv it looks like this request has been completed. Can this ticket be closed?
