### ISSUE TITLE
Update Desk.com Auto Responders (all languages)

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#408]
Detailed description of work: Update copy on auto responders and have localized to include links to localized faqs. Also update trigger logic as needed.

_Start date: October 1, 2016_ 
_Due date: October 13, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by stephaniemcv** [comment]
@cristinamoon @roseregina

Can you please review this copy and add edits/opinions/thoughts?

https://docs.google.com/document/d/1OGWZNO7jkJ3sDtLU70Fygef0ckrrXSHptGxp_ScHOC0/edit?usp=sharing

**Comment by cristina-moon** [comment]
I popped a suggested rewrite into comments.

**Comment by stephaniemcv** [comment]
Thanks!
@TheoChevalier 
The section titled "Updated Auto-Responder Text" is ready for your localization magic!
https://docs.google.com/document/d/1OGWZNO7jkJ3sDtLU70Fygef0ckrrXSHptGxp_ScHOC0/edit

**Comment by TheoChevalier** [comment]
I should ask for a “Localization started” label :) In the meantime, localization started!

**Comment by stephaniemcv** [comment]
Wooo! Thanks!

**Comment by TheoChevalier** [comment]
Hey @stephaniemcv here are the translations:

DE: https://raw.githubusercontent.com/mozilla/donate.mozilla.org/master/locales/de/autoresponder.lang
ES: https://raw.githubusercontent.com/mozilla/donate.mozilla.org/master/locales/es/autoresponder.lang
FR: https://raw.githubusercontent.com/mozilla/donate.mozilla.org/master/locales/fr/autoresponder.lang
IT: https://raw.githubusercontent.com/mozilla/donate.mozilla.org/master/locales/it/autoresponder.lang
pt-BR: https://raw.githubusercontent.com/mozilla/donate.mozilla.org/master/locales/pt-BR/autoresponder.lang

I suppose we should close this once it’s in desk.com

**Comment by TheoChevalier** [comment]
@roseregina @stephaniemcv looks like we never pushed those translations on desk.com, anything I can help with?

**Comment by stephaniemcv** [comment]
Oh, for the love of monkey spit and all things I cannot say in public.
Thank you @TheoChevalier!!!! I spaced this completely and am working on it now.

**Comment by stephaniemcv** [comment]
Completed adding languages and reorganizing rules. This should be firing correctly now. Thanks all!
