### ISSUE TITLE
Infrastructure: Create localized, triggered donation confirmations

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#413]
Detailed description of work: In association with ticket #404, and Stripe/Paypal integration with SalesForce - build corresponding donations confirmations that automatically trigger once a donation is complete.

_Start date: October 1, 2016_ 
_Due date: October 30, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by valianttry** [comment]
@stephaniemcv can you update this ticket and move it to a new milestone? TY!

**Comment by stephaniemcv** [comment]
Closing. LCM team scoped and we would be unable to hit our 11/29 deadline. Will need to use SawMill for the time being.
