### ISSUE TITLE
Need share copy for postcrimes

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#418]
Detailed description of work: Postcrimes has twitter and facebook share buttons - but we don't yet have copy for these modals.

I don't have a final character count, but here is an example of an image that will be shared:
https://postcrimes.mofoprod.net/#!/crime/57dff5f1cc0cd200033433cd - we may be able to get away with twitter automatically shortening this?

_Start date: September 19, 2016_ 
_Due date: September 20, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by KevZawacki** [comment]
Hey, how about:

**Twitter** (This character count assumes a link + image are shared, too): 

I sent a selfie to European Parliament to #fixcopyright. You can, too. Join me & @Mozilla: [LINK] [IMAGE]

**Facebook**: 

I sent a rebellious selfie to European Parliament to fix copyright. You can, too. Join me and Mozilla. Stand up for copyright reform: [LINK] [IMAGE]

**Comment by HPaulJohnson** [comment]
wfm, @KevZawacki 

cc:// @damiankay for localization, etc.

**Comment by brettgaylor** [comment]
Also looks good to me.

Let me check in with young astros re: character count

**Comment by HPaulJohnson** [comment]
I verified that these will work with character limitations and the images postcrimes generates. We should get them implemented asap now that the site is live. 

I also noticed that in the current twitter share setup, the images themselves aren't automatically being added, rather they are just including the link. They should be able to embed the image in the tweet just like they are doing with Facebook share.

**Comment by damiankay** [comment]
Let me know if I need to add this to L10N queue @brettgaylor

**Comment by brettgaylor** [comment]
Would it feel appropriate to hand to Kontextor?

**Comment by damiankay** [comment]
I think so. I'm not sure what our budget with them allows for, but they'll be able to turn it around much more quickly @brettgaylor . I can submit this to them today and I'm sure we'll have it by EOW.

**Comment by brettgaylor** [comment]
Budget is ok - well within contingency.

**Comment by damiankay** [comment]
Ok great. I'll send over to Kontextor and ask them to translate into Tier 1 and 2 locales. To confirm, I'm sending this: 

**Twitter** (This character count assumes a link + image are shared, too):

I sent a selfie to European Parliament to #fixcopyright. You can, too. Join me & @Mozilla: [LINK] [IMAGE]

**Facebook**:

I sent a rebellious selfie to European Parliament to fix copyright. You can, too. Join me and Mozilla. Stand up for copyright reform: [LINK] [IMAGE]

**Comment by brettgaylor** [comment]
Correct. You can remove [LINK][IMAGE]

**Comment by HPaulJohnson** [comment]
Looks like they updated this but in the Facebook version they added "Post Crimes" at the beginning of the sentence which makes it non-sensical; they should delete that copy. 

Also, FB pulls text from the OG tags as a headline in the share and this also just says "Post Crimes." Would be great to get them to update the OG tag to "Post Crimes: Make a statement" or "Post Crimes: Make a Meme & Send a Postcard" or even something super generic like "Mozilla Advocacy:  Reform Copyright". 

See attached for reference: 
![postcrimesfbshare](https://cloud.githubusercontent.com/assets/10078715/18730661/57354550-800c-11e6-907b-1ad9e35ba90e.jpg)

**Comment by damiankay** [comment]
@HPaulJohnson - can you specify the allowable character count? I'd like to let the localizers know. Not sure if other copy is being appended which will affect allowable max chars

**Comment by HPaulJohnson** [comment]
So, this is a bit of a moving target with images and dynamic links. Plus, Twitter just changed their rules and expanded the limit when tweeting an image but we haven't tested that. In any case, to be safe and given we've tested and verified with the messages above let's keep the max for twitter at 100 chars.

Facebook doesn't have the same char limits so they shouldn't worry about adding characters when translating those strings.

**Comment by damiankay** [comment]
Perfect - thanks @HPaulJohnson

**Comment by damiankay** [comment]
@brettgaylor - the Post Crimes share copy can be found [here](https://docs.google.com/spreadsheets/d/1dBARa2Pr9NB_Q5ZdPOV1Jx9NOLbATSPk3etSfCWHTkk/edit#gid=0) in the "Post Crimes" tab

**Comment by damiankay** [comment]
Hi @brettgaylor - wanted to confirm that you saw this. Can we close this one?

**Comment by brettgaylor** [comment]
Yes. Closing.

**Comment by damiankay** [comment]
thx!
