### ISSUE TITLE
Social Media Assets for Codemoji

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#42]
We are set to soft launch Codemoji next week with an email test (#26) and some light-weight social promotion, mainly to get feedback from an external/broader audience. 

Some basic ideas for social copy are in the attached: 
https://docs.google.com/document/d/1f9ijJTLZfFNX56x4dGrLWSEi-AgwdxdWfdh39-hOqbk/edit

We only need 1-2 Facebook and Twitter posts for the purpose of this test. Once we get feedback and assess we can initiate a second round of thinking on social media promos. 

cc/ @KevZawacki @natalieworth @lovegushwa

**Comment by natalieworth** [comment]
@stephaniemcv Could you post the design requirements here for the upcoming email :) I can finish them asap today.

**Comment by HPaulJohnson** [comment]
@natalieworth @lovegushwa we will need a different version of this Facebook card for new landing page (it's the default sharing image used in page meta data as well as on Share Progress page):

https://advocacy.mozilla.org/assets/img/share/Encryption-facebook-b5-06.png

^ This version is too "take action" focused (as a first CTA) and should be something more along the lines of earlier social graphics from beats 1-3. (We should have something existing to use)

**Comment by natalieworth** [comment]
@ScottDowne Colours for codemoji area:
Background: #005189
Text: #5381b9
Link: #ffffff
Hover on link: #5381b9
<img width="1001" alt="screen shot 2016-06-03 at 1 18 29 pm" src="https://cloud.githubusercontent.com/assets/14876567/15791745/0b6a6d6e-298e-11e6-9859-5df0b6e77de3.png">

**Comment by natalieworth** [comment]
@lovegushwa Have some rough .ai files and an After Effects file started here: https://drive.google.com/open?id=0B20-0lpP23c0SDZOZXpwT1c1bXM

**Comment by KevZawacki** [comment]
Hey @natalieworth @lovegushwa,

Looks like public launch will be Tuesday, June 28 -- think we're on track to have this ticket wrapped up before then?

**Comment by natalieworth** [comment]
@KevZawacki June 28 is great!

**Comment by natalieworth** [comment]
@KevZawacki Just adding the finished final social assets in this doc https://docs.google.com/document/d/1f9ijJTLZfFNX56x4dGrLWSEi-AgwdxdWfdh39-hOqbk/edit and attaching them with the links :)

**Comment by KevZawacki** [comment]
@natalieworth These are so great -- thank you! 

@lovegushwa Do you have a Google Drive link to the .gif we used on today's call?

**Comment by natalieworth** [comment]
All images/ gifs are attached in the gdoc here: https://docs.google.com/document/d/1f9ijJTLZfFNX56x4dGrLWSEi-AgwdxdWfdh39-hOqbk/edit
Feel free to reopen this issue if we need anything more or changed :)
