### ISSUE TITLE
Design graphics for Maker Party Social Stunt

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#421]
Detailed description of work:
MoCo Social Team is working on a "stunt" to kickoff Maker Party promotion on 10/6. Details of this activity are here: https://docs.google.com/document/d/1w2w_F6Y2dWEIVZibVOol7zx0pRE84-EvhZScT7hf4YY/edit

Copy is being worked on at the bottom of this doc: https://docs.google.com/document/d/1Ozel0ogJS9ow-nok9B2T_5-x3rv_vpnvmRMN4hLDy3M/edit and this ticket is for 1-2 graphics to accompany social media posts to promote the stunt. 

_Start date: September 19, 2016_ 
_Due date: September 23, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @lovegushwa @damiankay

**Comment by natalieworth** [comment]
Updated graphics are here ( V6-V9): https://redpen.io/p/uz42fd5e82268019c6
@HPaulJohnson

**Comment by natalieworth** [comment]
Final graphics for the Maker Party stunt are here: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0NXViV25HVUk3anc

Closing this issue but feel to reopen if you need anything else for this @HPaulJohnson
