### ISSUE TITLE
Rapid Response Video Production

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Advocacy#422]
Detailed description of work:
Video production for the rapid response copyright video. Content from @KevZawacki  in ticket #351.

_Start date: September 16, 2016_ 
_Due date: September 22, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @brettgaylor @lovegushwa @beccaklam @KevZawacki

**Comment by natalieworth** [comment]
First cut/ draft is here https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0NVYwMlBUaUJ6VVE

**Comment by KevZawacki** [comment]
@natalieworth This is **fantastic**! 

Re: The discussion in the Media channel about a new lede. Maybe "Don't break the internet"?

**Comment by natalieworth** [comment]
Final audio options for the video are here: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0TzN4ZzJveVd2Q1U

**Comment by natalieworth** [comment]
Most recent cut here: https://drive.google.com/file/d/0B20-0lpP23c0TFhmOHBCdkdfQTg/view

**Comment by natalieworth** [comment]
@brettgaylor @KevZawacki @HPaulJohnson EN, DE, and FR versions of .mov and .mp4 files are exported here for the rapid response video: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0RUFwVVlFSDNfYXc

@brettgaylor Do we need to have a localizer or someone have a 2nd pair of eyes on the DE and FR versions? Copy for those are here: https://docs.google.com/document/d/1pXMKnwTUkoOtmMSIYtBJrHR2sOqZf0sxtMrYmjZPh3s/edit

**Comment by KevZawacki** [comment]
@natalieworth Just to confirm -- the above localized videos are ready for the world?

**Comment by natalieworth** [comment]
@brettgaylor Are we able to get a localizer to proofread/ double check the DE and FR versions before being released? cc @KevZawacki

**Comment by brettgaylor** [comment]
Ok. We can file a bug to do that.

**Comment by KevZawacki** [comment]
@natalieworth @brettgaylor Just let me know when we've QA'd the localized versions, and I'll share publicly.

Also happy to help arrange QA. Let me know how I can help.

**Comment by brettgaylor** [comment]
@KevZawacki Filed here https://bugzilla.mozilla.org/show_bug.cgi?id=1305472

**Comment by brettgaylor** [comment]
@KevZawacki @natalieworth there are some corrections in the bugzilla ticket above for DE and FR.  Once those are updated, lets push the video to those markets.  There are a few comments regarding the speed of the text, which at this point we should disregard but consider for the next video - ie we may wish to make the on screen text length longer than we normally would considering the translations will likely come in at 20% longer than the english.  But lets call that learning :)

**Comment by natalieworth** [comment]
Updated the DE and FR versions and videos with links are in here:
https://docs.google.com/spreadsheets/d/1rmqeIJq1vMDFsI0sicu7XdVwkLDur-rerTPb3rjFyko/edit#gid=0

<img width="426" alt="screen shot 2016-09-27 at 2 05 37 pm" src="https://cloud.githubusercontent.com/assets/14876567/18893640/a092cf0e-84c3-11e6-803c-0f585dfcd49c.png">
<img width="425" alt="screen shot 2016-09-27 at 2 05 47 pm" src="https://cloud.githubusercontent.com/assets/14876567/18893645/a3de51b0-84c3-11e6-8997-0721ccdf72eb.png">
<img width="426" alt="screen shot 2016-09-27 at 2 05 52 pm" src="https://cloud.githubusercontent.com/assets/14876567/18893647/a3fd5e52-84c3-11e6-96c8-02d82e738f33.png">
<img width="426" alt="screen shot 2016-09-27 at 2 06 54 pm" src="https://cloud.githubusercontent.com/assets/14876567/18893655/a8fc1d9e-84c3-11e6-8154-17c76f0fa269.png">
<img width="424" alt="screen shot 2016-09-27 at 2 07 36 pm" src="https://cloud.githubusercontent.com/assets/14876567/18893656/a8fd2126-84c3-11e6-85e1-8aac2a5f1e01.png">
<img width="424" alt="screen shot 2016-09-27 at 3 04 36 pm" src="https://cloud.githubusercontent.com/assets/14876567/18893667/ba7ea168-84c3-11e6-9f63-c678fb0d709c.png">

Updates are from the bug here:https://bugzilla.mozilla.org/show_bug.cgi?id=1305472
<img width="859" alt="screen shot 2016-09-27 at 3 05 04 pm" src="https://cloud.githubusercontent.com/assets/14876567/18893685/cd72dfe6-84c3-11e6-887a-1d7fc9fe0891.png">

The only change with the DE version was that it was way too fast for the average person to read/ comprehend easily without already understanding the issue. I've slown the DE version down, but it's now running at 1:09 min:

<img width="856" alt="screen shot 2016-09-27 at 3 06 14 pm" src="https://cloud.githubusercontent.com/assets/14876567/18893747/f8cbb032-84c3-11e6-9a7e-9c309da5c94d.png">

**Comment by KevZawacki** [comment]
@natalieworth @brettgaylor 🎆 Will get them on FB right now. :-)
