### ISSUE TITLE
v2 Petition Site QA: Behavior after playing video

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#423]
After playing video on changecopyright, the full screen takeover remains and in the case of the "A Meme Is Born" video you are left with a page full of video credits. Two options for fixing: 
1. After video completes, close video player and return to petition. This is ideal.
2. Replace final frame of video with a call to action or something more branded. 

Screenshot: 
![postvidplay](https://cloud.githubusercontent.com/assets/10078715/18652542/1b66423e-7e88-11e6-813a-110031e05d11.jpg)

**Comment by damiankay** [comment]
@brettgaylor @lovegushwa - what do you prefer? 

CC @jendc123 @gholme4

**Comment by brettgaylor** [comment]
Ideally this would close and send users to petition sign, or failing that just close as Paul suggests

**Comment by damiankay** [comment]
@gholme4 can you close and sent users to the Petition to sign?

**Comment by jendc123** [comment]
Hi @damiankay the options to have the videos redirect would be a new feature and will require extra time to implement and would be a fairly heavy lift.  The best option would be to have the video close, once finished playing. We will do a bit of discovery and circle back on additional time required.

**Comment by damiankay** [comment]
@jendc123 that sounds good. 
@brettgaylor are you ok with simply closing the video for now? We can revisit and potentially add the link out post-launch. 
@lovegushwa, maybe we should add that to our list of features in our toolkit.

**Comment by gholme4** [comment]
@HPaulJohnson @damiankay #readyforreview

**Comment by HPaulJohnson** [comment]
The video window closes after playing is complete. Asssumming we are all okay with that as the solution, this passes.

**Comment by damiankay** [comment]
@brettgaylor - can you confirm that you're ok with this approach for launch?

**Comment by brettgaylor** [comment]
Yes, :+1:

**Comment by damiankay** [comment]
Great!
