### ISSUE TITLE
v2 Petition Site QA: Footer links need updating

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#424]
Footer links on v2 of site should be the same as existing v1 site. In particular, "Share this Site" should be removed (this goes to an old share progress page) and the privacy policy link should be updated to be consistent with existing site.

**Comment by damiankay** [comment]
CC @jendc123 @gholme4

**Comment by gholme4** [comment]
@damiankay #readyforreview

**Comment by HPaulJohnson** [comment]
this one is fixed. closing
