### ISSUE TITLE
v2 Petition Site QA: Volunteer check box is back on petition

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#426]
"I want to volunteer" check box is back on petition form. It should be removed as we are not asking for this option to be selected by signers. 

Screenshot: 
![formfields](https://cloud.githubusercontent.com/assets/10078715/18652684/3dd0e666-7e89-11e6-9733-cb58fad12d3c.jpg)

**Comment by damiankay** [comment]
CC @jendc123 @gholme4

**Comment by gholme4** [comment]
@damiankay #readyforreview

**Comment by HPaulJohnson** [comment]
looks good to me.
