### ISSUE TITLE
v2 Petition Site QA: Poptart cat takes me back to top when clicked

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#427]
Poptart/meme cat that appears when scrolling to section 2 of petition, says "Like this, check out memeland below." When I click on it I'm taken to very top of page, instead of down to Memeland section.

**Comment by damiankay** [comment]
CC @jendc123 @gholme4

**Comment by jendc123** [comment]
@damiankay can you drop in the links for both cats on the page.

**Comment by damiankay** [comment]
@jendc123 do you want links to the images? If so you can find them at the links below. 

We will use this Localized cat gifs for the first cat: https://drive.google.com/drive/folders/0BzuBOR2VJQqUSmJBYjZOdjkzZzA?usp=sharing

For the second cat please use this .gif without text:
https://drive.google.com/file/d/0BzuBOR2VJQqUaF9nV29jaE1TS1E/view?usp=sharing

From #434

**Comment by jendc123** [comment]
@damiankay what is the link to Memeland? I didn't see it in the copy deck.

**Comment by damiankay** [comment]
@HPaulJohnson do you have the link to Memeland?

**Comment by HPaulJohnson** [comment]
@brettgaylor should confirm but i believe it's postcrimes.org. in fact, i just checked it and the site is already live at that URL.

**Comment by brettgaylor** [comment]
Correct, postcrimes.org

**Comment by gholme4** [comment]
@HPaulJohnson @damiankay #readyforreview

**Comment by HPaulJohnson** [comment]
Verified. Fixed. Closing.
