### ISSUE TITLE
v2 Petition Site QA: Post petition signing behavior

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#429]
When I submit the petition I do not get a "a prompt to share as exists on the current changecopyright.org petition. Is this desired behavior? IMO, we should  ask for a share after the form submits. 

Also, once I have submitted the form, it is pulling in my name as part of the thank-you message along with a login/out message. Is this desired behavior? I'd just say thank you without personalization and insert a share CTA in this messaging area. 

Screenshot: 
![postsignscreen](https://cloud.githubusercontent.com/assets/10078715/18652896/cac38d7a-7e8a-11e6-8fab-7fab8aa01c56.jpg)

**Comment by beccaklam** [comment]
@HPaulJohnson Hey Paul, we actually discussed this with Fission as an issue about multiple users sharing the same computer. This is so multiple people can sign the petition should that be the case. In the original design of the form there is a share page... not sure why it's missing...

**Comment by beccaklam** [comment]
I do find this signed out modal' weird though, can we nix it? I don't think the user needs the feedback, they just need access to the form again if they are a new user:
![screen shot 2016-09-20 at 11 18 42 am](https://cloud.githubusercontent.com/assets/20977376/18676488/c4e74826-7f23-11e6-9084-64996cf7a8c7.png)

**Comment by beccaklam** [comment]
I also think it looks really awkward with the thank you bar in the middle of the screen. Like I suggested in ticket #433 we should ask Fission to change all forms/bars to always be sticky to the bottom of the screen:
![screen shot 2016-09-20 at 11 18 26 am](https://cloud.githubusercontent.com/assets/20977376/18676543/f2e2b648-7f23-11e6-9e2f-89a325f3622c.png)

**Comment by valianttry** [comment]
@jendc123 and @gholme4 was this fixed?

**Comment by gholme4** [comment]
@valianttry Yes, this was fixed.
