### ISSUE TITLE
"Play" unavailable on video 4 in Firefox

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#43]
What happens now:
When I open https://advocacy.mozilla.org/encrypt/social/4 and click on the 4th video, it should start playing or offer a ">" play button. Instead it just sits here:

![screen_shot_2016-05-26_at_6_42_45_pm__2_](https://cloud.githubusercontent.com/assets/9830371/15595211/e24b5d98-2371-11e6-8a15-7b3b255dfdb2.png)

What should happen:
The video should play, or the ">" button should be available.

I'm on  a Mac using Firefox 47

**Comment by ScottDowne** [comment]
@valianttry Seems to play for me. Do any of the videos play for you and is it just this one that doesn't?

Also, does this play for you? https://d24kjznqej0s8a.cloudfront.net/2016/encryption_campaign/beat5_landingpage.webm

**Comment by ScottDowne** [comment]
@valianttry I'm going to close this. We haven't had any reports so I'm hoping it was a one off thing.

Reopen this if it still happens to you.
