### ISSUE TITLE
v2 Petition Site QA: Facebook share image

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#430]
The Facebook share on the v2 petition looks to be pulling in the image of the poptart cat with the caption "Like this? Checkout memeland below." The image gets cutoff in the FB share and the copy doesn't make sense in this context. 

Can we make sure we define an alt image for FB sharing either in the button code or in the OG tags in the metadata? For now, we can use the same image as we did on v1 for this, unless @natalieworth or @lovegushwa have an alternate social share postage image they want used. 

Screenshot below:
![fbshareimage](https://cloud.githubusercontent.com/assets/10078715/18652993/b97dc6ba-7e8b-11e6-8466-42a8c4a7f5c2.jpg)

**Comment by damiankay** [comment]
@natalieworth @lovegushwa can you confirm which image you want to use pls?

**Comment by lovegushwa** [comment]
@damiankay working on this.

**Comment by lovegushwa** [comment]
@gholme4 @HPaulJohnson can you confirm the share copy?

Let's use the brain social share image here:
https://drive.google.com/file/d/0B20-0lpP23c0ZXh1TTZvSjMtSlE/view?usp=sharing

**Comment by HPaulJohnson** [comment]
image looks good, @lovegushwa 

for now, we should just use the share copy from the existing v1 site/FB share. it's already localized and works with this image. 

(eventually this is something i'd love to test/optimize for, but let's go with the mvp to get v2 shipped).

**Comment by damiankay** [comment]
@gholme4 please re-use copy from V1. Image is above.

**Comment by gholme4** [comment]
@HPaulJohnson @damiankay #readyforreview

**Comment by HPaulJohnson** [comment]
Tested in Chrome and looks good. In Firefox, I'm still getting the old issue but am assuming its a caching issue.

**Comment by vojtechsedlak** [comment]
If I am logged into NB, when I click the sidebar FB button in Firefox, I get a modal overlay with the correct image and localized copy, but I also get a new tab that opens with the poptart cat and old copy mentioned by Paul in the description of this ticket. 

In an incognito window in Firefox I only get the poptart cat popup, no modal overlay.

**Comment by gholme4** [comment]
@HPaulJohnson @vojtechmzl @damiankay #readyforretest

**Comment by lovegushwa** [comment]
@gholme4 we just landed updated social share content and copy. 

P2, but if you have a chance please swap the default share copy, for the copy in this deck:
https://docs.google.com/document/d/1PxnDB_f-zTMYi0zfTedz_jhBmhU6_qTTntSr_UiLpTs/edit

And update the share image: 
https://drive.google.com/file/d/0BzuBOR2VJQqURWVBSE1CQ3prREU/view?usp=sharing

**Comment by gholme4** [comment]
@lovegushwa I don't have access to that document. Please invite me.

**Comment by HPaulJohnson** [comment]
Testing again today. 

It's still broken in Firefox with old content and nyan cat showing up on Firefox share and english copy for Twitter and email.

For chrome, which previously passed testing, Twitter and Email share options are no longer localized and show up in English for all languages. Facebook is working as expected in Chrome.

**Comment by brettgaylor** [comment]
I'm also seeing the copy not being localized.

Here is facebook, in chrome, with locale set to polish

![image](https://cloud.githubusercontent.com/assets/345974/18852399/101dae72-83f5-11e6-88b0-ba44ce542a6e.png)

Similarly, email copy is not localized when i select the "email" link in the polish locale.

**Comment by damiankay** [comment]
@gholme4 @jendc123

**Comment by valianttry** [comment]
Facebook works from the homepage (Chrome) but Twitter is not localized.

![screen shot 2016-09-27 at 9 43 51 am](https://cloud.githubusercontent.com/assets/9830371/18883180/19c166b0-8497-11e6-9fe8-0abedabb5b17.png)
![screen shot 2016-09-27 at 9 44 03 am](https://cloud.githubusercontent.com/assets/9830371/18883181/19c3b1cc-8497-11e6-91ba-4c017c9ac2d3.png)

**Comment by HPaulJohnson** [comment]
email is also broken/not localized.

**Comment by valianttry** [comment]
Email copy is here:
https://docs.google.com/document/d/1aQ3ujht3MGBlaHT6NG1lUFD0YoxnTD8zC-NlwTaSsRs/edit 

Please let us know when this is updated

andrea

**Comment by jendc123** [comment]
@valianttry they were updated and ready for retesting.

**Comment by HPaulJohnson** [comment]
fixed
