### ISSUE TITLE
v2 Petition Site QA: Change state in petition button prevents me from signing (Chrome only)

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#431]
When filling out the petition form in Chrome, the "sign" button is below the fold. 

Screenshot 1:
![step1](https://cloud.githubusercontent.com/assets/10078715/18653082/569f8050-7e8c-11e6-9af9-9a5e5e27214d.jpg)

So, when I scroll down to complete the form and hit "sign" the button changes state to the persistent horizontal "Sign the Petition" bar that when clicked takes me back to the form from step 1 which I can't complete :( It's a vicious cycle. 

Screenshot 2: 
![step2](https://cloud.githubusercontent.com/assets/10078715/18653113/8b17df26-7e8c-11e6-8b06-4fe93d8be1cc.jpg)

Note: this only happens in Chrome as the "Sign" is well above the fold in my Firefox.

**Comment by damiankay** [comment]
CC @jendc123 @gholme4

**Comment by gholme4** [comment]
@HPaulJohnson What's the screen size of the computer you're working on? The problem is the form layout is too large and needs be smaller.

**Comment by HPaulJohnson** [comment]
13 inch Mac

**Comment by gholme4** [comment]
@HPaulJohnson @damiankay I made the form shorter to prevent the problem. #readyforreview

**Comment by HPaulJohnson** [comment]
@gholme4 @damiankay this fixed the problem. good to go. closing.
