### ISSUE TITLE
v2 Petition Site QA: Quotes in wrong position on page

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#432]
All quotes should be between the 1st and 2nd paragraph of each section, not after the 2nd paragraph.

See redpen for correct placement: 
https://redpen.io/bh9e2c7a6d82f9f458

<img width="828" alt="screen shot 2016-09-19 at 6 49 48 pm" src="https://cloud.githubusercontent.com/assets/12228435/18654979/0594f7a4-7e9a-11e6-91e9-4303bc07ed97.png">

**Comment by damiankay** [comment]
CC @jendc123 @gholme4

**Comment by gholme4** [comment]
@lovegushwa Can you please explain how to adjust the elements with the current English copy? The Redpen design has more paragraph blocks so I'm not clear how it all fits together.

**Comment by lovegushwa** [comment]
@gholme4 the quote blocks should go between the paragraphs like this:

![screen shot 2016-09-21 at 12 38 55 pm](https://cloud.githubusercontent.com/assets/12228435/18726331/ceec5d5e-7ff8-11e6-9fc6-5677c05b983b.png)

![screen shot 2016-09-21 at 12 39 04 pm](https://cloud.githubusercontent.com/assets/12228435/18726340/d72f468e-7ff8-11e6-97df-dd73846039be.png)

![screen shot 2016-09-21 at 12 39 12 pm](https://cloud.githubusercontent.com/assets/12228435/18726344/dd37263c-7ff8-11e6-802d-3c802c97f155.png)

**Comment by lovegushwa** [comment]
@gholme4 

<img width="736" alt="screen shot 2016-09-21 at 1 01 11 pm" src="https://cloud.githubusercontent.com/assets/12228435/18726955/8b9a588c-7ffb-11e6-9ed7-cbc71576138e.png">

<img width="730" alt="screen shot 2016-09-21 at 1 03 00 pm" src="https://cloud.githubusercontent.com/assets/12228435/18727017/c6ca9958-7ffb-11e6-9373-170f65916a9f.png">

<img width="722" alt="screen shot 2016-09-21 at 1 02 29 pm" src="https://cloud.githubusercontent.com/assets/12228435/18727025/cdfadcf6-7ffb-11e6-8759-c41bd4abfe63.png">

**Comment by gholme4** [comment]
@lovegushwa @damiankay #readyforreview

**Comment by lovegushwa** [comment]
@gholme4 the position of quotes between paragraphs is correct. Can we reduce the padding above the quotes by 1/2 so they appear optically centered?

<img width="967" alt="screen shot 2016-09-21 at 1 17 42 pm" src="https://cloud.githubusercontent.com/assets/12228435/18727573/18a7a91c-7ffe-11e6-8059-717c89a31648.png">

**Comment by gholme4** [comment]
@lovegushwa @damiankay #readyforreview

**Comment by lovegushwa** [comment]
@gholme4 looks perfect. thank you.
