### ISSUE TITLE
V2 petition site QA - jerky scrolling behaviour

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#433]
Chrome, OSX 10.11.2

When scrolling, the page immediately jumps to below the "CSI: GIF" thumbnail.

A recorded screencast:
https://dl.dropboxusercontent.com/u/7968133/weirdscroll.m4v

**Comment by beccaklam** [comment]
@brettgaylor @lovegushwa I wonder if this behavior could be corrected by always having the form/button sticky to the bottom instead of having it change midway. I don't think it would negatively affect the landing page. Thoughts?

**Comment by damiankay** [comment]
Related to #431 

CC @jendc123 @gholme4

**Comment by lovegushwa** [comment]
... there is a problem with the position of the sticky button effecting users filling out forms on smaller screens (13in). The sticky button and the petition form create a loop, when you scroll to the "sign" button which is below the fold, the sticky "sign the petition" button pops up, the effect is you can't actually click the  "sign" button. 

My recommendations: 
1. move the point "sign the petition" is activated further down the page. (so it does not pop up immediately after scrolling past the form.)
2. Fix the "jump," so the sticky button animates in smoothly and does not cause the content on the page to jump.

**Comment by gholme4** [comment]
@lovegushwa Activating the sticky button immediately when the form moves out of view is best for UX. The clear solution is to make the form layout smaller in height, so it fits on smaller screens.

**Comment by lovegushwa** [comment]
@gholme4  ok, if you can get the hight smaller that makes sense. 
Can you address the jerky page jump issue?

**Comment by gholme4** [comment]
@lovegushwa  @damiankay I made the form shorter and moved the sticky button to solve both problems. #readyforreview

**Comment by lovegushwa** [comment]
@gholme4 thank you. much better.
