### ISSUE TITLE
v2 Petition Site QA: Localize Nyan Cat

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#434]
@damiankay @HPaulJohnson 
We need to localize the Nyan Cat copy ... 
Brett was also suggesting a copy change something like

1st cat: "Keep the internet weird"
2nd cat: "That's what I'm talking about"
@KevZawacki any thoughts here? 

... so Nyan cat always always promotes what ever cool project we have going like post crimes. 
For @beccaklam let's pull out the speech bubble until we have localized versions of the cat read. 

<img width="544" alt="screen shot 2016-09-19 at 7 49 42 pm" src="https://cloud.githubusercontent.com/assets/12228435/18656002/436c3562-7ea2-11e6-91aa-581a7d7b4034.png">

<img width="1162" alt="screen shot 2016-09-19 at 7 52 06 pm" src="https://cloud.githubusercontent.com/assets/12228435/18656043/95bc5964-7ea2-11e6-83d8-f4003b09432d.png">

**Comment by HPaulJohnson** [comment]
@lovegushwa the existing copy was in the v2 copy deck so I assume it got submitted for localization? @damiankay handled that part so he can confirm. 

If memeland makes less sense in the context of postcrimes we can/should update. But, we should have something translated and something that can be used for launch at least.

**Comment by damiankay** [comment]
Hi @lovegushwa - you can find the cat copy here: 
https://pontoon.mozilla.org/bg/mozilla-advocacy/Copyright%20Petition/?search=memeland&string=154853

That said, there only appears to be the first string: "Like this, check out memeland below"

**Comment by KevZawacki** [comment]
@lovegushwa I like that copy!

**Comment by beccaklam** [comment]
@lovegushwa I've put the nyan cat gifs without the speech bubbles in the google drive:
https://drive.google.com/file/d/0BzuBOR2VJQqUX1lHTmRlN3ZlSnc/view?usp=sharing
https://drive.google.com/file/d/0BzuBOR2VJQqUaF9nV29jaE1TS1E/view?usp=sharing

**Comment by beccaklam** [comment]
@lovegushwa @HPaulJohnson @damiankay Localized cat gifs: https://drive.google.com/drive/folders/0BzuBOR2VJQqUSmJBYjZOdjkzZzA?usp=sharing

We are missing localizations for the second nyan cat gif though for the string: 'Now it's time to go to Memeland!'

**Comment by damiankay** [comment]
Yeah, I mentioned that above, but I wasn't sure if it was necessary. I should have brought it up on our call today. I'll see if I can pull off a translation now.

**Comment by damiankay** [comment]
@ScottDowne - can you please add this string to Pontoon?: 'Now it's time to go to Memeland!'

**Comment by ScottDowne** [comment]
@damiankay Added that string, should be on pontoon soon. Should be here: https://pontoon.mozilla.org/en-GB/mozilla-advocacy/Copyright%20Petition/?string=154336

I'll take a look in a bit, and make a note in this ticket that it's live on pontoon.

**Comment by damiankay** [comment]
Great - thanks @ScottDowne

**Comment by ScottDowne** [comment]
@damiankay ok, here it is https://pontoon.mozilla.org/en-GB/mozilla-advocacy/Copyright%20Petition/?string=158652

:rocket: :guitar:

**Comment by lovegushwa** [comment]
@damiankay so to wrap this up we will use this Localized cat gifs for the first cat: https://drive.google.com/drive/folders/0BzuBOR2VJQqUSmJBYjZOdjkzZzA?usp=sharing

for the second cat please use this .gif without text: 
https://drive.google.com/file/d/0BzuBOR2VJQqUaF9nV29jaE1TS1E/view?usp=sharing

**Comment by damiankay** [comment]
@gholme4 please let me know if you have any questions about this. Thanks

**Comment by gholme4** [comment]
@damiankay @lovegushwa Localizing images also needs to be done in the Bablic visual editor. First https://mozillafoundationstaging-mozillafoundation.nationbuilder.com/ needs to be added to the Mozilla account so the site can be crawled.

**Comment by damiankay** [comment]
Ok thanks @gholme4 - I'll let you know as soon as the site is in Bablic. @cadecairos is in EST, so likely won't be tonight.

**Comment by gholme4** [comment]
@damiankay Thanks. He needs to contact me when he's ready to add the new site so I can disconnect it from the main site translations.

**Comment by damiankay** [comment]
Ok @gholme4 - would you mind adding some instructions for Chris here: #451

I may have given him incorrect information Re setting up Bablic and want to make sure we don't break anything!

**Comment by cadecairos** [comment]
> Thanks. He needs to contact me when he's ready to add the new site so I can disconnect it from the main site translatios

@gholme4 Let me know when to enable bablic on the urls in #451

**Comment by damiankay** [comment]
This is ready for updating @jendc123 @gholme4

**Comment by jendc123** [comment]
@damiankay, Ola can translate this via Bablic.

**Comment by damiankay** [comment]
Hi @beccaklam - can you please double check that we have all of the correct localized versions? Should be all Tier 1 & 2 language versions for cat 1.

You can find the supported languages in the [wiki](https://github.com/MozillaFoundation/Advocacy/wiki/EU-Copyright-Campaign:-Project-information)
- Tier 1: English, French, German, Spanish, Polish
- Tier 2: Italian, Dutch, Czech, Bulgarian

Thanks!

**Comment by beccaklam** [comment]
Hi @damiankay we have all the above except Polish and Bulgarin (unless that's Hungarian, then we have that too). You can find them here: https://drive.google.com/drive/folders/0BzuBOR2VJQqUSmJBYjZOdjkzZzA?usp=sharing

**Comment by jendc123** [comment]
@damiankay @lovegushwa @beccaklam the cats are now updated #readyforreview.

**Comment by damiankay** [comment]
thanks very much @jendc123

**Comment by lovegushwa** [comment]
@damiankay @jendc123 @gholme4 the missing Dutch, Polish, and Bulgarian cats are now in this folder: https://drive.google.com/drive/folders/0BzuBOR2VJQqUSmJBYjZOdjkzZzA?usp=sharing

Use this gif without a speech bubble for the 2nd cat: 
https://drive.google.com/file/d/0B2qu3ExKWIlveG9FdWM2ZC1FRkE/view?usp=sharing

**Comment by damiankay** [comment]
Thanks @lovegushwa - I'll add these over the weekend.

**Comment by jendc123** [comment]
@damiankay @lovegushwa made the final cat updates #readyforreview

**Comment by jendc123** [comment]
@damiankay - #readyforreview

**Comment by damiankay** [comment]
Thanks very much @jendc123

**Comment by lovegushwa** [comment]
@jendc123 works thank you.
