### ISSUE TITLE
v2 Petition Site QA: change video thumbs.

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#435]
The small video thumbs are not in the correct order, starting from the 1st small thumb on the page, the order should be: 

CSI Gif
![video2](https://cloud.githubusercontent.com/assets/12228435/18656144/9b45e9da-7ea3-11e6-9f8e-8a491ce274f9.jpg)

MEME JAIL
![video3](https://cloud.githubusercontent.com/assets/12228435/18656145/9df6ba9c-7ea3-11e6-81a2-fd34dc41c884.jpg)

WE <3 THE INTERNET
![video4- same-as-video1](https://cloud.githubusercontent.com/assets/12228435/18656147/a232df8c-7ea3-11e6-97c4-044355181931.jpg)

**Comment by damiankay** [comment]
CC @jendc123 @gholme4

**Comment by gholme4** [comment]
#readyforreview

**Comment by HPaulJohnson** [comment]
looks good to me.
