### ISSUE TITLE
v2 Petition Site QA: align created in nationbuilder to left

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#436]
Move the "created in nationbuilder" text to the left so it's alights to the Mozilla logo as shown in this image:

![nationbuilder](https://cloud.githubusercontent.com/assets/12228435/18656212/3a353708-7ea4-11e6-8990-3f7a487e2090.gif)

**Comment by damiankay** [comment]
CC @jendc123 @gholme4

**Comment by gholme4** [comment]
@lovegushwa @damiankay  #readyforreview

**Comment by lovegushwa** [comment]
@gholme4 thanks. closing ticket.
