### ISSUE TITLE
v2 Petition Site QA: Fix overlap of share icons on mobile

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#437]
@beccaklam we should consider turning share icons off on mobile. Copy is still readable, but I'm not sure the disruption of the icons over the text is worth it. @HPaulJohnson @brettgaylor what do you think? 

![screenshot_20160919-201234](https://cloud.githubusercontent.com/assets/12228435/18656417/c4a2adca-7ea5-11e6-95ac-cf12a202dc02.png)

**Comment by HPaulJohnson** [comment]
Hmm, what's the other option besides removing :)

I think we will see more mobile traffic on v2 (paid media, channels other than snippet, etc) and, since we don't have a share CTA after you sign the petition in v2 (see issue #429), we'd basically be killing sharing for mobile visitors.

**Comment by beccaklam** [comment]
@lovegushwa @HPaulJohnson Yeah I agree something needs to be done, it's way too busy. My mobile is showing a thank you page after the user signs. But there should be a way for the user to share even if they don't sign or are done signing... what if we just put social at the beginning and end of the article? It would also pop up after user signs the form.
![screen shot 2016-09-20 at 11 58 51 am](https://cloud.githubusercontent.com/assets/20977376/18678220/54b282fe-7f29-11e6-9e56-e9d3391a0881.png)
![screen shot 2016-09-20 at 11 59 03 am](https://cloud.githubusercontent.com/assets/20977376/18678221/57833636-7f29-11e6-83eb-31f62cfe1b9f.png)

**Comment by damiankay** [comment]
CC @jendc123 @gholme4

**Comment by jendc123** [comment]
@lovegushwa @beccaklam can you confirm the approach you would like to take.  

cc @damiankay

**Comment by lovegushwa** [comment]
@jendc123 @gholme4

I agree with @beccaklam recommendation, can we implement exactly as seen in the images above?

**Comment by gholme4** [comment]
@lovegushwa @damiankay #readyforreview

**Comment by lovegushwa** [comment]
@gholme4 this solution works well, is it possible to use it for mobile and tablet but keep the original left  aligned floating share for desktop?

**Comment by gholme4** [comment]
@lovegushwa @damiankay Yes, that is doable. #readyforreview

**Comment by lovegushwa** [comment]
@gholme4 nice! perfect thank you.
