### ISSUE TITLE
v2 Petition Site QA: Nyan cat overlaps quote and number 2 graphic on mobile

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#438]
Nyan cat overlaps quote and number 2 graphic. A little bit of overlap on the color circle is nice but the cat should not obstruct the "2." Probably 5 or 10 px to the left will do.

![screenshot_20160919-201234 1](https://cloud.githubusercontent.com/assets/12228435/18656519/979e5bca-7ea6-11e6-8e8e-02881b517fc5.png)

**Comment by damiankay** [comment]
CC @jendc123 @gholme4

**Comment by gholme4** [comment]
@lovegushwa @damiankay It's been moved over 10px #readyforreview

**Comment by lovegushwa** [comment]
@gholme4 I took some screen measurements. Let's move it to the left 10 more px. 

TEST IMAGE: 
![screenshot_20160921-115559](https://cloud.githubusercontent.com/assets/12228435/18725615/e20eb3b2-7ff5-11e6-99c2-dc4cdb68d122.png)

**Comment by gholme4** [comment]
@lovegushwa @damiankay #readyforreview

**Comment by lovegushwa** [comment]
@gholme4 perfect, thank you!
