### ISSUE TITLE
sign up page doesn't reallt work on mobile anymore

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#44]
Not sure if this is a regression or what, but it's pretty busted.

**Comment by valianttry** [comment]
@ScottDowne what link?

cc @HPaulJohnson in case this is related to the landing page optimization work ....

**Comment by ScottDowne** [comment]
@valianttry my bad, I should have added more info.

Busted here: https://advocacy.mozilla.org/encrypt/signup

**Comment by ScottDowne** [comment]
It's fixed now https://advocacy-mozilla-org-prod.herokuapp.com/encrypt/signup/
