### ISSUE TITLE
v2 Petition Site QA: Lead In Text Too Long or Missing & Body Text is wrong size and colour

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Advocacy#440]
Detailed description of work:
Lead in text should on be two words.
# **No:**

![screen shot 2016-09-20 at 10 49 50 am](https://cloud.githubusercontent.com/assets/20977376/18675196/a64aa984-7f1f-11e6-85f3-6821f7eeddd5.png)
# **Yes:**

![screen shot 2016-09-20 at 10 52 35 am](https://cloud.githubusercontent.com/assets/20977376/18675318/fc33df0a-7f1f-11e6-9c13-1336ed002641.png)

Lead in text is also missing from all the articles:
# **No:**

![screen shot 2016-09-20 at 10 54 03 am](https://cloud.githubusercontent.com/assets/20977376/18675384/339fc2a6-7f20-11e6-935a-da16ce5d0e9c.png)
# **Yes:**

![screen shot 2016-09-20 at 10 55 28 am](https://cloud.githubusercontent.com/assets/20977376/18675451/5ff99af2-7f20-11e6-8a08-df7b20e8b804.png)
# **ALSO:**

The body text is at the wrong size and colour as you can also see above ^. Body text should be #4a4a4a (lead in text stays #000000) and larger than the lead in text. 
Desktop point sizes-
Lead-in Text: 16px
Body Text: 19px

**Mobile body font size is fine.

This is to help facilitate a more comfortable reading experience for the user on desktops and tablets. All this information is available to Fission if they click into the Photoshop files we provided them. 

Browser/device: Firefox, Safari, Chrome/Mac OS

**Comment by damiankay** [comment]
CC @jendc123 @gholme4

**Comment by gholme4** [comment]
@damiankay @beccaklam Can you please specify the lead in text in each paragraph for the English copy?

**Comment by beccaklam** [comment]
@jendc123 @gholme4

It's the first two words of every starting paragraph for points 1, 2 and 3. So point 1:
Point 1: **Copyright can** be valuable...
Point 2: **Mashups, memes**, and GIFs...
Point 3: **A key** part of what...

**Comment by gholme4** [comment]
@beccaklam @damiankay #readyforreview

**Comment by beccaklam** [comment]
@gholme4 @damiankay Hi George, sorry, but for Point three can we change extend the 'lead-in' style to include all of 'A key part'? 'A key' just looks kind of awkward. Please and thank you!

**Comment by gholme4** [comment]
@beccaklam @damiankay Yes. I made that change #readyforreview
