### ISSUE TITLE
v2 Petition Site QA: Article Titles (H3) Design Issues (Wrong colour, weight, padding and leading)

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Advocacy#441]
Article Titles (Points 1-3) have incorrect colour, font weight, padding and leading:
# **No:**

![screen shot 2016-09-20 at 10 54 03 am](https://cloud.githubusercontent.com/assets/20977376/18675900/d780b1c2-7f21-11e6-9b2b-04661491c3fa.png)
# **Yes:**

![screen shot 2016-09-20 at 10 55 28 am](https://cloud.githubusercontent.com/assets/20977376/18675956/ffa9b91e-7f21-11e6-85d4-e4ea32c6a756.png)

Colour should be #000000 not #4a4a4a, font weight should be pushed to the max (900 I guess), leading should be tighter, try 1.15em. Padding:
Desktop - 0 150px;
Tablet - 0 100px;
Mobile - 0 30px;

**Comment by damiankay** [comment]
CC @jendc123 @gholme4

**Comment by gholme4** [comment]
@damiankay @beccaklam #readyforreview
