### ISSUE TITLE
v2 Petition Site QA: Blockquotes need more leading and padding

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Advocacy#442]
Increase leading and padding of blockquotes for better readability and contrast from the body text:
# **No:**

![screen shot 2016-09-20 at 11 10 40 am](https://cloud.githubusercontent.com/assets/20977376/18676155/a803433c-7f22-11e6-888c-73303e22dae6.png)
# **Yes:**

![screen shot 2016-09-20 at 11 12 38 am](https://cloud.githubusercontent.com/assets/20977376/18676191/c7d77804-7f22-11e6-9687-0783d3774a6f.png)

**line-height: 34px and increase padding: 0 50px;**

**Comment by damiankay** [comment]
CC @jendc123 @gholme4

**Comment by gholme4** [comment]
@damiankay @beccaklam #readyforreview
