### ISSUE TITLE
v2 Petition Site QA: GA event for sidebar share buttons needs to be updated

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#443]
When user clicks the sidebar share on the action page, a GA event should be triggered. The class of the parent element has changed in V2, so the script.js file just needs to be updated to reflect the new class. Where it says `$(".share-bar a").on("click", function() {` it should now say `$(".socials-bar a").on("click", function() {`

**Comment by damiankay** [comment]
CC @jendc123 @gholme4

**Comment by gholme4** [comment]
@vojtechmzl @damiankay #readyforreview

**Comment by vojtechsedlak** [comment]
Thanks for the fix @gholme4. The event is now tracking correctly.
