### ISSUE TITLE
v2 Petition Site QA: Add ScrollDepth Google Analytics Event

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#444]
Implement http://scrolldepth.parsnip.io/ on the petition site to get a better understanding of how people engage with the page. The src file can be downloaded from the site and the following is the implementation script:

`<script src="jquery.scrolldepth.min.js"></script>
<script>
jQuery(function() {
  jQuery.scrollDepth();
});
</script>`

**Comment by damiankay** [comment]
CC @jendc123 @gholme4

**Comment by gholme4** [comment]
@damiankay @vojtechmzl #readyforreview

**Comment by vojtechsedlak** [comment]
Unfortunately the scrollDepth events are not being logged into GA. I can see the code in the script.js and it all seems correctly implemented, but there is nothing in GA.

**Comment by gholme4** [comment]
@vojtechmzl Can you check again?  The debugger shows the events being logged. See screenshot:
![screen shot 2016-09-21 at 11 59 37 am](https://cloud.githubusercontent.com/assets/2045330/18720808/39f17608-7ff3-11e6-83b6-da3fca6de1fb.png)

**Comment by vojtechsedlak** [comment]
Oh cool, yeah I can see the events now. Must have been a lag on the GA side. Thanks!
