### ISSUE TITLE
v2 Petition Site QA: Confirmation email content

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#445]
The confirmation email received after signing the petition seems broken. It reads "Here's the full petition:" and then only includes the headline. See screenshot attached. 

![emailconfirm](https://cloud.githubusercontent.com/assets/10078715/18679839/2fea7520-7f16-11e6-8661-e0294f173bba.jpg)

**Comment by damiankay** [comment]
CC @jendc123 @gholme4

**Comment by stephaniemcv** [comment]
Can confirm that @cristina-moon was not tapped for this. Did V1 have a confirm email. My vague memory is that the thank you for signing was just going to be on the next page.

**Comment by damiankay** [comment]
@stephaniemcv - you're right. There was no confirmation email from V1. 

@HPaulJohnson - can we stick with the V1 functionality and simply show the thank you on-screen, with share buttons?

**Comment by HPaulJohnson** [comment]
@damiankay thank-you on screen + share is great. 

re: email, not really my call. i defer to @valianttry and @stephaniemcv on that one.

**Comment by stephaniemcv** [comment]
I recommend/prefer the same setup we have with V1.

**Comment by jendc123** [comment]
@damiankay - this has been unchecked on staging and can be controled on a page by page basis.  #readytocheck

**Comment by damiankay** [comment]
@HPaulJohnson  can you retest please?

**Comment by HPaulJohnson** [comment]
@damiankay I just retested and did not receive a confirmation email. I'm assuming that's a pass.

**Comment by damiankay** [comment]
Yes, for now that's correct. Once we have Salesforce set up you should get a confirmation email from there @HPaulJohnson
