### ISSUE TITLE
Test Idea: Donate Ask on the thank you page

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#446]
Detailed description of work: Let's test including a donate ask on the thank you page of the v2 petition. Ideally we would create a mockup of what having a donate CTA added below share buttons would look like on both desktop and mobile. The implementation would be done either via Optimizely or in collaboration with Fission.

_Start date: September 20, 2016_ 
_Due date: October 7, 2016_ 

CC: @lovegushwa @beccaklam Please let me know if you would be able to help with mocking this up. Thanks!

**Comment by lovegushwa** [comment]
@beccaklam we need a donation ask with this copy ( ignore this design of course!) 

<img width="1114" alt="screen shot 2016-09-22 at 9 40 04 pm" src="https://cloud.githubusercontent.com/assets/12228435/18774367/2b8d1548-810d-11e6-93e4-a543b3493e49.png">

**Comment by lovegushwa** [comment]
@beccaklam Currently I'm not seeing anything after signing on desktop, did you create a share ask for desktop? I see a design for mobile. If you did not make one we are going to need it! Could be the same design but triggered as a modal. 

![mobile thank you and share](https://cloud.githubusercontent.com/assets/12228435/18774421/e1b90e44-810d-11e6-8cfc-7d9244c56551.png)

**Comment by beccaklam** [comment]
@lovegushwa I did design  a thank you for desktop, it was included in the red pens and the photoshop file:
![screen shot 2016-09-23 at 9 18 58 am](https://cloud.githubusercontent.com/assets/20977376/18786923/6320b382-816e-11e6-8728-f6fea1599b30.png)

**Comment by beccaklam** [comment]
@damiankay @vojtechmzl Here are designs that could be implemented for a donation ask. I have attached both desktop and mobile versions:
![desktoptabletdonate](https://cloud.githubusercontent.com/assets/20977376/18791025/1eae3f2e-817f-11e6-9af7-039bf3c66b30.png)
![mobiledonate](https://cloud.githubusercontent.com/assets/20977376/18791028/20c4e948-817f-11e6-8f5e-5036a9b89247.png)

**Comment by vojtechsedlak** [comment]
These look great! Thanks @lovegushwa! Could we create a version that combines both donate and share asks? That would be ideal to run a fully comprehensive test. Thanks!

**Comment by beccaklam** [comment]
@vojtechmzl @lovegushwa @damiankay Here are the designs that combine the share and donate ask. @lovegushwa thoughts on the design? It's a bit busy but not sure how to make it less so.
![desktopthankyoudonate](https://cloud.githubusercontent.com/assets/20977376/18793100/4f07ed48-8187-11e6-89d5-fc9ebfc69c5a.png)
![mobilethankyoudonate](https://cloud.githubusercontent.com/assets/20977376/18793105/52590a40-8187-11e6-850c-334682f3ccf5.png)

**Comment by lovegushwa** [comment]
@damiankay we are going to try and implement these tests via optimizely. Depending on the results we may ask Fission to add them to the petition template.

**Comment by damiankay** [comment]
Ok, thanks for the update @lovegushwa

**Comment by lovegushwa** [comment]
@beccaklam we need this image @2x
<img width="168" alt="screen shot 2016-09-23 at 12 49 07 pm" src="https://cloud.githubusercontent.com/assets/12228435/18799399/31f00646-818c-11e6-849b-e632a25dd879.png">

**Comment by beccaklam** [comment]
@lovegushwa @vojtechmzl Here's the png of the donate button: https://drive.google.com/file/d/0BzuBOR2VJQqUemRoM0xZZ0s5NTg/view?usp=sharing

**Comment by vojtechsedlak** [comment]
The results of the test were inconclusive. Closing this for now, with the hope of rerunning this test down the road.
