### ISSUE TITLE
Test Idea: Adding counter to the V2 petition form

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#447]
Detailed description of work: Let's test including some type of a signature counter to the V2 petition form. At this point the idea is to figure whether the mention of existing number of signatures makes an impact on conversions. Once we get answer to that question we can play with different types of counters. Ideally we would mock up what a simple counter could look like on the v2 petition form. Implementation would be done through Optimizely and with collaboration with Fission

_Start date: September 20, 2016_ 
_Due date: October 7, 2016_ 

CC: @lovegushwa @beccaklam Would you able to help with the mock up here? Let me know if you have any questions.  Thanks!

**Comment by lovegushwa** [comment]
@damiankay ... @vojtechmzl identified a few tests ( also see #446)
I want to get @beccaklam started designing these, but we need to make sure Fission has time / budget to implement the tests. Can you find out?

**Comment by damiankay** [comment]
Hey @lovegushwa - yes, I'll check with Jennifer tomorrow.

**Comment by damiankay** [comment]
@beccaklam @lovegushwa Fission might be able to do this for EOW, but they'd like to see a design to confirm. Can you provide this early today please?

**Comment by lovegushwa** [comment]
@damiankay spoke with Fission and said we would update them about this tomorrow

@vojtechmzl here are a couple options for a test, @beccaklam if you can solve what the mobile will look like and add the design before lunch that would be amazing.

<img width="790" alt="screen shot 2016-09-22 at 9 17 58 pm" src="https://cloud.githubusercontent.com/assets/12228435/18774174/43ff9dd2-810b-11e6-96ac-1980fc0b5232.png">

**Comment by beccaklam** [comment]
@damiankay @vojtechmzl Here are the mobile versions of @lovegushwa 's designs:
![mobile-progressbar-1](https://cloud.githubusercontent.com/assets/20977376/18790990/f9d339ca-817e-11e6-8e35-b0e9d7c8b5fb.png)
![mobile-progressbar-2](https://cloud.githubusercontent.com/assets/20977376/18790992/fbaf6ae8-817e-11e6-9e87-1765b8a476c1.png)

**Comment by vojtechsedlak** [comment]
These are really great! Thanks @lovegushwa @beccaklam. Just wondering if, for the purposes of the test, we should perhaps lose the copy and only go with numbers (v1 would then be probably better). Adding the bablic complexity into the equation just to run a test may not be the best idea and I think the numbers are self-explanatory. It could also be a good follow up test to see the impact of the copy itself.

**Comment by lovegushwa** [comment]
@damiankay we are going to try and implement these tests via optimizely. Depending on the results we may ask Fission to add them to the petition template.

**Comment by lovegushwa** [comment]
@vojtechmzl your talking about something like this? I assume we need to pull out the copy for localization reasons.
![petition](https://cloud.githubusercontent.com/assets/12228435/18799196/3732b014-818b-11e6-8fa6-30f69a729884.jpg)

**Comment by vojtechsedlak** [comment]
Yup, I think this is good for testing. Thanks @lovegushwa

**Comment by lovegushwa** [comment]
@beccaklam all we need is this image @2x
<img width="285" alt="screen shot 2016-09-23 at 12 50 03 pm" src="https://cloud.githubusercontent.com/assets/12228435/18799416/4a4155f6-818c-11e6-9c34-609aa1f65a08.png">

**Comment by beccaklam** [comment]
@lovegushwa @vojtechmzl SVG work? Here is the fake progress bar: https://drive.google.com/file/d/0BzuBOR2VJQqUZjBRUTF0dmRTbWc/view?usp=sharing

**Comment by vojtechsedlak** [comment]
Thanks for passing this along @beccaklam! SVG is fine

**Comment by vojtechsedlak** [comment]
Hey @beccaklam, would you be able to send me an updated img file (ideally png or jpg) with 78,126 as the achieved number of signatures and with the progress bar adjusted accordingly? Thanks!

**Comment by vojtechsedlak** [comment]
The results for this test are in and, drum roll, adding the counter does increase conversion rates! As you can see in the chart below, the presence of the counter resulted in 16.7% increase in conversion rates. That means that for every 100,000 visitors we could get 1,000 additional signatures. The results are statistically significant, so I would suggest implementing it on the production site. I will launch a new ticket for the implementation.

cc @beccaklam @lovegushwa @valianttry @HPaulJohnson @brettgaylor 

<img width="1272" alt="screen shot 2016-10-06 at 8 15 09 am" src="https://cloud.githubusercontent.com/assets/20688240/19158303/0ea7add6-8b9d-11e6-85bc-16a68ac5e786.png">

**Comment by vojtechsedlak** [comment]
Counter implemented, closing the issue.
