### ISSUE TITLE
v2 Petition Site QA: Localized video versions not showing

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#448]
English versions of videos are being served regardless of the language selected. The locale-appropriate video versions should be populated based on selected language.

**Comment by damiankay** [comment]
CC @jendc123 @gholme4

**Comment by damiankay** [comment]
To clarify, the localized videos should have been in list of links that were shared earlier. Thanks

**Comment by gholme4** [comment]
@damiankay @HPaulJohnson If a new site (https://mozillafoundationstaging-mozillafoundation.nationbuilder.com) was created to pull in the video links please add me as a collaborator.

**Comment by damiankay** [comment]
I'll follow up as soon as the site is in Bablic. Thanks!

**Comment by damiankay** [comment]
This should be ready for you know @jendc123 @gholme4

**Comment by jendc123** [comment]
Hi @damiankay and @HPaulJohnson - This is done via Bablic.

**Comment by damiankay** [comment]
@jendc123 does that mean that Kontextor needs to do this?

**Comment by valianttry** [comment]
This appears to have been cleared (just QAed a couple of languages and the correct localized videos played).
