### ISSUE TITLE
Maker Party: Map no longer displays

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#449]
Detailed description of bug:
The map no longer displays on the main landing / find an event page. 

Tested on Macbook Air / Firefox & Chrome

CC: @gholme4 @jendc123
![screen shot 2016-09-20 at 4 42 52 pm](https://cloud.githubusercontent.com/assets/19785709/18693017/5f276f22-7f53-11e6-9bc3-427a79ba738f.png)

**Comment by jendc123** [comment]
@damiankay the map is back up. #readyforreview
