### ISSUE TITLE
v2 Petition Site QA: After signing petition, still get a Sign the Petition CTA

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#450]
After successfully submitting a petition signature, I get a "Thank you for signing, Paul Johnson" message. But, I also get an additional CTA for me to "sign the petition" which takes me to the first section of the copy when clicked. 

Screenshot attached: 
![postpetitionsign](https://cloud.githubusercontent.com/assets/10078715/18693137/5079c0f0-7f54-11e6-81d0-346d887e94ff.jpg)

(Also, I thought we were getting rid of the personalization on the thank you message? Might be confused on that and not a P1).

**Comment by HPaulJohnson** [comment]
cc @damiankay

**Comment by damiankay** [comment]
CC @jendc123 @gholme4

**Comment by gholme4** [comment]
@damiankay @HPaulJohnson Sorry. I introduced this issue when I addressed another issue. #readyforreview

**Comment by damiankay** [comment]
Happens sometimes! thanks @gholme4 
@HPaulJohnson can you review when you have time?

**Comment by HPaulJohnson** [comment]
fixed! closing.
