### ISSUE TITLE
Maker Party: Add links to Events portal

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#452]
Detailed description of work:
Hey @ScottDowne - can you please go through the Maker Party pages on [learning](https://learning.mozilla.org/en-US/events) and add links to the [Nationbuilder pages](http://www.makerparty.community/) where necessary? There are a lot of dead links as the domain wasn't ready when you built the pages. Thx

_Start date: September 21, 2016_ 
_Due date: September 21, 2016_

**Comment by damiankay** [comment]
@ScottDowne - you can find the links here: https://docs.google.com/spreadsheets/d/1ETrREU8BHsvVWV4oZhfCiob_qUKEEW-E9Aal6S2pbsA/edit#gid=0

**Comment by ScottDowne** [comment]
@damiankay I'm pretty sure that's not what I need. What I need to know is:

On these pages:

https://learning.mofostaging.net/en-US/events/
https://learning.mofostaging.net/en-US/events/resources/

I need link targets for these links:

## First
- [x] The first get started link. I'm guessing we drop them on the maker party home page? https://www.makerparty.community/
  ![get-started](https://cloud.githubusercontent.com/assets/197334/18726504/c159b226-8012-11e6-9a06-002671f13ecd.png)

## Second
- [x] login link? Where should this go?
  ![login](https://cloud.githubusercontent.com/assets/197334/18726501/c157b17e-8012-11e6-9030-3efa3bfbe863.png)

## Third
- [x] Another get started link and sign the petition link. I;m guessing these go to https://www.makerparty.community/ and https://www.changecopyright.org/
  ![get-started-2](https://cloud.githubusercontent.com/assets/197334/18726503/c15803c2-8012-11e6-9343-1321231464e1.png)

## Fourth
- [x] All these are links, and I have no clue where we intent to send them when clicked.
  ![footer-1](https://cloud.githubusercontent.com/assets/197334/18726502/c157d316-8012-11e6-9f45-c7dcbb444be8.png)

## Fifth
- [ ] The activities are likely going to be on advocacy, but we still need to come up with links.
  ![activities](https://cloud.githubusercontent.com/assets/197334/18726505/c15a28d2-8012-11e6-8903-122db3f7364d.png)

## Sixth
- [x] Get your host pack link?
  ![get-host](https://cloud.githubusercontent.com/assets/197334/18726506/c15ae560-8012-11e6-8d14-5323c466947d.png)

## Seventh
- [x] Partner with us link and footer links for the second page?
  ![final](https://cloud.githubusercontent.com/assets/197334/18726507/c161a832-8012-11e6-9dfa-ebb1229035c0.png)

**Comment by HPaulJohnson** [comment]
@ScottDowne Press should link to press@mozilla.com. 

For contact us we are trying to get a new email created that we can hook into desk.com for support; in the mean time we can use makerparty@mozilla.org which is the old MP support email that at least still functions for the time being. 

Login should go to the login page on main MP site on Nation Builder

@ldecoursy do you have final links for "Host Pack" and "Partner With Us" (Partner pack, I assume)?

**Comment by ldecoursy** [comment]
Partner pack is here: https://mzl.la/2016MakerPartyPartner

Host pack is here https://mzl.la/makerpartyhostpack2016 (although still awaiting some final links, and some design love from @lovegushwa

**Comment by ScottDowne** [comment]
@ldecoursy @HPaulJohnson Question, should the partner pack and host pack links somehow handle l10n?

**Comment by ScottDowne** [comment]
@damiankay done https://learning.mofostaging.net/en-US/events/ and https://learning.mofostaging.net/en-US/events/resources/

**Comment by damiankay** [comment]
Thanks @ScottDowne  - we'll add the Activities and update the host pack links when available. 

Good question about the localized Host Packs though - any suggestions?

**Comment by ldecoursy** [comment]
Some of the links go to other Maker Party sites/documents that are being localized, others don't (online forum, for example). I'm not sure about the social media toolkit, though - @HPaulJohnson do you know? @lucyeoh do you know if the sample planning meeting agenda is being localized? The last two links in the doc (for the open web stretch and Chad's blog post) are not localized.

**Comment by ScottDowne** [comment]
So, all that's left is the activities need links, then I can place them in.

Also, to deal with any localized assets not currently being linked to.

I think both of those can and should be refiled in specific tickets, so closing this, and spawning into two new tickets. :rocket: :monkey:

**Comment by damiankay** [comment]
Thanks @ScottDowne - we'll also need to update the link to the host pack I believe.

**Comment by ScottDowne** [comment]
https://github.com/MozillaFoundation/Advocacy/issues/498
and
https://github.com/MozillaFoundation/Advocacy/issues/499

Should be used for future issues around links.
