### ISSUE TITLE
PayPal test donation flow is broken

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#453]
Not sure when this happened, or what the cause is yet.

Production donations using the real paypal account are still working, but, using staging, with test donation credentials is broken.

**Comment by valianttry** [comment]
@ScottDowne can you please ticket task(s) related to this and assign milestones / assignees; etc? Or just edit this ticket to quantify a piece of work we can track. TY!

**Comment by ScottDowne** [comment]
I was hoping it was something on paypal's end and would sort itself out, still busted though.

We should consider broken tests as a priority so we can continue to ship changes with confidence.

**Comment by ScottDowne** [comment]
Small update, seems it's just locally that the test is busted, still works on staging, which probably makes this less critical.

I'll poke around for  few more minutes, but likely going to p2 this I don't find anything.

**Comment by ScottDowne** [comment]
Fixed: https://github.com/mozilla/donate.mozilla.org/pull/1643

Looks like PayPal changed their password requirements for sandbox accounts. Ours was previously testtest, which started to fail. It needs a cap, special character, and a number now. I updated it to TestTest1. with the period...
