### ISSUE TITLE
Update copy in Pontoon

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#454]
Detailed description of work:
Hi @ScottDowne - there has been a request to update one of the base strings in Pontoon. Ton has asked that we change "login" to "log in" for EN-US and EN-GB. 

This sounds like a change that would affect many projects; any idea who would need to be looped in before making the change?

**Comment by ScottDowne** [comment]
@damiankay sorry, must have missed this, and caught it with a regular triage of my own bugs.

I can make that change on en-US and en-GB quite easily, only question I have is, to confirm that it's the "login" button on the "Already have an event? Login" bit here: https://learning.mofostaging.net/en-US/events/

![login](https://cloud.githubusercontent.com/assets/197334/18878781/e822b2ea-849f-11e6-9dcf-73ca328db6f8.png)

Once I make that change, all non English languages are going to have just that string out of date, and it'll display the previously translated string instead. We would need to let people know that there has been a copy change.

**Comment by ScottDowne** [comment]
FIxed this, and found a few other little nits in the copy that I fixed.
