### ISSUE TITLE
v2 Petition Site QA: Add Video Events for GA tracking

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#455]
I've added a couple of GA events to the Lightcase function in script.js in order to help us track how people engage with the videos. @gholme4 could we try implementing the code below? Please let me know if you have any questions. Thanks!

`/**
        * Initialize all instances of lightcase for modal content
        *
        */
        this.initLightcase = function () {
            $("span.media a").attr("data-rel", "lightcase:media");
            $('a[data-rel^=lightcase]').lightcase({
                video: {
                    width : 800,
                    height: 450
                },
                onFinish: {
                    contentLoaded: function() {
                        console.log("finished");
                        // Trigger Play Event in GA
                        var vidId = $(".lightcase-contentInner video").attr('src').split('mp4-format/');
                        ga('send', 'event', { eventCategory: 'Video', eventAction: 'Video Started', eventLabel: vidId[1]});
                        //Track Video Time in GA
                        var nextPercentDone = 0.25;
                        $(".lightcase-contentInner video").ontimeupdate = function() {
                            var vidId = $(this).attr('src').split('mp4-format/');
                            if (video.currentTime/video.duration >= nextPercentDone) {
                                ga('send', 'event', { eventCategory: 'Video', eventAction: (nextPercentDone * 100) + "% complete", eventLabel: vidId[1]});
                                nextPercentDone = nextPercentDone + 0.25;
                            }
                        };
                        $(".lightcase-contentInner video")[0].onended = function () {
                            // Track Video End in GA
                            var vidId = $(this).attr('src').split('mp4-format/');
                            ga('send', 'event', { eventCategory: 'Video', eventAction: 'Video Ended', eventLabel: vidId[1]});
                            lightcase.close();
                        };
                    }
                }
            });
        };`

**Comment by vojtechsedlak** [comment]
Ok, that code looks garbled, I will email you @gholme4 with the file. Sorry about that.

**Comment by gholme4** [comment]
@vojtechmzl @damiankay #readyforreview
