### ISSUE TITLE
Maker Party: Add CTAs

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#456]
Detailed description of work:
@HPaulJohnson I'm moving your comment about the copy for "Optional Link Menu" and "Host Kit" x 3 here. 

It would be great to use this to link to the MP home page on learning, as well as directly to the Host Pack. I think you said that we should have this copy localized already. Would it be in the copy deck? 

What copy should we use in place of "Optional link menu"? Would be great to find copy that's already localized for this as well.

**Comment by HPaulJohnson** [comment]
@damiankay we didn't actually plan for this "optional link menu" to be included so we didn't write copy for it. i'd suggest we just remove. 

The two things we did write copy for were a Host CTA and a share CTA. Copy (from deck) for these is: 

[Host CTA]
Become a Host
Mobilize and educate your community to take action through making by running your very own event using our tools and activities.
(learn more)

[Copyright Campaign Promo]
Join Maker Party. Make a Difference on Copyright reform in Europe. 
Help us spread the word (share)

Again, not really designed for a menu of links. I'd suggest we leave the Host CTA as is (it's already in the design), remove the link menu and add in a Share CTA. 

I think the Host pack is more appropriate for the host a party pages not a more general page like this which we will be driving attendee traffic to. Make sense?

**Comment by damiankay** [comment]
Ok @HPaulJohnson - that makes sense. Unfortunately they didn't make it into the comps. 

@jendc123 I know it's late to be adding content, but is it possible for Martha to create these CTAs? There were in the copy deck but we didn't catch that they didn't make it into the comps.

**Comment by jendc123** [comment]
@damiankay  I will let you know the timing on this pieces.  I hope to get it in the designs today.

**Comment by damiankay** [comment]
Thanks @jendc123

**Comment by Barfaaa** [comment]
@damiankay Here are two mockups. Let me know what you think and/or if there are other elements I should use for these CTAs. 
![event list - sidebar - ctas - v1a](https://cloud.githubusercontent.com/assets/8924671/18768733/289edee2-80dc-11e6-9771-2783dc294117.png)
![event list - sidebar - ctas - v1b](https://cloud.githubusercontent.com/assets/8924671/18768734/289f5b60-80dc-11e6-8f1c-1240230fbb21.png)

**Comment by damiankay** [comment]
Thanks @Barfaaa !

@lovegushwa @HPaulJohnson @geroter can you review and provide feedback please?

**Comment by Barfaaa** [comment]
**Lol** my name on here is @barfaaa haha! Must have set that up ages ago. (for context, Martha > Marf > Barf > Barfa thanks to friends and family, partially with the help of the movie _Space Balls_ i think.)

**Comment by damiankay** [comment]
I had to say I was wondering Martha! :-)

**Comment by HPaulJohnson** [comment]
These are great. Personally, I like the "Become a Host" CTA from version 1 and the "Share" CTA from version 2.

**Comment by damiankay** [comment]
Thanks @HPaulJohnson - @geroter @shaghdoosti @lovegushwa please chime in if you disagree, otherwise we'll ask Fission to integrate the CTAs tomorrow.

**Comment by jendc123** [comment]
Hi @damiankay are we good to go on implementing "Become a Host" CTA from v1 and "Share" CTA from v2. Thanks!

**Comment by damiankay** [comment]
Hi @jendc123 - yes, please go ahead. Thanks!

**Comment by jendc123** [comment]
@damiankay - we have made the update.  Is this the final text for both CTA's?

**Comment by damiankay** [comment]
@jendc123 - yes. The copy is out for translation now.
