### ISSUE TITLE
v2 Petition QA: Change Body Text Colour

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Advocacy#457]
@gholme4 @damiankay @lovegushwa After seeing the implementation of #4a4a4a for the Body copy we're finding it a bit too light after all. We're hoping to change it to #292929 which is just a touch darker. Again, please and thank you! 
# **Old:**

<img width="1440" alt="4a4a4a jog" src="https://cloud.githubusercontent.com/assets/20977376/18724579/e71a426c-800a-11e6-9290-5f5729d35d73.png">
# **New:**

![292929](https://cloud.githubusercontent.com/assets/20977376/18724588/f053d55a-800a-11e6-84ee-09a39ed2d16b.jpg)

**Comment by gholme4** [comment]
@beccaklam @damiankay I changed the text color. #readyforreview
