### ISSUE TITLE
Maker Party Social Promos

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#459]
Detailed description of work:
With v2 social nearing completion in #200, the final copy/design sprint for social will be around promos for Maker Party. The objective of these promos will be to drive attendance to various events in the EU and as such targeted to our tier 1 locales. Events are being seeded over the next 2 weeks, so we expect that we'll put these into market around 10/10

_Start date: September 21, 2016_ 
_Due date: October 10, 2016_ 

NOTE: We'll need to ship copy for localization by 10/3 to hit this deadline. 

CC: @lovegushwa @KevZawacki

**Comment by HPaulJohnson** [comment]
Kicked this 1-week sprint off today. Broken into 3 parts: 

1) Assets for Social Stunt on 10/5 (due eod Tues, 9/26)
- 2-3 visual assets (static or .gif). @natalieworth already making good progress on this.
- 1-2 snippet icons, also to be repurposed for email graphic. @lovegushwa is working on this one and may reuse some of Natalies work on social assets. 

2) Attend a Party Promos (due eod. Fri, 9/30 for localization)
- 6-9 versions of copy for FB, Twitter and Instagram posts @hpauljohnson @KevZawacki on the hook for copy
- 3-5 visual assets to be used in conjunction with above posts. @lovegushwa @beccaklam @natalieworth 
- Creative brainstorm to be scheduled for Tuesday, 9/27

3) System for storytelling with "Best of Maker Party" UGC content
- template for surfacing stories and photos from successful parties
- curation and retweeting strategy for everything tagged with #makerparty 

Progress to be tracked in this doc as we go: https://docs.google.com/document/d/1vKfoSGQ_RzRhK4R2s5YvM88vM-RJdXxz5617azsC7gM/edit

**Comment by KevZawacki** [comment]
I've selected two tweets from each category, tightened them up, and placed them in an approval doc [here](https://docs.google.com/document/d/1AqwFLAogCRQxmjiAA6_DFmgfD4OqtHztpYR-UaGisU8/edit). @HPaulJohnson, let me know if I can help further.

@beccaklam, you can drop links to your completed graphics into [the top of the document](https://docs.google.com/document/d/1AqwFLAogCRQxmjiAA6_DFmgfD4OqtHztpYR-UaGisU8/edit). Paul and I can take it from there.

**Comment by HPaulJohnson** [comment]
These have been shipped for policy approval. Once approved, I will close this ticket and create a new one for localization.

**Comment by brettgaylor** [comment]
Hey all - just playing wrangler here - Raegan has approved this, @shaghdoosti has indicated she doesn't need to approve.

So @HPaulJohnson , @lovegushwa , @KevZawacki looks like this is OK to submit to L10N as per #548

**Comment by HPaulJohnson** [comment]
Everything but the stunt tweets are ready to localize. I'm chasing down Maura to see how she wants to update this language. 

@brettgaylor Are we doing this via l10n or Kontextor?

**Comment by valianttry** [comment]
I can help you submit this to Kontextor Paul!

**Comment by HPaulJohnson** [comment]
These are approved and ready for localization. Final copy here:

https://docs.google.com/document/d/1AqwFLAogCRQxmjiAA6_DFmgfD4OqtHztpYR-UaGisU8/edit?ts=57eecf41
