### ISSUE TITLE
Maker Party: Event sharing error

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#460]
From [QA spreadsheet](https://docs.google.com/spreadsheets/d/1v6hU6ggrAlTCABRc67Fcg3CExI9x3v1lL1BL7gbtk5M/edit#gid=0)

Reported by @ldecoursy 

After creating an event, clicking on the "share" button redirects to a broken link in Mac Chrome and Firefox. Screen shots attached. 

CC: @jendc123 @gholme4

![screen shot 2016-09-21 at 2 57 10 pm](https://cloud.githubusercontent.com/assets/19785709/18731091/bac8e5b6-800e-11e6-97d8-0fe176015776.png)
![screen shot 2016-09-21 at 3 17 00 pm](https://cloud.githubusercontent.com/assets/19785709/18731092/bada31b8-800e-11e6-929f-21b17ef26c78.png)

**Comment by gholme4** [comment]
@damiankay This has been reported to NationBuilder. The following is support's latest update:

---

Hi George, 

I wanted to let you know that we're going to create a private test site on the nation so that we can isolate if the problems are stemming from SSL or site level customizations. We'll remove the site when we've completed the tests. 

Best,
Lauren Rowse
NationBuilder Support

**Comment by damiankay** [comment]
That's great - thanks for the quick action @gholme4

**Comment by damiankay** [comment]
Hi @gholme4 - any updates from Nationbuilder on this issue?

**Comment by gholme4** [comment]
@damiankay Not yet. I'll let you all know when I do.

**Comment by damiankay** [comment]
@gholme4 - could you please CC me on the email? I'll try to escalate it, as this is a pretty major blocker for us.

**Comment by gholme4** [comment]
@damiankay Will do.

**Comment by damiankay** [comment]
@gholme4 I didn't see an email yet. Can you forward please? We really need to clear this issue. Thanks!

**Comment by jendc123** [comment]
@damiankay I just forwarded you the thread.

**Comment by damiankay** [comment]
@gholme4 - here's an update that just came through from Nationbuilder related to this issue: 

> It appears the reason the redirect issue is happening is due to the NationBuilder-Twitter & Facebook authentication being disabled. It can be easily reenabled here: https://mozillafoundation.nationbuilder.com/admin/authentication_modes. Since this wasn't immediately obvious, our product team has pledged to make this experience better by designing a better error message moving forward. So definitely appreciate you flagging this for us here.
> 
> That said, we usually do not recommend turning off authentication because it powers the integrations we have for social sharing.
> Sometimes folks like to turn off this feature with the idea that it will disable Facebook or Twitter logins on the website. A workaround in this case is to simply just strip off the login links from the /admin page and the homepage. This ensures that the authentication stays in place, while cosmetically, inhibiting users from logging in through social media.

**Comment by gholme4** [comment]
@valianttry #readyforreview

**Comment by valianttry** [comment]
@ldecoursy can you test to make sure this problem was corrected?

**Comment by ldecoursy** [comment]
Worked for me in Chrome 👍 
In Firefox, I accidentally clicked "share on twitter" but I wanted to use Facebook instead. I'm having trouble getting back to the event page - it's stuck on the twitter api authentication page. Even if I open a new window and try to go directly to makerparty.community, it opens back to the same page, and when I click Cancel, Return to NationBuilder, it won't do - keeps refreshing to the twitter authentication page.

**Comment by jendc123** [comment]
Hi @ldecoursy - we are aware of this issue and have reached out to NationBuilder support. It's been escalated to their engineers.  

---

Hi George,

I sincerely apologize for misreading your previous email. A member of our product team was able to replicate the issue, and it has been escalated to our engineers.

We will keep you up to date as we have more information.

Best,
Lauren Rowse
NationBuilder Support

**Comment by gholme4** [comment]
@ldecoursy @valianttry @HPaulJohnson This will continue to be a problem for control panels users (all of us that can access the back-end or users who have created an event). General site visitors will not have the problem. Here is NationBuilder's response:

After some additional testing, it appears that this problem only occurs for control panel users. While we recognize that this is not ideal, control panel users can share their pages directly from the control panel. All other users should be able to share their events and RSVPs from the front facing site as expected. 

Please let us know if you encounter any problems with this workaround!

Same issue as #525

**Comment by valianttry** [comment]
Closing WONTFIX
