### ISSUE TITLE
Maker Party: Update Footer

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#461]
Footer used on makerparyt.community pages is wrong and should be updated to reflect the copy deck. Changes include: 
- Remove "share this page" option
- Add "code of conduct" link
- Update destination URLs for legal and privacy links.

Details on page 5 of copy deck: https://docs.google.com/document/d/16ObBANwvduy59NjYC3aOF9cIPsDG3RdGszmHwqXHPv4/edit

**Comment by damiankay** [comment]
@jendc123 @gholme4

**Comment by gholme4** [comment]
@HPaulJohnson Please list the correct URLs for the footer links here.

**Comment by HPaulJohnson** [comment]
Here is what I have for the footer: 
- Contact Us: makerparty@mozillafoundation.org (note: this isn't live yet but working on getting it setup by Monday)
- Join the Conversation: https://medium.com/mozilla-advocacy
- Legal: https://beta.webmaker.org/#/legal?_k=gelv6e (i know this is weird - Webmaker and all, but it's what Abigail has requested)
- Privacy: https://www.mozilla.org/privacy/websites/
- Code of Conduct: (? need to find out; see below)
- Donate: https://donate.mozilla.org

RE: Code of Conduct link in footer, @shaghdoosti @geroter is this something we want and need? I was assuming it was given these are in-person events. If we do want to include a link, do we have an existing CoC for participation that we can link to?

**Comment by jendc123** [comment]
Hi @HPaulJohnson @damiankay which Font Awesome icon do we need to use for Code of Conduct?

**Comment by valianttry** [comment]
@lovegushwa do you know the answer to this Q re: Font Awesome?

**Comment by HPaulJohnson** [comment]
contact us email address needs to be updated with a new alias that is hooked into desk.com. The updated email is:

makerparty@mozillafoundation.org

**Comment by valianttry** [comment]
@shaghdoosti can you confirm that we should link to the "Community Participation Guidelines" Which are here: https://www.mozilla.org/about/governance/policies/participation/?

**Comment by shaghdoosti** [comment]
Yes - that seems right to me.

**Comment by HPaulJohnson** [comment]
@valianttry email address for contact us in the footer still needs updating. It should be:

makerparty@mozillafoundation.org

**Comment by valianttry** [comment]
@gholme4 and @jendc123 this is a pretty easy one, can you fix?

**Comment by gholme4** [comment]
@valianttry @HPaulJohnson I changed the contact link. What of the Cod of Conduction link and icon?

**Comment by valianttry** [comment]
@lovegushwa ANOTHER ICON PLZ

**Comment by lovegushwa** [comment]
@gholme4 please replace the "Medium" icon with "code of conduct:"
https://drive.google.com/file/d/0B2qu3ExKWIlvSHhMTElscGlnY0k/view?usp=sharing

Should like to here:
https://www.mozilla.org/about/governance/policies/participation/

<img width="794" alt="screen shot 2016-10-09 at 10 42 32 pm" src="https://cloud.githubusercontent.com/assets/12228435/19227681/c645a28c-8e71-11e6-8bbc-2fd454a59e4e.png">

**Comment by gholme4** [comment]
@lovegushwa @valianttry #readyforreview

**Comment by lovegushwa** [comment]
@gholme4 I'm not seeing the code of conduct in the footer. This should replace "Medium" ... see above.

![screen shot 2016-10-20 at 12 36 37 pm](https://cloud.githubusercontent.com/assets/12228435/19575128/f16a4fe6-96c1-11e6-8be5-c1183839faa9.png)

**Comment by gholme4** [comment]
@HPaulJohnson @valianttry Hi. I replaced the Medium link with Code of Conduct.

**Comment by TheoChevalier** [comment]
And this is not localized…

**Comment by TheoChevalier** [comment]
Turned out we had the translation ready for the Maker Party website, so I reused that and pushed it on Bablic. But please, next time ping me before updating the copy on a prod website.
