### ISSUE TITLE
Maker Party: Update confirmation email FROM (sender)

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#462]
Detailed description of work:
Currently our confirmation email sent to users after signing up to NB displays as sent from Andrea  / Mozilla Foundation. I'm assuming this is because Andrea is the main account contact for NB.

Who should be listed as the sender? @HPaulJohnson @KevZawacki @shaghdoosti

**Comment by damiankay** [comment]
@jendcd123 I'll let you know when this is ready for you

**Comment by HPaulJohnson** [comment]
@damiankay is this for hosts? attendees? both? I'm not sure who the audience is for this.

**Comment by damiankay** [comment]
@HPaulJohnson this is for anyone who signs up for an account. Hosts **must** do this, so it's mostly hosts who will see this email, but it could also potentially be attendees.

**Comment by damiankay** [comment]
There's a thread about the email copy here: #135

**Comment by HPaulJohnson** [comment]
Ok, in that case, I'd suggest @shaghdoosti be listed as the sender on this email.

**Comment by damiankay** [comment]
Ok, so Mozilla Advocacy / @shagdoosti? 

(in one location Mozilla Foundation is listed, in another Andrea's name is listed)

**Comment by HPaulJohnson** [comment]
I think that's right @damiankay. But I think @shaghdoosti should sign off before we close this one.

**Comment by valianttry** [comment]
This now seems to say "Mozilla Foundation". It should say from "Mozilla" but this isn't urgent. Moving to October 3 Milestone. 

![thank_you_for_joining_-_andrealw_gmail_com_-_gmail](https://cloud.githubusercontent.com/assets/9830371/18940725/c3f7e298-85bf-11e6-93e2-46f56a68dfeb.png)

**Comment by valianttry** [comment]
WONTFIX
