### ISSUE TITLE
v2 Petition QA: illustration should be optically centered 

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#463]
@gholme4 I added some transparency to the right side of this image so circle building illustration is optically centered when viewing in mobile, you should be able to replace the image with this one: https://drive.google.com/file/d/0B2qu3ExKWIlveGphYkVUcFZtdnM/view?usp=sharing

![screen shot 2016-09-21 at 5 37 10 pm](https://cloud.githubusercontent.com/assets/12228435/18733708/3ab31db0-8022-11e6-92da-a6accb21dd3e.png)

**Comment by gholme4** [comment]
@lovegushwa @damiankay #readyforreview
