### ISSUE TITLE
v2 Petition QA: replace background texture with better image

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#464]
@gholme4 grabbed a higher res background image from our Postcrimes site, please replace the pixilated image with this one: https://drive.google.com/file/d/0B2qu3ExKWIlvZ0s3ZF8ydmJGVjQ/view?usp=sharing

![screen shot 2016-09-21 at 5 38 13 pm](https://cloud.githubusercontent.com/assets/12228435/18733760/9ba42736-8022-11e6-9077-ed74b91e1d79.png)

**Comment by gholme4** [comment]
@lovegushwa @damiankay  #readyforreview
