### ISSUE TITLE
v2 Petition QA: more heart

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#465]
@gholme4 the donate heart is much smaller than the other icons. Please bump the size up so it looks like this, thank you!

![screen shot 2016-09-21 at 5 49 43 pm](https://cloud.githubusercontent.com/assets/12228435/18733924/0fb138ac-8024-11e6-8d8a-215121666a9b.png)

**Comment by gholme4** [comment]
@lovegushwa @damiankay #readyforreview
