### ISSUE TITLE
v2 Petition QA: en dash is wrong font weight

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#466]
@gholme4 the en dash used in the quote attribution should be the same font as the italic "The Register," it looks like it's bold. The other 2 quotes also have the same issue.
![screen shot 2016-09-21 at 5 53 13 pm](https://cloud.githubusercontent.com/assets/12228435/18733983/a5386eae-8024-11e6-9edb-3668b3d217f2.png)

**Comment by lovegushwa** [comment]
@gholme4 I refreshed the page and the weight looks right, but the dash now looks like a hyphen. 
Lets replace it with an EN (or if that's what it currently is then an EM dash)
<img width="318" alt="screen shot 2016-09-21 at 8 45 03 pm" src="https://cloud.githubusercontent.com/assets/12228435/18736493/6a2ace5c-803c-11e6-826a-c60979a67c45.png">

**Comment by gholme4** [comment]
@lovegushwa @damiankay #readyforreview
