### ISSUE TITLE
v2 Petition QA: section numbers are low resolution

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#467]
All the section numbers appear to be low resolution on retina. @beccaklam can you make sure @gholme4 has the assets he needs? It looks like the .svgs you made reference a font goole font, rather than being an image. If that's the case can you make them @2x OR or outline the type in the .svg

<img width="716" alt="screen shot 2016-09-21 at 5 57 23 pm" src="https://cloud.githubusercontent.com/assets/12228435/18734039/2483a372-8025-11e6-9281-71ac36355774.png">

**Comment by gholme4** [comment]
@lovegushwa @beccaklam Yes. Please provide new images for the section numbers.

**Comment by beccaklam** [comment]
@gholme4 @lovegushwa @damiankay 

Here are the updated images! I made the type outlines and saved them again as SVGs:

https://drive.google.com/file/d/0BzuBOR2VJQqUdkltR3h2X0JfVkU/view?usp=sharing
https://drive.google.com/file/d/0BzuBOR2VJQqUekI5c0k1cnlGMk0/view?usp=sharing
https://drive.google.com/file/d/0BzuBOR2VJQqUR04xVk5CcXo2cmc/view?usp=sharing

**Comment by gholme4** [comment]
Thanks @beccaklam.
@lovegushwa @damiankay #readyforreview
