### ISSUE TITLE
Finalizing Host pack design 

### ISSUE THREAD

**Issue by shaghdoosti** [MozillaFoundation/Advocacy#471]
Detailed description of work: Design for Host Pack. 

_Start date: September 22, 2016_ 
_Due date: October 03, 2016_ 

CC: @ldecoursy Can you drop in the link to the host pack - @lovegushwa the due date here is just a suggestion - if you could look at the pack, scope and say when you think it's possible that would be great. I'm hoping that we can reuse alot of the design elements from the partnership pack here.

**Comment by ldecoursy** [comment]
Link to the host pack is here: https://docs.google.com/document/d/10JRtPlrOQjOSXUnJlMOsipBrPBaTQ0X4Htc_K2mSm6I/edit#heading=h.uhwwokhzpscs

One thing to note is that the icons on the 2nd page are placeholders - we need to replace those.

Thanks @lovegushwa !

**Comment by lovegushwa** [comment]
@shaghdoosti I think we can get this sorted by end of day Monday. Will see if I can get a solid start tomorrow if I can get some irons out of the fire.

**Comment by lovegushwa** [comment]
@shaghdoosti here is a draft for review: 
https://docs.google.com/a/mozilla.com/presentation/d/1OpV62j95tN-CuRy2RGWuKXw1P1OS9Vs-94DzkjXS8Po/edit?usp=sharing

**Comment by valianttry** [comment]
FYI zipped localized host packs are here, if helpful:

[Maker Party Host Pack_Translations.zip](https://github.com/MozillaFoundation/Advocacy/files/499754/Maker.Party.Host.Pack_Translations.zip)

**Comment by shaghdoosti** [comment]
Awesome! these look great. All we need is link to the survey @ldecoursy do you have that by any chance?

**Comment by ldecoursy** [comment]
@shaghdoosti I don't - 270s planning doc is here although I'm not sure it's final or who is creating the actual survey: https://docs.google.com/document/d/1VM4Rt9X6y8TG1qgXAr6G6CQdyiI0fvBwyho40Csf244/edit#heading=h.drmkm5rhp9kd

**Comment by shaghdoosti** [comment]
Hey - 

270 is in charge of working on the survey - it's going to take a few days to get it. We should move ahead and drop the link later.

**Comment by lovegushwa** [comment]
@shaghdoosti I recommend we make a page at the start of the deck that includes links to gdocs or PDF files of the other languages. So the deck acts as a hub, and links out to the translated text docs.

**Comment by lovegushwa** [comment]
Here are the translated decks, as noted by Kristina these all a bit of translation of the title page.

"Join Maker Party. Make a difference."
and "Sept-Nov 2016"  

is needed in all languages

EN
https://docs.google.com/presentation/d/1OpV62j95tN-CuRy2RGWuKXw1P1OS9Vs-94DzkjXS8Po/edit?usp=sharing

PL
https://docs.google.com/presentation/d/1bUkd1zWFJdzitS2i7ykWsF5xteFcrXAy6W2IhOJlXH0/edit?usp=sharing

IT
https://docs.google.com/presentation/d/15Rkio1xrM4I3H20OhQZUgArEtxWJIJWAFScvT0H9Dv0/edit?usp=sharing

DE
https://docs.google.com/presentation/d/1Or0fja5tUXGONvVEI9IiH772t2Rss1EoRDeCX32syzI/edit?usp=sharing

ES
https://docs.google.com/presentation/d/12hDy1vnd73GBRXUxiFIN_sr7lJ8e_5k3vtQfYW5SfdI/edit?usp=sharing

PL
https://docs.google.com/presentation/d/1BG7qk2HvSgIax2oaFKXThT_jEjdh8YfeHeTeVZjxDdk/edit?usp=sharing
