### ISSUE TITLE
Copyright Petition: V2.5 form validation

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#472]
Detailed description of work:
@lovegushwa can you please sync with @jendc123 on how the new form will validate? Jennifer, can you add more detail for Jordan please? 

CC: @brettgaylor @valianttry @beccaklam

**Comment by jendc123** [comment]
Hi @lovegushwa - we don't know how you anticipated this form to show validation error. We currently have it validating each form field which isn't great UX.  Can you provide us with quick walk through of what you had in mind. Also happy to hop on call.

**Comment by lovegushwa** [comment]
@jendc123 looking into this. Will speak with @beccaklam and get back to you asap.

**Comment by beccaklam** [comment]
Hi @jendc123 and @gholme4, we redesigned the form and this is what we would like the back button to look like:
![formwithbackbutton](https://cloud.githubusercontent.com/assets/20977376/18767384/d64a59b2-80ec-11e6-85c6-8da06e99f80c.png)
I've attached the arrow here:
https://drive.google.com/file/d/0BzuBOR2VJQqUZDdaRXByc3pxWEk/view?usp=sharing
CC: @lovegushwa @damiankay

**Comment by lovegushwa** [comment]
@gholme4 I checked out the new form and realize the UI is now busted when looking at the check boxes. Sorry about the back and forth here. Also 

<img width="808" alt="screen shot 2016-09-22 at 9 08 32 pm" src="https://cloud.githubusercontent.com/assets/12228435/18773996/68dac34a-8109-11e6-8665-249f5727adf9.png">

Here is a alternate solution, @beccaklam you want to weigh in here? 

<img width="769" alt="screen shot 2016-09-22 at 9 07 52 pm" src="https://cloud.githubusercontent.com/assets/12228435/18774013/9e3e64d8-8109-11e6-9d7f-6dbc3eb7a2a3.png">

**Comment by lovegushwa** [comment]
@gholme4 still can move backwards without first filling in the field. Is this something we can solve? 

<img width="787" alt="screen shot 2016-09-22 at 9 19 45 pm" src="https://cloud.githubusercontent.com/assets/12228435/18774078/57858548-810a-11e6-929c-51824be7de4e.png">

**Comment by beccaklam** [comment]
Hi @lovegushwa @gholme4 here are all the steps with Jordan's new design implemented:
![form_v3](https://cloud.githubusercontent.com/assets/20977376/18790903/a37ebe78-817e-11e6-9ac7-06c676d881b1.png)
I also agree that we need to fix the inability to move backwards without first filling in the field. We were told that creating the back button would fix this problem? @jendc123 Also we are finding on desktop and tablet that the 'thank you' step of the form (^see above) has not been implemented? Can we please add that? Thank you!

**Comment by jendc123** [comment]
@lovegushwa @beccaklam @damiankay, please hold off on testing for full functionality.  We are making updates and will circle back.

**Comment by jendc123** [comment]
Hi @lovegushwa @beccaklam @damiankay - a couple of things to raise on the form. In your version above with the back button on the right hand side, we wanted to flag that it may confuse users since it appears to be inside the field.  We suggest using a back button on the left hand side 

<img width="613" alt="form buttons" src="https://cloud.githubusercontent.com/assets/6034476/18796951/9037eebe-8199-11e6-893b-385f69b36099.PNG">

We have also updated the styling for the form navigation below the fields so it eliminates any confusion around using them to move back/forth within the form.

**Comment by beccaklam** [comment]
Hi @jendc123 sure we can do the left side arrow but can we have it look like this:
![form_sept23](https://cloud.githubusercontent.com/assets/20977376/18798961/20e2b666-81a3-11e6-9406-a1d2565e39d2.png)
CC: @lovegushwa @damiankay
