### ISSUE TITLE
Maker Party QA: Changing Google Analytics Tracking ID

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#473]
The tracking on the Maker Party Events site currently uses the ChangeCopyright.org ID. It needs to be updated to UA-35433268-71.

**Comment by gholme4** [comment]
@vojtechmzl @damiankay  #readyforreview

**Comment by vojtechsedlak** [comment]
Thanks for the update @gholme4. Works great.
