### ISSUE TITLE
v2.5 petition QA: Adding GA event to multiple step form

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#476]
I've sent an email to George with details on this. We need to add a custom event to each step of the form, so that we can track user attrition within the signing process. Just logging it here for tracking purposes.

**Comment by gholme4** [comment]
@vojtechmzl #readyforreview

**Comment by vojtechsedlak** [comment]
Perfect. Works great. Thanks for your help @gholme4!
