### ISSUE TITLE
v2.5 Petition Site QA: Confirmation email content

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#478]
As experienced in earlier testing on v2, the v2.5 form is generating a confirmation email that needs to be turned off. 

Screenshot:
![email_confirm](https://cloud.githubusercontent.com/assets/10078715/18767145/6802b7ca-80d2-11e6-9115-0358cfc05031.jpg)

@damiankay

**Comment by damiankay** [comment]
@jendc123 @gholme4

**Comment by gholme4** [comment]
@HPaulJohnson @damiankay   #readyforreview

**Comment by HPaulJohnson** [comment]
looks good @gholme4 . no email received after submitting the form. closing.
