### ISSUE TITLE
v2 Petition QA: share buttons jump right when scrolling

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#479]
@gholme4 the share buttons jump from a fixed position next to the copy, to the right edge of the browser. I prefer the sticky buttons stay next to the copy (1st location) while scrolling down the page if possible.

1st location
![screen shot 2016-09-22 at 3 47 19 pm](https://cloud.githubusercontent.com/assets/12228435/18768700/eacc5e6e-80db-11e6-9ad0-8d93d858685d.png)

sticky location 
![screen shot 2016-09-22 at 3 47 27 pm](https://cloud.githubusercontent.com/assets/12228435/18768702/ed867aa4-80db-11e6-8289-6e3b26f7a655.png)

**Comment by gholme4** [comment]
@lovegushwa That isn't possible with CSS because the fixed buttons are positioned relative to the window. When they aren't fixed they are positioned relative to the content container.

**Comment by lovegushwa** [comment]
@gholme4 can fix the buttons to the left "sticky location" above (which is relative to the window.)

**Comment by lovegushwa** [comment]
@gholme4 can you fix the buttons to the right side of the browser window as a compromise? (would look something like the "sticky location" show above?)

**Comment by gholme4** [comment]
@lovegushwa #readyforreview
