### ISSUE TITLE
video in encrypt covers some text

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#48]
This is only really an issue because it's not selectable and thus not interactive for translating purposes.

If you hover over the text under the video on this page, you can see it's not allowing it to be easily translated in place.

https://mozilla-pontoon-staging.herokuapp.com/sl/mozilla-advocacy/Direct%201/

**Comment by damiankay** [comment]
Hey @ScottDowne - is this still an issue?

**Comment by hannahkane** [comment]
Closing as we're no longer working on this.
