### ISSUE TITLE
v2 Petition QA: smooth animation for v2.5 sticky petition transition

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#480]
@gholme4 

v2 sticky bar animates in nice and smooth from the bottom of the page
Can we apply the same animation to the v2.5 petition sticky bar? 

![form-animation](https://cloud.githubusercontent.com/assets/12228435/18769079/ce8656d0-80de-11e6-96ef-846db729b5fe.gif)

**Comment by gholme4** [comment]
@lovegushwa @damiankay #readyforreview

**Comment by lovegushwa** [comment]
@gholme4 looks great! thank you.
