### ISSUE TITLE
Poster videos for youtube

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#481]
Can we upload some custom images so that the youtube poster frame isn't randomly chosen?  Always makes a big diff.  We should do this for Facebook when we post there, too.

**Comment by KevZawacki** [comment]
@brettgaylor Definitely! What'd you have in mind?

To see the thumbnails that are currently being used, log in to our YouTube channel and view our unlisted videos. Ping me if you need credentials.

**Comment by natalieworth** [comment]
@brettgaylor @KevZawacki do you know if I need to export a static image to upload for them? Or are we able to directly select a frame within the youtube/ social media platforms?

**Comment by KevZawacki** [comment]
@natalieworth You can select from three frame options YouTube provides, or upload a custom one. See below:

![screen shot 2016-09-23 at 2 07 52 pm](https://cloud.githubusercontent.com/assets/11045250/18796411/20074d76-8197-11e6-90d1-66e54c00bcf9.png)

@brettgaylor Did you have specific ideas in mind? In a lot of cases, the options YouTube gives us are pretty good. For example, the CSI: GIF title screen frame option above.

**Comment by brettgaylor** [comment]
@KevZawacki  i believe @natalieworth  uploaded screen grabs I believe for each video - they are in a google drive folder together (right?). I feel they are better because they don't have subtitles (ie "its our job to track down" is kind of without context) and are chosen based on being compelling graphically.  Youtube sometimes has the right ones for sure, but the "custom thumbnail" option almost always better.

**Comment by natalieworth** [comment]
@KevZawacki I'll grab the one's I passed along to Jordan for the website

**Comment by natalieworth** [comment]
@KevZawacki Here's images exported directly (without subtitles):
Explainer Video: https://drive.google.com/file/d/0B20-0lpP23c0eXVkMjNZMk9DQWc/view
Meme Jail Video: https://drive.google.com/file/d/0B20-0lpP23c0S0NualotUjZjdHc/view
CSI Video: https://drive.google.com/file/d/0B20-0lpP23c0ZGUwQUh5cS0yaHM/view

**Comment by brettgaylor** [comment]
exactly!

**Comment by natalieworth** [comment]
:D @KevZawacki Let me know if those work or it you need help with them

**Comment by KevZawacki** [comment]
@natalieworth These are perfect! I'll update :-)
