### ISSUE TITLE
Copy creation: Explainer Video

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#482]
Detailed description of work: Create and route copy to create an email compelling our list to watch our new video, with pugs. 
https://docs.google.com/document/d/1ip38M5aGZCMVrgZBxtmvkJC3k0Q8QXeOAV-7-b-YY74/edit
Send Date: 9/27/16
**Currently in routing**

_Start date: September 1, 2016_ 
_Due date: September 26, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @cristina-moon @valianttry @shaghdoosti

**Comment by stephaniemcv** [comment]
Associated design ticket #483

**Comment by stephaniemcv** [comment]
Associated build ticket #484

**Comment by stephaniemcv** [comment]
Associated QA ticket #485

**Comment by valianttry** [comment]
Copy was reviewed and approved. Final copy has been submitted to Kontextor for localization.
