### ISSUE TITLE
Design: Explainer Video email

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#483]
Detailed description of work: Image request for hero image (600x300px). Using template on the left, need play button and text "Watch our new video, with pugs"
<img width="921" alt="0f262b50-7e7a-11e6-9582-acafce3d159d" src="https://cloud.githubusercontent.com/assets/11812272/18789669/088f5482-8169-11e6-9542-c8a90898f4b6.png">

_Start date: September 23, 2016_ 
_Due date: September 26, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @shaghdoosti @valianttry

**Comment by valianttry** [comment]
@stephaniemcv our text is going to be significantly longer than the legth showing in the template, left. Seems like that's probably OK but just wanted to flag. Final copy is being localized here: https://docs.google.com/spreadsheets/d/1dBARa2Pr9NB_Q5ZdPOV1Jx9NOLbATSPk3etSfCWHTkk/edit#gid=683702336

**Comment by valianttry** [comment]
@stephaniemcv our text is going to be significantly longer than the length showing in the template, left. Seems like that's probably OK but just wanted to flag. Final copy is being localized here: https://docs.google.com/spreadsheets/d/1dBARa2Pr9NB_Q5ZdPOV1Jx9NOLbATSPk3etSfCWHTkk/edit#gid=683702336

**Comment by stephaniemcv** [comment]
Not a problem. Text will also not be center justified as in the image. We used this template with the Encryption Campaign and some pretty lengthy copy there. Image with play button consistently got lots of clicks.

**Comment by beccaklam** [comment]
@stephaniemcv @valianttry @lovegushwa Here is the hero image :https://drive.google.com/a/mozilla.com/file/d/0BzuBOR2VJQqUcjhOV3BNM2poN00/view?usp=sharing Let me know if you need any changes/save at a different resolution.

**Comment by stephaniemcv** [comment]
Woo! Thanks @beccaklam! I'll ping you when we have the localizations, so we can swap the text.

**Comment by stephaniemcv** [comment]
@beccaklam I need four hero images localized for DE, FR, ES, PL. Translations are on row 4 here: 
https://docs.google.com/spreadsheets/d/1dBARa2Pr9NB_Q5ZdPOV1Jx9NOLbATSPk3etSfCWHTkk/edit#gid=683702336

**Comment by beccaklam** [comment]
@stephaniemcv Here are all the images as PNGs. Let me know if you prefer them as JPEGs. 
https://drive.google.com/drive/folders/0BzuBOR2VJQqUdGNWbThMSEVma28?usp=sharing The files are labeled by the language.

**Comment by lovegushwa** [comment]
CC @lovegushwa
