### ISSUE TITLE
Build: Explainer Video Email

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#484]
Detailed description of work: Code and load copy & design

_Start date: September 26, 2016_ 
_Due date: September 26, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by valianttry** [comment]
@stephaniemcv --  Kontextor's localizations will end up in the email tab here:
https://docs.google.com/spreadsheets/d/1dBARa2Pr9NB_Q5ZdPOV1Jx9NOLbATSPk3etSfCWHTkk/edit#gid=683702336

You'll have to ask @brettgaylor for the final URLs. This is the first video we are hosting on YouTube, so the URL situation might be a bit different. Also ccing @vojtechmzl to make sure we get all our tracking set up correctly. 💯

**Comment by brettgaylor** [comment]
@stephaniemcv just quickly discussed with some media folks - we have a strong preference for just linking right to the petition page, where the video will have a prominent cal to action with a play button.  So we would prefer _not_ linking to youtube.

That URL will simply be changecopyright.org.  A preview of what that will look like, with the play button as it will exist, is here:
https://petitionv25-mozillafoundation.nationbuilder.com/

To ensure pull through of that CTA you could make the image in the email v. similar, with a play button.

**Comment by stephaniemcv** [comment]
@brettgaylor 
Image request with play button already submitted to our designers #483 ^_^
