### ISSUE TITLE
QA: Explainer Video Email

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#485]
Detailed description of work: Review Group, please check copy, rendering and link functionality and place edits/issues in this ticket

_Start date: September 26, 2016_ 
_Due date: September 27, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by valianttry** [comment]
For all of them: Including clicking on the URL in the emal -- it takes 3 clicks to actually get the video to play, which isn't ideal UX. You 1) click the link to open the petition page; 2) Click the red circle "play" button in the center; and 3) have to click the ">" arrow on the video box. Is there any way to simplify and set one of these to just "auto play"?

DE: Is "Hallo" correct German for "Hello"? I noticed ES is also "Hallo". Approved though I couldn't get the videos to play to make sure it's the German version. (Hotel wifi sadface). I trust you checked!

ES: Is "Hallo" correct for salutation? Not "Ola"? Checked copy and all links, approved.

PL: Again, "Hallo" -- not PL. Sorry I forgot to get this translated but I believe the greeting is available in a past spreadsheet for past email stranslation. The text and links worked as expected and the locale matched.

FR: "Hallo" - get correct FR salutation.

**Comment by stephaniemcv** [comment]
UX: Mine is playing in two clicks, I can't replicate the ">" in the video box. And I don't think this can be fixed in email.

Greetings: All updated to correct language. 

Putting the kibosh on the PL email, currently we don't have a PL version video.

**Comment by valianttry** [comment]
all good! No new tests needed. Approved.

**Comment by valianttry** [comment]
all good! No new tests needed. Approved.
