### ISSUE TITLE
Email: Host a Maker Party

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#486]
Detailed description of work: Create and route copy for invite email about a host.
Audience: Anyone on existing Maker Party lists; anyone who signs the petition. Localization: DE, FR, EN-UK, ES, PL 
Draft: https://docs.google.com/document/d/1TiwEl_pmwSSf5YUt2GjGfj9BfPebJBLgGbHQ2GYM-aw/edit
Send date: 9/29/16

@shaghdoosti @valianttry can you please choose a variant and start the approval routing process?

_Start date: September 1, 2016_ 
_Due date: September 27, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @cristina-moon

**Comment by stephaniemcv** [comment]
Associated design ticket #487

**Comment by stephaniemcv** [comment]
Associated build ticket #488

**Comment by stephaniemcv** [comment]
Associated QA ticket: #489

**Comment by cristina-moon** [comment]
Hey @stephaniemcv there is another ticket for this (#135). Do you want to consolidate? If not, I can respond in both.

**Comment by cristina-moon** [comment]
I'm rewriting the email copy today 11am-1pm pt based on guidance from @shaghdoosti. 270 is also helping!

**Comment by cristina-moon** [comment]
[Updated email draft copy (2 variants) is here](https://docs.google.com/document/d/1TiwEl_pmwSSf5YUt2GjGfj9BfPebJBLgGbHQ2GYM-aw/edit) for feedback from @shaghdoosti and @valianttry

**Comment by valianttry** [comment]
Sara is now routing this through approvals.
