### ISSUE TITLE
Build: Host a Maker Party email

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#487]
Detailed description of work: Image request for call out box image (200x200px). Using template on the right with text "Host a Maker Party for EU copyright reform"

<img width="921" alt="0f262b50-7e7a-11e6-9582-acafce3d159d" src="https://cloud.githubusercontent.com/assets/11812272/18790553/79cf1274-816c-11e6-9f6b-fe33078a04e3.png">

_Start date: September 23, 2016_ 
_Due date: September 27, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @shaghdoosti @valianttry

**Comment by lovegushwa** [comment]
@stephaniemcv some general makerparty email graphics here:
https://drive.google.com/drive/folders/0B2qu3ExKWIlvOVlyTkRDTXE2cVE?usp=sharing

I'd like to make these more specific to the copy, will borrow from the social assets @beccaklam is making and post something tomorrow.

**Comment by lovegushwa** [comment]
@stephaniemcv let's go with these options:
https://drive.google.com/file/d/0B2qu3ExKWIlvOVJ3T1NncUNGb3c/view?usp=sharing
https://drive.google.com/file/d/0B2qu3ExKWIlvX1NtSXoyMUEzaE0/view?usp=sharing

![maker-party-party-400x400](https://cloud.githubusercontent.com/assets/12228435/19008864/43738798-8723-11e6-80b7-311eacd0b24a.jpg)

![maker-party-600x300](https://cloud.githubusercontent.com/assets/12228435/19008871/48b72070-8723-11e6-8bd1-866adc38039b.jpg)
