### ISSUE TITLE
QA: Host a Maker Party email

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#489]
Detailed description of work: Review Group, please check copy, rendering and link functionality and place edits/issues in this ticket

_Start date: September 28, 2016_ 
_Due date: September 29, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by valianttry** [comment]
PL:
all links (images and text) work correctly.
Looks like we're using a regular dash but we normally use em dash that's a big longer... not a huge blocker if it takes a lot of work to fix across all emails, but just pointing this out:
![_test_pl_html_75_000_zwolennikow_ _czas_na_impreze__-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/19252115/d05c18ce-8ef7-11e6-8036-79ce87c41947.png)

APPROVED and no need for a retest.

**Comment by valianttry** [comment]
EN:
- I noticed when I click the header image the link sends me to the makerparty.community URL and the tracking seems to get lost. The link location when i copy is: https://click.e.mozilla.org/?qs=02fa2b4ceef354ec65b8c9007cefea01b94957ebaeb5acdb88fca672ba031aad0d0b06432107bd89
- The tracking seems to be correct for text link no 1: https://www.makerparty.community/?locale=en&utm_campaign=makerparty&utm_source=newsletter-mofo&utm_medium=email&utm_content=text1&utm_term=398633
- And also the 2nd text link: https://www.makerparty.community/?locale=en&utm_campaign=makerparty&utm_source=newsletter-mofo&utm_medium=email&utm_content=text2&utm_term=398633

**Comment by valianttry** [comment]
FR:
- The header image URL seems to be missing tracking parameters: https://www.makerparty.community/?locale=fr
- The tracking parames seem correct on the 2 text links in the email: https://www.makerparty.community/?locale=fr&utm_campaign=makerparty&utm_source=newsletter-mofo&utm_medium=email&utm_content=text2&utm_term=398658

This is APPROVED and I don't need to see a new test for the URL fixes.

**Comment by valianttry** [comment]
ES:
- Header image URL is missing tracking parameters
- Text link 1 has tracking: https://www.makerparty.community/?locale=es&utm_campaign=makerparty&utm_source=newsletter-mofo&utm_medium=email&utm_content=text1&utm_term=398662
- Text link 2 also has tracking: https://www.makerparty.community/?locale=es&utm_campaign=makerparty&utm_source=newsletter-mofo&utm_medium=email&utm_content=text2&utm_term=398662
- There's an extra "S" at the beginning of the graph starting with "Registrate":

![_test_es_html_75_000_simpatizantes_-_hagamos_una_fiesta_-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/19252827/e2b53844-8efb-11e6-8bcd-373a3d827514.png)

**Comment by valianttry** [comment]
DE:
- No tracking on header image URL
- Text link 1 looks correct: https://www.makerparty.community/?locale=de&utm_campaign=makerparty&utm_source=newsletter-mofo&utm_medium=email&utm_content=text1&utm_term=398655
- Text link 2 looks correct: https://www.makerparty.community/?locale=de&utm_campaign=makerparty&utm_source=newsletter-mofo&utm_medium=email&utm_content=text2&utm_term=398655

This is APPROVED and I don't need to see another test.
