### ISSUE TITLE
Maker Party QA: Fix title and description metatags 

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#491]
The current title for the site is "Maker Events". @HPaulJohnson Is there a preferred version/syntax? There also is no description metatag (should be ~155 characters). From SEO perspective it should highlight Mozilla, copyright and maker party.

**Comment by HPaulJohnson** [comment]
Here's localized copy for title and description tags on Maker Party sites. 

https://docs.google.com/document/d/1W5JQJhCMr2hR9tLK2Xan8Fph_DkVFJ-BrbzPjFhAans/edit

NOTE: polish is not available at this time and czech is missing a description until those translations complete in pontoon.

**Comment by gholme4** [comment]
@vojtechmzl @HPaulJohnson @valianttry OG tags have been updated so translating can begin. #readyforreview

**Comment by vojtechsedlak** [comment]
The English version is now correct, @valianttry I presume we need to insert the corresponding translations through Bablic ourselves? I don't have access, but am happy to help.

**Comment by valianttry** [comment]
I'm working on these now. Shouldn't take long.

**Comment by valianttry** [comment]
OK I updated all of them but could use help doing QA -- @vojtechmzl can you help with that? The URL is: https://www.makerparty.community/.

**Comment by vojtechsedlak** [comment]
The only one that's not translating is Polish, otherwise it looks great @valianttry

**Comment by valianttry** [comment]
All is done except Polish. I'll ask Kontextor to fill in Polish in this document.

**Comment by vojtechsedlak** [comment]
Oh I see, right, I now see Paul's comment above. Sorry for the confusion.

**Comment by valianttry** [comment]
Kontextor provided Polish, this has been updated in Bablic.
