### ISSUE TITLE
Maker Party QA: Fix Open Graph metatags

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#493]
The OG tags are present, but need to be udpated. @HPaulJohnson would you be able to identify what should be the title and description for the homepage. Specific events include the name of the event as title, but the description og tag seems to be the same across the site.

**Comment by HPaulJohnson** [comment]
see #491 for content

**Comment by jendc123** [comment]
@vojtechmzl @HPaulJohnson - #491 is #readyforreview.

**Comment by gholme4** [comment]
@vojtechmzl @HPaulJohnson @valianttry OG tags have been updated so translating can begin. #readyforreview

**Comment by valianttry** [comment]
I believe this was completed. Please re-open if that's incorrect per #491
