### ISSUE TITLE
Test Idea: Different background image in the header

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#495]
Detailed description of work: Let's test different images that relate to different social content we are testing through paid ads.

_Start date: September 23, 2016_ 
_Due date: October 10, 2016_ 

CC: @lovegushwa let's upload the images here once they are ready. Thanks!

**Comment by beccaklam** [comment]
@vojtechmzl @lovegushwa Here is one idea. The thought here is that there would be a still image of the social replacing the video still on the landing page. The explainer vid would then live in Section 1's video, see the first PNG for what I mean:
![antique-lp-test](https://cloud.githubusercontent.com/assets/20977376/18840849/f2ccfe84-83dd-11e6-83b1-6e1039dc7774.png)
How the idea would play out for other social images and desktop:
![screen shot 2016-09-26 at 11 44 21 am](https://cloud.githubusercontent.com/assets/20977376/18840965/481979b2-83de-11e6-8fb9-b9c256d92c82.png)
![screen shot 2016-09-26 at 11 44 54 am](https://cloud.githubusercontent.com/assets/20977376/18840969/4ac892c4-83de-11e6-87fa-9adb24cde7b4.png)
![screen shot 2016-09-26 at 11 39 18 am](https://cloud.githubusercontent.com/assets/20977376/18841006/5dcc10ee-83de-11e6-9861-a8ff76a85792.png)
![screen shot 2016-09-26 at 11 39 29 am](https://cloud.githubusercontent.com/assets/20977376/18841005/5da3c1a2-83de-11e6-8468-b9a02f7362ef.png)

Alternatively if we don't want the explainer vid to live so far down the page we could have it come right after the fold:
![screen shot 2016-09-26 at 11 46 27 am](https://cloud.githubusercontent.com/assets/20977376/18841073/9154b3bc-83de-11e6-9c4c-5701e7d070ba.png)

**Comment by vojtechsedlak** [comment]
Closing the issue as technical challenges prevented us from running this test.
