### ISSUE TITLE
maker party login link is not using the primary domain and instead does a redirect

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#497]
Detailed description of work:

Not sure where this gets fixed. NationBuilder? Also not sure how significant of an issue this is, but the steps to reproduce are:
1. Go here: https://www.makerparty.community/login

Expected: Should see a login page, on the https://www.makerparty.community/login url.
Actual: You see a login page, but are now on: https://makerevents-mozillafoundation.nationbuilder.com/login

Hopefully this isn't an issue and we can live with it. I am only concerned about this from a security or privacy issue, if there is one, once people start to signup. If we only need to care about this from a brand/fanciful url, then maybe we can p2 it.

CC: @cadecairos @damiankay

**Comment by damiankay** [comment]
@ScottDowne - could you please submit a support ticket for this as well. It seems to me like a P2 as well, but let's see if we can get Nationbuilder working on it. Thanks

**Comment by jendc123** [comment]
Hi @ScottDowne and @damiankay custom domain names are not supported on log-in pages. From the NationBuilder documentation: "All pages within your site will use your custom domain (so mysite.com will display in the address bar) except for login and donation pages. Since those pages require SSL certificates, they will display as https://nationslug.nationbuilder.com"

http://nationbuilder.com/hughreilly/going_live_with_my_own_url

**Comment by cadecairos** [comment]
We've got SSL enabled and forced on our site - do they still not support login on the custom domain

**Comment by ScottDowne** [comment]
@cadecairos @damiankay seeing how unique our own SSL and process to get that setup was, I wonder if an exception can be made for us for the login page? Another thing we'll need to know is if anyone has an issue with the login page being off our URL. From a brand or security perspective, is there anything or anyone that has an issue with login being off our custom domain.

**Comment by gholme4** [comment]
@ScottDowne @valianttry Sorry, but NationBuilder says this is not possible.

---

I checked in with our product and engineering teams regarding this request, and unfortunately it is not currently possible to log in using a custom domain, given our current implementation of SSL.

Best,
Lindsey

---

Lindsey Needham
NationBuilder Support
help@nationbuilder.com
213.394.4623

**Comment by valianttry** [comment]
This is WONTFIX and also a very low priority. For the vast majority of users, a change in domain URL will go unnoticed. Closing this. (Edgecase not worth the ROI + technology wont allow us to do this easily)
