### ISSUE TITLE
Place activities links in MP site once we know where they are being hosted

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#498]
From https://github.com/MozillaFoundation/Advocacy/issues/452
- [ ] The activities are likely going to be on advocacy or a google doc?, but we still need to come up with links.
  ![activities](https://cloud.githubusercontent.com/assets/197334/18726505/c15a28d2-8012-11e6-8903-122db3f7364d.png)

CC @damiankay

**Comment by valianttry** [comment]
The host packs will be localized and ready to place wherever we're hosting them tomorrow (THURS). Do we know format and URLs yet?

cc @stephaniemcv

**Comment by valianttry** [comment]
@ScottDowne any update on progress?

**Comment by ScottDowne** [comment]
@valianttry yeah, when I move it over to google docs, it messes up a bunch of formatting, so I've started to sort that out.

I also need each of the 4 activities to be linked to separately, and not in one big doc. So I need to split them up, ending up with a total of 20 links. 5 languages and 4 activities. 5 \* 4 = 20.

**Comment by ScottDowne** [comment]
It might be fine, but what about this?

https://docs.google.com/document/d/1G1xiIV783vvPUrX_YrzFWi5mg_qz3whLVky7xK_FVxU/edit
That's postcrimes in de. If that works, I can do that for the rest.

**Comment by ScottDowne** [comment]
Here are the localized activities that need to be moved to a gdoc: https://github.com/MozillaFoundation/Advocacy/files/503607/delivery_translation_activities.zip

**Comment by valianttry** [comment]
@lovegushwa

**Comment by lovegushwa** [comment]
hey so I was talking with @ScottDowne about this template: https://chadsansing.github.io/eu-maker-party-sample-activites/updated-eu-maker-party-content/activity01-postcrimes.html#overview
he thinks  localized versoins can all be done by EOD wednesday with @beccaklam's  help

... we could have 270 do a very light reformatting of google docs if your worried. but I think if we can ship real pages very soon, it's not worth putting a bunch of formatting energy into docs.

if we make google docs, they will look something like this: https://docs.google.com/a/mozilla.com/document/d/1Ixq_aTXAveiX1GMlWbFbvvwV2BteOn9jOHDEGBkAhXg/edit?usp=sharing

**Comment by ScottDowne** [comment]
Yeah, with Becca's help, we can realistically get this for eod Wednesday eastern time, but I'm hoping Tuesday eod eastern time can have something ready for QA.

**Comment by valianttry** [comment]
@lucyeoh and @brianking FYI ^^ updates live on Wednesday.

**Comment by ScottDowne** [comment]
@lucyeoh and @brianking English is done on staging. We can start QA on English. Here are the links.

https://advocacy-mozilla-org-staging.herokuapp.com/en-US/maker-party/activities/post-crimes
https://advocacy-mozilla-org-staging.herokuapp.com/en-US/maker-party/activities/meme-around
https://advocacy-mozilla-org-staging.herokuapp.com/en-US/maker-party/activities/contribute-to-the-commons
https://advocacy-mozilla-org-staging.herokuapp.com/en-US/maker-party/activities/combined-maker-party-activities

They were ported, so lots can be broken, but the common things are copy and paste errors in the copy, broken links, and html tags as text, some I am aware of, and just havn't had a chance to go through it all and fix things I missed in my first pass.

**Comment by ScottDowne** [comment]
@beccaklam Here is the checklist we can use for what's translated. I'm doing this per file, not per page, because some pages are shared.

de
- [x] de post-crimes.properties
- [x] de meme_around.properties
- [x] de contribute-to-the-commons.properties
- [x] de combined-maker-party-activities.properties
- [x] de maker-party-activities.properties

it
- [x] it post-crimes.properties
- [x] it meme_around.properties
- [x] it contribute-to-the-commons.properties
- [x] it combined-maker-party-activities.properties
- [x] it maker-party-activities.properties

es
- [x] es post-crimes.properties
- [x] es meme_around.properties
- [x] es contribute-to-the-commons.properties
- [x] es combined-maker-party-activities.properties
- [x] es maker-party-activities.properties

pl
- [x] pl post-crimes.properties
- [x] pl meme_around.properties
- [x] pl contribute-to-the-commons.properties
- [x] pl combined-maker-party-activities.properties
- [x] pl maker-party-activities.properties

fr
- [x] fr post-crimes.properties
- [x] fr meme_around.properties
- [x] fr contribute-to-the-commons.properties
- [x] fr combined-maker-party-activities.properties
- [x] fr maker-party-activities.properties

**Comment by brianking** [comment]
Do you think it makes sense to distribute the EN versions on staging to our core mobilisers (currently ~27 ppl) to get some eyes and review on them?

**Comment by ScottDowne** [comment]
@brianking I do believe that would be helpful, seeing how they were ported, and a few things could be out of place.

**Comment by ScottDowne** [comment]
I believe we can start doing QA on a few languages now too.

DE
https://advocacy-mozilla-org-staging.herokuapp.com/de/maker-party/activities/post-crimes
https://advocacy-mozilla-org-staging.herokuapp.com/de/maker-party/activities/meme-around
https://advocacy-mozilla-org-staging.herokuapp.com/de/maker-party/activities/contribute-to-the-commons
https://advocacy-mozilla-org-staging.herokuapp.com/de/maker-party/activities/combined-maker-party-activities

IT
https://advocacy-mozilla-org-staging.herokuapp.com/it/maker-party/activities/post-crimes
https://advocacy-mozilla-org-staging.herokuapp.com/it/maker-party/activities/meme-around
https://advocacy-mozilla-org-staging.herokuapp.com/it/maker-party/activities/contribute-to-the-commons
https://advocacy-mozilla-org-staging.herokuapp.com/it/maker-party/activities/combined-maker-party-activities

ES
https://advocacy-mozilla-org-staging.herokuapp.com/es/maker-party/activities/post-crimes
https://advocacy-mozilla-org-staging.herokuapp.com/es/maker-party/activities/meme-around
https://advocacy-mozilla-org-staging.herokuapp.com/es/maker-party/activities/contribute-to-the-commons
https://advocacy-mozilla-org-staging.herokuapp.com/es/maker-party/activities/combined-maker-party-activities

PL
https://advocacy-mozilla-org-staging.herokuapp.com/pl/maker-party/activities/post-crimes
https://advocacy-mozilla-org-staging.herokuapp.com/pl/maker-party/activities/meme-around
https://advocacy-mozilla-org-staging.herokuapp.com/pl/maker-party/activities/contribute-to-the-commons
https://advocacy-mozilla-org-staging.herokuapp.com/pl/maker-party/activities/combined-maker-party-activities

FR
https://advocacy-mozilla-org-staging.herokuapp.com/fr/maker-party/activities/post-crimes
https://advocacy-mozilla-org-staging.herokuapp.com/fr/maker-party/activities/meme-around
https://advocacy-mozilla-org-staging.herokuapp.com/fr/maker-party/activities/contribute-to-the-commons
https://advocacy-mozilla-org-staging.herokuapp.com/fr/maker-party/activities/combined-maker-party-activities

**Comment by ScottDowne** [comment]
I believe we're done this, and all languages are on staging.

I updated the comment above with all the links, to all the activities in all languages.

**Comment by ScottDowne** [comment]
There are still a few strings we're missing. Links to missing strings:
- [ ] https://github.com/mozilla/advocacy.mozilla.org/blob/master/locales/en-US/maker-party-activities.properties#L1-L4
- [ ] https://github.com/mozilla/advocacy.mozilla.org/blob/master/locales/en-US/maker-party-activities.properties#L13-L14
- [ ] https://github.com/mozilla/advocacy.mozilla.org/blob/master/locales/en-US/combined-maker-party-activities.properties#L1

**Comment by beccaklam** [comment]
## *Across the board missing: (except German, I think)
- "Make Some Memes!"

Note: All of the meme examples are in English. Will that be a problem?

**Comment by beccaklam** [comment]
ES
**Meme-around**
"Think about how many people are attending, and how long you’ll have them for to decide whether to do this as a standalone or as part of a longer event!"
"Make Some Memes!"

**Comment by valianttry** [comment]
I've submitted these missing strings to Kontextor. When they're available @ScottDowne can update them on the site.

**Comment by lovegushwa** [comment]
@ScottDowne @beccaklam you did an amazing job knocking these out! Thank you :)

**Comment by ScottDowne** [comment]
OK, this is all done and shipped for realzez.

I'm creating a new issue for the new strings coming from Kontextor. I'll link it here when it's filed.

Feels good to close this one. :rocket:
