### ISSUE TITLE
Localize the rest of advocacy

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#50]
Right now, in order to get the site started on pontoon, I prioritized localizing the encrypt campaign.

I want to go back and do the rest of the site. This just involves going through, finding all the strings, removing them, and putting them into a properties file per page.

**Comment by damiankay** [comment]
How much time would you need for this @ScottDowne ? I'm assuming it's going to have to happen after the Nationbuilder work is complete.

**Comment by hannahkane** [comment]
I think this is no longer a goal. Closing.
