### ISSUE TITLE
Copyright Petition V2: Add localized versions of footer

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#500]
Detailed description of work:
@jendc123 can your team copy the localized footer strings from V1 of the Petition? The footer was updated after we turned Bablic on, and the translations seem to have been lost. 

CC: @gholme4 @brettgaylor @HPaulJohnson

**Comment by jendc123** [comment]
@damiankay - the text in the v2 petition is translated.  The links need to be updated.

**Comment by damiankay** [comment]
@jendc123 - the links are correct. They'll redirect to the user's locale automatically. Thanks
