### ISSUE TITLE
v2 Petition Site QA: Check localized metatags

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#502]
All title and metatags should be updated as per the [following document](https://docs.google.com/document/d/1tAc6T_8scqBiEL42-qzLMQ6X6IqWhkXgmfEkH17ju8s/edit) that @HPaulJohnson put together.

**Comment by damiankay** [comment]
@jendc123 @gholme4 could you address this please?

**Comment by jendc123** [comment]
@damiankay this has been updated and #readforreview.
