### ISSUE TITLE
v2 Petition Site QA: First two fields of the form not translating

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#505]
Labels in the first two fields of the form are not translating for me in Firefox (FIrst Name, Last Name)

![screen shot 2016-09-23 at 2 48 42 pm](https://cloud.githubusercontent.com/assets/20688240/18802302/dafd9554-819c-11e6-8b63-14c14f582594.png)

**Comment by damiankay** [comment]
@gholme4 @jendc123 can you please identify how we fix this issue? Are these labels in Bablic?

**Comment by jendc123** [comment]
@damiankay we have connected with Bablic support.  We have imported all the strings but for some reason a few of them like "First Name*" are not being shown.  We will keep you updated.

**Comment by damiankay** [comment]
Thank you @jendc123

**Comment by jendc123** [comment]
@damiankay this is #readyforretesting
