### ISSUE TITLE
v2 Petition Site QA: localized content not displaying

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#506]
@gholme4 some of the localized content is not showing, effects all languages. 

<img width="521" alt="screen shot 2016-09-23 at 3 39 32 pm" src="https://cloud.githubusercontent.com/assets/12228435/18803338/f5f87f20-81a3-11e6-9f9f-7fd77914b5cd.png">

<img width="960" alt="screen shot 2016-09-23 at 3 35 47 pm" src="https://cloud.githubusercontent.com/assets/12228435/18803276/713b3f52-81a3-11e6-8e02-c39dd886e16a.png">

<img width="993" alt="screen shot 2016-09-23 at 3 41 12 pm" src="https://cloud.githubusercontent.com/assets/12228435/18803358/30e60d3c-81a4-11e6-8367-906523b2cf57.png">

**Comment by damiankay** [comment]
@gholme4 - In trying to replace the current copy with translated text for "we <3 the internet", I get the following error message: 

> Your translation is missing some of the original text variables: 3
> Those variables need to be present in the translated version too, please use these guidelines in your translation:
> {0} represents 3

Can you advise how to update this copy to French, for instance? The French copy is "Nous aimons l’internet"

**Comment by gholme4** [comment]
@damiankay I changed the text to "We love the internet" since my attempt to prevent 3 from being read as a variable failed. The rest of the caption can be translated now.  Translations need to be provided for the other copy @lovegushwa  mentioned.

**Comment by damiankay** [comment]
All have been updated except for "we <3 the internet". @gholme4 can you please change back to the format with the symbol? That's how all of our translations except for French are set up. Thx!

**Comment by gholme4** [comment]
@lovegushwa @valianttry #readyforreview

**Comment by valianttry** [comment]
done, all corrected.
