### ISSUE TITLE
v2.5 Petition Site QA: Videos not playing in Firefox

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#507]
Videos are not playing correctly in Firefox. Works fine in Chrome.

There is audio but just a spinning wheel in place of video. @lovegushwa and @brettgaylor also confirmed it was happening.

**Comment by damiankay** [comment]
@gholme4 any idea why this is happening? 

CC @jendc123

**Comment by brettgaylor** [comment]
This could be because of firefox compatability with mp4 files. Although I thought Firefox was now supporting mp4s...

@gholme4 we did provide webm, so you could do
 `<video>
<source>foo.webm</source>
<source>foo.mp4</source>
</video>`

And it should work - i believe it gets best results when you use webm first for fallback order.

**Comment by damiankay** [comment]
@brettgaylor @HPaulJohnson - I can't replicate this. The videos are a bit slow to load, but they work. Which version are you on? I'm still in Firefox 48.1

**Comment by HPaulJohnson** [comment]
FF 48.0.1

**Comment by damiankay** [comment]
@cadecairos @ScottDowne please have a look at this issue when you can. 3 out of 6 can view the videos in FF.

**Comment by cadecairos** [comment]
The videos are loading fine for me in Firefox 49 and 52

I think we're dealing with some folks' Firefox installations not being able to decode mp4 video. The simple solution, I believe, is what @brettgaylor suggested above:

> @gholme4 we did provide webm, so you could do
> `<video> <source>foo.webm</source> <source>foo.mp4</source> </video>`
> 
> And it should work - i believe it gets best results when you use webm first for fallback order.

**Comment by damiankay** [comment]
This is actually resolved now. For some reason the video was hidden ( @gholme4 can explain I'm sure)
