### ISSUE TITLE
v2 Petition QA: Thank you / share modal not loading after signing the petition

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#508]
@gholme4 (CC @beccaklam )
I'm not seeing the thank you / share modal after signing the petition. Any blockers to getting this working? (on both desktop and mobile)

![mobile thank you and share](https://cloud.githubusercontent.com/assets/12228435/18804917/d601698a-81b6-11e6-9676-345557b04342.png)

**Comment by jendc123** [comment]
Hi @lovegushwa - both George and I are getting the thanks message. 
<img width="305" alt="thank you note" src="https://cloud.githubusercontent.com/assets/6034476/18805058/9145083a-81d2-11e6-9e25-fbf23a95178e.PNG">

**Comment by lovegushwa** [comment]
@jendc123 ... @HPaulJohnson tested it on mobile / all good. 
But it's not working on desktop for either of us. Are you testing it on desktop?

**Comment by gholme4** [comment]
@lovegushwa There isn't a thanks modal in the desktop design. If you want I can unhide the modal on desktop.

**Comment by lovegushwa** [comment]
@gholme4 yes please unhide it, that should work just fine.

**Comment by beccaklam** [comment]
@gholme4 @jendc123 @lovegushwa There was a thanks modal designed for desktop and tablet:
![screen shot 2016-09-26 at 9 49 47 am](https://cloud.githubusercontent.com/assets/20977376/18836468/2f805f8e-83ce-11e6-8a66-fa58eba686c0.png) It was included in the PSD files and the redpens?

**Comment by HPaulJohnson** [comment]
I'm now seeing this upon page load every time I visit the site. I also see it after I sign the petition. 

We should remove the instance on page load. Also, the "back to article" language is confusing in the context of the site/petition. Probably should just be a "X" to close this modal. Screenshot:
![share_modal](https://cloud.githubusercontent.com/assets/10078715/18841200/cb29d946-83c5-11e6-891b-2a5fdfafdc78.jpg)

**Comment by jendc123** [comment]
@lovegushwa @beccaklam @HPaulJohnson @damiankay - Please hold off on the QAing the "Thanks" module while we make some updates to the page. I'll let folks know when it's ready for retesting.

**Comment by jendc123** [comment]
@lovegushwa @beccaklam @HPaulJohnson @damiankay - this is ready for review. #readyfortesting

**Comment by lovegushwa** [comment]
@jendc123 @gholme4 the modal is working "Please share this" and "Thank you" should be on the same baseline. Other than that it's a pass!

<img width="1247" alt="screen shot 2016-09-27 at 11 57 50 am" src="https://cloud.githubusercontent.com/assets/12228435/18887641/c66c3aea-84a9-11e6-9aaa-68aaf47c7614.png">

**Comment by valianttry** [comment]
@gholme4 was this done? We can QA again if need be.

**Comment by gholme4** [comment]
@valianttry Yes, That has been updated. #readyforreview

**Comment by valianttry** [comment]
@vojtechmzl can you make sure this was fixed and then close this ticket? TY!

**Comment by vojtechsedlak** [comment]
The modal is appearing correctly and the text alignment is fixed. As Paul flagged above the wording Back to article doesn't really make much sense. Also, that string does not appear to be translating (see below). Could it be replaced with a an X button in the corner?

cc @valianttry @gholme4 @jendc123 

<img width="1088" alt="screen shot 2016-09-28 at 9 34 02 am" src="https://cloud.githubusercontent.com/assets/20688240/18922766/d4cc8fd0-855e-11e6-84d9-d321774b106f.png">

**Comment by valianttry** [comment]
@jendc123 can you add an "X" in the upper corner and get rid of the button alltogether?
@gholme4 

If "yes" we can review and close

**Comment by gholme4** [comment]
@valianttry #readyforreview
