### ISSUE TITLE
v2 Petition QA: 2.5 form not advancing in Firefox

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#509]
@gholme4 the 2.5 form seems non functional in Fire Fox. I can't click into the field to input text or trigger anything with the red button.

<img width="951" alt="screen shot 2016-09-23 at 5 58 25 pm" src="https://cloud.githubusercontent.com/assets/12228435/18804947/6dd465fa-81b7-11e6-8146-1d4931ffe06a.png">

**Comment by jendc123** [comment]
@lovegushwa we can't seem to replicate the issue.  Can you provide any more details.

**Comment by lovegushwa** [comment]
@jendc123 @gholme4 here is a screen recording of my trying to click in the field and click the red button. You can see its not responsive.

![animationd](https://cloud.githubusercontent.com/assets/12228435/18821349/1bff8eb8-835a-11e6-874b-4f762ed4ccea.gif)

<img width="586" alt="screen shot 2016-09-25 at 7 47 25 pm" src="https://cloud.githubusercontent.com/assets/12228435/18821377/54edfc0a-835a-11e6-9552-a5bbc7f37f96.png">

<img width="625" alt="screen shot 2016-09-25 at 7 58 07 pm" src="https://cloud.githubusercontent.com/assets/12228435/18821388/7194378e-835a-11e6-81c4-3808e2d38a99.png">

CC @beccaklam @HPaulJohnson @natalieworth @damiankay can you test the v2.5 form and try to duplicate this bug in Firefox? 
https://petitionv25-mozillafoundation.nationbuilder.com/

**Comment by lovegushwa** [comment]
@jendc123 the same setup fails to play any videos:
![animatione](https://cloud.githubusercontent.com/assets/12228435/18821479/4154b4e4-835b-11e6-8b76-71d6e3bbb122.gif)

**Comment by HPaulJohnson** [comment]
I have the same two issues. Form is unresponsive in Firefox (can't click/edit form field and can't click next button) and video player never shows up (just get sound and the spinning circle). Both of these work perfectly in Chrome. 

I'm on FF 48.0.1 on Macbook Pro 13'' OS X Yosemite.

**Comment by beccaklam** [comment]
It seems to work for me... @lovegushwa @damiankay 
<img width="642" alt="screen shot 2016-09-26 at 9 47 59 am" src="https://cloud.githubusercontent.com/assets/20977376/18836417/fb65cdce-83cd-11e6-9815-e79c5d3ef1d0.png">

**Comment by damiankay** [comment]
@gholme4 @ScottDowne @cadecairos - can you please look into this and see if you can replicate the problem that Brett, Paul and Jordan are having with video playback?

**Comment by ScottDowne** [comment]
Worked for me, but, there is only one video source, an mp4, so that's likely the cause.

I'll try it on a bunch of browsers + OS combinations.

**Comment by ScottDowne** [comment]
I tried on the browser + OS combinations both @lovegushwa and @HPaulJohnson used, and it worked.

I suspect it's unrelated to the browser + os combination.

The way mp4 works in FF is that it doesn't. When firefox gets an mp4, it just unloads it to the OS. In a lot of cases, it can then pass or fail if that OS has software installed to play the video. In these cases, the machines I used, probably had the software, and maybe Jordan and Paul don't? My advice is just to support both mp4 and webm, which if memory serves me, FF supports natively, and chrome supports mp4 and webm natively.

**Comment by damiankay** [comment]
I think the problem is that there's no clear way to link to two separate video formats via Bablic. Is that correct @gholme4 @jendc123 ? Ideally we should be using both the MP4 and the webm videos.

**Comment by ScottDowne** [comment]
Oh, is this maybe a Bablic thing? (wouldn't be surprised if it only allows one video format)

This is technically possible without Bablic, but would be very unfortunate if Bablic's the cause, but likely, not much can be doing about it inside Bablic/NationBuilder land.

**Comment by lovegushwa** [comment]
Looks like video is now working.

**Comment by ScottDowne** [comment]
Sounds good. I say we close this. Either reopen or file a new ticket if something else comes up.

**Comment by damiankay** [comment]
Thanks @gholme4 !

**Comment by lovegushwa** [comment]
@ScottDowne this ticket is for 2.5 form not advancing in Firefox, which we will resolve in a day or two. (we're going to launch with the old form.)

**Comment by ScottDowne** [comment]
@lovegushwa ah, fyi, that worked for me too.

**Comment by gholme4** [comment]
@lovegushwa @valianttry #readyforreview

**Comment by lovegushwa** [comment]
Works!
