### ISSUE TITLE
Email: Host a Maker Party Kicker

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#510]
Detailed description of work: Create and route copy for follow up email to those invited to host a Maker Party to get them to complete the CTA.
Audience: Anyone who Opened Host a Maker Party #486 but did not complete Host action
Draft: @cristina-moon
Send date: 10/11/2016

_Start date: September 26, 2016_ 
_Due date: September 30, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @shaghdoosti @valianttry

**Comment by cristina-moon** [comment]
[First draft of kicker email is here!](https://docs.google.com/document/d/1o7GveL-qW3q6NBmN5OiZ2tjTI3qQaI1uy7BAFMXf1w8/edit?usp=sharing) Ready for feedback and edits from @shaghdoosti and @valianttry :)

**Comment by stephaniemcv** [comment]
Updated version of copy: https://docs.google.com/a/mozilla.com/document/d/1UUmPz2Lu8fIyYF_Owfewm8qrsE2LYjHdUvU97vbREpk/edit?usp=sharing

Has been routed by policy and legal.

@TheoChevalier can you move this forward for localization in DE, FR, ES PL? We're aiming for a send next week Friday.

**Comment by TheoChevalier** [comment]
@stephaniemcv gosh I totally missed this notification, sorry about that :( 
Sending it to Kontextor right away for DE, ES and PL. I’ll do FR myself tonight

**Comment by TheoChevalier** [comment]
Here is the French version, I’ll update when I receive the other 3 translations. https://docs.google.com/a/mozilla.com/document/d/1UhXKcsO2LpfWvbyIxzo7RMk3sCDYpIZIIwIji_rq2aA/edit?usp=sharing

**Comment by TheoChevalier** [comment]
Hey @stephaniemcv here are the DE, ES and PL translations https://docs.google.com/spreadsheets/d/1dBARa2Pr9NB_Q5ZdPOV1Jx9NOLbATSPk3etSfCWHTkk/edit#gid=125626957
