### ISSUE TITLE
Create second rapid response video

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/Advocacy#511]
Detailed description of work: Create RR video based on 9/27 blog post

First-draft script [here](https://docs.google.com/document/d/1Y9AJolU0Xn7neXaKCJNellC9RUlsPZxYadLxrCGgUNg/edit).

Blog post [here](https://docs.google.com/document/d/10HnY9uMOlYD1W7HWnjWM_MxsJ37f3Viuhq4ayBApmLQ/edit), if you want to consider alternative copy. Should be localized into EN, ES, FR, DE and PL by tomorrow morning.

_Start date: September 26, 2016_ 
_Due date: October 3, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @natalieworth @brettgaylor @HPaulJohnson

**Comment by brettgaylor** [comment]
I like!  I wonder if we can discern the final length of one of these - the first one was just shy of a minute - i think we should aspire to shorter, which this seems to be.

Maybe we could just do by word count?

Also - I think we want to decide in this process what the poster image is.

**Comment by KevZawacki** [comment]
Word count for the first RR video: 91 words, which = 58 seconds
Word count for the second RR video: 90 words, which = ~the same

If we want to trim, we could drop the second scene all together. 

Poster image... a Post Crimes creation?

**Comment by brettgaylor** [comment]
Yes, that was my suggestion, too.

@lovegushwa has some great social images for postcrimes that I've seen.

**Comment by lovegushwa** [comment]
@KevZawacki @brettgaylor 

This is the postcrimes social share ... I do agree we should push into #theartoftheposter 
Wondering if posters need to be a ticket and if we should devise a testing plan?

![social-postcard](https://cloud.githubusercontent.com/assets/12228435/18885136/3722d826-849f-11e6-8c14-5f9bfffe0bf7.png)

**Comment by KevZawacki** [comment]
Hi, @brettgaylor @natalieworth 

I tweaked[ the script](https://docs.google.com/document/d/1Y9AJolU0Xn7neXaKCJNellC9RUlsPZxYadLxrCGgUNg/edit) a bit. Pulling localized versions for the first version proved difficult (I would have had to remove certain words, which would have screwed up syntax).

I think this version is better. Let me know -- then I'll send to Mika and Raegan.

I also rewrote our next blog (Maker Party) so we won't have syntax errors going forward.

**Comment by brettgaylor** [comment]
Sorry for late response!  It looks great to me. My only question was around the word "doctored" - but I'm good to send this for approval!

**Comment by natalieworth** [comment]
@KevZawacki @brettgaylor This is great! Love the length of it too. It'll be awesome to see how a shorter response video compares to the 1 min one 👍 💯

**Comment by KevZawacki** [comment]
@brettgaylor @natalieworth 

All approvals are in! Ready to start creating.

@natalieworth You'll notice the EN version has some extra language that isn't localized. Specifically, scenes 4 and 5. That's intentional.

**Comment by natalieworth** [comment]
Awesome! Thanks @KevZawacki

**Comment by natalieworth** [comment]
@brettgaylor @KevZawacki Really rough placement cut is here:
https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0ZEtKRThMYlhBUGs

I've also added a vimeo link since my wifi takes forever on the Island to upload to the drive:
https://vimeo.com/185571577

**Comment by brettgaylor** [comment]
Like it.  feel you could cut the "show policymakers how outdated laws are" section and cut straight to "send selfie to parliament"

also, we can change "join hundreds" to "join more than a thousand"

**Comment by KevZawacki** [comment]
@natalieworth I really dig the mourning emoji and Eiffel Tower gifs

**Comment by natalieworth** [comment]
@brettgaylor @KevZawacki 2nd cut for this is up on vimeo here: https://vimeo.com/185728065

**Comment by lovegushwa** [comment]
@natalieworth Hey Natalie just a few simple type tweaks:

use "fi" ligature
![screen shot 2016-10-06 at 9 34 49 am](https://cloud.githubusercontent.com/assets/12228435/19171138/209ea426-8bd0-11e6-8910-ab2abf7a59fe.png)

Use real apostrophe, not foot mark in "Commission's" 
Seems like a word break after "the commissions" might push "needs" down a line, and look better.

![screen shot 2016-10-06 at 9 36 01 am](https://cloud.githubusercontent.com/assets/12228435/19171144/2f05cf62-8bd0-11e6-9f24-db704356fe6a.png)

**Comment by natalieworth** [comment]
@KevZawacki @brettgaylor Final files for these have been exported and added to the drive document (at the bottom of the page under 'Rapid Response Video 2':
https://docs.google.com/spreadsheets/d/1rmqeIJq1vMDFsI0sicu7XdVwkLDur-rerTPb3rjFyko/edit#gid=0

**Comment by KevZawacki** [comment]
Thanks, @natalieworth.

@brettgaylor @HPaulJohnson, getting these up on social now.
