### ISSUE TITLE
v2 Petition Site QA: Add test variants to thank you modal

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#512]
We are hoping to run a test on the thank you modal, where we want to combine a share ask with a possible fundraising CTA. I will email you with an updated _petition_thanks_modal.html file that includes two additional variants of the layout, with display:none set. When we launch, I will set up a test through Optimizely where I will unhide each variant. Would it be possible to update the file @gholme4 @jendc123? 

There is also a donate button image that I uploaded into NB and that's referenced in the code. I am sending it along as well, in case it needs to be reuploaded after the theme is updated. If that is the case, its URL will need to be changed in the _petition_thanks_modal.html file.

Please let me know if you have any questions! Thanks for your help!

**Comment by gholme4** [comment]
@vojtechmzl I added a different version of what you provided to match the current design.

**Comment by vojtechsedlak** [comment]
That's perfect! Thanks @gholme4.
