### ISSUE TITLE
Maker Party: Update "legal" link

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#514]
Detailed description of work: @gholme4 can you please update the "legal" link in the Maker Party footer to point to: https://www.mozilla.org/en-US/about/legal/terms/mozilla/

_Start date: September 26, 2016_ 
_Due date: September 27, 2016_ 

CC: @jendc123 @valianttry

**Comment by valianttry** [comment]
NOTE that the link should be: 

https://www.mozilla.org/about/legal/terms/mozilla/

without "en-US" so that it will automatically render the locale set by the user.

**Comment by gholme4** [comment]
@valianttry #readyforreview

**Comment by valianttry** [comment]
This is fixed -- closing!
