### ISSUE TITLE
Maker Party: Update CTA email copy

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#515]
Detailed description of work: 
@shaghdoosti @HPaulJohnson When I click on the mail icon in the “Make a difference on copyright reform in Europe...” CTA box, the email copy says:

> Education, parody, photography, and remix shouldn’t be unlawful online. It’s time to set our imaginations free in the EU — sign Mozilla’s petition to reform outdated copyright law: https://www.makerparty.community/

Is this the correct copy? If so, we should update the link. 

Bigger question: can we serve up localized copy for this email @gholme4 ? 

_Start date: September 26, 2016_ 
_Due date: September 27, 2016_ 

CC: @valianttry

**Comment by HPaulJohnson** [comment]
Please use this copy/doc for all social shares on Maker Party site: 

https://docs.google.com/document/d/1YBoLZ5f7KL4yVgzPI9HMES-SX3yAZ7N9p4vSTYVAedo/edit
