### ISSUE TITLE
Maker Party: Broken RSVP link

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#516]
Detailed description of work: The update/cancel link in the RSVP email doesn't work. 

_Start date: September 26, 2016_ 
_Due date: September 27, 2016_ 

CC:

**Comment by valianttry** [comment]
I'm not 100% certain this is the issue Damian pointed out originally. But when I click the "unfollow here to stop receiving updates" link, I go to a login page with a weird red box error that isn't very helpful.

![thank_you_for_joining_-_andrealw_gmail_com_-_gmail](https://cloud.githubusercontent.com/assets/9830371/18941214/f43e4ede-85c3-11e6-8f8c-e36c73840471.png)

![join_-_maker_events](https://cloud.githubusercontent.com/assets/9830371/18941227/1b7a5d3a-85c4-11e6-80cf-740424d55f95.png)

**Comment by valianttry** [comment]
When I click the "update or cancel" URL in my email RSVP confirmation, I am sent to the form to RSVP (unhelpful). I should be sent to a page that allows me to "click to cancel" or "login to cancel" with some hint. 

![rsvp_confirmation_for_october_29_event_-_andrealw_gmail_com_-_gmail](https://cloud.githubusercontent.com/assets/9830371/18941545/f39a0f60-85c6-11e6-863c-8d774a239539.png)

This is the page that opens on-click:

![october_29_event](https://cloud.githubusercontent.com/assets/9830371/18941552/fe0ca728-85c6-11e6-942c-41b27d8b1f5e.png)

**Comment by gholme4** [comment]
@valianttry The link in that email is correct. The event page is where a person cancels an RSVP. In the usual flow the user will see a checkbox to cancel the RSVP instead of the default RSVP form, because the user's session will be active.
