### ISSUE TITLE
Deploy V2 petition to changecopyrightorg

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#517]
V2 petition should be hosted at changecopyright.org - do we coverage of all the steps necessary to deploy there?

cc @jendc123 @gholme4

**Comment by valianttry** [comment]
FYI @jendc123 indicates the SSL cert should be fine:

[9/26/16, 5:40:35 PM] Jennifer OReilly Mott: We are all set - we are not making any changes in Nationbuilder
[9/26/16, 5:40:42 PM] Jennifer OReilly Mott: we are going to change the url in Bablic
[9/26/16, 5:41:12 PM] Jennifer OReilly Mott: and it will all be pointing to ChangeCopyright.org
[9/26/16, 5:41:20 PM] Jennifer OReilly Mott: which already has SSL etc

**Comment by cadecairos** [comment]
Correct me if I'm wrong, but don't we still need to update the domain configuration in NationBuilder to tell it that the new v2.5 site should be served to changecopyright.org? Updating the Bablic site with the new URL won't update which site changecopyright.org shows.

**Comment by jendc123** [comment]
@cadecairos We are also going to update the theme on ChangeCopyright.org.

**Comment by cadecairos** [comment]
@jendc123 So we're overwriting the existing markup and updating bablic to use the new strings on that site?

Will we have a backup copy of the theme currently on the site?

**Comment by jendc123** [comment]
@cadecairos, correct.  We will have a back-up.

**Comment by cadecairos** [comment]
OK, Makes sense to me, thanks for the clarification

**Comment by valianttry** [comment]
closed resolved it is LIVE!
