### ISSUE TITLE
SalesForce Backend Field Names

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#518]
Detailed description of work: In order to set up triggered messages, I need to know the collection of Campaign  field names mapped into SF as well as to be able to AMPscript dynamic content into the emails. (Example: Maker Party Venue Address = Location__c )

Child Campaign Name or Maker Party Event Name or ID
Host Name
Host?
Maker Party Time and Date
Attendee?

Associated ticket: #477 

_Start date: September 27, 2016_ 
_Due date: September 28, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @valianttry @drewmoto @jendc123 @imagerwalt

**Comment by drewmoto** [comment]
Hi @stephaniemcv @valianttry Here is my crack at the SF Field Mappings. Please pass along and/or tag FIssion in this for their confirmation. I could not tag them for some reason. Thx. 

[NBSalesforceMakerPartyFieldLevelDetail.docx](https://github.com/MozillaFoundation/Advocacy/files/499331/NBSalesforceMakerPartyFieldLevelDetail.docx)

**Comment by stephaniemcv** [comment]
Woo! Thanks @drewmoto! I can start moving forward with the triggered email content. 

CC: @jendc123 @imagerwalt

**Comment by jendc123** [comment]
@valianttry can we close this?
