### ISSUE TITLE
Petition QA: Sidebar share buttons lead to an error

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#519]
I get the following messages when trying to share from the sidebar on the v2 petition at changecopyright.org

![screen shot 2016-09-27 at 3 27 40 pm](https://cloud.githubusercontent.com/assets/20688240/18894324/294d3e6c-84c7-11e6-870f-edf24a9d3127.png)

CC @valianttry @gholme4

**Comment by valianttry** [comment]
Repeat of https://github.com/MozillaFoundation/Advocacy/issues/318.

Working on this now. @ScottDowne or @cadecairos can you help?

**Comment by ScottDowne** [comment]
Worked for me with a private tab, didn't without. Cache is likely.

**Comment by ScottDowne** [comment]
So cache made it work for me in FF, but chrome doesn't work.

This is all super familiar, and I suspect we hit this before, and there was a fix around the facebook app thingy.

**Comment by valianttry** [comment]
[9/27/16, 3:53:57 PM] Jennifer OReilly Mott: e also wanted to flag that we should confirm that it's on a paid Bablic account.
[9/27/16, 3:54:14 PM] Jennifer OReilly Mott: We don't have access to those settings
[9/27/16, 3:54:25 PM] Jennifer OReilly Mott: We can probably just move it over

@ScottDowne or @cadecairos can you double check our account settings?

**Comment by gholme4** [comment]
@ScottDowne @vojtechmzl Is this the correct FB app? https://developers.facebook.com/apps/235412103527113/dashboard/

**Comment by ScottDowne** [comment]
Yeah that's the only one I know of.

**Comment by cadecairos** [comment]
The App ID in the share code on changecopyright.org has the wrong app ID:

![screenshot from 2016-09-27 20-43-32](https://cloud.githubusercontent.com/assets/438003/18896847/14f36a3c-84f3-11e6-97a5-c03474630169.png)

It should be "235412103527113"

**Comment by cadecairos** [comment]
A small gotcha with Facebook apps is that various changes you make to them can result in the app ID being regenerated without much, if any, notification to you.

**Comment by gholme4** [comment]
@vojtechmzl @cadecairos @ScottDowne @valianttry The site was using NationBuilder's default FB app ID originally without a problem. After switching themes today the custom domain was no longer validated. I added the FB code after NB's code to make this work. #readyforreview

**Comment by valianttry** [comment]
Closing resolved.
