### ISSUE TITLE
Codemoji Email Reivew

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#52]
Please review the email copy, test the link and note any feedback in this ticket.
Audience: Audience Segmentation: 50% active advocates; 50% nonAA 
Audience size = 100,000

**Comment by brettgaylor** [comment]
I think its great!  I wonder if you want to add something like "Brett, from the Media team" or just some other way to indicate who the heck this Brett character is or the kind of things you might see from him.

**Comment by HPaulJohnson** [comment]
@stephaniemcv looks good. Can we hyperlink "new Codemoji game" in the first paragraph to make something clickable above the fold?

**Comment by stephaniemcv** [comment]
@HPaulJohnson yes, good catch. There was supposed to be a link there and I missed it. 

@brettgaylor Brett, I like it - I will add.

**Comment by lovegushwa** [comment]
@stephaniemcv can we change the emoji image? I created a new one with a white background:
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvLU9aN2J5a1JrZ3M/view?usp=sharing

**Comment by valianttry** [comment]
Two things:
1. I suggest we hotlink every instance of "Codemoji" to codemoji.
2. Brett is not a normal email signer, we should add his full name and title after his signature, so it looks like:
   "
   Brett

Brett Gaylor, Director of Advocacy Media" << @brettgaylor is this your new correct title?

@stephaniemcv how are you defining Active Advocates for targeting purposes?

**Comment by stephaniemcv** [comment]
@valianttry 

I'm going to recommend against linking every "Codemoji", we may get flagged as spam for having too many of the same link

We can go two ways. I can randomly select 50,000 from our original AA group or a random 50,000 from those who clicked 2 or more emails from the encryption series.

**Comment by valianttry** [comment]
@stephaniemcv I'm so glad to have you as our deliverability samarai 🏆

**Comment by KevZawacki** [comment]
Email looks great! 👍

**Comment by HPaulJohnson** [comment]
@stephaniemcv looks good to me too!

**Comment by KevZawacki** [comment]
@stephaniemcv The second (12:48 p.m. ET) email looks good, too. 😄
