### ISSUE TITLE
Heartbeat Fundraising Test

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#520]
Detailed description of work: Conduct a test of fundraising message in the Firefox Heartbeat. Coordinate with Matthew on possible testing ideas to facilitate best user experience.

[Meeting Notes](https://docs.google.com/document/d/1BcSoaUqxkaNUr6azXWlMg3ypPjb8KqT2Da3gXu-R40U/edit)
[Proposal](https://docs.google.com/document/d/1Otd_wPhwtNo5JjdK5-talkxo-Xi0RQ0kol5xehSvmys/edit#heading=h.dhws63t3mdi)
[Bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1298192)

(Matt H. removed the deadline)

CC: @valianttry

**Comment by Matt-Holland** [comment]
We are having delays in hearing back on the results of the test. We will eventually get the results and learn from it, but this will not contribute to EOY 2016 fundraiser.

**Comment by vojtechsedlak** [comment]
The results of the heartbeat test were as follows:

EN
5.51% CTR
$9/1000 impressions

DE
1.94% CTR
$21/1000 impressions

Based on the results we believe that the heartbeat could potentially aid with fundraising. The heartbeat team however identified the following roadblocks:

- A proper design that doesn't use the heartbeat logo since it's somewhat confusing and may be interpreted in unexpected ways.  Example: https://twitter.com/TechAndNews/status/802203486477807616
- User testing to ensure that design isn't misinterpreted
- Firefox leadership (likely Nick Nguyen and Mark Mayo) approval to make use of this type of mechanism for fundraising purposes

Let's revisit this at a later on, when we talk fundraising plans for 2017

**Comment by HPaulJohnson** [comment]
Closing this "testing ticket" but will definitely add to the agenda for debrief and 2017 planning.
