### ISSUE TITLE
Deploy V2.5 petition to changecopyright.org

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#521]
@jendc123 @cadecairos @gholme4 

Let's deploy v2.5 ( https://petitionv25-mozillafoundation.nationbuilder.com/ ) end of day (PST) tomorrow, Thursday the 29th. 

This should give us enough time to get statistically significant traffic for v2, and still get solid Friday EU traffic for v2.5. 

Any flags here? I know we had some issues with elements in the page breaking when we deployed v2. Should we anticipate some issues?

CC  @shaghdoosti @valianttry @HPaulJohnson @brettgaylor

**Comment by jendc123** [comment]
Hi @lovegushwa we need to implement [(https://github.com/MozillaFoundation/Advocacy/issues/512)] but we anticipate having everything ready to go for tomorrow.
