### ISSUE TITLE
Create estimates of 2016 media reach

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#523]
Detailed description of work: To evaluate the 2016 media work and plan for 2017, we need to pull together some numbers.  Understood these will be imperfect.

Unique visitors to encrypt website
Unique visitors to codemoji.org
Unique visitors to changecopyright.org
Unique visitors to postcrimes.org
Total video views of encryption + copyright videos
Twitter mentions
Earned media Stories (encryption, codemoji, copyright)
Estimated reach of stories (UMV x article)

I'll check in with team that is PMing reporting to see when these actually need to be gathered by.

_Start date: September 1, 2016_ 
_Due date: October 3, 2016_ 

CC: @HPaulJohnson @OpenMatt

**Comment by KevZawacki** [comment]
@brettgaylor @vojtechmzl Suggested tactics or tools for the "Estimated reach of stories (UMV x article)" metric?

Currently, my method would be checking the individual ad kits for each publication. This multiplied by ~300 publications = 5 or 6 hours for results that may not be entirely accurate. 

Happy to do so if that's the only way. But would need to deprioritize Maker Party and MozFest for some time.

**Comment by brettgaylor** [comment]
Just spoke to Angela and Matt - there's no rush to grab these numbers, but worth a discussion of how we want to express reach of media work.

**Comment by brettgaylor** [comment]
Ugh - @KevZawacki no dont do that!  Do you already have pubs categorized as tier 1, 2, 3?

**Comment by KevZawacki** [comment]
@brettgaylor No, but that's easy to do. 

I could also research UMV for the 10 or 15 most-read publications. Then we could say something like, "Placements in POLITICO, TechCrunch, xx, yy, zz, etc., alone netted us 150M views."

**Comment by KevZawacki** [comment]
I think we should quantify press metrics by:

-- Number of mentions
-- Sentiment (positive, neutral, negative)
-- Quality of mentions (tier 1, 2, 3)
-- High-level impact (see above comment)

@brettgaylor thoughts?

**Comment by brettgaylor** [comment]
Yes, that feels appropriate.  No need to begin till next week however once the broader strokes of the board deck are settled.

@KevZawacki are we tracking sprinklr mentions still?  We could combine EU/codemoji with copyright with that

@vojtechmzl would you be able to help with totalling unique views for codemoji/encryption/copyright next week?

**Comment by vojtechsedlak** [comment]
Yup, absolutely.

**Comment by KevZawacki** [comment]
@brettgaylor Yep, we have Sprinklr numbers for Encryption and Codemoji. 

Copyright is tough -- our contract with Sprinklr expired, so we have limited data from the past month. Further, most copyright chatter is taking place on FB, which Sprinklr isn't great at fetching from.

BUT @vojtechmzl has some nifty scripts that also measure social. So that should do the trick :-)

**Comment by KevZawacki** [comment]
**COPYRIGHT** (as of 10/17/16)
- **Press mentions**: 114
- **Press sentiment**: 64% positive, 36% neutral, 0% negative
- **Press quality**: 20% tier 1, 32% tier 2, 48% tier 3
- **Press geo spread**: 19 countries (Australia, Austria, Belgium, China, Estonia, France, Germany, Hungary, Ireland, Italy, Mexico, the Netherlands, Norway, Poland, Portugal, Russia, Spain, UK, U.S.) 
- **Press impact**: Capstone placements include Hipertextual (3.3M unique monthly visitors),  POLITICO EU (1.5M unique monthly visitors), v3 (2.6M unique monthly visitors), and Heise (6.4M unique monthly visitors).
- **Op-ed?** Yes; [EU Observer](https://euobserver.com/opinion/134752)
- [Full coverage report](https://docs.google.com/spreadsheets/d/1AUmq2rekAi0BmZBWOIuwsCtkzDyD9ZSFKBiy6tffajA/edit#gid=0)

**CODEMOJI**
- **Press mentions**: 134
- **Press sentiment**: 96% positive, 3% neutral, 1% negative
- **Press quality**: 22% tier 1, 31% tier 2, 47% tier 3
- **Press geo spread**: 25 countries (Argentina, Australia, Brazil, Chile, China, Colombia, Costa Rica, Dominican Republic, France, Germany, India, Ireland, Italy, Japan, Mexico, the Netherlands, Peru, Poland, Russia, Spain, Taiwan, UK, U.S., Ukraine, Venezuela)
- **Press impact**: Capstone placements include coverage in TechCrunch (12M unique monthly visitors), Mashable (45M unique monthly visitors ), Slate (25M unique monthly visitors) El Androide Libre (10M unique monthly visitors), and WIRED Germany
- **Op-ed?** No; none pitched
- [Full coverage report](https://docs.google.com/spreadsheets/d/1seVzFajQEwRiGUb7eHbirCk2aPcDH87J5jJerjQI5ak/edit#gid=0)

**ENCRYPTION**
- **Press mentions**: 162
- **Press sentiment**: 100% positive / neutral 
- **Press quality**: 22% tier 1, 28% tier 2, 50% tier 3
- **Press geo spread**: 19 countries (Australia, Bolivia, Brazil, Canada, Colombia, Costa Rica, France, Germany, Guam, Ireland, Italy, Kenya, Mexico, Peru, Poland, Spain, UK, U.S., Venezuela)
- **Press impact**: Capstone placements include coverage in NPR Morning edition (13M unique weekly listeners), CNN (87M unique monthly visitors), and The Guardian (34M unique monthly visitors)
- **Op-ed?** Yes; [CNN](http://www.cnn.com/2016/02/18/opinions/apple-encryption-backdoor-fbi-surman/)
- [Full coverage report](https://docs.google.com/document/d/1LryyQV2ssyPZl4lpeG3YVwVQakFBn2fE_7sEjaGNz9M/edit)

## 

**TOTAL**
- **Press mentions**: 404
- **Press sentiment**: 81% positive, 19% neutral, <1% negative
- **Press quality**: 21% tier 1, 31% tier 2, 48% tier 3
- **Press geo spread**: 35 countries on six continents. (Argentina, Australia, Austria, Belgium, Bolivia, Brazil, Canada, Chile, China, Colombia, Costa Rica, Dominican Republic, Estonia, France, Germany, Guam, Hungary, India, Ireland, Italy, Japan, Kenya, Mexico, the Netherlands, Norway, Peru, Poland, Portugal, Russia, Spain, Taiwan, UK, Ukraine, U.S., Venezuela)
- **Press impact**: Placements in NPR, CNN, The Guardian, TechCrunch, and scores of other publications; reached over 200M readers. 
- **Op-eds?** In CNN and the EU Observer

**Comment by vojtechsedlak** [comment]
Here are the metrics you inquired about @brettgaylor:

**Websites**
- Encryption campaign
  - 1,060,561 unique pageviews
- Codemoji
  - 2,363,834 unique pageviews
- Change Copyright
  - 1,003,595 unique pageviews
- Postcrimes
  - 11,761 unique pageviews
- **TOTAL = 4,439,751**

**Video**
- Encryption
  - YouTube
    - 19,337
  - Website
    - 487,569
  - Snippet
    - 1,147,300
  - Organic Social
    - 213,084
  - Paid Social
    - 2,103,316
  - **TOTAL = 3,970,606**
- Copyright
  - YouTube
    - 31,520
  - Website
    - 95,108
  - Social (organic+paid)
    - 176,834
  - **TOTAL =  303,462**
- **TOTAL = 4,274,068**

**Social Engagement**
- Codemoji
  - 8.666
- Encrypt
  - 41,771
- Change Copyright
  - 14,632
- Postcrimes
  - 17
- **TOTAL = 65,086**

**Comment by brettgaylor** [comment]
Awesome!  Thank you @KevZawacki @vojtechmzl !

**Comment by KevZawacki** [comment]
@brettgaylor @HPaulJohnson Earned media metrics complete -- see comment above.

**Comment by KevZawacki** [comment]
Hi @brettgaylor,

I've spent a bit more time assessing how we classify press hits (tiers 1-3). As a result, I've updated the "Press Quality" sections in my analysis above. Nothing major, just more discerning between what's tier 1 and what's tier 2. 

If you've ported that information into any decks, let me know -- I can update there, as well. 

@vojtechmzl, can we updated the copyright earned media dashboard accordingly? New data: 20% tier 1, 32% tier 2, 48% tier 3. [Here's the spreadsheet](https://docs.google.com/spreadsheets/d/1AUmq2rekAi0BmZBWOIuwsCtkzDyD9ZSFKBiy6tffajA/edit#gid=0).

**Comment by brettgaylor** [comment]
Thanks, Kevin!  Really useful.

What's the criteria for the different tiers? Is it circulation, subjective importance, etc?

**Comment by KevZawacki** [comment]
@brettgaylor A mix of reach (daily/monthly readership) and prestige. The ranking process is inherently subjective, but I'm trying to create a single framework that can be applied to multiple campaigns. 

So NYT would always be tier 1, The Next Web would always be tier 2, etc.

Perhaps we need to revisit this down the line, but it works well for 2016.

**Comment by vojtechsedlak** [comment]
Dashboard updated @KevZawacki 

Speaking of media reach I've also been toying around with the idea of using social shares as a proxy for media reach. Essentially, we can see how many times an article has been shared on Facebook and extrapolate the possible readership from that value. If we for instance say that on average 1% of readers share an article on social media, then an article with 100 Facebook shares would have been seen by ~10,000 people. I am working on compiling numbers for the Copyright campaign and so far I can see that the articles have generated around 2,000 shares on Facebook, which would translate to 200,000 readers. The question here is what should be the average sharing rate (i.e. is it 1%, 3%, 5%?). Let me know if you guys have any thoughts. This is something we could be using going forward as a fairly easy way of estimating reach of press hits and it's also directly correlated to the tier system, since tier 1 media generate most shares. 

Sorry for the lengthy post.

cc @brettgaylor

**Comment by vojtechsedlak** [comment]
So it's actually ~4,900 shares that the articles generated so here are the breakdowns based on different sharing rates:
- 1% of readers shared -> 490,000 readers
- 2%  of readers shared -> 245,000 readers
- 3% of readers shared -> 163,300 readers

**Comment by valianttry** [comment]
Closing this, please re-open if it's still being worked on.
