### ISSUE TITLE
Build Maker Party > Nationbuilder > Salesforce integration QA checklist

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#524]
Detailed description of work:
We need to run a details QA to make certain that host and rsvp registration data is all flowing correctly through to Salesforce. This is critical to get right so that audience targeting for email works properly in the future, among other reasons.

_Start date: September 28, 2016_ 
_Due date: October 4, 2016_ 

CC: @jendc123 @stephaniemcv

**Comment by imagerwalt** [comment]
Both of the hosts and rsvps are under "CampaignMembers" object, there's a dropdown inside the object for the type, hosts are as "host" and rsvps are as "attendee" 

I think it's been tested, so it should be resolved, but I'll look again once I get the access to SF again.

**Comment by valianttry** [comment]
Thanks @imagerwalt !

**Comment by valianttry** [comment]
This work is paused until Andrew comes back up for air after Dreamforce. Data is being held and stored in Nationbuilder for now.

from Andrew: 
_Since we couldn't rely on Fission's code not to use up our API data, we deactivated their Production account until we felt confident that it was fixed. Walter requested a test Heroku instance to test his code, he's had access to Sandbox the entire time, and Nationbuilder will be housing the MP and Petition records until we reconnect so we don't delay Maker Party launch.

I know that Walter said he was confident it was fixed but I thought we discussed holding off on reconnecting Production until we were back from Dreamforce so I/we could monitor traffic._

**Comment by valianttry** [comment]
QA for data passthrough is tracked in this spreadsheet:
https://docs.google.com/spreadsheets/d/106zfqsmCKmovmSDHvoqvHFCZuE8zG-BKbWZNewZM3xY/edit#gid=1915745399

**Comment by valianttry** [comment]
From @drewmoto the final outcome from QA:

Hi Andrea et al.,

We finished the majority of the test cases yesterday which I think gave us a good representation of where we are at with the functionality of the tool currently. Unfortunately, most of the test cases failed in some form or another. Some of them were localization issues and languages not being captured correctly in Salesforce. They were noted and assigned to Fission.
It is up to the Foundation if the localization issues are critical-blockers along with the Social Media sharing issue and the format of the welcome email template. The languages not passing through to Salesforce is a lower priority in my mind since NB can hold the data while a fix is implemented.

Fission team - Let us know if you have any questions on our findings and what the timing on fixes is.
