### ISSUE TITLE
Maker Party QA: Not allowing Twitter Auth for sharing locks me out of site

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#525]
After setting up an event or RSVP'ing for an event, I clicked share on Facebook and Twitter. I was then prompted to allow access to Twitter app. I said no and then an endless loop began. 

Once I've said no to twitter app access once and I go to login into my account I get redirected to this page (step 1): 

![mp_twt_auth](https://cloud.githubusercontent.com/assets/10078715/18933714/e8cda3b2-858a-11e6-9685-46122a016069.jpg)

If click cancel on this screen, I get redirected to this page (step 2): 
![mp_twt_auth_2](https://cloud.githubusercontent.com/assets/10078715/18933749/101f625c-858b-11e6-9b3d-579dbd0235c0.jpg)

Clicking on "Return to Nationbuilder" returns me back to step 1. And the loop begins. Even if I type makerparty.community directly into the URL I get redirected to step 1 twitter auth page; I'm essentially locked out of the site unless I agree to give it access to my twitter. 

It's bit convulted to recreate, and I'm now locked out in all my browsers, but I think the path to recreate is login, setup an event, on the share screen select twitter and, when prompted, say no/cancel.

**Comment by HPaulJohnson** [comment]
This also happens on the post RSVP share flow (not just host/share) but only if I'm previously logged into Nation Builder.

**Comment by gholme4** [comment]
@HPaulJohnson @valianttry We've contacted NB support about this problem. The same thing happens for Facebook.

**Comment by valianttry** [comment]
Answer from Nationbuilder support:

_From: help@nationbuilder.com
Subject: Re: Prompt to share problem
Date: September 29, 2016 at 1:44:37 PM CDT

Hi George,

After some additional testing, it appears that this problem only occurs for control panel users. While we recognize that this is not ideal, control panel users can share their pages directly from the control panel. All other users should be able to share their events and RSVPs from the front facing site as expected.

Please let us know if you encounter any problems with this workaround!

Best,
Lauren Rowse
NationBuilder Support_

**Comment by valianttry** [comment]
#Wontfix
