### ISSUE TITLE
Maker Party: Design icons for snippet promo for MP Stunt

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#526]
Starting on 10/12 we'll be kicking off Maker Party it a "stunt" to get as many people as possible to upload photos to the commons in a single day. Part of that promotion is snippet.

Maura and Liz from MoCo social team are managing this part of the campaign and we are supporting on the design. They'll do copy but we can track icon design here. 

cc @natalieworth @lovegushwa

**Comment by natalieworth** [comment]
Snippet drafts are here @HPaulJohnson:https://redpen.io/p/qj4d60f2ac98a50591
 I also emailed the redpen to Maura and Liz to take a look
cc @lovegushwa @beccaklam

**Comment by natalieworth** [comment]
Maker party snippet icon drafts are up on redpen: https://redpen.io/p/qj4d60f2ac98a50591 and waiting for the Firefox team to check them.

The stunt launch has been pushed back until Oct 12—so we have a little bit of leeway to get these done. I'll be one PTO until Oct 4, so here is the illustrator file with the different snippet versions in case something comes up before I am back: https://drive.google.com/file/d/0B20-0lpP23c0MFlDeGxLeV9HMmM/view

cc @lovegushwa @beccaklam
