### ISSUE TITLE
Optimized images to speed up petition pageload

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#527]
@gholme4 @cadecairos 

I optimized the v2 petition images, this should speed up the time it takes to load the petition. I think it's probably as easy as overwriting the old images but bablic may complicate this. 

https://drive.google.com/drive/folders/0B2qu3ExKWIlvTDJUeThFaDA1QzQ?usp=sharing

CC @jendc123 @brettgaylor @valianttry @HPaulJohnson

**Comment by gholme4** [comment]
@lovegushwa I replaced the images with the optimized versions.
