### ISSUE TITLE
Email Volume KPI

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#528]
Detailed description of work:  What Andrea is looking for:
_Dramatically increased volume
Steph can we make a charge for volume increase over time? Like since we started using BSD (2011-2012)
Vojtech can help grab this “over time” view of volume and segmentation // modeling our strategy on behavioral data vs. general preference. Better personalization._

Utlizing the BSD History doc I shared with you can you create:
-  a breakdown of how many emails we created (Not list size or delivery, the actual emails themselves) by year and quarter. (Foundation as a whole vs Advo/Fundraising).
- Segmented emails vs full list sends (Advocacy/Fundraising only)

For 2016 you will need to go into SFMC and pull an email send report or by user (Tracking--Reports) and break it down by the above.

_Start date: September 29, 2016_ 
_Due date: October 4, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by vojtechsedlak** [comment]
Here are a few ways of capturing the changing nature of email volume in the last few years.

**1. Number of emails sent per quarter (Advocacy+Fundraising vs. All MoFo)**
The graph shows that in the last few quarters, the overall volume of emails sent has been increasing. In the past the biggest bumps were associated with EOY fundraising.

![image 2](https://cloud.githubusercontent.com/assets/20688240/18975094/8c946f40-865c-11e6-89b9-7e0dc9126be5.png)

**2. Avg number of targeted supporters per email (Advocacy+Fundraising vs. All MoFo)**
We can see a decrease in the last few quarters in the average number of individuals who are targeted by our emails. This is evidence of increased segmentation.
![image 1](https://cloud.githubusercontent.com/assets/20688240/18975181/26dd8fa0-865d-11e6-96f2-a2d429ee802a.png)

**3. Avg number of targeted supporters vs. Total number of emails sent (Advocacy+Fundraising)**
Combining the above two charts, we can see the relationship between the two metrics. As the number of emails sent increases, the avg number of targets decreases. The trend is particularly notable in the last year and a half.

![image](https://cloud.githubusercontent.com/assets/20688240/18975210/53567b82-865d-11e6-8e23-26bc78f4f6b8.png)

Let me know if this would work for the presentation @stephaniemcv @valianttry or if you had something else in mind.

Thanks.

**Comment by stephaniemcv** [comment]
@vojtechmzl your amazing graphs just made my day, sir!

**Comment by valianttry** [comment]
@vojtechmzl can you drop a link to the spreadsheet where these charts live? I can't see where Q1 -3 2016 lives on that last chart and I want to make sure I get the totals correct. Thanks! This is truly awesome, and it's so good to see we're following through with our plans. :medal_sports:

**Comment by vojtechsedlak** [comment]
[Here](https://docs.google.com/spreadsheets/d/1wsaGg1QUAl-9hTKzjTH6y-oSPYlOXr1PcnlRB1DcidE/edit#gid=1741832897) is the raw spreadsheet @valianttry. In Q1 2016, the advocacy team has produced the total of 29 emails. Let me know if there is anything else I can drill deeper into.

**Comment by vojtechsedlak** [comment]
Closing this for now, let me know if there is anything else I can follow up on @stephaniemcv. Thanks!
