### ISSUE TITLE
Doesn't have a contribute.json

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#529]
Detailed description of work: Received a bug report in my email regarding "CHANGECOPYRIGHT.ORG". It doesn't have a contribute.json (Not sure what this means, I was just the first person they found in Phonebook)
 @ScottDowne @cadecairos 
![petition-js-error](https://cloud.githubusercontent.com/assets/11812272/18936949/2b3759c8-85a9-11e6-9f8e-a8fe031e9934.jpg)

_Start date: September 28, 2016_ 
_Due date: September 28, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @valianttry @jendc123

**Comment by cadecairos** [comment]
They're referring to this Mozilla norm that we've yet to adopt across many MoFo projects: https://www.contributejson.org/

Essentially a standard format for describing a project, where it's hosted (source), who's responsible, where  to file bugs, etc.

**Comment by cadecairos** [comment]
Thing is, this isn't really a project that people can contribute to, since it's built on a closed platform...

**Comment by stephaniemcv** [comment]
Should I forward you the email and you can respond?

**Comment by ScottDowne** [comment]
I think it's fair to say we won't be able to actually do what they are requesting, but yeah, maybe we can respond somehow in a somewhat positive way?
