### ISSUE TITLE
Codemoji bug: Key emoji section doesn't auto-scroll in Firefox

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#53]
Steps to reproduce:
1. I receive a Codemoji URL from a friend and am asked to decipher. 
2. I decipher it (FUN!) and then I go up into my address bar and refresh the codemoji URL to send my own codemoji.
3. I type a message, but then there's no scroll bar available in the middle section to pick my key.
4. I have to use "down arrow" in order for it to scroll in FF AND in Chrome.

![codemoji_ _a_fun_tool_to_learn_about_ciphers](https://cloud.githubusercontent.com/assets/9830371/15876584/053b132a-2cc3-11e6-8297-3541e39325ef.png)

cc @HPaulJohnson @ScottDowne @lovegushwa 

![screen_shot_2016-06-07_at_3_18_55_pm](https://cloud.githubusercontent.com/assets/9830371/15878294/91e6636e-2cce-11e6-9a84-11e39df2e5d1.png)

**Comment by ScottDowne** [comment]
I sometimes see a scrollbar and sometimes I do not.

Actually currently I cannot make it come back :(

I'll debug some more.

**Comment by ScottDowne** [comment]
If you go there from https://learning.mozilla.org/codemoji/#/welcome scrollbar works, from https://learning.mozilla.org/codemoji/#/encrypt it does not.

**Comment by ScottDowne** [comment]
Looks to be fixed. Reopen if I am incorrect.
