### ISSUE TITLE
Email: Attend a Maker Party! 

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#530]
Detailed description of work: Create and route copy to encourage RSVPs to Maker Partys
Audience: Anyone on existing Maker Party lists; anyone who signs the petition. 
Suppression: Unengaged, Maker Party Hosts, Maker Party Attendees
Localization: DE, FR, EN-UK, ES, PL
Draft: @cristina-moon
Send date: 10/19/2016

_Start date: September 29, 2016_ 
_Due date: October 7, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @valianttry  @shaghdoosti

**Comment by stephaniemcv** [comment]
Design: #531 
Build: #532
QA: #533

**Comment by cristina-moon** [comment]
[Email draft is here!](https://docs.google.com/document/d/141_asVQYWU6F2-Zj3hhbhO9UmOWoP3hKbCzM2ubXuj4/edit?usp=sharing) Ready for feedback and edits from @valianttry and @shaghdoosti.

@stephaniemcv question for you: Are we able to use standard or custom fields in callouts or subject lines?

**Comment by cristina-moon** [comment]
Welcome back from MozFest, @shaghdoosti and @valianttry -- Attend a Maker Party email draft is ready for your review!

**Comment by valianttry** [comment]
Looks great! I made a few suggested edits and notes. Thanks!
