### ISSUE TITLE
Multiple emails with the message "Come to MozFest"

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#534]
Detailed description of work: **This is a discussion and clarification ticket.**
The MozFest team have a MozFest reminder email scheduled for 10/26. During Advocacy email calendaring we talked about also having a Come to MozFest email sent on 10/24.

I do not recommend that we have basically the same two emails going out the same week. Granted these would be to two different lists MozFest & MakerParty/EU. But I am flagging two concerns:
- A MozFest message to the MakerParty list may be confusing.
- At this time, the overlap between the two audiences/list is unknown.

@Saallen @KGorr @shaghdoosti Please discuss and decide how we should proceed with these emails.

_Start date: September 29, 2016_ 
_Due date: October 10, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @valianttry

**Comment by KGorr** [comment]
The email from the mozfest team will be going to only those register for the festival - ticket holders. It will include last minute prep items and reminders. 

I'm not sure what your note at the bottom of the ticket means @stephaniemcv - can you clarify?

**Comment by stephaniemcv** [comment]
@KGorr Does that mean your team will be using Tito to send the email? If so, I'll take it off the main launch calendar.

If you mean the start date/due date, it's for some Zenhub reporting.

**Comment by KGorr** [comment]
How hard is it to import over all ticket holder contact info? TiTo doesn't have as much functionality as Exact Target (meaning, it will look way pretty if you send), but we can do in TiTo if that makes the most sense.

**Comment by stephaniemcv** [comment]
TiTo would probably make the most sense.

Technically, an import itself into SalesForce is not difficult. There is however, no current data structure to designate that these are ticket holders. So we would end up doing a very messy external data extension and query setup that is probably not going to be worth the level of effort.

**Comment by KGorr** [comment]
+1 you can take us off the list then! Thanks, @stephaniemcv

**Comment by stephaniemcv** [comment]
The only question then remains is if you still want Advocacy to promote MozFest on 10/24. Targeted audiences would be: Maker Party; geotargeted: UK only. I'll let you and @shaghdoosti discuss/decide that.

**Comment by KGorr** [comment]
Would love your input here, @Saallen @edrushka @KevZawacki

**Comment by edrushka** [comment]
Can you clarify what you mean by "promote MozFest"?

By 10/24 Tickets will have sold out (fingers crossed). If the Advocacy list was to promote MozFest, I would suggest highlighting the content of our Dialogue and Debate speakers series, which will be streamed live and then archived on the MozFest website. Some of the talks will have serious appeal/relevance to that list.

**Comment by KevZawacki** [comment]
Agree with @edrushka -- the D+D speaker series is most relevant for the advocacy list

**Comment by stephaniemcv** [comment]
Per @shaghdoosti "I think they're very different emails to very diferent list segments". I'm making to call to remove this email from Advocacy's calendar. Thank you everyone for your discussion and input!
