### ISSUE TITLE
Email: Last Chance Attend a Maker Party!

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#535]
Detailed description of work: Create and route copy to encourage RSVPs to Maker Parties
Audience: Anyone who received the first RSVP email and did NOT register.
Suppression: Unengaged, Maker Party Hosts, Maker Party Attendees
Localization: DE, FR, EN-UK, ES, PL
Draft: @cristina-moon
Send date: 10/26/2016

_Start date: September 29, 2016_ 
_Due date: October 14, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @valianttry @shaghdoosti

**Comment by stephaniemcv** [comment]
Design: #536 
Build: #537
QA: #538

**Comment by cristina-moon** [comment]
[Draft copy for the Attend a Maker Party Last Chance email](https://docs.google.com/document/d/1-eNqq2m---6iY6m_Oj5YTS9oCksTFswATwK4wS196bE/edit) for review from @shaghdoosti and @valianttry :)
