### ISSUE TITLE
Build: Last Chance Attend a Maker Party!

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#537]
Detailed description of work: Code and load copy & design

_Start date: October 19, 2016_ 
_Due date: October 24, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by valianttry** [comment]
@stephaniemcv I assigned a milestone but feel free to update it. :)
