### ISSUE TITLE
Quick copyedit to Codemoji banner on encryption site

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/Advocacy#54]
Small edit needed to the below banner, which appears [here](https://advocacy.mozilla.org/en-US/encrypt/codemoji-b/1):

![screen shot 2016-06-08 at 9 19 18 am](https://cloud.githubusercontent.com/assets/11045250/15932012/09629322-2e28-11e6-9836-cd6dacc313c2.png)

@ScottDowne Can we change to: "Introducing Codemoji, an educational game that teaches you about cipher**s**, the building block**s** of encryption." (Make "cipher" and "building block" plural.)

**Comment by KevZawacki** [comment]
@ScottDowne With external comms around Codemoji happening next week, possible to update this before 6/28?

**Comment by ScottDowne** [comment]
It's on staging: https://advocacy-mozilla-org-staging.herokuapp.com/en-US/encrypt/codemoji/1

If it looks a ok, I can move it to prod anytime.

**Comment by KevZawacki** [comment]
@ScottDowne Yep, looks a-ok. Ready to move! Thanks.

**Comment by ScottDowne** [comment]
Done
