### ISSUE TITLE
Maker Party: Facebook Share Not Working on https://www.makerparty.community/

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#540]
Detailed description of work:

When I click on the Facebook Share button in the right margin of https://www.makerparty.community/ I see the same error we've seen repeatedly with the petition Facebook share. 

![error_and_post_to_facebook](https://cloud.githubusercontent.com/assets/9830371/18940258/7094417c-85bb-11e6-8f29-a4db6fbe1a9a.png)

See also #318 

Correct copy for social shares for Maker Party pages is here:
https://docs.google.com/document/d/1YBoLZ5f7KL4yVgzPI9HMES-SX3yAZ7N9p4vSTYVAedo/edit

_Start date: September 29, 2016_ 
_Due date: October 3, 2016_ 

cc: @HPaulJohnson

**Comment by gholme4** [comment]
@valianttry A Facebook app needs to be created for makerparty.community. Please send me the app ID after it's created.

**Comment by valianttry** [comment]
I asked @ScottDowne to help here.

**Comment by ScottDowne** [comment]
Can do.

**Comment by ScottDowne** [comment]
@gholme4 Done. The public id is 336654656680907

And you have been added as a developer on it.

**Comment by gholme4** [comment]
@ScottDowne I do not have access to the FB app. Did you copy my same information from copyright-petition? Can you please take it off development mode?

**Comment by ScottDowne** [comment]
@gholme4 I sent an invite to gholme4, which is currently says (pending). not sure if that means it's waiting on you to confirm, of it it's still sending the invite.

I'm looking for the button to make it live now.

**Comment by ScottDowne** [comment]
@gholme4 OK, should be live now.

**Comment by gholme4** [comment]
@ScottDowne Sorry. I keep forgetting about accepting the invitation. Thanks.

**Comment by ScottDowne** [comment]
np :)

**Comment by gholme4** [comment]
@ScottDowne @valianttry This works now. What is the share image for FB?

**Comment by ScottDowne** [comment]
@valianttry Yup, works, we just need an image. I'm clearing myself as assignee, though.

**Comment by valianttry** [comment]
@HPaulJohnson or @lovegushwa can you drop a link to the maker party Facebook share image here? TY!

**Comment by lovegushwa** [comment]
We should have a makerparty share ready tomorrow. Coming from @beccaklam. 
@HPaulJohnson do you know if a square image will work?

**Comment by lovegushwa** [comment]
@beccaklam I think the fist in the air should work well as the default.

**Comment by lovegushwa** [comment]
We're going to with a maker party brand for the share, the link is here: 
https://drive.google.com/file/d/0B2qu3ExKWIlvbTJVOFhGN2MxRE0/view?usp=sharing

![maker-party-600x300](https://cloud.githubusercontent.com/assets/12228435/19008651/7b08f686-8721-11e6-99d1-a45479276328.jpg)

**Comment by lovegushwa** [comment]
@gholme4 see the link above for the marker party share.
CC @HPaulJohnson @jendc123

**Comment by gholme4** [comment]
@lovegushwa I added the new share image.
