### ISSUE TITLE
Clear all TEST events in preparation for soft launch

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#541]
Detailed description of work:
We will be inviting a few early hosts to add REAL events starting Thursday 9/29 EOB PST. We would like to purge all test events and "Fake" data by that time.

_Start date: September 29, 2016_ 
_Due date: September 29, 2016_ 

CC: @jendc123  adn gholme4

**Comment by imagerwalt** [comment]
Ah I mentioned that on the other ticket #477 these are some test events just want to run by you before I deleted them, here's the original message:

Hey @drewmoto I've deleted most of the test ones. There are still a few left, but just want to run by you just in case. (see the attached image)

There're a bunch with the emails like mp.trusted.host@gmail.com or mp.volunteer.manager@gmail.com those I believe are test events as well.

Anyway I'm moving the credential from sandbox to prod now, will let you know when it is tested and deployed
![screen shot 2016-09-28 at 11 13 34 am](https://cloud.githubusercontent.com/assets/283657/18967660/f1041402-863a-11e6-9442-0e85714b05b0.png)

**Comment by drewmoto** [comment]
@imagerwalt @valianttry On the salesforce side I can only see that they were created by the Fission SF Account. But I think we can safely assume they are test records. I looked up the email mp.trusted.host@gmail.com and the Contacts name was 'Jamie Trusted Host'

**Comment by valianttry** [comment]
There are currently zero real events in the system. Fine to delete all and associated records. If testers end up being real hosts, they can just sign up again. NBD.

**Comment by jendc123** [comment]
@valianttry @drewmoto @imagerwalt  - mp.trusted.host@gmail.com is definitely a test account. We have a couple version of them.  We created them to test different permission levels.  They can be cleared.
