### ISSUE TITLE
Temporary Bablic account for Petition V2.5 (new form)

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#542]
Detailed description of work:
[9/29/16, 1:24:09 PM] Jennifer OReilly Mott: Is Chris able to create a new paid account in Bablic for v2.5?
[9/29/16, 1:24:35 PM] Jennifer OReilly Mott: We will only need the account for today and then we can delete it

_Start date: September 28, 2016_ 
_Due date: September 29, 2016_ 

CC:

**Comment by cadecairos** [comment]
a few q's:
- What URL am I setting it up with
- what languages
- who needs access

**Comment by jendc123** [comment]
Hi @cadecairos - the languages are the same as v2 and the same people need access.  The url is [https://petitionv25-mozillafoundation.nationbuilder.com/](url)

cc @valianttry

**Comment by cadecairos** [comment]
Bablic isn't letting me add the site: ![bablic](https://pageshot.net/images/b29cbf41-cf25-4833-80fe-5afd4cbaffff)

**Comment by jendc123** [comment]
@cadecairos @valianttry we removed the snippet.

**Comment by cadecairos** [comment]
Completed!
