### ISSUE TITLE
QA Fail: Translations of Nyan Cat dissapeared

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#544]
Oddly, the Nyan cat translations of "meme land" are now back to English.  Here is the Italian locale:

![image](https://cloud.githubusercontent.com/assets/345974/18972916/e0c7cb28-864f-11e6-8c76-2189d1aa2407.png)

This was working last night and early this morning.

**Comment by brettgaylor** [comment]
cc @jendc123 @gholme4

**Comment by jendc123** [comment]
@brettgaylor -  I'm pretty sure we caused this when we updated the images to a smaller file size.  I've updated. This is ready for review.

**Comment by brettgaylor** [comment]
Yay!  Thanks for that :)  Worked for me. Will close.
