### ISSUE TITLE
Add 'cookies' URL to the bottom footer nav of petition and maker party pages.

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#545]
Detailed description of work:
Abigail and Mika from legal recommend that we add a link about cookies to our Copyright campaign websites. This is the same link we now have on all mozilla.org pages. This would be a universal change for both Maker Party pages and petition pages.

The URL is:
https://www.mozilla.org/privacy/websites/#cookies

_Start date: September 30, 2016_ 
_Due date: October 13, 2016_ 

CC: @lovegushwa 

![internet_for_people__not_profit_ _mozilla](https://cloud.githubusercontent.com/assets/9830371/18997854/16d4412e-86eb-11e6-9841-b9e018cb4238.png)

**Comment by valianttry** [comment]
@lovegushwa is making an icon

**Comment by lovegushwa** [comment]
@gholme4 legal asked us to add this cookie icon: 
https://drive.google.com/file/d/0B2qu3ExKWIlvOTZMRVpwMUpfeWc/view?usp=sharing

You can link it to this page: https://www.mozilla.org/privacy/websites/#cookies

<img width="794" alt="screen shot 2016-10-09 at 10 30 04 pm" src="https://cloud.githubusercontent.com/assets/12228435/19227578/b3decf20-8e70-11e6-8852-ed792743f549.png">

**Comment by gholme4** [comment]
@lovegushwa @valianttry #readyforreview

**Comment by valianttry** [comment]
I reviewed on Maker Party -- it's approved and looks great there.

@gholme4 one edit to the footer on the petition pages:

"Contact Us" should point to makerparty@mozillafoundation.org

**Comment by valianttry** [comment]
I also sent an email to makerparty@mozillafoundation.org . @stephaniemcv can you check to see if it comes through to Desk.com?

**Comment by valianttry** [comment]
@stephaniemcv I got the autoreply so it looks as though the email is working correctly:

![hey__read_me_stephanie_-_andrealw_gmail_com_-_gmail](https://cloud.githubusercontent.com/assets/9830371/19259028/8ea1d30c-8f32-11e6-84e3-f766acab0a17.png)

**Comment by gholme4** [comment]
@valianttry I updated the petition contact us link.

**Comment by TheoChevalier** [comment]
Here are the translations for “Cookies”, pulled from the footer of mozilla.org pages:
https://transvision.mozfr.org/string/?entity=mozilla_org/main.lang:3d8e1b5f&repo=mozilla_org
We can safely reuse those translations as the context is the same.

If it’s more convenient, a JSON file is available here https://transvision.mozfr.org/api/v1/entity/mozilla_org/?id=mozilla_org/main.lang:3d8e1b5f

Feel free to ping me if you need anything else

**Comment by valianttry** [comment]
hi @gholme4 apologies for some confusion.

I believe the footer should not have a "join the conversation" link. It should be replaced by a "code of conduct" link. It should match what you see in this comment:
https://github.com/MozillaFoundation/Advocacy/issues/461#issuecomment-252541087

**Comment by valianttry** [comment]
@TheoChevalier if you get your bablic login, this is a great first edit to start to get to know it as a user. If you get your bablic login, let me know I can give you a quick tutorial. It's pretty straightforward.

**Comment by TheoChevalier** [comment]
@valianttry Sure, I’d like to give it a look, but I still have not received my account atm.

**Comment by stephaniemcv** [comment]
@valianttry 
Tis working. I see it under the Maker Party Inbox in Desk.com

**Comment by gholme4** [comment]
@valianttry I replaced the Join the conversation link with Code of Conduct.
