### ISSUE TITLE
Test Idea: Optimize Petition Form Title (currently "Sign the petition")

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#546]
Detailed description of work: As per brainstorming conversation in August, let's test different variations of the petition title that appears at the top of the form.

Tested Variants:
- Sign the petition
- Take Action
- Show your support

_Start date: September 20, 2016_ 
_Due date: October 14, 2016_ 

CC:

**Comment by vojtechsedlak** [comment]
The results on this test are in @valianttry @HPaulJohnson. As you can see in the graph below, **Show your support** won the test, with 98% statistical significance. It improved the petition conversion rate from 5.66% to 9.07%, which is a fairly substantial increase. The tested audience here was only English and the test ran on the v2 design (without the multi-step form). My recommendation would be to get the Show your support string translated into as many languages as possible and either retest or implement on the petition site.

Please let me know if you have any questions! Happy to support as much as I can, just not sure what the localization process looks like. Thanks!

<img width="1271" alt="screen shot 2016-09-30 at 12 31 32 pm" src="https://cloud.githubusercontent.com/assets/20688240/19004318/32f3d062-870a-11e6-9e2c-e6c9d0f35624.png">

**Comment by HPaulJohnson** [comment]
whoa, that's awesome @vojtech. with the paid media stuff running, the more we can do quickly to optimize our conversion petition, the better off we are going to be with getting our CPA's down. 

@valianttry I'm happy to get this loaded up for localization. assuming the process is the same, i.e. put it into github and it gets sucked into pontoon for translation?

**Comment by valianttry** [comment]
I submitted the phrase to Kontextor for localization. Will update this ticket when she gets back with the translations!

**Comment by valianttry** [comment]
Kontextor provided translations:

DE: Machen Sie mit
ES: Muestra tu apoyo
FR: Affichez votre soutien
PL: Pokaż Twoje wsparcie (if too long use: Wesprzyj nas)
IT:  Mostra il tuo sostegno
BG: Покажи подкрепата си
NL: Toon je support
CS: Podpořte nás
EN-GB: Show your support

CC: @vojtechmzl and @gholme4  and @HPaulJohnson
