### ISSUE TITLE
EU Copyright Campaign: Initial reporting and optimization recommendations

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#547]
Detailed description of work: With Paid Media campaign now running, we'll do an initial flash report this week and make some initial recommendations for optimizations for remainder of campaign

_Start date: October 1, 2016_ 
_Due date: October 7, 2016_ 

CC: @vojtechmzl

**Comment by Matt-Holland** [comment]
closing this ticket since the campaign is past
