### ISSUE TITLE
Maker Party: Localize Social Promos

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#548]
Detailed description of work: When social promos for Maker Party are approved in #459 we will submit for localization and track progress in this ticket. 

_Start date: September 30, 2016_ 
_Due date: October 7, 2016_ 

CC:

**Comment by valianttry** [comment]
@HPaulJohnson I'll help you submit this to Kontextor as soon as you're ready. They can turnaround in 24 - 48 hrs with heads up.

**Comment by HPaulJohnson** [comment]
@valianttry these are ready for Kontextor. Final copy here: 

https://docs.google.com/document/d/1AqwFLAogCRQxmjiAA6_DFmgfD4OqtHztpYR-UaGisU8/edit?ts=57eecf41

**Comment by TheoChevalier** [comment]
@HPaulJohnson Hey Paul, anything else needed here, or we can close this ticket?

**Comment by HPaulJohnson** [comment]
@TheoChevalier these are complete and available here:

https://docs.google.com/spreadsheets/d/1dBARa2Pr9NB_Q5ZdPOV1Jx9NOLbATSPk3etSfCWHTkk/edit#gid=452822882

Closing.
