### ISSUE TITLE
Update Tier 2 language videos

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#549]
Detailed description of work:
Localizations are happening in Amara for Tier 2 languages. 

bulgarian
dutch
czech
italian
polish

http://www.amara.org/en/videos/7BbfRhxN6N0V/info/we-love-the-internet/?tab=video

It will require a youtube embed.

_Start date: September 1, 2016_ 
_Due date: October 14, 2016_ 

CC:

**Comment by brettgaylor** [comment]
@jendc123 @gholme4 we have most of these translations completed, and would like to be able to feature the main header video in Dutch, Czech, Italian and Polish

It would require a JS file and some custom HTML per language - is that possible with the lightbox plugin?

Details of embedding are here:
https://github.com/pculture/unisubs/wiki/Embed-Code-Usage-Guide

**Comment by brettgaylor** [comment]
cc @TheoChevalier

**Comment by TheoChevalier** [comment]
Ok, I thought we were using Amara, but we ended up using YouTube quite early. So if it doesn’t work with Amara on NB, we could alternatively use YouTube, I think. It’s been done for Firefox 10 years for instance [1] but here are things to know about doing so: https://www.yetanothertechblog.com/2015/01/15/video-subtitles-and-localization/ With our set of locales, it should be okay, though.

[1] Embedded video with Italian subtitles https://web.archive.org/web/20150113053438/https://www.mozilla.org/it/firefox/independent/

**Comment by brettgaylor** [comment]
@TheoChevalier so how would that work?  We would export subs from amara, and bring them into youtube? Is it possible to force a locale on a youtube embed?

**Comment by brettgaylor** [comment]
also - we do already have the video on youtube that we want to subtitle, if it helps.

**Comment by TheoChevalier** [comment]
If we’re going down that road, here’s how I see it (basically what you said):
- Keep hardcoded direct links to videos with encoded subtitles (French, German, Spanish…)
- Import other locales into YouTube from Amara.

You can force YouTube to display subtitles, but you can’t force it to display a specific locale. That’s part of why it’s bad to use it, but the locales we target should be detected correctly.

To force YouTube showing subs, we just need to add this parameter to the embed code https://developers.google.com/youtube/player_parameters#cc_load_policy (so, adding ?cc_load_policy=1 at the end of the video URL should do it)

As for how YouTube detects the locale, I will leave it to flod: 

> -    If you’re logged in into Google, you’ll get the locale you choose for YouTube. For example I get English subtitles, even if I’m using a browser in Italian (a quick test is to watch the video in private mode).
> -  If you’re not logged in, you’ll get the first good locale based on the Accept Language header sent by your browser. For example, for ‘dsb’ (Lower Sorbian) this equals to “dsb, hsb, de, en-US, en”, and German is the first available language on the list.`

I think it will also work on mobile, but I didn’t check

**Comment by irvin** [comment]
@TheoChevalier I don't understand what "NB" is.

>  if it doesn’t work with Amara on NB

There is a massive advantage to direct embedded Amara - if anyone want to add new locale or improve current subtitles, they can do it on Amara and it will just show up on our site, without the need of our monitoring or download-upload hesitate.

**Comment by TheoChevalier** [comment]
>  I don't understand what "NB" is.

Sorry, NB stands for NationBuilder, the underneath software of the petition website.

> There is a massive advantage to direct embedded Amara - if anyone want to add new locale or improve current subtitles, they can do it on Amara and it will just show up on our site, without the need of our monitoring or download-upload hesitate.

I agree, and that’s definitely something worth mentioning. For this specific project however, we can’t translate the website into additional languages, so localizing the video in new locales would have little value. We’re considering YouTube in case Amara could not be implemented on the petition website.

**Comment by hannahkane** [comment]
Can we close this ticket, or is it still useful?

**Comment by TheoChevalier** [comment]
We will probably have to set up a system for localized video subtitles at some point, but this work won’t happen in this ticket, let’s close it
