### ISSUE TITLE
v2 Petition Site QA: Remove rounded corners on bablic menu

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#550]
@gholme4 please remove the rounded corners from the bablic menu. 

![screen shot 2016-10-03 at 10 14 32 am](https://cloud.githubusercontent.com/assets/12228435/19046846/131f2790-8954-11e6-854f-44e8d40bb4be.png)

**Comment by gholme4** [comment]
@lovegushwa I cannot do that. This request must be sent to Bablic support.

**Comment by lovegushwa** [comment]
@valianttry can we ask Bablic for this? ... Some versions of the site this was fixed, others not.
