### ISSUE TITLE
v2.5 Form QA: Mobile Issues

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Advocacy#551]
Detailed description of work: Issues for v2.5 form on mobile (iOS and Android)
1. On iOS Firefox, Safari and Chrome, when the user taps into the form field it scrolls the user all the way down to the bottom of the page. This doesn't seem to happen on Android Firefox and Chrome.
   ![bug](https://cloud.githubusercontent.com/assets/20977376/19056153/6d059b04-8995-11e6-8861-b9b8d7fe41b3.gif)
2. 'Required Field' and carousel progress buttons overlap (this happens for iOS Firefox, Safari, Chrome and Android Chrome and Firefox)
   ![img_6469](https://cloud.githubusercontent.com/assets/20977376/19055058/20e0d176-8990-11e6-88b8-ac031d0b5f9e.PNG)
3. Form fields cut off for 'Sign The Petition' on iPhone 5, better on large screen sizes (see above for example too)
   ![img_6474](https://cloud.githubusercontent.com/assets/20977376/19055231/ead61900-8990-11e6-8000-0dbfa94d42a0.PNG)
4. 'Sign The Petition' doesn't localize:
   ![img_6479](https://cloud.githubusercontent.com/assets/20977376/19055263/12b6e044-8991-11e6-8246-d0d227576030.PNG)

_Start date: Oct 3, 2016_ 
_Due date: Oct 4, 2016_ 

CC: @lovegushwa @gholme4 @jendc123

**Comment by gholme4** [comment]
@beccaklam Which iOS device are you using? Which version of IOS is it running?

**Comment by beccaklam** [comment]
@gholme4 iOS 10
CC @lovegushwa

**Comment by lovegushwa** [comment]
@beccaklam are you on a iphone 5?

**Comment by beccaklam** [comment]
@lovegushwa Yes

**Comment by gholme4** [comment]
@beccaklam @lovegushwa  I made the hero section smaller in height, since the problem is caused by the form not being in view on page load. 

The second problem is corrected. 

A fix is not apparent for the third issue since "Sign the Petition" will vary in length based on language and won't wrap to the next line. Any suggestions?

**Comment by beccaklam** [comment]
@gholme4 Could we do a media query where when the width of the screen is less than say, 350px (iPhone 5 is 320px) we change the font size from 24px to 20px? 20px seems to accommodate  the smaller screen width:
![screen shot 2016-10-04 at 9 22 13 am](https://cloud.githubusercontent.com/assets/20977376/19075614/b577f4da-8a13-11e6-8866-4ac74e87aa8b.png)
CC: @lovegushwa

**Comment by gholme4** [comment]
@beccaklam I updated with your suggestion.

**Comment by beccaklam** [comment]
@gholme4 I think 'Sign The Petition' has been fixed but the other form fields are still showing at font-size:24px when the screen width is less than 350px. Can we change it so that the form fields for 'First Name, Last Name, E-mail, and Country' are also font-size:20px when the screen width is less than 350px?

Fixed 'Sign The Petition' at 20px
<img width="729" alt="screen shot 2016-10-05 at 2 10 15 pm" src="https://cloud.githubusercontent.com/assets/20977376/19125524/5b2b57fe-8b05-11e6-8553-45e0f46df112.png">

Not Fixed Other Form Field still at 24px when screen width is less than 350px
<img width="732" alt="screen shot 2016-10-05 at 2 09 46 pm" src="https://cloud.githubusercontent.com/assets/20977376/19125540/6e087c44-8b05-11e6-947b-02eb0bc8fbcf.png">

CC: @lovegushwa @valianttry

**Comment by gholme4** [comment]
@beccaklam #readyforreview

**Comment by beccaklam** [comment]
@gholme4 Awesome, looks great!

I found another issue when I was reviewing though: When I tap the 'i' icon:
<img width="24" alt="screen shot 2016-10-05 at 2 53 28 pm" src="https://cloud.githubusercontent.com/assets/20977376/19126976/17bae57e-8b0b-11e6-9abd-8ff8b3b17f42.png"> on my phone, the yellow box doesn't show up. I'm wondering if it's because currently the box appears on hover but one can't hover on phones. Would we be able to enable users to tap the icon and the yellow box would show? This is the box I'm talking about:
<img width="309" alt="screen shot 2016-10-05 at 2 54 44 pm" src="https://cloud.githubusercontent.com/assets/20977376/19127010/410aca52-8b0b-11e6-9271-7520f0cc1bc4.png">

CC: @lovegushwa @valianttry

**Comment by beccaklam** [comment]
@gholme4 Also, issue 1 of this thread is happening again in Firefox and Safari in all languages except English on iOS. As in, if I load a fresh page in say, Polish the bug occurs. If I load it in English, it's fine.

CC: @lovegushwa @valianttry

**Comment by gholme4** [comment]
@beccaklam I decreased the height of the hero section to prevent this from happening.

**Comment by beccaklam** [comment]
@gholme4 Awesome, thank you!
