### ISSUE TITLE
Links in Maker Party strings seem wrong

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/Advocacy#552]
Not sure where is the Maker Party copy issue, so opening a new one ;)

I just noticed the new strings in Pontoon, and this seem wrong: https://pontoon.mozilla.org/fr/mozilla-advocacy/all-resources/?filter=untranslated&string=158727
a href="/maker=party/ -> should be /maker-party/ I presume

I think at this point we should update the string ID to make sure no locale will pick up the typo in their translation

CC: @ScottDowne

**Comment by ScottDowne** [comment]
Yup that's def a typo. I'm not at a computer atm so I cannot update it now.

**Comment by ScottDowne** [comment]
Fixed. Thanks for catching this. :rocket:
