### ISSUE TITLE
v2.5 Form QA: Mysterious 'Address Required' Validation

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Advocacy#553]
Detailed description of work: 
I've tested this on a Mac running OS X El Capitan using Firefox, Chrome and Safari as well as iOS 10 using the same three browsers and a mysterious 'address is required' validation occurs after the user presses sign. This goes away if I refresh the page but occurs when the page is first loaded:

![form_v2 5](https://cloud.githubusercontent.com/assets/20977376/19055458/058e16a2-8992-11e6-8379-5efd1bb58283.gif)

_Start date: Oct 3, 2016_ 
_Due date: Oct 4, 2016_ 

CC: @lovegushwa @gholme4 @jendc123

@lovegushwa Can you replicate the bug?

**Comment by brettgaylor** [comment]
Crud!

**Comment by gholme4** [comment]
@beccaklam @valianttry #readyforreview
