### ISSUE TITLE
v2.5 Petition Site QA: back arrow easy to accidentally hit 

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#554]
@gholme4 It's really easy to accidentally hit the back button when trying to check the check boxes. We could move the boxes a little more to the right? Or make a change to the back arrow target area on the check box pages.  

![check-box-back](https://cloud.githubusercontent.com/assets/12228435/19057742/e7ec3fd0-8986-11e6-910e-026a4ca8bd75.gif)

**Comment by gholme4** [comment]
@lovegushwa @valianttry #readyforreview
