### ISSUE TITLE
v2.5 Petition Site QA: check box difficult to click. 

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#555]
@gholme4 not sure whats going on here, but the check box can be unresponsive at times. If the giff I need to click it three times before it responds. 

![check-box](https://cloud.githubusercontent.com/assets/12228435/19057854/dbc2e302-8987-11e6-89f3-cce14bb493df.gif)

**Comment by gholme4** [comment]
@lovegushwa @valianttry #readyforreview
