### ISSUE TITLE
EU Copyright Campaign: v2.5 Petition Form not localized

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#556]
The copy on the petition form itself is not localized on the new v2.5 version of the form. This looks to be the case for all languages, replicated in both FF and Chrome. 

cc @valianttry @brettgaylor @lovegushwa

**Comment by lovegushwa** [comment]
^ @gholme4 @jendc123

**Comment by beccaklam** [comment]
@gholme4 @jendc123 @lovegushwa @valianttry @brettgaylor 
The localization is spotty, it comes in and out of places but seems to be consistent in its inconsistency. The specific spots not localized are:
- 'required field' and the 'information' hover
- 'first name, last name, e-mail, country, updates, privacy' in the progress bar
- 'Sign The Petition'
- 'Yes, I want to receive e-mail updates about Mozilla's campaigns'
- The thank you bar that loads after
  ![form_notlocalizing](https://cloud.githubusercontent.com/assets/20977376/19076160/b392f212-8a15-11e6-9d26-8be46770cb2b.gif)

Tested on OS X El Capitan, FF 49.0 Chrome Version 53.0.2785.116 (64-bit), Safari Version 10.0

**Comment by valianttry** [comment]
This is the result of an error in Bablic. @jendc123 has filed a ticket with Bablic support but due to timezones this may not get fixed until tomorrow PST.

**Comment by valianttry** [comment]
Looks like this is done @jendc123 -- looks like this is slowly updating -- we'll be QAing throughout today.

**Comment by brettgaylor** [comment]
getting there!  Just went through to see if there were any outliers. I found:

*_German *_ 
“required fields”
Email
Updates
Privacy

**Spanish**
First name
Last lame
emai
Country
Updates

**French**
Updates
privacy

**Polish**
Required fields
Email
Updates

**Italian**
Email
Updates
Privacy

**Dutch**
Email
Updates
Privacy

**Czech**
Updates

**Bulgarian**
Updates
Last names

CC @jendc123

**Comment by jendc123** [comment]
@brettgaylor - can you point me to the word "updates" in Pontoon?  I haven't had much success finding it as a single string.

**Comment by brettgaylor** [comment]
Looks like we missed it.  @valianttry will send to Kontextor to translate.

Are there other we're missing?

**Comment by jendc123** [comment]
@brettgaylor -  I'm not sure every country has a word for "privacy"?  There seems to be some missing i.e. Italian? Again not 100% sure since I sadly only speak English and very basic Spanish and a dash of high school French.

**Comment by valianttry** [comment]
EN: Updates
PL: Aktualizacje
ES: Actualizaciones
CS: Updaty
NL: Updates
BG: Aктуализации
IT: Aggiornamenti

FR: To be done
DE: To be done

**Comment by valianttry** [comment]
I found "Privacy" as a standalone word at this URL in Pontoon:

https://pontoon.mozilla.org/en-GB/mozilla-learning-network/all-resources/?search=privacy&string=154211

**Comment by brettgaylor** [comment]
Should we file a bug to get it in all of our locales?  Seems to be missing BG, IT, PL

**Comment by valianttry** [comment]
I added it to the queue of strings Kontextor is working on, but it may not be ready until early next week.

**Comment by jendc123** [comment]
@valianttry and @brettgaylor - I've translated the word "updates" #readyforreview.

**Comment by jendc123** [comment]
Hi @brettgaylor and @valianttry - I think this can be resolved.

**Comment by HPaulJohnson** [comment]
cleaning up my github issues in the new year and this one looks to be resolved. closing.
