### ISSUE TITLE
EU Copyright Campaign: Nyan cat not localized on v2.5 petition site

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#557]
Looks like when we launched the v 2.5 today, we went back the English versions of Nyan cat. First cat should have localized copy, 2nd cat should have no thought bubble. 

cc: @valianttry @brettgaylor @lovegushwa

**Comment by HPaulJohnson** [comment]
^ @gholme4 @jendc123

**Comment by jendc123** [comment]
@HPaulJohnson @valianttry - cats are localized. #readyforreview. Please be sure to clear cache.
