### ISSUE TITLE
v2.5 Form QA: Trying to drag to highlight drags entire form

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Advocacy#558]
Detailed description of work: When I try to drag my mouse over to highlight something I end up dragging the entire form. The only workaround is to double click to highlight. Is there a way we can fix this? 
![highlight drag](https://cloud.githubusercontent.com/assets/20977376/19076431/bf25d2a6-8a16-11e6-8644-d4f0a6851bf6.gif)

_Start date: Oct 4, 2016_ 
_Due date: Oct 5, 2016_ 
.
Tested on OS X El Capitan, FF 49.0 Chrome Version 53.0.2785.116 (64-bit), Safari Version 10.0 
CC: @lovegushwa

**Comment by gholme4** [comment]
@beccaklam Disabling swiping on non-touch devices is the only thing I could do.

**Comment by beccaklam** [comment]
@gholme4 Perfect!
