### ISSUE TITLE
v2.5 Form QA: Weird red line on edge of form (Safari)

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Advocacy#559]
Detailed description of work: There's a weird red line on the left edge of the form in Safari:
![screen shot 2016-10-04 at 9 38 09 am](https://cloud.githubusercontent.com/assets/20977376/19076483/f3956a88-8a16-11e6-996f-f09c38dd4d98.png)
Looks like a CSS fix.

_Start date: Oct 4, 2016_ 
_Due date: Oct 5 2016_ 

CC: @lovegushwa

**Comment by gholme4** [comment]
@beccaklam Which version of Safari and OS do you see this on?

**Comment by beccaklam** [comment]
@gholme4 Safari 10.0

**Comment by gholme4** [comment]
@beccaklam @valianttry #readyforreview
