### ISSUE TITLE
Add localized snippet text to pontoon

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#56]
Lets add the following text to pontoon:

"[Stand with us] as we fight to keep your Web life encrypted. And learn what encryption actually means while you’re at it."

The [stand with us] is a link to the localized versions of this:
https://advocacy.mozilla.org/en-US/encrypt/codemoji-b/2

**Comment by ScottDowne** [comment]
Do we want to translate some variants and maybe do some A/B testing?

**Comment by ScottDowne** [comment]
For now just the one string: https://pontoon.mozilla.org/sl/mozilla-advocacy/all-resources/?search=snippet&string=153243

Let me know if you want to add variants, I'm happy to.

**Comment by ScottDowne** [comment]
Also, the link you pasted in the initial comment was the redirect of an A/B test, and in en-US.

I'm guessing you meant "https://advocacy.mozilla.org/encrypt/codemoji/" (should redirect to /2)

We can change it to whatever though, even after it's translated.
