### ISSUE TITLE
v2.5 Form QA: Make Thank You Bar Smaller on Mobile

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Advocacy#560]
Detailed description of work: @gholme4 @jendc123
The form and thank you bar is obtrusively large on small screens at the moment. I think this is okay for the form as it could be incentive for the user to fill in the form to make it shrink so they can read better. Can we make the thank you bar smaller by removing the 25px of padding-bottom and make all the text 16px? ONLY for mobile though, so this would be a media query fix.
So turn this:
![screen shot 2016-10-04 at 9 58 23 am](https://cloud.githubusercontent.com/assets/20977376/19076981/cc1a9cec-8a18-11e6-9837-b21b415b6788.png)
to this:
![screen shot 2016-10-04 at 9 58 56 am](https://cloud.githubusercontent.com/assets/20977376/19076982/cf980b2a-8a18-11e6-9c7e-3796c9cdca50.png)

_Start date: Oct 4, 2016_ 
_Due date: Oct 5, 2016_ 

CC:  @lovegushwa

**Comment by gholme4** [comment]
@beccaklam @valianttry #readyforreview
