### ISSUE TITLE
v2.5 QA: Country not being recorded properly with submissions

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#561]
Since the launch of v2.5 petition, there is a spike in records that have (blank) as a country. In the table below you can see that almost all records on Oct 4th have (blank) as Country. 

<img width="403" alt="screen shot 2016-10-04 at 9 32 12 am" src="https://cloud.githubusercontent.com/assets/20688240/19083084/a5d2ebdc-8a15-11e6-8587-761d0d7342b9.png">

cc @valianttry @gholme4 @jendc123

**Comment by jendc123** [comment]
hi @vojtechmzl are you seeing this info from Analytics?

**Comment by vojtechsedlak** [comment]
I exported the data directly from Nation Builder.

**Comment by gholme4** [comment]
@vojtechmzl #readyforreview

**Comment by vojtechsedlak** [comment]
Things appear to be coming through now, though we will see in a couple of hours, if the (blank) value continues to appear. Marking this as QA Pass for now, but leaving the ticket open.
