### ISSUE TITLE
EU Copyright Campaign: Page load speeds have gotten worse in v2.5

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#562]
Looking at page load speeds in GA this a.m., we've gotten significantly worse over the last two days, correlating with launch of v 2.5 of petition. 

The desktop score is now 47/100 and our mobile score is now 39/100. For our top trafficked page our average page load time is 12.19 seconds!

Details: https://developers.google.com/speed/pagespeed/insights/?utm_source=analytics&tab=mobile&url=https%3A%2F%2Fchangecopyright.org%2F%3Flocale%3Dit%26sample_rate%3D0.1%26snippet_name%3D5764

cc: @vojtechmzl @valianttry @brettgaylor

**Comment by brettgaylor** [comment]
@jendc123 and @gholme4, did the optimizations that we completed get reverted here?

**Comment by gholme4** [comment]
@brettgaylor For a brief time it was necessary to unminify  a script. Now the page speed is back to what I saw before then.
