### ISSUE TITLE
Maker Party Event Pages: Social share localizations are messed up (again)

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#563]
Detailed description of work:
There are mixed localizations -- some locales have English titles and localized text for Facebook share; some have localized titles but English text, some are mixed English and translated text.

The correct translations are here:
https://docs.google.com/document/d/1YBoLZ5f7KL4yVgzPI9HMES-SX3yAZ7N9p4vSTYVAedo/edit

(no Polish)

_Start date: October 3, 2016_ 
_Due date: October 6, 2016_ 

![post_to_facebook_and_mozilla_maker_party__urheberrecht_reformieren_and_new_issue_ _mozillafoundation_advocacy_and_mattermost](https://cloud.githubusercontent.com/assets/9830371/19096358/a088b75c-8a50-11e6-83ea-ef83a192bd78.png)

**Comment by valianttry** [comment]
cc: @HPaulJohnson @jendc123 @gholme4

**Comment by jendc123** [comment]
@valianttry - I just requested access to the doc.

**Comment by valianttry** [comment]
@jendc123 I don't own it so pasting here:

Maker Party Social Share Copy

English
FACEBOOK
Join Maker Party. Make a difference. Maker Party is part of Mozilla’s effort to promote creativity, opportunity and innovation in the EU.  Learn more at https://mzl.la/makerparty

EMAIL
Subject: Mozilla Maker Party: Reform Copyright

Body: 
Join Maker Party. Make a difference. Maker Party is part of Mozilla’s effort to promote creativity, opportunity and innovation in the EU.  Learn more at https://mzl.la/makerparty

TWITTER
Join #makerparty. Make a difference. Join me to celebrate the Internet’s potential for innovation & creativity. mzl.la/makerparty

German
FACEBOOK
Gehen Sie zur Maker Party. Verändern Sie etwas. Maker Party ist Teil von Mozillas Anstrengungen, Kreativität, Chancen und Innovation in der EU zu fördern. Erfahren Sie mehr: https://mzl.la/makerparty

EMAIL: 
Subject: Mozilla Maker Party: Urheberrecht reformieren

Body: Gehen Sie zur Maker Party. Verändern Sie etwas. Maker Party ist Teil von Mozillas Anstrengungen, Kreativität, Chancen und Innovation in der EU zu fördern. Erfahren Sie mehr: https://mzl.la/makerparty

TWITTER: 
Gehen Sie zur #MakerParty. Verändern Sie etwas. Feiern Sie mit mir das Potenzial des Internets für Innovation und Kreativität.

French
FACEBOOK:
Rejoignez la Maker Party. Faites changer les choses.  Les Maker Party font partie des efforts de Mozilla pour promouvoir la créativité, les possibilités et l’innovation dans l’Union européenne. Apprenez-en davantage: https://mzl.la/makerparty

EMAIL: 
Subject: Mozilla Maker Party: Réformons le droit d’auteur

Body: Rejoignez la Maker Party. Faites changer les choses.  Les Maker Party font partie des efforts de Mozilla pour promouvoir la créativité, les possibilités et l’innovation dans l’Union européenne. Apprenez-en davantage: https://mzl.la/makerparty

TWITTER: 
Rejoignez #MakerParty. Faites changer les choses. Rejoignez-moi et fêtons ensemble le potentiel innovateur et créatif d’Internet.

Spanish
FACEBOOK:
Únete a Maker Party. Ten un papel decisivo. Maker Party es parte del esfuerzo de Mozilla por promover la creatividad, la oportunidad y la innovación en la Unión Europea. Descubre más: https://mzl.la/makerparty

EMAIL: 
Subject: Mozilla Maker Party: Defiende una reforma del copyright

Body: Únete a Maker Party. Ten un papel decisivo. Maker Party es parte del esfuerzo de Mozilla por promover la creatividad, la oportunidad y la innovación en la Unión Europea. Descubre más: https://mzl.la/makerparty

TWITTER: 
Únete #MakerParty. Ten un papel decisivo. Ven y celebra conmigo el potencial innovador y creativo de Internet.

Italian
FACEBOOK: 
Partecipa a Maker Party. Fai la differenza. Maker Party è una delle piattaforme ideate da Mozilla per promuovere creatività, opportunità e innovazione in Europa. Ulteriori informazioni: https://mzl.la/makerparty

EMAIL
Subject: Mozilla Maker Party: Riformiamo la legge sul copyright

Body:  Partecipa a Maker Party. Fai la differenza. Maker Party è una delle piattaforme ideate da Mozilla per promuovere creatività, opportunità e innovazione in Europa. Ulteriori informazioni: https://mzl.la/makerparty

TWITTER:
Partecipa #MakerParty. Partecipa anche tu e celebra assieme a me il potenziale di Internet per l’innovazione e la creatività.

Dutch
FACEBOOK: 
Doe mee met Maker Party. Maak een verschil. Maker Party is onderdeel van de inspanning van Mozilla om creativiteit, mogelijkheden en innovatie in de EU te bevorderen. Meer info: https://mzl.la/makerparty

EMAIL
Subject:  Mozilla Maker Party: Hervorm auteursrecht

Body: Doe mee met Maker Party. Maak een verschil. Maker Party is onderdeel van de inspanning van Mozilla om creativiteit, mogelijkheden en innovatie in de EU te bevorderen. Meer info: https://mzl.la/makerparty

TWITTER: 
Doe mee met #MakerParty. Maak een verschil. Doe met me mee en vier de potentie voor innovatie en creativiteit van het internet.

Czech
FACEBOOK:
Připojte se k Maker Party. Učiňte změnu. Maker Party je součástí snahy Mozilly podpořit kreativitu, příležitost a inovaci v EU. Zjistěte více: https://mzl.la/makerparty

EMAIL: 
Subject: Mozilla Maker Party: Reformujte autorské zákony

Body: Připojte se k Maker Party. Učiňte změnu. Maker Party je součástí snahy Mozilly podpořit kreativitu, příležitost a inovaci v EU. Zjistěte více: https://mzl.la/makerparty

TWITTER:
Připojte se k #MakerParty. Učiňte změnu. Přidejte se k mojí oslavě možností internetu v oblasti inovací a kreativity.

Bulgarian
FACEBOOK:
Присъединете се към Maker Party. Дайте своя принос. Присъединете се към мен в чест на потенциала на интернет за иновации и творчество. https://mzl.la/makerparty

EMAIL: 
Subject: Mozilla Maker Party: Реформиране на авторското право

Body: Присъединете се към Maker Party. Дайте своя принос. https://mzl.la/makerparty

TWITTER: 
Присъединете се към #MakerParty. Дайте своя принос. Присъединете се към мен в чест на потенциала на интернет за иновации и творчество.

**Comment by jendc123** [comment]
@valianttry @HPaulJohnson - this is #readyforreview.

**Comment by HPaulJohnson** [comment]
These are all localized. Looks good. 

One additional thing is that somewhere along the line of actually translating the copy, the mzl.la/makerparty link got dropped from the localized tweets. It's a p2 but if we could add it back to the twitter shares at the end of the copy/string that would be super helpful. Not a blocker.

**Comment by lovegushwa** [comment]
@jendc123 ^

**Comment by jendc123** [comment]
@HPaulJohnson and @lovegushwa - I'm seeing the url in all tweets? 
<img width="942" alt="capture" src="https://cloud.githubusercontent.com/assets/6034476/19164286/5647baca-8bcd-11e6-89d9-92259dfeb4d1.PNG">

**Comment by lovegushwa** [comment]
@jendc123 thank you, we can close this.

**Comment by HPaulJohnson** [comment]
@lovegushwa @jendc123 I think you were QA'ing wrong site. This is an issue on makerparty.community. The screenshot above is from changecopyright.org.

Reopening.

**Comment by jendc123** [comment]
sorry about that @HPaulJohnson and @lovegushwa. I'll make the update shortly.

**Comment by jendc123** [comment]
@HPaulJohnson @lovegushwa this is #readyforreview.

**Comment by HPaulJohnson** [comment]
Looks good, @jendc123. Thank you. Closing.
