### ISSUE TITLE
Maker Party: Submit event participant survey for L10N

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#565]
Detailed description of work:
We need to put the survey EN text into localization queue asap. 

Original EN text is here:
https://docs.google.com/document/d/1VM4Rt9X6y8TG1qgXAr6G6CQdyiI0fvBwyho40Csf244/edit#heading=h.drmkm5rhp9kd 

_Start date: October 4, 2016_ 
_Due date: October 11, 2016_ 

CC: @ldecoursy

**Comment by valianttry** [comment]
The survey was set up in SurveyGizmo here:
http://www.surveygizmo.com/s3/3095377/e30b0c675d33

This can provide context for localization.

**Comment by TheoChevalier** [comment]
Deadline for translations is October 31.
Required locales are: bg, cs, de, es, fr, it, nl, pl

I’ll start extracting the strings and expose them on Pontoon

**Comment by TheoChevalier** [comment]
We actually need the data extracted from SurveyGizmo (with the exact key names used internally) before we can expose the strings.

**Comment by zhelding** [comment]
Dropping translation export here for convenience.

[Attendee Survey Translation Export.xlsx](https://github.com/MozillaFoundation/Advocacy/files/524978/Attendee.Survey.Translation.Export.xlsx)

**Comment by TheoChevalier** [comment]
Thanks, that’s exactly what I needed. I extracted the strings and their key, but I first need to fix a bug in our extraction script (nothing related to this request, just a technical issue)

**Comment by TheoChevalier** [comment]
Translation has started, progress can be tracked here: 
https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=surveys/survey_maker_party_2016.lang

Announcement to localizers: https://groups.google.com/d/msg/mozilla.dev.l10n.web/Qpp9NXd4BZs/_nCPEPhxEQAJ

**Comment by TheoChevalier** [comment]
@zhelding Hey Zoe, one of our localizer is asking a question that I think you can answer:
“I see some open questions there, who will read the answers in all those languages? Are they going to be machine translated or is it meant as a feedback for the hosts? ”

**Comment by TheoChevalier** [comment]
@zhelding  Also, how is the survey going to be sent to attendees? Through the website? Email? Sent by hosts?
Some localizers would like to translate the survey even if they did not localize the website, because they are hosting Maker Parties, do you think it would make sense to add more locales like that (Slovenian, in this case)?

**Comment by zhelding** [comment]
@TheoChevalier My understanding is that hosts will not have access to the survey responses, so I presume they will have to be machine translated. Also, we intended for a link to the survey to be distributed by hosts at the end of Maker Parties as well as available on the event page afterwards, so I agree that it makes sense to add more / whatever locales might be relevant.

**Comment by TheoChevalier** [comment]
@zhelding thanks! I’ve added sl. Could you try pushing the French translations (attached here) to SurvezGuizmo please? Just to make sure everything is imported as expected

[fr.xls.zip](https://github.com/MozillaFoundation/Advocacy/files/534229/fr.xls.zip)

**Comment by zhelding** [comment]
@TheoChevalier, sorry I wasn't keeping an eye on this. Did you manage to check if the import worked correctly?

**Comment by TheoChevalier** [comment]
@zhelding Sorry if I think my instructions were confusing, let me try to clarify :) 
I need you to upload the French translations back into SurveyGizmo, to make sure the survey is fully translated (then you would need to do the same for other locales on October 30) 

You should use the “Import translated fields” option in this screen https://dyzz9obi78pm5.cloudfront.net/app/image/id/556f5e2d7cb829f312626090/n/2015-06-03_1405.png
Then upload the fr.xls file that you can download from here: https://github.com/mozilla-l10n/engagement-l10n/blob/master/surveygizmo/maker_party_2016/fr.xls

Let me know if you have any issue!

**Comment by zhelding** [comment]
All good! Everything working as expected.

**Comment by TheoChevalier** [comment]
@zhelding you can import all the locales available here. We’re only missing Slovenian (opt in) and Polish https://github.com/mozilla-l10n/engagement-l10n/tree/master/surveygizmo/maker_party_2016

**Comment by zhelding** [comment]
@TheoChevalier, all imported. Thanks!
