### ISSUE TITLE
Localize last few activities strings

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#566]
A few strings for the activities are still being localized.

From #498

Strings are:
- "Make Some Memes!"
- "CC-BY-SA by Mozilla
- "{num} of {total}"
- "Overview"
- "Combined Maker Party Activities"
- "2-3 hours"
- "Maker Party | {title}"

**Comment by brettgaylor** [comment]
Hey @valianttry if these come in while you are dreaming the force let us know!

**Comment by valianttry** [comment]
@ScottDowne these are completed. They're in the tab "Resources MISSING" in this spreadsheet:
https://docs.google.com/spreadsheets/d/1dBARa2Pr9NB_Q5ZdPOV1Jx9NOLbATSPk3etSfCWHTkk/edit#gid=797834410 

Can you close this when you update them @ScottDowne ?

**Comment by ScottDowne** [comment]
Done.
