### ISSUE TITLE
v2.5 Form QA: Weird Polish Sign Button only on Mobile

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Advocacy#568]
@gholme4 @jendc123 Detailed description of work: Polish 'sign' button has what seems to be repeating text at the bottom of the button. This happens on iOS across Chrome, Safari and Firefox.
![img_6494](https://cloud.githubusercontent.com/assets/20977376/19127398/c3b2c0c6-8b0c-11e6-9180-a4a7f122dc2d.PNG)

_Start date: Oct 5, 2016_ 
_Due date: Oct 6, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @lovegushwa @valianttry

**Comment by gholme4** [comment]
@beccaklam I made the font size smaller so the button text would not wrap.

**Comment by beccaklam** [comment]
@gholme4 thanks!
