### ISSUE TITLE
v2.5 Form QA: Information Icon not working on Mobile

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Advocacy#569]
@gholme4 @jendc123 

I found another issue when I was reviewing though: When I tap the 'i' icon:
<img width="24" alt="screen shot 2016-10-05 at 2 53 28 pm" src="https://cloud.githubusercontent.com/assets/20977376/19126976/17bae57e-8b0b-11e6-9abd-8ff8b3b17f42.png"> on my phone, the yellow box doesn't show up. I'm wondering if it's because currently the box appears on hover but one can't hover on phones. Would we be able to enable users to tap the icon and the yellow box would show? This is the box I'm talking about:
<img width="309" alt="screen shot 2016-10-05 at 2 54 44 pm" src="https://cloud.githubusercontent.com/assets/20977376/19127010/410aca52-8b0b-11e6-9271-7520f0cc1bc4.png">

CC: @lovegushwa @valianttry 

_Start date: Oct 5, 2016_ 
_Due date: Oct 6, 2016_

**Comment by gholme4** [comment]
@beccaklam @valianttry #readyforreview
