### ISSUE TITLE
v2.5 Form QA: Adding 'close' icon to Privacy Information Pop-Up on Mobile/Pop-Up Form not localizing

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Advocacy#570]
Detailed description of work: @gholme4 @jendc123 Can we add a 'close' icon to the information pop-up like this?
![privacy notice](https://cloud.githubusercontent.com/assets/20977376/19155892/12385afc-8bae-11e6-887b-9b50deec0db4.png)
Right now it's not clear that you need to tap the form again on mobile to close it. Here is an icon if you need it: https://drive.google.com/file/d/0BzuBOR2VJQqUUGRLOUIxSm0tZXM/view?usp=sharing

Also, the pop-up is not localizing on iOS and OS X across FF, Safari and Chrome. But is that a Bablic issue? @valianttry 
![screen shot 2016-10-06 at 10 28 29 am](https://cloud.githubusercontent.com/assets/20977376/19156248/3a1d3514-8baf-11e6-936c-b958b077cc09.png)

_Start date: Oct 6, 2016_ 
_Due date: Oct 7, 2016_ 

CC: @lovegushwa @valianttry

**Comment by gholme4** [comment]
@beccaklam I added the close icon.

**Comment by beccaklam** [comment]
Thank you @gholme4 Just waiting on @valianttry to see what the issue is with the pop-up not localizing before closing the ticket.

CC: @lovegushwa
