### ISSUE TITLE
v2.5 petition: Add counter/progress bar to the petition

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#571]
Detailed description of work: We ran a test that indicated that adding a petition counter to the page increases conversions. You can find full details here: #447. You can see the design treatment of the counter below. We tested a fixed image, but the progress bar would ideally be dynamic and update with the latest numbers from NB. 

![3732b014-818b-11e6-8fa6-30f69a729884](https://cloud.githubusercontent.com/assets/20688240/19158538/f8e3cb00-8b9d-11e6-9fd6-6b2f96caaaae.jpg)

_Start date: October 6, 2016_ 
_Due date: October 8, 2016_ 

CC: @lovegushwa @valianttry @jendc123 @gholme4

**Comment by jendc123** [comment]
Hi @brettgaylor - we updated the template test template with the thermometer [https://www.changecopyright.org/copyright_with_thermometer].  It looks like we still need to reduce it's length, center the word "required" and then the dots are red.  What should it look like on desktop? 
![compare](https://cloud.githubusercontent.com/assets/6034476/19568407/6877af82-96bf-11e6-9176-59f664e12c5c.jpg)

**Comment by beccaklam** [comment]
@jendc123  @brettgaylor  Desktop version:
![screen shot 2016-10-20 at 2 39 00 pm](https://cloud.githubusercontent.com/assets/20977376/19573055/9fb200b6-96d2-11e6-9260-010f7676e682.png)

**Comment by jendc123** [comment]
Hi @brettgaylor, @vojtechmzl , @beccaklam - we updated the Spanish template and the thermometer 
[https://petitionv25spanish-mozillafoundation.nationbuilder.com/]

**Comment by lovegushwa** [comment]
@jendc123 looks good.

**Comment by brettgaylor** [comment]
Looks good to deploy!

**Comment by jendc123** [comment]
Hi @brettgaylor - the thermometer is now live on the site [https://www.changecopyright.org/]

**Comment by brettgaylor** [comment]
:+1:
