### ISSUE TITLE
Warsaw, Poland event not showing on the map

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#572]
Detailed description of work:

A new event isn't showing up as a pin on the world map on the maker party site.

![mozilla_maker_party__reform_copyright](https://cloud.githubusercontent.com/assets/9830371/19159334/e44c9624-8ba0-11e6-9f94-39211e0d5212.png)

_Start date: October 6, 2016_ 
_Due date: October 6, 2016_ 

CC: @gholme4 @jendc123

**Comment by valianttry** [comment]
@ldecoursy try adding a full address (right now there's no street)

**Comment by ldecoursy** [comment]
Street address has been added however still not seeing the pin on the map in Poland.

**Comment by valianttry** [comment]
@gholme4 any ideas?

**Comment by jendc123** [comment]
Hi @valianttry and @ldecoursy when I  add in the address I copied from the Poland Foundation website 

Fundacja Nowoczesna Polska
ul. Marszałkowska 84/92 lok. 125
00-514 Warszawa

We are able to get an exact match in Nationbuilder.  Can you confirm this is the correct address? 
<img width="736" alt="poland" src="https://cloud.githubusercontent.com/assets/6034476/19311073/d5f5c8ca-905a-11e6-8bd0-8a772b86b029.PNG">

**Comment by ldecoursy** [comment]
Hi @jendc123 That's the address for the organization that is hosting the event, but that's not where the event will be. It's at Kinoteka Multiplex: Palace of Culture and Science, plac Defilad 1, 00-901 Warszawa I can't seem to find another address for it though...

**Comment by jendc123** [comment]
@ldecoursy - I believe the issue is having "Kinoteka Multiplex:" before Palace of Culture and Science. 
<img width="736" alt="poland 2" src="https://cloud.githubusercontent.com/assets/6034476/19312220/7a58fe06-905f-11e6-9cba-545f62e8b63b.PNG">

**Comment by ldecoursy** [comment]
OK I think that should work. Thanks for your help!
