### ISSUE TITLE
[MozFest] Hi-res/Vector files of PostCrimes Images

### ISSUE THREAD

**Issue by Melechuga** [MozillaFoundation/Advocacy#573]
**Detailed description of work:**
One activity proposed for Maker Party @ MozFest is to have participants take photos of themselves with IRL cutouts of the images from PostCrimes. I will ask professional printers to make life-size cardboard cutouts of the images. Can you please share hi-res or vector files of the PostCrimes images?
- [Eiffel Tower](http://core0.staticworld.net/images/article/2016/09/eiffel-tower-100684717-primary.idge.jpg)
-  [EU Parliament](https://cnet3.cbsistatic.com/img/o-a_ag7OyO7iANg5vdshhXx9mfk=/620x0/2016/09/27/4737f09a-81a6-4276-b6b1-1c9772b0430c/eu-parliment.jpg)
-  and the Little Mermaid one

Also, if someone can help with scaling this so we know how big these images should be so they're close to life-size (more importantly, so that the average adult can fit their face in the cutout hole), that would be very helpful!

This needs to be done in time to give the printers in London time; the sooner the better, but hopefully Oct. 14 at the latest. 
_Start date: October 6, 2016_ 
_Due date: October 14, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @lovegushwa

**Comment by brettgaylor** [comment]
I've asked these from the agency that built the site

**Comment by lovegushwa** [comment]
@beccaklam once the illustrations come in from Young Astronauts, We're looking to have something like this made, @Melechuga is arranging a printer and I can help you figure out how to set up the files for print.

![1](https://cloud.githubusercontent.com/assets/12228435/19245030/ed1acff6-8ed3-11e6-87cf-ddee2ccb25c1.png)

**Comment by beccaklam** [comment]
Hi @Melechuga here are the high res files we discussed. They are made to be four feet tall.
https://drive.google.com/drive/folders/0BzuBOR2VJQqUeFQ4aEpVUU5YWEk?usp=sharing Let me know if you need a different file format. Also, you might need to let the printers know the die cut is on its own layer.

CC: @lovegushwa
