### ISSUE TITLE
Create metrics dashboard for fundraising

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#575]
Detailed description of work:
The team will need a metrics dashboard for tracking key performance KPIs during the campaign. This can be similar to the Copyright Campaign dashboard: 
https://datastudio.google.com/#/org/Ra9O2QIYT8We-1pOmnS_6w/reporting/0B5UMbl9u1_wQRnZOU0pYc1FPSWs/page/b9e 

Is it possible for this dashboard's charts to be embedded in blog posts, or shared publicly outside of Google Suite?

_Start date: October 5, 2016_ 
_Due date: October 19, 2016_

**Comment by valianttry** [comment]
Here's a starter list of KPIs for the campaign:
- Raise a total of $4 million USD total by December 31, 2016
- Increase conversion rates in priority locales
- Increase the overall proportion of donations from outside the United States
- Increase email list optin rate
- Improve welcome email experience
- Increase giving by email by leveraging dynamic content and donor history data

Improve donor nurturing and care by: 
- localize the FAQ
- Reduce response times for Desk.com cases
- Build a “case to give” web site that tells the story of donor impact
- Create a special “thank you” experience

**Comment by vojtechsedlak** [comment]
I have been already working on a basic MoFo fundraising dashboard [here](https://datastudio.google.com/#/org/Ra9O2QIYT8We-1pOmnS_6w/reporting/0B5UMbl9u1_wQNF9TWUFPWm1EWUU/page/Aao). I will expand it to include the metrics and objectives you highlighted above. 

As for embedding the charts elsewhere, we can always insert them as images, which is easy. If we want them to be interactive, we can recreate them within the blog environment. Depending on the complexity of the chart that can take an hour to couple of hours.

**Comment by valianttry** [comment]
@vojtechmzl it would be handy if we can break out the % of revenue coming in through various payment methods. Check out Wikimedia's breakout in their testing of paypal, cc, and amazon: https://meta.wikimedia.org/wiki/Fundraising_2013. I think one chart would do it. It would be interesting if we can see which specific CC people used as well (AMEX vs. Mastercard; etc)

**Comment by valianttry** [comment]
I don't see any real use for the "transaction ID" feed (e.g. every transaction with an amount at the bottom of page 1). Do you have a compelling reason to include it or can we remove?

**Comment by valianttry** [comment]
PayPal % is usually over 60% (I think?) so this seems low. Maybe the demographics are different given US only makes up 31%? So maybe non US donors don't use PP as much?

![mofo_fundraising_dashboard](https://cloud.githubusercontent.com/assets/9830371/20154130/d5fafe4a-a67a-11e6-9fa8-54bab4aa5686.png)

**Comment by valianttry** [comment]
Can we see revenue year-over year by channel and add a goal line for this year's target? For instance, last year we raised $180,000 on mozilla.org, this year we'd like to hit $200,000. I have data from past years by channel. I'd include email (mofo), email (moco), mozilla.org, snippet, search, referral, social, other.

**Comment by valianttry** [comment]
It would be great to breakout our target locales, not just country. We should watch both revenue AND conversion, and be able to see improvements / changes over last year.That way we can track progress on those key locales where we're working to improve the donor experience. 

![mofo_fundraising_dashboard](https://cloud.githubusercontent.com/assets/9830371/20154445/28e5277e-a67c-11e6-8b29-c7db3992906a.png)

**Comment by valianttry** [comment]
We should add a subscriber funnel optimization page like you did with Copyright. We really want to improve how many people opt in to our list if we can.
