### ISSUE TITLE
Social share insn't working on Maker Party events site

### ISSUE THREAD

**Issue by geroter** [MozillaFoundation/Advocacy#577]
https://www.makerparty.community/mtuohy45/be_a_cczero_hero

Nothing happens when I click the social share button with only Twitter selected after I confirm my attendance.

@valianttry and @shaghdoosti

**Comment by valianttry** [comment]
This worked fine for me in Chrome:

![andrea_wood___valiant____twitter](https://cloud.githubusercontent.com/assets/9830371/19247838/d12b81ce-8ee1-11e6-811c-11903dc635f1.png)

**Comment by shaghdoosti** [comment]
I tried this too in Chrome when I got to here I pressed post. First time it went to an error page, second time it didn't do anything: 

<img width="1091" alt="screen shot 2016-10-10 at 12 09 57 pm" src="https://cloud.githubusercontent.com/assets/13626384/19248046/a5025d7e-8ee2-11e6-9060-7ce8808b34f3.png">

**Comment by valianttry** [comment]
It's possible this is related to:
https://github.com/MozillaFoundation/Advocacy/issues/460#issuecomment-250578401

And only impacts control panel users. @gholme4 can you help confirm?

**Comment by gholme4** [comment]
@valianttry I don't believe these errors are related because the same thing doesn't happen to all users with control panel access. We have little or no control over what happens after a user clicks that "Post" button. I have sent NB support an email about these problems.

**Comment by valianttry** [comment]
@shaghdoosti and @geroter can you please report what browser / OS you were using? (Please include these details anytime you report a bug, thanks!)

NB support answer:

> From: help@nationbuilder.com
> Subject: Re: Prompt to share error
> Date: October 11, 2016 at 9:40:35 AM CDT
> To: george@fissionstrategy.com, help@nationbuilder.com
> Cc: jennifer@fissionstrategy.com
> 
> Hi George,
> 
> I tested and was unable to replicate the error. As you can see here I was able to share on both Facebook and twitter:
> 
> https://mozillafoundation.nationbuilder.com/admin/sites/3/pages/151/activities
> 
> Do you know what browsers they were using?
> 
> Thanks,
> 
> Kev
> 
> Kev O'Connor
> NationBuilder Support
> help@nationbuilder.com
>

**Comment by geroter** [comment]
Windows 10
Firefox Developer Edition 32bit - 51.0a2
