### ISSUE TITLE
Map is disappearing --- eeek

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#580]
Detailed description of work:
In Chrome Incognito tab i open Maker Party, changed the language from EN > IT, and the map showed up but then disappeared. It looks like this:

![cursor_and_mozilla_maker_party__riformiamo_la_legge_sul_copyright](https://cloud.githubusercontent.com/assets/9830371/19290880/a0d4fb8c-8fc6-11e6-83f1-a9c1a77a58a3.png)

_Start date: October 11, 2016_ 
_Due date: October 12, 2016_ 

CC: @gholme4 @jendc123

**Comment by valianttry** [comment]
related to #128 ?

**Comment by jendc123** [comment]
@valianttry and @gholme4 - I've sent a note to help to ask about API calls.

**Comment by valianttry** [comment]
I also escalated this with Dana, it's serious since we are going to start to send more traffic today.

**Comment by valianttry** [comment]
This appears to be fixed. Closing.
