### ISSUE TITLE
[MozFest] Space Design

### ISSUE THREAD

**Issue by Melechuga** [MozillaFoundation/Advocacy#582]
Detailed description of work:
MozFest is happening in 16 days! All of the sessions are chosen, and we know we'll be in the 4th floor library. I need help with designing the actual space, though I have some ideas. This space represents our Policy and Advocacy work both around copyright and mobilization. Whoever takes this on has plenty of creative license, but know that there's a time crunch. We will have:
- 3 workshop spaces
- The Lounge
- The Art Space (hopefully gritty, graffiti-like).

Resources:
- [Blueprint of Library](https://drive.google.com/a/mozilla.com/file/d/0B_B9-Ny1xBaRRFpuZ0FQX0VoZ2s/view?usp=sharing)
- [Image of back area of library](https://drive.google.com/a/mozilla.com/file/d/0B_B9-Ny1xBaRT0t3YTByd1E5dlZpRDVQdGlISG5haUYwU0g4/view?usp=sharing)

_Start date: Asap_ 
_Due date: October 28, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @lovegushwa

**Comment by Melechuga** [comment]
Ideas:
- Grafitti background
- "Keep the Internet Weird" banner
- Signs for Sessions
- [Tree for women's event](https://upload.wikimedia.org/wikipedia/commons/6/64/Meuble_h%C3%A9raldique_aulne.svg)
- Quilt
- Creative Commonspace

**Comment by beccaklam** [comment]
Hey Melissa, here is the link to where you can find our PDFs of our Keep The Internet Weird banners: https://drive.google.com/drive/folders/0BzuBOR2VJQqUdHdpa1RHWUpWT2c?usp=sharing
CC: @lovegushwa @natalieworth
