### ISSUE TITLE
Maker Party: Phone Number appears to be required

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#583]
Detailed description of work: Event creation form, phone number field has an \* next to it. You don't have to actually fill in the field to progress, but it LOOKS like it is requred.

_Start date: October 10, 2016_ 
_Due date: October 11
![phone-number-not-required](https://cloud.githubusercontent.com/assets/11812272/19330767/34b6ee2c-9095-11e6-9a45-58ff411747ba.jpg)
, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by gholme4** [comment]
@stephaniemcv @valianttry Hi. I removed the \* because the template does not require the phone number.

**Comment by stephaniemcv** [comment]
Closing because phone number is not required.
