### ISSUE TITLE
Maker Party: Venue Zip has * to be required, but not actually required

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#584]
Detailed description of work: I was able to make an event with no venue Postal code

![venue-zip-required-but-not-enforced](https://cloud.githubusercontent.com/assets/11812272/19330868/d9844a1c-9095-11e6-9309-efd9fd5641b0.png)

![zip-not-required](https://cloud.githubusercontent.com/assets/11812272/19330875/e3615232-9095-11e6-9a3c-4cdd19344475.jpg)

_Start date: October 12, 2016_ 
*Due date: October 12

, 2016\* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by gholme4** [comment]
@stephaniemcv @valianttry Hi. I removed the \* because the template does not require the postal code.

**Comment by stephaniemcv** [comment]
@gholme4 I'm confused. I thought zip was a required field to power the google map so people can find Maker Parties near them?

**Comment by gholme4** [comment]
@stephaniemcv Yes, but the postal code isn't required to submit an event. That's NationBuilder's logic.
