### ISSUE TITLE
Review and update the donor FAQ and Ways to Give content

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#586]
Detailed description of work:

**Refresh the text of the current FAQ to reflect:**
- any changes in systems, processes, or offerings that we need donors to know. We will need Alexei, Pamela, and Angela to help with this review.
- New questions or requests from the past year that appear frequently enough in Desk.com cases to add here

**Localize the updated FAQ into priority locales, this means we need to:**

_NOTE any text that might only apply to a particular locale_
- Remove any US-centric language or references that we can

**Decide on a new locations for the FAQ.** 

We may need to move it to a web page because localizing a wiki page is apparently exponentially difficult. @TheoChevalier and @ScottDowne will scope what this will take.
- Update links on all the donation forms to point to the corresponding locale’s FAQ.

Related: 
#394 #396

**Here is the Google Doc where we're making edits:**
https://docs.google.com/document/d/16ofBfNadmTOd_MwKmvpY7VcsQuBVU_l-dhAwsfhWRNw/edit

_Start date: October 13, 2016_ 
_Due date: October 31, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @stephaniemcv

**Comment by stephaniemcv** [comment]
Just rabbit holed in Desk.com and this might be a great place for the FAQ and all sorts of things to live. We can set up a [Support Center](https://support.desk.com/customer/portal/articles/8393-understanding-your-support-center) with [Multilingual Support](https://support.desk.com/customer/portal/articles/566428-getting-started-multilingual-support) (built in?!)
- [Here's a sample ofwhat other orgs have done](https://www.desk.com/blog/12-awesomely-designed-support-centers-and-what-makes-them-rock)

@TheoChevalier @ScottDowne either of you interested in diving deeper on this?

**Comment by TheoChevalier** [comment]
From what I can see in this doc, this would be a huge step forward compared to the setup detailed here https://github.com/MozillaFoundation/Advocacy/issues/394#issuecomment-254311191 But maybe I’m failing to see what would be the advantages of having the FAQ in Desk.com, would love to understand them if I missed that.

Here are some of the pros of creating a static webpage:
- Existing translations can be updated without our intervention (localizers can do QA)
- Copy updates and new translations will be pushed automatically, without any copy/pasting (Desk.com solution seem to require a manual copy/pasting)
- Scalability: we can translate the FAQ in any of the ~90 locales we support at Mozilla (vs. 53)
- We won’t have issues with locale codes mismatch (locale codes used in Desk.com might differ from ours)

Not having an automated end-to-end process (e.g copy/pasting) would slow us down and would make future updates a lot harder to manage.

So, taking that into consideration, I would recommend we explore this solution only if having the FAQ on Desk.com provides a decisive advantage compared to having a static webpage.

**Comment by ScottDowne** [comment]
I think I agree with @TheoChevalier that the actual content should be in a static page enabled in Pontoon. However, maybe we could setup something in desk.com that links out to or somehow displays the localized faq page, or something along those lines?

**Comment by TheoChevalier** [comment]
> From what I can see in this doc, this would be a huge step forward compared to the setup detailed here

Gha, I meant “this would be a huge step **backwards**”

**Comment by stephaniemcv** [comment]
@ScottDowne I'll poke around to see if there's anything like that. And if I find anything, we'll just tag it as a "nice to have" and focus on a static webpage.

Thank you both for taking a look at it!

**Comment by ScottDowne** [comment]
Just a little inspiration for what this could look like really easily: https://advocacy.mozilla.org/en-US/open-web-fellows/info

**Comment by valianttry** [comment]
@TheoChevalier it might be helfpul for you to get a tour of Desk.com and how we use it. I think it will help us make a better decision here. Desk.com helps us triage incoming support emails, which are tracked at the user-level in a database which offers a number of advantages. For instance, storing FAQ answers on a static webpage would require @stephaniemcv and her team to copy/paste answers to questions from the web-based FAQ into templates in Desk.com in order to respond to incoming Qs by email. Some of that work could be automated (possibly?). I'm not advocating for one solution over another -- just want to make sure we are looking at all the functionality we need and use before making a 💯 decision.

**Comment by valianttry** [comment]
Just chatted with @ScottDowne and I proposed that we reveal a custom FAQ for a few high priority locales. For instance, the most common request from German donors is for bank transfer (we cannot offer bank transfer at this time). If the browser locale = DE, we should show an FAQ that has the most common Qs for that locale. We probably only need to do this for DE and French (two prominent locales with FAQs unique from EN donors).

**Comment by ScottDowne** [comment]
@valianttry We can make the FAQ linkable, and have it so we can link to specific questions, and then have them expanded. Would this somehow make copy and pasting into desk.com easier? Example, paste them a link like https://donate.mozilla.org/de/faq/#reissue-receipt

Can also link to the FAQ in desk.com in general, if possible, to try to funnel people to the FAQ first?

@TheoChevalier With the possibility of DE and FR only content, do you have any ideas on how to leverage pontoon well for this, so a string only needed for DE isn't translated into ~49 languages. Like a separate repo or pontoon page maybe? Can a specific page in pontoon have the languages it's supported in be limited separately from the whole repo?

**Comment by TheoChevalier** [comment]
@ScottDowne it could work with multilingual files like .lang or .po, but not with monolingual files like .properties, because Pontoon will compare locale files against en-US file and drop everything that’s not in there. Using .PO, we should be able to edit .PO files for a few locales and manually add strings.

Otherwise we would have to move each custom locale to a dedicated project on Pontoon, with a dedicated repo each time, so I don’t think we want to do that.

**Comment by ScottDowne** [comment]
@TheoChevalier interesting! So, is .po something we can integrate with just a single page, or do we need to move the whole repo to .po files? In the meantime, I'll take a look at .po files.

**Comment by TheoChevalier** [comment]
@ScottDowne We need to check with @mathjazz I think we never done that before. And actually talked with flod, he’s not even sure we can do that with .PO. @mathjazz, do you know if we can add strings on a .PO file only for a few locales and if we can have both .properties and .po in the same repo?

**Comment by mathjazz** [comment]
We can have a mix of different file formats in the same repository. What you're asking for is something like this:
https://mozilla-pontoon-staging.herokuapp.com/projects/test/

So `for-de-only.lang` is only exposed to German and `for-sl-only.lang` is only exposed to Slovenian:
https://mozilla-pontoon-staging.herokuapp.com/de/test/
https://mozilla-pontoon-staging.herokuapp.com/sl/test/

Here's the corresponding repository:
https://github.com/mathjazz/pontoon-test

As @TheoChevalier pointed out, strings that are only exposed for a subset of locales need to be stored in a bilingual file format (.po, .lang and .xliff).

And a slight correction: the bilingual files with the same name need contain the same set of strings. So we actually expose different files to different locales, not different strings within the same file.

**Comment by stephaniemcv** [comment]
@KevZawacki 
The FAQ has been extensively commented on and I'm officially handing over to you.
https://docs.google.com/document/d/16ofBfNadmTOd_MwKmvpY7VcsQuBVU_l-dhAwsfhWRNw/edit#

Hit me up with any questions.

**Comment by KevZawacki** [comment]
@stephaniemcv OK -- [document](https://docs.google.com/document/d/16ofBfNadmTOd_MwKmvpY7VcsQuBVU_l-dhAwsfhWRNw/edit#) has been fully reviewed and copyedited.

**Comment by stephaniemcv** [comment]
@KevZawacki , thank you for busting that out! 

Document has now been passed to Abigail in legal for a final review.

**Comment by valianttry** [comment]
@stephaniemcv please let me know if you need anything. I find it's helpful to give Abigail specific deadlines (in this case, Nov 10 would be ideal so we can start getting this in the L10N queue).

**Comment by ScottDowne** [comment]
Don't forget it needs to be built after copy and before l10n can start ;)

**Comment by stephaniemcv** [comment]
@ScottDowne @TheoChevalier Abigail has officially signed off. I toss it over to you guys. ^_^
https://docs.google.com/document/d/16ofBfNadmTOd_MwKmvpY7VcsQuBVU_l-dhAwsfhWRNw/edit#

**Comment by roseregina** [comment]
feedback on the page redesign: 
1. I thought that the ways to give page was also being made stable and localized. There is a link under question 1 to the wiki page. I may be totally wrong on the localization part. 
2. Link to [PayPal](https://www.paypal.com/webapps/mpp/ua/privacy-full) and [Stripe](https://stripe.com/privacy)'s privacy policies in the second paragraph. 
3. "Mail a check" links to the ways to give page on the wiki. 

All the other bits look good.

**Comment by ScottDowne** [comment]
Pretty sure we can close this.

https://donate.mozilla.org/faq and https://donate.mozilla.org/ways-to-give
