### ISSUE TITLE
Meme Around activity is called Meme School on MLN

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/Advocacy#587]
Detailed description of work:

“Meme School“ on this page https://learning.mozilla.org/en-US/events/resources links to the “Meme Around” activity here https://advocacy.mozilla.org/en-US/maker-party/activities/meme-around
We need a single name for localization, and I suppose “Meme Around” is the final name.
I think “Meme School“ is only used here and in the survey. Not sure who owns MLN copy.

@ScottDowne do you have a specific tool to update strings, or it’s done manually?

_Start date: October 14, 2016_ 
_Due date: October 14, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

**Comment by ScottDowne** [comment]
For en-US strings, we update it directly in the .properties file, here is the string in question: https://github.com/mozilla/learning.mozilla.org/blob/master/locales/en-US/event-resources.properties#L4

I suspect the name changed late in the game, from a copy point of view, and it wasn't pushed out to any of the old usages of the name. "Meme Around" is the newest and probably the correct one.

I dunno anything about the survey.

**Comment by TheoChevalier** [comment]
Thanks @ScottDowne, for one second I thought we had to add the string to locale files, but of course we don’t, Pontoon will do it.
I will take care of the survey, no worries. It was mostly to check if we were okay with the change.

**Comment by TheoChevalier** [comment]
Fixed in https://github.com/mozilla/learning.mozilla.org/pull/2343
