### ISSUE TITLE
What's the current status of signup snippet?

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#588]
I was just kicking the tires, and this is what I found, and what I still need to test.
It looks roughly like this without a `video_url` set
![test-no-vid](https://cloud.githubusercontent.com/assets/197334/19399417/6b3cdcaa-921f-11e6-982f-6ecff9f66441.png)
This is it with a `video_url` set
![with-video](https://cloud.githubusercontent.com/assets/197334/19399431/7766fcc2-921f-11e6-8708-6568c17e2b6b.png)
All the text is configurable, so the values I put in are just test data.

After a successful submission, which uses basket, I see this. (test text again, it's configurable, and localizable)
![success](https://cloud.githubusercontent.com/assets/197334/19399460/a44190ae-921f-11e6-84f2-e8cafa2267e1.png)

And submission error messaging looks like this. (test text again, it's configurable, and localizable)
![error](https://cloud.githubusercontent.com/assets/197334/19399530/f4bdf6da-921f-11e6-8f83-f66aa565fe8d.png)

Both of these look like they should be centered, but that seems to be broken.

Double opt ins work.

It uses Basket, so we should be good to go on the salesforce end.

**Comment by ScottDowne** [comment]
cc @valianttry or @stephaniemcv 

I'll let you cc any more needed people from here.

**Comment by jkt230** [comment]
Here are my notes with my conversation with the Product UX team:
- The video piece needs to be removed (keep the Firefox logo)
  Scott, looks like we have that already
- Per Stephen and his guidelines, the form should not disrupt the page layout
- Doesn’t move up or down static elements of the page (as it currently does)
- Is it possible that the email form stays within the orange area as seen here: http://people.mozilla.org/~shorlander/snippet-best-practices/about-home-layout-flexible-space.png
- Currently I think the form pushes the whole bottom page down 

So questions - is it possible to have that form without pushing the page layout down? Possible to make all smaller? Also, can we change the button color?

**Comment by ScottDowne** [comment]
We can not currently change the button colour within the template, I would need to change the code. No biggie, I can do that. I think green or blue or make it configurable is best.

I can rip the video right out, so it's not even an option. This might make the most sense.

Yeah, making it smaller might require quite a bit more design work, and essentially a new build, as I don't see making it smaller to be a great experience, but again, designers can decide if smaller (to fit in the space) is sufficient.

**Comment by valianttry** [comment]
@jkt230 do you all have any design resources or .... do we need to talk about adding this to our creative team's queue? Things are getting a bit tight with fundraising coming up, but as I said we might be able to spare some time given this has implications for fundraising for us (the ROI case for list growth is easy to make).

cc @lovegushwa (<<Jordan, our lead designer)

**Comment by ScottDowne** [comment]
@jkt230 do you happen to know the dimensions in that image as pixel values?

@valianttry So Becca wonders if the multi step form we used in copyright is a possible solution to cut down on snippet height?

**Comment by valianttry** [comment]
OOOOOH i love @beccaklam  idea!! We were looking for an excuse to use this form for optin testing.... shazaam.

For the uninitiated here is a screengrab of the "slider" form (below) and you can test it yourself on the https://www.changecopyright.org/ petition:

![mozilla_advocacy__reform_copyright](https://cloud.githubusercontent.com/assets/9830371/19401899/b859f3f4-9212-11e6-9605-d8f6a7aab262.png)

FYI It was reviewed and approved by Marshall and compliance / legal.

**Comment by jkt230** [comment]
@ScottDowne I believe it's the same as above the search bar, as long as it sits within 470 x 192 it should be good. 

Sounds like there are 3 versions we can test:
1) The slider form
2) Maybe a simple snippet and if you click on it or hover over, the opt-in form drops down below - Scott / Andrea - would we need a designer for this?
3) Making the original form smaller to fit within 470 x 192 - Scott / Andrea - do we still need a designer in this case? 

If designer resources are needed, I need to investigate on how we can get them. We currently don't have a dedicated designer. Let me know, thanks!

**Comment by ScottDowne** [comment]
I don't need a designer for 1 and 3. 2, I would need a designer if the form isn't the same, but if it's just hover and then expand the current form, then I don't think I need designers for that either.

**Comment by jkt230** [comment]
@ScottDowne Per your question on #2, I would imagine the form to be the same (maybe different button color).

**Comment by valianttry** [comment]
@jkt230 button color can be a useful data point from our current fundraising form test. WE'll know if color makes any difference. :)

**Comment by jkt230** [comment]
@ScottDowne Can you give me a timeline in terms of having these to test so I can let Giorgos know when to expect them? Thank you!!!!

**Comment by ScottDowne** [comment]
@jkt230 I don't have a timeline yet, it sounds like we're scoping what would be involved, but if there is a timeline, I'm not aware of it.

Either way, I'll let you know when I know of a timeline so we can give Giorgos a heads up :)

**Comment by jkt230** [comment]
@ScottDowne Ah I see, is there anyway it can be completed by next Wed.? Consider it an early birthday present to Andrea? :) We get this rolling and we can get more subscribers to the Moz Foundation list! Anyways, let me know when you know your timeline. 

Thanks!

**Comment by ScottDowne** [comment]
@jkt230 hey, just doing mozfest stuff until next week, then I'll start on this.

What it looks like I'll be doing, and if this is okay with everyone else, is the sliding form version here: https://github.com/MozillaFoundation/Advocacy/issues/588#issuecomment-253912275, so it easily fits into the space. I might also try a few simpler versions that still fit, and we can test.

@jkt230 should I or you give Giorgos a heads up, about timing and direction?

**Comment by jkt230** [comment]
@scottdowne Great, and Wes also pointed out a 4th test that we can use (no dev work required). You've built the fundraising button that we could potentially use for email. 

![screen shot 2016-10-27 at 9 12 01 am](https://cloud.githubusercontent.com/assets/6807556/19777446/0e8d01ca-9c2d-11e6-9354-85403200c9b1.png)

As for heads up just ping both I and Giorgos, thanks!

**Comment by jkt230** [comment]
@ScottDowne A friendly follow up to see if we can test the templates you have created next week? We just ran the one above this comment for a few days and pulling results to see if it drove any higher conversions for sign-ups. The CTR was a bit lower than just sending them directly to the landing page.

**Comment by ScottDowne** [comment]
@jkt230 I think I can have it ready by next week. Depends how my day goes, but this is my second task on my list.

Also, I'm not sure what you meant by "The CTR was a bit lower than just sending them directly to the landing page"

Another thing I noticed, but unrelated to fundraising, the snippet icons seem to be subjectively too large for a lot of the content. Is this known/intended/acceptable?

**Comment by jkt230** [comment]
Thanks @ScottDowne - let us know if there's anything we can do to help. 

As for CTR - it's our metric to measure clicks over impressions. So with a simple snippet that has just a link I think average ctr would be around .13% but with the form above (the button) the ctr was around .09%. 

As for snippet icons - I believe they're now 64 x 64 instead of the old 40 x 50. Do they look strange to you?

**Comment by ScottDowne** [comment]
I've only yesterday and today been able to carve out some time to start the dev on this. Had a cold for the first half of this week too.

Interesting, so in a test of button vs link, link out performed the button?

Yeah, I think 64x64 can look strange, depending on the text. I don't think one size is going to work in all cases. For snippets with two lines, I think this looks best:
![icon-size](https://cloud.githubusercontent.com/assets/197334/20225287/8d27f654-a810-11e6-877f-b103f7badbc7.png)

Which is 40w x 50h

For snippets with 3 or more lines of text, and depending on the layout of the icon, it may warrant a larger icon. 64 x 64 would probably be the max. 50x50 might also be acceptable in some cases?

Thoughts on the sizes?

**Comment by jkt230** [comment]
Got it. We went from 40 x 50 to 64 x 64 because the creative team has repeatedly given us feedback that's it's hard to create icons that small which limits what they can create. I would think it's best to stay with one size for consistency but I'll loop with the creative team to get their thoughts. 

Any updates on the email form?

**Comment by jkt230** [comment]
@ScottDowne Circling back around to this - I know you were building out a few of these but would it be possible to get one form by next week? Let me know!

**Comment by ScottDowne** [comment]
@jkt230 I hope to have the email signup finished this week. It's close.

Just to double check that we're on the same page. I'm making it work like form in https://www.changecopyright.org/ that cool? It's pretty interactive, hence why it's taken a bit of time.

**Comment by jkt230** [comment]
@scottdowne Yup, is there a place to put snippet copy?

**Comment by ScottDowne** [comment]
@jkt230 Created a pull request and put into review just now: https://github.com/mozmar/snippets/pull/93

And yeah, there is a standard icon and text that's a pretty standard snippet, with the form under it.

Looks roughly like this:

![step1signup](https://cloud.githubusercontent.com/assets/197334/20580859/fde97bec-b1a2-11e6-9530-ecf6003a91fd.png)

and:

![signupstep2](https://cloud.githubusercontent.com/assets/197334/20580862/01696264-b1a3-11e6-945e-6d96b0964bfb.png)

**Comment by ScottDowne** [comment]
The text I used in my screenshots is totally just testing text, and can be whatever you want in whatever language.

**Comment by jkt230** [comment]
Thanks Scott, couple Qs:
1) We can change up icon and text?
2) Are there more required fields besides Email, First Name? I'm assuming last name, privacy etc is included?

**Comment by ScottDowne** [comment]
Yeah, any icon (or non) and any text.

I based it off the previous signup, with had first name, country, and email (no last name)

And yes, there is a privacy policy too, which can be whatever text we want in whatever language:

![step3signup](https://cloud.githubusercontent.com/assets/197334/20580955/ad38f776-b1a3-11e6-891a-6a83a5eb9859.png)
![signupstep4](https://cloud.githubusercontent.com/assets/197334/20580957/af6fe266-b1a3-11e6-9455-54da88a62e0e.png)

**Comment by ScottDowne** [comment]
Please excuse my "To agree of not to agree." test privacy policy too :)

**Comment by ScottDowne** [comment]
This is finished. Any new issues around it should be filed as a new ticket.
