### ISSUE TITLE
Prep comms for 6/28 Codemoji launch

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/Advocacy#59]
We're ready to move ahead with external comms, ideally on Tuesday, June 28. [Here's the comms plan](https://docs.google.com/document/d/1iY6OkuVDSJgUx0QSuvjbIQpeRrb0SjPr81Kwyyd4jOA/edit#).

Checklist and questions:
- [x] Complete comms plan (content, media list, etc.)
- [x] Confirm Codemoji doesn't need additional dev work before 6/28 cc @ScottDowne 
- [x] Confirm Codemoji doesn't need additional design work before 6/28 cc @lovegushwa @natalieworth 
- [x] Determine email next steps cc @stephaniemcv @valianttry Do we have room in the calendar for a second, larger Codemoji email? I'm happy to draft it
- [x] Finalize social media and external comms graphics cc @lovegushwa @natalieworth Possible to wrap up tickets #37 and #42 this week?
- [x] Align with MoCo Comms and agencies cc @kevzawacki
- [x] Align with MoCo Social and Razorfish cc @kevzawacki
- [x] Align with MoCo Marketing (MJ, Greg) cc @kevzawacki
- [x] Get Mark's sign-off on statement cc @kevzawacki
- [x] Write all-MoFo email from Brett cc @kevzawacki

cc @brettgaylor @HPaulJohnson

**Comment by stephaniemcv** [comment]
@KevZawacki @valianttry 
Per the CRM integration calendar we are technically cleared to start sending emails on 6/28 to the Foundation list. There is the caveat that CRM team may need some extra time to finish setting things up so it may be best to plan in some flex.

**Comment by KevZawacki** [comment]
@stephaniemcv @valianttry 

Gotcha. Can/would we want to send a Codemoji email to the remainder of the Advocacy list in the meantime, on either 6/28 or 6/29? Any way to parse out people who received the beta test?

I can tweak the old email in a way that won't require additional policy review.

**Comment by lovegushwa** [comment]
@natalieworth let's connect today on finishing up the social media launch assets for @KevZawacki

**Comment by stephaniemcv** [comment]
@KevZawacki @valianttry
There was discussion of going to another 100,000 cohort before full deployment to the remaining list, but I'm not sure where that conversation landed. @shaghdoosti do you have any input regarding this?

And yes, I can suppress anyone who already received the test.

**Comment by KevZawacki** [comment]
@stephaniemcv @shaghdoosti Gotcha. Either way, I've prepped copy for the second email and opened a new ticket, #61
