### ISSUE TITLE
Add existing localized copy to new snippet designs and launch

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#590]
See #326 
Once the test of the #326 snippet designs are complete, assuming results are positive, we should launch those snippets in our high priority locales as soon as possible. 

We can plug in existing 2015 localized copy. That copy is here:

DE:
Mozilla, die Entwickler von Firefox, sind auf Ihre Spende angewiesen. <em>Wenn jeder nur 3€ spenden würde, hätten wir genug für das ganze nächste Jahr. Spenden Sie jetzt.</em>

ES:
Además de crear Firefox, Mozilla es una organización sin fines de lucro que depende del apoyo de tus donaciones. <em>Si todo el que lee esto contribuye con 3€, tendremos para todo un año. Dona ahora.

FR:
Mozilla, qui a créé Firefox, est une fondation sans but lucratif, et nous comptons sur vos dons pour nous soutenir. <em>Si chaque personne qui lit ceci donnait 3€, les besoins de Mozilla seraient couverts pour l'année à venir. Faites un don maintenant.

PTBR:
A Mozilla, desenvolvedora do Firefox, é uma organização sem fins lucrativos, e nós contamos com suas doações para continuar o trabalho. <em>Se todos que estejam lendo isso nos ajudarem com R$10, nós estariamos suportados por outro ano. Doe agora.

You can see the above localized variants in this spreadsheet tab "Tracking Content Variants":
https://docs.google.com/spreadsheets/d/1Inh1KSkXSh8cJiCnvwm00JOq85FsPQR5L3pzPzQBBio/edit#gid=349958906

_Start date: October 17, 2016_ 
_Due date: October 19, 2016_ 

CC: @ScottDowne @TheoChevalier

**Comment by vojtechsedlak** [comment]
The tests are currently being set up by Wes, with the following variants tested
- winner from 2015 EOY campaign
- optimized variant of new design with grey highlight of amount
- optimized variant of new design with blue highlight of amount

**Comment by valianttry** [comment]
I'm closing this ticket as the work seems to be finished. If that is incorrect please reopen. (just cleaning up github tickets)
