### ISSUE TITLE
Create social media plan for EOY fundraising

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#591]
Detailed description of work:
Review the Project Brief here: 
https://docs.google.com/document/d/1vCqtXP-anfi-50W0C2j_zrhNIZncXRBFX9xt9ujRRpk/edit#

review draft timeline here:
https://docs.google.com/spreadsheets/d/1huVMZb2FlKgILOM3q9Ky1Spf4qLpzdqkWH3Ka3WhvsQ/edit#gid=0

Craft a social media plan that helps prime audiences ahead of calls for donations. This work will require help from design and creative of course. 🎱 

_Start date: October 18, 2016_ 
_Due date: October 31, 2016_ 

CC: @lovegushwa @HPaulJohnson

**Comment by HPaulJohnson** [comment]
copy complete and shipped to l10n for localization. Tracked in ticket #634 

design to be complete by Thursday, 11/17. Tracked in ticket #631 

closing this one!
