### ISSUE TITLE
Localize copy for Heartbeat fundraising test

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#595]
Detailed description of work: 
We are planning to run a fundraising test in Firefox Heartbeat, as part of our EOY fundraising campaign. While we were initially hoping to reuse existing strings for EN and DE, the two target locales, technical limitations around the snippet require a localization of new strings. There is also a need to translate a feedback survey into German.

The new strings that need to be localized into German:
- Prompt Language
  - “Will you donate to Mozilla, the nonprofit organization behind Firefox? Thanks!“
    -“Did you know that Mozilla, the maker of Firefox, is a nonprofit dependent on donations of users like you?”
    -“If everyone reading this chipped in $3, Mozilla would be supported for another year.”
- Buttons Language
  - Donate
  - Donate Now
- Feedback Language
  - Give Feedback
  - I Don’t Like This

I will provide content for the survey, as soon as it becomes available. @TheoChevalier would you please be able to help with getting those strings translated? Please let me know if you have any questions. Would you also be able to provide estimate for how long this might take, so that we can adjust our timeline accordingly? Thank you!

_Start date: October 18, 2016_ 
_Due date: October 25, 2016_ 

CC: @valianttry

**Comment by TheoChevalier** [comment]
Hey @vojtechmzl, 

Once the survey is ready, and assuming you’re using SurveyGizmo, could you please extract strings like here? https://github.com/MozillaFoundation/Advocacy/issues/565#issuecomment-253251477 (Instructions are here if needed https://help.surveygizmo.com/help/export-fields-for-translation#export-fields-for-translation )

In the mean time, could you help clarifying where and how the strings above will be used? Is is in a snippet on about:home, or in a toolbar like Heartbeat used to be displayed? If you have a mock-up (even a draft) that would greatly help localizing it properly. For instance, getting context for button languages and with which string(s) they are associated.

Regarding timeline I can’t say for sure before having a look at the survey content, but given it’s only one locale, it should be ready pretty quickly.

Thanks!

**Comment by TheoChevalier** [comment]
Also, just to make it clear, I will expose all the strings (survey + heartbeat) at the same time, to avoid annoying localizers with multiple requests.

**Comment by vojtechsedlak** [comment]
Thanks for fleshing out the process @TheoChevalier, much appreciated! Here is a preview of the test that I got from the heartbeat team. It is indeed the toolbar-like notification that appears at the top of the browser window:

<img width="637" alt="screen shot 2016-10-19 at 9 31 14 am" src="https://cloud.githubusercontent.com/assets/20688240/19527930/de5a5150-95de-11e6-8d58-570fd330a4e0.png">

I am still waiting for the survey content, but will pass it along as soon as I get it. The survey will be hosted on surveygizmo and will be linked to with the "Give Feedback" link.

Thanks again!

**Comment by TheoChevalier** [comment]
Localization has started, progress can be tracked here: https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=surveys/survey_eoy_heartbeat.lang
Once it’s complete, I will export the translations into a .xls file that can be imported back into SurvezGizmo.

**Comment by TheoChevalier** [comment]
Hey @vojtechmzl here are the German translations: https://github.com/mozilla-l10n/engagement-l10n/blob/master/surveygizmo/eoy_heartbeat/de.xls 
Let me know if you have any issue uploading them into SurveyGizmo.

If the UI strings need to be copy/pasted, this view should be more appropriate https://l10n.mozilla-community.org/langchecker/?website=6&file=surveys/survey_eoy_heartbeat.lang&action=translate&show

**Comment by vojtechsedlak** [comment]
Thank you very much @TheoChevalier. I really appreciate your help with this!

**Comment by vojtechsedlak** [comment]
Hey @TheoChevalier, here is a [link](http://qsurvey.mozilla.com/collab/Foundation-Heartbeat-Test?sglocale=de) to the German survey with inserted translations. I'm not sure if the usual workflow includes QA/validation at this point, but just wanted to pass this along. Thanks!

**Comment by TheoChevalier** [comment]
Yeah, always better to check the final result :) Everything looks good to me!
