### ISSUE TITLE
EOY Test: Preselecting an amount for non-snippet traffic 

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#597]
Detailed description of work: Traffic from sources other than the snippet does not get a preselected amount. Test whether this would improve conversions.

_Start date: October 19, 2016_ 
_Due date: December 1, 2016_ 

CC:

**Comment by vojtechsedlak** [comment]
Test is now running.

**Comment by Matt-Holland** [comment]
@vojtechmzl did we get results from this test? Can we add the results to this ticket and close the ticket?

**Comment by vojtechsedlak** [comment]
Yup, the results were inconclusive, as per the chart below. Closing this issue.
<img width="1250" alt="screen shot 2016-12-07 at 5 17 19 pm" src="https://cloud.githubusercontent.com/assets/20688240/20993762/429d512e-bca1-11e6-98a1-2751f4c152d6.png">
