### ISSUE TITLE
EOY Test: Snippet Icon Images

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#598]
Detailed description of work: Test multiple variants of images with the fundraising snippet. 

_Start date: October 19, 2016_ 
_Due date: December 1, 2016_ 

CC:

**Comment by ScottDowne** [comment]
@vojtechmzl who should be cc'ed on this?  Do we need images made? Nov 16th worried me.

**Comment by vojtechsedlak** [comment]
Hey @lovegushwa, could we put together 3 or 4 different ideas for the snippet icon that would align with the creative identity work done on social? The icons would ideally be all accompanied by the same copy below:

"Mozilla, the maker of Firefox, is a non-profit, and we rely on your donations for support. If everyone reading this chipped in $3, we would be supported for another year. Donate now."

We are waiting for other test variable to land, so this would be a good test to run asap. Let me know if you have any questions or if I can set up a call for us to chat about this?

Thanks.

**Comment by Matt-Holland** [comment]
these are now in the rotation, as per @vojtechmzl . Closing this ticket as completed.
