### ISSUE TITLE
Q2 Program Review - Email stats

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#60]
@stephaniemcv - Hoping to pull together some data for the Q2 Program Review. Specifically, looking for the following: 
1. Click rates
2. Email rates
3. Opt-ins 
Would you be able to help?

**Comment by stephaniemcv** [comment]
I can get you this. Edit: But I won't be able to finish pulling numbers until the 23rd, earliest. Due to CRM integration work, I can't login to SalesForce or MarketingCloud (ExactTarget)

**Comment by damiankay** [comment]
Ah, gotcha. No problem, we'll hold tight until you have access. Thanks!
