### ISSUE TITLE
EOY Test: Thank you page design (adding thank you image/gif/video)

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#601]
Detailed description of work: Test different thank you messages to see if they improve opt-in rates.

_Start date: October 19, 2016_ 
_Due date: December 1, 2016_ 

CC:

**Comment by valianttry** [comment]
@vojtechmzl what's needed for this work? Given it's already November, let's pick perhaps 2-3 creative variants to test. We will need to ticket the design work as soon as possible.

**Comment by vojtechsedlak** [comment]
Design of the new thank you page tracked [here](https://github.com/MozillaFoundation/Advocacy/issues/623)

**Comment by vojtechsedlak** [comment]
Hey @ScottDowne, what's the status of the new thank you page design? I was hoping we could set up a test before Hawaii, but not sure whether we can trigger it the same way as the frequency selector test with a URL parameter?

**Comment by vojtechsedlak** [comment]
Changes to the thank you page design did not improve conversions on the email sign-up form nor the social buttons. The overall engagement on the page was also lower for the new design, as per the chart below:
<img width="1134" alt="image" src="https://cloud.githubusercontent.com/assets/20688240/21622448/512dc9be-d1b2-11e6-9381-5a144df5d38a.png">

Further brainstorm might uncover opportunities for optimizing the thank you page user flow.
