### ISSUE TITLE
Design: EOY 2016 Identity Directions

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#605]
Design multiple EOY identity directions that build on our visual system from last year, but without Dapper Fox. Start with the heart, explore other directions that incorporate non-fox digital native content like cats etc. Create design variants with and without copy. Ideally we will test performance of directions on social October 26-29.

_Start date: October 19, 2016_ 
_Due date: October 25, 2016_ 

CC: @HPaulJohnson @vojtechmzl @natalieworth @beccaklam @valianttry

**Comment by lovegushwa** [comment]
Last years creative for reference: 

![screen shot 2016-10-20 at 1 19 50 pm](https://cloud.githubusercontent.com/assets/12228435/19576461/f207097a-96c7-11e6-9f7e-7479ee53103a.png)

**Comment by lovegushwa** [comment]
@HPaulJohnson do you think we can swing a test next week?

**Comment by HPaulJohnson** [comment]
Yes, we could do simple quick test on Facebook targeting Moz supporters and even people who donate money to charities/causes. We'd need some budget though not a lot for a quick test.

**Comment by lovegushwa** [comment]
@brettgaylor we would like to spend 2k testing different creative directions next week. Can you approve this?

**Comment by brettgaylor** [comment]
Yes 👍

**Comment by lovegushwa** [comment]
@KevZawacki is working on social copy here: https://docs.google.com/document/d/1Pg-4PWXu8z5y0T5Il6VYxZU__T5QwucoqiBX9jV5xPc/edit

Also Kevin's case to give document should be helpful: https://docs.google.com/document/d/1YXEooaZfMO3jQoBTzgoLqWmVXQYKNnNkoUXjhiFJqtM/edit#

**Comment by lovegushwa** [comment]
@beccaklam @natalieworth from todays creative discussion: 

HEARTS - “share some love with us"
This direction build off of last years heart theme, but with a focus on formal graphic beauty, very nice vector shapes, warm color and texture. Eye candy. Some options include numbers related to giving goals or a deadline countdown. All about asking our users to share some love and give back.

<img width="399" alt="screen shot 2016-10-21 at 5 19 44 pm" src="https://cloud.githubusercontent.com/assets/20977376/19612338/fe0baf68-97b3-11e6-8245-eb09541ac132.png">
<img width="200" alt="screen shot 2016-10-21 at 5 19 31 pm" src="https://cloud.githubusercontent.com/assets/20977376/19612337/fe0b3d30-97b3-11e6-9542-4c036390cd34.png">
<img width="201" alt="screen shot 2016-10-21 at 5 19 16 pm" src="https://cloud.githubusercontent.com/assets/20977376/19612336/fe0ab05e-97b3-11e6-9654-9bc7a725b158.png">

PHOTO w/ filter and scribbles - “show the good we do"
A similar image based approach taken by many nonprofits, but with a twist. A instagram and sticker like treatment move the images of people out of a typical NGO pity space into a equal stakeholder in internet culture space. EMPOWERMENT.

<img width="598" alt="screen shot 2016-10-21 at 12 47 24 pm" src="https://cloud.githubusercontent.com/assets/14876567/19611828/67776aee-9798-11e6-8c66-a356482b888b.png">
<img width="557" alt="screen shot 2016-10-21 at 12 48 04 pm" src="https://cloud.githubusercontent.com/assets/14876567/19611845/7c1543b8-9798-11e6-9f9d-32848dbadd6a.png">

THROWBACK - “we built the web you love, but the web of today is under threat, help"
This direction plays up collective love for the internet via digital nostalgia. (Possibly though anthropomorphizing bits of interface or hardware.)  But that old internet we love is now under threat, join the epic struggle and help us defend it. Some stranger things vibes here. 

<img width="590" alt="screen shot 2016-10-21 at 10 34 56 am" src="https://cloud.githubusercontent.com/assets/14876567/19611889/a9dc6ec0-9798-11e6-99f8-e6ae374e421a.png">
<img width="550" alt="screen shot 2016-10-21 at 2 24 47 pm" src="https://cloud.githubusercontent.com/assets/14876567/19612222/3733326c-979a-11e6-88c7-4a06526ed60b.png">
<img width="532" alt="screen shot 2016-10-21 at 2 25 37 pm" src="https://cloud.githubusercontent.com/assets/14876567/19612231/43875afc-979a-11e6-81fd-a1d744bb20b4.png">
<img width="392" alt="screen shot 2016-10-21 at 2 26 29 pm" src="https://cloud.githubusercontent.com/assets/14876567/19612253/6820b3fe-979a-11e6-8ba2-ae4487529d1f.png">
<img width="266" alt="screen shot 2016-10-21 at 2 27 40 pm" src="https://cloud.githubusercontent.com/assets/14876567/19612284/978ec86a-979a-11e6-9bc2-d5af038a95e9.png">

CAT illustration in space - “faux kick starter” 
We attract attention to our fundraising ask by positioning it as a faux kick starter to send the internets most beloved creature, a cat, to space. Folks expect a illustrated fox not a illustrated cat so I expect this direction would be hard to ignore. This could easily tie into something like, well now that we have your attention learn about our [Case to Give](https://docs.google.com/document/d/1YXEooaZfMO3jQoBTzgoLqWmVXQYKNnNkoUXjhiFJqtM/edit#).

<img width="400" alt="screen shot 2016-10-21 at 5 23 27 pm" src="https://cloud.githubusercontent.com/assets/20977376/19612340/05579f16-97b4-11e6-9377-8a76a19643a3.png">
<img width="627" alt="screen shot 2016-10-21 at 5 23 18 pm" src="https://cloud.githubusercontent.com/assets/20977376/19612341/05586e28-97b4-11e6-878e-5695a623f30d.png">
<img width="297" alt="screen shot 2016-10-21 at 5 23 07 pm" src="https://cloud.githubusercontent.com/assets/20977376/19612342/05593830-97b4-11e6-8595-bce0c17b7aaf.png">

CATs, DOGs, and PIZZA photo in space - “a healthy web is more than cats” … (it’s about dogs too)
Similar to the idea above in that this direction points to our [Case to Give](https://docs.google.com/document/d/1YXEooaZfMO3jQoBTzgoLqWmVXQYKNnNkoUXjhiFJqtM/edit#). It celebrates the internet we love with net art like collages of a cat + another popular internet item. It uses fun to get to serious. 

I can see it working with @KevZawacki copy: A healthy web is about more than just cats—it's about free expression & equality. Support Mozilla & a healthy web today: [LINK] [IMAGE]

<img width="419" alt="screen shot 2016-10-21 at 5 15 48 pm" src="https://cloud.githubusercontent.com/assets/20977376/19612350/0bc3981e-97b4-11e6-8a38-62d0cf845983.png">
<img width="419" alt="screen shot 2016-10-21 at 5 15 59 pm" src="https://cloud.githubusercontent.com/assets/20977376/19612363/1b67ae9a-97b4-11e6-9aea-8e45835e2c70.png">

CHARACTERs - “empowerment and belonging” (shared vision for the future, free and open.)
This direction is about kindness/sweetness, friendship and collective action. It uses weird wonderful web like characters working together to teach, share, take action and celebrate to pull on heartstrings. Cute little sympathetic critters that embody the best of what Mozilla stands for. How could you not donate?

<img width="796" alt="screen shot 2016-10-21 at 12 20 19 pm" src="https://cloud.githubusercontent.com/assets/14876567/19611853/8429470c-9798-11e6-96eb-6c1041b2bd07.png">
<img width="395" alt="screen shot 2016-10-21 at 12 20 12 pm" src="https://cloud.githubusercontent.com/assets/14876567/19611857/88899018-9798-11e6-97e5-63870ecf223f.png">
<img width="580" alt="screen shot 2016-10-21 at 11 03 44 am" src="https://cloud.githubusercontent.com/assets/14876567/19611865/93115110-9798-11e6-8a97-26a3e6db23e9.png">
<img width="428" alt="screen shot 2016-10-21 at 11 04 34 am" src="https://cloud.githubusercontent.com/assets/14876567/19611871/956e75a0-9798-11e6-8005-4ed896aa8125.png">

**Comment by lovegushwa** [comment]
@HPaulJohnson @KevZawacki checkout these directions above. I'd like to finalize a post for copy for each direction EOD Monday and decide if we should go ahead with our test next week.

**Comment by brettgaylor** [comment]
FWIW - cat in space FTW

**Comment by lovegushwa** [comment]
@beccaklam @natalieworth 
So lets test: HEARTS, PHOTO, CHARACTERS

**Comment by lovegushwa** [comment]
@HPaulJohnson @natalieworth @beccaklam 

PIZZA CAT, no copy
PHOTO, no copy
HEARTS, no copy + Donate
CHARACTERS, no copy + Donate

@natalieworth see what copy works best in your character design:

"Your support makes Mozilla's work possible."
"Support Mozilla, Donate now."
"Help protect freedom online."

**Comment by lovegushwa** [comment]
@natalieworth @beccaklam drop your creative and copy into this doc:
https://docs.google.com/document/d/1Pg-4PWXu8z5y0T5Il6VYxZU__T5QwucoqiBX9jV5xPc/edit

**Comment by HPaulJohnson** [comment]
Added some initial copy for the four design directions at the bottom of the doc above.

**Comment by vojtechsedlak** [comment]
Below are URLs we can use for tracking respective variants in GA. If there are multiple versions for each variant, we can distinguish them with the use of utm_term. Let me know if there is anything else I can help with!

Pizza Cat
https://donate.mozilla.org/?utm_source=facebookAd&utm_medium=cpc&utm_content=pizzacat

Photo
https://donate.mozilla.org/?utm_source=facebookAd&utm_medium=cpc&utm_content=photo

Hearts
https://donate.mozilla.org/?utm_source=facebookAd&utm_medium=cpc&utm_content=hearts

Characters
https://donate.mozilla.org/?utm_source=facebookAd&utm_medium=cpc&utm_content=characters

**Comment by HPaulJohnson** [comment]
thanks, @vojtechmzl. I added shortened versions of each in the gdoc for use in social.

**Comment by lovegushwa** [comment]
Ok, final creative is in the deck here:
https://docs.google.com/a/mozilla.com/document/d/1Pg-4PWXu8z5y0T5Il6VYxZU__T5QwucoqiBX9jV5xPc/edit?usp=sharing

**Comment by lovegushwa** [comment]
@HPaulJohnson excited to learn about the testing results we will be pushing to finish up #606 in the next few days.

**Comment by natalieworth** [comment]
@lovegushwa @beccaklam @vojtechmzl Exported these photographic options with different treatments here. I'm not 100% loving the overlay option yet, so I exported a couple of those. I also updated the polaroid images to include photos from our Maker Party repo of images on Flickr. If we end up going in that direction, we'll probably have to get some help to confirm the different events if needed.
Directions:
1) No treatment
2) Overlay
3) Collage
4) Narrative
https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0RzFpN0dlR0duREk

**Comment by valianttry** [comment]
@natalieworth i'm a little worried these photos are ... not diverse enough? Meaning, our audience is not just this demographic. Possible to diversify? E.g. our biggest campaign this year was in the EU... which isn't really represented in these photos. I'd be glad to hop on a call to talk more if you'd like.

Also, if these are Laura's pics we're sure we have signed releases / permission to use them?
