### ISSUE TITLE
Finalize: EOY 2016 Identity

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#606]
Choose a final identity direction based on the test results of work happening in ticket #605 

_Start date: November 1, 2016_ 
_Due date: November 4, 2016_ 

CC: @natalieworth @beccaklam @HPaulJohnson @vojtechmzl @KevZawacki @stephaniemcv @valianttry

**Comment by lovegushwa** [comment]
@KevZawacki is working on copy in #596

**Comment by KevZawacki** [comment]
New batch of social copy here: #625

**Comment by lovegushwa** [comment]
Will update with designs and close by EOD.

**Comment by lovegushwa** [comment]
Need another day to button this up.

**Comment by lovegushwa** [comment]
Great work @natalieworth @beccaklam we have a solid foundation to build on here. Let's make a few tweaks early next week but overall a really solid visual direction and sets us up to do some email testing.
A note on the numbers, those are deadline or date specific email callouts IE only so many days left to donate ... numbers don't need to be localized. CC @valianttry @stephaniemcv 

Mozilla.org takeover:
A.
<img width="1172" alt="screen shot 2016-11-11 at 3 07 37 pm" src="https://cloud.githubusercontent.com/assets/12228435/20233079/cf491534-a821-11e6-8d4e-ff6be5ce1cc1.png">
B.
<img width="1174" alt="screen shot 2016-11-11 at 3 07 19 pm" src="https://cloud.githubusercontent.com/assets/12228435/20233088/daf3e7a6-a821-11e6-87b0-ad9f18b40e91.png">

Social posts:
![social-2](https://cloud.githubusercontent.com/assets/12228435/20233208/997b9d72-a822-11e6-88c4-8645d8115dc7.png)
![social-3](https://cloud.githubusercontent.com/assets/12228435/20233209/9cea0d54-a822-11e6-9695-5a1cd9229af2.png)
![social-v1](https://cloud.githubusercontent.com/assets/12228435/20233214/a39e5484-a822-11e6-96e0-06c61dc056e6.jpg)

Email
![email_callout_v1](https://cloud.githubusercontent.com/assets/12228435/20233252/de297eee-a822-11e6-8e29-13df194476b2.jpg)
 callouts:

![email_callout_v2](https://cloud.githubusercontent.com/assets/12228435/20233256/e360a0cc-a822-11e6-82e0-86c860f13d5c.jpg)

![email_callout_v3](https://cloud.githubusercontent.com/assets/12228435/20233263/ea45595a-a822-11e6-938a-f0ab3dc6a3cb.jpg)

![email-2](https://cloud.githubusercontent.com/assets/12228435/20233278/0654f556-a823-11e6-8b1e-cb665a4f04e0.png)

![email-3](https://cloud.githubusercontent.com/assets/12228435/20233282/0d79ce74-a823-11e6-957c-1d34677c3c1a.png)

.giff:
![hearts_email_gif](https://cloud.githubusercontent.com/assets/12228435/20233302/4247d510-a823-11e6-8c83-e2b4d57783be.gif)

![hearts2x](https://cloud.githubusercontent.com/assets/12228435/20233307/46f47550-a823-11e6-9bde-32df70fb805d.gif)

Snippet icon:
![heart-snippet](https://cloud.githubusercontent.com/assets/12228435/20233331/6baa8196-a823-11e6-86d8-9e5902cbe7bf.png)
