### ISSUE TITLE
changecopyright.org meme gifs are now busted links

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#608]
Not sure what's changed, if it's Fission's end, or the hosting end. Are we hosting those images? Links seem to be busted.

Examples:

https://d3n8a8pro7vhmx.cloudfront.net/themes/57d9d5fd78b8e21a19000001/attachments/original/1475103681/memelandCTA_1.gif?1475103681
https://d3n8a8pro7vhmx.cloudfront.net/themes/57d9d5fd78b8e21a19000001/attachments/original/1475107420/memelandCTA_2.gif?1475107420

These used to be gifs.

CC: @brettgaylor @lovegushwa @cadecairos

**Comment by TheoChevalier** [comment]
Note that they are missing only for the English version. The link on the French version for instance is https://uploads.bablic.com/uploads/57e2ad4b7b8060016003f60b/57ed989118f45f6d37ca8d17.gif and it’s still up.

**Comment by jendc123** [comment]
@ScottDowne - We will check it out, but we have done nothing that would impact the cats. We may need to contact NB support.

**Comment by cadecairos** [comment]
Yeah, that's not a Mozilla Cloudfront domain, best to contact NB to see whats up.

**Comment by jendc123** [comment]
Hi @ScottDowne @cadecairos and @TheoChevalier - the English cat is up and working.

**Comment by ScottDowne** [comment]
Awsome, thanks! :rocket:
