### ISSUE TITLE
L10N cleanup on donate.mozilla.org

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/Advocacy#609]
While discussing with Scott, I realized we had to fix a few things on donate.mozilla.org before landing new strings.
1. Some locales have not been enabled on Pontoon while we seem to target them. 
   Those are the locales I plan to enable on Pontoon: da, bn-IN, gu, hi-IN, ml, nb-NO, nn-NO, te, th. To understand where this list comes from: we have a folder in the repo for those locales, but they are not enabled in Pontoon. If we don’t want to target any of them, please let me know.
   I think we could also add: bg, sr, ms, dsb, hsb, rm, my, tr, fi
   Are all those locales supported by Stripe (or any other required tool)?
2. In the website, we need to rename those locales to match Pontoon:
   gu-IN -> gu
   ml-IN -> ml
   mr-IN -> mr
   te-IN -> te
3. es-ES and es-MX are not enabled on Pontoon and contain 2015 translations from es (International Spanish)
   This means es-ES and es-MX translations are outdated and not maintained by localizers while es is up-to-date. We should remove content from those folders and update the website so that it picks Spanish translations from es folder.
4. I think some strings can be removed, and I want to remove them before adding new locales:

I assume it’s safe to remove those since the service is gone https://github.com/mozilla/donate.mozilla.org/blob/master/locales/en-US/messages.properties#L122-L129

I’m not sure where those strings were used: https://github.com/mozilla/donate.mozilla.org/blob/master/locales/en-US/assets.properties Do we still need them?

Same for snippets, do we know if we’re going to reuse them, or if we will have brand new copy? https://github.com/mozilla/donate.mozilla.org/blob/master/locales/en-US/snippet.properties 
Will we be able to display snippets for each locale complete? If not, we might want to move snippets elsewhere.

@ScottDowne assigning this one to you mostly for 2 and 3 as I’m not too familiar with the code.
@valianttry I assume you know more about the tool requirements in 1 for donate and maybe copy in 4.

**Comment by ScottDowne** [comment]
I'll take on the brunt of this, and probably file some smaller tickets if needed.

Some thoughts:
1. I'm not actually sure where those folders came from either. I thought it was from pontoon. Guess not. I'm fine with enabling anything already there, and adding new ones. When it comes to currencies, we need to consider stripe and paypal. For stripe we can use anything here: https://support.stripe.com/questions/which-currencies-does-stripe-support#currencygroup1 or here: https://support.stripe.com/questions/which-currencies-does-stripe-support#currencygroup2. It's a lot. Paypal is a bit more restrictive, in that it only supports: https://developer.paypal.com/docs/classic/api/currency_codes/#paypal However, we can setup a stripe only page, like INR: https://donate.mozilla.org/?currency=inr Finally, if it's a locale that both stripe and paypal don't support the logical currency, we can also default to something else that might work.
2. I think I can do this, I'll let you know if I run into anything.
3. Is es-MX essentially the same as es-ES that we can merge them with es? If so, we may need some better linking built in. I thought we enabled these on pontoon ages ago :( . Is it possible to enable es-ES and es-MX in pontoon so we don't need logic to handle this, if the languages are different enough?
4. I'm fine with removing whatever strings are not being referenced in the code, cause we can always find it again in the repos history, so there is little risk. Remove all the things :)

**Comment by TheoChevalier** [comment]
1. Thanks for the pointers, I will check but I think we are covered.
   I also just noticed that we’re missing some associations in this file https://github.com/mozilla/donate.mozilla.org/blob/90a4683d5585b81dc88819041ba601fb0abdc7ff/src/data/locale-data.js
   Like ja locale is not associated to JPY, ru not associated to RUB… Should we go through the list and add what’s missing?
2. Perfect, thanks!
3. In Mozilla world, we support 4 Spanish variants: es-AR, es-CL, es-ES and es-MX. They are all different (in the same way en-US is different from en-GB, etc). es locale is different in the way that it’s a “neutral” translation that can be understood in Spain, Chile, Argentina, Mexico etc. So, either we only keep es, either we remove it and enable the 4 locales instead. I can ask localizers if they want to support the 4 locales, but honestly I think this is a bit overkill for this kind of content, especially since es is already done.

I haven’t looked too much at the code, but do you think we could do something similar to this? Browsers with accept-language set to es-\* will already fallback to es, so we just need to set the currency

```
  switch(acceptLang) {
  case es-AR:
    currency='ars'
   break;
  case es-CL:
    currency='clp'
   break;
  case es-MX:
    currency='mxn'
   break;
  case es-ES:
    currency='eur'
   break;
  default:
 break;
  }
}
```

4 Ok great. Getting a PR ready

**Comment by ScottDowne** [comment]
@TheoChevalier I think you're right that supporting all es variants is overkill, and we should stick to simple es.

The question I have is around what the user should see. So say I'm in Mexico and go to donate, I get the es form, with the MXN currency. So is my URL going to be donate.mozilla.org/es/ or donate.mozilla.org/es-MX/ or does it matter?

**Comment by TheoChevalier** [comment]
> The question I have is around what the user should see. So say I'm in Mexico and go to donate, I get the es form, with the MXN currency. So is my URL going to be donate.mozilla.org/es/ or donate.mozilla.org/es-MX/ or does it matter?

I think either are okay, with a preference for /es/. When visiting AMO with es-MX set as accept-language, it displays /es/ for instance: https://addons.mozilla.org/es/firefox/

**Comment by ScottDowne** [comment]
@TheoChevalier Sounds good. I'll shoot for /es/ in the url, but still stay true to the currency.

**Comment by valianttry** [comment]
I assigned a milestone as I'm trying to sort and order tickets for EOY. Please edit the milestone if necessary.

**Comment by ScottDowne** [comment]
@TheoChevalier a handful of this work has been done. I think we should either update it with a list of what's left, if anything, or file a couple tickets that separate the final bits into new tickets and close this one.

**Comment by TheoChevalier** [comment]
Remaining work is basically:
- Merging https://github.com/mozilla/donate.mozilla.org/pull/1644
- Me enabling locales on Pontoon, but I need to announce the campaign on l10n.web mailing list first, which I should be able to do soon
