### ISSUE TITLE
Write / send second Codemoji email

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/Advocacy#61]
Copy for the second email can be found [here](https://docs.google.com/document/d/1a5I_neWdI01JSm_C3lx3Hm8KZb58UQYcvCbrOBkZsr0/edit). It's nearly identical to the first -- I only changed the P.S.

@stephaniemcv, let me know how I can help further to get this prepped for a 6/28 send. ??

**Comment by KevZawacki** [comment]
@stephaniemcv Just reviewed the test email -- looks great! No changes from me. 

Codemoji is also back online, so we're ready to send. Let me know how I can help further. ??

[--- Commented from Asana.com
#commenter Damian Kuehn
---[aa]

**Comment by stephaniemcv** [comment]
Thanks for the heads up! Right now it's an issue of finishing re-building
the new audience queries and figuring out why my numbers aren't matching
up... >_<

On Wed, Jun 29, 2016 at 4:39 AM, Kevin Zawacki notifications@github.com
wrote:

> @stephaniemcv https://github.com/stephaniemcv Just reviewed the test
> email -- looks great! No changes from me.
> 
> Codemoji is also back online, so we're ready to send. Let me know how I
> can help further. ??
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/MozillaFoundation/Advocacy/issues/61#issuecomment-229320902,
> or mute the thread
> https://github.com/notifications/unsubscribe/ALQ9sG3jWhSOwK4W7KKvCnULuuYYYimcks5qQktugaJpZM4I7wQ-
> .

[--- Commented from Asana.com
#commenter Damian Kuehn
---[aa]

**Comment by valianttry** [comment]
quick process note on this:
The ticketing for an email send should be more nuanced. e.g. "draft + approvals" should be separate from "QA and launch" etc. @stephaniemcv can you work with @damiankay to finalize some protocol for email send ticketing?

**Comment by damiankay** [comment]
Good call @valianttry - @stephaniemcv I'll set up a call to discuss! :-)

**Comment by damiankay** [comment]
Closing this issue - please reopen if necessary
