### ISSUE TITLE
Verify data pipeline for spanish version of changecopyright.org

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#611]
We've stood up a spanish only version of the petition to help with page load times for paid media.

The URL is:
https://es-mozillafoundation.nationbuilder.com/

Can we confirm that the data will be collected properly here for petition, and that google analytics is tracking this page correctly?

cc @HPaulJohnson

**Comment by vojtechsedlak** [comment]
Google Analytics is working correctly, but I can't seem to be able to submit the form, so I can't check that data is flowing into salesforce. Were you guys able to?

**Comment by brettgaylor** [comment]
Mmm you're right.  I could not complete.  In Chrome after I submitted, I see the following glitch.

![image](https://cloud.githubusercontent.com/assets/345974/19703592/3b4f4fda-9ab9-11e6-85e3-5907c2f47996.png)

**Comment by stephaniemcv** [comment]
Data does not appear to be syncing between NB and SF. I tried two different days to account for any delays in the sync.

**Comment by jendc123** [comment]
Hi @stephaniemcv - I'll have Walter look into this morning.

**Comment by imagerwalt** [comment]
Hey @stephaniemcv , it was not sent into the webhook and therefore not sync'ed into Salesforce. That's because the translation tool was removed. George added a field to mimmic the user_language option so it should be back working now. Will check again in about an hour to make sure it is sent to SF successfully. (the test user is fswl102322@mailinator.com)

**Comment by stephaniemcv** [comment]
@imagerwalt, @brettgaylor
Confirming that data is syncing now. I found Walter's test and did another one and the correct info passed through to SalesForce.

**Comment by brettgaylor** [comment]
So @HPaulJohnson feels like final hurdle has been jumped.

**Comment by HPaulJohnson** [comment]
@brettgaylor we turned the spanish ads on today. can we close this one?

**Comment by brettgaylor** [comment]
Thumbs up emoji!
