### ISSUE TITLE
Status of current EOY Thank you email

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/Advocacy#612]
@stephaniemcv Do you know if the email localized here is automatically picking translations from the GitHub repo, or if it’s copy/pasted somewhere? https://github.com/mozilla/donate.mozilla.org/blob/master/locales/en-US/email.properties

With the current setup, we keep asking people to translate it in all the locales we support on the website, I’d like to understand if it makes sense to continue doing so (i.e. if we are supporting or willing to support more locales, and which ones, for this email), or if existing translations are stored somewhere and that’s all we need. If so, I will stop exposing this file to l10n.

However if we plan to update its content that’s a different story and I need to know that as well

**Comment by stephaniemcv** [comment]
I'm only vaguely familiar with the workings around this. @ScottDowne can you comment?

It looks like the Stripe donation receipt. And I have been looking for this, because it will be moved out of Sawmill and into SalesForce Marketing Cloud with the Stripe/Paypal integration to SalesForce.  In terms of time, we didn't have plans to update the language, and re-localize, just move the EN and all translated versions as is.

**Comment by TheoChevalier** [comment]
Thanks @stephaniemcv 
We have this email translated in most of those locales: https://github.com/mozilla/donate.mozilla.org/tree/master/locales and are planning to add ~10 more soon. Does that scale with SalesForce, or we’re planning to move only a few locales?
I don’t know for which locales we’re actually sending this email

**Comment by ScottDowne** [comment]
I'm not super familiar either.

I was poking around today, and it actually looks like the strings for this were at some point moved here: https://github.com/mozilla/webmaker-mailroom/blob/master/locale/en_US/stripe_charge_succeeded_2014.json

I really really want this on salesforce ;)

Also related: https://github.com/MozillaFoundation/Advocacy/issues/404

**Comment by ScottDowne** [comment]
For what it's worth, adding more locales into the current email system, or updating the strings, looks trivial.

**Comment by TheoChevalier** [comment]
OK, then here’s what I think we could do:

we can import existing translations into SalesForce (the up-to-date translations in donate repo, not the ones in webmaker-mailroom repo). If we really need json files, I assume a script has been used in the first place to export them

#404 suggests that marketing might want to update the email? If it’s the case we should wait for the new copy, if not we can expose the latest en-US template for l10n, then update SalesForce again once we have a good coverage.

Does that sound good?

**Comment by ScottDowne** [comment]
@TheoChevalier I agree with your plan.

To convert properties to json, we use https://www.npmjs.com/package/pontoon-to-json

**Comment by valianttry** [comment]
@stephaniemcv this raises an interesting question -- we will have many more locales to associate with donor records than we actually service with outgoing email. E.g. Japanese. We can currently story locales with user records without needing to do any major infrastructure changes correct? (Thinking about what it took to set up the new locales for Maker Party). Is this a Q for Andrew?

**Comment by stephaniemcv** [comment]
That is correct. We can store an "Email Newsletter Language" field that only services languages supported by Basket infrastructure and a "Campaign Language" field can capture unsupported languages.

**Comment by stephaniemcv** [comment]
@ScottDowne Would the conversation in #618 change the data flow to SawMill? I know we want to work on moving all donor acknowledgements away from that and into SalesForce, however the scoping for that is looking to be bigger and take longer than initially thought.

**Comment by ScottDowne** [comment]
@stephaniemcv Should be separate. We're already using basket on donate, so this should come together nicely.

I also don't see any issues in the current usage of sawmill (sending thank yous) and #618 blocking each other.

**Comment by valianttry** [comment]
@ScottDowne based on the ^^ conversation, can you make sure the necessary tickets are created for this work? Please assign milestones; etc.

**Comment by ScottDowne** [comment]
@valianttry I think this might actually be closable. We don't have anything actionable until we have SalesForce sending thank you emails.

Once we do, we need to consider the decision made in this comment in this ticket: https://github.com/MozillaFoundation/Advocacy/issues/612#issuecomment-256626579

So closing, I think we have what we need. @TheoChevalier feel free to reopen or file something else if I missed something :)

**Comment by TheoChevalier** [comment]
@ScottDowne sounds good, but can we update SawMill with latest translations until we move to SalesForce? (If it’s quick?) Current translations are really outdated.

**Comment by ScottDowne** [comment]
Yeah should be easy and worth it.
