### ISSUE TITLE
PayPal down

### ISSUE THREAD

**Issue by roseregina** [MozillaFoundation/Advocacy#614]
Detailed description of work:
Multiple reports of attempts to donate through PayPal bringing this error message: 
{"statusCode":400,"error":"Bad Request","message":"donation failed"} 

_Start date: October 27, 2016_ 
_Due date: October 28, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by cadecairos** [comment]
I see ~20 failed paypal donations in the last hour, and over 270 successful donations. 

This could be related to that users card/account not being authorized to make the donation. I don't think there's anything wrong on our end right now, although if they're just seeing a bunch of JSON as an error message, that does suck.

**Comment by roseregina** [comment]
Could this be location-related? I believe that all the reports came from Brazil (though there was a spike in messages from Brazil and Germany over the past couple days, so it could just be coincidence)

**Comment by ScottDowne** [comment]
I think we should keep our eyes on this, see if it gets worse, or we see a pattern.

Right now, I don't see anything we can act on, or indication that something is broken on our end.

I did a test donation, and it most definitely works, and paypal isn't reporting any downage of service.

Regarding the error message, I have seen that before while testing, and I'm pretty sure it's also on paypals end, but might be worth spinning into it's own ticket to see if you can intercept that and display a better error.

**Comment by roseregina** [comment]
here is an image that one of the error reporters sent us (in case it is more meaningful to you than me)
 ![image](https://cloud.githubusercontent.com/assets/15040203/19808521/40fee800-9cf3-11e6-8f0b-16e220e5b3c3.png)

**Comment by ScottDowne** [comment]
Yeah, we can display a better error for that, at the very least. Filed that here: https://github.com/MozillaFoundation/Advocacy/issues/615

**Comment by roseregina** [comment]
thanks @ScottDowne, does this mean that I should close this issue?

**Comment by ScottDowne** [comment]
@roseregina Yeah, let's close this, until we see a pattern or get more data, or otherwise something looks different.

We have systems in place that if enough things start to fail, we are notified, so I'm not super worried if this isn't independently tracked.
