### ISSUE TITLE
QA: Host a Maker Party Kicker

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#616]
Detailed description of work: **Review Group, please check copy, rendering and link functionality and place edits/issues in this ticket.**

Potential issues: 
- Google  form not localized (ES, DE, FR, PL)
- Learning pages not localized in PL (https://learning.mozilla.org/pl/events & https://learning.mozilla.org/pl/events/resources)

_Start date: October 28, 2016_ 
_Due date: October 31, 2016_ 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by valianttry** [comment]
EN version:
- There's a needed hyphen here: "The best way to show that is through in person events." Should be: "The best way to show that is through in-person events."

Typo: "MaRker Parties"

![_mp_kicker_test_best_party_in_the_eu__-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/19953695/31f1d900-a12e-11e6-9d8d-50cf5765c4f9.png)

I didn't realize we would send a short EN google form to all locales. The form seems unnecessary -- why not just give them an email address to send an email declaring their interest? (someone sending an email would share name, email automatically -- the "preferred method of communication" seems superfluous.) Obviously they are already comfortable with email as a good communication channel. I would suggestion we ask recipients who are interested simply to email makerparty@mozillafoundation.org and ask their Qs. I'm also worried about the plan to respond to those who write in nonEN languages -- is 270 taking this on? Are they ready to handle interested hosts speaking DE, FR, etc? Even though the form is in EN, people will respond in their own language.

**Comment by valianttry** [comment]
The P.S. says: "PS - Not sure how to add in your event into nationbuilder? Check out this handy video."

The link opens a 22-minute video (the Webinar). It's not a short sweet tutorial on adding an event. It would be more truthful to say "We recorded a Webinar for hosts to teach you all you need to know to create your own event." This isn't a blocker for me, but I think we could do better to explain what the link actually is.

Is the Webinar in any other language? If not, we may want to add "(English-only)" after "Check out this handy video". We risk annoying people who expect localized content. I'm curious what Theo thinks of this approach.

**Comment by TheoChevalier** [comment]
> Is the Webinar in any other language? If not, we may want to add "(English-only)" after "Check out this handy video". We risk annoying people who expect localized content. I'm curious what Theo thinks of this approach.

That’s a good practice we tend to follow as localizers when we have access to the content linked. For instance, we usually do it when we link blog posts in another language from a localized text. Example: https://transvision.mozfr.org/?sourcelocale=en-US&locale=fr&repo=mozilla_org&search_type=entities&recherche=mozilla_org/firefox/dnt.lang:2faa2173&perfect_match=perfect_match (we appended “(In English)” to the French translation)

If we just had a link, we could have added “[en]”, that would have avoided changing the copy, and having a new string to translate

**Comment by stephaniemcv** [comment]
Based on the issues with this email and the decision to extend the Maker Party campaign, @shaghdoosti and I are making the call not to send this email.
