### ISSUE TITLE
GIFs are not localized anymore on changecopyright.org

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/Advocacy#617]
Locales used to have localized Nyan cat gifs, but are now showing the English version.

**Comment by valianttry** [comment]
@jendc123 at Fission has helped rectify this issue before with assistance from @gholme4

**Comment by jendc123** [comment]
Hi @TheoChevalier and @valianttry we will check this out this morning and circle back with an update.

**Comment by jendc123** [comment]
Hi @TheoChevalier and @valianttry - this has been updated and ready for review.

**Comment by TheoChevalier** [comment]
Hi @jendc123 thank you, looks good
