### ISSUE TITLE
Get donation info into Salesforce

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#618]
Detailed description of work: For the Stripe/Paypal Integration to Basket, provide a Stripe and PayPal endpoint to Pmac in MoCo for testing posts.

*Start date: November 3, 2016* 
*Due date: November 7, 2016* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by ScottDowne** [comment]
@stephaniemcv Maybe a question for pmac, but why not have donate send the info to basket directly when someone makes a donation?

**Comment by stephaniemcv** [comment]
@drewmoto Is this something we considered? I don't know if we thought this was an option.

**Comment by ScottDowne** [comment]
I guess it depends on the data? But at the point we make the donation, we likely have all the info we need, and I'm happy to send it to basket after the donation is successful. Might be easier than mucking around in stripe and paypal apis, which are not super easy.

**Comment by drewmoto** [comment]
Emailed PMac to get his thoughts. I dont see why this wouldnt work
considering you have the data already.

**Comment by pmac** [comment]
@ScottDowne I'm very open to this idea. We're already integrating with FxA like this. The best/easiest thing would actually be if you were to put the donation event data in a queue at Amazon SQS which basket could consume. We're planning on moving the FxA integration this way, and going that way for this could help get that ball rolling, as well as being more reliable and efficient than HTTP POSTs. 

And yes, I'd very much welcome not having to integrate with the Stripe and PayPal APIs. Their webhooks don't send enough info, so I'd have to then call out to their APIs to get the rest of the user info I need.

**Comment by ScottDowne** [comment]
For reference, these are the lines of code where we could be adding this:

Paypal: https://github.com/mozilla/donate.mozilla.org/blob/master/routes/index.js#L290-L291
Stripe one time: https://github.com/mozilla/donate.mozilla.org/blob/master/routes/index.js#L169-L170
Stripe monthly: https://github.com/mozilla/donate.mozilla.org/blob/master/routes/index.js#L234-L235

I suspect with a tiny bit of work could pull stripe one time and monthly into one path like paypal.

I still don't really know all the data we need to pass to basket, but we are using basket here: https://github.com/mozilla/donate.mozilla.org/blob/90a4683d5585b81dc88819041ba601fb0abdc7ff/routes/signup.js#L15-L21 It uses something called hatchet, which I'm pretty sure is an SQS queue that we created. https://www.npmjs.com/package/hatchet

**Comment by pmac** [comment]
Yeah, the hatchet thing looks perfect! The data we need is something @drewmoto can help us define. I believe he has it in a gdoc somewhere.

**Comment by drewmoto** [comment]
Here is the field mapping doc PMac referenced.
https://docs.google.com/spreadsheets/d/1Vqy_Ojg5i61ks4qm67_0rdiIvZlWu-kALMjr9KSd_iQ/edit#gid=239699807

Let me know if we should get a session on the calendar to talk through some
of this.

**Comment by cadecairos** [comment]
Yeah this should be really easy to implement with hatchet and the "send_post_request" event type. I can do this if you have too much on youre plate @ScottDowne

**Comment by cadecairos** [comment]
@drewmoto I've sent a request to access that doc using my ldap account, can you approve that when you've got a chance.

**Comment by ScottDowne** [comment]
@cadecairos that would be amazing! 🚀 I'll assign to you, let me know if you need help, have questions or want review.

**Comment by cadecairos** [comment]
@pmac Can you share the basket endpoint I should be making a post request to with the donor emails/names?

**Comment by pmac** [comment]
@cadecairos it'll be a new one I've not yet written. Let me know what you'll be sending and in what format and I can provide that for you.

Sending JSON encoded data would be great btw 😄

**Comment by pmac** [comment]
Actually maybe I'm misunderstanding... I though we were talking about you putting the info onto an SQS queue which basket would consume. Is this POST for something else?

**Comment by cadecairos** [comment]
Yeah it's a bit confusing.

We have a queue processor called sawmill that fetches messages from an SQS queue and processes the messages based on their contents. The important bit here for us is the "send_post_request" message that we use to post an arbitrary json payload to a URL. Ideally we'd like an endpoint on basket that our queue can use to post data to.

As for what the data looks like, I'm not sure. in the spreadsheet that @drewmoto and @stephaniemcv shared, there's only email, first name and last name. I presume we also want some data related info, and donation amount/type. (need confirmation here.)

**Comment by pmac** [comment]
oh yes. there's much more info. I think you only looked at the first tab of that spreadsheet. Look especially at the "Opportunity" and "RecurringDonation" tabs. So are you saying that we can't just communicate via a queue? Basket can receive POSTs, but it would be better if these data never went through the HTTP server since that would leave more connections available for newsletter subscriptions from the various websites.

**Comment by cadecairos** [comment]
There's no reason I can't drop the JSON data directly into a new SQS Queue and give basket read access!

**Comment by pmac** [comment]
> There's no reason I can't drop the JSON data directly into a new SQS Queue and give basket read access!

That would be my preference, but we can always go the easy POST way for now and upgrade later. That's my plan for our FxA integration as well. I think our time for this task may be short.

**Comment by cadecairos** [comment]
It should be really simple to add in a queue for donor data, I can have a PR on the donate.mozilla.org repo ready in a couple hours.

**Comment by cadecairos** [comment]
Update: I've got the code (still need to commit and get code review), SQS queues and IAM credentials ready to go. I just need a confirmation of the data I should include. right now, a queue message looks like this:

``` json
{
  "timestamp": "2016-11-08T21:57:59.785Z",
  "data":
   { "name": "Generous Donor",
     "email": "generous_donor@example.com",
     "donation_amount": "50.00",
     "currency": "USD",
     "recurring": true
  }
}
```

There are fields in the doc I really don't understand, if there's anything else that salesforce needs, let me know.

**Comment by pmac** [comment]
@cadecairos based on the Recurring tab of the doc it looks like they also want "installment period" which can be "Monthly, Quarterly, Yearly, Weekly, or 1st and 15th", and "installments" which seems to be a number. Do you have anything like that?

Also, any reason `donation_amount` is a string instead of an int?

Regarding SQS: An unfortunate thought just occurred to me... in which AWS region do your SQS queues exist? Basket is in us-west-2 and eu-west-1. If you're in one of those, then great, if not then we should just post the above JSON to an HTTP endpoint on basket.m.o. Apologies for the churn.

**Comment by cadecairos** [comment]
@pmac no worries, I can easily set up the queue in us-west-2, and modify the iam policies.

As for recurring donation, we only have monthly donations, so we can hard code that value when we're looking at a recurring donation.

Not sure why donation_amount is a string, ill confirm whether or not I can pass it as a number type

**Comment by cadecairos** [comment]
So it doesn't look like this will happen today, too much left to figure out and implement.

We still need to:
- Determine if we're enabling multi-currency on SF
- have donate submit donor infomation to a message queue
- have basket consume the data from donate (VIA the message queue above) and send it to salesforce.

Something we haven't considered: recurring charges for both paypal and stripe won't go into the Queue, because they aren't processed on donate.mozilla.org. We'll probably need to build a webhook for stripe subscription charges, and poll paypal (macro and micro) accounts to identify these charges.

**Comment by pmac** [comment]
> Something we haven't considered: recurring charges for both paypal and stripe won't go into the Queue, because they aren't processed on donate.mozilla.org. We'll probably need to build a webhook for stripe subscription charges, and poll paypal (macro and micro) accounts to identify these charges.

Unless someone objects I think that can be a v2 thing. My understanding is that this integration is all about us avoiding sending donation solicitation email to existing donors. We should be able to accomplish that with this simple message queue. If we need to integrate with the payment processors, then we can just go with that fully and forget the pings from donate.m.o.

**Comment by ScottDowne** [comment]
Hm, I think the only thing around recurring charges that we'll need to consider is if people cancel/update their amount. Would it make sense to have donate listen for that webhook then pass it to basket? Dunno if there would be advantages or disadvantages there.

**Comment by pmac** [comment]
Hopefully we can hash this all out in a meeting soon. But I'm hoping that changes after the initial donation won't matter since the idea is to avoid bothering people who've donated. If they change the amount or cancel then I'd think we would still want to avoid bothering them, and the payment processors will always be the source of record for these data. I don't think we have much hope of keeping this info perfectly in sync on the Salesforce side.

**Comment by ScottDowne** [comment]
@pmac that's a good point. I think that actually works and makes sense.

**Comment by ScottDowne** [comment]
Just an update:

@pmac @cadecairos We decided a few things, don't need to be final, but it sounds like we're agreeing and worth pushing forward.

We're going to send frequency as a string, with "monthly", "yearly", etc. For now this is just going to be monthly. Another field for recurring, which is true or false.

example data: `{recurring: true, frequency: "monthly"} vs {recurring: false}`

We also talked about amount being in the currency, storing the currency code as a string.

and another field, if we can get it, of the actual amount we got, after fees, and conversion rate, in USD, if possible. (not sure if paypal or stripe support this, would be great if it did)

**Comment by ScottDowne** [comment]
This _looks_ like we can get balance data from a transaction id. https://stripe.com/docs/api#balance_transaction_object

Not sure about paypal yet.

**Comment by ScottDowne** [comment]
We also talked about storing what service (paypal vs stripe) and the transaction id so we can link it back.

**Comment by ScottDowne** [comment]
Annnd, source url!

**Comment by cadecairos** [comment]
@pmac Here's the what the message payload looks like (recurring and single) 

https://gist.github.com/cadecairos/e66ab0a4c0bd0e1fdab2ba352905ae2d

**Comment by cadecairos** [comment]
Let me know if we should modify it in any way, otherwise I'll go ahead and merge mozilla/donate.mozilla.org#1646

**Comment by pmac** [comment]
@cadecairos looks perfect to me. I'll let you know if I run into issues during the implementation.

**Comment by cadecairos** [comment]
Donate.mozilla.org is now sending donation information into an SQS queue for consumption by basket.

**Comment by Matt-Holland** [comment]
@cadecairos should this ticket be closed? From reading the comments it seems like there are multiple parts of what we want; maybe it's more correct to create separate issues for the non-P1 parts, and close this P1 ticket. What do you think?

**Comment by cadecairos** [comment]
Yes, this work is 100% completed 

🎉 🌮 🎉
