### ISSUE TITLE
post signup page is removing any query params

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#62]
Example: signups from https://advocacy.mozilla.org/en-US/encrypt/signup?test=test

Are actually redirected to https://advocacy.mozilla.org/en-US/encrypt/signup-complete

This is because we're not passing the params along when we do the react router context swap on this line.

https://github.com/mozilla/advocacy.mozilla.org/blob/master/src/pages/encrypt/signup.js#L28

I suspect it just needs to be changed to
`this.context.router.replace("/" + locale + '/encrypt/signup-complete' + window.location.search);`

**Comment by ScottDowne** [comment]
This is an issue if we want to be tracking specific campaign or snippet signups via UTM query params. Not sure how that's done.

In the case of signup-complete it removes the param, in the case of hybrid/etc it doesn't do a redirect and instead fires a signup event.

I think ideally we rely on the signup event, which is not fired from what I can tell when we do a redirect to signup-complete, then figure out how to filter signup events from inside google analytics.

We should be passing along any params with any redirects though anyway. That's probably something I broke when I did the react-router upgrade.

@alanmoo @simonwex thoughts?

**Comment by alanmoo** [comment]
Is there a specific method you have to call to fire a tracking event using the params? I feel like UTM params generally work in conjunction with page loads, but I haven't really worked with them before.

What are we trying to track in this case?

**Comment by ScottDowne** [comment]
I think it's this: https://github.com/mozilla/advocacy.mozilla.org/blob/master/src/components/encrypt-signup.js#L74

`ga.event({ category: "Signup", action: "Submitted the form" });`

In this case we want to track signups from other teams in Mozilla that are using our page to run campaigns. In general though, tracking signups based on a campaign would be nice.

I'm also not sure how much of a priority this is yet.

**Comment by ScottDowne** [comment]
This got fixed recently, mostly it was a cloudfront thing, if I recall correctly.
