### ISSUE TITLE
Build Spectacular Snippet

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#620]
Detailed description of work:
Design work happening in #400 

*Start date: December 12, 2016* 
*Due date: December 23, 2016* 

CC:

**Comment by Matt-Holland** [comment]
@ScottDowne will start building on Dec. 12, might be done by 23rd to have it done-done. That’s xmas weekend and then 26th and 27th to get review (need to check with Yrgos, MoCo dependency for signoff)

**Comment by ScottDowne** [comment]
Looks like https://github.com/MozillaFoundation/Advocacy/issues/400 has become the build ticket.

Going to close this one, and do my work in #400.
