### ISSUE TITLE
Build web page for NEW localized FAQ

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#621]
Detailed description of work:

See #394 
Build a static webpage and extract the strings in a .properties file, which will be then exposed on Pontoon & GitHub

*Start date: November 7, 2016* 
*Due date: November 30, 2016* 

CC: @TheoChevalier

**Comment by TheoChevalier** [comment]
To sum up the l10n plan on the technical side:
- Expose common strings into a .properties file in the en-US folder
- Create an additional file (.po or .xliff) per locale where we need custom strings, put this file in locale folders only (not in en-US), then make the page pick those additional files

Alternative plan if what we customize is really one or two strings for German and French:
- Expose common strings into a .properties file in the en-US folder
- Hardcode custom translations into the page, fr & de localizers will edit the page directly on GitHub

This way Scott won’t have to deal with different file formats

**Comment by TheoChevalier** [comment]
page is live, closing this one
 https://donate.mozilla.org/faq
