### ISSUE TITLE
Share test accounts for donation testing

### ISSUE THREAD

**Issue by roseregina** [MozillaFoundation/Advocacy#622]
Please share the test accounts for doing QA on the localized donation pages. 

*Start date: November 7, 2016* 
*Due date: November 10, 2016* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @stephaniemcv @ScottDowne

**Comment by ScottDowne** [comment]
@stephaniemcv @roseregina Here's our documentation on how to make a test donation: https://github.com/mozilla/donate.mozilla.org/blob/master/docs/QA_Checklist.md

It'll work on staging, which is here: https://donate.mofostaging.net/en-US/

**Comment by ScottDowne** [comment]
Close this if that worked.

I'm pretty sure emails are not sent from staging, but might be wrong. So the only way to currently test that is an actual donation, which kinda sucks.

**Comment by ScottDowne** [comment]
Closing, ping me if you have any questions about this.
