### ISSUE TITLE
Design a joyful / delightful post-donation Thank You page? gif? experience?

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#623]
Detailed description of work:
We want to delight users with a Thank you (animation? Gif?). 

We had a rich brainstorm back in October and the notes from that are here:
https://docs.google.com/document/d/1XlgGt1xUe-vwfzHirm7U6IoqumQmhVLuyfxdv-wpk4k/edit

There might be creative fodder here: #247 

@vojtechmzl is also testing the post-donation flow to optimize for email opt-in (could be a separate step from Thank You, or could be incorporated as a fun ask on the page... e.g. "We don't want you to miss out on news about the impact of your gift, Andrea!"

*Start date: November 6, 2016* 
*Due date: November 30, 2016* 

The existing page:
![donate_mozilla_org___give_to_mozilla_today](https://cloud.githubusercontent.com/assets/9830371/20075574/93490854-a4e9-11e6-8760-f886a006c550.png)

CC:

**Comment by lovegushwa** [comment]
So to test the flow go to:
http://donate.mofostaging.net/

And use:
https://github.com/mozilla/donate.mozilla.org/blob/master/docs/QA_Checklist.md

**Comment by lovegushwa** [comment]
@ScottDowne should we include the users name in the design (re. #362 )

**Comment by lovegushwa** [comment]
@beccaklam you can see the current thank you page here: donate.mozilla.org/thank-you
Download the artwork here: https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlveW9zckJ0WFBla0k/view?usp=sharing

**Comment by ScottDowne** [comment]
@lovegushwa yes, we should add the user's name. Functionality for that is there.

**Comment by vojtechsedlak** [comment]
@beccaklam @lovegushwa I was just chatting with Paul about possibly running some tests around the share buttons on the thank you page and we were wondering if they could be featured more prominently than they are now? Currently, the share buttons only appear if someone signs up for email updates, which limits their exposure quite a bit. Having them maybe featured alongside the sign up ask would help with that.

Also, could we add Share by email to the share CTAs, alongside Facebook and Twitter? 

Hope this doesn't mess with the UX too much. Please let me know if you have any questions.

Thanks!

**Comment by beccaklam** [comment]
@vojtechmzl What would someone be sharing if they clicked the share buttons? CC:@lovegushwa

**Comment by vojtechsedlak** [comment]
@beccaklam They would be sharing the donate.mozilla.org page. We are hoping to run some tests using ShareProgress, which allows to test different share images and share copy.

**Comment by beccaklam** [comment]
@vojtechmzl @lovegushwa Here are some options for the share as well as the new artwork for the donation page. Still WIP: https://redpen.io/p/muc5124775472158d5

**Comment by lovegushwa** [comment]
@beccaklam can we close this ticket?

**Comment by beccaklam** [comment]
@lovegushwa Not yet? Though the design is done. I just have to clean up my code and commit again. The ticket will close when the pull request merges with the master repo though. Also!
@vojtechmzl What did you and Paul envision the share e-mail to say in terms of Subject: and Body: ? Would the share need to be localized?

**Comment by HPaulJohnson** [comment]
@beccaklam here is the copy we can use for the email share option on the thank you page: 

Subject: Join me in supporting Mozilla

Body: I donated to Mozilla today because I love the Internet! Mozilla, the maker of Firefox, is a non-profit and relies on donations for support. Join me and help protect the Internet as a global public resource: https://donate.mozilla.org

@TheoChevalier can you help get the above localized?

**Comment by TheoChevalier** [comment]
@beccaklam do you know if we can have HTML markup in the localized string, i.e. `<a href="https://donate.mozilla.org">https://donate.mozilla.org</a>` in the body string, or it has to be plain text? I assume plain text since not all email clients are sending HTML emails?

**Comment by WillatMozFdn** [comment]
@TheoChevalier I think you're right, the body string will not accommodate HTML markup, since it uses the mailto: tag and the encoding for any HTML characters is likely to futz up that link.  So, I would assume plain text only on this one, based on my experience with ShareProgress.

**Comment by TheoChevalier** [comment]
Thanks Will! Yeah, let’s play it safe 🚨

**Comment by Matt-Holland** [comment]
@TheoChevalier is this ticket complete now? Do you know?

**Comment by ScottDowne** [comment]
Not sure what this is waiting on, but the page is done and the test can be run. @vojtechmzl anything  missing on your end?

**Comment by vojtechsedlak** [comment]
The test is currently running, so good to close this ticket. The results will be tracked #601.
