### ISSUE TITLE
Currency select layout could be improved for locales with a long title

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/Advocacy#624]
Example with Italian:
<img width="455" alt="capture d ecran 2016-11-08 a 20 03 21" src="https://cloud.githubusercontent.com/assets/1294206/20115023/960ca144-a5ee-11e6-9824-65a1ec5a471d.png">

Not a blocker, but we could give it some love by moving the currency select in a better way.

**Comment by flodolo** [comment]
Even something like this would look nicer (`padding.right: 115px` on the `<h3>`, `position: absolute; top: 0; right: 0;` for the `<span>`)

![screenshot 2016-11-08 21 22 50](https://cloud.githubusercontent.com/assets/3644868/20115704/9429d29c-a5f9-11e6-8e2e-88d7bba3743d.png)

**Comment by TheoChevalier** [comment]
Actually, there’s already an open issue for that (#373)
