### ISSUE TITLE
Design email graphics based on the new EOY designs 

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#626]
Detailed description of work:
 
Design work happening here: https://github.com/MozillaFoundation/Advocacy/issues/606

@stephaniemcv can provide direction (e.g. existing templates and dimensions for email graphics)

We want to send a test with different designs to a segment of our list (EN) to see if there's a winner for our email audience in terms of conversion and $$ raised.

We may just want to do this as part of our message 1 send.

*Start date: November 11, 2016* 
*Due date: November 15, 2016*

**Comment by stephaniemcv** [comment]
Images work well in email when the reader understands that it is a "button". And we will need text on the image to help convey that. My recommendation is "donate" or "give".

In terms of templates we do have a mobile responsive 2 column. Image is 250x250.
![mofo-advo-template-2column-desktop-250x250px](https://cloud.githubusercontent.com/assets/11812272/20225600/7960579c-a801-11e6-934f-e8a26c21ecd8.jpg)
![mofo-advo-template-2column-mobile-250x250px](https://cloud.githubusercontent.com/assets/11812272/20225601/7960b822-a801-11e6-86c5-edb036337e63.jpg)

Full width banners also need to convey button. The play button got 20% more clicks than the "Watch the Video" button. This template image is 600x300.

![mofo-advo-template-1column-desktop-600x300px](https://cloud.githubusercontent.com/assets/11812272/20225719/1a140544-a802-11e6-9a71-d62b54354cef.jpg)
![mofo-advo-template-1column-mobile-600x300px](https://cloud.githubusercontent.com/assets/11812272/20225718/1a13bfe4-a802-11e6-951b-e0483c3c14e4.jpg)

We can also experiment with depth of images. In the Codemoji email, this image still received a lot of clicks, though it wasn't as high as the button in the email. Image is 600x70.

![mofo-advo-template-1column-desktop-600x70px](https://cloud.githubusercontent.com/assets/11812272/20225805/82a4de26-a802-11e6-8a21-908ce37fa671.jpg)
![mofo-advo-template-1column-mobile-600x70px](https://cloud.githubusercontent.com/assets/11812272/20225806/82a4fdfc-a802-11e6-9bf5-a80605195a3d.jpg)

I am very excited about the possibility of animated gifs you showed me the other day!

**Comment by TheoChevalier** [comment]
> Images work well in email when the reader understands that it is a "button". And we will need text on the image to help convey that. My recommendation is "donate" or "give".

Just keep in mind that if we localize it, we will need more space. For instance "Donate" in Italian will be something like "Fai una donazione"

**Comment by lovegushwa** [comment]
@stephaniemcv a few questions:

> Can we stick with the smaller square image / template for all fundraising emails? 
> Do we have email callout copy written already?

**Comment by lovegushwa** [comment]
Last years email callouts. @stephaniemcv do we have data for any tests we ran here?

1.
![eoytilesupdated_final_v1](https://cloud.githubusercontent.com/assets/12228435/20277622/2a1dae62-aa56-11e6-9516-56f5c3d45ac7.png)

2.
![eoytilesupdated_final_v2-2](https://cloud.githubusercontent.com/assets/12228435/20277625/2f3c6550-aa56-11e6-94db-e34c11701eec.png)

3.
![eoytilesupdated_final_v2-3](https://cloud.githubusercontent.com/assets/12228435/20277630/3360e840-aa56-11e6-9827-ae5049e79eea.png)

4.
![eoytilesupdated_final_v2-4](https://cloud.githubusercontent.com/assets/12228435/20277634/382ed8a0-aa56-11e6-9685-3a3f7e1c1ab6.png)

5.
![eoytilesupdated_final_v2-5](https://cloud.githubusercontent.com/assets/12228435/20277640/3c757c8e-aa56-11e6-98bb-21c8e777d006.png)

6.
![eoytilesupdated_final_v2-6](https://cloud.githubusercontent.com/assets/12228435/20277642/406d6dc4-aa56-11e6-8787-ff203327ff64.png)

7.
![eoytilesupdated_final_v2-7](https://cloud.githubusercontent.com/assets/12228435/20277646/443574ce-aa56-11e6-940b-cd2a4209926b.png)

8.
![eoytilesupdated_final_v2-8](https://cloud.githubusercontent.com/assets/12228435/20277648/48c1b3b8-aa56-11e6-8a53-14fbda9aab2e.png)

**Comment by lovegushwa** [comment]
Also last years tiles ... we have translation in DE, ES, FR, and IT for these titles:

Each Designs had a static and active state:
A.
![eoy_2015_v1-static_en](https://cloud.githubusercontent.com/assets/12228435/20277792/e242e8ea-aa56-11e6-93e1-f428f98c03a1.png)
![eoy_2015_v1-rollover_en](https://cloud.githubusercontent.com/assets/12228435/20277795/e768fc10-aa56-11e6-9375-1fc52e396e1f.png)


B.
![eoy_2015_v2-static_en](https://cloud.githubusercontent.com/assets/12228435/20277799/edfcff90-aa56-11e6-84a2-db59b3bb6e2d.png)
![eoy_2015_v2-rollover_en](https://cloud.githubusercontent.com/assets/12228435/20277805/f5a3a136-aa56-11e6-9c4c-3de541f2dbbb.png)

**Comment by lovegushwa** [comment]
Ok here is a baseline I think we should run with:

A.
<img width="600" alt="eoy_email_2016-05" src="https://cloud.githubusercontent.com/assets/12228435/20284546/71c8bfa6-aa72-11e6-800a-bc5a603130cb.png">

B.
<img width="600" alt="eoy_email_2016-01" src="https://cloud.githubusercontent.com/assets/12228435/20284549/777c26c2-aa72-11e6-9394-1f5da01c1709.png">

C.
<img width="600" alt="eoy_email_2016-04" src="https://cloud.githubusercontent.com/assets/12228435/20284560/80f104d4-aa72-11e6-9fe4-24f88e35c8cc.png">

D.
<img width="600" alt="eoy_email_2016-06" src="https://cloud.githubusercontent.com/assets/12228435/20287398/16d5c922-aa81-11e6-9de1-c7024a96af1d.png">

E.
<img width="600" alt="eoy_email_2016-02" src="https://cloud.githubusercontent.com/assets/12228435/20284565/85a4aab2-aa72-11e6-8710-24d730dbcca4.png">

F.
<img width="600" alt="eoy_email_2016-03" src="https://cloud.githubusercontent.com/assets/12228435/20284580/92b2ad80-aa72-11e6-981f-185857c6ddf4.png">

**Comment by lovegushwa** [comment]
Ok, so @stephaniemcv needs two callouts for localized email. 
Let's localize A. and B. in ES, IT, DE, FR ... oh and A is already localized from last year :)
B we will remove the "deadline december 31"

**Comment by TheoChevalier** [comment]
> A is already localized from last year :)
I’m curious about who localized it, and where is it stored?

**Comment by stephaniemcv** [comment]
@TheoChevalier I think it was Kontextor.

**Comment by TheoChevalier** [comment]
@stephaniemcv Alright, then we definitely need a review by the community

**Comment by stephaniemcv** [comment]
I'm confused. We had the text and used it last year in the campaign? The goal of reusing is so we can build the emails quickly since we're running out of time :-(

**Comment by stephaniemcv** [comment]
btw here's production spreadsheet
https://docs.google.com/spreadsheets/d/1lCpUiBe5B19SASA53CRpkzTK7hrBnxRANTT0kkRZDGo/edit?ts=57e1f3b0#gid=4

**Comment by TheoChevalier** [comment]
@stephaniemcv We’re trying to heal our relation with our localizers. Sending Kontextor translations without any review nor warning won’t help us here. It’s not because we did this mistake once that it’s okay to do it again :/

I’m sorry if I haven’t been clear about that, but we should stop sending anything that has not been properly reviewed, including past translations. I understand we’re very late for this email, so if you need to send it today, please proceed, but I need to know the full list of locales so that I can warn localizers. And if we have more content ready for the next email, please send it my way and I will get it reviewed quickly (even one day or two is better than nothing)

**Comment by stephaniemcv** [comment]
Ahah. Thanks, @TheoChevalier, that gives me better context about the situation. I would prefer to proceed in a way that heals, not harms.

And my apologies for not being clear, there's no email this week. But I'll push to try and package the content for the first email send next week (fingers crossed) that has copy and image w/ text to you for the DE, FR, ES localizers ASAP.

**Comment by lovegushwa** [comment]
@TheoChevalier please review the translated email callouts for A here:
https://drive.google.com/drive/folders/0B2qu3ExKWIlvMGlPQ3NZcWRWOXc?usp=sharing

**Comment by lovegushwa** [comment]
@valianttry can you review the copy / callouts above so I can wrap these up ... !? :)

**Comment by TheoChevalier** [comment]
@lovegushwa Asked localizers for feedback, hopefully this should be okay (and moved the assets where they can have access https://drive.google.com/drive/folders/0B8po55rC8WGXd0tocEc5a0lPc2c )

**Comment by lovegushwa** [comment]
@TheoChevalier thank you! ... This is the copy we need translated for the other localized email callout.
<img width="408" alt="screen shot 2016-11-14 at 4 51 24 pm" src="https://cloud.githubusercontent.com/assets/12228435/20288780/b215be52-aa8a-11e6-87c6-66cae2d026bd.png">

**Comment by TheoChevalier** [comment]
@lovegushwa roger that, thanks! @stephaniemcv Is the second email callout already localized as well, or needs to? Actually, we might want to update the spreadsheet directly with what need to be localized, what need to be reviewed, and for which locales.
For instance, Italian is missing from the spreadsheet, so I’m a bit confused

**Comment by lovegushwa** [comment]
@TheoChevalier so just for the sake of clarity, we need the graphic in this post localized, and the other version already localized reviewed  https://drive.google.com/drive/folders/0B8po55rC8WGXd0tocEc5a0lPc2c . Languages should be DE, FR, IT, ES, EN. Thats all we need for email callouts! 
<img width="408" alt="screen shot 2016-11-14 at 4 51 24 pm" src="https://cloud.githubusercontent.com/assets/12228435/20289466/ed5adb38-aa8e-11e6-9c21-ed3a95a7547d.png">

**Comment by TheoChevalier** [comment]
@lovegushwa feedback from German localizer:

> For German, it should be „Spenden Sie vor dem 31. Dezember“ (or maybe
> „Spenden Sie bis zum 31. Dezember“ (up until December 31)).

Italian and French are ok, still waiting for Spanish

**Comment by TheoChevalier** [comment]
Spanish looks good too, so only German need to be updated. 

I will expose the other callout when we have the final copy for the localized emails

**Comment by lovegushwa** [comment]
Excellent, thank you @TheoChevalier

**Comment by lovegushwa** [comment]
@stephaniemcv @HPaulJohnson here is a set of six final EN email callouts.
https://drive.google.com/drive/folders/0B2qu3ExKWIlvcnF4R2IybUpWQ0E?usp=sharing

**Comment by lovegushwa** [comment]
@stephaniemcv @HPaulJohnson here is the first set of localized callouts in ES, IT, DE, FR. "Support Mozilla, Give before December 31"  
https://drive.google.com/drive/folders/0B2qu3ExKWIlvZ19xd0NJU2FISUk?usp=sharing
