### ISSUE TITLE
Kount Rules - define some variables

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#628]
Detailed description of work: Replicate some rules from Kount into Stripe's Radar to improve fraud detection.
@ScottDowne could you please go through and define what some of the rules are?
https://docs.google.com/document/d/1ks8Sh6lTGi_FpcxwPj6gzk1REXR6BG-zNmrjn5QpA48/edit

*Start date: November 14, 2016* 
*Due date: November 18, 2016* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @cadecairos @roseregina

**Comment by ScottDowne** [comment]
@cadecairos reported our percentage is now below 1%.

I think I'm just going to close this. I don't think the Kount stuff was all that useful anyway.

**Comment by roseregina** [comment]
does this mean that our kount meeting for later today is cancelled? @stephaniemcv

**Comment by ScottDowne** [comment]
We could probably cancel it, yeah, unless @cadecairos was pulling one over on me.

**Comment by stephaniemcv** [comment]
I'm ok with canceling today. Yay we're under 1%!
