### ISSUE TITLE
Design social graphics for EOY

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Advocacy#631]
Detailed description of work:
Finalize social share images for facebook and twitter. We will need native shares and post donation share imagery.

Copy is in #596 

Identity variations happening in #591 

*Start date: November 14, 2016
*Due date: November 16, 2016

CC: @lovegushwa @beccaklam @KevZawacki @HPaulJohnson

**Comment by natalieworth** [comment]
Original draft directions from myself and @beccaklam are in #606

**Comment by natalieworth** [comment]
https://drive.google.com/drive/u/1/folders/0BzuBOR2VJQqUU1FoVDc0UW9wTE0

**Comment by natalieworth** [comment]
Hey! I have the refined versions for social on redpen here: 
https://redpen.io/p/kx1eca386dff55cd06

There are 4 gif options at the bottom of the redpen (although the text based one will need some work still). If there are any flags just post it in the redpen doc and I can update. I'll then add the final file exports to the drive and link to the content google document for social.

cc @KevZawacki @HPaulJohnson  @lovegushwa @beccaklam

**Comment by HPaulJohnson** [comment]
FYI re: localized social. To manage the # of requests we didn't send all of the versions to localization. To see which versions are being localized see ticket #634 

cc: @KevZawacki

**Comment by natalieworth** [comment]
Thanks @HPaulJohnson , I'll update based on those

**Comment by Matt-Holland** [comment]
Just cleaning up some of our open tickets -- I can't tell from this discussion if this work is complete or still ongoing. Can someone enlighten me?

**Comment by HPaulJohnson** [comment]
Done. Closing.
