### ISSUE TITLE
Desk.com Macro - Donor having technical problems during donation

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#632]
Detailed description of work: Need to refine a response that includes next actions to donors that email in and say they are having trouble donating. Things like "donation form is spinning but not progressing" "paypal gives me the 400 code", "Kapersky won't let me donate".

Here's what we have currently in response to Form Spinning:

Hello, 
I'm sorry you are having trouble with the donation form. We are seeing donations coming through normally, so it's difficult to pinpoint exactly why your donation attempt is failing. Please try these three things:

1. Try giving using this form one more time: https://donate.mozilla.org;
2. Turn off browser Add-ons and/ or try donating in a private browsing window; 
3. If your transaction still doesn't complete, please reply to this email and let us know exactly the error you see and we will try to help. Please feel free to include a screen shot. 

For other ways to give, such as by check, Bitcoin, Paypal or more, please visit our Ways to Give page: https://wiki.mozilla.org/Ways_to_Give

Thank you so much, we do appreciate your support.

Regards, 
The Mozilla Fundraising Team

@ScottDowne @cadecairos any thoughts you'd add to this? We'll take your comments and work them in/refine.

*Start date: November 15, 2016* 
*Due date: November 30, 2016* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @roseregina

**Comment by roseregina** [comment]
With Kaspersky, I think that part of what is going on might be related to Safe Money. Here's a decent  explanation of what it is: http://support.kaspersky.com/11161

This means that I think we maybe need to tell people emailing about Kaspersky to add donate.mozilla.org to the approved list.

**Comment by HPaulJohnson** [comment]
@stephaniemcv can we close this one?

**Comment by stephaniemcv** [comment]
Sure.
