### ISSUE TITLE
Update Link(s) in Saw Mill Donor Confirmation

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#633]
Detailed description of work: In the Saw Mill donor confirmation, the link to Donor FAQ and "respond within 48 hours" text needs to be updated with new url #621 and "respond within 72 hours".
![saw-mill-donation-confirm-11152016](https://cloud.githubusercontent.com/assets/11812272/20329225/37b08848-ab54-11e6-99d7-d7d1d4e92cf2.jpg)

*Start date: November 15, 2016* 
*Due date: December 1, 2016* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @roseregina

**Comment by cadecairos** [comment]
The 72 hrs fix is live on production now.

**Comment by Matt-Holland** [comment]
@ScottDowne  @cadecairos  is the changed link to the FAQ live now also? Can we close this ticket?

**Comment by Matt-Holland** [comment]
Re-sending question: @ScottDowne @cadecairos is the changed link to the FAQ live now also? Can we close this ticket?

**Comment by ScottDowne** [comment]
@Matt-Holland No, sorry not yet. I can do this ASAP, and I think get @cadecairos to ship it.

**Comment by ScottDowne** [comment]
Fixing in https://github.com/mozilla/webmaker-mailroom/pull/56

**Comment by cadecairos** [comment]
@Matt-Holland @ScottDowne FAQ link update is live on production

**Comment by ScottDowne** [comment]
Closing.

**Comment by Matt-Holland** [comment]
I see that this link is now included in the donation receipts I'm receiving. Closing this ticket.
