### ISSUE TITLE
Localize EOY Social

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#634]
Detailed description of work: Localize social posts in all of the target locales for EOY fundraising

*Start date: November 15, 2016* 
*Due date: November 28, 2016* 

CC:

**Comment by HPaulJohnson** [comment]
@TheoChevalier here is the final copy to be localized. please let me know if you have any questions.

https://docs.google.com/a/mozilla.com/document/d/1VLghfZCPazJr_IEfj7dFweOO3zN7Hk5qip4XjfIdSXE/edit?usp=sharing

Also, going to assign this ticket to you.

**Comment by TheoChevalier** [comment]
@HPaulJohnson Thanks! I have a few questions:
Are all the posts going to be used as tweets (as well as fb posts)? You’ve set the limit to 140 characters, but with a link, the limit is actually 116 characters for l10n, and some strings are already 139 characters long.
Also, when it’s a link + an image it’s even less I think (I don’t think this has changed with recent Twitter modifications around character count, but I might be wrong)
Let’s also not forget that some locales like French and German have a high expansion rate (around 20-30%), so it will be hard not to remove some of the meaning.
Could you help clarify which ones will be used as localized tweets?

**Comment by HPaulJohnson** [comment]
Good, call @TheoChevalier. I've shortened or removed anything longer than 116 chars. The image no longer impacts max char length but the URL will; we'll be using a short link like mzl.la/donate. I've tested all of these with that link and image and they work. 

Our general approach is to write posts that will work across both FB and twitter. Realizing that l10n will lengthen many/most, I'm hopeful that we are enough under that these will all work as both FB posts and tweets. If there are some that cannot be shortened enough for Twitter we can just use those on FB.

**Comment by TheoChevalier** [comment]
@HPaulJohnson perfect, thank you!
Last thing to confirm is the list of locales. On the localization plan I see en-GB, de, es, fr, pt-BR. Is that correct? I.e. we don’t want nl & it?
https://docs.google.com/spreadsheets/d/1TGJWL6OgPqeQj9otd1GKfd9DWBlZpXp2uUC-zYs6VAc/edit#gid=0

**Comment by HPaulJohnson** [comment]
@TheoChevalier I don't see why we wouldn't also do NL and IT as well. I'll update the spreadsheet to reflect that assuming it's not a big, additional effort for l10n. The more the merrier!

**Comment by TheoChevalier** [comment]
Thanks again :) I think we’re all set \o/ I’ll expose the strings tomorrow (already quite late here)
And no, no additional effort on my side, as long as we’re using those translations, it’s fine

**Comment by TheoChevalier** [comment]
Completion can be tracked here (updated every ~15 min) https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=social/2016/fundraising.lang (locales in white are complete)

**Comment by TheoChevalier** [comment]
All locales (except en-GB) are complete and can be found here:

https://l10n.mozilla-community.org/langchecker/?website=6&file=social/2016/fundraising.lang&action=translate&show
