### ISSUE TITLE
Implement Share Progress on post-donation Share page

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#635]
Detailed description of work: On the social share page - donate.mozilla.org/share - we want to do some testing/optimization using Share Progress tool. 

If possible we should also include an Email share option on this page along with existing Facebook and Twitter share options, based on how well email has performed in previous testing. 

*Start date: November 15, 2016* 
*Due date: December 2, 2016* 

CC: @ScottDowne @vojtechmzl

**Comment by HPaulJohnson** [comment]
@ScottDowne I will setup the tests in Share Progress and provide code snippet that can be embedded in the buttons on the existing page. Let me know if you have any questions or concerns based on our previous implementations of this functionality.

**Comment by HPaulJohnson** [comment]
@lovegushwa @natalieworth we can probably accomodate 2-3 tests in the post-donate share CTA. this can include copy and images. @vojtechmzl and I discussed redoing some of our previous testing from paid to start with. This would include: 
- Photo treatment
- Pizza cat
- Heart treatment

For photo and heart, can you drop in any final designs when you complete them for ticket #631 here?

**Comment by HPaulJohnson** [comment]
@ScottDowne I've setup the Share Progress buttons so we can do some testing on the thank-you page. For now, these are just in English so let me know if that's an issue. This is a P2 so let me know if you have capacity to implement or whether we should move this out to a later milestone. 

First, we will need to enable Share Progress on the Thankyou page with this code: 

`<script src="//c.shpg.org/352/sp.js"></script>`

Then, for the buttons here is the code snippet for each button type: 
Email:
`<div class='sp_177234 sp_em_small' ></div>`

Facebook:
`<div class='sp_177235 sp_fb_small' ></div>`

Twitter:
`<div class='sp_177236 sp_tw_small' ></div>`

**Comment by HPaulJohnson** [comment]
one additional thing to support the testing of the images that get shared via Facebook. I need a URL where the images are hosted, preferably on the donate site. I have the default one we are currently using but have two additional ones that need to be hosted. They are

![eoypizzacat](https://cloud.githubusercontent.com/assets/10078715/20693835/ecaed4de-b595-11e6-9e2e-ebd303d33150.jpg)
![eoyheart](https://cloud.githubusercontent.com/assets/10078715/20693844/f547b570-b595-11e6-9709-bcaff208feb2.jpg)

**Comment by ScottDowne** [comment]
@HPaulJohnson Links are up, that's all for tonight though:

https://donate.mozilla.org/assets/images/share-progress-heart.jpg
https://donate.mozilla.org/assets/images/share-progress-pizza-cat.jpg

**Comment by HPaulJohnson** [comment]
@ScottDowne thanks for the images, plugged them into the tests. 

Also, noticed that the existing default got changed to the heart. I thought we were keeping the existing image (person teaching from a laptop) as the control. Given we are testing heart and pizza cat would be great to have previous image - a photo - as the control if at all possible.

**Comment by ScottDowne** [comment]
@HPaulJohnson I'm not following this bit:

Also, noticed that the existing default got changed to the heart. I thought we were keeping the existing image (person teaching from a laptop) as the control. Given we are testing heart and pizza cat would be great to have previous image - a photo - as the control if at all possible.

**Comment by ScottDowne** [comment]
I'm not aware of any changes to the share image.

**Comment by HPaulJohnson** [comment]
This is the URL I had for the default image: 

https://donate.mozilla.org/assets/images/EOY_facebook_v1.a152496406bad899d1a920f6d6b9f507.png

When I looked earlier it had changed to the heart, and the Share Progress preview showed it as the heart. 

Seeing your note, I just went back in to verify and it's back to the original image. 

So, in the end, maybe I'm just crazy and it never changed. Everything should be good. Apologies for any confusion.

**Comment by ScottDowne** [comment]
@HPaulJohnson I think this is going to do it: https://github.com/mozilla/donate.mozilla.org/pull/1685

I have not yet merged. I want to sync up with you when I merge it, because locally I cannot test it, and I may need your help to quickly get it on production and test it there.

**Comment by ScottDowne** [comment]
Done. Being deployed now.
