### ISSUE TITLE
Broken chart on fundraising.mozilla.org

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/Advocacy#636]
looks like the chart is broken on https://fundraising.mozilla.org/ (Donors by source is empty, missing colors for countries)

 The web console is yelling:

>  Data request failed
>      charts.js:352:9	CHARTS.fetchData/request.onload https://fundraising.mozilla.org/wp-content/themes/OneMozilla-child/bower_components/mofo-eoy-charts/charts.js:352:9
> 	(Asynchrone : EventHandlerNonNull)
> 	CHARTS.fetchData https://fundraising.mozilla.org/wp-content/themes/OneMozilla-child/bower_components/mofo-eoy-charts/charts.js:347:5
> 	CHARTS.init https://fundraising.mozilla.org/wp-content/themes/OneMozilla-child/bower_components/mofo-eoy-charts/charts.js:302:5
> 	<anonyme> https://fundraising.mozilla.org/wp-content/themes/OneMozilla-child/js/ui.js:5:5
> 	<anonyme> https://fundraising.mozilla.org/wp-content/themes/OneMozilla-child/js/ui.js:1:2

**Comment by ScottDowne** [comment]
@vojtechmzl are the charts on the wiki something you are familiar with?

**Comment by vojtechsedlak** [comment]
Yup I am familiar with d3js. How can I get access to the site @ScottDowne ? I see it's in wordpress

**Comment by ScottDowne** [comment]
@vojtechmzl haha, I was hoping you knew how to get access.

**Comment by vojtechsedlak** [comment]
Ha, sadly I never got the keys to that one.

**Comment by ScottDowne** [comment]
@cadecairos master of keys, I present to you this problem in which I could probably solve slower and badlier than thou. You know how to give @vojtechmzl access to fundraising.mozilla.org site?

🔑 🔑 🗝 🗝 🎹 

Thanks :)

**Comment by TheoChevalier** [comment]
Thanks to whoever fixed this! I’m not sure the data is updated live nor this is this year’s data, but I’m not sure what it’s supposed to show either :)
