### ISSUE TITLE
What do to with faq and ways to give wiki pages

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#637]
We have a bunch of links in email templates and desk.com macros to articles on wiki.mozilla.org

https://wiki.mozilla.org/Ways_to_Give and https://wiki.mozilla.org/Donate

We're looking to replace these with links on donate.mozilla.org

So either we update links in the templates and macros, or we setup a redirect on the wiki, which ever is easier.

@stephaniemcv

**Comment by TheoChevalier** [comment]
As a first step, once https://github.com/mozilla/donate.mozilla.org/pull/1675 is in prod, should we replace content of the wiki pages with something like a big link “Please check out our new FAQ page”?

**Comment by stephaniemcv** [comment]
Yup. We'll use that as a stop gap until we can figure out a more permanent solution.

**Comment by TheoChevalier** [comment]
Updated the wiki, and the new link is now live on prod https://donate.mozilla.org/

**Comment by ScottDowne** [comment]
Think this is closable? @stephaniemcv @TheoChevalier

**Comment by stephaniemcv** [comment]
I think it is.
