### ISSUE TITLE
Embed video into localized landing pages

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#64]
Hi Simon,

Hoping you can embed the Spanish and German versions of video 2 into the respective landing pages. I believe you and Brett have chatted about this already. 

Here are links to the Spanish and German pages: 
https://advocacy.mozilla.org/es/encrypt/codemoji/2
https://advocacy.mozilla.org/de/encrypt/codemoji/2

@brettgaylor will share the localized videos shortly. 

Thanks!

CC @ScottDowne

**Comment by simonwex** [comment]
@brettgaylor and I chatted about me uploading some new vids, but this is a bit more than that. I think @alanmoo is the best to help out with this. 

I'm sending an email to both you and Brett for us to corral all the Scott-backfill work. I'd like to do this centrally to reduce the amount of PM work involved.

**Comment by damiankay** [comment]
Sounds good - thanks @simonwex 
@alanmoo, can we jump on a quick vidyo chat tomorrow to discuss details?

**Comment by ScottDowne** [comment]
Quick drive by for whoever does this, the key is these lines: https://github.com/mozilla/advocacy.mozilla.org/blob/master/src/components/encrypt-video.js#L76-L77

And checking the value of `this.context.intl.locale` and changing the video source as necessary.

Also consider cases where there isn't a video for that locale, we should always fallback to something we do have, probably English.

**Comment by alanmoo** [comment]
Merged and on staging. @damiankay Can this go live on production any time?

**Comment by damiankay** [comment]
Hey @alanmoo - we need to make a small change to the Spanish page HTML text before deploying to production. 
The copy: "Descubre el cifrado"
Should say: "Descubre senorita ciphrado"

Would it be possible to do this on Monday morning so that we can deploy Monday afternoon? 

Thanks!

https://advocacy.mozilla.org/es/encrypt/codemoji/2

**Comment by alanmoo** [comment]
Yup, I'll take care of that Monday.

**Comment by brettgaylor** [comment]
@alanmoo I don't know if this happens on Pontoon or is hard coded. Lets look into it on Monday but we shouldn't let it be a blocker.  Thanks for pinch hitting!

**Comment by brettgaylor** [comment]
Also, the text should be:

Te presentamos a la Señorita Cifrado

**Comment by ScottDowne** [comment]
If it's a correct translation it happens on pontoon. If it's a change to
the string it happens in the code but for English only.

**Comment by alanmoo** [comment]
Since the translated site was already live, I pushed the changes to support translated video into production. I also suggested a change for the text via the Pontoon UI (though I'm not clear on why I can't just change it in the repo.)

**Comment by ScottDowne** [comment]
I noticed a typo in my last post. I said incorrect when I meant correct.

Technically you can change strings right in the repo but we have no way of ensuring it's the correct translation. I also don't want to get into a habit where devs are pasting in strings from translators when we have a tool to do this.

**Comment by alanmoo** [comment]
@ScottDowne I get that and it totally makes sense, though given this is a slightly different case (it's a bit of a branding translation rather than just normal content), I merged it in manually. (I also wasn't sure how to get it approved via Pontoon, though I can get filled in on that another time).

**Comment by damiankay** [comment]
Thanks guys!

**Comment by ScottDowne** [comment]
@alanmoo @damiankay what is a branding translation?

**Comment by ScottDowne** [comment]
I worry a localizer might come in and see this translation as off and not know the context, and possibly "correct" it and revert the translation.

**Comment by damiankay** [comment]
Can we retroactively add the translation to Pontoon? Would that resolve the issue?

**Comment by ScottDowne** [comment]
Ideally we change the English string too to represent the branding and context, but I'm not really sure what we're trying to do with this. My knee jerk reaction is we shouldn't be doing this kind of translation the way we are. Sounds more like a swapping of content for a new locale, than a translation.

**Comment by ScottDowne** [comment]
Pontoon updates with the translation, once we manually merge it. So no need to retroactively add it.

**Comment by damiankay** [comment]
Ok. Let's get a few of us together to chat through the optimal process when you're back. I'd like to have a better understanding of best practices anyway.

**Comment by ScottDowne** [comment]
Generally a translated string is changed for two reasons.
1. The translation is incorrect from the English, and needs to be fixed.
2. The English string changed, and thus the translations also need to be changed.

So I worry we just changed this string to now trigger point number 1 there. Not sure though, as I'm still not confident I know what we're trying to do. When I look at the English string, it's stored as "Meet Encryption", if we're not confident that's what the string still saying after the change, then I suspect we need to figure something out.

It can probably wait until I'm back.

**Comment by damiankay** [comment]
@brettgaylor would be best qualified to answer whether it was an incorrect translation from English. My guess is that it was not incorrect, but that the new translation is more fitting in this context.

**Comment by alanmoo** [comment]
I think both the original and the new translation were technically correct, but the new one clarifies that we're presenting "Encryption" as a character, not just a concept. The phrase "Meet Encryption" is kind of ambiguous in English, the new translation is more specific. (It's went from 'Discover encryption' to 'We present Miss Encryption').

Language subtleties are weird.

**Comment by brettgaylor** [comment]
Correct!  It doesn't capture the idea that encryption is a character.

Scott - do you know if our process would be to insert our own translation
in Pontoon?  I wish i knew how Pontoon actually worked :)

**Comment by damiankay** [comment]
I'm going to organize a Pontoon training session when Scott is back (thanks in advance, @ScottDowne  ;-)
