### ISSUE TITLE
Design: Snippet test creative

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#640]
Create the following icons for snippet tests running the week of 12/3:

- Localized icons for DE and FR likely heart + a cultural symbol or reference to the flag
- Pixel heart icon
- Pixel heart animated .gif

@vojtechmzl missing anything here?

*Start date: November 22, 2016* 
*Due date: November  25, 2016* 

CC: @HPaulJohnson @vojtechmzl @natalieworth @beccaklam

**Comment by beccaklam** [comment]
@vojtechmzl What size should the snippets be? cc:@natalieworth

**Comment by natalieworth** [comment]
@beccaklam I think the usual size we have done in the past for the icon sizes on snippet were between 64 x 64px @ 2x (sometimes a little larger/ or they could be a rectangle too...I don't think they always have to be square)

**Comment by natalieworth** [comment]
@beccaklam also if you want to export your heart ones that you have already done, I could work on the DE/FR options for Friday

**Comment by beccaklam** [comment]
@natalieworth Thanks! Was just wondering because @lovegushwa said they might be testing some new sizes? <--@vojtechmzl And yes, I'll work on polishing the heart ones :)

**Comment by vojtechsedlak** [comment]
@beccaklam Good question. We're currently testing 32x32px vs 64x64px, so we may scale things down if the we see that the smaller one ends up performing better.

**Comment by beccaklam** [comment]
@natalie @vojtechmzl @lovegushwa Put Pixel heart icon and Pixel heart animated .gif in this folder on the drive: https://drive.google.com/open?id=0BzuBOR2VJQqUX1N5Szh6T2IzNVE

**Comment by natalieworth** [comment]
@beccaklam @vojtechmzl @lovegushwa put options for localized test icons here: https://redpen.io/p/en58751ffb0c169cd3

**Comment by natalieworth** [comment]
Uploaded the snippet icon version files here: https://drive.google.com/drive/u/1/folders/0BzuBOR2VJQqUX1N5Szh6T2IzNVE

There are a FR and DE animated version for each flag. I also included an alternate version of an icon for FR of the Eiffel Tower as another option if we want to test it against the DE animated flag option.

@lovegushwa @beccaklam @vojtechmzl

**Comment by natalieworth** [comment]
@vojtechmzl Do you know if we shipped these to the snippet team yet? I was also hoping to add to this for testing (if it's not too late)

1. DE animated flag vs. FR animated flag icons:
https://drive.google.com/file/d/0B20-0lpP23c0ZVZ6SW56WEM1Z28/view
https://drive.google.com/file/d/0B20-0lpP23c0SHFPeTJ1QlBoWXc/view

2. DE flag vs. FR Eiffel Tower icons:
https://drive.google.com/file/d/0B20-0lpP23c0ZVZ6SW56WEM1Z28/view
https://drive.google.com/file/d/0B20-0lpP23c0SVJKZHoxa19HU3c/view

3. DE pixel heart vs. FR pixel heart:
https://drive.google.com/file/d/0B20-0lpP23c0ZllaTmY2djhkWlU/view
https://drive.google.com/file/d/0B20-0lpP23c0dkxkNmI0ZThGbm8/view

Thanks! :) cc @lovegushwa @beccaklam

**Comment by vojtechsedlak** [comment]
Just to recap the results here, animated icons won across the board, with beating heart winning in the EN locale and with waving flag gifs winning in DE and FR locales over static variants.

**Comment by natalieworth** [comment]
Thanks @vojtechmzl :) The animated ones were my preference so glad they won! Closing this ticket but feel free to reopen if anything else has to be included in this.
