### ISSUE TITLE
Support longer translations for donate button on snippet

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/Advocacy#643]
We’re going to support Italian next week, and the button is probably going to be “Fai una donazione”, which does not fit great in the current button:

<img width="501" alt="capture d ecran 2016-11-23 a 23 49 14" src="https://cloud.githubusercontent.com/assets/1294206/20585272/c7a2d02a-b1f1-11e6-9d3e-f48c9d51b21e.png">
 
 
But it is a lot better with `padding: 7px 4px` instead of `padding: 7px 0`:
<img width="574" alt="capture d ecran 2016-11-23 a 23 48 45" src="https://cloud.githubusercontent.com/assets/1294206/20585276/cd488a42-b1f1-11e6-9ab2-95163c29cdb5.png">

I think we should make this change in advance, so that we’re good to go next week once we have the translation.
@ScottDowne does that look like a good enough fix?

**Comment by ScottDowne** [comment]
Yeah that looks good to me.

**Comment by TheoChevalier** [comment]
Thanks, opened https://github.com/mozmar/snippets/pull/94
