### ISSUE TITLE
Design a mobile version of snippet

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#645]
Detailed description of work: We need modified copy and resized image to run snippet in the mobile version of FF. 

*Start date: November 28, 2016* 
*Due date: December 1, 2016*

**Comment by HPaulJohnson** [comment]
Specs for mobile snippet are: Mobile snippet 100 character limit, icon size 96x96.

@lovegushwa can you create a version of heart icon that is 96x96?

For copy, we can use this modified version of existing snippet copy:
"Mozilla, the maker of Firefox, is a non-profit and we rely on donations for support. Donate now."

**Comment by lovegushwa** [comment]
@beccaklam can you make a version of the pixel heart at 96x96

**Comment by beccaklam** [comment]
@HPaulJohnson @lovegushwa Here are the icons, I've exported one at 1X and one at 2X: https://drive.google.com/open?id=0BzuBOR2VJQqUVnd4V1J3TC01ZGM

**Comment by HPaulJohnson** [comment]
@vojtechmzl can you provide me a tagged URL for use with the mobile snippet?

**Comment by vojtechsedlak** [comment]
@HPaulJohnson https://donate.mozilla.org/?utm_source=mobile-snippet&utm_medium=snippet&utm_campaign=EOY2016

**Comment by HPaulJohnson** [comment]
This is set to go-live today!

**Comment by HPaulJohnson** [comment]
@TheoChevalier Here is the copy we used for EN version of mobile snippet: 

"Mozilla, the maker of Firefox, is a non-profit and we rely on donations for support. Donate now."

It would be great to localize. The max char length is 100 so we may need to shorten the EN version to accommodate longer translations. Here are some options:

"Mozilla, the maker of Firefox, is a non-profit and we rely on donations. Donate now."

"Mozilla is a non-profit and we rely on donations for support. Donate now."

"Support Mozilla, the maker of Firefox. Donate now."

**Comment by TheoChevalier** [comment]
Thanks, Paul. I will expose the en-US version and suggest the variants in a comment. 
Assuming we want the same locales, i.e. de, fr, es, it, pt-BR, pl, ru (they are also the top locales on mobile)

**Comment by HPaulJohnson** [comment]
yes, let's go with the same locales.

**Comment by TheoChevalier** [comment]
Completion status can be tracked here https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=snippets/2016/dec2016_eoy_mob.lang

**Comment by TheoChevalier** [comment]
@vojtechmzl @HPaulJohnson Let’s ship de, fr, pl today https://l10n.mozilla-community.org/langchecker/?website=6&file=snippets/2016/dec2016_eoy_mob.lang&action=translate&show#string1

**Comment by TheoChevalier** [comment]
Forgot to close this, but localized versions are live https://snippets.mozilla.com/json-snippets/
