### ISSUE TITLE
Snippet copy variations for testing week of 12/12

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#646]
Detailed description of work: To continue testing/optimization of snippet, and to fight fatigue with existing snippet versions, we'd like to introduce a set of additional copy tests to run the week of 12/12-12/26. 

*Start date: November 28, 2016* 
*Due date: December 1, 2016* 

CC: @KevZawacki

**Comment by HPaulJohnson** [comment]
Initial directions to be tested with copy from [last week's brainstorm](https://docs.google.com/document/d/1Wq6_iDGpd2XC426N96357QE_4N6P5F3W5p83Dql5UGQ/edit?ts=58236f11) include: 

- Length
- Internet “Health Bar”
- Defend the Internet 
- Fight for the Internet 
- Quotes / Testimonials
- Stats

**Comment by HPaulJohnson** [comment]
I'll be working on copy for these here, hoping to have something by EOD tomorrow 11/29. 

https://docs.google.com/a/mozilla.com/document/d/1DKmv0N_P3NdOD8DR9iy7CmJ_pM8Mn1Jxo1zfTfqUmCA/edit?usp=sharing

**Comment by HPaulJohnson** [comment]
I put a bunch of options in the doc, mostly pulled/remixed from a bunch of existing content. Would love some feedback, edits, and input on what are the strongest tests. 

https://docs.google.com/document/d/1DKmv0N_P3NdOD8DR9iy7CmJ_pM8Mn1Jxo1zfTfqUmCA/edit#

@vojtechmzl @TheoChevalier @KevZawacki @lovegushwa @natalieworth @beccaklam can you take a look and let me know what you think?

**Comment by TheoChevalier** [comment]
Hey Paul, I really like them, and in my opinion the 3 “length” and the 2 “stats” copy are the strongest, they resonate with me as there are very concrete examples of what we’re doing. The length[A] copy is even better as it mentions Firefox, and is clear about donations not directly supporting Firefox. The copy is already quite long, but maybe we can tweak it to mention non-profit as well? Or that would be too much?
Also added a question about trolls (and just to be clear, I don’t see any other potential l10n issue)

**Comment by TheoChevalier** [comment]
Just received formal/informal German variants: https://docs.google.com/a/mozilla.com/document/d/10GV0ectp7oegUXP7XsevRdpCIeT5K5ZWz3Ti0ITnzIA/edit?usp=sharing

**Comment by vojtechsedlak** [comment]
These are great @HPaulJohnson!
I think the following versions best capture the given variant's attribute and could be evaluated in the big content framing showdown of EOY 2016.

Length - A
Health Bar - A
Defend - B
Fight - B
Stats - B

I am thinking whether we should only run this test only in EN and wait for the locale-specific test (#629) to conclude. @TheoChevalier, @HPaulJohnson what do you think?

**Comment by HPaulJohnson** [comment]
thanks, both. the only one i'm not totally "feeling" is the trolls version (health bar - A) so may swap it out. Otherwise, I'll submit this list (might throw in a few additional versions just to have some in our backpocket if we see fatigue) to snippet team for feedback. 

I think it makes sense to run these outside of EN only after the current testing has concluded.

**Comment by HPaulJohnson** [comment]
Here's what I sent to Wes tonight for review by the snippet team: 

https://docs.google.com/document/d/1bJALd39V4f-9NiM_KnkMKILNhlp6n-C83-j4Wg1DKWY/edit

Note, I tweaked the health bar one a bit and included an additional "Internet Meme" variation that we could use in conjunction with nyan cat. 

I'll let everyone know what feedback we get.

**Comment by HPaulJohnson** [comment]
Approved by snippet team!

@vojtechmzl when our next set of tests concludes we can put start getting these in the rotation.

**Comment by Matt-Holland** [comment]
@vojtechmzl  since the copy is approved, can I close this issue?

**Comment by vojtechsedlak** [comment]
Yup, we can close this issue. The new copy will go into circulation later today or tomorrow. Thanks!
