### ISSUE TITLE
Additional icon testing for snippet

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#647]
Detailed description of work: To continue testing/optimization of snippet, and to fight fatigue with existing snippet versions, we'd like to test additional snippet icons the week of 12/12

*Start date: November 28, 2016* 
*Due date: December 12, 2016*

**Comment by HPaulJohnson** [comment]
Note to @lovegushwa @natalieworth @beccaklam this ticket is time permitting given all the other design deliverables due this week. But, if there is additional time, coming out of[ last week's brainstorm](https://docs.google.com/document/d/1Wq6_iDGpd2XC426N96357QE_4N6P5F3W5p83Dql5UGQ/edit?ts=58236f11) we discussed a few additional icon possibilities that would be worth trying, including: 

- Thermostat
- Nyan cat
- Emoji

We are working on some copy variations in ticket #646 and we could combine these two, time permitting.

**Comment by lovegushwa** [comment]
Here is a set from @natalieworth https://redpen.io/p/bt51488c0998c42666
These can be selected from and exported as final icons post Hawaii

**Comment by HPaulJohnson** [comment]
These are great @natalieworth & @lovegushwa. The copy in ticket #646 was approved and will work well paired with some of these. Nyan cat, the raised fist and megaphone for example. Also would love to see us start testing with the Thermometer. 

We can prob go ahead and share these with Wes for feedback so we can get them in rotation week of 12/12.

**Comment by lovegushwa** [comment]
@natalieworth when you get a chance next week can you pull the icons Paul listed together to show Wes? (like we will send them to Wes with copy in a snippet mockup on redpen like this: https://redpen.io/p/qj4d60f2ac98a50591)

**Comment by lovegushwa** [comment]
Also just noticed this cool fist @beccaklam made for Makerparty, we could re-use it.

<img width="731" alt="screen shot 2016-12-03 at 3 40 32 pm" src="https://cloud.githubusercontent.com/assets/12228435/20862966/19abe116-b96f-11e6-9e57-3aa757a36fcb.png">

**Comment by natalieworth** [comment]
Hey @Matt-Holland , mocked up the above snippet icon recommendations from @HPaulJohnson here: https://redpen.io/p/mw03e76deeaa6689b1
cc @lovegushwa @beccaklam

**Comment by natalieworth** [comment]
@vojtechmzl I have the icons exported @2x here: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0QkRZTS0wU3hCc2s
Copy ticket from Paul is here (feel free to use whichever snippet team feels fits best): https://docs.google.com/document/d/1DKmv0N_P3NdOD8DR9iy7CmJ_pM8Mn1Jxo1zfTfqUmCA/edit
And my copy suggestion pairing can be found in the mock-ups on redpen here: https://redpen.io/p/mw03e76deeaa6689b1
cc @Matt-Holland @lovegushwa

**Comment by natalieworth** [comment]
@vojtechmzl @Matt-Holland I'm going to close this, but feel free to reopen if there are any issues from Wes with the snippet icons.
