### ISSUE TITLE
Design: Four callout boxes for testing in EOY fundraising email #2

### ISSUE THREAD

**Issue by WillatMozFdn** [MozillaFoundation/Advocacy#648]
Detailed description of work:  Our primary test for EOY fundraising email #2 will be four different callout box designs.  (The body of the email is a kicker/lift note on top of whatever wins the content test in email #1.)  Ideally, these designs are rather distinct from one another so we can hopefully get clear test results.

*Start date: November 29, 2016* 
*Due date: December 5, 2016* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @HPaulJohnson @lovegushwa @stephaniemcv @Matt-Holland 

(Hrmmmm ... I can't figure out how to add the "fundraising" and "email" labels here, is there a code trick for that?)

**Comment by lovegushwa** [comment]
We can choose from the selection here: https://drive.google.com/drive/folders/0B2qu3ExKWIlvb2FsbnNLU3RmQms?usp=sharing

Also we should consider testing this .giff
https://drive.google.com/a/mozilla.com/file/d/0BzuBOR2VJQqUa1F4bERvdnVZVFE/view?usp=sharing
