### ISSUE TITLE
Complete video localization

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#65]
Hi Brett,

Not sure about the details for this one! Just sending as a reminder. 

I'm assuming that this needs to be done before @simonwex can add the videos to the snippet. Please update issues #64 and  #66 when you've exported the final videos.

**Comment by simonwex** [comment]
@brettgaylor and I chatted about me uploading some new vids, but this is a bit more than that. I think @alanmoo is the best to help out with this. 

I'm sending an email to both you and Brett for us to corral all the Scott-backfill work. I'd like to do this centrally to reduce the amount of PM work involved.

**Comment by damiankay** [comment]
Hey Brett - when will you actually have the final video files? Is there anything I can help with?

**Comment by damiankay** [comment]
Hi again - just chatted with @alanmoo about this and we're hoping to do the following:
1. If you could please upload to the same location as the other videos that would be ideal. We might need @simonwex to upload the videos to the CDN, in which case the earlier we get these to him the better. 
2. When naming the video files, please use the same file name as the English videos, but append the locale ID to the end, I.e. "encrypt-video-2-es.mov" for Spanish (adding the "es" and "de").

**Comment by brettgaylor** [comment]
Got it.  Does anyone know what the final size needs to be for the snippet files though?  Compressing the ones for landing pages right now.

cc @ScottDowne @lovegushwa to see what those final snippet video dimensions where.

**Comment by brettgaylor** [comment]
OK @alanmoo @simonwex videos are compressed and available here:
https://drive.google.com/a/mozilla.com/folderview?id=0B0bF99sa1fRJbm15bkwxNk1XU2M&usp=sharing

Please upload to the amazonsssss!
