### ISSUE TITLE
Embed video into snippet

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#66]
Hi Simon,

Please embed the localized versions of Encryption video 2 into the snippet for the German and Spanish versions of Firefox. 

@brettgaylor will supply the videos shortly. I'm waiting for confirmation on the correct format. 

Thanks

CC @ScottDowne

**Comment by ScottDowne** [comment]
This is mostly a moco thing. You just give them the video files and translated copy for each locale, they set it up.

**Comment by brettgaylor** [comment]
Snippet videos are here
https://drive.google.com/a/mozilla.com/folderview?id=0B0bF99sa1fRJMmtXWmxsUEJHem8&usp=sharing

**Comment by damiankay** [comment]
Hi Natalie,

The MoCo snippet team require poster images from the Crypty video. If we've created poster images for the landing pages, I'd think that we can use the same ones. 

The dimensions need to be 341x192. I'm not sure of format, so perhaps create a JPG and a PNG? 

Would you be able to create these and send them to me early today? 

You can find the videos here:
https://drive.google.com/a/mozillafoundation.org/folderview?id=0B0bF99sa1fRJMmtXWmxsUEJHem8&usp=gmail#

Thanks!

**Comment by damiankay** [comment]
Hi Natalie - don't worry about it. @brettgaylor did it already. Thanks!

**Comment by ScottDowne** [comment]
This is done.
