### ISSUE TITLE
Email Thanks

### ISSUE THREAD

**Issue by Matt-Holland** [MozillaFoundation/Advocacy#663]
Detailed description of work:
All 2016 donor thank you
Thank you animated gif/video

*Start date: November 29, 2016* 
*Due date: January 4, 2017* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by lovegushwa** [comment]
@WillatMozFdn @stephaniemcv forgive the wait on this. You can get the emoji images here:
https://drive.google.com/drive/folders/0B2qu3ExKWIlvZ2hrMDRPeEtxb3M?usp=sharing

Blue button color #1381d5

<img width="678" alt="screen shot 2017-01-10 at 9 08 23 pm" src="https://cloud.githubusercontent.com/assets/12228435/21836541/cfde85d2-d77a-11e6-8566-4d28f0667606.png">

**Comment by hannahkane** [comment]
Triaging all open tickets. Can this ticket be closed?

**Comment by stephaniemcv** [comment]
Yes. Email was sent in January.
