### ISSUE TITLE
Go / No Go decision on Dev Edition

### ISSUE THREAD

**Issue by Matt-Holland** [MozillaFoundation/Advocacy#664]
Detailed description of work:

#392 

*Start date: December 12 2016* 
*Due date: December 13, 2016* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by ScottDowne** [comment]
I suspect how the spectacular snippet works out is going to be the primary factor on if we have time to do this or not.

**Comment by ScottDowne** [comment]
Pretty sure we're not doing this, because it might be a little too late in the game ;)
