### ISSUE TITLE
"Remember me" button in stripe check out 

### ISSUE THREAD

**Issue by roseregina** [MozillaFoundation/Advocacy#667]
Is it possible to remove the "remember  me" button on the second page of the donation form? It confuses some people and then stripe sends a text message and a couple donors have flipped out a little bit because they didn't understand what stripe is. 

example donor email:

> I just donated to you for the umpteenth time and it said " save my location 
> " . I checked yes , and know got a text from stripe.com saying they have my 
> credit card card info and do other organizations. What the heck is this ? 
> Call me to explain. Forget hiding behind the cloak of secrecy with only 
> online communication . 
> 

*Start date: December 1, 2016* 
*Due date: September 2, 2019* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @cadecairos @ScottDowne @stephaniemcv

**Comment by cadecairos** [comment]
Yes we can consider removing that option: 

```
data-allow-remember-me 	Specify whether to include the option to "Remember Me" for future purchases (true or false). The default is true.
```

(from [Stripe checkout docs](https://stripe.com/docs/checkout#optional))

**Comment by ScottDowne** [comment]
It's already on staging.

Should be on prod in a few minutes.

**Comment by ScottDowne** [comment]
Closing, being deployed now.

**Comment by roseregina** [comment]
awesome sauce. thank you.
