### ISSUE TITLE
Stripe decline indicator for donor

### ISSUE THREAD

**Issue by roseregina** [MozillaFoundation/Advocacy#668]
Is there any way for us to have stripe or sawmill send some kind of "your card has been declined" email or notification? I think it would clear up a certain amount of donor confusion about what is going on when that happens. A lot of people think they have donated and are confused and miffed when there is no acknowledgment. And if not, this is something that should get added to the next revision of the FAQ. 

<< Matt H. removed due dates since this is still be to prioritized >>

CC: @cadecairos @ScottDowne @stephaniemcv

**Comment by cadecairos** [comment]
They should see a message like this if the card is declined: 

![](https://i.imgur.com/BAVcuZA.png)

**Comment by cadecairos** [comment]
however, if we do block the charge on suspicion of fraud, they get no message it seems.

(try donating with the card # 4100000000000019 (all other data can be fake) on donate.mofostaging.net)

**Comment by cadecairos** [comment]
I'm checking if there's a webhook event for blocked charges

**Comment by roseregina** [comment]
ok, thank you. I'm on a bus for the next 9 or so hours, so I don't think that I'm going to be able to do it until this evening, but that is super helpful to know what should happen.

**Comment by cadecairos** [comment]
@roseregina if you're interested in seeing how the stripe form responds to various fail states, [this page is your friend](https://stripe.com/docs/testing#cards). Armed with that and https://donate.mofostaging.net, you can try to simulate the conditions that our donors might be reporting.

**Comment by roseregina** [comment]
@cadecairos awesome sauce. thank you

**Comment by roseregina** [comment]
possible more information on this: 
 Donor using Ubuntu Linux 16.04, browser is Firefox 50.0.2 reports:
> When I click "pay", I see this window (screenshot). After that this
> window closed fast and I'm back on "donate now" page. No error messages.
> I don't know what is the reason of problem.

![image](https://cloud.githubusercontent.com/assets/15040203/21064608/b9e54eba-be29-11e6-807a-76e4e2d4cf57.png)

stripe says: Payment declined by customer's bank. The bank did not return any further details with this decline.

(from CASE #17686)

**Comment by ScottDowne** [comment]
We are now properly displaying errors for anything cept legit fraud.

Example, this case below should now get an error message.

![](https://cloud.githubusercontent.com/assets/15040203/21064608/b9e54eba-be29-11e6-807a-76e4e2d4cf57.png)

I think the combination of Stripe's internal errors, and our custom error for what Stripe is missing, we can close this.

We can open more tickets around this if we come up specific ways to make it better.
