### ISSUE TITLE
EOY Bug: Post donate share buttons don't work

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#669]
Detailed description of work: After completing a donation, opt-in and landing on the share page, the Facebook and Twitter share buttons are not functional.

To recreate donate.mozilla.org > make a donation > opt-in > try to share (broken in both Firefox and Chrome) 

NOTE: If you go directly to donate.mozilla.org/share both buttons are functioning. The bug only exists when completing an actual donation.

Additional context, last night we pushed to prod Share Progress code into each of the buttons (Facebook and Twitter) to allow for some testing and optimization of share messaging. This bug would appear to be a result of that update. 

cc: @simonwex @Matt-Holland @ScottDowne

**Comment by simonwex** [comment]
@HPaulJohnson can you reproduce this in staging without using a real payment method?

**Comment by HPaulJohnson** [comment]
@simonwex haven't tried. how do i do that?

**Comment by simonwex** [comment]
@HPaulJohnson this would be specifically be one type of payment method?

@cadecairos do you know the change associated with this bug? Can we just back it out?

**Comment by HPaulJohnson** [comment]
I only tried it with stripe/credit card. I can try it with paypal if that's helpful

For now, I'd be fine with backing out last night's change to fix it. We can revisit next week when there's less travel/PTO happening.

**Comment by simonwex** [comment]
@HPaulJohnson, for future ref, QA checklist is here:

https://github.com/mozilla/donate.mozilla.org/blob/master/docs/QA_Checklist.md

**Comment by Matt-Holland** [comment]
this change was backed out by @ScottDowne , closing this ticket as resolved.

**Comment by ScottDowne** [comment]
Just a heads up, me and @cadeecairos landed a fix to re enable share progress. We'll watch this as we push it to prod, and update here once it's said and done.

**Comment by ScottDowne** [comment]
On prod now, and share buttons are now working post signup. Sorry about this.
