### ISSUE TITLE
Twitter share not working on Codemoji

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#67]
A new bug has recently surfaced (that didn't appear to exist in earlier testing) where the Twitter share button is unresponsive after you create a new scrambled message. 

@simonwex @ScottDowne

**Comment by valianttry** [comment]
My tests  (Mac OS 10.11.5)

Twitter button FAILED in  new Incognito tab in Chrome v 51
Twitter button FAILED in new "Private" tab in Firefox 48 Beta

Twitter button WORKED in new standard tab in Chrome v 51
Twitter button FAILED in new standard tab in Firefox 48 Beta

**Comment by HPaulJohnson** [comment]
I've recreated bug in the following scenarios:
- FAILED via new standard tab Firefox desktop v 47.0
- FAILED via new standard tab Chrome desktop v 51.0.2704
- FAILED via private tab Firefox desktop v 47.0
- SUCCESS via incognito tab Chrome desktop v 51
- SUCCESS via Firefox mobile app
- SUCCESS via Chrome mobile app

**Comment by abusedmedia** [comment]
I'm not able to reproduce the issue, I suspect it's related the the message content, can you share the message which cause the issue?

**Comment by HPaulJohnson** [comment]
@abusedmedia I think you may be right about the message content. 

In private browsing mode (Firefox desktop) I tried the message "hello world" and twitter worked
In private browsing mode (Firefox desktop) I tried the message "it's friday, ya'll" and twitter failed

Also, in my second failed attempt (with "it's friday, ya'll") if I close the share window (click "X") and return to create message, don't change anything and return to share message screen twitter share works.

**Comment by abusedmedia** [comment]
Confirmed, the second one cause the issue (no matter the browser)
It throws a URL malformed error.
For some reasons the twitter share widget doesn't like some chars

**Comment by ScottDowne** [comment]
I think it's the space character.

**Comment by ScottDowne** [comment]
Sometimes space character is fine, like in this case "drg ffd"

**Comment by abusedmedia** [comment]
Found out the reason, trying to push a branch (to make a pr) with the fix but I don't have the right...

**Comment by HPaulJohnson** [comment]
thanks, @abusedmedia. tagging @cadecairos on your question, though most of that crew is off on holiday today and not sure they are available.

**Comment by cadecairos** [comment]
@abusedmedia you should be able to open prs now.

**Comment by HPaulJohnson** [comment]
Hi @cadecairos @abusedmedia @ScottDowne, just wanted to check in and see if this one was resolved?

**Comment by cadecairos** [comment]
Looks resolved to me - the "it's friday y'all" string doesn't trigger the error anymore on my machine.
