### ISSUE TITLE
Paypal donation FAILURE due to authentication fail

### ISSUE THREAD

**Issue by Matt-Holland** [MozillaFoundation/Advocacy#670]
Detailed description of work:
In testing, discovered cannot donate with PayPal because authentication never succeeds, although using correct username, password and captcha. Using the same credentials to log in to PayPal **directly** does work, and if already logged in to PayPal then the donation form donation flow works.

To reproduce:
1) Visit firefox start page, see the donation snippet
2) select an amount, click the PayPal button
3) be redirected to: https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&useraction=commit&token=EC-83V4625082488024T#/checkout/login
4) Page requests an email address and password, although no captcha. Enter a correct email address for a functional PayPal account, and the correct password. click "Login" button
5) Be returned back to https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&useraction=commit&token=EC-83V4625082488024T#/checkout/login , with error message "Check your email address and password and try again." added to top of page, and a captcha added below the password field.
6) Enter correct email, password, and captcha
7) return to step 5

8) in new tab in same browser, navigate to https://www.paypal.com/, click "login" link, and be redirected to https://www.paypal.com/signin?country.x=US&locale.x=en_US.
9) Page has fields for email, password, and captcha. Enter same email and password as in step 4, and enter the correct captcha for the page, click "login"
10) be redirected to https://www.paypal.com/myaccount/home , correctly logged in.

11) in same browser, other tab, return back to https://donate.mozilla.org/en-US/?token=EC-72N19506GR895642P  , select an amount and click the PayPal button
12) see a "waiting" screen with the words "securely logging you in..."
13) be redirected to the next step in the donation flow, https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&useraction=commit&token=EC-0GR28503WL699122H#/checkout/review
14) click "Pay Now", and donation is processed properly

Using Firefox 50.0.1
Mac OS El Capitan 10.11.6

*Start date: December 7, 2016* 
*Due date: December 8, 2016* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @simonwex @HPaulJohnson @roseregina @vojtechmzl

**Comment by ScottDowne** [comment]
Looking into this.

**Comment by ScottDowne** [comment]
So far, step 5 for me doesn't result in an error.

**Comment by ScottDowne** [comment]
Based on reading your steps, looks like you're not able to log into paypal from the paypal checkout signin page, but you can from the standalone paypal/signin page.

Once logged in via paypal/signin, it sounds like the donation then works as expected, skipping the checkout signin page and thus skipping whatever is broken.

**Comment by Matt-Holland** [comment]
@ScottDowne that is correct

**Comment by Matt-Holland** [comment]
Also, I cannot repro the bug using Chrome Version 54.0.2840.98

**Comment by ScottDowne** [comment]
@Matt-Holland Questions for you to help diagnose:

1. what browser
2. what amount
3. monthly or one time?
4. OS?
5. currency?

**Comment by ScottDowne** [comment]
@cadecairos help on this, Steph is hitting this too. Any thoughts?

**Comment by ScottDowne** [comment]
@Matt-Holland Also, what version of Firefox is having this issue? The fact that Chrome works, makes me wonder if it's something in a specific version.

**Comment by cadecairos** [comment]
Just saw this, moving to somewhere I can use my laptop

**Comment by cadecairos** [comment]
@ScottDowne - Matt was using FX 50.0.1 on Mac OS El Capitan 10.11.6

The STRs did not trigger the problem for me using Firefox 50.0.1 on Windows 10

**Comment by Matt-Holland** [comment]
Will, Chris and Scott have all not been able to repro this issue, and there is no surge in complaints about PayPal donations, so this seems to be limited to only my testing machine. Closing the issue.

**Comment by ScottDowne** [comment]
Other things we determined:

1. It wasn't an addon.
2. It still failed using staging and paypal sandbox.

**Comment by ScottDowne** [comment]
related? https://www.paypal-community.com/t5/About-eBay-Archive/can-log-into-paypal-but-when-I-try-to-pay-for-something-I-bought/td-p/865169
