### ISSUE TITLE
Localized email #2 callout

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/Advocacy#671]
Handing off to you guys the translations for the second callout: https://github.com/MozillaFoundation/Advocacy/issues/626#issuecomment-260519286 

Here are the translations:
https://l10n.mozilla-community.org/langchecker/?website=6&file=emails/2016/fundraising_email_2.lang&action=translate&show#string2

Note that we don’t need the Italian callout, as email #2 has been cancelled for Italian

**Comment by beccaklam** [comment]
@lovegushwa Can you send me the link to where the email call out graphics are so I can work on this next week?

**Comment by beccaklam** [comment]
@TheoChevalier @WillatMozFdn Here is the link to the localized call outs for e-mail #2 "Your support makes Mozilla's work possible" https://drive.google.com/open?id=0BzuBOR2VJQqUNkx4ODh1X1htUEE

**Comment by TheoChevalier** [comment]
@beccaklam thank you, they look great! Sorry for the last minute change, but it looks like in the end the Italian email will be sent, could you add the IT one, please?

**Comment by beccaklam** [comment]
@TheoChevalier @WillatMozFdn I've updated the folder with links to the call outs at smaller sizes (~60MB each) and included Italian: https://drive.google.com/open?id=0BzuBOR2VJQqUNkx4ODh1X1htUEE Let me know if they load clear enough?

**Comment by WillatMozFdn** [comment]
yep @beccaklam they uploaded just fine!  Dropping them in the emails now, I think we can consider this one closed....
