### ISSUE TITLE
Building localized email #2

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/Advocacy#672]
Here are the translations in for the second email, so that you can start building the localized emails:

https://l10n.mozilla-community.org/langchecker/?website=6&file=emails/2016/fundraising_email_2.lang&action=translate&show

**Comment by TheoChevalier** [comment]
Hey @WillatMozFdn we actually did not cancel the Italian email?

**Comment by WillatMozFdn** [comment]
That's correct.  It's translated, so coding it and sending it actually do not take all that much work.

**Comment by stephaniemcv** [comment]
@TheoChevalier also the Italian segment had a much stronger OR and CR than we were expecting.
