### ISSUE TITLE
Design: Hero image for FF&Y fundraising email

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/Advocacy#673]
Detailed description of work: FF&& do not have design resources to support this. Their size specs are: 1280 X 420 (it's 640x210 at 2X for retina screens). I will also post location of copy in this ticket.

*Start date: September 8, 2016* 
*Due date: September 13, 2016* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by lovegushwa** [comment]
@beccaklam please resize this image to the above size provide a 1x 2x to be safe.
@WillatMozFdn if you need anything more specific once you know the email content just ask @beccaklam 

<img width="1411" alt="screen shot 2016-12-09 at 5 04 47 pm" src="https://cloud.githubusercontent.com/assets/12228435/21069755/a6224880-be31-11e6-9cb7-f18410d45024.png">

**Comment by beccaklam** [comment]
Here is the link to the resized image on the drive: https://drive.google.com/open?id=0BzuBOR2VJQqUQTZYZ1lNZUVRN2M Please let me know if you need anything else @stephaniemcv!

**Comment by Matt-Holland** [comment]
assuming this is done since the FF&You email is ready to go. Closing.
