### ISSUE TITLE
Add South African Rand (ZAR) to currency options in donation form

### ISSUE THREAD

**Issue by Matt-Holland** [MozillaFoundation/Advocacy#674]
Detailed description of work:
(related to closed issue #374)

Add ZAR to currency option on donation form. Note that PayPal does not accept ZAR, so hide the PayPal option when ZAR is selected.

*Start date: December 12, 2016* 
*Due date: December 19, 2016* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by Matt-Holland** [comment]
@roseregina note that I've created this ticket for the ZAR issue.

**Comment by TheoChevalier** [comment]
ZAR currency is live
