### ISSUE TITLE
Increase the font size on the text below the form on donate.mozilla.org 

### ISSUE THREAD

**Issue by roseregina** [MozillaFoundation/Advocacy#675]
Donors are having a hard time finding the links down there because it seems like it is probably legalese small print. I have gotten specific complaints for the links for Bitcoin and the FAQ. 

*Start date: December 8, 2016* 
*Due date: December 15, 2016* 

CC: @stephaniemcv

**Comment by beccaklam** [comment]
@ScottDowne Can we increase the font-size of .disclaimers and .donation-notice to 13px? I think that should do the trick.
<img width="1379" alt="screen shot 2016-12-09 at 12 21 54 pm" src="https://cloud.githubusercontent.com/assets/20977376/21108533/4daf36f2-c04a-11e6-86b9-a38c791fdb65.png">

**Comment by TheoChevalier** [comment]
Change is live
