### ISSUE TITLE
Change the snippet donate button from red to blue 

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#676]
@ScottDowne firefox UX asked if we can change the snippet button from red to blue. @vojtechmzl said it will not impact conversion. It important to show we are responsive so land this quickly next week if possible.

**Comment by TheoChevalier** [comment]
Looks like this has been done on all current snippets, closing

**Comment by ScottDowne** [comment]
Yup this was done without me quite a while ago as it's a non code change.
Thanks all for taking care of this so quickly while I'm on pto.
