### ISSUE TITLE
Customized email acknowledgements for donations via PayPal

### ISSUE THREAD

**Issue by roseregina** [MozillaFoundation/Advocacy#682]
Now that we are integrating PayPal donation information with SalesForce, can we make SalesForce send nice acknowledgments to those donors like Sawmill does for Stripe? 

*Start date: December 13, 2016* 
*Due date: September 2, 2018* 

CC: @stephaniemcv @cadecairos @ScottDowne @TheoChevalier (tagged b/c it would require localization)

**Comment by WillatMozFdn** [comment]
This is actually under discussion with MoCo LCM email team, as we look towards bringing all email functions into ExactTarget/SFMC (i.e., hopefully no more little pools of data out there in places like Sawmill & google sheets.)  Don't expect any movement on it this year but it is on the radar for early next year.

**Comment by WillatMozFdn** [comment]
Ha ha, look, progress on this one! Blueprint doc: https://docs.google.com/document/d/1bLqQ8roK7KDgd9KtcdwX-pR8UUjjxvVy5yvxMfPOPiA/edit#heading=h.zgkrvh6313ma 
@stephaniemcv

**Comment by stephaniemcv** [comment]
Onward to launching this puppy!

**Comment by WillatMozFdn** [comment]
Closing, this one's done for USD donors, and in the next LCM sprint for localization
