### ISSUE TITLE
Broken link  between German donate page and German donor FAQ

### ISSUE THREAD

**Issue by roseregina** [MozillaFoundation/Advocacy#684]
The link from the German donate page (https://donate.mozilla.org/de ) to the FAQ is incorrect. The link (https://donate.mozilla.org/faq ) redirects to the English language page (https://donate.mozilla.org/en-US/faq ) instead of the German language page (https://donate.mozilla.org/de/faq ) 

Start date: December 13, 2016
Due date: December 21, 2016
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @stephaniemcv @cadecairos @ScottDowne @natalieworth @beccaklam

**Comment by TheoChevalier** [comment]
It redirects to en-US because you’re using a en-US browser, but if you’re using a German browser, redirect will be ok

**Comment by roseregina** [comment]
Thank you! I'll go ahead and close this issue then
