### ISSUE TITLE
Test: pixel heart on donate.mozilla.org

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#685]
replace default white heart with pixel heart on donate.mozilla.org

Artwork here:
https://drive.google.com/drive/folders/0B2qu3ExKWIlvWm1PTFgtNjRuWEk?usp=sharing

<img width="628" alt="screen shot 2016-12-15 at 3 19 14 pm" src="https://cloud.githubusercontent.com/assets/12228435/21248401/b899b142-c2eb-11e6-9ada-4728f69cd490.png">

**Comment by vojtechsedlak** [comment]
Hey @lovegushwa, here are the results from this test. As you can see, the pixel heart (the orange line) did not improve conversion rate:
<img width="1322" alt="image" src="https://cloud.githubusercontent.com/assets/20688240/21398713/2a0f0ce4-c75d-11e6-8c3f-e103e98c012d.png">

Let me know if you have any questions.

**Comment by ScottDowne** [comment]
Pretty sure we can close this now..
