### ISSUE TITLE
Share icon buttons broken in Firefox

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Advocacy#686]
Detailed description of work:
The share links are broken in Firefox browser on the facebook/ twitter share icons: https://donate.mozilla.org/en-US/share/

CC: @ScottDowne @HPaulJohnson

**Comment by natalieworth** [comment]
<img width="374" alt="screen shot 2016-12-19 at 4 04 11 pm" src="https://cloud.githubusercontent.com/assets/14876567/21333541/50377a22-c605-11e6-898f-7b680800af7c.png">

**Comment by ScottDowne** [comment]
How are they broken?

**Comment by natalieworth** [comment]
@ScottDowne There should be the social windows that pop-up when clicked, but nothing happens in Firefox. They're working in Chrome for us, but me, Jordan, and Rebecca couldn't get them to work in Firefox.

**Comment by natalieworth** [comment]
<img width="954" alt="screen shot 2016-12-20 at 9 11 14 am" src="https://cloud.githubusercontent.com/assets/14876567/21360334/54d769ae-c694-11e6-99b3-2f9d4dff858f.png">

**Comment by ScottDowne** [comment]
This was fixed, it was CSS of all things.
