### ISSUE TITLE
DRAFT Fundraising Snippet Copy (EU Net Neutrality)

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#69]
Description:
Since mid June, we have been promoting savetheinternet.eu's petition supporting net neutrality to Firefox users in the EU. That campaign will conclude when the deadline for comments passes on July 18. We want to put a follow-on fundraising campaign in the same locales while Mozilla's message about net neutrality is still fresh in the mind of users. We need two fundraising blurbs for snippet. Once the 2 blurbs are finalized, they will be submitted to L10N to be localized to: EN-GB, DE, FR, ES-ES, IT. 

Snippet copy should be no longer than 2 medium or 3 short sentences. The blurbs should mention the net neutrality campaign to remind users that Mozilla is investing in positive change in their country. For reference, the final EU net neutrality snippet language can be found here in EN: https://docs.google.com/document/d/1Eunqtau62RORzTu6IBc1HHugTGASrRtI9Ht4bGlJbAY/edit 

In order to give L10N localizers as much time as possible, we need **final EN copy no later than Monday July 11 5pm EST** Sooner would be better.

**Approvers of the copy:**
Andrea
Snippet team (Jean Collings or Winston Bowden)
Mark / Angela

cc @damiankay I wanted to create a label called "EU NN Fundraising" but I don't seem to have that power. It also looks like I can't assign anyone or select a milestone... did I break something when I installed Zenhub?

**Comment by valianttry** [comment]
cc @KevZawacki who should be the assignee for this (can't assign anyone atm)

**Comment by KevZawacki** [comment]
Hi @valianttry 

Four draft snippets [here](https://docs.google.com/document/d/1vOxxomPlm0wkRq3AcMRJ8xlYiDcEJ0ONbtO5nqBIeio/edit), and also pasted below. 

If one sticks out, happy to continue riffing on that theme!

## 

Mozilla is standing up for net neutrality in the EU — will you help support a free and open internet? When you donate to Mozilla, you help keep the internet exceptional.

Mozilla fights for net neutrality in the EU and around the world. To protect the web, Mozilla relies on donations from everyday internet users like you. Will you donate?

Mozilla is fighting for net neutrality in the EU. Will you support the cause? Your donations help us protect the internet.

The EU deserves a free, open internet. That’s why Mozilla is standing up for net neutrality. You can help: When you give to Mozilla, you’re helping build a better web.

**Comment by valianttry** [comment]
Drafts are through all necessary approvals and have been sent to localizers. #71
