### ISSUE TITLE
Ukrainian Hryvna (UAH) for Stripe checkout

### ISSUE THREAD

**Issue by roseregina** [MozillaFoundation/Advocacy#691]
Add Ukrainian Hryvna (UAH) currency option, which is currently supported by Stripe. 

We should make sure to have this in place by next year. The reason that this currency is notable because of the political history between Ukraine and Russia, so the lack of UAH option/ feeling forced to donate in RUB feels like a bit of an insult. 

*Start date: December 26, 2016* 
*Due date: September 2, 2017* 

CC: @stephaniemcv

**Comment by ScottDowne** [comment]
We can do this in 2016. It's super easy.

**Comment by roseregina** [comment]
Awesome sauce. I'll assume it's added as soon as I see this thread is closed.
I made a new issue for a larger conversation about this general sort of thing for next year; #692.

**Comment by ScottDowne** [comment]
Done, and it's the default currency for UK, can see it in action here: https://donate.mozilla.org/uk
