### ISSUE TITLE
Clicking on stripe button triggers the spinning cog on PayPal button

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/Advocacy#693]
I guess it’s not critical, but it’s also probably a recent regression, so filing a ticket anyway.

<img width="305" alt="capture d ecran 2016-12-28 a 01 33 43" src="https://cloud.githubusercontent.com/assets/1294206/21511201/b83c6a6c-cc9d-11e6-8e9a-cb0c9913f28b.png">

Noticed that while working on something else, and realized that this was not due to my patch. Had a quick look, but couldn’t figure what’s wrong

CC: @ScottDowne

**Comment by ScottDowne** [comment]
This has actually always been there. For like three years. You're the first
to call it out :)

**Comment by TheoChevalier** [comment]
Ah, my bad, I’m probably not clicking enough on those buttons (or probably clicked only on PayPal a few days ago).
Yeah, definitely not a big deal, then

**Comment by ScottDowne** [comment]
Doesn't need to happen this year, but, https://github.com/mozilla/donate.mozilla.org/pull/1727

**Comment by hannahkane** [comment]
Is this still valid or should we close?

**Comment by TheoChevalier** [comment]
All fixed :)
