### ISSUE TITLE
Content testing - categorizing and tracking creative

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#699]
Create a system for categorizing and tracking social the performance of social media content. A successful system would help us define creative attributes what are likely to work best for a particular audience. 

Questions: how does this relate to the harmony institute work / the total engagement index?

*Start date: January 6, 2017* 
*Due date: January 13, 2017* 

CC: @HPaulJohnson @vojtechmzl @natalieworth @beccaklam

**Comment by hannahkane** [comment]
I think this system is in place now, so closing.
