### ISSUE TITLE
Content testing - defining audiences

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#700]
Define a set of audiences when testing creative (see issue #699). Should we create and test audiences around privacy and security issues we are likely to campaign on in 2017? 

*Start date: January 6, 2017* 
*Due date: January 13, 2017* 

CC: @HPaulJohnson @vojtechmzl @natalieworth @beccaklam

**Comment by hannahkane** [comment]
@lovegushwa - does this ticket still feel useful?
