### ISSUE TITLE
Fixing dev handoff  / QA process

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#705]
- List all the things that go wrong. Went wrong in recent campaigns.
- Create a handoff and QA process / checklist.

**Comment by natalieworth** [comment]
@lovegushwa @beccaklam I talked to an interaction friend and she recommended this app: https://zeplin.io/
It essentially let's you upload designs from Sketch (I think possibly photoshop too) and then allows access to developers to get specs/ dimensions/ pixel spacing/ font information, etc. Looks awesome and like something we could try out! I think it's free with 1 project—so we could even test if we want to use it?
@taisdesouzalessa @flukeout @sabrinang @kristinashu Not sure if you guys have used this yet either?

**Comment by natalieworth** [comment]
Oh! It also let's you create a style sheet for developers.

**Comment by taisdesouzalessa** [comment]
Hey @natalieworth I used Zeplin in my previous job and I can say that it saved me 2-3 hours of doing redlines for specs and the engineer who worked with me loved it. The measurements are pretty reliable and there was way less back and forth between dev and design.  

InVision has a new feature pretty similar to Zeplin: https://www.invisionapp.com/feature/inspect so I guess once we get InVision we can have this feature as well. For now, I think Zeplin is worth it a shot.

**Comment by ScottDowne** [comment]
Not saying this is currently a huge issue or even needs to be fixed, and we can give zeplin a shot either way. This is just where I see the most friction if any. I see two areas where design is needed during or after the handoff, that we can possibly fix.

1. Feedback, confusion, communication, and missing information during dev/handoff. Also when the dev tries to figure it out, it's usually not accurate and requires a few more needless feedback iterations on top of the extra time the dev spent calculating positions, colours, sizes and fonts. I think Zeplin would absolutely help here.
2. Changes or pivots in campaigns based on metrics after shipping. Not sure if this applies to the original ticket, but maybe consider it. Zeplin probably won't help much here. I think for 2 we just need a designer able to re prioritize the campaign, and stay up to date while the campaign's running even if not needed.
