### ISSUE TITLE
Fundraising thank you - videos & landing pages

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#710]
Three "choose your own adventure" videos landing pages:

- Sincere 
- Funny
- Cute

*Start date: January 5, 2017* 
*Due date: January 10, 2017*

**Comment by lovegushwa** [comment]
Pages will say "thank you" above the video or possibly a full sentence related to content of the video. Will decide on final copy EOD.

<img width="1039" alt="screen shot 2017-01-09 at 12 42 08 pm" src="https://cloud.githubusercontent.com/assets/12228435/21782664/10f2f3a4-d669-11e6-9655-70cda787f3c7.png">

**Comment by lovegushwa** [comment]
Redpen's are here: https://redpen.io/p/qte76e824e411176d8

**Comment by lovegushwa** [comment]
@HPaulJohnson we can you write a sentence for each of the videos? (see post below) 
CC @natalieworth @beccaklam

**Comment by lovegushwa** [comment]
Hi @cadecairos we need to get a few videos on Amazon cloud for a fundraising email going out on Thursday. Here are links to .webm and .mp4 videos:

Cute: https://drive.google.com/drive/folders/0B20-0lpP23c0anNPbG15bmdLVEU?usp=sharing

Hero (funny): https://drive.google.com/drive/folders/0B20-0lpP23c0TDQwT0xZaVlKV00?usp=sharing

Sincere: https://drive.google.com/drive/folders/0B20-0lpP23c0UzViZUo1ZjBxclk?usp=sharing

**Comment by cadecairos** [comment]
[Links to all the videos on the CDN are in this bug](https://github.com/MozillaFoundation/mofo-devops/issues/441#event-919198410)

edit: broken link

**Comment by HPaulJohnson** [comment]
Here's some copy for the landing pages for each of these.

https://docs.google.com/document/d/1loG-7YM219kfawJAjr2zZhopgc6z1GqDHChfI4K26gY/edit

**Comment by lovegushwa** [comment]
@cadecairos @HPaulJohnson thank you!

**Comment by lovegushwa** [comment]
@cadecairos once you finish reviewing @beccaklam's code and push the pages live please post the links here. 

CC @WillatMozFdn

**Comment by cadecairos** [comment]
https://donate.mozilla.org/jan-thank-you-sincere
https://donate.mozilla.org/jan-thank-you-superhero
https://donate.mozilla.org/jan-thank-you-cute

@WillatMozFdn

**Comment by lovegushwa** [comment]
Thanks @cadecairos !

**Comment by lovegushwa** [comment]
@beccaklam awesome work! 
A few issues to tweak / consider for next time depending on whats possible tomorrow. 

Header type is inconsistent across pages
<img width="1237" alt="screen shot 2017-01-11 at 5 13 47 pm" src="https://cloud.githubusercontent.com/assets/12228435/21873161/88e4d0c6-d821-11e6-9eee-e660535e14fc.png">

<img width="1237" alt="screen shot 2017-01-11 at 5 13 45 pm" src="https://cloud.githubusercontent.com/assets/12228435/21873164/96d8311e-d821-11e6-8cbb-9341f23be303.png">

<img width="1237" alt="screen shot 2017-01-11 at 5 13 42 pm" src="https://cloud.githubusercontent.com/assets/12228435/21873168/9d7666d0-d821-11e6-8de9-5ccc728e8656.png">

Love this header type but it's renders a little to light, could be a weight heavier or make the color 100% black # 000000
<img width="829" alt="screen shot 2017-01-11 at 5 16 24 pm" src="https://cloud.githubusercontent.com/assets/12228435/21873263/55543a8e-d822-11e6-8924-901f4495cc60.png">



We need to watch the fold for smaller screens, going forward lets make 1280x800 the standard we design for. (I think may have not been an issue with one line of copy as you originally designed)
<img width="1237" alt="screen shot 2017-01-11 at 5 21 50 pm" src="https://cloud.githubusercontent.com/assets/12228435/21873326/a5abeb8a-d822-11e6-92ed-fe8cb9d83706.png">
