### ISSUE TITLE
Fundraising thank you - localize content

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#711]
@TheoChevalier here is the content that needs localization in DE, ES, FR, IT. (Am I missing anything?)
Ashley is getting this all approved today so I'll flag any changes if they happen. Stay tuned. 

Email content:
https://docs.google.com/document/d/1xF7bEqzijxCFRTc5PHr83XkR2i1gZoZ2GQR4sVGyMFU/edit

Landing page copy:
https://docs.google.com/document/d/1loG-7YM219kfawJAjr2zZhopgc6z1GqDHChfI4K26gY/edit

CC @WillatMozFdn @stephaniemcv @HPaulJohnson

**Comment by TheoChevalier** [comment]
Thanks Jordan! From the doc, I take that the winning subject is just “Thanks”, correct? And that I can ignore the preheader text?

**Comment by WillatMozFdn** [comment]
Actually, Theo, preheader text should also be localized please.  I just
narrowed it down to the one we'll use.  Does that work for you?

 - Will

**Comment by TheoChevalier** [comment]
Absolutely, thanks for correcting me :)
I’m not too familiar with those, but I assume it’s like here https://www.campaignmonitor.com/blog/email-marketing/2011/12/a-practical-guide-to-email-preheaders/ Something that won’t be displayed in the body, but only seen in notifications or before opening the email?

**Comment by WillatMozFdn** [comment]
Yep, exactly.  Gmail, Android mail clients and Outlook (desktop) are the
biggest platforms that display preheader text, pretty sure some others do
as well.  Definitely wouldn't want that to be in English for a localized
email ...

(FYI, for the localized fundraising emails in December, I generally grabbed
a short line of text from the body of the email itself, that summarized the
main point of the message decently well...and used that for the preheader.)

 - Will

**Comment by lovegushwa** [comment]
@WillatMozFdn @TheoChevalier when do you want to send the localized emails?

**Comment by WillatMozFdn** [comment]
It'll be next week sometime ... I think we should get them out basically as
soon as the localizers come back with the translations?  (They don't need
to all go out at the same time.)

 - Will

**Comment by TheoChevalier** [comment]
What Will said.
So far, German is complete and you can proceed with it: https://l10n.mozilla-community.org/langchecker/?website=6&file=emails/2017/fundraising_thank_you.lang&action=translate&show

Italian is being reviewed, and French is ongoing.

**Comment by TheoChevalier** [comment]
All locales are now complete: https://l10n.mozilla-community.org/langchecker/?website=6&file=emails/2017/fundraising_thank_you.lang&action=translate&show

**Comment by WillatMozFdn** [comment]
Great, thanks Theo!

Will code those up today and run a proof by the localizers, hopefully get
them out tomorrow.

 - Will

**Comment by lovegushwa** [comment]
@beccaklam can you confirm the landing pages are localized properly? (the strings are all working...)

**Comment by beccaklam** [comment]
Looks good to me @lovegushwa !
