### ISSUE TITLE
Privacy survey email callout

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#713]
Create a email callout for the privacy survey. Something fun / without text so we don't need to localize.  You can read the email copy here: https://docs.google.com/document/d/1S0Isrc0pm6AibZEJJkW_b5NoRnvKS0-hQWIkvR352O8/edit

**Due 1/26 Thursday (End of day)**

@WillatMozFdn can you provide image specifications for @beccaklam?

**Comment by WillatMozFdn** [comment]
Sure.  Actually, I think we do want it to have some text ... "Take our three-minute survey."  Size & specs should probably be the same as for other callout boxes that we used in the fundraising emails at EOY ... i.e. https://image.e.mozilla.org/lib/fe9915707361037e75/m/3/MoFo_GLOBAL_AVO_2016_FUND_HTML_2016_EOY_ALL_EN_IMG_Msg4callout.jpg .  We specify 250 x 250 pixels in the email code, but I think we over-design at 600 x 600 for retina displays -- ??  (Let me know, I'm curious about that....)

**Comment by TheoChevalier** [comment]
Confirming that I’ve exposed “Take our 3 Minute Survey” to l10n, so you can use it if you want

**Comment by lovegushwa** [comment]
@beccaklam you need to make DE and FR as well. You will find the strings here (only DE is ready now):
https://l10n.mozilla-community.org/langchecker/?website=6&file=emails/2017/data_privacy_day.lang&action=translate&show

**Comment by beccaklam** [comment]
@lovegushwa @WillatMozFdn Here are the callouts in EN and DE: https://redpen.io/p/kpc62bd9d5b03eb97a Let me know if you have any edits if not I'll upload them to the drive.

**Comment by TheoChevalier** [comment]
Just got a review for the French one so that it doesn’t block you, it’s “Répondez à notre bref sondage (3 min)” (it should appear in a few on the l10n dashboard)

**Comment by beccaklam** [comment]
Thanks @TheoChevalier! @lovegushwa @WillatMozFdn Here are the call outs in all three locales: https://redpen.io/p/kpc62bd9d5b03eb97a Let me know if you need any changes if not I'll upload them and add the links here.

**Comment by WillatMozFdn** [comment]
Thanks Becca!

Hmmm, wondering how we can +stephaniev@mozillafoundation.org to this thread?

**Comment by lovegushwa** [comment]
@stephaniemcv ^ see @beccaklam redpens.

**Comment by beccaklam** [comment]
@lovegushwa @WillatMozFdn @stephaniemcv If there's no changes I've put the files on the drive: https://drive.google.com/drive/folders/0BzuBOR2VJQqUSXd2YUEwVTRnWWM?usp=sharing

**Comment by stephaniemcv** [comment]
No changes from me. I think they look great!
