### ISSUE TITLE
Privacy survey social

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#714]
Create a social share for the privacy survey. Write social copy (twitter / facebook)
Could be funny, just like the clever survey copy which I recommend using as a source of inspiration. https://docs.google.com/document/d/1NEIoAulFwxCF-MpnlTomQxNAKMHDuRaxw7cia4x30Zo/edit

**Due 1/26 Wednesday (End of day)**

**Comment by beccaklam** [comment]
Privacy Survey Social Illustration: https://redpen.io/p/ejde35ab06eb3f4723

**Comment by beccaklam** [comment]
Link to artwork: https://drive.google.com/open?id=0BzuBOR2VJQqUZXNYNGRWUm1kTEk
