### ISSUE TITLE
weigh the value of changes in NB vs creating a stopgap page

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#715]
Is there any potential in keeping NB and making changes we need directly to it.

Or, is making a whole new site give us the impact we expect.

For what it's worth, I think building the stop gap is pretty easy, and I'm not super worried about it.

**Comment by ScottDowne** [comment]
cc @simonwex

**Comment by ScottDowne** [comment]
Doing a new site in NB would be more work than creating a static page integrated with salesforce.

Copying over the existing NB pages and updating copy as a static page would be more work than just updating copy in NB.

I feel like that gives us two options. Updating copy in existing NB site or stopgap static site.

Updating copy in existing NB site.
Pros:
- Least amount of work. Possibly a day or less of work.

Cons:
- Wouldn't give us the ability to make non copy changes quickly.

Stopgap static site.
Pros:
- Can roll out a whole new experience, design and copy.

Cons:
- Is more than a days work.

**Comment by hannahkane** [comment]
Wouldn't even copy changes in NB be costly given difficulty of l10n?

**Comment by ScottDowne** [comment]
@hannahkane Yeah, good call. It's likely significant but less than it was the first time we built it.

That also reminds me, we likely still have a contract with bablic that we should factor in to monthly costs of NB, right?

**Comment by cadecairos** [comment]
Bablic costs about $700/month

**Comment by hannahkane** [comment]
I'm going to close this, as we've made a decision.
