### ISSUE TITLE
Design: Copyright Petition V3 

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#716]
Redesign the copyright petition site. 
Wireframes due 2/17
UI due 2/22

Draft content:
https://docs.google.com/document/d/10kCzOBpVzG3ueMqNIC100BBo33bDOdB31715YH41KWQ/edit

Legacy wireframes / UI:
https://redpen.io/p/rh3ca19956fb0a83c8
https://redpen.io/p/coa34e472107659406

Share progress:
https://share.mozilla.org/352/169283

Brand benchmarks:
https://projects.invisionapp.com/share/ZJ9YTAGEA#/screens
https://mozilla.ninja/
https://www.mozilla.org/en-US/internet-health/
https://internethealthreport.org/v01/
https://www.mozilla.org/en-US/internet-health/privacy-security/

CC: @hannahkane @ScottDowne @shaghdoosti @beccaklam @Melechuga

**Comment by hannahkane** [comment]
@beccaklam - we have final designs for this, right? If so, could you drop in final assets here and close the ticket? Thanks!

**Comment by beccaklam** [comment]
Final assets: 
![desktop](https://cloud.githubusercontent.com/assets/20977376/23308009/a3c42504-fa77-11e6-9a42-3a4cd1747324.png)
![tablet landscape](https://cloud.githubusercontent.com/assets/20977376/23308007/a3c15874-fa77-11e6-8316-5f9564591904.png)
![tablet portrait](https://cloud.githubusercontent.com/assets/20977376/23308008/a3c335fe-fa77-11e6-86c2-6c718f3b9c61.png)
![mobile portrait fullpage](https://cloud.githubusercontent.com/assets/20977376/23308006/a3c0e128-fa77-11e6-94fa-8737f0417e4a.png)

**Comment by ScottDowne** [comment]
@beccaklam I'm looking for the header image.
