### ISSUE TITLE
Codemoji Snippet

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#72]
In conjunction with second wave of promotion for Codemoji to coincide with World Emoji Day on 7/17, we are planning on running Snippet promo. 

Snippet team has indicated there is availability at the end of July and are currently confirming and considering creative approaches. 

Potential deliverables pending Snippet Team's feedback include: 
- 2-3 versions of copy (complete)
- Graphics to accompany copy
- Embedding of video "trailer" 

Tentative go-live date would be 7/15. 

Dependencies include Snippet Team, MoFo Comms and Design.

cc: @KevZawacki @natalieworth @lovegushwa @damiankay

**Comment by KevZawacki** [comment]
@HPaulJohnson Pasting proposed snippet copy below, so it's easy to find:

## 

Some people express themselves best through emoji. Are you one of them? Try Codemoji, Mozilla’s new game that’s all about emoji, ciphers, and encryption. 

Morse code. Pig Latin. Invisible ink. And now, emoji code. Try Codemoji, Mozilla’s new game for encoding messages with emoji (and learning the basics of online ciphers). 

Love emoji and secret messages? Try Codemoji — send notes encoded in emoji, and learn about the basic building blocks behind encryption. 

Psst. Want to send a secret note to friends, encoded in emoji? Try Codemoji — and see if your friends can decipher your message. You’ll also help teach them about ciphers, the basic building blocks behind encryption. 

What do ciphers, emoji, and encryption have in common? Codemoji! Try Mozilla’s new game for learning the basics behind encryption.  

????✉????✋???????? ??????????. No, we didn’t fall asleep on the keyboard. Those emoji spell out a secret message. Decipher it for yourself — try Codemoji, a game for learning about ciphers, the basic building blocks of encryption.

[--- Commented from Asana.com
#commenter Damian Kuehn
---[aa]

**Comment by HPaulJohnson** [comment]
Update from snippet team:

> Everyone responded well to Codemoji. We would love to get it on the snippet by or before World emoji day. It would be wonderful if you could get creative to throw together an icon (64x64) or two that you think best encapsulates Codemoji. I posted the snippet copy that I liked below, along with a link to the Mozilla tone and position doc.
> 
> Try to get me the assets by Monday or Tuesday. That way I can review them, then put them up for approval in our Wednesday creative check-in meeting.
> 
> Favorite Snippets:
> ????✉????✋???????? ??????????. No, we didn’t fall asleep on the keyboard. Those emoji spell out a secret message. Decipher it for yourself — try Codemoji, a game for learning about ciphers, the basic building blocks of encryption.
> 
> Morse code. Pig Latin. Invisible ink. And now, emoji code. This #WorldEmojiDay, try Codemoji, Mozilla’s new game for encoding messages with emoji (and learning the basics of online ciphers).
> 
> Psst. Want to send a secret note to friends, encoded in emoji? Try Codemoji — and see if your friends can decipher your message. You’ll also help teach them about ciphers, the basic building blocks behind encryption.
> 
> Links:
> 
> Link to Tone and Position Doc: https://docs.google.com/a/mozilla.com/document/d/1M54RiNDnl_BDfk7Jqy2Wn4XqAgI-icQzWZ8HE3KuwI4/edit?usp=sharing
> 
> Link to sweet tone-centric slideshow: https://docs.google.com/a/mozilla.com/presentation/d/17LGZsfNDDAb6dF9eYVq_amSv-z720qFsXCv5acGOt_U/edit?usp=sharing

@natalieworth can you create 1-2 icons to accompany copy above that can be used for Snippet. Would need to by Tuesday. Let me know if that's possible and/or if you need additional direction.

[--- Commented from Asana.com
#commenter Damian Kuehn
---[aa]

**Comment by natalieworth** [comment]
Hey @HPaulJohnson I've upload 2 icons here: https://drive.google.com/open?id=0B20-0lpP23c0aXROajlNb3FsVDQ at 64 x 64 px @ 144dpi
Let me know if the snippet team needs different requirements. Thanks :)

**Comment by lovegushwa** [comment]
@natalieworth icons look great!

**Comment by damiankay** [comment]
Closing this issue - please reopen if necessary
