### ISSUE TITLE
Build campaign homepage and form

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#725]
Comps are being finalized in #716

**Comment by hannahkane** [comment]
Question that just occurred to me - do we need to validate the email address field? If so, do we need an error state mockup?

**Comment by TheoChevalier** [comment]
@ScottDowne and I were wondering the same. It seems we can’t just use the HTML “required” attribute, so we will need a custom error message

**Comment by ScottDowne** [comment]
Yeah. I think we need two errors. Email is required and email is invalid.

**Comment by WillatMozFdn** [comment]
@ScottDowne -- re: email is invalid, do we have a validation script already on the books somewhere that checks basic syntax of an email address, just to make sure it's in the proper format?  Unfortunately I don't think there's a ton we can do right now to make sure the address is in fact a deliverable one ... it's on my list to get a company like BriteVerify or DataValidation through the vendor approvals process, so we can back-end ping their services and throw an alert at the user ("There seems ot be a problem with your email address, please double-check it?") while they're still on the form ... but that approvals process is going to take some time.

**Comment by ScottDowne** [comment]
I was just going to use the browser email validator. It just checks for
format.

**Comment by hannahkane** [comment]
cc @beccaklam for error message UI guidance

**Comment by hannahkane** [comment]
Filed a separate ticket for the error state, so we don't lose track of it. https://github.com/MozillaFoundation/Advocacy/issues/737

**Comment by ScottDowne** [comment]
It's pretty much built, and the error messages for email is functional.

https://changecopyright-org-staging.herokuapp.com/en-US/#get-involved

I think we should close this, and keep #737 open.

**Comment by hannahkane** [comment]
Sweet. Closing.
