### ISSUE TITLE
DUE FEB 24: Finalize copy

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#727]
Copy should align with existing design for [copyright site](https://github.com/MozillaFoundation/Advocacy/issues/716).

**Comment by hannahkane** [comment]
@shaghdoosti - can you link to the copy here, please?

**Comment by shaghdoosti** [comment]
Here it is: https://docs.google.com/document/d/1juXdq413TCG-M2WV7qZvJe9IOxO-jsFVCexgSV40c8k/edit?ts=58addd12

**Comment by shaghdoosti** [comment]
Note: I did my best to keep copy changes as minor as possible - but we had to shift a few things for strategic reasons.

**Comment by hannahkane** [comment]
Great. Thanks. Closing ticket now.
