### ISSUE TITLE
DUE FEB 27: Copy and icon for snippet

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#732]

**Comment by beccaklam** [comment]
Copy variants sent to Wes:
Variant A: Did you know you’re one of the biggest funders of public scientific research? Find out more here. 
Variant C: Happy Open Data Day - show how much you heart open data by taking action in support of research being more easily available. 

Snippet (64x64)
![open-data-64px](https://cloud.githubusercontent.com/assets/20977376/23382506/6a481c36-fd10-11e6-863f-50cf04ee7bc5.png)

**Comment by hannahkane** [comment]
Nice work! Closing.
