### ISSUE TITLE
Automatic Email Response

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#733]
Do people who sign up for either the Open Data Day letter or Copyright campaign get an automatic email afterward?

cc @shaghdoosti

**Comment by shaghdoosti** [comment]
I don't think so. @stephaniemcv  @HPaulJohnson is this something we've done before?

**Comment by stephaniemcv** [comment]
NationBuilder was set up to send a triggered email after signing the Copyright Campaign. I'm not sure with the work of moving Copyright off of NationBuilder if this is still true.

I'm not looped in on the Open Data Day letter, so I'm no help there.

**Comment by shaghdoosti** [comment]
Ahhh - good to know that was a nationbuilder feature. Given this is a MVP - I don't think we need a triggered email for either.

**Comment by hannahkane** [comment]
OK, cool. Closing!
