### ISSUE TITLE
QA: "Get Involved" link fail

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#734]
If I click on "Get Involved" from the homepage, it correctly scrolls down to the form, but if I click on it from the Resources page, it just takes me to the top of the homepage.

**Comment by hannahkane** [comment]
This was Chrome-specific, and @ScottDowne, your fix seems to have worked. In Chrome, it still goes to the top of the homepage for a split second, but then jumps down to the form. I wouldn't consider this a blocker, so closing.

**Comment by ScottDowne** [comment]
The "split second, then jumps to the form" seems to be how chrome handles hash urls. I can see the same weirdness when I go here in chrome: https://github.com/MozillaFoundation/Advocacy/issues/734#issuecomment-282808857
