### ISSUE TITLE
Potential typo in a string

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/Advocacy#735]
One of our localizers spotted a potential typo in this string:

> By signing, you accept {linkTerms} and {linkPrivacyPolicy}, and agree to receive occasional emails about campaigns from Mozilla. You can unsubscribe at any time.

Should it be by signing **up**, or is it okay as is? Note that the button below says “Sign me up”

**Comment by shaghdoosti** [comment]
It should be signing up. Where is this typo? Let's get it fixed in the English version too.

**Comment by TheoChevalier** [comment]
Thanks, will push the fix with the other string changes

**Comment by TheoChevalier** [comment]
Fixed https://github.com/mozilla/copyright/commit/c74083b0277bf70ca9d4302c4c87737e22a1f208
