### ISSUE TITLE
Legal review of sites

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#736]
- [x] Open Data Day
 - [ ] Copyright

@shaghdoosti - shall I coordinate with Abigail to conduct legal reviews of both the copyright site and the open data site, or is that something you'll do?

**Comment by hannahkane** [comment]
Done for Open Data, so moving to next milestone to complete for Copyright.

**Comment by hannahkane** [comment]
@shaghdoosti - do you think we can close this ticket? Has the Copyright site passed legal review?

**Comment by shaghdoosti** [comment]
I would say yes. Closing now.
