### ISSUE TITLE
QA: improve error state for form validation

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#737]
We need UX guidance for how to handle two error states: email field left blank, or email address is invalid.

@beccaklam - can you please advise on design, copy, and any other UX elements? Thanks!

**Comment by TheoChevalier** [comment]
@beccaklam Here are the messages Scott and I planned to use, let me know if this is good to merge or if you want to tweak them a little bit. But once it’s merge, let’s consider them final please :) 
https://github.com/mozilla/copyright/pull/24/files

**Comment by ScottDowne** [comment]
If there is more to do for validation work to do, we can add, but for the most part, I see the only thing left is the error message translations, so once that's done, and there is no more QA feedback on the UX of it, we can close.

**Comment by beccaklam** [comment]
@TheoChevalier @ScottDowne @hannahkane The strings look good to me. @ScottDowne One note on the UX, it would be good to have the error message not in arvo. Makes it feel more error-like.

**Comment by TheoChevalier** [comment]
Thanks, strings have landed

**Comment by hannahkane** [comment]
Adding Open Data Day label to this, because fixes should apply there as well

**Comment by ScottDowne** [comment]
Strings have also been updated in open data day petition site. I think we can close.

**Comment by ScottDowne** [comment]
@beccaklam I missed your arvo comment. I think we should probably but that in a new ticket just to drop the history in this ticket.
