### ISSUE TITLE
Design: Header + Social share for open data day

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#739]
- [X] Header image
- [x] Social share for share progress

Design a social share for open data day, will be shared by users via share progress. 
We can repurpose this snippet copy for a post. https://docs.google.com/a/mozilla.com/document/d/1pqJN23mj3jeNJmdiQr97Q8vqrXQ_0kAPgfo0lqgMaHo/edit?usp=sharing

CC @natalieworth  @hannahkane @HPaulJohnson @shaghdoosti

**Comment by natalieworth** [comment]
@lovegushwa @beccaklam Header drafts and image explorations are in here:
https://redpen.io/p/syd651d32158458060

They're still quite rough. If you have any preference let me know and I can possibly refine 1-2 options?

**Comment by hannahkane** [comment]
Hey @natalieworth - do you have an estimate for when these will be finalized? Do we need to schedule a time to talk through the options?

**Comment by natalieworth** [comment]
@hannahkane Final image file for this is here: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0Q0h4UzRGTFVyM0k
Background grey hex code is #F1F1F2 if needed for dev

**Comment by hannahkane** [comment]
thanks, @natalieworth. Will there be a separate asset for the social share? I added a checklist to the original comment of this ticket to clarify.

**Comment by natalieworth** [comment]
@hannahkane yah! Just working on that now and will add here asap for Share progress/ social.

**Comment by natalieworth** [comment]
@lovegushwa @beccaklam @hannahkane @HPaulJohnson  I have 2 options that we can A/B test:

1. Copy: You paid for it, you should be able to see it. Show your support for public research data here.
![open-data-social-shares-v1-03](https://cloud.githubusercontent.com/assets/14876567/23525665/16b6921a-ff44-11e6-8cfc-6827ca2f4432.jpg)

2. Copy: TBD/ Did you know you’re one of the biggest funders of public scientific research? Find out more here.
![open-data-social-shares-v2](https://cloud.githubusercontent.com/assets/14876567/23525669/1876933e-ff44-11e6-95a7-fd791a362ab4.jpg)

3. Alternatively for social, we could link to the actual gif as I don't think Share Progress supports gif sharables:
Copy:
Did you know you’re one of the biggest funders of public scientific research? Find out more here. 
![who-me](https://cloud.githubusercontent.com/assets/14876567/23525730/40cd8c20-ff44-11e6-80f4-25ad78b4b289.gif)

Copy was taken from this document (I think originally snippet): https://docs.google.com/document/d/1pqJN23mj3jeNJmdiQr97Q8vqrXQ_0kAPgfo0lqgMaHo/edit

Let me know if they are good to go from you guys and I will cc Scott to implement them.

**Comment by HPaulJohnson** [comment]
Love these, and a great test. I don't think Share Progress supports .gif format, so we should use static version for that, but we can/should test .gif version in our organic social posts to promote open data day.

**Comment by natalieworth** [comment]
@ScottDowne Have 2 options for the Share progress here (1200 x 628px):
https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0TE1BUEVTTl94Vms

**Comment by hannahkane** [comment]
Closing this. Nice work, @natalieworth!
