### ISSUE TITLE
Share This copy for Open Data Day

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#740]
@shaghdoosti  - can you please provide copy for the Open Data Day "share this" feature on the site? Possible to get this by tomorrow?

 - [x] Email (subject line, body)
 - [x] Twitter (tweet)
 - [x] Facebook (title, description)

**Comment by shaghdoosti** [comment]
Hey - 

Twitter and FB copy are here. I'll work on the email SL and body today and it'll be in the same doc. 

https://docs.google.com/document/d/1pqJN23mj3jeNJmdiQr97Q8vqrXQ_0kAPgfo0lqgMaHo/edit

**Comment by shaghdoosti** [comment]
Email share is now in the google doc too. 

https://docs.google.com/document/d/1pqJN23mj3jeNJmdiQr97Q8vqrXQ_0kAPgfo0lqgMaHo/edit

**Comment by hannahkane** [comment]
Thanks, @shaghdoosti. Closing this ticket now.
