### ISSUE TITLE
QA: Contact and Share This icons missing on staging

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#742]
Is this a known issue? Do we have the icons?

cc @ScottDowne @beccaklam

**Comment by beccaklam** [comment]
@hannahkane Yes I need to get Scott the icons by EOD, but we're aware of this issue.

**Comment by beccaklam** [comment]
Hey @ScottDowne cc @hannahkane here are the PNGs for the contact, share and join the conversation icons:
[missing-footer-icons.zip](https://github.com/MozillaFoundation/Advocacy/files/805110/missing-footer-icons.zip)

**Comment by ScottDowne** [comment]
Links updated on staging: https://changecopyright-org-staging.herokuapp.com/en-US/#get-involved
