### ISSUE TITLE
Social share for Copyright Campaign

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#743]
I'm assuming we need this...

@shaghdoosti @lovegushwa to verify and provide more details.

**Comment by natalieworth** [comment]
@hannahkane I can take this on in addition to the header image on the open data site. We'll also need a social share for the open data page (not sure if you want to make a separate ticket for that)? Feel free to assign me if you do! :)

**Comment by hannahkane** [comment]
Thanks, @natalieworth! I was thinking the social share for open data was covered by #739. Let me know if you'd rather have that ticket divided into two. Whatever is best for you!

**Comment by shaghdoosti** [comment]
Here's the copy for the copyright share. @HPaulJohnson will you have a look?

https://docs.google.com/document/d/1qSiHHO3talrhdr2HKI2LSnhazkcqE-1B94O7WA_MHmo/edit

@hannahkane I'm not sure how we tackle localisation on this. 

S.

**Comment by TheoChevalier** [comment]
Unless @ScottDowne has more knowledge than me on this, things in ShareProgress can’t be localized :/ It looks hosted on our side, but I don’t really know how it works

**Comment by shaghdoosti** [comment]
I think this merits a conversation on Monday.

**Comment by hannahkane** [comment]
I believe we're creating different ShareProgress versions for each locale. @ScottDowne can say more.

**Comment by ScottDowne** [comment]
@TheoChevalier yeah, so it's pretty low tech solution, and not great at all. We setup a share progress test using their UI for each locale. That gives a url, and we need to key each locale to a url, and store and swap that in the repo. These tools really don't like l10n.

I figure this solution wouldn't work at all if we had a donate level number of locales. In that situation, I think we'll see the upper limits of share progress.

**Comment by TheoChevalier** [comment]
@ScottDowne alright, let’s do that. When you have a minute, could you show me where I will need to paste translations? Just as an example

**Comment by ScottDowne** [comment]
Update, me and @TheoChevalier  walked through making multiple pages in share progress. We hit a potential snag.

Share progress' UI is not localized, just the content, from our tests. @HPaulJohnson does that sound right to you?

If that's the case, what we'll probably end up doing is using share progress for just English, and the other languages are going to use a static share page which won't be testable. Then when we get results from share progress, we can then ensure the static pages switch to the winning copy.

Thoughts?

**Comment by HPaulJohnson** [comment]
@ScottDowne I just forwarded you an email thread I had from last Summer with Share Progress support about how to localize the UI too. Check it out and see if this solves this issue and/or let me know if you want me to help work through this with them.

**Comment by natalieworth** [comment]
@lovegushwa @beccaklam Have 2 options based on feedback from Yuliya when we were discussing brand stuff today. My preference is the V2. If it's good to go, we can implement on the site.
V1:
![copyright-header-v1](https://cloud.githubusercontent.com/assets/14876567/23686362/07ca9468-035e-11e7-8e94-9fd5817f8320.jpg)

V2:
![copyright-header-v2](https://cloud.githubusercontent.com/assets/14876567/23686365/0c63d12e-035e-11e7-9bbc-0ac90d8419d9.jpg)

**Comment by natalieworth** [comment]
Files for these are in here: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0cFI5bGhVcXlDY3M

**Comment by natalieworth** [comment]
@lovegushwa @beccaklam Social share options:
V1:
![copyright-social-02](https://cloud.githubusercontent.com/assets/14876567/23686449/86879d64-035e-11e7-84db-a8a967f039a6.jpg)


V2:
![copyright-social-03](https://cloud.githubusercontent.com/assets/14876567/23686450/8688e278-035e-11e7-87d6-00a3adbc1b4d.jpg)

**Comment by natalieworth** [comment]
@lovegushwa @beccaklam Share image is in here: https://redpen.io/p/ynac0cec7127db9ae7
If there's no changes I can drop the link in here

**Comment by natalieworth** [comment]
@ScottDowne have the header image here https://drive.google.com/file/d/0B20-0lpP23c0cnk2ZUIyelZ0WjA/view

**Comment by natalieworth** [comment]
Final social file here:
https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0Vzk2Wlg2aVh0YTQ
