### ISSUE TITLE
Favicon for Open Data and Copyright Campaign

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#744]
@lovegushwa - do we just use the mozilla "m"?

**Comment by hannahkane** [comment]
@ScottDowne - assigning this to you as an implementation ticket. Assuming we're going with the mozilla m unless @lovegushwa says otherwise.

**Comment by ScottDowne** [comment]
It's easy to swap out, already implementing the m.

**Comment by ScottDowne** [comment]
Done. Closing.
