### ISSUE TITLE
Visualizations for Privacy Survey

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Advocacy#746]
Detailed description of work: Creating data visuals for the Medium blog post article and social shares. (Designs will also need to be localized)

Content:
https://docs.google.com/document/d/1qn1J3PviebZTBozXEs305BNvXfnrHM2EXz8zgstsK6U/edit?ts=58b5ad99

cc @lovegushwa @beccaklam @hannahkane if this is a duplicate ticket, just close. I'm not 100% which one's you're watching over for us (is it just copyright)?

*Start date: February 28, 2017 
*Due date: March 2, 2017

**Comment by beccaklam** [comment]
@caltrider 
Designs are here:
https://redpen.io/p/qnef5874057dc5d52e <-- redpen for comments
![artboard 7](https://cloud.githubusercontent.com/assets/20977376/23527073/75d187fa-ff62-11e6-822c-c4df441cf8c8.png)
![artboard 4](https://cloud.githubusercontent.com/assets/20977376/23527074/75dc1260-ff62-11e6-889e-429894087987.png)
![artboard 3](https://cloud.githubusercontent.com/assets/20977376/23527078/75eb54aa-ff62-11e6-90b9-987c05c9285d.png)
![artboard 3 copy](https://cloud.githubusercontent.com/assets/20977376/23527077/75e0047e-ff62-11e6-8f3e-896c6bceaab0.png)
![artboard 2](https://cloud.githubusercontent.com/assets/20977376/23527075/75de8036-ff62-11e6-83fa-fe3d7bd7b15f.png)
![artboard 1](https://cloud.githubusercontent.com/assets/20977376/23527076/75de8af4-ff62-11e6-93fa-f7e9cdb00e62.png)
