### ISSUE TITLE
QA: remove two nav items

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#749]
EDIT: Per conversation below, please remove both navigation items. Should look like the first design in https://github.com/MozillaFoundation/Advocacy/issues/749#issuecomment-283475417

----

Open Data Day site shouldn't have "Copyright Campaign" in the navigation.

Not sure how we didn't notice this in the design phase. :) @shaghdoosti - what should the navigation item be?

**Comment by shaghdoosti** [comment]
Hannah - can you ping me the staging link so I can look and make a suggestion?

**Comment by hannahkane** [comment]
https://iheartopendata.mofostaging.net/en-US

**Comment by shaghdoosti** [comment]
Ha! let's change copyright campaign to Open Data Day. 

Having the two buttons (Copyright and get involved) up top that don't link anywhere feels odd in general. Can we just remove them?

**Comment by shaghdoosti** [comment]
Also the button under the form should say 'add my name' not 'sign me up'.

**Comment by hannahkane** [comment]
@shaghdoosti - moving your button copy comment to a new issue, so we don't lose it. (#754)

Re: the two buttons. The links should work, though the Get Involved link should just scroll you down to the form. Did it not work for you? Or did it work, but you just don't like that use of a navigation element?

If it's the latter, let's discuss with @beccaklam. That nav bar at the top would look might sparse with just the moz logo.

**Comment by shaghdoosti** [comment]
I don't love the navigation feature - can we redirect the get involved button to the Mozilla Science page?

**Comment by hannahkane** [comment]
I think it would be jarring to send the user to the Science site without any context. Maybe we could change the link copy to "Learn more about Mozilla and Open Science" or something?

**Comment by shaghdoosti** [comment]
Or 'Want more? Check out Mozilla Science.'

**Comment by hannahkane** [comment]
I think that works. 

@beccaklam and @lovegushwa - how do you feel about two of the three nav links taking the user off the site?

**Comment by beccaklam** [comment]
@hannahkane @shaghdoosti @lovegushwa I think getting rid of the links entirely works, we can also do the 'Open Data Day' + 'Mozilla Science' option (I think 'Want more? Check out Mozilla Science.' may be too long of a name for a button/link) Here are two mock ups:
![open-data-no-links](https://cloud.githubusercontent.com/assets/20977376/23482001/87a0931c-fe9b-11e6-9fa5-3aaf698031e8.png)
![open-data-science-link](https://cloud.githubusercontent.com/assets/20977376/23482029/983ae0c4-fe9b-11e6-82ed-b0eb477b8898.png)

**Comment by hannahkane** [comment]
I think I'd prefer the first option, bc I don't think the connection to Mozilla Science is clear. (If we want to promote MozSci, I think we could do that a different way, but probably not within the time frame.)

@shaghdoosti - this is your call, though.

**Comment by ScottDowne** [comment]
I'm changing the "copyright" label to "open data day" because that's just a plain oversight.

We can keep this open to figure out how to optimize the nav.

**Comment by hannahkane** [comment]
@shaghdoosti - do you want to make a final call on this? Should we remove the two navigation items entirely, or provide a link to Mozilla Science?

**Comment by shaghdoosti** [comment]
Let's keep things simple and take it out.

**Comment by hannahkane** [comment]
Cool. Updated title and original comment to reflect decision.

**Comment by ScottDowne** [comment]
This update is building on staging now.
