### ISSUE TITLE
Document and create a list of features expected from nationbuilder for makerparty

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#75]
A lot of good info came from here: https://docs.google.com/spreadsheets/d/1hs5ULg3671t7c7DS7mmjrg4jPvmSC6RjU12p5palI8Q/edit#gid=0

This is mostly to get the ball rolling. We should move this list into more specific tickets as we solidify it.
- Signup(crm/et)
- Signin(auth0)
- Event map
- Create an event
- Modify an event
- Delete an event?
- Communication (mass email sends)
- Attend an event
- Find events near me
- Share event with friends
- Invite friends to an event
- Unsubscribe from event
- Message event organizer

**Comment by damiankay** [comment]
I think it's safe to close this now
