### ISSUE TITLE
QA: Should we reference the date?

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#750]
The main copy includes this phrase: "Given today is Open Data Day..."

Nowhere on the site do we reference March 4. I'm assuming we'll keep the site up past Saturday (or....is the expectation that we don't?). Wondering if we should say "Given that March 4th is Open Data Day..." instead, to provide context.

Also, is there something we can link to to give more context to Open Data Day?

**Comment by hannahkane** [comment]
@shaghdoosti - do you have thoughts on this? If you're not concerned, feel free to close this ticket.

**Comment by shaghdoosti** [comment]
I think we should leave as is. Thanks!
