### ISSUE TITLE
QA: Remove Country field, since this campaign is US only

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#751]
Assuming the country list should for the Open Data Day campaign should not be the same as Copyright Campaign.

What should the country list be, though? Is this just for U.S.'ians? cc @shaghdoosti

**Comment by shaghdoosti** [comment]
Hey - this campaign is US only.

**Comment by hannahkane** [comment]
Should we just not have a Country field then?

**Comment by shaghdoosti** [comment]
I'd say yes. We don't need a country field for the open data campaign. But it's okay to leave if it's too hard to remove.

**Comment by hannahkane** [comment]
@ScottDowne - let's remove. I don't think having a country list with only one option makes sense. Changing the title of this bug to reflect this.

**Comment by ScottDowne** [comment]
Removed.
