### ISSUE TITLE
QA: we don't prevent people from signing multiple times

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#753]
Not sure if this is an issue we care about. I know we'll de-duplicate when we migrate to SF, but wondering if there's any concern about this - either from a usability angle or a tech angle (bots?)

cc @lovegushwa @ScottDowne @beccaklam

**Comment by beccaklam** [comment]
I'll leave this up to Scott but I don't think people would sign multiple times/don't think hackers would target our site? @hannahkane cc: @ScottDowne @lovegushwa

**Comment by ScottDowne** [comment]
So I do need to make sure the button isn't clickable if it's currently submitting.

However, if people come back here and try submitting multiple times, basket takes care of it (in our case basket takes care of it when we do the import). It'll not send out a double opt in if that email already exists within the system and is double opt in'ed already, if it's not, they get another email. On top of that, if they submit again with new info, it'll merge the record.

**Comment by hannahkane** [comment]
k. Feel free to close this ticket, @ScottDowne.

**Comment by ScottDowne** [comment]
I added a little bit of logic just to make sure the button can only be clicked once, and submit once, until it succeeds or fails.

I think we can call this closed.
