### ISSUE TITLE
QA: mobile/safari field is selected even after I've moved to another field

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#755]
Using an iPhone 7 to view the site in Safari. The First Name field is yellow, even after I've moved to another field. Not sure if this is a bug, or just something I've not noticed before. Assuming this applies to both sites, so adding both labels.

![49b348bf-4e4a-4d6d-b4cd-26361dd011a6](https://cloud.githubusercontent.com/assets/8389648/23479011/ecf27542-fe77-11e6-9ef6-b5f1058000c2.PNG)

**Comment by ScottDowne** [comment]
I couldn't reproduce. Does it happen each time you try to fill out the form, or only sometimes?

**Comment by hannahkane** [comment]
Sorry, realized this is related to the auto-form fill feature. Not specific to the app. Closing.
