### ISSUE TITLE
Implement GA on Open Data Petition Site

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#758]
Detailed description of work: Implement GA tracking script + add events for form submit.

*Start date: March 2, 2017* 
*Due date: March 2, 2017* 

CC: @ScottDowne @hannahkane

**Comment by hannahkane** [comment]
thanks, @vojtechmzl. OK to assign this ticket to you?

**Comment by hannahkane** [comment]
This is done, right? Can we close?

**Comment by ScottDowne** [comment]
Yup, I have confirmed with @vojtechmzl and he said it's working.
