### ISSUE TITLE
QA: Implement GA events on ChangeCopyright.org site

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#759]
Detailed description of work: Ensure proper tracking ID and form submit events are added. 

*Start date: March 2, 2017* 
*Due date: March 2, 2017* 

CC: @ScottDowne @hannahkane

**Comment by ScottDowne** [comment]
I've used existing code for this, so just need to plug the ga account creds into Heroku.

**Comment by vojtechsedlak** [comment]
I was actually just going to file a PR on both repos with changes to the index.js file, which currently has the UA ID for our donate site, and with custom GA event added to the signup-form.js component. Can I go ahead and do that?

**Comment by ScottDowne** [comment]
Yup.

The events are started and here:

https://github.com/mozilla/iheartopendata.org/blob/master/src/mixins/signup.js#L13-L16
https://github.com/mozilla/iheartopendata.org/blob/master/src/mixins/petition.js#L13-L16
https://github.com/mozilla/copyright/blob/master/src/mixins/signup.js#L13-L16

Feel free to make changes to the values sent to the event. I took a guess.

**Comment by vojtechsedlak** [comment]
Oh cool. Yeah those look great. For the property ID, the copyright site should have UA-49796218-44. Open Data site petition ID is UA-87658599-5. 

Let me know if there is anything else I can help with. Once it's implemented, I will do a quick QA.

Thanks @ScottDowne!

**Comment by ScottDowne** [comment]
@vojtechmzl did an issue for this get tagged open data day too?

**Comment by vojtechsedlak** [comment]
I filed a separate ticket #758 for the Open Data site.

**Comment by ScottDowne** [comment]
I think this got done today.
