### ISSUE TITLE
Trailer Production for World Emoji Day Video

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Advocacy#76]
Creating a short (15 sec.) trailer video for World Emoji Day.

Script: https://docs.google.com/document/d/1dSADHJJnqyUKQ5Gqq9p_ex8U254CM3yqoGf57Re76-o/edit

Deck: https://docs.google.com/presentation/d/1L-X4BQ3yaEblb_iV2Bc0tlT0ZQ9BZIvEuaIz3XcaouQ/edit#slide=id.g153698739e_0_3

cc @lovegushwa @brettgaylor @KevZawacki

**Comment by natalieworth** [comment]
Update: 
Draft versions are happening here: https://drive.google.com/drive/folders/0B20-0lpP23c0X1Zjd28zU1kzM1U
Will post other exports for this in the afternoon once credits have been finalized.

**Comment by natalieworth** [comment]
- [x] Snippet video: (341x192 px, webm compression http://www.fnordware.com/WebM/)
- [x] Video for social (facebook): 1280 x 720p), MP4 or MOV format
- [x] Video for social (twitter): 1280 x 720p, MP4 format
- [x] Youtube: 16:9 aspect ratio/ 1920 x 1080 HD (make 1080p/ 720p)

**Comment by natalieworth** [comment]
Files are uploading to folder here: https://drive.google.com/drive/u/0/folders/0B20-0lpP23c0TTNnZklxeVVEcGM
Just waiting on the final Snippet video resolution size and then good to go!

**Comment by natalieworth** [comment]
cc @HPaulJohnson

**Comment by HPaulJohnson** [comment]
thanks, @natalieworth. 

The Twitter version needs to be MP4 format and it looks like the one in the folder is .mov. Can you convert to MP4 and let Liz and I know when it's ready?

**Comment by natalieworth** [comment]
@HPaulJohnson I think Liz was able to convert it from Youtube. I'm not able to export MP4 from Adobe for some reason, but there is a converter site once it's uploaded to Youtube or facebook: http://www.onlinevideoconverter.com/video-converter

**Comment by natalieworth** [comment]
@HPaulJohnson I've also included a subtitled version for the facebook video—since it autoplays (let me know we'll need any other versions/ outputs subtitled and I can export those also):
*also check my spelling/ punctuation if you're able to! I double-check...but you never know :)
https://drive.google.com/open?id=0B20-0lpP23c0TmhiOGxMcDVtanM

**Comment by HPaulJohnson** [comment]
that's awesome, thanks @natalieworth 

the only punctuation I would change would be to remove the em dash in "where people-and..." It will ready cleaner if it just says "where people and..."

**Comment by natalieworth** [comment]
For sure, just updating and I'll post here soon

**Comment by natalieworth** [comment]
@HPaulJohnson Final Facebook files are in here (including subtitled version): https://drive.google.com/drive/u/0/folders/0B20-0lpP23c0MmNFaE1qUTZqYm8

**Comment by natalieworth** [comment]
Woot woot, final files are here and closing this: https://drive.google.com/drive/u/0/folders/0B20-0lpP23c0TTNnZklxeVVEcGM
Happy Belated World Emoji Day! 👍 💯
