### ISSUE TITLE
Implement ShareProgress

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#760]
I don't *think* this is a duplicate, and just want to track.

**Comment by hannahkane** [comment]
Copy is here: https://docs.google.com/document/d/1pqJN23mj3jeNJmdiQr97Q8vqrXQ_0kAPgfo0lqgMaHo/edit

**Comment by ScottDowne** [comment]
We have a placeholder link: http://share.mozilla.org/352/179206

I fudged some of it because I couldn't figure out all of share progress too quickly, but we have a link we can QA and implement now.

I also implemented the link. So should be on staging very soon.

**Comment by hannahkane** [comment]
- [X] Twitter and FB worked as expected. 
 - [ ] Email was confusing. It says to "copy and paste the text below" and the text below is "Subject: https://iheartopendata.org?sp_ref=278335100.352.179206.e.0.2&source=email"
 - [ ] Not sure there's anything we can do about this, but the Han Solo graphic has no context. Is that okay?
![screen shot 2017-03-02 at 3 16 31 pm](https://cloud.githubusercontent.com/assets/8389648/23531503/8f3bad76-ff5b-11e6-9833-5ea172eaf57d.png)

**Comment by hannahkane** [comment]
It's kind of like we're saying "You're almost done!" And Han is like, "Me? I'm almost done?" :)

**Comment by ScottDowne** [comment]
One your second point with email, I couldn't actually find the email text in the doc when I last looked, so it's actually currently blank.

**Comment by hannahkane** [comment]
Copy is at the top of this doc: https://docs.google.com/document/d/1pqJN23mj3jeNJmdiQr97Q8vqrXQ_0kAPgfo0lqgMaHo/edit

**Comment by HPaulJohnson** [comment]
RE: the main image (hans solo in the split above), the subhead text ("Your action has been submitted. Now multiply your impact by telling your friends.") is editable to add context. Note, that whatever text we use will need to work with both versions of the share image we are testing.

**Comment by ScottDowne** [comment]
Updated twitter. I think we can close.

If you find anything else share progress related, might as well open a new ticket.

🚀
