### ISSUE TITLE
Checkboxes 

### ISSUE THREAD

**Issue by shaghdoosti** [MozillaFoundation/Advocacy#761]
@hannahkane @ScottDowne 

Here are the two check boxes we should have on both petition pages (copyright and open data) 

![screen shot 2017-03-02 at 12 14 19 pm](https://cloud.githubusercontent.com/assets/13626384/23525034/e89d1c66-ff41-11e6-8ad7-5867823f8d21.png)
![screen shot 2017-03-02 at 12 14 11 pm](https://cloud.githubusercontent.com/assets/13626384/23525035/e8a2f6d6-ff41-11e6-97d7-1154960cc563.png)

**Comment by shaghdoosti** [comment]
Just a clarifying point - both checkboxes should be unchecked.

**Comment by ScottDowne** [comment]
It's on staging now: https://iheartopendata.mofostaging.net/en-US/#get-involved

Feel free to close if this works as expected.

**Comment by shaghdoosti** [comment]
Thank you this is perfect.

**Comment by hannahkane** [comment]
@ScottDowne Scott - should the user preference re: mailing be showing up in the google sheet? If this gets to SF some other way, then this is +1 from me.

**Comment by ScottDowne** [comment]
@hannahkane Yeah, the signatures go into the sheets, and signups go directly into salesforce, then when we migrate, any signatures would merge with the mailing list signup, and any signatures no already in salesforce, get added in as just signatures, and not signups.

**Comment by hannahkane** [comment]
Cool. thanks!

**Comment by shaghdoosti** [comment]
One last thing - @ScottDowne can you update where the privacy policy links to? It should link to here: https://www.mozilla.org/en-US/privacy/websites/

**Comment by ScottDowne** [comment]
Cool, that's building now too.
