### ISSUE TITLE
Privacy on the footer - 

### ISSUE THREAD

**Issue by shaghdoosti** [MozillaFoundation/Advocacy#762]
In the footer of the page - can we change the text 'privacy policy' to 'privacy'. As per legal's request. 

@hannahkane @ScottDowne 

Thanks!

**Comment by ScottDowne** [comment]
Update is building.

Another thing I noticed, copyright also has this as "Privacy Policy" and that was translated.

We should fix that in copyright too, so I'll switch the labels because it's done for open data day.

@TheoChevalier ^^

**Comment by TheoChevalier** [comment]
@ScottDowne hold on, I’m talking with @shaghdoosti about it, it migh change again

**Comment by ScottDowne** [comment]
@TheoChevalier That's cool, it's already pushed out. However, the cost to changing this is low because it's not translated, so I'm happy to change it up again when you need it.

**Comment by shaghdoosti** [comment]
Yep - just for context - everything on the open data site is final. 

Abigail wants to double check the language (checkboxes and privacy policy) on the copyright page with EU council. There's a chance that will change. 

@hannahkane (for reference.)

**Comment by ScottDowne** [comment]
@TheoChevalier Looks like we're going to go ahead with the change to make the footer link in copyright the same as open data.

I believe this is all inside the properties file. So should be simple, just needs to be translated, right?

**Comment by TheoChevalier** [comment]
@ScottDowne Roger that.  Just need to update the string and change the string ID, but I would like to push that at the same time as #768 (which should be coming today as well, right?)

**Comment by TheoChevalier** [comment]
I’ve exposed the string for localization
