### ISSUE TITLE
Open Data / Copyright Design QA

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#763]
From @beccaklam 

Some design QA post-launch:

**Priority 1**

- [x] Mobile needs a sticky button that sits at the bottom of the page like copyright v2. Button will direct user to form at the bottom of the page

**Priority 2**
- [x] Change footer links to Fira to be consistent with mozilla.org

- [x] Add in functionality (media query for view port?) so that tablet also has a fixed 'cover-page' where the 'get involved button' is always above the fold

- [x] On desktop/tablet the form should become sticky once it gets into view on a user's screen. We need to work on cutting down the amount of copy so this can accommodate for a variety of screens.

**Comment by hannahkane** [comment]
@ScottDowne - did the last checkbox here ever land? Do you want to keep this ticket open?

**Comment by ScottDowne** [comment]
@hannahkane I'm working on that last checkbox now, might as well land it before copyright goes to snippet tomorrow.

**Comment by hannahkane** [comment]
@ScottDowne - you've made the form sticky, right? Can we close this?

**Comment by ScottDowne** [comment]
Yup
