### ISSUE TITLE
Create localized graphics for DPD survey results

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/Advocacy#764]
Hey @beccaklam here are the French and German translations for the DPD survey result graphics: 

https://l10n.mozilla-community.org/langchecker/?website=6&file=emails/2017/results_graphics.lang&action=translate&show

Let me know if you have issues with any of the strings

**Comment by beccaklam** [comment]
Designs are here: 

German:
![artboard 1](https://cloud.githubusercontent.com/assets/20977376/23619392/810e4570-0261-11e7-99b9-a49d265e2f65.png)
![artboard 2](https://cloud.githubusercontent.com/assets/20977376/23619394/8110988e-0261-11e7-8832-462aafc839a4.png)
![artboard 3 copy](https://cloud.githubusercontent.com/assets/20977376/23619395/811505b8-0261-11e7-8b59-f041a9f458fd.png)
![artboard 3](https://cloud.githubusercontent.com/assets/20977376/23619396/8115267e-0261-11e7-99d4-fcbc79c1dedb.png)
![artboard 4](https://cloud.githubusercontent.com/assets/20977376/23619391/810c78bc-0261-11e7-8041-d9e4e43708be.png)
![artboard 7](https://cloud.githubusercontent.com/assets/20977376/23619393/810e801c-0261-11e7-9014-d4d059e3d4ea.png)

French:
![artboard 1](https://cloud.githubusercontent.com/assets/20977376/23619406/86aae3f8-0261-11e7-8d42-0e66e6ff8d0c.png)
![artboard 2](https://cloud.githubusercontent.com/assets/20977376/23619408/86aeb5b4-0261-11e7-8742-1f422f055ba7.png)
![artboard 3 copy](https://cloud.githubusercontent.com/assets/20977376/23619407/86ab24e4-0261-11e7-8bc7-596ea3065e8a.png)
![artboard 3](https://cloud.githubusercontent.com/assets/20977376/23619404/86a65c84-0261-11e7-9de6-ba70b550d5c3.png)
![artboard 4](https://cloud.githubusercontent.com/assets/20977376/23619405/86a9bdac-0261-11e7-8d9f-8c7fb5972634.png)
![artboard 7](https://cloud.githubusercontent.com/assets/20977376/23619403/86a67fc0-0261-11e7-9154-2a55b3e6b8a3.png)

**Comment by TheoChevalier** [comment]
Thank you @beccaklam! Swapped graphics in the localized blog posts
