### ISSUE TITLE
Privacy Survey Email Callout

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#765]
Create a callout for the privacy survey email. 
290x290

@WillatMozFdn @caltrider can you suggest copy for this callout?

Example of prior callout in action:
![screen shot 2017-01-27 at 12 36 06 pm](https://cloud.githubusercontent.com/assets/12228435/23624148/938f4526-0259-11e7-98cb-5d418dd7dd40.jpg)

**Comment by beccaklam** [comment]
@WillatMozFdn @caltrider @lovegushwa Here's a take on the call out:
![email-call-out](https://cloud.githubusercontent.com/assets/20977376/23627607/667be91a-027f-11e7-964c-5bc2b3c0da52.png)

**Comment by caltrider** [comment]
@lovegushwa @beccaklam @WillatMozFdn 

We could tweak this image:
![1c489764-026e-11e7-9373-19dddb0a9b3c](https://cloud.githubusercontent.com/assets/22063437/23627503/40cb1f9e-026e-11e7-91e5-8d2b6fb4a33a.png)

With this text:
Survey Says! (big headline)
We crunched the numbers and found some surprising results
Check them out

**Comment by beccaklam** [comment]
hey @caltrider we can work with the above idea ^ but we're also working with a small square box, something like 200x200px. Would you be able to make the copy shorter?

**Comment by caltrider** [comment]
@beccaklam How about this:

Survey Says! (big headline)
See the surprising results.

**Comment by beccaklam** [comment]
@caltrider Love it 👍

**Comment by beccaklam** [comment]
@caltrider @lovegushwa @WillatMozFdn Here is the e-mail graphic:
<img width="600" alt="email-call-out 2x" src="https://cloud.githubusercontent.com/assets/20977376/23662884/eeae35e6-031e-11e7-9a40-0e4c77062414.png">

**Comment by beccaklam** [comment]
@caltrider @lovegushwa @WillatMozFdn Here is the e-mail graphic:
<img width="600" alt="email-call-out 2x" src="https://cloud.githubusercontent.com/assets/20977376/23663410/7e2a1c34-0320-11e7-8a69-fb91f6f7031f.png">

**Comment by beccaklam** [comment]
@WillatMozFdn @lovegushwa @caltrider Hello, has it been decided which wording we're going with? @TheoChevalier needs the string so he can get it localized.

**Comment by caltrider** [comment]
@lovegushwa @caltrider @TheoChevalier
I say go with the "Survey Says! See the surprising results" unless @WillatMozFdn has any objections to that.

**Comment by WillatMozFdn** [comment]
yeah, I'm good with that!

One thing to raise, though ... that works really well in English b/c it's a
common term thanks to the TV show Family Feud.  (Will they get to 200
points and get the fat prize?)

But maybe we should stick with the straighter version, "See our Privacy
Survey results," for the DE and FR versions?  I'm just not sure how well
"Survey Says" will translate ....

 - Will

**Comment by caltrider** [comment]
@WillatMozFdn TIL, there are French and German versions of Family Feud.  I wonder if they are as trashy and awesome as our American version?  Also, I wonder if what they say instead of "Survey Says!".  But yes, good point. If that's not something that translates, we should go with the simpler "See our privacy survey results". @TheoChevalier @beccaklam

**Comment by TheoChevalier** [comment]
I know the French version of the show, but I’m not sure there’s such a thing in it… Or if there is, it’s not known by everyone. So yeah, I’ll probably just use the simpler version for localization, but feel free to keep this one for English. Does that sound good?

**Comment by caltrider** [comment]
@TheoChevalier that works for me. thanks.

**Comment by TheoChevalier** [comment]
@beccaklam Here are the translations:
German: "Lesen Sie die Ergebnisse unserer Datenschutzumfrage"
French: "Découvrez les résultats surprenants de notre sondage"

**Comment by beccaklam** [comment]
@TheoChevalier @WillatMozFdn @caltrider @lovegushwa 
Here are the localized e-mail call outs:
<img width="600" alt="privacy-blog-callout-de" src="https://cloud.githubusercontent.com/assets/20977376/23755419/489a081a-04ae-11e7-9fa3-47de49db679f.png">
<img width="600" alt="privacy-blog-callout-fr" src="https://cloud.githubusercontent.com/assets/20977376/23755418/486a776c-04ae-11e7-8520-0e893117400e.png">
