### ISSUE TITLE
Copyright Campaign Email Callout

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#766]
Create a callout for the privacy survey email. 
290x290

@WillatMozFdn @caltrider can you suggest copy for this callout?

Example of prior callout in action:

![screen shot 2017-01-27 at 12 36 06 pm](https://cloud.githubusercontent.com/assets/12228435/23624978/71c44ed4-025c-11e7-8c2c-288e43b8a154.jpg)

**Comment by natalieworth** [comment]
@WillatMozFdn @caltrider is there copy for this?

**Comment by WillatMozFdn** [comment]
Hey @natalieworth  -- sorry, I'm confused ... do you mean for the Copyright **story collection** email, where we're asking people for their stories about copyright on a surveygizmo form?  (I'll have to look into that.)  However, if you're talking about the copyright petition-ish campaign -- we're actually not going to send email on that one, all the traffic to the site will be snippet- and social-driven.  (Hope that makes sense?)

**Comment by TheoChevalier** [comment]
If there is something else to localize for the copyright story collection email, I need to know too. Next time we should include those strings in the initial copy doc, it’s getting late for l10n.

**Comment by natalieworth** [comment]
Hey @WillatMozFdn , oh I meant copy for the email callout? Do we need an email callout design for this campaign? Here's an example from the last one I made:
<img width="399" alt="screen shot 2017-03-07 at 1 33 48 pm" src="https://cloud.githubusercontent.com/assets/14876567/23678931/deefe93a-033a-11e7-9c79-2b8d48b7eff2.png">
Sorry, didn't mean to confuse you :)

**Comment by WillatMozFdn** [comment]
yeah, basically, have we created any graphics to go along with this copy ... https://docs.google.com/document/d/1L6A3PGZaXykyCyEg05oP3x9UG-cAvD8p0qU27RGFK9o/edit ... does anyone remember making callout boxes that say "share your story" -- ??

**Comment by natalieworth** [comment]
@WillatMozFdn Is it good to start on a graphic for this or does copy for teh call-out still have to be approved?

**Comment by WillatMozFdn** [comment]
Let's get started and no, we don't need any special approvals for this.
Firmly in the domain of stuff that Jen, Steph or I can create.

How about ... "Share your copyright story" -- ??

Plain, but will do the job, I think?

 - W

**Comment by TheoChevalier** [comment]
/me grabs his French localizer hat:

French: "Racontez votre anecdote sur le droit d’auteur"
Shorter version if it’s too long "Votre anecdote sur le droit d’auteur" (Your copyright story)

**Comment by natalieworth** [comment]
@lovegushwa @beccaklam Copyright callout is here https://redpen.io/gme2505b258497553d
If it's good to go I'll drop the google drive link in here.
@WillatMozFdn What languages do we need localized for this one?

**Comment by WillatMozFdn** [comment]
French and German ... those are the only 2 languages into which we
localized the original survey.

Thanks for asking!

 - W

**Comment by TheoChevalier** [comment]
@natalieworth And here is German "Erzählen Sie Ihre Geschichte zum Urheberrecht"

**Comment by natalieworth** [comment]
Thanks for the translations @TheoChevalier 
@WillatMozFdn I've got the versions exported at 1x and 2x here: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0bldacFNGWllGTm8
cc @stephaniemcv 

Let me know if you need anything else for these! THanks :)
