### ISSUE TITLE
Implement share progress / Build Share page

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#767]
I didn't see an issue for the actual implementation.

We have a significant l10n worry here. The share progress UI is in English. We can provide translations for content, but not the UI. We have two options.

1. We can do what Paul got back from the share progress peeps: "Thanks for reaching out. We don't have an automatic feature to support localization currently. However, we can help with providing share page versions in different languages by using a multi-lingual wrapper that provides translations based on a URL parameter. The action would need to be sent via email with segmented audiences based on country/language spoken to give each audience the correct link. If you're interested in that option, we can create the wrapper for you. All we would need on your end would be the desired translations for the share page. Let me know what you think!" Not sure how I feel about that, or how easy it would be to maintain/make changes, or how fast they would be with this. Frankly, it's sounds all sorts of bad.

2. Build a share page. We could still use share progress for English if we want. This is my vote.

Either way, we need to localize something...

cc @hannahkane @TheoChevalier

**Comment by TheoChevalier** [comment]
I share @ScottDowne’s concerns with 1, this will probably won’t scale with 25 locales (while prop 2. will), and even if we downscale the number of supported locales for share progress, maintenance won’t be easy. What if strings don’t fit in the UI? At first glance, using Firefox Devtools, I broke their UI with French translations. It’s been built with English in mind, sadly. There could be all kind of problems: encoding, truncations, hardcoded strings, markup required, them pasting the wrong language… So, we also need to keep that in mind if we go this way. While this may look easier to setup, we might hit issues later on.

**Comment by hannahkane** [comment]
Any downsides to option 2, aside from the obvious extra effort?

**Comment by ScottDowne** [comment]
Option 2 probably feels like more work, but my bet is option 1 is riddled with hidden costs.

**Comment by hannahkane** [comment]
We don't get the ShareProgress features for A/B testing, right? Or are you suggesting we build that in, with something like Optimizely?

**Comment by TheoChevalier** [comment]
ShareProgress would be used for en-US only, so A/B testing can still be done in English (but not for the other locales). Once we know which version is the winning one in English, we will swap it out for all locales.

**Comment by ScottDowne** [comment]
What Theo said.

I was also going to add we could do all this in optimizely too.

We could also use share progress to setup just buttons, and not pages, which can be implemented into our page, which can support AB testing though share progress. The issue with this is we still have the scale issue that theo mentioned.

**Comment by hannahkane** [comment]
Got it; this all makes sense. I'd also vote for Option 2, with a localized Share page, and using EN ShareProgress test results to inform the other locales.

**Comment by hannahkane** [comment]
@ScottDowne - I updated the ticket title to reflect the two tasks this ticket morphed into, as per discussion in stand today. Would you rather have two different tickets?

**Comment by ScottDowne** [comment]
We can keep them as one for now.

**Comment by hannahkane** [comment]
See #770 for design.

**Comment by ScottDowne** [comment]
Just a small update. We have a stubbed share page, and we also have share progress in English.

i just need to add buttons for native share. Then we can close.

**Comment by ScottDowne** [comment]
Should be done now: https://changecopyright-org-staging.herokuapp.com/de/share

Closing.

Any issues found should be filed in new tickets.

🚀 🎉 🎈
