### ISSUE TITLE
Implement privacy and signup checkboxes

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#768]
Right now the site has:

<img src="https://cloud.githubusercontent.com/assets/197334/23640995/f12e406e-02be-11e7-90b5-33ea35c765bf.png" width="300">

There was talks today in chat about changes needing to be made here. I think we should have this request tracked. We likely need two checkboxes. Looking similar to (but with different button copy):

<img src="https://cloud.githubusercontent.com/assets/197334/23641429/9d55f182-02c1-11e7-8ef9-dd02bfe2a593.png" width="300">

Changes to this also are going to require some l10n resources, I think.

@TheoChevalier @hannahkane @shaghdoosti

**Comment by hannahkane** [comment]
Sorry if this isn't the right place to note this, but it seems that we'll likely need some special treatment of folks coming via the promotional email, as we did with the Open Data campaign. That might be more than hiding the email checkbox; it might be actually offering a different CTA (e.g. Share).

I believe that decision will be made during an email-focused meeting today at 10:30am PT.

**Comment by hannahkane** [comment]
Confirming that the "you can email me" checkbox is required to be checked. If user doesn't check it, we should display an error and not submit the form.

**Comment by TheoChevalier** [comment]
@shaghdoosti Any update from legal on the copy?

**Comment by ScottDowne** [comment]
Dual checkboxes, without copy are on staging.

**Comment by shaghdoosti** [comment]
It should be the same copy as open data.

**Comment by ScottDowne** [comment]
Yup. Just waiting for it to go through l10n then should be good to go.

**Comment by TheoChevalier** [comment]
Done, I’ve exposed the strings for localization
