### ISSUE TITLE
DUE ASAP: Design for Share page

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#770]
As discussed in Stand, we'll need a design for a custom Share page or modal.

Copy for the shareable content will come from #741, but not sure we have copy for the page itself. @shaghdoosti?

**Comment by shaghdoosti** [comment]
Here's the copy: https://docs.google.com/document/d/1qSiHHO3talrhdr2HKI2LSnhazkcqE-1B94O7WA_MHmo/edit

**Comment by shaghdoosti** [comment]
If there's any other copy you need @ScottDowne @lovegushwa let me know.

**Comment by TheoChevalier** [comment]
I think we will at least need the main message in the page, something like “Thanks for signing up! Will you use one of the buttons below to spread the word about copyright reform?”

**Comment by shaghdoosti** [comment]
Great - I updated the google doc with a title for the page.

**Comment by beccaklam** [comment]
@TheoChevalier @shaghdoosti @hannahkane @lovegushwa @ScottDowne here are some mockups for the thank you page:
https://redpen.io/p/jgf786c9179496b8b4 <-- redpen for comments
@HPaulJohnson Can you look over the copy for this share page?
Desktop:
![desktop](https://cloud.githubusercontent.com/assets/20977376/23680137/29727a82-0358-11e7-9c08-fafe5ef30442.png)

Tablet:
![tablet portrait copy](https://cloud.githubusercontent.com/assets/20977376/23680167/34f00ab4-0358-11e7-9693-0b0072134b66.png)

Mobile:
![mobile portrait fullpage](https://cloud.githubusercontent.com/assets/20977376/23680175/3ae73f82-0358-11e7-916a-4950cec5bda3.png)

**Comment by hannahkane** [comment]
WFM! Thanks, @beccaklam.

**Comment by HPaulJohnson** [comment]
Looks good @beccaklam. 

What do you think about dropping the "share by," "post to," and "share on" copy and just using the icons or "email," "facebook," "twitter". I think it is clear enough to people what we are asking them to do here and the fewer words the better.

**Comment by beccaklam** [comment]
That work, I'm assuming we're just taking the buttons from share progress?

**Comment by TheoChevalier** [comment]
I’ve exposed the strings for localization

**Comment by beccaklam** [comment]
@ScottDowne @hannahkane @HPaulJohnson @TheoChevalier Small icon version:
The buttons will be generated using share progress using their create new share buttons feature.
![desktop](https://cloud.githubusercontent.com/assets/20977376/23708305/811e6b3e-03e3-11e7-9170-f64adbdcb144.png)
![tablet portrait copy](https://cloud.githubusercontent.com/assets/20977376/23708307/812176c6-03e3-11e7-98fc-4d452563a7dd.png)
![mobile portrait fullpage](https://cloud.githubusercontent.com/assets/20977376/23708306/811fb2e6-03e3-11e7-9b54-fce5ae1b92f5.png)

**Comment by hannahkane** [comment]
Nice. Closing this ticket.
