### ISSUE TITLE
Open Data Day impact report and follow-up actions

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#771]
@vojtechmzl and I will work on a deck to summarize the impact as compared to goals and objectives.

Should include:
 - [x] Goals and objectives of campaign; analysis of whether they were met
 - [x] Impact, including:
   - [x] Signatures
   - [x] New emails
   - [x] Shares 
   - [x] Analysis of traffic patterns

Other potential follow-up actions:
 - [x] Schedule retrospective
 - [ ] What are the engagement follow-up tasks? What's happening with the signatures themselves? How are we engaging signatories next?
 - [ ] What happens with the website itself? Are we keeping it live indefinitely, including the email collection feature? 

cc @shaghdoosti @lovegushwa @ScottDowne @WillatMozFdn @stephaniemcv @stephwright

**Comment by ScottDowne** [comment]
- [ ] Deliver the sheet data to life cycle marketing team to get it migrated into Salesforce.

**Comment by shaghdoosti** [comment]
Who is responsible for this?

**Comment by hannahkane** [comment]
@shaghdoosti - are you asking about the migration to Salesforce in particular or the whole thing? I filed this ticket, but wasn't really sure who was responsible for the various pieces of follow-up.

@ScottDowne - are you responsible for getting the sheet data to marketing? I think we need to answer the question about what we're doing with the site / ongoing data collection first. @shaghdoosti - are you the right person to answer that question? I'm wondering if we should change the form to be just an email sign-up, so that we're no longer collecting signatures. 

I'll schedule a retrospective. We could use that time to talk about follow-up tasks if needed, though ideally we can handle that elsewhere so the retro can focus on identifying learnings from the campaign.

**Comment by stephaniemcv** [comment]
Just FYI, migrating the signatures into Salesforce is going to happen Q2 Sprint 1, (21 Mar 2017-04 Apr 2017) along with the work on Basket so we can flow in petition data directly without putting it in a sheet. This will be our interim solution until we get a platform setup (Soapbox or other?).

Looking forward to the retrospective.

**Comment by hannahkane** [comment]
Thanks, @stephaniemcv.

Should we just keep the petition open until Q2 then?

**Comment by stephaniemcv** [comment]
Yup!

**Comment by hannahkane** [comment]
@stephaniemcv - have the signatures been migrated?

**Comment by stephaniemcv** [comment]
Unfortunately, no. This is still on my plate.

**Comment by stephwright** [comment]
@hannahkane there is some further action happening on this petition.  It's being referenced in an announcement coming out this week as well as part of events working w/ Advocacy team leading up to March.

**Comment by stephaniemcv** [comment]
Just curious, how long do you think we'll be collecting signatures?

**Comment by stephwright** [comment]
That's a good question... I need to talk to a few folks about that.  At a conf this week so pretty blocked up re: trying to schedule convos.  I can try to get an (better) answer for you by EOW.

**Comment by stephaniemcv** [comment]
Sounds good, thank you!

**Comment by stephwright** [comment]
Talked to Chris & Ashley and we'd like to keep it open as long as we're still promoting and obtaining signatures.  The current plan around that is a promotion leading up to Tax Day and around the March for Science.  If we could keep this open until a few days after the March, that'd be ideal.

How does that sound?

**Comment by stephwright** [comment]
Oh... btw... can anyone tell me how many signatures we have so far?  Sara used to be my goto to find that out.

**Comment by hannahkane** [comment]
I see 15,653 responses as of right now.

**Comment by stephwright** [comment]
Thx @hannahkane !  Will pass that info along.

**Comment by hannahkane** [comment]
@stephaniemcv - do you have an update on migrating the signatures?

**Comment by stephaniemcv** [comment]
Goal is to have them in by 5/17. Not sure how full your plate is, but there's science email campaign debrief, you want in?

**Comment by hannahkane** [comment]
@stephaniemcv ^ sure, if I haven't already missed it!

**Comment by hannahkane** [comment]
@stephaniemcv - do you think we're good to close this issue? We're aiming to remove the form from the site this week. Will we or have we gotten all the signatures into the right place?

**Comment by stephaniemcv** [comment]
I think we are good to close the issue. Signatures are not loaded yet as we're still working out some infrastructure conventions around legacy data.
