### ISSUE TITLE
Brainstorming for Healthy/Unhealthy Website

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Advocacy#772]
Detailed description of work:
Continue thinking of ideas for healthy/unhealthy internet website. 

*Start date: March 8 2017* 
*Due date: March 9, 2017* 

CC: @lovegushwa

**Comment by hannahkane** [comment]
Can we close this?

**Comment by hannahkane** [comment]
Or...maybe I don't know what this is. Nevermind. :)

**Comment by beccaklam** [comment]
Yes we can close! The madlib is basically this.
