### ISSUE TITLE
Replace logo on donate page

### ISSUE THREAD

**Issue by WillatMozFdn** [MozillaFoundation/Advocacy#773]
Detailed description of work: Get our new logo/wordmark onto https://donate.mozilla.org/ .  This will take some careful design; Scott and I looked at it and cannot figure a way to do this easily and still stay in brand guidelines.

*Start date: March 8, 2017* 
*Due date: March 22, 2016* 

(due date not firm)

CC: @beccaklam @lovegushwa

**Comment by hannahkane** [comment]
Just out of curiosity, what's the deadline related to?

**Comment by WillatMozFdn** [comment]
Nothing in particular.  Not a firm due date.

**Comment by hannahkane** [comment]
Did this get done? If not, should we push to next week when designers are back in the office?

**Comment by hannahkane** [comment]
@lovegushwa - how do you want to prioritize this? It doesn't seem urgent, but is it something you want to try to get done this week?

**Comment by WillatMozFdn** [comment]
Hey team ... moving along on this one ... on or about **July 15th**, our MoCo colleagues will start including a donation link in the footer of their emails.  (Yay!!!!)  So I'd like to have the new logo in place on donate.mozilla.org by then.  Do-able?  Jordan, I'll ping you about this today (or just show up to the Advo stand-up at 12:30 ET, my calendar is finally clear of conflicts at that time today.  :-) ) 

cc @lovegushwa @hannahkane

**Comment by hannahkane** [comment]
Adding this to the June 23 milestone and to the media team's weekly sprint planning doc to remind folks to discuss this on Monday. This should be considered a commitment - just a reminder to discuss it and see when it can be done.
