### ISSUE TITLE
QA: broken link on Resources page 

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#774]
The link to "Mozilla position on the Commission proposal for a directive on copyright in the digital single market" goes to a folder on Google drive. Should it go to a particular file?

**Comment by ScottDowne** [comment]
I can confirm that's the correct link that was in the google doc. Who should we cc to get an updated link?

**Comment by hannahkane** [comment]
cc @Melechuga ^

**Comment by Melechuga** [comment]
Hey @hannahkane, I mentioned this in the google doc and it was suggested that we could host this?
The[ 1-pgr is here](https://drive.google.com/a/mozilla.com/file/d/0BybHRPPm37TJS0R6cFRpa0x5SmdGWk82YjN2M1Bla19hN3hZ/view?usp=sharing
) (not sure what happened with the link); also updated in the [Google Resources page](https://docs.google.com/a/mozilla.com/document/d/1oH0AHjP_SpCtatrmPxkOEJDzz8sUWQ_P5PGBdqCjNgU/edit?usp=sharing)

**Comment by hannahkane** [comment]
I think we just need to change the link. I remember suggesting we could host it, but is there anything wrong with linking to a google hosted file?

**Comment by ScottDowne** [comment]
Thanks, should be fixed now.
