### ISSUE TITLE
Small typos in one of the German blog graphics for DPD

### ISSUE THREAD

**Issue by WillatMozFdn** [MozillaFoundation/Advocacy#776]
https://cdn-images-1.medium.com/max/1000/1*Vjv68KFWe3JfnI37pTqR2g.png

(last image on https://medium.com/@mozilla/hacker-verfolger-und-spione-die-ergebnisse-unserer-datenschutzumfrage-70459f25ea60#.wvclsbaae)

Germans say there are two issues: 
"It looks mostly fine, but the
final image (about which sources to trust) contains a grammar error
(again, sorry), which is now fixed in the strings (Der Regierung → Die
Regierung) but also contains an improper line break. The first word
should break as „Vertrauens-würdigste“, if possible."

*Start date: March 9, 2017* 
*Due date: March 10 2, 2017* 

CC: @lovegushwa @beccaklam

**Comment by beccaklam** [comment]
@WillatMozFdn I'll fix that.

**Comment by beccaklam** [comment]
Changes have been made with this graphic:
![artboard 3 copy](https://cloud.githubusercontent.com/assets/20977376/23798527/13179c8c-0573-11e7-9941-4bf607176fa9.png)

**Comment by hannahkane** [comment]
@WillatMozFdn - are we good to close this issue?

**Comment by WillatMozFdn** [comment]
yes, please close.  Thanks!
