### ISSUE TITLE
DUE MARCH 13: Pi Day Fundraising Email Graphics

### ISSUE THREAD

**Issue by caltrider** [MozillaFoundation/Advocacy#777]
Hey @lovegushwa , here's my first attempt at a ticket for the two Pi Day email graphics.  
Hopefully I got it right. If not, feel free to tell me what I got wrong.

Due date on this would hopefully be no later than mid-day Monday to give Will and Steph time to get the email ready to go first thing Tuesday. The email has been approved by everyone but Marshall and Mark, so hopefully it is close to final approval and this won't change. Wanted to go ahead and get things rolling so we're not scrambling too much.

Here's the [link to the email draft](https://docs.google.com/document/d/1NYMmoAyIXl9LNp5D8aBYhHcuyBWqr7yWSWn2OTCDZCk/edit) for context for these graphics.

**Graphic #1: Literal Pie Graphic** (should be 600x400px (or 500)
I imagine this as an actual pie, if possible, with 6 equal slices labeled with the labels below.
There's a fair amount of text (sorry about that...it was the best I could do).
Bonus points if you can work π and/or mozilla into the pie 

Here's the text in the email setting up the graphic:

"Picture Mozilla as a pie. Here’s what that pie looks like:"

And here's the text for the graphic [pie graphic with 6 equal slices of the pie labeled:]
Fight for a healthy internet
Stand up for privacy online
Teach the web
Build an awesome browser
Innovate with our community
Increase access to the web

**Graphic #2:  Call Out Box** (250x250px)
Celebrate Pi Day with a Donation to Mozilla
[donation boxes with the following amounts: $3.14, $15, $9, $26]

Here's how they did that for the snippet:
![image](https://cloud.githubusercontent.com/assets/22063437/23800451/b05c6856-0569-11e7-8398-165c2ead95b4.png)

*Start date: March 10, 2017* 
*Due date: March 13, 2017* 

CC: @HPaulJohnson, @WillatMozFdn

**Comment by hannahkane** [comment]
This is a great ticket, @caltrider!

Some totally meta things having nothing to do with the actual work described in the ticket:

- I'm adding a label to describe a functional area, in this case "design" and to associate it with a project, in this case "Pi Day" (a label I just created).
- Also adding it to the "March 17 milestone" since, per request, we use milestones to differentiate each week. In the case when the work is needed before the end of the week, it can be helpful to put the due date in the name of the ticket, so I've done that here.
- Will let @lovegushwa add an assignee.

**Comment by WillatMozFdn** [comment]
@stephaniemcv needs to be on on this one ... she's taking point on this email (I'll be working on a french event email for about the same time/maybe a day later.)

**Comment by lovegushwa** [comment]
@caltrider so the small callout (graphic 2).  What about "Donate some dough for our pie" ?

**Comment by lovegushwa** [comment]
@caltrider love the pie snippet icon. Can you use it?

**Comment by caltrider** [comment]
@lovegushwa @natalieworth Oh, I LOVE it!  Yes! It's brilliant.

**Comment by caltrider** [comment]
@lovegushwa Use the pie snippet icon for what?

**Comment by lovegushwa** [comment]
@caltrider can we use the pie icon as is for this years snippet?

**Comment by caltrider** [comment]
@lovegushwa Oh yeah, I'm totally cool with that.

**Comment by lovegushwa** [comment]
@stephaniemcv here is the callout: https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvMWJTRF9jUE9MSlE/view?usp=sharing

and the pie chart:
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvRTY2S0JYSjJRdXM/view?usp=sharing
