### ISSUE TITLE
Copyright snippet 

### ISSUE THREAD

**Issue by shaghdoosti** [MozillaFoundation/Advocacy#778]
Hey -

Wes sent around snippets that we used for copyright last year - these have already been localised. I think these two would work just as well this time around and would save us having to design a new icon and localizing text again. 

Let me know if this sounds good and I'll put it in motion: 

![screen shot 2017-03-10 at 9 56 53 am](https://cloud.githubusercontent.com/assets/13626384/23806835/1749f46c-0578-11e7-82a2-9bec27627e3c.png)

@TheoChevalier @lovegushwa @HPaulJohnson @hannahkane @ScottDowne @beccaklam

**Comment by TheoChevalier** [comment]
Thanks Sara, this sounds like a good idea. Which locales are targeted with those snippets? Just checking we support them all on the new website

**Comment by shaghdoosti** [comment]
Well - which languages do we support on the website? Then I'll ask the snippet team for those locales?

**Comment by TheoChevalier** [comment]
Locales that are 100% complete:
ast, bg, cs, de, el, es, et, fr, fy-NL, ga-IE, hu, it, nl, pl, pt-PT, sk, sl, sv-SE

**Comment by TheoChevalier** [comment]
> We may get Polish by Monday, too.

Correction, Polish is now done

**Comment by hannahkane** [comment]
This is live, right? Can we close this issue?

**Comment by TheoChevalier** [comment]
Yup, this can be closed
