### ISSUE TITLE
Locale negociation doesn’t work on https://www.changecopyright.org/

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/Advocacy#779]
Locale negociation — being redirected to `https://www.changecopyright.org/fr` for instance if you’re using a browser in French — doesn’t work with the prod domain. Everyone is redirected to en-US (so, `https://www.changecopyright.org/en-US`)

It works here: https://changecopyright-org-production.herokuapp.com/
And on staging too: https://changecopyright-org-staging.herokuapp.com/

@ScottDowne and I think it’s something at the domain level, and probably the artifact from NB @cadecairos mentioned, but filing to track this and make sure this is the cause.

CC @cadecairos

**Comment by TheoChevalier** [comment]
To test, just set a supported locale (French for instance) as default language for content in Preferences > Content > Language, then load https://www.changecopyright.org/

**Comment by ScottDowne** [comment]
Was chatting with giddy and it looks like the domain wasn't set to properly
send lang headers. We fixed. If that was actually the prob it might work in
20 mins or so.

**Comment by ScottDowne** [comment]
Worked for me!

**Comment by TheoChevalier** [comment]
Same here! Thanks guys :)
