### ISSUE TITLE
Create a Makerparty/nationbuilder RACI metrix

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#78]
https://en.wikipedia.org/wiki/Responsibility_assignment_matrix

Requested in: https://docs.google.com/document/d/19Hlxw4ZABIbcYog8VJdAYfdhjniiqtcV1gwkD25MA1w/edit

Responsible:
Accountable:
Support:
Consulted:
Informed:

**Comment by damiankay** [comment]
Hey @ScottDowne - what aspect of the project is this RACI matrix for? I can take this on, but just want to be clear.

**Comment by ScottDowne** [comment]
@damiankay I think just the maker party event platform build with nationbuilder.

**Comment by damiankay** [comment]
See the following document for a RASCI matrix:
https://docs.google.com/document/d/1b0U2wUi7aPwfUa8v5hcXC8UtqueyxgBZQuK1Nsqf5wo

This has been approved by George, Sara, and Chris
