### ISSUE TITLE
News Matrix sample content

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#780]
To kickstart the News Matrix, let's collect a set of content to play around with for the initial design. We can use this to test the axes (just checked, that is in fact the plural of axis), and have real data to use for design. Can also get a sense of how much effort is involved in collecting, curating, and editing content for a typical matrix.

**Comment by caltrider** [comment]
The sample content can be found in the [News Matrix brief doc](https://docs.google.com/document/d/1KSd7rdKclHlsJCYoZLZGg7sYuBfZ5t5-Zf6rhppuNuI/edit#) down at the bottom:

https://docs.google.com/document/d/1KSd7rdKclHlsJCYoZLZGg7sYuBfZ5t5-Zf6rhppuNuI/edit#

I created this [story drop doc](https://docs.google.com/document/d/1BZwGKe6iOPdn_YGkzJ-eilEEDmHVgiw50CYNT88F2u4/edit) and shared with everyone for the ongoing, weekly content. I'll collect all the stories for the week here and then organize them each Thursday and share with the designer working on the matrix that week.

https://docs.google.com/document/d/1BZwGKe6iOPdn_YGkzJ-eilEEDmHVgiw50CYNT88F2u4/edit

**Comment by hannahkane** [comment]
@caltrider - awesome! Should we close this ticket now since the sample content is done?

**Comment by caltrider** [comment]
@hannahkane Yeah, I think that's OK.  I'll be doing each week's content in this [Story Drop doc ](https://docs.google.com/document/d/1BZwGKe6iOPdn_YGkzJ-eilEEDmHVgiw50CYNT88F2u4/edit)from here on out.
