### ISSUE TITLE
Design: News Matrix template

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#781]
Use content from #780 to come up with a design that's flexible enough to support future editions of the matrix.

**Comment by beccaklam** [comment]
latest iteration:
![news matrix 3](https://cloud.githubusercontent.com/assets/20977376/24368364/287b99e2-12ee-11e7-98f2-31dea9ea4444.png)

**Comment by caltrider** [comment]
@lovegushwa @beccaklam 
Here's that info for the design:

Title:  This Week in the Web
2nd Line:  The TL;DR of All Things Internet
Footer: Thin underneath the matrix that says “Love these? Get them in your inbox each week. Sign up at XXX”
Y (vertical) Axis:   (our version of high brow/low brow)
Top: Nerd
Bottom : Noob
X (horizontal) Axis:  (our version of awesome/awful)
Left: Downvote
Right: Upvote
Design Ideas:
Internet look at feel
Easy to read the blurbs in each quadrant
Shared on:
Thinglink (which will embed into websites)
Reddit
FB
Twitter
Instagram ???

**Comment by lovegushwa** [comment]
@beccaklam added some comments to redpen: 
https://redpen.io/qu170751bd9a16f608

**Comment by beccaklam** [comment]
@caltrider @hannahkane @lovegushwa 
Latest iteration based on feedback:
https://redpen.io/nc32dbebb666432912<-- redpen for comments
![news matrix 5a](https://cloud.githubusercontent.com/assets/20977376/24475163/fefc1e42-149c-11e7-8311-b7052a6c8bf5.png)

**Comment by beccaklam** [comment]
With date:
![news matrix 5b](https://cloud.githubusercontent.com/assets/20977376/24508496/96b7794a-1531-11e7-9958-a7431e2bf49c.png)

**Comment by beccaklam** [comment]
Date Option #2:
![news matrix 5c](https://cloud.githubusercontent.com/assets/20977376/24509457/6b639668-1534-11e7-92d4-cd9e562de934.png)

**Comment by beccaklam** [comment]
Newest iterations:
https://redpen.io/wk196ad4118bf9eae3 <-- redpen for comments
![news matrix 6](https://cloud.githubusercontent.com/assets/20977376/24559229/eddf9c4a-160b-11e7-8d9d-b575ea561c71.png)
![news matrix 6a](https://cloud.githubusercontent.com/assets/20977376/24559232/ef5533be-160b-11e7-8a0e-39faa168c554.png)

**Comment by beccaklam** [comment]
@lovegushwa @caltrider Newest Iteration:
https://redpen.io/hfa422ad52394748c2 <-- redpen for comments
![news matrix 7a](https://cloud.githubusercontent.com/assets/20977376/24763217/ba30f5a8-1abe-11e7-963e-232287eca5be.png)

**Comment by caltrider** [comment]
@beccaklam @lovegushwa 
I love it!  Looks great.  Great work!

Just realized, in the footer, we should probably take out "each week". So it should read:
"Love these? Get them in your inbox. Sign up here." 

Also, should there be a Mozilla logo on it some where?

I have this week's content just about read to send to build this week's first matrix. Look for it shortly.

**Comment by beccaklam** [comment]
@lovegushwa @caltrider April 1 News Matrix first draft, the images need some work I can clean/brighten them up in the morning:
![news matrix april 1](https://cloud.githubusercontent.com/assets/20977376/24775926/d2a63f0c-1aec-11e7-97fe-054abafb8973.png)

**Comment by lovegushwa** [comment]
@beccaklam Looking great overall! 

- the inside of the B on NOOB is missing! 
- we should connect on editing images
- some of the dots are not centered or constantly spaced from the block of copy, I think we can solve this with how the temple file is setup
- @caltrider I think we should could cut down on the amount of copy for the next one.

**Comment by hannahkane** [comment]
Donezo!
