### ISSUE TITLE
Finalize Protest Sign Remix concept

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#782]
Brief is [here](https://docs.google.com/document/d/15omlkFBMtQupXvcREQ1ShNuGhigukkwAyLFFhvx8jds/edit)

We need to finalize the concept so we can assign appropriate design and development resources, and file the appropriate implementation tickets.

**Comment by lovegushwa** [comment]
@hannahkane seeing if @flukeout is interested

**Comment by hannahkane** [comment]
Closing this as the plan has changed. @lovegushwa and @caltrider - feel free to file new tickets for the Science March work.
