### ISSUE TITLE
Design: Iterate on News Matrix landing page

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#783]
Dropping some notes in here from a conversation I just had with @HPaulJohnson. Hoping interested people can have a discussion around this while I'm out tomorrow and Friday.

@beccaklam's [wireframes](https://redpen.io/p/sb0e5aa8bd56c0ba5e) are a kickass exploration of what an in-depth hub could look like, with some nice ideas about tailored subscriptions, increasing the shareability of content, and building cool viewers for individual projects. Definitely meets the requirements outlined in [the brief](https://docs.google.com/document/d/1Kc-m56qXy_EC6wD19voQb3a24e_NoU3hQELW4EGPA4E/edit).

Given a desire to ship this within 2-3 weeks, as well as a need to hone in on a key result (1M subscribers), Paul and I would like to propose a narrower version of the exploration.
 * we think that the portfolio version in the wireframes is likely the right starting point (as opposed to the Feed version). 
 * For this rollout, we suggest a single page, rather than a full website with navigation and subpages. We need to identify the projects that will be ready to feature at launch, but it likely won't be so many that we need the topic sub-pages right away. Nor will we need individual pages for the projects themselves. Instead, each featured project can simply link out to wherever it currently lives.
 * For now, we can focus on a single general list sign-up, rather than the content-specific sign-ups, since we don't have that content ready to go (file under: dope idea for the future)

**Comment by hannahkane** [comment]
cc @lovegushwa

**Comment by hannahkane** [comment]
[Latest iteration](https://redpen.io/cn6f36ef68c1d5e99f) looks great, but likely needs another round based on feedback from @HPaulJohnson in the redpen as well as a team discussion around the requirements listed in #786

**Comment by beccaklam** [comment]
@hannahkane @lovegushwa 
Latest iteration:
https://redpen.io/xadede11a8016b38f3<-- redpen for comments
![news matrix landing page](https://cloud.githubusercontent.com/assets/20977376/24475196/1fec782c-149d-11e7-9664-f741563391c9.png)

**Comment by beccaklam** [comment]
Archive UI: Still need to work on footer
https://redpen.io/ym854ba2d8dd56f6ee<-- redpen for comments
![news matrix landing page](https://cloud.githubusercontent.com/assets/20977376/24509998/efcf2178-1535-11e7-9c53-65b02b643c55.png)

![news matrix landing page copy 2](https://cloud.githubusercontent.com/assets/20977376/24510009/f66b6082-1535-11e7-8eaa-1134f50b340a.png)

**Comment by lovegushwa** [comment]
Worked with Rebecca on some tweaks to the news matrix and blog template this morning. Should see updates tomorrow.

**Comment by beccaklam** [comment]
Newest iterations:
https://redpen.io/mq02462ef5d9a169bd <-- redpen for comments
![news matrix landing page tron](https://cloud.githubusercontent.com/assets/20977376/24559258/117f8d18-160c-11e7-8ffc-92a2fdbefb20.png)
![news matrix landing page wired](https://cloud.githubusercontent.com/assets/20977376/24559260/1180e3c0-160c-11e7-998f-9b4932ff8e90.png)
![news matrix landing page wired - archive functionality](https://cloud.githubusercontent.com/assets/20977376/24559259/1180ee1a-160c-11e7-88aa-0adf361e72b9.png)

**Comment by hannahkane** [comment]
woohoo! These look great. What do we need to do to get to Done?
 - [ ] OK on design elements ( @lovegushwa? )
 - [ ] Final copy for page, including form ( @caltrider? )

@beccaklam - what else do you need to be considered Done?

**Comment by caltrider** [comment]
Hey @lovegushwa @hannahkane @beccaklam 

Here's the copy for the sign-up side bar:

Like What You See? (headline)
There's more what that came from.
Sign up to get great stuff in your inbox.
Button Text: Sign Me Up (this works good for me)

**Comment by hannahkane** [comment]
I'm going to close this, since we've moved to the build phase.
