### ISSUE TITLE
Add Captcha to Donation

### ISSUE THREAD

**Issue by roseregina** [MozillaFoundation/Advocacy#784]
Investigate feasibility (and desirability) of addition a captcha to the donation process, possibly through Google's invisible recaptcha

*Start date: March 17 2017* 
*Due date: June 1, 20167* 

CC: @stephaniemcv @vojtechmzl

**Comment by WillatMozFdn** [comment]
I think we can close this one now?  @ScottDowne & @cadecairos

**Comment by cadecairos** [comment]
Yup, and looks like we did it before 20167, which is nice.
