### ISSUE TITLE
Add rejection notice for Stripe.com failed donations

### ISSUE THREAD

**Issue by roseregina** [MozillaFoundation/Advocacy#785]
Add message to appear to donor after a Stripe donation attempt is rejected that they should email donate@ for assistance

--> This will allow us to switch to having stripe automatically reject all "elevated risk" transactions, since the vast majority are definitely or probably fraud. 

*Start date: March 17, 2017* 
*Due date: May 1, 2017* 

CC: @stephaniemcv @vojtechmzl

**Comment by ScottDowne** [comment]
I'm pretty sure we can close this now.
