### ISSUE TITLE
Build News Matrix promo/archive page

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#786]
Design from #783

Functional requirements:
 - Should be build in a modular way so that it can easily be reproduced with different content (e.g. the upcoming Safety Tips content)
 - Should include Optimizely and Analytics
 - Should be localizable, using preferred l10n workflows. [Question for @HPaulJohnson and @caltrider - even though we'd like the infrastructure for future variations of this page to be localizable, can you clarify whether the initial News Matrix page will be localized?]
 - Should include Salesforce integration
 - Should allow for different states, i.e. a "not on list" state that includes a sign-up form, and a "on list" state that promotes a Share CTA, and doesn't include the sign-up form
 - Should be easy for admins to update content weekly
 - We need to decide where this page lives. Suggestions?

cc @caltrider @lovegushwa @beccaklam @natalieworth @simonwex @TheoChevalier

**Comment by hannahkane** [comment]
@lovegushwa @ScottDowne @beccaklam @caltrider - any thoughts on where this page should live? Should it have a unique url? Or something like advocacy.mozilla.org/matrix?

**Comment by lovegushwa** [comment]
@hannahkane @caltrider I'm ok with advocacy.mozilla.org/matrix ... however we are collaborating with the internet health MoCo team on this, could impact our decision?

**Comment by lovegushwa** [comment]
@hannahkane @beccaklam @ScottDowne so this requirement may have been lost in the mix but @caltrider 's idea was incorporate live links to content just like: http://nymag.com/arts/all/approvalmatrix/approval-matrix-2016-09-05/

They use the service https://www.thinglink.com/ to do this.
@ScottDowne whats needed to move this forward?

**Comment by ScottDowne** [comment]
So, thinglink is paid, but it's cheap, and it's pretty handy. We can probably use it.

It looks like we can use them as an iframe. I'm prototyping a system where after creating the thinglink using thinglink, click their iframe embed, and paste that code into a file called `new-matrix-1.html` where the dash number goes up. The highest number gets displayed first. This way we can pretty easily just drop embed code into empty html files and put them into a directory, and have new content added via girhub, which can trigger a build on the site.

**Comment by hannahkane** [comment]
👍  solid plan!

just confirming - the archive will essentially be a list view of past matrices, right? will there be a way to link to a particular matrix? (not sure that's a real use case, just curious)

**Comment by vojtechsedlak** [comment]
Not sure if this is already the case, but just wanted to flag that it would be great to track each matrix as a separate pageview in Google Analytics. For the signup form and share buttons, we should also have our standard custom events in place.

In order to know how people engage with the matrices, I was wondering if we could also include custom events indicating when people click on a link within the matrix. In case that's possible, I've added a section to the [GA event syntax doc](https://docs.google.com/document/d/1HjOwcydEnfkX6tyd4MCt3tcEkloroyrKK5HDCQdmMMM/edit#). Please let me know if that makes sense or if you have any questions.

**Comment by ScottDowne** [comment]
@vojtechmzl Not sure how we would track thinglinks inside our page itself, as it's just an iframe.

We would need to rely on the metrics built into the thinglink platform.

**Comment by vojtechsedlak** [comment]
Oh right, it seems that thinglinks has some built-in analytics capabilities, so we should get some metrics from that.

**Comment by hannahkane** [comment]
Tiny copy edits based on the demo we saw during stand today:

I believe the copy on the form read: "There's more from where that came from." The first "from" should be removed.

Also, I believe the form field said "e-mail" instead of "email."

**Comment by lovegushwa** [comment]
@hannahkane @ScottDowne @beccaklam 

If we decide we want to eventually link our product pages together,  using the advocacy.mozilla domain seems like a better choice than weekintheweb.mozilla.org ... unless we are ok with domains changing as a user navigates between pages.

![screen shot 2017-04-05 at 4 57 48 pm](https://cloud.githubusercontent.com/assets/12228435/24731769/08d072a4-1a21-11e7-9332-fb70c9b75e49.png)

**Comment by hannahkane** [comment]
I'm going to close this ticket, and we can open new tickets for any remaining work, such as mobile optimization.
