### ISSUE TITLE
Determine where the Privacy landing page "lives"

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#788]
Discussed with @HPaulJohnson:
 * Though eventually the Privacy landing page (as well as any future variations) might end up on mozilla.org or on the Network site, for now, we're recommending it live on advocacy.mozilla.org
 * The advocacy.mozilla.org homepage could be updated to reflect the latest output from the team, with the Privacy landing page occupying the hero block, and moving the Encrypt project down to one of the featured items below the fold. 
 * Recommend we update the branding on the advocacy.mozilla.org landing page. i.e. replace "Mozilla Advocacy" wordmark with new mozilla wordmark (and no reference to advocacy). <- we should do this regardless of other decisions
 * Decision to be made about whether to provide navigation from pages like the Privacy Landing Page and the Encrypt landing page back to the homepage.

cc @caltrider @lovegushwa @beccaklam @natalieworth @ScottDowne @simonwex

**Comment by hannahkane** [comment]
cc @Melechuga - are you the owner of the Advocacy site?

**Comment by Melechuga** [comment]
@hannahkane I'm not sure what you mean; do you mean for this project specifically?

**Comment by hannahkane** [comment]
@Melechuga - sorry I wasn't clear. Maybe a better question is, would you like to be kept in the loop about any decisions we make about advocacy.mozilla.org? I'm not sure who "cares" about that site? Maybe Vanessa?

**Comment by hannahkane** [comment]
I'm going to close this for now. We still need to figure out where the "News matrix promo and archive page" lives, but I'll list that as a requirement on the [build ticket](https://github.com/MozillaFoundation/Advocacy/issues/786).

I think we need to have a larger conversation about infrastructure for advocacy content moving forward, with an eye towards understanding the connection/journey between advocacy content and network.
