### ISSUE TITLE
Remove apostrophe from resource on ChangeCopyright

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#789]
The first resource on [this page](https://www.changecopyright.org/en-US/resources) shouldn't have an apostrophe.

**Comment by ScottDowne** [comment]
Almost missed this :(

Building on staging now.

**Comment by ScottDowne** [comment]
On staging, building prod now: https://changecopyright-org-staging.herokuapp.com/en-US/resources

**Comment by ScottDowne** [comment]
This landed and I forgot to close the issue after confirming on prod: https://changecopyright.org/en-US/resources
