### ISSUE TITLE
Setup Nationbuilder/Makerparty sandbox

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#79]
Use nationbuilder sandbox to start a makerparty example for what we need.

The idea here is not for experimenting features, but to build in actual working features and start to get a release candidate.

Doesn't need to be sandbox, maybe they have a version that we can make private and just click public when it's ready.

Start to setup features we define in: https://github.com/MozillaFoundation/Advocacy/issues/75

**Comment by ScottDowne** [comment]
- [x] setup sandbox env
- [x] moving all responsible and accountable people into one sandbox

-- [ ] Each feature implementation has it’s own ticket -- happening in https://github.com/MozillaFoundation/Advocacy/issues/75

start getting it setup the way we like it with our current feature list, isn’t really done, but something people can look at.

Goal is to solidify our list of features. Find holes or issues we missed, and add or remove features from our list. It’s really a gut check on our list.

**Comment by damiankay** [comment]
@ScottDowne can you please share the sandbox with Jonathan Claudius? See #91

**Comment by ScottDowne** [comment]
Yup I can do this tomorrow.

**Comment by ScottDowne** [comment]
I slapped this page together http://makerparty-mozillasandbox.nationbuilder.com/

I'm using a default template, design is not something we need to look at here.

**Comment by damiankay** [comment]
Hey @ScottDowne - is this done, or do you still need to add anyone to the sandbox?

**Comment by ScottDowne** [comment]
Yeah, I think the sandbox permissions are pretty easy. If anyone else I missed needs access I can give it.

We still have an open task to file tickets for each feature, but I don't think that's super useful right now, too soon. So going to push that. We can do that in https://github.com/MozillaFoundation/Advocacy/issues/75
