### ISSUE TITLE
Need Callout box graphics for Copyright Campaign "Call your MEP" email

### ISSUE THREAD

**Issue by WillatMozFdn** [MozillaFoundation/Advocacy#790]
Let's use the same background & design we did for the copyright share your story email, that is, 
https://image.e.mozilla.org/lib/fe9915707361037e75/m/3/copyright-shareyourstory_callout_EN.jpg 

But for this new round of emails, the wording in the box for EN should be "Be a hero for copyright reform".  We'll also need to do DE, FR, ES and PL versions ... that string is going out for localization today (request prioritized over the localization of the rest of the email) so I hope to have those four phrases to you Monday.

Planning to launch the email early morning US time, Weds. March 29.

*Start date: March 24, 2017* 
*Due date: March 28, 2017* 

CC: @lovegushwa @beccaklam @TheoChevalier

**Comment by TheoChevalier** [comment]
Here are the German, French and Spanish translations for the call out:

https://l10n.mozilla-community.org/langchecker/?website=6&file=emails/2017/copyright_call.lang&action=translate&show#string6

**Comment by beccaklam** [comment]
Hey @WillatMozFdn @TheoChevalier I've finished the EN, DE, FR, and ES versions. Just waiting for PL.

**Comment by beccaklam** [comment]
![artboard 22 copy 3- 1x](https://cloud.githubusercontent.com/assets/20977376/24375607/f4b85b86-1306-11e7-8f67-a945d0e590cc.png)
![artboard 22 copy 4](https://cloud.githubusercontent.com/assets/20977376/24375609/f4ba3cd0-1306-11e7-967f-aaed8b2ff114.png)
![artboard 22 copy 5](https://cloud.githubusercontent.com/assets/20977376/24375610/f4bcdd28-1306-11e7-8340-aadebe2db919.png)
![artboard 22 copy 6](https://cloud.githubusercontent.com/assets/20977376/24375608/f4b8f550-1306-11e7-91a6-0cd03670b436.png)

**Comment by lovegushwa** [comment]
@beccaklam thank you.

**Comment by WillatMozFdn** [comment]
Beautiful -- thank you SO much!

 - Will

**Comment by TheoChevalier** [comment]
Polish is now ready! https://l10n.mozilla-community.org/langchecker/?website=6&file=emails/2017/copyright_call.lang&action=translate&show#string6

**Comment by beccaklam** [comment]
Thanks @TheoChevalier 
Here you go @WillatMozFdn 
![pl](https://cloud.githubusercontent.com/assets/20977376/24475782/09da41fc-149f-11e7-89c5-8d0a0f1e2c5e.png)

**Comment by hannahkane** [comment]
Are we good to close this?

**Comment by WillatMozFdn** [comment]
Yes, please go ahead and close -- I have all five versions (EN, DE, FR, ES,
PL) I need.
