### ISSUE TITLE
Design and Build: Madlib

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#792]
Just realizing we don't have a ticket for this, and I think we should!

As discussed at stand, I believe we decided to focus on the primary use case first (user adds awesome content), and then focus on the need for any moderation tools.

**Comment by lovegushwa** [comment]
The original concept sketch
<img width="927" alt="screen shot 2017-03-30 at 3 03 50 pm" src="https://cloud.githubusercontent.com/assets/12228435/24528174/3dea67e0-155a-11e7-9a62-797de0041825.png">

Where the madlib sits in the user journey
<img width="1411" alt="screen shot 2017-03-30 at 12 36 22 pm" src="https://cloud.githubusercontent.com/assets/12228435/24528190/50e86fcc-155a-11e7-821a-2b1b1ab0fedf.png">

**Comment by lovegushwa** [comment]
@hannahkane @ScottDowne @beccaklam 

In addition to contributing to the madlib a user should be prompted to:
- share the video (through share progress?)
- sign up to email  (we should promise some sort of followup content based on the ideas users contributed, similar to how we wrote a medium post after users filled out the privacy survey.)

**Comment by lovegushwa** [comment]
@hannahkane any thoughts on us prioritizing share vs signup?

**Comment by hannahkane** [comment]
I think it depends on the final functionality. Sharing might be more fun if you can share what you added vs. just sharing the tool.

**Comment by hannahkane** [comment]
@lovegushwa, can you clarify the step between the video and the survey/madlib? Is it that at the end of the video they can click on a link to go to one of those as an optional next step? Or does the video itself set up the survey/madlib for the user?

(Apologies, because I think you probably explained this on a call, but I just realized I missed a piece.)

**Comment by lovegushwa** [comment]
@hannahkane no problem. You would click a link below the video in a users facebook feed for example. That link would take you to the survey or the madlib (it's an AB test so one or the other.)

**Comment by hannahkane** [comment]
Was playing around with the Madlib earlier. It's nice and snappy! My feedback is largely around context. Specifically:
 * Not clear to a user coming to the page for the first time that they are being invited to add to the list
 * Not clear to a user if what they type will be seen by others, or what it will be used for
 * When you first arrive, the user doesn't know where the existing items came from
 * no context about Mozilla (maybe not needed for users arriving from the IH video, but seems important from users who are arriving from a share. Or, is what they're sharing going to be the video?)

And then in terms of functionality, it really seems like users might want to delete/edit their comments. We don't necessarily have to add this functionality, especially if it's not trivial. What do others think?

**Comment by ScottDowne** [comment]
delete/edit would be a significant amount of work.

**Comment by beccaklam** [comment]
@lovegushwa @hannahkane 
https://redpen.io/p/rbe1bb7099797d2e3b <-- redpen for comments
Share proposals (using share progress buttons) for the Internet Health Mad Lib Landing Page:
![desktop copy 3](https://cloud.githubusercontent.com/assets/20977376/24670543/782bc60c-193c-11e7-9cc3-bf7dc553f789.png)
![iphone se](https://cloud.githubusercontent.com/assets/20977376/24670544/78303b4c-193c-11e7-8d8c-5f5bd65a6a61.png)

**Comment by hannahkane** [comment]
Looks good, @beccaklam.

@lovegushwa - will you provide copy for the Shares?

**Comment by beccaklam** [comment]
@hannahkane My thoughts on your questions:

_**-     Not clear to a user coming to the page for the first time that they are being invited to add to the list**_ 

I think the convention of a flashing cursor indicates they can add to the list. Also if a user starts typing they will automatically be typing into the input

_**-     Not clear to a user if what they type will be seen by others, or what it will be used for**_

I agree this isn't clear... one idea that came to mind is we could do a sort of alert box before the user started the experience?)

_**-     When you first arrive, the user doesn't know where the existing items came from**_

This again could be answered by the alert box... if they came from the video they should have an idea though of where the existing items came from?

_**-     no context about Mozilla (maybe not needed for users arriving from the IH video, but seems important from users who are arriving from a share. Or, is what they're sharing going to be the video?)**_ 

What people share will be the video unless they copy and share the URL directly.

_**And then in terms of functionality, it really seems like users might want to delete/edit their comments. We don't necessarily have to add this functionality, especially if it's not trivial. What do others think?**_ 


Scott says this would be a lot of work and I agree with him... if someone puts up something terrible we could delete it through the google sheet?

**Comment by hannahkane** [comment]
Thanks, @beccaklam. Everything above makes sense, especially now that I've seen the video and how the "What does it mean to you?" question is asked at the end (thanks, @natalieworth!).

Note: There wasn't a flashing cursor when I viewed the site yesterday, in Chrome. Is that a bug? (can't verify now, bc tunnel is gone)

**Comment by lovegushwa** [comment]
left three comments in the redpen (one new one since you last looked @beccaklam )

**Comment by beccaklam** [comment]
@hannahkane the flashing cursor was implemented maybe yesterday. Your link is gone because it's a temporary one to the site scott was running locally.

@hannahkane @lovegushwa wireframes for modal box that pops up after a user hits enter on the input: https://redpen.io/tm7a2a1b43559269d1<-- redpen for comments
![desktop_1](https://cloud.githubusercontent.com/assets/20977376/24678363/3d682102-1958-11e7-9f50-7befc6749c2c.png)
![desktop_2 png](https://cloud.githubusercontent.com/assets/20977376/24678362/3d65bdb8-1958-11e7-9a7e-9991f23d2a66.png)
![desktop_3](https://cloud.githubusercontent.com/assets/20977376/24678361/3d651e94-1958-11e7-9e56-1ec39ce364d3.png)

**Comment by lovegushwa** [comment]
@beccaklam this is cool. Some notes:
- Could we use an X rather than a close link? Whats your thinking here?
- the mozilla logo needs to be in it's box, so here it would be the white box with black text.
- we should drive to www.mozilla.org/internet-health rather than internthealthreport.org
- great first draft of the copy. It needs to do two things 1. address how a individual contribution shapes overall internet health. 2. Compel folks to share so even more voices are heard. 

Could be something like: 

"Thanks for contributing. Mozilla made this because all our voices shape a healthy internet. Please share so more can contribute. Learn more about internet health at https://www.mozilla.org/internet-health"

@caltrider can we get your eyes on this copy?

**Comment by caltrider** [comment]
Hey @lovegushwa @beccaklam. Great job on the copy. I don't have too many tweaks.  My thoughts:

How about we swap the word contribute (which brings to mind $$$ donations) for sharing.

Thanks for sharing! We *heart* the internet. Help keep it healthy. 
Share this with your friends. 
Learn more at https://www.mozilla.org/internet-health

**Comment by beccaklam** [comment]
update:
![desktop_3a](https://cloud.githubusercontent.com/assets/20977376/24716237/57f53dda-19fc-11e7-9ce0-7090fc73793c.png)

**Comment by hannahkane** [comment]
@lovegushwa @beccaklam - I'm going to close this ticket. If we have add'l tweaks (i.e. for color), please open a new ticket.

The ticket for the [science version of the madlib](https://github.com/MozillaFoundation/Advocacy/issues/814) is still open.
