### ISSUE TITLE
Choose and purchase a thinglink account 

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#795]
@ScottDowne and @caltrider - can you coordinate with Ashley (to approve budget) and Cade (to purchase/manage)?

**Comment by ScottDowne** [comment]
These are our options if we want to go with a stock plan: https://www.thinglink.com/signup?buttonSource=fpPricing

I'm heavily leaning towards the 20/month.

**Comment by caltrider** [comment]
@ScottDowne Agreed.  The $20 a month seems right for us.

Did you see the email I shot you and Chris and Ashely?

I think we should be good to go on getting this set up.

**Comment by hannahkane** [comment]
@caltrider - can we close this ticket? Are we good?

**Comment by caltrider** [comment]
@hannahkane Yes, @cadecairos got this up and running like a boss last week.

**Comment by hannahkane** [comment]
Thanks. I'll close this now, but you should also be able to close tickets in the future.
