### ISSUE TITLE
Create the second matrix!

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#797]
This will be the first one to go out via email

**Comment by hannahkane** [comment]
@WillatMozFdn - I'm putting this in the April 14 milestone, because we're using a weekly convention for milestones, always ending on Friday. But this ticket needs a specific deadline before Friday - for the matrix to go out via email at the end of next week, by what day does the matrix need to actually be built/populated?

**Comment by hannahkane** [comment]
Can we close this? Is the second matrix done?

**Comment by WillatMozFdn** [comment]
*Wednesday EOD* (Pacific time) should be our deadline to have the graphic
(and accompanying list of links) approved and finalized.  That gives us one
business day to build, test and proof so we can get it launched Friday
morning.

 - W

**Comment by caltrider** [comment]
The plan is to have the content ready on my end and to the designer and simultaneously to the folks for approval (they've been briefed on the process and so know the turn around schedule) no later than 10:30am MT on Thursdays. I'd rather not have this done the day before because that cuts out a whole day of news for us to include and makes the content less relevant.

**Comment by hannahkane** [comment]
We should discuss this more. It sounds like design needs up to 4 hours to build the matrix once the content is in hand. This means it will be ready end-of-day ET on Thursday (assuming there are no changes from the content approval folks), which doesn't allow for build, test, and proof before the Friday morning send.

How can we resolve this?

**Comment by WillatMozFdn** [comment]
Most likely, by planning to send Saturday morning (queued up and set on
timer by EOD Friday).  Nothing wrong with that from an engagement point of
view ... and it's definitely WAY better than Friday afternoon or
evening.... (although, we could in fact test that)....

**Comment by hannahkane** [comment]
That makes sense to me. @caltrider - does a Saturday send work for you?

**Comment by caltrider** [comment]
@hannahkane @WillatMozFdn works for me

**Comment by hannahkane** [comment]
Closing, as this project has been indefinitely tabled
