### ISSUE TITLE
Design: Privacy tips landing page

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#799]
Design a landing page for privacy tips to be built next week. Below is a wireframe to kick off the process. A few notes:
- I think we should keep the top bar + nav because we will probably want to localize this content, we may want to create a "safety 101" page eventually which is basically a curation of our most essential tips. 

- We need to develop a privacy tips content plan. I'm started a ticket for that here #800 

- I'm thinking we will have two kinds of content. The first is basically a paragraph summary of a thing a user should do (like use a VPN) with links to relevant content outside our site. The second is video content which could be deeper dives into privacy / security related topic. 

- The small square next to the blocks of tip copy is a placeholder for a cool ass .gif. We may want to consider how this graphic and a social post could be the same thing / or related in a production efficient manner. 

Questions: 
- user feedback is important, should we include a place for users to comment or ask questions / we can use this feedback to inform future videos or tips?

- should user be able to share individual videos or tips in addition to the site? 

CC: @beccaklam @caltrider @hannahkane 

![privacy-tips-wireframe](https://cloud.githubusercontent.com/assets/12228435/24736798/268a5c92-1a3f-11e7-8524-114aa360c822.jpg)

**Comment by lovegushwa** [comment]
@beccaklam I started a project folder, please edit my hacked sketch file and take a stab at UI so we can keep this rolling.

https://drive.google.com/drive/folders/0B2qu3ExKWIlvU3FqUnBhMnp3TTA?usp=sharing

**Comment by beccaklam** [comment]
@lovegushwa 
https://drive.google.com/open?id=0BzuBOR2VJQqUZ2o3OXp6bklZUmc <-- exported PNGs
https://drive.google.com/open?id=0BzuBOR2VJQqUUEVhY2hmT0Q4ZDA <-- sketch file

**Comment by beccaklam** [comment]
Here is where we got this week with wireframes. 
https://redpen.io/p/jg2d65c4dc4205102a <-- redpen for comments

**Wireframes:**
![safety tips sketch 2 copy 8](https://cloud.githubusercontent.com/assets/20977376/25540625/cd9ccdd0-2c19-11e7-82fa-88d42285421f.png)
![safety tips sketch 2 copy 7](https://cloud.githubusercontent.com/assets/20977376/25540629/cfba2c20-2c19-11e7-9f4a-660e2f6a8000.png)
![safety tips sketch 2 copy 3](https://cloud.githubusercontent.com/assets/20977376/25540632/d15d4a08-2c19-11e7-821e-13986ad0333d.png)
![ipad pro portrait copy 3](https://cloud.githubusercontent.com/assets/20977376/25540636/d408ced0-2c19-11e7-8b9a-95405c642d93.png)
![ipad pro portrait copy 2](https://cloud.githubusercontent.com/assets/20977376/25540639/d61f73ae-2c19-11e7-951e-23a143c0b708.png)
![ipad pro portrait](https://cloud.githubusercontent.com/assets/20977376/25540641/d778de98-2c19-11e7-9f78-19a0e1bc6123.png)
![iphone se](https://cloud.githubusercontent.com/assets/20977376/25540649/de5682b0-2c19-11e7-98fb-7285598c50bd.png)
![iphone se copy 2](https://cloud.githubusercontent.com/assets/20977376/25540651/e004c5cc-2c19-11e7-9ea7-ebcbaacbaaee.png)
![safety tips sketch 2 copy 4](https://cloud.githubusercontent.com/assets/20977376/25540657/e6469e1a-2c19-11e7-986e-009e2920460d.png)
![ipad pro portrait copy](https://cloud.githubusercontent.com/assets/20977376/25540660/e7bf4ae4-2c19-11e7-8936-80cb05773821.png)
![iphone se copy](https://cloud.githubusercontent.com/assets/20977376/25540665/ebf672f4-2c19-11e7-994d-225be82831c1.png)

**UI:**

**Comment by beccaklam** [comment]
@hannahkane @lovegushwa @natalieworth @HPaulJohnson 
I added some first draft UI for the Safety Tips site to this redpen:
https://redpen.io/p/kyf3f62200a887e56f
I also added some new ideas for the subscription button where users can sign up their e-mail. I did some more research on editorial sites and the convention is to have the subscribe button top right. Will work on fleshing out the UI further Monday (May 8) morning! Also going to drop in the screens here:
![landing-page](https://cloud.githubusercontent.com/assets/20977376/25725193/fb6a5fac-30ec-11e7-85e1-436e28a66783.png)
![inner-page](https://cloud.githubusercontent.com/assets/20977376/25725191/fb68d43e-30ec-11e7-9165-803dd5cc40d2.png)
![subscription 2 option](https://cloud.githubusercontent.com/assets/20977376/25725190/fb677f9e-30ec-11e7-8aac-94315eed3141.png)
![subscription 2 option hover](https://cloud.githubusercontent.com/assets/20977376/25725195/fb6cb612-30ec-11e7-9a9d-1684cf29028e.png)
![suscription 1 option](https://cloud.githubusercontent.com/assets/20977376/25725194/fb6b3da0-30ec-11e7-92ae-97c5dc0f1f19.png)
![suscription 1 option hover](https://cloud.githubusercontent.com/assets/20977376/25725192/fb69ea90-30ec-11e7-93c2-83190f5e80e5.png)
![suscription 3 option](https://cloud.githubusercontent.com/assets/20977376/25725196/fb7261a2-30ec-11e7-84d1-ec4f1d581b9e.png)
![suscription 3 option hover](https://cloud.githubusercontent.com/assets/20977376/25725197/fb77aa4a-30ec-11e7-9cd0-d79bda221d93.png)

**Comment by beccaklam** [comment]
@hannahkane @lovegushwa @HPaulJohnson @natalieworth Safety Tips UI Design update:
https://redpen.io/ngb8baa84428aa19d8

**Comment by hannahkane** [comment]
I put a couple small comments on the redpen, but just wanted to say here that I'm digging this!

**Comment by HPaulJohnson** [comment]
I agree with Hannah - really love how these are developing. I think the removal of the numbers on the vids helps and I think the "subscribe" in the upper right hand corner is the best place for that CTA.

**Comment by beccaklam** [comment]
Added some more modal design options along with some fixes to the comments @hannahkane left above and some alternate UI style options: https://redpen.io/p/kyf3f62200a887e56f
CC: @hannahkane @lovegushwa @HPaulJohnson @natalieworth

**Comment by hannahkane** [comment]
These are all nice options! Will leave to others to decide.

**Comment by natalieworth** [comment]
@beccaklam @lovegushwa uploaded the UI based on some direction changes yesterday and with a new font (just one version so far—still gotta refine any others) https://redpen.io/ng2ed085bac7c218d1 
Font is place holder for now, but the closest I had on my computer to the similar style was Plak
@lovegushwa does this UI feel right for what you were thinking? trying to make it feel mozilla-y too :D

**Comment by beccaklam** [comment]
@hannahkane @lovegushwa @HPaulJohnson @natalieworth Added some alternative inner page options after looking at youtube and vimeo pages more closely. These have the gallery of 'more videos' stacked on the right hand side and are more conducive to successive watching I think.
https://redpen.io/p/kyf3f62200a887e56f <-- redpen for comments
![safety tips sketch 2 copy 5](https://cloud.githubusercontent.com/assets/20977376/25954694/0b0182b8-3635-11e7-817d-182c882afb85.png)
![safety tips sketch 2 copy 7](https://cloud.githubusercontent.com/assets/20977376/25954695/0b06cb42-3635-11e7-94e7-5cd26d3d4cc4.png)

**Comment by hannahkane** [comment]
Latest is here: https://redpen.io/p/eo07ee9db3059d0a00

**Comment by hannahkane** [comment]
Closing this ticket, as I believe design is done. Can file follow-up tickets for tweaks as needed.
