### ISSUE TITLE
Design landing page for software update email 

### ISSUE THREAD

**Issue by shaghdoosti** [MozillaFoundation/Advocacy#8]
This email is scheduled for send on May 18. 

There is already a landing page that needs to be updated for this campaign. Here is the link: https://petitions.mozilla.org/stay-secure/

Changes that it needs: 

-Petition page needs to be simplified to a button that says 'I updated!' 
-It would be great to get some design to point out/emphasize the instructions at the bottom of the page. 
-The header should be replaced. 

@valianttry @stephaniemcv @lovegushwa

**Comment by valianttry** [comment]
@lovegushwa any update on this? I'm going to take over this bug while @shaghdoosti goes on PTO starting tomorrow 😄

**Comment by mmika** [comment]
http://mzl.la/update goes to a page with this url https://petitions.mozilla.org/stay-secure/
We should perhaps adjust the url and take the word 'petitions' out? -- it is confusing.

**Comment by natalieworth** [comment]
cc @lovegushwa

**Comment by natalieworth** [comment]
Drafts are here:
https://docs.google.com/document/d/1jJE28HGJWEXWo45rgy6dJBSq7jNcO_a2oVI8xu5YlEE/edit

**Comment by natalieworth** [comment]
@valianttry do you have the power to change or add a permission for me to access the file above ^ I'm currently not able to view it

**Comment by valianttry** [comment]
@natalieworth you should have access now, but that email will need some more work, FYI. That's in #20

**Comment by valianttry** [comment]
OK I worked on the email copy ( #19 ) and made some notes on the page design, below

Notes:
-- This is going to our email list, so the email signup form is obsolete. It just needs a button "I Updated!"
-- The most important content on this page is the list of software sites, which is too far down on the page. Any way to lift those up or at least tighten white space so there's no scrolling needed?
-- I don't know exactly what analytics are already on that page, but just want to double check we can count clicks on the 'I updated!" button? Is that a Q for @ScottDowne ?

![update_your_software_](https://cloud.githubusercontent.com/assets/9830371/15204884/8f70dafe-17c7-11e6-93ed-9b060223b750.png)

**Comment by natalieworth** [comment]
@HPaulJohnson After someone clicks 'I updated' could we have the option after for a social share? Currently people get redirected to a facebook or twitter social share option after hitting the sign-up on the original petition page:
<img width="1416" alt="screen shot 2016-05-12 at 9 24 37 am" src="https://cloud.githubusercontent.com/assets/14876567/15222668/b2f8d9f0-1825-11e6-8889-11213ce9a6e6.png">
<img width="1422" alt="screen shot 2016-05-12 at 9 26 10 am" src="https://cloud.githubusercontent.com/assets/14876567/15222674/b612905e-1825-11e6-8fca-e935407c28d7.png">
If we had this option to share after updating, what content would you want shown or people directed to?

**Comment by HPaulJohnson** [comment]
@natalieworth we are going to see if we can implement Share Progress here. Work happening in #23 on that.

**Comment by natalieworth** [comment]
@valianttry I have a couple drafts for this page up on red pen: https://redpen.io/p/zh695f4ba062afbca7
The first 3 options are using the existing template style and design. The last 2 alternatively use the existing colours and consistent font with the encryption campaign work.

cc @lovegushwa

**Comment by ScottDowne** [comment]
Build ticket is here: https://github.com/MozillaFoundation/Advocacy/issues/18

**Comment by natalieworth** [comment]
@valianttry Went over this with @lovegushwa and we are proposing this option for development:
https://redpen.io/ptd29b247f9f0e8626
- we updated the orientation of the page so the update links are higher and on the left side, with the 'Tell us you updated' and 'I updated!' button on the right side. 
- updated the footer to match the newer existing one on the site
- email is also currently using sandstone, so we've maintained that for consistency, but utilized the UI for the button and footer based on the encryption site
- I think too when the email templates are updated based on the future branding, we could rethink this page more to accommodate the ask and updated stylings

**Comment by ScottDowne** [comment]
@natalieworth this looks good and is a quick build.

One question is have we thought about mobile yet? I can see a simple solution of stacking the left and right blocks being problematic in that the left panel would take up the whole screen pushing the button off the screen.

**Comment by natalieworth** [comment]
@valianttry Can you review this before build? https://redpen.io/ptd29b247f9f0e8626

**Comment by natalieworth** [comment]
Closing this. Final design is here: https://docs.google.com/open?authuser=natalie%40mozillafoundation.org&id=0B20-0lpP23c0X25WUFpJWUM3am8
