### ISSUE TITLE
Start building signup(crm/et) and signin(auth0)

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#80]
Not sure yet the tasks involved here yet, but, it roughly looks like
- [ ] integrate auth0 with nationbuilder
- [ ] webhook setup for crm/et

Likely we want to spawn these into separate issues.

**Comment by ScottDowne** [comment]
Main goal here is to at least to requirements gathering and get it started. I would take a guess that actual completion (integrated into sandbox) happens next heartbeat, but maybe not.

If we integrate this work nextheartbeat, we should create a ticket to implement these.

**Comment by ScottDowne** [comment]
Nationbuilder sandbox doesn't seem to have auth configuration available, so it's hard to play around with that aspect.

**Comment by ScottDowne** [comment]
So I don't forget:
- [x] send nationbuilder an email asking about sandbox and auth.

**Comment by damiankay** [comment]
Will set up when contract is signed

**Comment by a-kilroy** [comment]
I can check in with the IAM team to see how progress is going with auth0 if you all need/want me to

**Comment by damiankay** [comment]
That would be amazing if you could @a-kilroy - thanks!

**Comment by a-kilroy** [comment]
I checked with Pierros and he feels like the auth0 progress has been positive enough that we could start planning to pilot with it. He suggested that someone reach out to him and he can discuss next steps. @ScottDowne I suspect that's you but seems like a big enough thing that you'll want @simonwex involved as well. Once that's done, please make sure both @damiankay and I know clear steps and dates. I have check ins with that team so I can help bridge the gap.

**Comment by damiankay** [comment]
Thanks for getting things moving RE auth0 @a-kilroy 

Just wanted to flag that @simonwex will be on PTO for a week as of tomorrow. @ScottDowne - you might want to see if you can connect today if you have any questions.

**Comment by ScottDowne** [comment]
@damiankay not likely, it's pretty late for Pierros timezone.

Looks like we're dong it without Wex.

**Comment by damiankay** [comment]
Sorry, I just meant if you want to connect with @simonwex you should do it today. I know it's not ideal, as you won't be able to speak to Pierros until tomorrow at the earliest. Thx!

**Comment by ScottDowne** [comment]
Ah, I see. Yup, I already added him to the email I sent out. Should be enough, right?

**Comment by ScottDowne** [comment]
@a-kilroy no response yet from Pierros.

**Comment by ScottDowne** [comment]
@a-kilroy Getting this started is my P1for the week. Should we send out another email to Pierros? I'm not a fan of being blocked, though, so I'm going to try to do my own research on this. Any info you have would be great.

**Comment by ScottDowne** [comment]
Blockers and questions.

So far I know I need to get the crm hooked up, and there is a mozilla auth0 that's being shipped that we need to integrate with.

Questions: how much of this falls on me, and how much falls on the agency?
Blockers: Chat with Pierros around auth0, chat with Stephanie around crm integration, some real life nationbuilder to work on.

The auth0 setup is a little vague to me, and that's blocked on getting something from Pierros, or otherwise knowing what it's solving (sso?). Possible thing to do in the meantime. See if I can setup a dev auth0 thingy of my own, and integrate with nationbuilder sandbox.

crm is pretty much just blocked on getting endpoints and API docs on how to integrate with the crm. Possible thing to do in the meantime, create a test webhook in nationbuilder's sandbox.

**Comment by damiankay** [comment]
Hey @ScottDowne - don't worry about CRM for now. I think Fission will be doing this. Maybe keep pinging Pierros. Have you tried IRC or other channels?

**Comment by ScottDowne** [comment]
@damiankay cool, that sounds great!

**Comment by ScottDowne** [comment]
So I think where we're going to head with this for next week.
1. CRM looks like it's happening with Fission, so I'll focus less on that.
2. Auth0 looks like we're going forward with it, and see what's involved. Questions I'm answering are. Does the data in Auth0 transfer or work with IAM once IAM is ready, if we integrate before IAM is ready. Has Auth0 gone through vendor review.

**Comment by ScottDowne** [comment]
No luck with trying to integrate auth0 (I created a test account) with nationbuilder's sandbox.

Just, not able to figure out (yet) which values from each dashboard need to be plugged into the other dashboard.

I think finding docs or getting help from either nationbuilder or auth0, or someone else that would otherwise have experience with this would probably be the next best step.

**Comment by ScottDowne** [comment]
I found this before, but, it's actually starting to become clear to me what they are talking about http://nationbuilder.com/enterprise_sso

**Comment by damiankay** [comment]
Hey @ScottDowne - did you have any luck with this? Is it something we should talk to Fission about?

**Comment by ScottDowne** [comment]
Yeah, so CRM is happening with Basket if the fields allow that.

Techno jargon warning: We're going to setup a Python and Heroku app that uses the webhooks in NationBuilder, then sends the info to either Basket or directly to SalesForce.

For signup, we're going to use Auth0 if it gets through vendor review in time, if not, we'll just use default nationbuilder auth.

**Comment by damiankay** [comment]
Update from Fission RE: User Data 
They're assumption is that they're not using Basket, but will rather use force API to send user data directly to SalesForce. 

CC @ScottDowne @cadecairos @drewmoto @valianttry

**Comment by ScottDowne** [comment]
I was chatting with Walter today, and he was still thinking Basket.

**Comment by damiankay** [comment]
Weird - Jennifer said otherwise. I'll include that in my follow up questions this afternoon.

**Comment by damiankay** [comment]
FYI - The Salesforce team was able to provide Walter with the permissions required to send data directly to SFDC via API, so they won't be using Basket for the integration. 

@ScottDowne @valianttry @simonwex @a-kilroy

**Comment by damiankay** [comment]
@a-kilroy - do you know where we're at with Auth0 for Maker Party?

**Comment by a-kilroy** [comment]
I don't have a good update for you at the moment but am hoping to have
something before the end of the week.

**Comment by damiankay** [comment]
Thanks Arielle

**Comment by a-kilroy** [comment]
OK update. Tristan in IT is managing this and is aware of our timeline now. He's going to prioritize getting the vendor review done as well as work on getting the needed contract in time so we can use it. We'll be ahead of the curve here so it might make some manual account matching for them later but it's a small enough number that he doesn't think it's a big deal. I'm going to follow up with him first thing next week (he's on PTO tomorrow) to make sure it is looking good and then I think we can figure out the build steps.

**Comment by damiankay** [comment]
This is great news. Thanks @a-kilroy

**Comment by a-kilroy** [comment]
And I have lost faith that we will be able to do this on our deadline. I think we should go to plan B.

**Comment by ScottDowne** [comment]
I think that makes this ticket resolved. I'll take any resolved ticket as good news! :rocket:

**Comment by damiankay** [comment]
Confirming that we will use Nationbuilder's default persona management. 

For event attendees: we will only collect name & email, option for email opt-in, no option for editing user profiles
For hosts: ?

We will need to figure out how we will we migrate identities and users to our new system. 

This has been discussed and approved by @geroter @simonwex @a-kilroy
