### ISSUE TITLE
Content: privacy tips content plan

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#800]
Whats the cadence and plan for privacy tips? The landing page includes 2 kinds of content: short 1 paragraph tips that possibly link out to other resources, and explainer / expert interview videos. 

NYTs is putting out great privacy content right now:
https://www.nytimes.com/2014/11/21/technology/personaltech/using-a-vpn.html?action=click&contentCollection=Personal%20Tech&module=RelatedCoverage&region=EndOfArticle&pgtype=article

We need plan for tips this week. 

CC: @caltrider @hannahkane @beccaklam

**Comment by hannahkane** [comment]
We could have distinct cadences for social and email, as we do with the news matrix (which will be produced and shared weekly, but emailed only every other week).

Email schedule for this should respect the rest of the email content calendar.

**Comment by hannahkane** [comment]
Another thing to discuss is localization of this content

**Comment by hannahkane** [comment]
And another thing is the branding of this. I'd thought we were leaning towards "safety" as our frame for this (e.g. Safety First). Can we clarify?

**Comment by hannahkane** [comment]
Closing this ticket, as it no longer seems useful.
