### ISSUE TITLE
Multiple instances of the mablib site 

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#802]
@hannahkane @ScottDowne we should be able to spin up multiple versions of the madlib site:

- a version for folks from our email list
- a version or two for social testing (Alex could weigh in here on the exact number)
- a version for snippet traffic (we will launch this after we run the initial social test.)

I'm curious if these 'threads' develop different tones based on the origin of the traffic.
If we need to shut one of these down for troll reasons we can still link to another version thats less problematic.

**Comment by ScottDowne** [comment]
So I'm thinking we can do this in a query string. examples: madlib.org/?channel=social madlib.org/?channel=email madlib.org/?channel=snippet.

This would then use 1 of 3 different data sources.

We should probably default to social if they manage to go to a link without the query.

**Comment by vojtechsedlak** [comment]
Will we be recording the threads in any machine-readable way? If we for instance had a csv file that gathered the entries, with associated timestamps and maybe full URL paths, we could so some sentiment analysis afterwards.

**Comment by hannahkane** [comment]
@ScottDowne - aside from answering @vojtechmzl's question above, is this ticket done?

**Comment by lovegushwa** [comment]
@ScottDowne we will also be making a science version. Hold tight for the sub domain and the copy. #814 has the details.

**Comment by ScottDowne** [comment]
I think we can close this. There are multiple links for email social and snippet. Social is the default.

We can tweak this further in new issues.

@vojtechmzl Issues around metrics can be filed in a new issue. I have time to tackle this now, so please ping me if you want to chat.

@lovegushwa Issues around science site and domains are also better served as new issues. You can ping me with any questions.
