### ISSUE TITLE
Copy change: open data day site

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#803]
CC @hannahkane @ScottDowne @caltrider 

We need to make a small copy change to the open data days site so we can promote it via snippet on US tax day (April 17th).

https://iheartopendata.org/en-US/#about

Change this copy in the 2nd paragraph:

Given today is Open Data Day we thought that it would be a great moment for us as taxpayers (the funders of large amounts of scientific research!) to advance a set of principles we’d like to see apply to publicly-funded research:

TO 

Given it's tax season we thought that it would be a great moment for us as taxpayers (the funders of large amounts of scientific research!) to advance a set of principles we’d like to see apply to publicly-funded research:

**Comment by hannahkane** [comment]
@ScottDowne - ok if I put this in the current milestone?

**Comment by ScottDowne** [comment]
It's updated on staging now: https://iheartopendata.mofostaging.net/en-US/#get-involved

**Comment by ScottDowne** [comment]
I'll close this once it's on prod

**Comment by ScottDowne** [comment]
Fixed.
