### ISSUE TITLE
Build: Privacy Tips Landing Page

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#804]
Design will happen in #799

Should be similar to News Matrix landing page in that it needs to be easily updateable by staff (new Tips every week).

Unlike the News Matrix, this site will be localized.

url will be advocacy.m.o/safety

**Comment by hannahkane** [comment]
@lovegushwa - I feel like this is unlikely to happen this week, so I'm going to remove from the milestone. Lets see how far we get with content and design before we bring this back into the fold.

**Comment by hannahkane** [comment]
@HPaulJohnson - pinging you to start thinking about the url. When would be a good time to discuss?

**Comment by hannahkane** [comment]
Notes from planning meeting:

- aiming to get on staging by May 31
- one week-ish for QA
- url will be advocacy.m.o/safety

**Comment by ScottDowne** [comment]
@hannahkane think we can close this?

**Comment by hannahkane** [comment]
Good call. Will file additional changes as separate tickets.
