### ISSUE TITLE
Research and choose call tool for Copyright Campaign targeting European Parliament

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#806]
The immediate impetus for this work is the possibility of adding a call tool to the [Copyright Campaign site](https://www.changecopyright.org/en-US/) in time for a June vote in the European Parliament. Even if we can't meet the deadline for this vote, we'll certainly need this for future campaigns, so we'll need to identify a tool regardless.

For that project, we need to identify a tool that meets the following requirements:
 * User -> MEP matching for European locales
 * Localizeable
 * Passes security review
 * [program and technical teams to add add'l requirements]

**Comment by hannahkane** [comment]
cc @Melechuga @Matt-Holland @ScottDowne - please add details about add'l requirements or questions you have that would inform our evaluation of potential tools.

Note: I'm not assigning this ticket to anyone or putting it in a specific milestone yet, but we can capture ideas/questions here in the meantime, while we sort out competing priorities.

**Comment by Melechuga** [comment]
Hey @hannahkane @ScottDowne 
I'm going to speak with the developer from Bits of Freedom on Friday morning (PT). If there are general security questions I can ask on your behalf so you can decide whether to dig in further or not, please let me know. If you'd like to join the call, that would be great too! Otherwise I will have a general meet-and-greet convo about the tool and hope he'll be amenable to following up via email.

**Comment by hannahkane** [comment]
Chris's concerns were about the expired SSL certificate and the fact that the code hadn't been updated in 2 years. Do we know that the tool is still maintained?

What time is the meeting?

**Comment by Melechuga** [comment]
Chat w/Bits of Freedom re: PiPhone:

- On SaveTheMeme.net, phone is actually hosted on LQDN's server and only the frontend is supported by Bits of Freedom (frontend code is at https://code.bof.nl)
- Maintenance of the Python code done by LQDN (yes it is maintained, but it is ugly).
- Rejo (engineer) has a list of improvements he will share with us.
- BoF says the code works right now, but they know it's not optimal (for example, current code is loading images from the EU Parliament website directly, but these are loaded over http:// -- causes concern for users who get a "warning"; also the location of the images could change; also localization challenges for elements on the backend.)
- Rejo believes this tool could be a lot better, even modular (so you can run both national and EU campaigns), amongst other features.
- Would be helpful if the EU digital rights organizations could have a good tool that is accessible to the campaigners.

Conclusion: don't use piphone; support building a better one.

**Comment by hannahkane** [comment]
Thanks, @Melechuga. 

It seems like there's an opportunity here, but I think we need clarity about where this fits in with other priorities. 

Can we set up a time to discuss, perhaps with Ashley, @Matt-Holland, and @simonwex?

**Comment by Melechuga** [comment]
Hey @hannahkane, re: PiPhone, Rejo also added: "I also just verified all the requests a browser does: a single request make a number of TLS-secured calls to the savethememe.net and a number of non-TLS-secured calls to www.europarl.europa.eu. The second group of calls is inherent to the code of PiPhone. It should be different, but changing is not something I can fix with the code I am hosting myself."

Re: my notes, sorry, I should've been clearer that "support building a better one" isn't directed at you/the team! I just put everything in one place. The big-picture is that we won't be using PiPhone at this time so you don't have to finagle this in with other priorities. I believe @Matt-Holland is researching other options. Thanks!

**Comment by hannahkane** [comment]
Thanks, @Melechuga.

@Matt-Holland - when you have a moment, could you share a bit about the options you're researching? Is there anything you need help with?

**Comment by hannahkane** [comment]
Closing, as this conversation is happening elsewhere.
