### ISSUE TITLE
Design: Science march poster & social post template

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#807]
Design templates so we can knock out 12 unique protest posters and social graphics Wednesday the 19th. Related ticket #808

**Comment by natalieworth** [comment]
@lovegushwa @hannahkane @beccaklam process here so far for the science posters:
I'll also add these to redpen here so they're easier to comment on: https://redpen.io/p/fq8f87a8b168e0c122

@lovegushwa The working photoshop files are also here if you want to explore anything/ need it tomorrow. Kind of fun to try different things: https://drive.google.com/drive/u/0/folders/0B20-0lpP23c0U3pYaWdmS2s0Q1E

![poster-v1](https://cloud.githubusercontent.com/assets/14876567/25026632/24278eac-205c-11e7-9042-9820828262d2.jpg)
![poster-v2](https://cloud.githubusercontent.com/assets/14876567/25026633/242ad170-205c-11e7-959e-1007536d107c.jpg)
![poster-v3](https://cloud.githubusercontent.com/assets/14876567/25026636/242ceaa0-205c-11e7-8bf2-f08cc23beaa2.jpg)
![poster-v4](https://cloud.githubusercontent.com/assets/14876567/25026635/242cf9aa-205c-11e7-9a6a-5296f1b4c3e2.jpg)
![poster-v5](https://cloud.githubusercontent.com/assets/14876567/25026634/242bb522-205c-11e7-8c69-444ffa36b237.jpg)

**Comment by natalieworth** [comment]
Pinterest inspiration was here too @lovegushwa @beccaklam https://www.pinterest.com/nataliejworth/protest-signs/?eq=protest&etslf=7211

**Comment by natalieworth** [comment]
Updates/ progress on Science posters from today @lovegushwa @beccaklam @caltrider @hannahkane if you want to check them out. https://redpen.io/p/fq8f87a8b168e0c122
<img width="824" alt="screen shot 2017-04-18 at 5 02 00 pm" src="https://cloud.githubusercontent.com/assets/14876567/25157896/17b9ca58-2459-11e7-83ad-93818e183673.png">
<img width="423" alt="screen shot 2017-04-18 at 5 02 10 pm" src="https://cloud.githubusercontent.com/assets/14876567/25157897/17bcbf9c-2459-11e7-96c9-9e7038870369.png">
<img width="425" alt="screen shot 2017-04-18 at 5 02 17 pm" src="https://cloud.githubusercontent.com/assets/14876567/25157898/17bf1490-2459-11e7-9655-cde5f63dd508.png">
<img width="426" alt="screen shot 2017-04-18 at 5 02 24 pm" src="https://cloud.githubusercontent.com/assets/14876567/25157899/17bf723c-2459-11e7-8a7d-e87cd2f13d9c.png">

**Comment by natalieworth** [comment]
Original copy for these are here https://docs.google.com/spreadsheets/d/1seK0ySZrJA3Qo-U0_UwMimmwWJ_slKr0mVeIbCPxuq8/edit#gid=1255626302

And I made a google doc with the final chose copy (for us to split up/ claim):
https://docs.google.com/document/d/1zEZh34NM_KLsJjfO6x9w0Bco9lldrVGpmxp9aXGtGNo/edit

**Comment by beccaklam** [comment]
@natalieworth @lovegushwa @hannahkane @caltrider 
Super rough posters from me can be found here: https://redpen.io/p/upee8d67e125e92153
Still need to add colour/imagery and general polishing.

**Comment by natalieworth** [comment]
Final posters are here:
https://drive.google.com/drive/u/0/folders/0B20-0lpP23c0RGhCeFNxUERGR1E

Final photoshop files (split into portrait and landscape version are here):
https://drive.google.com/drive/u/0/folders/0B20-0lpP23c0and2WXNuMXRURG8

**Comment by natalieworth** [comment]
Imgur link is here too http://imgur.com/a/ZuLoU
