### ISSUE TITLE
Distribution plan for Science March posters

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#808]
Meta ticket for Science March poster distribution:

- [x] decide on the number of posters (let's make 12??)
- [ ] build a medium post to share the posters
- [ ] create a email to share the posters
- [ ] <s>create a share progress page for each poster instance</s>

Related tickets:
email ticket #809 
medium copy / build ticket #810
share progress ticket #813 

CC: @caltrider @hannahkane @natalieworth

**Comment by hannahkane** [comment]
@lovegushwa - given the specific tickets for each item, now I'm thinking maybe we can close this ticket, since there's nothing actionable on it. What do you think?

**Comment by hannahkane** [comment]
Noting here that, as per conversation in Slack, we'll skip creating ShareProgress pages for each poster, and instead will point directly from Medium to imgur, where we'll host the posters.
