### ISSUE TITLE
Email: Share science march posters with list

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#809]
- [ ] write email copy
- [x] create callout graphic

**Comment by natalieworth** [comment]
Hey Will, I have the ticket here at 250 x 250 @ 144dpi. I feel like it looks a little low res on my Macbook display? So let me know if you need a higher resolution?
![science-graphic-v1](https://cloud.githubusercontent.com/assets/14876567/25016015/3133a76c-2033-11e7-83d4-915f66104613.jpg)

**Comment by natalieworth** [comment]
@WillatMozFdn

**Comment by lovegushwa** [comment]
@WillatMozFdn email callouts
(these are supposed to look a little tattered and distressed, I upped the image size to 500x500px but lowered the overall compression quality so the file size is still small but will look better on retina displays.)

Callout 1:
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvZHVuQzNvbzA2TDQ/view?usp=sharing

Callout 2:
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvVHpBd1V5TXFZbUk/view?usp=sharing
