### ISSUE TITLE
Build: Maker Party pages on learning.mozilla.org

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#81]
The agreed upon approach for the events website design is to re-use as many elements as possible from last year's Maker Party website. 

We'll be using the WIP sandbox created in here: https://github.com/MozillaFoundation/Advocacy/issues/79 to get an idea as to what pages need to be designed.

Design should be based on: 
Required functionality #75 
Site map #126

Due August 12

CC @lovegushwa @ScottDowne

**Comment by ScottDowne** [comment]
Also we'll have:

A list of pages defined here: https://github.com/MozillaFoundation/Advocacy/issues/82
A list of features defined here: https://github.com/MozillaFoundation/Advocacy/issues/75

**Comment by damiankay** [comment]
@lovegushwa what do you need to get started on this (other than a deadline)? :-)

**Comment by HPaulJohnson** [comment]
Started a shell doc to start working on copy based on low-fidelity wireframes. Let us know the copy deadline and we'll make sure to have this completed in time. 

https://docs.google.com/document/d/16ObBANwvduy59NjYC3aOF9cIPsDG3RdGszmHwqXHPv4/edit

cc/ @KevZawacki

**Comment by damiankay** [comment]
Thanks Paul - hoping to talk to Nationbuilder today and will update the deadline then.

**Comment by lovegushwa** [comment]
@damiankay it's my plan to get this done this week.

**Comment by lovegushwa** [comment]
@HPaulJohnson high-fidelity wireframes. https://redpen.io/ara44235f28a055e41
Add any copy tweaks. Also look at the language in the nav. 

I'm going to start converting this to full color UI / add images. Goal to ship to @ScottDowne early tomorrow.

**Comment by damiankay** [comment]
Hey @lovegushwa - were you able to ship this to @ScottDowne as planned?

**Comment by lovegushwa** [comment]
@damiankay @ScottDowne @HPaulJohnson 
The Makerparty pages on learning.mozilla.org are ready to build, comps and images here:

https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvZTk5dUdZRGRSNTQ&usp=sharing

I used standard learning.mozilla.org styles / buttons etc so it should be a snap. Some copy will probably change in QA, notes on copy and links in this redpen: https://redpen.io/p/zm16bb6ea5c2a69eec

**Comment by lovegushwa** [comment]
@ScottDowne if you have questions tomorrow when you start on this, @HPaulJohnson should be able to help.

**Comment by lovegushwa** [comment]
@ScottDowne the website copydeck is here:
https://docs.google.com/document/d/16ObBANwvduy59NjYC3aOF9cIPsDG3RdGszmHwqXHPv4/edit

The pages you are replacing on learning.mozilla are these:
https://learning.mozilla.org/en-US/events
https://learning.mozilla.org/en-US/events/resources/#event-guides

**Comment by ScottDowne** [comment]
@HPaulJohnson do you know if there are any links in these updates that link to a page already in l.m.o?

Or otherwise link to something that's not in the desired locales?

**Comment by ScottDowne** [comment]
Bulk of the work done here. https://github.com/mozilla/learning.mozilla.org/pull/2165

Main goal, get through review and on Pontoon asap. We need to give l10n plenty of time. We can do further QA once it's on staging.

**Comment by damiankay** [comment]
Thanks @ScottDowne - waiting for final ok on copy tomorrow (Tuesday), then we'll get it in for L10n.

**Comment by ScottDowne** [comment]
@damiankay So there is a small decision that needs to be made regarding what to do with the old pages while we translate the new pages.

The issue is, in order to have the pages on Pontoon, they need to be on staging, which also means they need to be good enough to be on production. But, we shouldn't have these pages on production until we're translated. So we have a small chicken and egg problem.

The two solutions are:
1. Create a hidden page with the new content, put that on pontoon so they can start translating the unshipped pages. Once we're ready to ship, update the links and update pontoon to point to the real links.
   - pros: This is not disruptive to the user.
   - cons: Requires us to go in and update the links in pontoon later.
2. Update the existing links like we intend to, but hide them in the nav until we're ready.
   - pros: Doesn't need t update anything in pontoon later.
   - cons: Anyone with the old links can see the new pages before we ship. We'll have a missing nav item temporarily while we translate.

**Comment by damiankay** [comment]
@ScottDowne - let's talk about this today. We'll also likely need to make a few edits in response to George's copy deck feedback in #235

**Comment by damiankay** [comment]
@hannahkane - after a bit of discussion, the recommendation is to load up our edits on production so that the L10n community can start translations. Not much traffic is expected to these pages as they haven't been promoted since last year's Maker Party. Can you let us know what you think of this approach and whether we should jump on a call to discuss? 

CC @ScottDowne @HPaulJohnson

**Comment by ScottDowne** [comment]
I'm chatting with @hannahkane about this now, and it looks acceptable to update the links, and hit it from the nav until we're ready.

**Comment by hannahkane** [comment]
WFM. Appreciate the heads up. I've let stakeholders know; we'll see if anyone raises any concerns.

**Comment by damiankay** [comment]
Fantastic - thanks @hannahkane !

**Comment by lovegushwa** [comment]
@damiankay changes regarding George's copy deck feedback in #235 ... actual copy changes will happen once they are approved. Some content changes on the resources page (2nd page in the redpen link.)
https://redpen.io/p/ta8378af24bdb1627e

**Comment by ScottDowne** [comment]
@lovegushwa this is on staging now. Being added to pontoon in the hour.

I just wanted to double check that copy in the redpen is up to date? I was seeing changes in the redpen, and I didn't see string changes in the google doc. Is this correct? I was confused cause usually I would trust the doc over the redpen, but redpen seemed more correct.

**Comment by damiankay** [comment]
Hi @ScottDowne - the text in the copy deck is the latest; the redpen copy has not all be updated yet.

**Comment by damiankay** [comment]
Hi @lovegushwa @natalieworth @beccaklam 

The Maker Party pages on learning are ready for an initial look by the creative team. Can you please review the pages and flag any issues for @ScottDowne below before EOD today? 

Please note that the links are not in place, and Scott still needs some images in 1x and 2x (you'll see which ones are missing). 

Pages to review are here: 
- https://learning.mofostaging.net/en-US/events/resources
- https://learning.mofostaging.net/en-US/events/

**Comment by lovegushwa** [comment]
@ScottDowne @damiankay 

Looking great overall. 

To much space above "what is maker party" Can you make the spacing similar to the mozilla clubs page? (same issue on host resources page.)
![screen shot 2016-09-12 at 5 41 25 pm](https://cloud.githubusercontent.com/assets/12228435/18458050/9e53d42a-7912-11e6-9f36-6b866f9f0e1f.png)

Can you use the same heading style for makerparty activites as whats shown on the teaching activities page? @HPaulJohnson do you think we need to include the same tags (shown in hot pink.)
![screen shot 2016-09-12 at 6 04 57 pm](https://cloud.githubusercontent.com/assets/12228435/18458139/78a1f9cc-7913-11e6-9422-a84e2a446360.png)

![screen shot 2016-09-12 at 5 42 25 pm](https://cloud.githubusercontent.com/assets/12228435/18458104/0bde12ee-7913-11e6-8697-110e69353da8.png)

**Comment by damiankay** [comment]
Closing as we're now in QA
