### ISSUE TITLE
Ask email audience for Science March poster ideas

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#812]
The plan, as I understand it, is to collect clever/smart/insightful/funny Science March poster ideas from our Mofo email audience, and design posters for about 12 of the best ideas.

We'll need:
 - [x] Email copy. The email will link to a science version of the madlib (which is cool, because then people will be able to see and be inspired by other people's ideas).

I believe this will be US-only, to align with the focus of the march. I also believe we're aiming to send this out this week.

Who will draft copy for this email?

cc @lovegushwa @WillatMozFdn @stephaniemcv @stephwright @caltrider

**Comment by stephaniemcv** [comment]
Confirm that audience will be EN-US and @caltrider will be drafting copy.

**Comment by hannahkane** [comment]
@stephaniemcv @WillatMozFdn - When do we need this copy by to have the email go out on Friday?

**Comment by WillatMozFdn** [comment]
Copy would need to be finalized and submitted for approvals three full
business days before intended launch.

Who is project managing this email?  We need that person to fill out a planning
document
<https://docs.google.com/document/d/1aEzfTaqUPbzA4kwnIIcfGNT2FOTf9msp0c1JNk8pw3g/edit>
.

 - Will

**Comment by hannahkane** [comment]
I believe @caltrider is point on this. Jen - do you have time to fill out the planning document and write the copy tomorrow?

**Comment by caltrider** [comment]
Here's the draft copy:  https://docs.google.com/document/d/1K79FO013rF5-zidNeGALWNNmND41pm5yDlJluXRv_q0/edit

**Comment by hannahkane** [comment]
Done!
