### ISSUE TITLE
Build: separate share progress pages for each Science March social poster

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#813]
Create a share progress page for each Science March social poster. Pages will be linked from a Medium post containing 12 different poster graphics with links to share under each graphic. #810 

CC: @hannahkane @ScottDowne @natalieworth @beccaklam @vojtechmzl

**Comment by hannahkane** [comment]
Team wants to go with imgur for hosting these, so I'm closing this.

Please reopen if imgur doesn't meet our needs.

**Comment by hannahkane** [comment]
Reviving so we can use this for social shares (which imgur doesn't track)

**Comment by hannahkane** [comment]
As per Slack conversation....gonna go with just linking directly from Medium to imgur, and will use downloads/clicks as our meaningful metric.
