### ISSUE TITLE
Create science version of madlib

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#814]
Should be hosted on the same domain as the other madlib (ticket filed in private devops repo), but with "science" as the subdomain.

Instead of "A healthy internet is...", it should read....something else.

Ideas:
 * "An awesome March for Science poster would be..."
 * "I march for science because..."
 * "I Love Science" and then the prompt in the text field would be "Share your best March for Science poster idea"

What do y'all think, @lovegushwa @natalieworth @beccaklam @ScottDowne?

**Comment by stephwright** [comment]
Just discovered this site thx to Kaitlin: https://www.signsforscience.com/
Maybe there is some sort of collaboration that can happen there?
Reached out to find out who is behind it.  No mention on the website and WHOIS indicates domain is registered through a proxy.  Sent an email to "contact" address to see if I can find out more.

**Comment by lovegushwa** [comment]
@beccaklam add your take on the copy

"March for science posters ... "
"your cleaver idea here" 

+ modal fires on visiting the landing page provides context

**Comment by beccaklam** [comment]
A look at copy for the Science Madlib:
Also are we going to provide a link to where people can find the posters when they're released?
![science madlib](https://cloud.githubusercontent.com/assets/20977376/24926410/7229323e-1ec9-11e7-87b8-27d59b9be587.png)

**Comment by lovegushwa** [comment]
@beccaklam @hannahkane 

- can we create a placeholder medium post that says something about the 12 signs will be posted here and then link to on the madlib page? 

- The copy seems close, @hannahkane  what do you think about "Making a cleaver sign is hard. Help Mozilla make it not" 

Alt could be something like: 

"Support the March for Science by sharing a clever protest sign slogan. Mozilla will design posters from 12 of our favorites and post them here (link) to print or share online."

**Comment by hannahkane** [comment]
@lovegushwa - I like your alt copy. I don't think the march is being billed as a protest, though, so maybe this slight edit: "Support the March for Science by sharing a clever science-themed slogan. Mozilla will design posters from 12 of our favorites and post them here (link) to print or share online."

Drawing on language from the official March website, I'm wondering if the prompt ("Clever science poster TBD" above) should be: "Stand up for science". I like "share your sign idea" as the helper text.

**Comment by hannahkane** [comment]
- [ ]  for handling shutdown (if needed): build a static page that doesn't have the input and says we're no longer accepting submissions

**Comment by hannahkane** [comment]
- [ ] add link to Medium post, when we have it

**Comment by beccaklam** [comment]
**New copy for modal (tentative, needs work):**
Support the March for Science by sharing a clever science-themed slogan. mozilla will design posters from 12 of our favorites to print or share online. Follow us on Facebook and Twitter to see the final products.

**Comment by beccaklam** [comment]
**Modal suggestion two:**
Support the March for Science by sharing a clever science-themed slogan. mozilla will design posters from 12 of our favorites. Follow us on Facebook and Twitter to print or share the final products.

**Comment by beccaklam** [comment]
@hannahkane @lovegushwa  would something like this work?
<img width="1440" alt="screen shot 2017-04-13 at 2 46 43 pm" src="https://cloud.githubusercontent.com/assets/20977376/25019274/0c540ab6-2058-11e7-96bc-b7e14717009a.png">

**Comment by hannahkane** [comment]
👍

**Comment by beccaklam** [comment]
@hannahkane 
**Shutdown site copy in modal:**
Thank you for sharing your March for Science slogan ideas! Our designers are excited to transform our favorites into 12 awesome posters. Follow us on facebook and twitter to print or share the final products.

**Comment by hannahkane** [comment]
@beccaklam - So very perfect.

**Comment by lovegushwa** [comment]
@beccaklam Liz suggested this edit: 

Support the March for Science by sharing a clever science-teamed slogan. Mozilla will design poster from 12 of our favorites. Follow us on Twitter to see the final results (and then print them and share them)!

**Comment by beccaklam** [comment]
@hannahkane @lovegushwa  
**latest iteration:** 
Support the March for Science by sharing a clever science-teamed slogan. Mozilla will design a set of posters from our favorites. Follow us on Twitter to see the final results (and then print them and share them)!

**Comment by hannahkane** [comment]
"science-themed" not "teamed"

Otherwise, ok with me. (Just out of curiosity, why are we removing FB?)

**Comment by beccaklam** [comment]
@hannahkane Liz suggested we use one channel to simplify!

**Comment by WillatMozFdn** [comment]
The downside of simplifying onto one channel is that we're going to exclude
a lot of people who are on FB but not Twitter.  Could I suggest that we
flip that back and ask for follows & announce in both channels?

(At least in terms of generating new subscribers, at both CREDO and Bernie
we found that FB produced about 90% of the action, versus Twitter, only
about 10%.)

 - W

**Comment by hannahkane** [comment]
Closing this ticket. Let's file new issues for things that come up.

**Comment by hannahkane** [comment]
Closing this issue. Let's file new issues for anything that comes up.
