### ISSUE TITLE
Tax Day snippet

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#815]
https://iheartopendata.org has been updated to reflect tax day messaging.

Needed:
- [ ] copy
- [ ] icon

**Comment by lovegushwa** [comment]
Looks like snippet copy is developing here: 
https://docs.google.com/document/d/11LhLsxSaesi0hHnhP9Iyu7fUzjPFExQjUpZVgFJccaY/edit

**Comment by hannahkane** [comment]
@lovegushwa to email Wes about whether icons are needed and if we're good on copy

**Comment by hannahkane** [comment]
Donezo.
