### ISSUE TITLE
QA: News Matrix country list is Europe

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#818]
This Week in the Web targets US, CA, UK, and AU. I think those should be the countries listed, if we need the country field at all (@caltrider?)

**Comment by ScottDowne** [comment]
Good call, forgot this. (it was built off of copyright)

**Comment by ScottDowne** [comment]
Adding these countries, however, it might be worth pointing out that country input is optional.

**Comment by hannahkane** [comment]
Looks close to good now, but UK isn't there, and "undefined" is.

**Comment by ScottDowne** [comment]
Fixed. I got hung up on country codes. UK country code is actually GB and not UK. Weirdos.

**Comment by hannahkane** [comment]
K. Works. Thanks!

**Comment by WillatMozFdn** [comment]
We really do want to have the country field -- that's super-helpful in
targeting emails (i.e., Copyright campaign to UK people, net neutrality
activism to US people, etc. etc.)

Unresolved question, though, is what to do with the edge cases of people in
other countries who want to sign up for this email ... let's say for
example Ireland ... ??

I don't have a good answer to that right now.

 - W

**Comment by hannahkane** [comment]
@WillatMozFdn - We do have the country field; it's just optional. We can add more countries to the list, like Ireland. Should we do that?
