### ISSUE TITLE
QA: madlib site

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#822]
Overall this page looks beautiful.

<img width="1538" alt="screen shot 2017-04-11 at 10 49 44 am" src="https://cloud.githubusercontent.com/assets/12228435/24968289/a947a870-1f61-11e7-8238-99811d700949.png">
@beccaklam lets sit and look at how the brand pallet is applied, look into a gradient background color or tiled background image. 

<img width="1544" alt="screen shot 2017-04-11 at 10 50 09 am" src="https://cloud.githubusercontent.com/assets/12228435/24968305/b5ea4614-1f61-11e7-9f64-1a516dcf3f89.png">
@ScottDowne Text style color when you click out of input field is not great. Is there a reason users need to click in and out of the input field?

**Comment by lovegushwa** [comment]
@beccaklam @ScottDowne these two color options are approved via brand. Focus on getting the science version ready to ship, we can review at standup. Excited to see this go live! 

I emailed you the sketch file (didn't see a folder for this project on the drive.) 

![screen shot 2017-04-12 at 6 27 10 pm](https://cloud.githubusercontent.com/assets/12228435/24992439/48cd6abe-1fd6-11e7-90a9-591a56a2ea81.png)

![screen shot 2017-04-12 at 6 27 44 pm](https://cloud.githubusercontent.com/assets/12228435/24992446/4f316e78-1fd6-11e7-84ef-79a4cac77750.png)

**Comment by hannahkane** [comment]
Closing this in lieu of #837
