### ISSUE TITLE
Choose and treat photo for Science poster ask email

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#824]
The email will go out Saturday, and we need to choose from a selection of photos of Steph's rad daughter making a sign.

(Steph shared these in a dropbox, which I just shared with @lovegushwa)

**Comment by hannahkane** [comment]
@natalieworth - would you have some time to work on this? I can share the dropbox with you.

**Comment by natalieworth** [comment]
@hannahkane yeah! for sure! do we have the resolution requirements?

**Comment by lovegushwa** [comment]
@natalieworth lets use our square callout. 250x250px
I passed the email with the photos in it along you to. 

... The image callout is small so you may need to crop in on the hand and the brush to make it work visually.

**Comment by natalieworth** [comment]
![science-graphic-v3 300dpi](https://cloud.githubusercontent.com/assets/14876567/25019259/dcc9b2a0-203e-11e7-9020-6ff85a6521dc.jpg)
@lovegushwa I made it 250 x 250 @ 300dpi? It was originally 144dpi but the resolution and image size looked really small on my Mac Retina display? It's only 29KB at 300dpi so it should be fine for email.

**Comment by lovegushwa** [comment]
@WillatMozFdn updated with the new callout image
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvVTNTaVRuSEhUaGM/view?usp=sharing

**Comment by WillatMozFdn** [comment]
got it, all good, afaik we can close this ticket
