### ISSUE TITLE
Ensure GA tracking & event implementation on Madlib and News Matrix site

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#826]
Hey @ScottDowne, just wanted to check in on the analytics setup for the two new sites. Is there anything I can help with on that?

As for requirements, each site should have its own GA property (I just filed a devops ticket [here](https://github.com/MozillaFoundation/mofo-devops-private/issues/52). The following custom events should be in place, utilizing the standard [syntax](https://docs.google.com/document/d/1HjOwcydEnfkX6tyd4MCt3tcEkloroyrKK5HDCQdmMMM/edit#heading=h.kt9r8418ucd9):

- form submit
- social share buttons
- madlib submit

The other thing I wanted to ask about is whether we could pass along full URLs on the signup forms. We are currently only sending along the domain (e.g. typeoutloud.org), but we should start passing along adjacent parameters as well for each session (e.g. typeoutloud.org?utm_campaign=test&utm_term=123... etc). This is already a standard practice on MoCo forms. Can we do this on the news matrix site?

Thanks!

cc @hannahkane

**Comment by ScottDowne** [comment]
This is done for madlib. Keeping open for news-matrix.

**Comment by hannahkane** [comment]
Closing, as news matrix has been indefinitely tabled
