### ISSUE TITLE
Create stylesheet for makerparty/nationbuilder

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#83]
Turns comps into a stylesheet.

Comps created in: https://github.com/MozillaFoundation/Advocacy/issues/81

If possible, store the stylesheet in a repo we can use for any code assets.

**Comment by ScottDowne** [comment]
Likely Fission does this, but for now, just pushing to next HB.

**Comment by ScottDowne** [comment]
Actually, doesn't make much sense to push this...

Wow, we have very little time...

**Comment by damiankay** [comment]
Closing this - I'm assuming Fission will take care of this
