### ISSUE TITLE
Create page for madlib takedown

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#830]
@ScottDowne @hannahkane 

Lets build this in the same style as the modal, but just center the type on a black page.

Thank you for sharing your March for Science slogan ideas! We will design a set of posters from our favorites. Follow us on Twitter to see the final products (and then print and share them)!

**Comment by ScottDowne** [comment]
This is fixed, and documentation is here: https://github.com/mozilla/typeoutloud.org#for-when-something-goes-bad-and-we-need-to-turn-off-input
