### ISSUE TITLE
Modal for Internet Health Madlib

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#836]
Fixes needed:
 - [x] mozilla logo needs highlight
 - [x] heart should be an image of a heart
 - [x] links should work, excluding a Share flow, which is happening in https://github.com/MozillaFoundation/Advocacy/issues/838

**Comment by hannahkane** [comment]
Forgot that we already wrote this:

"Thanks for sharing. mozilla made this because we <3 the internet. Help keep it healthy by sharing with your friends. Learn more about internet health here."

**Comment by HPaulJohnson** [comment]
^ this copy works for me

**Comment by hannahkane** [comment]
Cool.

Just to clarify - the "here" at the end should link to https://internethealthreport.org

**Comment by hannahkane** [comment]
@ScottDowne - updated original comment with remaining work

**Comment by ScottDowne** [comment]
Do we have links for the share yet?

**Comment by hannahkane** [comment]
I think @beccaklam commented on this [here](https://github.com/MozillaFoundation/Advocacy/issues/838#issuecomment-294977991)

**Comment by ScottDowne** [comment]
I just need the link in the modal, not the link in the top right? And it's in imgur now and not share progress, iirc, and becca's previous patch was for share progress link stying (although it also didn't have links)

**Comment by hannahkane** [comment]
The imgur links are for the Science Posters, not the Internet Health madlib.

I believe the link in the modal will go to ShareProgress, but perhaps we should discuss at stand?
