### ISSUE TITLE
Update colors for Internet Health madlib

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#837]
Just want to make sure we don't forget this. @beccaklam - can you please drop in whatever the final palette is?

**Comment by beccaklam** [comment]
@hannahkane @ScottDowne 
Green: #159D9B
Yellow: #FFF587
Pink: #FEC6C7
Purple: #B0B3E7
Blue: #C2E8F9
![internet health madlib hex codes](https://cloud.githubusercontent.com/assets/20977376/25144609/7269531e-243c-11e7-88a9-a5879398f3fa.png)
