### ISSUE TITLE
Add Share flow to madlib

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#838]
@beccaklam's design has a share icon in the top right corner. Let's add it.

**Comment by beccaklam** [comment]
@ScottDowne I have a pull request for this from the science repo. Let me know if you need help finding it?

**Comment by ScottDowne** [comment]
Live on staging: https://share.mozilla.org/352/180435

Just needs:

- [ ] links to be updated to prod.
- [ ] images and text.

**Comment by hannahkane** [comment]
@HPaulJohnson and @lovegushwa - can one of you please provide the images / copy to be used in the ShareProgress workflow?

**Comment by lovegushwa** [comment]
@hannahkane @ScottDowne 
- We are going to share videos not static graphics 
- We might need a different share progress instance for each of the three videos being tested
@agiedt any thoughts here? 
- I'm not sure if we can also add a poster (image) and a video we will need to test this.

Three videos
https://drive.google.com/file/d/0B20-0lpP23c0bzZmWmRWWjR5SzA/view
https://drive.google.com/file/d/0B20-0lpP23c0OU1OTGg3ZXJYaWc/view
https://drive.google.com/file/d/0B20-0lpP23c0TWlSNkZ0dTRBLXM/view

**Comment by ScottDowne** [comment]
@hannahkane We are blocked on Paul getting back to us, right?

My suggestion is to get a simple share progress page done, with just posters, links, and copy.

Then we can add enhancements with videos somehow.

**Comment by HPaulJohnson** [comment]
Hi all. I'm working on this right now and making edits directly in Share Progress. 

However, it's not looking like videos is a supported media type that can be shared. I have a question to their support team to confirm. If not, we'll need some static images to share and the sharing action will be driving directly to the madlib without any embedded video. 

Let me know if this doesn't make sense. Basically, as long as the SP page is linked to from typeoutloud instance we have setup for this, I can take it from here.

**Comment by agiedt** [comment]
In regards to the followiing:

   - We might need a different share progress instance for each of the
   three videos being tested
   @agiedt <https://github.com/agiedt> any thoughts here?

Ideally, I think you would want an distinct share progress instance for the
different videos.  However, it is possible that one would work.  Depending
on resource constraints you could work to build one and then see how it
goes.  Let me know if you want to talk this over.

Alex

**Comment by hannahkane** [comment]
Done!
