### ISSUE TITLE
Add Upvoting to typeoutloud.org

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#839]
Putting this here for discussion purposes. 

Would need to think about purpose / strategy questions, including:
 - [ ] how does upvoting fit into our meaningful actions or TEI definitions?
 - [ ] what value does upvoting add?
 - [ ] how might the addition of upvoting change our engagement strategy for future madlibs?

And various aspects of UX, including:
 - [ ] how to upvote
 - [ ] how to undo
 - [ ] how vote counts are displayed
 - [ ] whether votes affect ordering; what is the UX of the re-ordering of items

And technical implementation aspects, including:
 - [ ] how to prevent gaming / would we limit upvotes?
 - [ ] would we require login?

**Comment by lovegushwa** [comment]
@hannahkane would love to add this. Also could sharing be a form of voting? Like 'vote by sharing your favorite lines.'

**Comment by hannahkane** [comment]
@lovegushwa - that's a great idea.

Thinking on the question of "what's the value of upvoting?" - it could allow us to crowdsource topics for appointment content. For example, we could ask "What privacy-related topics would you like to see short videos on?" The addition of voting would make that much more meaningful for us as we decide what topics to invest production time in.

**Comment by HPaulJohnson** [comment]
closing for now. can re-evaluate as we think about how we might re-use typeoutloud in our 2018 engagement plans.
