### ISSUE TITLE
Create Maker Party copy deck

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#84]
Copy deck for the Maker Party events site on Nationbuilder.

We'll also have:
A list of pages defined here: #82
A list of features defined here: #75 

*Due date: \* September 6, 2016

**Comment by damiankay** [comment]
@KevZawacki I've set you as the assignee - please let me know if this should go to someone else! Please note this is for a future Heartbeat / milestone.

**Comment by damiankay** [comment]
@KevZawacki I'll follow up when we've finalized which pages are required, hopefully by EOW

**Comment by KevZawacki** [comment]
@damiankay Sounds good -- thanks.

cc @HPaulJohnson for awareness.

**Comment by KevZawacki** [comment]
Awaiting further direction -- changing milestone.

**Comment by damiankay** [comment]
@HPaulJohnson @KevZawacki Fission has requested that we have copy to them by August 24.

What can I do to support? Is there anything that you need?

Straw dog for content can be found here: https://docs.google.com/document/d/1driaq40M1b085sbyDoJSQAFkMsvEPvhnux3E-ZIkHN8/edit#heading=h.fx6wqxf7zyya

**Comment by HPaulJohnson** [comment]
@damiankay We have wireframes for the 2 main landing pages ( #130) but do we have any for the events pages themselves? We'd likely need those to do the necessary copy for those pages. 

We'll start with the 2 pages we have wireframes of for now.

**Comment by damiankay** [comment]
Requesting these now. Thanks!

**Comment by damiankay** [comment]
Confirming that Fission needs the copy deck by August 24th. I've requested the wireframes and will add asap. Thanks!

**Comment by damiankay** [comment]
FYI - Fission expects to send additional wireframes on Monday.

**Comment by damiankay** [comment]
@KevZawacki @HPaulJohnson - Wireframes are here: https://projects.invisionapp.com/share/G78C7AR2E#/screens/182608017

Please note there are two sets. We're going with the "Nationbuilder-y) wireframes. There might be a small tweak or two, but we really need to get moving on the copy deck. You can see the different options by clicking on the 9-box icon at the bottom of the page. 

Note, we'll need to wrap up the copy deck with internal sign-off by Sep 6 if at all possible.

**Comment by HPaulJohnson** [comment]
thanks, @damiankay. no problem, we are already making good progress on copy. i should have something to send through the approval process by thursday with the hopes that we could have sign-off by 9/6.

**Comment by damiankay** [comment]
You guys rock - thank you!

**Comment by HPaulJohnson** [comment]
Draft of copy for all pages complete. I'm having @KevZawacki do a final pass to tighten and clean up and then these should be ready to ship. 

https://docs.google.com/document/d/16ObBANwvduy59NjYC3aOF9cIPsDG3RdGszmHwqXHPv4/edit

**Comment by HPaulJohnson** [comment]
@KevZawacki has completed his edits so this should be ready to go for approvals. @damiankay to track down exactly who needs to review/sign-off on this before it goes to Fission.

**Comment by damiankay** [comment]
Thanks @HPaulJohnson & @KevZawacki 
I'm using this document as my guide for approvals: 
https://docs.google.com/spreadsheets/d/1wQt_Em7DkEWprx-bFHqV8CpHJub3T5Gf9YCKqbMA1XE/edit#gid=0

I'll update and close this issue as soon as it's made the rounds.

**Comment by HPaulJohnson** [comment]
I've tagged @shaghdoosti @chrislarry33 @geroter in the doc to review, if possible, by EOD 9/6.

**Comment by damiankay** [comment]
This has been approved. Closing

**Comment by TheoChevalier** [comment]
Hi, just a couple notes on potential mistakes I found while translating

“Facilitation: Making people feel welcome and excited to angage.” -> should be engage, I suppose :)

Also, wondering if this string was just a comment on the Gdoc and should not have been added to the copy https://pontoon.mozilla.org/fr/mozilla-advocacy/Copyright%20Petition/?string=154863

**Comment by TheoChevalier** [comment]
+ There might be an unwanted repetition of together here “Together we can amplify our organizations’ work together on copyright reform, reach and engage new audiences and create events that are relevant to your region, country or city.”

**Comment by ScottDowne** [comment]
Angage is a typo. I can fix in a bit. It's also very possible there are
strings in there that were not clear from the Google doc. I can double
check in a bit too.

**Comment by ScottDowne** [comment]
Updated the first two issues (The typo needs to go through review, so expect that done Monday), I'll let someone else comment on the double usage of together, as the fix feels a little less objective. @damiankay

**Comment by damiankay** [comment]
@HPaulJohnson would you mind looking at the comment on repetition above from @TheoChevalier ?

**Comment by HPaulJohnson** [comment]
Good catch @TheoChevalier, let's remove the second instance of together. So, this should be the final string:

"Together we can amplify our organizations’ work on copyright reform, reach and engage new audiences and create events that are relevant to your region, country or city."

**Comment by damiankay** [comment]
Thanks @HPaulJohnson 

@ScottDowne can you please edit the string as per Paul's suggestion above?
