### ISSUE TITLE
Paperstorm snippet

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#841]
- [x] copy
- [x] icon
--
- [x] French
- [x] Spanish
- [x] Italian
- [x] German
- [x] UK

**Comment by TheoChevalier** [comment]
@brettgaylor just checking, do we need a Dutch snippet if the website is not localized in Dutch?

**Comment by brettgaylor** [comment]
I seem to remember we were going to make a Dutch localization - but maybe Moniker has abandoned? I will ask.

**Comment by brettgaylor** [comment]
Snippet copy here @HPaulJohnson 
https://docs.google.com/document/d/1yvEeOYJp6mvT97BCo_rwFfgCcgJwlul1WUAUfrecF8w/edit

@natalieworth - we had an idea for the icon.  Could we use one of the classic 8-bit browsing hands, but have it furiously clicking?  Wonder if shrapnel / chaos could be flying away from its fingers? Or leaflets?

**Comment by TheoChevalier** [comment]
Still waiting for a final review for Italian snippets, but we should have all of them ready today (updated completed locales).

**Comment by TheoChevalier** [comment]
Italian is now ready too. Looks like the icon is the last missing piece

**Comment by HPaulJohnson** [comment]
Final versions, with translations and icons, submitted to snippet team today: 

https://docs.google.com/document/d/1VjHa2H6xgJFABjeLAgnLTPoDBmcguM1xqwUnGWPS5KE/edit

**Comment by brettgaylor** [comment]
Do we have an ETA from Snippet team as to when they'll turn it out?

We want to make sure @cadecairos is online when it happens so we can just monitor traffic surges - so morning Eastern time.

**Comment by HPaulJohnson** [comment]
@brettgaylor @cadecairos this is planned to go live tomorrow a.m. EU time and run for two weeks.

**Comment by brettgaylor** [comment]
Do you know if we can request a specific time - like -  14:00 CET, 9am EST?

**Comment by HPaulJohnson** [comment]
Scheduled for 9 am EST tomorrow.

**Comment by cadecairos** [comment]
Great, I'll keep my eyes on the health checks.

**Comment by natalieworth** [comment]
For ticket reference, I've uploaded the final export files and gifs here @1x and @2x sizes:
https://drive.google.com/drive/folders/0B20-0lpP23c0Nm1pSHcwVU5UMFE

My illustrator files for the static icons are here in case there are any size/ resolution issues: https://drive.google.com/drive/folders/0B20-0lpP23c0azJOeW5HdkxpS3c

**Comment by hannahkane** [comment]
Closing. Please re-open if incorrect.
