### ISSUE TITLE
Paperstorm email

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#842]
@brettgaylor - I think I understood that Paperstorm will need an email send at some point. Could you please fill out one of @WillatMozFdn's [email request templates](https://docs.google.com/document/d/1aEzfTaqUPbzA4kwnIIcfGNT2FOTf9msp0c1JNk8pw3g/edit) so we can get it on the calendar, and get the process going?

**Comment by brettgaylor** [comment]
I made a start to the template here:
https://docs.google.com/document/d/1VfZkOzsIEZM5cQzFXakTzmA12pBOHfjEz2HvBWr3hmo/edit

I'm not clear from this template whether I'm supposed to write the email myself?  I'm also not clear on how many days to leave, since I'm not that knowledgeable about the email production process.

**Comment by WillatMozFdn** [comment]
Yay for Brett!  Thanks for starting the process.

I'll be your writer here so don't worry about that.  But we should chat
since I want to find out the best ways to describe Paperstorm in a way that
will really make a splash.

 - W

**Comment by hannahkane** [comment]
@WillatMozFdn - do you have a draft of the copy so @beccaklam can make the callout?

**Comment by hannahkane** [comment]
ping @WillatMozFdn and @brettgaylor - do we have a target date for sending this?

**Comment by WillatMozFdn** [comment]
Email draft is here: https://docs.google.com/a/mozilla.com/document/d/199tAmvZhcqOa0QI6d9782j6T8ygGBgIe5vcBZauMzX4/edit?usp=sharing ... target date for the send is Thursday night the 11th (will set up the test to go out morning European time).

**Comment by WillatMozFdn** [comment]
@beccaklam (or @natalieworth ) -- the two callout box images I'd like to test in the email are basically screen grabs of what someone sees as they're using the paperstorm site (targeted on European parliament building).  The first is static ... the other would be an animated version of that with paper falling from the sky.  Size is 250 x 250 and of course need to keep file size reasonable -- so maybe no retina version?  I'll leave that up to your design judgment....  (cc @lovegushwa )

**Comment by beccaklam** [comment]
@WillatMozFdn 
Here is the gif and static graphic as requested. The gif is 625 KB and the static is 106KB. I made the static one 500x500 to accommodate for retina. Let me know if you need any changes!
![paperstorm-email-callout](https://cloud.githubusercontent.com/assets/20977376/25818748/aecdd164-33f9-11e7-8def-10a44a7ccc15.gif)
![giphy-static-2](https://cloud.githubusercontent.com/assets/20977376/25819240/5a1df638-33fb-11e7-8b27-9f55c3efd35d.jpg)


CC: @hannahkane @lovegushwa

**Comment by WillatMozFdn** [comment]
Nailed it, @beccaklam !!!  I think these are EXACTLY what we need.  Thanks!!!!
