### ISSUE TITLE
Design: Create Soapbox Engage petition template design

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#843]
@HPaulJohnson - could you please add details about what's needed here?

**Comment by lovegushwa** [comment]
@beccaklam did some exploratory wireframe work for a template in December.
https://redpen.io/p/rh3ca19956fb0a83c8

notable features:
- campaign updates
- comments from supporters 
- a thermometer 

Additional features campaigners asked for: 
- Ability to link to other content / campaign pages (links)

**Comment by lovegushwa** [comment]
@beccaklam we need to Re-skin this Sumofus page design to fit the new Mozilla brand.
Basically take the exact design but add our typography, color, button style and footer.

https://actions.sumofus.org/a/uber-ceo-travis-kalanick-has-got-to-go/

<img width="1443" alt="screen shot 2017-05-01 at 11 29 59 am" src="https://cloud.githubusercontent.com/assets/12228435/25589621/26ac0ea0-2e62-11e7-8de8-e0ea68687bb3.png">

**Comment by beccaklam** [comment]
@hannahkane @lovegushwa @HPaulJohnson Do I need to do this in Soapbox Engage? Or do I just need to come up with a design?

**Comment by hannahkane** [comment]
Good question, and I'm not sure of the answer. @HPaulJohnson - let me know if you'd like for me to coordinate with Matt on this.

**Comment by HPaulJohnson** [comment]
@beccaklam @hannahkane my understanding is that we are just doing the visual design of a template at this point and not actually doing anything in Soapbox.

**Comment by beccaklam** [comment]
https://redpen.io/p/no3f2c9ac5d374c402<-- redpen for comments

![desktop hd copy](https://cloud.githubusercontent.com/assets/20977376/25628223/72c70f02-2f33-11e7-80bf-48611f8eb2ac.png)
![desktop hd](https://cloud.githubusercontent.com/assets/20977376/25628224/72c71740-2f33-11e7-929c-d30ec59834f2.png)

**Comment by hannahkane** [comment]
I believe this is done.
