### ISSUE TITLE
DUE MAY 5: Paperstorm social

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#844]
We'll need some images to drive traffic to the site, and in particular I was thinking these should celebrate when a milestone within Paperstorm is reached, ie when users succeed in covering the EU parliament, or the Bundestag in Berlin, etc.

There are 20 locations within the app, each of who also have a corresponding MEP that users will be prompted to tweet at while they're paperstorming.

We don't need to celebrate all of these, but it would be fun to do some of them.  Here's a list of the locations, plus the MEPs associated with those locations:
https://docs.google.com/spreadsheets/d/14a0tNwyT7aghh_jyxpdCACpbUntH9EkD-W31zzSwBeo/edit#gid=0

So it would be great to have social content something like:

> We did it!  10,000,000 leaflets covering The EU on #paperstorm. What do you think, @commidini? Add yours at paperstorm.it

The graphic could either be a screenshot of that location covered, something soviet inspired, etc.

We should share these on both  Twitter and Facebook

**Comment by brettgaylor** [comment]
I just updated this ticket to reflect that we'll need both copy and images for this, and also to put this on the radars of @TheoChevalier and @agiedt  Do we want to engage localizers for this kind of social, or should we use vendors for this?  Or should we just use English for all locales?  

 @agiedt perhaps we'd just want to put paid behind the video post discussed in #840 ?

**Comment by brettgaylor** [comment]
- [ ] Twitter copy

- [ ] Twitter image

- [ ] Facebook copy

- [ ] Facebook image

- [ ] localized copy

**Comment by TheoChevalier** [comment]
> Do we want to engage localizers for this kind of social, or should we use vendors for this? Or should we just use English for all locales?

@brettgaylor Yes, I think localizing the social message is important, and that we should make it part of the global request (website, snippet, email, social). I’ll ask teams if they have cycles between next week and May 8th to work on each aspect, and if they don’t or are not responsive, we can hire our vendor for the most critical locales (TBD).

Do you think we can get the social copy with the snippet copy early next week? Or it will be ready later?

**Comment by brettgaylor** [comment]
I think we'd likely need till the end of next week to develop the social text, since we haven't yet started.  Sound right @HPaulJohnson ?

**Comment by lovegushwa** [comment]
@brettgaylor @HPaulJohnson we have some questions / blockers. 
- we need develop copy / a concept in tandem ... we should probably sprint on this with @HPaulJohnson to develop some initial copy ideas. 
- I'm assuming we are not doing paid promotion, the 20% text rule would make that impossible.
- How is localization of these social shares going to work? A post to @mozilla and https://www.facebook.com/mozilla/ for each location/goal reached? It does not seem like we would post 5 different localized posts to one channel for each goal reached.

**Comment by TheoChevalier** [comment]
>  It does not seem like we would post 5 different localized posts to one channel for each goal reached.

Actually, why not for Facebook? People would only see posts in their language.
If that was your concern (flooding people with text in language they don’t speak)
Not sure what we’ve been doing on Twitter in the past, I assume we still can’t target a locale nor a country…

**Comment by agiedt** [comment]
Facebook/Instagram will not serve content to users unless it is in their
selected language.

**Comment by lovegushwa** [comment]
@beccaklam @natalieworth I cleared up above questions with @brettgaylor this morning
- this is paid promotion, so we will not use any text in the posts
- facebook and twitter let you localize a post so ...  if you speak FR you only see the the FR post, and if you speak DE you only see the DE post
- we are going to select 6  [locations](https://docs.google.com/spreadsheets/d/14a0tNwyT7aghh_jyxpdCACpbUntH9EkD-W31zzSwBeo/edit#gid=0) to illustrate, a isometric style or straight on ground level view would look good, choose no more than 1 locations per country. https://www.pinterest.com/lovegushwa/paperstorm/

![img_20170424_180534](https://cloud.githubusercontent.com/assets/12228435/25364741/611c223a-2919-11e7-8e30-9e7cf8d5f034.jpg)

**Comment by lovegushwa** [comment]
@beccaklam @natalieworth
We also need 2 generic posts that are about meeting our paper drop goals but are not identifiable locations. Something like this would work: 

![img_20170424_180620](https://cloud.githubusercontent.com/assets/12228435/25364819/e8a6d0b0-2919-11e7-9386-d5f988ae311b.jpg)

**Comment by lovegushwa** [comment]
@beccaklam @natalieworth explore some styles (illustration, photo+3d etc.) could be a combination of a google maps street view photo and 3d rendered paper for example. Think click bait, these should make folks do a double take then scanning a social feed.

**Comment by beccaklam** [comment]
<img width="1024" alt="eu-parlement-3 2x" src="https://cloud.githubusercontent.com/assets/20977376/25546985/4af8d38c-2c33-11e7-8abe-3afb0e3a2f2b.png">

![test3a](https://cloud.githubusercontent.com/assets/20977376/25547027/6a43e45c-2c33-11e7-8774-566386e8ddf8.png)

**Comment by natalieworth** [comment]
@brettgaylor @lovegushwa @beccaklam @hannahkane We were able to get a start on the social concepts/ drafts for paper storm/ rain here: https://redpen.io/p/mn207cd41594cdfaa2
Feel free to add comments in the Redpen link or any other ideas we could try! There's a couple gifs in there too that are viewable in Chrome (sorry Firefox) :)

**Comment by HPaulJohnson** [comment]
copy shipped to @TheoChevalier for localization: https://docs.google.com/document/d/1yvEeOYJp6mvT97BCo_rwFfgCcgJwlul1WUAUfrecF8w/edit

**Comment by brettgaylor** [comment]
Hey @natalieworth @beccaklam @lovegushwa !

These are awesome.  My thoughts:

-The ones resonating for me most are the photo collage treatments, because they are quite different than the actual paper storm treatment.  The illustration feels closer to the actual site, which makes it seem more important that it really matches their style
-As i mentioned to Natalie, I don't think we can use an "anti" copyright symbol, since we are only opposed to bad copyright, not copyright in general. I'd propose instead that we use the meme faces from the flyers
-Now that we have some of the copy created, I think we should go with a third style - it would be cool to maybe mashup the "browsing hand" that browsers use when hovering a link, and uncle sam/soviet style propaganda, which is always pointing at people/the future.  Some of the copy in the social uses phrases like "For Europe! For Culture!" etc, and would pair well with a cheeky take on clicktivism/activism/propaganda.  Social copy is here:
https://docs.google.com/document/d/1yvEeOYJp6mvT97BCo_rwFfgCcgJwlul1WUAUfrecF8w/edit

**Comment by beccaklam** [comment]
@hannahkane @lovegushwa @natalieworth Social with border, paper and memes
https://redpen.io/kzcb523c51684ab802 <-- redpen for comments
![budestag](https://cloud.githubusercontent.com/assets/20977376/25637250/5988a040-2f52-11e7-9247-94b8ac3e50ff.jpg)
![coleseum](https://cloud.githubusercontent.com/assets/20977376/25637246/5984d154-2f52-11e7-8a7a-035d4c646356.jpg)
![eiffel-tower](https://cloud.githubusercontent.com/assets/20977376/25637249/5986dbd4-2f52-11e7-87df-6835bb411ce1.jpg)
![eu-parliament](https://cloud.githubusercontent.com/assets/20977376/25637245/59849cde-2f52-11e7-9204-9dd4b313e74e.jpg)
![palace-of-culture-and-science](https://cloud.githubusercontent.com/assets/20977376/25637247/598507dc-2f52-11e7-9702-52ad7d38362f.jpg)
![prague-castle](https://cloud.githubusercontent.com/assets/20977376/25637248/5986a2e0-2f52-11e7-934f-1e4db8b2a505.jpg)

**Comment by brettgaylor** [comment]
These are great!

Two things:
1) we had to replace Bundestag with Reichstag.  Could you swap that in @beccaklam ?
2) Feels like this is a good opporunity to try the new brand - I was talking to  Bradley Cohen there about using Paperstorm as an opportunity to explore the identity system.  Could we try adding the moz://a, plus "Paper Storm" below in this images as a way to explore the lockup?

**Comment by brettgaylor** [comment]
Here's the deck they've circulated:
https://docs.google.com/presentation/d/1oToaX4Q96ysuz1p9sFeTvtJBi7gG7u6ckddeT4iAXs0/edit#slide=id.g1db296cfe6_1_59

You can see there that Paperstorm would be an example of the "supported by" system on page 4-5

**Comment by lovegushwa** [comment]
@beccaklam @brettgaylor so Bundestag and Reichstag are the same building, so nothing to change!

**Comment by beccaklam** [comment]
@lovegushwa @brettgaylor @natalieworth @hannahkane put some lockup options in the redpen: https://redpen.io/kbe6f2655aa4c4f369

**Comment by beccaklam** [comment]
@brettgaylor @lovegushwa @hannahkane @natalieworth final social exports here:
https://redpen.io/hy297f61918beb1cd4 <-- redpen
![paperstorm-social-1](https://cloud.githubusercontent.com/assets/20977376/25707288/0bd0a5e0-30b1-11e7-8d85-5bfce4b6f16f.jpg)
![paperstorm-social-2](https://cloud.githubusercontent.com/assets/20977376/25707290/0bd8c626-30b1-11e7-923e-b67379dc1b1d.jpg)
![paperstorm-social-3](https://cloud.githubusercontent.com/assets/20977376/25707292/0bda7c32-30b1-11e7-8513-97a808850dbd.jpg)
![paperstorm-social-4](https://cloud.githubusercontent.com/assets/20977376/25707289/0bd64fb8-30b1-11e7-8c48-bba39405fe2d.jpg)
![paperstorm-social-5](https://cloud.githubusercontent.com/assets/20977376/25707291/0bd9cb5c-30b1-11e7-8766-e0f257704c7c.jpg)
![paperstorm-social-6](https://cloud.githubusercontent.com/assets/20977376/25707293/0bdb57d8-30b1-11e7-8a1e-f1a9f5c8ee47.jpg)

**Comment by beccaklam** [comment]
@hannahkane @lovegushwa @natalieworth @brettgaylor All the final social files can be found in this folder: https://drive.google.com/drive/folders/0BzuBOR2VJQqUbzJYemh6WFc5NTg?usp=sharing
All my files are in this folder: https://drive.google.com/drive/folders/0BzuBOR2VJQqUZ01fX2U5SFRVQTg?usp=sharing

**Comment by hannahkane** [comment]
Nice work, @beccaklam!

@lovegushwa @brettgaylor - are we good to close this ticket?

**Comment by brettgaylor** [comment]
Good from my end!

**Comment by HPaulJohnson** [comment]
All of the social with translations in a single doc: 

https://docs.google.com/document/d/1aTSTy1wOMssbLIbgyC0jKr8qr0cgzhuLirn6tXEvDLA/edit

Shared with comms and moco social teams as well. 

Once we have the video asset we can get paid campaign setup and wrap this up.

**Comment by Rillke** [comment]
It might be off-topic but the paperstorm.it performs too slowly to be useful to me; and while it is loading it writes something about an "Epische Schlacht" - which might be true but might be also not well perceived and tempts me to close the tab immediately. We had enough battles in Europe and I will not participate an another one, I thought. Throwing paper around to waste my environment, even if it is virtual ... it's simply too hard to understand the point the site is trying to make. /OpinionFromGermany
