### ISSUE TITLE
Bug: typeoutloud.org replace non-retina images

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#847]
X to close modal and share icon are non retina. Replace with @2x or SVGs.

<img width="786" alt="screen shot 2017-04-20 at 6 06 36 pm" src="https://cloud.githubusercontent.com/assets/12228435/25258418/22b4f756-25f4-11e7-89e9-c26a9eabd731.png">

**Comment by beccaklam** [comment]
@ScottDowne Here are the @2x icons!
[@2x icons.zip](https://github.com/MozillaFoundation/Advocacy/files/947152/2x.icons.zip)
If you want me to implement them I can, just thought it might be easier for you to do it since you probably have everything set up already.

**Comment by ScottDowne** [comment]
I can do it.

**Comment by beccaklam** [comment]
@ScottDowne Thanks!

**Comment by ScottDowne** [comment]
@beccaklam just a reminder we wanted to go with svg for these, likely.

**Comment by beccaklam** [comment]
@ScottDowne svg files:
[svg icons.zip](https://github.com/MozillaFoundation/Advocacy/files/948137/svg.icons.zip)

**Comment by ScottDowne** [comment]
Landing now.
