### ISSUE TITLE
Bug: typeoutloud.org modal not optimized for mobile

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#848]
@beccaklam 
The modal is not great on mobile, it should be close to the middle of the screen and the text should be larger (looks perfect on desktop, please don't change that!) Can you make it better!? 

CC@ScottDowne 

<img width="498" alt="screen shot 2017-04-20 at 6 15 42 pm" src="https://cloud.githubusercontent.com/assets/12228435/25258595/6b3a994e-25f5-11e7-87b3-e95a63d4d553.png">

**Comment by ScottDowne** [comment]
Yeah I can def make the text bigger. Not sure what you want with it
centered.

**Comment by ScottDowne** [comment]
I made text bigger, line height bigger, and margin top and bottom bigger.

Let me know if that's enough.

**Comment by ScottDowne** [comment]
Did a bunch of changes again. Should be vastly different now.

**Comment by lovegushwa** [comment]
@ScottDowne new version looks great!
