### ISSUE TITLE
Polish feature complete sandbox

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#86]
Take the feature complete sandbox created here: https://github.com/MozillaFoundation/Advocacy/issues/85

And implement:
- [ ] copy https://github.com/MozillaFoundation/Advocacy/issues/84
- [ ] styles https://github.com/MozillaFoundation/Advocacy/issues/83
- [ ] any missing backend work

**Comment by damiankay** [comment]
Closing as I believe Fission will be taking care of this.
