### ISSUE TITLE
DUE APRIL 27: Copy for Net Neutrality petition

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#863]
The petition will be based on [this one](https://iheartopendata.org/en-US/).

We'll need:

- [x] Headline (replaces "Did you know you’re a major funder of scientific research?")
- [x] Subhead (replaces "Open access to publicly-funded research accelerates discovery and progress.")
- [x] CTA (replaces "Get Involved" on button)
- [x] Body text
- [x] Form headline and instructions (replaces "Do you agree? If so, add your name to these principles and share widely so we can help create more space for open data and science. Your signature, combined with hundreds of scientists, will show our leaders that taxpayers expect to see the results of the scientific research so we can build on and expand on these findings.")
- [x] Footer copy (replaces "Mozilla is a global non-profit dedicated to putting you in control of your online experience and shaping the future of the web for the public good. Visit us at mozilla.org." though we could certainly just re-use that.)
- [x] Submit button copy (replaces "Add my name")
- [x] ShareProgress copy for Email
- [x] ShareProgress copy for Facebook
- [x] ShareProgress copy for Twitter

( @ScottDowne - anything else?)

**Comment by lovegushwa** [comment]
@HPaulJohnson is this still happening? @WillatMozFdn said it's the call email, do we still want this for later?

**Comment by hannahkane** [comment]
Ashley told me yesterday she still wants to do this, in conjunction with Moco, and that Josh will wrangle copy tomorrow. @ScottDowne is working on the build now (to be launched on Monday).

**Comment by ScottDowne** [comment]
I also need copy for the share bits that we'll be using. We can use share progress or the html share tags, either is fine with me. Just having the copy is probably the hard bit.

**Comment by hannahkane** [comment]
Noting that we have draft copy for the site including the form, but we still need copy for the ShareProgress prompts.

**Comment by hannahkane** [comment]
@levjoy is working on this

**Comment by hannahkane** [comment]
Final copy is here: https://docs.google.com/document/d/17I8lRVknvicmhLTP-TO1HGBfLPEmkvx4-7PVfIV_XU4/edit

Note: We still need ShareProgress copy from @levjoy, please!

**Comment by HPaulJohnson** [comment]
@hannahkane here is copy for Share Progress: 

https://docs.google.com/document/d/1fch2gBIE_CA_ogK9xncuqZuJwnxN8sdgpblfrEbo4-s/edit

@lovegushwa to supply FB share image tomorrow

Let me know if you need anything else. cc/ @levjoy

**Comment by hannahkane** [comment]
cc @ScottDowne ^

**Comment by hannahkane** [comment]
Closing this ticket, since we have all copy now.
