### ISSUE TITLE
We should share an editable version of the Privacy & Security Toolkit with localizers

### ISSUE THREAD

**Issue by chadsansing** [MozillaFoundation/Advocacy#864]
Let's make #825 editable for a community member in Brazil who wants to localize the Privacy & Security Toolkit.

cc @beccaklam, @hannahkane

**Comment by beccaklam** [comment]
Hi @chadsansing, just wanted to follow up on this. Will I be receiving a set of strings to plug into my InDesign file or did you want me to upload my InDesign file?

**Comment by chadsansing** [comment]
I haven't gone through this process before, @beccaklam, so if you tell me what to send you in what format, I can do that sometime this week in between Rockwood sessions; otherwise, proceed with any format a lay user could localize with a .pdf editor? Apologies for my ignorance here :)

**Comment by hannahkane** [comment]
Sorry, @chadsansing, I didn't realize localization was a requirement for this. @beccaklam - correct me if I'm wrong, but I'm guessing we can't make this editable with a pdf editor. @chadsansing - do you expect other people will want to localize?

**Comment by chadsansing** [comment]
We have a Brazilian Mozillian ready to localize.

**Comment by chadsansing** [comment]
This is more of an inquiry than a requirement - my bad for not thinking of it earlier.

**Comment by hannahkane** [comment]
Given the number of projects and tight deadlines in our queue, I'm going to suggest we hold off on this, unless it's trivial to implement.

**Comment by HPaulJohnson** [comment]
@chadsansing doing a ticket cleanup. what are your thoughts on this? can we close or is it still an opportunity we should consider resourcing in 2018?

**Comment by chadsansing** [comment]
Let's close, @HPaulJohnson -
