### ISSUE TITLE
DUE APRIL 28: NN petition image

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#865]
Similar palette/concept to the Pai/phone image used in today's email, but without the phone focus.

**Comment by hannahkane** [comment]
@lovegushwa - can you assign this, please? thank you!

**Comment by lovegushwa** [comment]
@natalieworth can you give me some image specs? (~size in px)

**Comment by lovegushwa** [comment]
image size is ~ 4500x3900px

**Comment by lovegushwa** [comment]
@ScottDowne the petition site graphic is ready:
(hit me up with a preview so I can make sure the 'NO' looks good as a responsive image.)

https://drive.google.com/file/d/0B2qu3ExKWIlvb1NKNWJzR3FiSW8/view?usp=sharing

**Comment by ScottDowne** [comment]
Done: https://advocacy-mozilla-org-staging.herokuapp.com/en-US/net-neutrality/
