### ISSUE TITLE
EMAIL SHIPPING MAY 1: NN petition email #1

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#866]
This is rapid response, so I don't know that we'll be able to follow the timeline outlined in the Email Planning Template. It sounds like we're going to need an email as soon as Monday to drive people to the [NN petition](#862) we're spinning up.

Ashley has said we'll likely do more than one email push, and will discuss the strategy with @WillatMozFdn later today.

- [ ] Josh will provide the copy.
- [ ] @lovegushwa to assign someone to create the image, based on the copy
- [ ] @WillatMozFdn to coordinate the send

**Comment by WillatMozFdn** [comment]
So, brief update after our campaign meeting yesterday.  We need to harmonize our verbage for the petition with a number of other groups; we're not going to participate in their joint email-to-petition project (NEVER ever participate in one of those btw!) but we WILL go in with them on delivering petition signatures.  So our language needs to be pretty close to theirs ... which means we can't write our email or petition until a coalition of groups agrees on language. Which makes a May 1 email launch kinda doubtful. For now, though, we can and should focus on spinning up our website/petition page with placeholder verbage.  I'll start a RASCI/Planning document for the email now; even though timeline is unclear at this point, the information in that document will help us be ready for fast approvals and send when we do have final verbage.

**Comment by lovegushwa** [comment]
@WillatMozFdn 
Here are a few email callout options. 'Darth Pai' is my favorite: 
(Will should we run a test?)

https://drive.google.com/file/d/0B2qu3ExKWIlvWFlsZDNwbEM5UGM/view?usp=sharing
https://drive.google.com/file/d/0B2qu3ExKWIlvTVdaSVU0VFF3M0k/view?usp=sharing
https://drive.google.com/file/d/0B2qu3ExKWIlvR2c4dFpDYWJYNWc/view?usp=sharing

**Comment by hannahkane** [comment]
This happened.
