### ISSUE TITLE
Fix typography on NN Petition Site

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#867]
@beccaklam the petition site typography feels off. Can you take a pass at it? We can implement Zilla if it's straight forward and not a blocker to shipping quickly.
<img width="1393" alt="screen shot 2017-04-28 at 10 40 43 am" src="https://cloud.githubusercontent.com/assets/12228435/25540328/842d70ce-2bff-11e7-9f13-4e658ad2dba6.png">

**Comment by beccaklam** [comment]
Type changes were implemented yesterday. @ScottDowne Is there a place @lovegushwa can look at the changes? CC: @hannahkane

**Comment by ScottDowne** [comment]
Should be on staging shortly after being merged to master.

**Comment by ScottDowne** [comment]
https://advocacy-mozilla-org-staging.herokuapp.com/en-US/net-neutrality

**Comment by ScottDowne** [comment]
I'm going to close this.  We can iterate on new things as we find them in new issues.
