### ISSUE TITLE
DUE THURSDAY: NN snippet copy and icon

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#868]
- [ ] copy
- [ ] icon

**Comment by hannahkane** [comment]
@levjoy - could you provide the snippet copy, please?

**Comment by HPaulJohnson** [comment]
Working on snippet copy here: 

https://docs.google.com/document/d/1pQnAml4Qo9ZBGBe4GYK6lIKLONMJxXwEQY8Yy9a1DjA/edit

Started with May 4th themed ideas and will add in more evergreen ideas in the a.m. @levjoy, if you have additional ideas please add to this doc. 

RE: 5/4 version, we are pretty tight on timeline and I repurposed copy as much as possible from email and petition but it's unclear what approvals we've received on those. Snippet team will need assurances that this language has been previously approved to proceed. @hannahkane do you know the status of approvals on email copy and petition?

**Comment by hannahkane** [comment]
Per Ashley's email, we have final approval on email and petition language. :)

**Comment by hannahkane** [comment]
I believe this is done. Closing!
