### ISSUE TITLE
Safety Tips user journey map

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#872]
Let's use a visualization to think through how people will:
 * discover Safety Tips
 * sign up for emails via Safety Tips
 * discover secondary CTAs, specific to each Safety Tip

**Comment by hannahkane** [comment]
@beccaklam and @HPaulJohnson to co-create this

**Comment by beccaklam** [comment]
![safety first user journey map](https://cloud.githubusercontent.com/assets/20977376/26206391/b1a70a2a-3bb2-11e7-9617-76d01c816867.png)

**Comment by hannahkane** [comment]
This is super helpful!

A few questions: 
- are the modals on the LP and the IP the same? If so, it feels maybe too aggressive to show it a second time, if they just dismissed it. (Also, I'm assuming we wouldn't show it a second time if they signed up on the first one.) But maybe they're different CTAs (e.g. the first one is email, the second is share?)
- is the modal CTA the same as the "Subscribe" button on the page itself? I think so, but just checking. I still feel like "Subscribe" in this context sounds more like you're subscribing to a YT feed.

Will be good to keep this updated as we add more CTAs.

**Comment by hannahkane** [comment]
Wondering if this ticket has served its purpose. Do we still need it?

**Comment by beccaklam** [comment]
I think it has, the actual journey map is different from the above. I think we can close this for now and if we need to make another map we can make a new ticket.
