### ISSUE TITLE
Bug: NN petition, change how mozilla is written in copy

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#876]
@ScottDowne replace "moz://a"  with "Mozilla" in the body copy ... and should also not be in a bolder weight, should be the same weight as the body copy.

<img width="497" alt="screen shot 2017-05-04 at 11 20 49 am" src="https://cloud.githubusercontent.com/assets/12228435/25718780/3556567a-30bc-11e7-9486-df4494378348.png">
<img width="866" alt="screen shot 2017-05-04 at 11 20 55 am" src="https://cloud.githubusercontent.com/assets/12228435/25718927/9d4edcb6-30bc-11e7-9226-587df72cfc63.png">

**Comment by ScottDowne** [comment]
@lovegushwa That's a feature of the Zilla font. It does that all by itself. The characters and bold changes.

I can turn it off only by making those lines not the Zilla font.

**Comment by lovegushwa** [comment]
@ScottDowne I slacked you a updated version of the typeface, should fix this issue.
