### ISSUE TITLE
end of life plan for petitions

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#880]
How are we going to end-of-life petitions?

Options include:
 * Do nothing. Keep them open indefinitely. (Periodic updates to SF?)
 * Keep the page alive, but replace the form with a "we're no longer accepting signatures" message.
 * Kill the page.

@stephaniemcv @ScottDowne @HPaulJohnson @lovegushwa @levjoy @caltrider - any opinions on this?

**Comment by WillatMozFdn** [comment]
I not a fan of the "do nothing" option -- that's basically an open-ended
commitment ... so within 6-12 months, those periodic updates will be
unmanageable and a giant time-suck for Scott and Stephanie (with, most
likely, very little return). Also, petitions often go stale once
circumstances move on.

The second option -- just close it off and not accept new signatures --
seems best to me.

(And of course our options will be different once soapboax engage is in
place -- I imagine they have pre-set options for de-activating a petition.)

 - Will

**Comment by ScottDowne** [comment]
I don't have a strong opinion about the three options, but if I had to pick something, I would say just kill it, and redirect it somewhere.

For the future, I think ideally, we get to a point where we bring back petitions.mozilla.org, then we can put all our petitions there under a path, like petitions.mozilla.org/copyright or petitions.mozilla.org/net-neutrality. Then we can put which ever campaign is our current one under petitions.mozilla.org/

Once we end of life a petition, it would redirect to petitions.mozilla.org/ which would just show our most recent petition.

This means we wouldn't have vanity urls unless we made an exception for some reason, but it allows us to move much faster and ship a petition in a day or less, and would be able to easily kill stuff off without too much fuss.

This plan is also maintainable by one dev, as it wouldn't require constant devops resources to create and teardown servers and urls.

**Comment by stephaniemcv** [comment]
I also vote for killing and redirecting.

**Comment by hannahkane** [comment]
What would we redirect to? 

@ScottDowne's suggestion re: petitions.m.o suggests we'd redirect to a newer petition, but I think that's potentially confusing. If you thought you were going to a copyright petition, and instead landed on a net neutrality petition, it would probably seem like a bug. 

I do like the idea of petitions.m.o, and I think that workflow could be finessed a bit. We could have a modal: "Sorry, copyright is no longer accepting signatures. But have you tried net neutrality?"

Should we consider a solution like that ^ for the current copyright and open data petitions? (i.e.. Redirect both to NN, but add a modal explaining why we did it)

To @WillatMozFdn's point about Soapbox—it does sound like we're working towards replacing our petition tooling with Soapbox, but I'm unclear on when that will fully happen, especially given the lack of a workable localization flow (as I understand it). Hmm...I'm going to ask that this be added to the next Advocacy team meeting agenda.

**Comment by ScottDowne** [comment]
@hannahkane yeah, I like that idea better around "Sorry, copyright is no longer accepting signatures. But have you tried net neutrality?" and agree that a straight up redirect would seem like a bug.

**Comment by caltrider** [comment]
I like @hannahkane's suggestion. Let's go with the  petitions.m.o shut down, redirect with the message of "Sorry, copyright is no longer accepting signatures. But have you tried net neutrality?"

That work for everyone @WillatMozFdn @ScottDowne @stephaniemcv @hannahkane?

**Comment by stephaniemcv** [comment]
Works for me!

**Comment by hannahkane** [comment]
per conversation with @stephwright - for the iheartopendata letter, we're going to keep the page live, but replace the form with copy.

Thanks, all, for your feedback on this issue. I'll close this ticket, and will open new ones for the implementation details.

**Comment by hannahkane** [comment]
Sorry, just realized the Change Copyright campaign wasn't actually a petition. It's just an email signup. @ScottDowne - do we have to shut it down? Is it not talking directly to basket?

**Comment by ScottDowne** [comment]
Yeah this is still connected to basket. I dunno if we need to shut it down
for any technical reasons.

**Comment by stephaniemcv** [comment]
Let's not shut Copyright down, especially if it's just an email signup.

**Comment by hannahkane** [comment]
Closing this ticket, as plan for Copyright is NoChange, and plan for Open Data is in #899.

Not discussed above, but the NN petition will remain open for awhile, so no need to address anything there.

As @WillatMozFdn points out above, much of this becomes moot in a Soapbox Engage world.
