### ISSUE TITLE
BUG: tweets need https:// in twitter to be clickable

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#881]
Current @mozilla tweet isn't clickable because it isn't recognizing paperstorm.it as a URL
![image](https://cloud.githubusercontent.com/assets/345974/25858845/c82fb7ce-34aa-11e7-82bc-3270f0d147b2.png)

Let's make sure we have the full URL for future tweets - can we fix/repost that one?

@HPaulJohnson not sure who has their finger on the tweet trigger

**Comment by HPaulJohnson** [comment]
I let Kevin Z and Liz know for future tweets. Not sure who posted this particular one but both of them and me will have our fingers on the tweet trigger from time to time. 

For this particular one, we are just going to have to live with it.
