### ISSUE TITLE
Design: Due July 12 - Half-page ad

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#885]
Mozilla is sponsoring Netroots Nation this August, and as part of the sponsorship deal we get an ad in the program (spec details below). 

Netroots reaches an audience of about 2k bloggers, grassroots activists, and progressive organizers focused on US issues. Recently, Black Lives Matter and the Bernie Sanders campaign were heavily promoted at the conference.

Specs: Full Color (CMYK), 7.5” wide x 4.75” tall, high-res PDF or tif file preferred, with all fonts outlined.

More conversation to come regarding focus and message of ad.

**Comment by hannahkane** [comment]
Note from May 16 discussion with @HPaulJohnson and @Melechuga: need to have messaging in place by end of All-Hands

**Comment by hannahkane** [comment]
pinging @HPaulJohnson and @Melechuga - just want to see if there are any relevant updates in terms of clarifying messaging, and make sure it's still on your radar to clarify before/during All-Hands.

**Comment by hannahkane** [comment]
from meeting with @Melechuga, @HPaulJohnson and @lovegushwa: key message is that progressive orgs need a healthy internet. CTA is to attend the Lean Data Practices for Civil Society Organizations session.

**Comment by hannahkane** [comment]
Aiming for concept done before All-Hands, though final execution isn't needed until later.

**Comment by Melechuga** [comment]
Here's a link to our session, if useful: http://www.netrootsnation.org/nn_events/nn-17/lean-data-practices-for-civil-society-organizations/

**Comment by hannahkane** [comment]
As discussed on today's stand, @natalieworth is going to check in with the durable team to see if there are Net Neutrality assets we can repurpose. @Melechuga - would this work for you?

**Comment by natalieworth** [comment]
@Melechuga @hannahkane @HPaulJohnson @lovegushwa @beccaklam Couple of options for this in here: https://redpen.io/p/nw4539295777aafb41
They're focused on promoting the session, but it'd be good to pin down what specific content I should include (e.g. date, time, location, etc?) Not sure how much is necessary or if this is the right messaging for it?

**Comment by Melechuga** [comment]
Thanks @natalieworth!
I added some notes in the redpen; loving v.2, but have some questions re: the original intent of the design.
Also I tried editing my comments, but just ended up agreeing with myself a lot so...yea...sorry :-/

**Comment by natalieworth** [comment]
@Melechuga there are 2 pdfs in this folder https://drive.google.com/drive/folders/0B20-0lpP23c0UUhTVUo3TXpoelU?usp=sharing
1 option includes 'bleed' (I wasn't sure if the printer needed that or not)? If not, we can just send them the regular option.
