### ISSUE TITLE
Bulk submission of comments to FCC

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#887]
We're building a [front-end to collect comments](#886) from the public in regards to the potential for new net neutrality rules from the FCC.

We'll need to devise a mechanism for delivering those comments to the FCC. Can be delivered in bulk or in batches, but needs to account for FCC backend instability.

Deadline will be determined by effort estimate.

**Comment by hannahkane** [comment]
Hoping @simonwex can lead on this

**Comment by hannahkane** [comment]
My understanding is this is in progress. Plan is to upload a small set via csv as a test, and if all goes well, do a large batch. Then, keep monitoring as new comments come in, and upload as needed.

cc @alanmoo @cadecairos @levjoy

**Comment by digiexchange** [comment]
Hi all - just curious how the test went?

**Comment by levjoy** [comment]
Hi 0- just curious how the test went?

**Comment by cadecairos** [comment]
I uploaded 99 records on Friday, June 9th - I just did a search on the FCC website, and they've yet to be entered.

**Comment by alanmoo** [comment]
(This is to be expected, but if they're not showing up early next week we'll investigate alternative options)

**Comment by levjoy** [comment]
Ah! Sounds good.

**Comment by cadecairos** [comment]
Just to update here...

I submitted rows 2 to 100 and they were accepted and posted by the FCC last week.

Based on that success, about an hour ago I submitted rows 101 to 35600 (35499 comments) via the bulk upload tool on the FCC website. We should expect to see them sometime next week, during the all-hands meeting.

**Comment by hannahkane** [comment]
Just confirming that we have evidence those comments landed, right, @cadecairos?

Should we plan on something like a weekly upload between now and the end of the campaign? @cadecairos - what would work best for you?

**Comment by hannahkane** [comment]
@cadecairos @alanmoo - the FCC will stop accepting comments after August 17th, so we should plan to submit any we haven't already by then.

I'll be on PTO starting tomorrow through Wednesday, so please direct any questions to @brettgaylor or @levjoy. Thanks!

**Comment by alanmoo** [comment]
The comment period has been extended to August 30.

**Comment by hannahkane** [comment]
Closing this since it's being tracked in the dev-ops repo
