### ISSUE TITLE
ASAP: Content and requirements for FCC comments front-end

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#888]
- [x] form fields, in preferred order (including checkbox for permission to use comment publicly)
- [x] which form fields are optional/required
- [x] additional field validation, if any + error messages (including, for example, if there's a character minimum or maximum for the Comment field)
- [x] desired url and path (final: advocacy.mozilla.org/net-neutrality-comments)
- [x] page content
  - [ ] headline
  - [ ] sub-headline
  - [ ] CTA button text, to jump to form
  - [ ] main body content
  - [ ] form intro
  - [ ] submit button text
  - [ ] ShareProgress copy (email, Twitter, FB)

We'll use the final content/messaging to determine whether a new hero/ShareProgress image is needed.

**Comment by levjoy** [comment]
Form field info and other notes here: https://docs.google.com/document/d/1F5I2ZDMKUhfe6uQOKuTEL0XTx6Hyrkbo_lpFLjQ9WU4/edit

Content to come.

**Comment by hannahkane** [comment]
Thanks, @levjoy! I added some questions; some for you and some for @ScottDowne.
