### ISSUE TITLE
Celebratory paperstorm tweet

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#889]
We have covered the EU parliament + Eiffel tower, and likely Prague Castle by tomorrow morning.

Should we send out some tweets?  These are the ones we pre-wrote:
Yes! We dropped 10 000 000 leaflets dropped on the EU Parliament! 🎉  We think @comodinicachia noticed :) Join paperstorm.it!

^^ use some of the graphics we haven't used yet?  I also have some screen grabs

OMG @JeanMarieCAVADA the Eiffel tower is covered in a #paperstorm.  [number] leaflets have been dropped at paperstorm.it

I wonder if adding the video to these might be better engagement technique?  The images we've used so far, the "postcard" style - didn't seem like they caught people's eye as much as we'd hoped.

 @HPaulJohnson what are the chances can we send these tomorrow?

**Comment by hannahkane** [comment]
@brettgaylor - did this happen?

**Comment by brettgaylor** [comment]
No - was stalled in some strategy discussions around when to do a 2nd round of press pitching.
