### ISSUE TITLE
Change link to advocacy to be a more prominent call to action

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#89]
As we start to plan snippet access, it would be great to consider adding some list growth options - I'd like to consider sending one cohort of users to a share page (after they share the emoji with a friend) that includes an embedded signup form. Thoughts @valianttry @ScottDowne ?

![screen shot 2016-07-08 at 3 51 32 pm](https://cloud.githubusercontent.com/assets/19785709/16741828/e40f833c-4759-11e6-9558-7a8169ba26b6.png)

**Comment by ScottDowne** [comment]
I believe basket signups currently require a server, and I don't think codemoji has one. So that'll need to be created too, although maybe there is an existing shared one we can use.

@cadecairos ^^

**Comment by cadecairos** [comment]
Codemoji does, in fact, have a server! 

https://github.com/mozilla/codemoji/blob/d573d92500545024f8fb62874828a27dd2b7687a/web/server.js

**Comment by damiankay** [comment]
@ScottDowne @cadecairos are there any other technical challenges that might make this a risky proposition to complete this week? 

@valianttry @brettgaylor If you'd like to proceed I can ask Natalie to work on the UX.

**Comment by ScottDowne** [comment]
Then yeah, this isn't too bad, can be done in a week. Not sure if I have the time to do it this week.

**Comment by brettgaylor** [comment]
We'd need to do it this week if it were to be used, since goal is to have it for world emoji stuff which will launch friday

**Comment by damiankay** [comment]
@brettgaylor do we need an entirely new page, or should we add a CTA to the top section (near "learn more about how encryption works")?

**Comment by brettgaylor** [comment]
The idea here was actually whether we could embed a form in that page, rather than a link (which we already have)

**Comment by damiankay** [comment]
Right - sorry. Do we have form elements that we can pass on to @natalieworth for UX design?

**Comment by ScottDowne** [comment]
Both a link to a sign up form page or a form right in an existing page
should be pretty easy. I would talk to designers though about adding a form
to an existing page though. It might be too much going on and distract from
our primary focus goal on that page.

**Comment by brettgaylor** [comment]
It would be the type of thing that it would be great to A/B test.

My gut is telling me that this is beyond the scope of this week.

**Comment by damiankay** [comment]
@ScottDowne how long would it take to set up Optimizely on the Codemoji site in order to do some A/B testing?

**Comment by ScottDowne** [comment]
Dunno how long. So I think I should spend 15 mins tomorrow to figure that
out. My guess is a couple hours.

**Comment by brettgaylor** [comment]
@scottdowne and I met about this issue and decided that a form would likely be too distracting within the page.  Given we know that conversions to the link at the top of the page "Learn more about how modern encryption works" are poor, a compromise could be to change the text to something more direct such as "Sign up with Mozilla Advocacy to learn more about encryption"

@HPaulJohnson what do you think of the suggested language above?

**Comment by HPaulJohnson** [comment]
Think this is a good, short-term/quick way to address issue. For mobile, we might be a bit long on word count. Can we drop the Mozilla or Advocacy or both to tighten it up: 

"Sign up to learn more about encryption"

**Comment by valianttry** [comment]
Can I suggest an alternative? We would likely increase the optin rate by offering one field, say email, and a "submit" button that then lands the user on a full form. Their email address could be auto-filled from the previous field page. Meaning, we don't need to embed the entire form on the codemoji page.

**Comment by ScottDowne** [comment]
Just to help anyone to get an idea as to what page we're talking about:

![ctas](https://cloud.githubusercontent.com/assets/197334/16778696/2426a2e6-483d-11e6-80ef-67eb4c4af75b.png)

We're talking about adding a signup mailing list link in the top white banner, instead of a link to a signup, correct?

cc @natalieworth

**Comment by brettgaylor** [comment]
@valianttry discussion today was that we probably didn't have cycles to add a form and then it was dubious since might depress conversions to the other CTAs on that page (ie share the encoded message).  Do you disagree/think adding email is worth experimenting?

**Comment by brettgaylor** [comment]
@ScottDowne it would go to the same page.  We're just talking about changing the copy.

**Comment by valianttry** [comment]
Agreed @brettgaylor . The share this message function is so important for driving traffic it's probably not wise to muck it up (e.g. "choice paralysis"). Right now there are two direct links to our optin form: 1) when i click "learn more" in the footer, and 2) "learn more about how encryption works" at the top. If I click on either one, I land on the page version with the full form on the right, which is good (below). I wasn't in the chat, but I don't think codemoji's primary goal is optins -- it's already asking a lot of a user -- and if they're truly interested there are paths to opt in. That said, we can talk about alternative locations for a more obvious optin - perhaps the footer.

![learn_about_encryption_-_mozilla_advocacy](https://cloud.githubusercontent.com/assets/9830371/16786202/eb0d1836-4847-11e6-86ac-3fe355bb5b6b.png)

**Comment by brettgaylor** [comment]
Looks like we ran out of runway for this.
