### ISSUE TITLE
Design: NN stickers!

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#891]
Potential elements:

- mozilla logo
- "Save the Internet"
- "#netneutrality"

@natalieworth to work on design + logistics of rush printing in DC (for use on Tuesday)

**Comment by hannahkane** [comment]
cc @caltrider

**Comment by hannahkane** [comment]
@natalieworth - are we good to close this ticket?

**Comment by natalieworth** [comment]
@hannahkane yeah! sent the stickers to Jen on Friday
