### ISSUE TITLE
Design: NN comment collection page

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#892]
We're using the NN petition as a basis, but will need to make design adjustments to accommodate the very different form.

@beccaklam - you can see the form fields and, as of now, draft copy in [this doc](https://docs.google.com/document/d/1F5I2ZDMKUhfe6uQOKuTEL0XTx6Hyrkbo_lpFLjQ9WU4/edit#)

Things we've discussed:

- smaller hero image
- we need to figure out what to signal to the user in terms of an appropriate comment length
- can consider other changes, too, like changing the layout of the page, if it serves the goals of getting people to fill out a longer form, including providing a thoughtful comment

**Comment by beccaklam** [comment]
@hannahkane So I looked over the doc. I'm a bit confused: are we creating our own version of the form the FCC already has on their site? https://www.fcc.gov/ecfs/filings/express

**Comment by hannahkane** [comment]
Sorry, @beccaklam, I should have explained more. Yes, the FCC has a form, but we're going to host our own front-end to collect the required info, and then submit to the FCC site on behalf of our users.

The motivation behind this is two-fold: 1) so we can drive our users to comment with a better user experience than what the FCC provides, and 2) so we can count the number of actions our users have taken.

**Comment by beccaklam** [comment]
@hannahkane sounds good. I'm proposing something like this design for the comment collection page. I basically just tweaked the design I made for the Soapbox Engage Template:
![comment collection page](https://cloud.githubusercontent.com/assets/20977376/26013525/de7d4888-3726-11e7-9faf-36bd6eb066bd.png)

**Comment by beccaklam** [comment]
@hannahkane ^ this is all just dummy content

**Comment by hannahkane** [comment]
From a product/goals perspective, this is a great iteration. Thanks, @beccaklam.

**Comment by beccaklam** [comment]
@hannahkane @ScottDowne @lovegushwa 
Updated the design with the copy and form fields:
Note: I tried to make it look more 'serious'.
https://redpen.io/p/fq8e4b885ee77e3b9f <-- redpen for comments
![desktop hd copy 3](https://cloud.githubusercontent.com/assets/20977376/26076388/9c78a768-3986-11e7-9044-df1996cbc18c.png)


If a user checks the e-mail box:

![desktop hd copy 4](https://cloud.githubusercontent.com/assets/20977376/26076394/9fbcc83c-3986-11e7-9af1-a7f5dbce8693.png)

**Comment by hannahkane** [comment]
@beccaklam - thanks for this iteration! I think it looks great. Have invited @levjoy to comment and offer feedback about the more formal/serious direction.

**Comment by hannahkane** [comment]
@beccaklam - do you have an idea about what the hero image might be? @lovegushwa - will we have Foxy images we can use?

**Comment by hannahkane** [comment]
per planning conversation, sounds like we want to try the broken glass image. @lovegushwa - can you get that to @beccaklam to try, please?

**Comment by beccaklam** [comment]
@hannahkane @lovegushwa @ScottDowne 

![desktop hd copy 3](https://cloud.githubusercontent.com/assets/20977376/26080319/f56268ac-3993-11e7-937d-0dc83e69cf8a.png)
![desktop hd copy 4](https://cloud.githubusercontent.com/assets/20977376/26080318/f55dba50-3993-11e7-9019-0fee7524ccf6.png)

**Comment by beccaklam** [comment]
@hannahkane @lovegushwa @ScottDowne  Added some minor changes to the desktop version (i.e. moving privacy policy sentence before the 'submit your comment' button, and also did another treatment for the title to see if it feels more onbrand) and added mobile screens. You can see them in the redpen (mobile screens don't translate well to github in my opinion): https://redpen.io/p/fq8e4b885ee77e3b9f

**Comment by beccaklam** [comment]
@hannahkane @lovegushwa @ScottDowne Updated the NN comment collection design mock up with the final text: https://redpen.io/p/fq8e4b885ee77e3b9f Just waiting on image from @lovegushwa

**Comment by hannahkane** [comment]
@lovegushwa @beccaklam - how are you feeling about the site design with the Foxy image? Are we good to close this?

**Comment by hannahkane** [comment]
Flagging that if we do go with Foxy for now, we'll have to change it later as the drivers for this site (email, social, etc.) get less Foxy-specific. This image is super weird without the additional Foxy context.
