### ISSUE TITLE
Animated gifs for FR, DE, ES Paperstorm emails

### ISSUE THREAD

**Issue by WillatMozFdn** [MozillaFoundation/Advocacy#893]
As expected, the animated gifs won out in the testing we did this morning with the Paperstorm email.

So for French, German and Spanish versions -- aiming to launch on May 18 or 19 -- we should use the same kind of graphic, only ... showing the flyers flying in these three respective languages instead of English.

Make sense?

*Start date: May 12, 2017* 
*Due date: May 17, 2017* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @beccaklam @lovegushwa @stephaniemcv

**Comment by beccaklam** [comment]
@WillatMozFdn Here are the DE and FR gifs. The ES version of paperstorm.it is currently buggy. Will try on Monday again. CC: @hannahkane 
![de](https://cloud.githubusercontent.com/assets/20977376/26015271/63b54594-372e-11e7-9e77-ef5f480919ac.gif)
![fr](https://cloud.githubusercontent.com/assets/20977376/26015283/6bb147de-372e-11e7-9749-64d939016c40.gif)

**Comment by WillatMozFdn** [comment]
Awesome, thanks @beccaklam!

**Comment by beccaklam** [comment]
@WillatMozFdn Here is the ES gif:
![es](https://cloud.githubusercontent.com/assets/20977376/26069536/3062d2cc-396f-11e7-9457-0216f171c57a.gif)

**Comment by WillatMozFdn** [comment]
Confirmed that we do need the Italian animated gif ... hopefully the site
is less buggy now?

Possible by 5 PM eastern time tomorrow, so I can queue up the email for
Friday (EU time) launch?

many thanks!!

 - Will

**Comment by beccaklam** [comment]
@WillatMozFdn  Here you go! Can you close this ticket if we're good? Thanks :)
![it](https://cloud.githubusercontent.com/assets/20977376/26172322/f9e1d6dc-3b15-11e7-9c05-21bd9a474a14.gif)

**Comment by WillatMozFdn** [comment]
all good, please go ahead and close.  thanks!!!!
