### ISSUE TITLE
Compare Call Congress tools

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#894]
We need a call tool that meets the following requirements:

- Matches U.S.'ians to their Congresspersons and Senators, based on geography (either zip code, or lat/long), and initiates a phone call between the user and the target
- Allows for us to add corporate targets as well
- passes security and vendor reviews

The following requirements are nice-to-haves:
- localizable
- ability for user to initiate through SMS 
- free and open source 

Can we look at Call Power and potentially other tools, including tools we've used in the past, and assess whether requirements are met?

**Comment by hannahkane** [comment]
@ScottDowne - are there add'l technical requirements you'd want to add? Please update the first comment accordingly. :)

**Comment by hannahkane** [comment]
@ScottDowne - a good deliverable for this might be a matrix comparing different products across features and technical specs. Alternately, the deliverable could just be your opinion and rationale for what tool we should use.

**Comment by brettgaylor** [comment]
Note that we granted Open Media to do some work on the call-power tool - https://github.com/spacedogXYZ/call-power/pull/12#issuecomment-273640224

They have a bunch of experience using it that I'm sure they'd be willing to share.  Currently powering many different call-your-rep campaigns.

**Comment by hannahkane** [comment]
Oh, thanks, @brettgaylor. Did not know that. That's important context.

**Comment by ScottDowne** [comment]
One thing I noticed, given all the requirements in the initial comment, there is nothing asking for an admin dashboard, or the ability to create or edit campaigns, ideally without a dev. That's the major power of a tool or platform.

Given the requirements, both needs and nice to haves, it sounds like we're describing a back end technology or service, and not a tool or platform.

**Comment by ScottDowne** [comment]
As per what we've used in the past, all I have used is call.mozilla.org which connected to a back end service that used twilio. It worked well enough but pretty much just did the one thing.

**Comment by hannahkane** [comment]
I think this ticket is no longer needed. We've identified a tool, and I believe we're conducting a vendor review now.
