### ISSUE TITLE
Bug: Fix em-dash's on petition site

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#897]
@ScottDowne can you fix the em dashes on the new petition site?
https://advocacy-mozilla-org-staging.herokuapp.com/en-US/net-neutrality-comments/#advocacy

one after needed "neutrality"
<img width="707" alt="screen shot 2017-05-17 at 10 42 26 am" src="https://cloud.githubusercontent.com/assets/12228435/26169444/85d991c6-3af2-11e7-92d2-bc251e3b972a.png">

two needed in the sentence "Net neutrality allows consumers -- not big companies -- ..."
<img width="727" alt="screen shot 2017-05-17 at 10 42 18 am" src="https://cloud.githubusercontent.com/assets/12228435/26169468/9d7327ca-3af2-11e7-8f92-a1d469d566e4.png">

**Comment by ScottDowne** [comment]
Done
