### ISSUE TITLE
Bug: replace logo on new petition site with SVG

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#898]
Hey @ScottDowne, the logo as implemented is not on brand. Can you replace it with a logo SVG you can download here? https://mozilla.ninja/s/Mozilla_Large-Logo_Black-and-white.zip

<img width="425" alt="screen shot 2017-05-17 at 11 22 19 am" src="https://cloud.githubusercontent.com/assets/12228435/26169654/679baaa4-3af3-11e7-9b85-feb3b84c24d8.png">

**Comment by ScottDowne** [comment]
Is the idea we want it to be pixel perfect? Or is their some weird reason we need to use an svg for this?

I would like to keep doing this with css, if possible. I can get them the same with css.
