### ISSUE TITLE
DRAFT copy for fundraising email follow-up to encryption campaign

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#9]
Andrea is working on a draft here:
https://docs.google.com/document/d/1n7PkKT75hLcNzfwkb1ljaWESXSKI96Utn2vqgVOj-Ms/edit

I'll update this ticket when it's ready for review and approvals! 💰
#262 is where a callout design is happening

**Comment by valianttry** [comment]
@stephaniemcv I just worked on the draft more -- I shipped it off to @msurman for a quick look to make sure the tone/approach is on point, then we can push through review and approvals asap. Launch Friday morning would not be terrible. Call outs look so good!

**Comment by valianttry** [comment]
OK Mark gave it a thumbs up, @KevZawacki and @brettgaylor can you please look over this draft by 11am PST / 2pm EST Thursday? ?? 
https://docs.google.com/document/d/1n7PkKT75hLcNzfwkb1ljaWESXSKI96Utn2vqgVOj-Ms/edit

[--- Commented from Asana.com
#commenter Damian Kuehn
---[aa]

**Comment by KevZawacki** [comment]
@valianttry Gladly -- just added my thoughts. Looks great!

**Comment by valianttry** [comment]
Chris Riley is looking at it right now

**Comment by valianttry** [comment]
@stephaniemcv i know you're out of town... what's your best guess on test + ship schedule for this?

**Comment by stephaniemcv** [comment]
Build and test today, ship Monday, that way we could still get the tip 1 out Thurs/Friday. I'm not seeing any other email sends this week. But will confirm

**Comment by ScottDowne** [comment]
Closing this, looks like it was done, and is also quite old.

Feel free to reopen or refile something.
