### ISSUE TITLE
Choose: Nationbuilder or build an in-house campaign microsite featuring a petition sign up form

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#90]
An online petition is a key part of our public education and engagement strategy for Copyright reform.
We need to build a petition page that can accept signatures from people in the following locales:
p1: Germany, France, Italy, Spain, UK
p2: TBD

**Deadline to go live: August 31, 2016**

Key questions:
1. Can Nationbuilder send data to Salesforce?
2. Can Nationbuilder be stood up in time for the work we would need to do to launch a petition site in multiple locales on August 31?
3. Is security review still moving forward for Nationbuilder? Is that a blocker for using Nationbuilder?

Here is an example of an organization using Nationbuilder for a petition page:
http://www.gunxgun.org/join_the_movement

**Comment by ScottDowne** [comment]
To my knowledge, we've only stored petition signatures in BSD.

I don't know if crm can do this, and if it's going to be ready in time.
I don't know if ET/basket can do this.
Then there is nationbuilder.

**Comment by damiankay** [comment]
@ScottDowne - is your recommendation to go with Nationbuilder then, assuming we need it to connect with Salesforce and have it ready for Aug 31? 

Also, can we tie it (I.e. Nationbuilder microsite/petition) in with Pontoon for localization?

**Comment by ScottDowne** [comment]
No, I still feel better not relying on nationbuilder with such a risky timeline.

I'm trying to see if using BSD for petitions like we used to use it has any downsides.

The previous flow was a microsite that was hosted completely by us https://github.com/mozilla/petitions.mozilla.org. We then would send the data into BSD, which would then be used when we sent along the petition. I don't know why we cannot do it that way again. It's not like this is signup data. And it's not like this is data we can keep around inside something like a CRM. If our petition also wants to be for signup, we have to ask that separately and do double opt in, and would just use basket/exact target like we have been.

**Comment by valianttry** [comment]
@ScottDowne I have major concerns about using BSD for anything. I am hoping to send them a termination letter this week which means complete shut down in 90 days. We've disabled all forms using BSD for good reason.

**Comment by damiankay** [comment]
@ScottDowne Let's wait to see what is required from the user stories #92 before choosing a path. I think that the rest of the team would like to use Nationbuilder if at all possible for the Petition site, as that's what we'll need to use in the future, and this campaign will continue on through H1 2017.

**Comment by ScottDowne** [comment]
@valianttry I agree, but we don't have a replacement ready yet, and we're planning a campaign that's dependent on this functionality, putting us in a pretty hectic (and risky) position.

**Comment by ScottDowne** [comment]
I guess, without BSD, nationbuilder is our only option. Making this choice kinda simple.

**Comment by ScottDowne** [comment]
I took a quick look at nation builder's petition setup, and it looks like we can send data to it, but create the form off nation builder if we want to. Or use the whole thing.

So we have the option for using it as:
- signature storage + page hosting
- just signature storage

It also makes the signature process quite a bit easier if they already have an account  in nationbuilder, because a lot of the info is assumed based on their account info when the signed up.

**Comment by ScottDowne** [comment]
The required fields in a nationbuilder petition is only first name, last name, and email OR phone.

It doesn't look to have much of a configuration, or that I can find yet, for the fields we display/collect.

**Comment by damiankay** [comment]
That's a great catch @ScottDowne . Any other functionality / design limitations that might be relevant to this project / future petition sites?

**Comment by ScottDowne** [comment]
Nothing yet, it looks functional.

The only thing I want to stress is we can still use this with or without a micro site, depending on the needs of the campaign. My guess is we don't do the micro site without good reason.

So the only risk is still making sure it's through sec review.

@damiankay we should probably setup a call with me, maybe you, and the designer, so I can do a demo for nationbuilder petition pages. With the goal of understanding the limitations, so design can be done with limitations in mind.

**Comment by damiankay** [comment]
Awesome - thanks @ScottDowne !

I'll set up a meeting with the designers for early next week.

**Comment by ScottDowne** [comment]
I poked around nationbuilder for localized pages. Looks like there is no supported way (that I could find), there is a hack, but it doesn't scale at all. So the more locales we have, the harder changes become. Also won't integrate with Pontoon.

My advice is we build the micro site, outside of nationbuilder, which sends the signatures to nationbuilder/crm.

**Comment by ScottDowne** [comment]
I found a thing (it's not great, but better than nothing) that does machine(free) or human(paid) translation via a free trial or paid account that works with nationbuilder, example: http://makerparty-mozillasandbox.nationbuilder.com/?locale=de

**Comment by ScottDowne** [comment]
It's called http://www.bablic.com

**Comment by ScottDowne** [comment]
Decision: nationbuilder

I did a test today to get the petition signatures into nationbuilder from a microsite.

Nationbuilder uses an authenticity_token on the client that needs to be validated on the server.

So only their pages can push the data into nationbuiler, and because we only have one system that can handle signatures, it makes a microsite not feasible for this campaign.
