### ISSUE TITLE
QA NN comment collection site

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#901]
Staging is here: https://advocacy-mozilla-org-staging.herokuapp.com/en-US/net-neutrality-comments/

 - [x] Design QA ( @beccaklam - feel free to check now if you're good with design )
 - [x] Salesforce QA ( @stephaniemcv - can you please confirm all is well? )
 - [x] Copy QA ( @levjoy - can you give the site a once-over?)
 - [x] Functionality + overall QA ( @hannahkane )

**Comment by beccaklam** [comment]
@ScottDowne CC: @hannahkane 
Not sure why but the form side seems to break a bit when the browser is greater than 1800px:
![screen shot 2017-05-18 at 1 59 31 pm](https://cloud.githubusercontent.com/assets/20977376/26216510/66a8a09a-3bd2-11e7-9122-a70a7d2ccfcd.png)

Is there a reason we're not capitalizing these titles?
![screen shot 2017-05-18 at 1 59 55 pm](https://cloud.githubusercontent.com/assets/20977376/26216561/8827fac2-3bd2-11e7-8259-50037ad1c4d0.png)

Very nit-picky: but can we center these icons?
![screen shot 2017-05-18 at 2 02 40 pm](https://cloud.githubusercontent.com/assets/20977376/26216613/b3d2a9d8-3bd2-11e7-95ae-b3c91da5acb2.png)

**Comment by WillatMozFdn** [comment]
Also nit-picky -- in the first talking point, can we put the period inside
the quotation marks?

That is,

 Net neutrality has been called the "First Amendment of the Internet".

should be...

Net neutrality has been called the "First Amendment of the Internet."

**Comment by ScottDowne** [comment]
Building those fixes, should be live by the time you read this, cept for "Is there a reason we're not capitalizing these titles?" because the answer is yes, we were requested to keep them all lowercase from MoCo brand.

**Comment by hannahkane** [comment]
@ScottDowne - Twitter message is missing the first letter.

**Comment by stephaniemcv** [comment]
staging not hooked up to SF, I can only test in production

**Comment by hannahkane** [comment]
@ScottDowne - last paragraph in left column feels like a non-sequitur. Suggest removing it and adding "Brief, specific and personal comments are most effective" as placeholder text in the comment field.

![screen shot 2017-05-18 at 3 46 43 pm](https://cloud.githubusercontent.com/assets/8389648/26220654/4fa5f44c-3bc8-11e7-928c-a27cdebb8e78.png)

**Comment by levjoy** [comment]
Here's suggested revised copy for the Share Progress email copy: 

Hi - 

I just told the FCC, in my own words, why it needs to scrap its plans to hand over the internet to big cable companies like Comcast, AT&T, and Verizon.

The FCC is inviting public comments on this hugely important issue. Send in YOUR comment in support of net neutrality now. https://advocacy-mozilla-org-staging.herokuapp.com/net-neutrality-comments/?sp_ref=304876451.352.181032.e.0.2&source=email

**Comment by hannahkane** [comment]
@ScottDowne - Can we put a favicon on the ShareProgress page?

**Comment by ScottDowne** [comment]
" Twitter message is missing the first letter." Fixed

**Comment by stephaniemcv** [comment]
All is well with email addresses going into Salesforce and confirm/welcomes firing.

**Comment by hannahkane** [comment]
OK, I'm going to say we're good to go. There are a few outstanding items that @ScottDowne will get to, but nothing that would block the email send or the video from going out.

@HPaulJohnson, please point the shortlink ( mzl.la/savetheinternet ) to the new address so we can use that for the video.

**Comment by ScottDowne** [comment]
I'm pretty sure I've done everything (it's building now) but the favicon, which I dunno how to do in share progress but we might get to tomorrow.

If there is anything you requested that's not currently done, let me know 'cause it means I forgot ;)

**Comment by hannahkane** [comment]
@ScottDowne - looks good. If you can tomorrow, please remove "Brief, specific and personal comments are the most effective. Submit your comment now, and tell the FCC to leave net neutrality alone." from the bottom of the left column, since the placeholder text in the comment field makes it redundant. 

Thanks!
