### ISSUE TITLE
Switch to PayPal Giving Fund from 

### ISSUE THREAD

**Issue by roseregina** [MozillaFoundation/Advocacy#902]
PayPal Giving Fund is a 501c3 that allows other 501c3 organizations to receive donations through PayPal with a reduced processing fee. It also functions as the backbone to many popular low level fundraising pushes, like Humble Bundle. 

By registering ourselves with PayPal Giving Fund we may be able to avoid paying some PayPal fees and gain additional donations through additional exposure to supporters. 

Because of the fee reduction, we might be able to reduce our minimum PayPal donation since there is not the same fraud incentive as with credit card donations. However, I am unclear if we can have two PayPal accounts connected to the same 501c3 for this program and if we do enough volume that we might already receive a better rate. 

--> I do not know how this will effect the current set up with the micropayment account and given the effort and complexity, I want to make sure that this has not already been investigated and found to be an undesirable option. 

--> I also do not know if this will effect what information we receive or how we would acknowledge PayPal donations once that is integrated with SalesForce since PPGF does the legal acknowledgement. 

Information on PayPal Giving fund: [https://www.paypal.com/givingfund/faq#nonprofit](https://www.paypal.com/givingfund/faq#nonprofit)

*Start date: May 18, 2017* 
*Due date: July 15, 2017* 

CC: @WillatMozFdn @cadecairos @ScottDowne 
__

**Comment by WillatMozFdn** [comment]
Closing this one -- after reading too many horror stories about these guys, such as here: https://www.paypal-community.com/t5/About-Payments/PayPal-Giving-Fund-problem/td-p/954817 ... not a path I think we should go down anytime soon.
