### ISSUE TITLE
Design uniform "tips" text treatment

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#905]
We need a unfirom text treatment for the "HERE COMES THE TIP" part of these videos.  Rebecca's is an example:

https://drive.google.com/file/d/0BzuBOR2VJQqUbkVTcERqNkFBam8/view

Also - do we want a uniform logo/CTA at the end of them for Safety Tips?

Jordan you mentioned you would tackle making screens for these pre-PTO

**Comment by lovegushwa** [comment]
@brettgaylor going to take care of the web banner assets, can you loop in @natalieworth on the uniform treatment bits for the video? ... I already talked to her about a style for the 'tips' today, and creating a 'Safety First' bumper.

**Comment by brettgaylor** [comment]
👍
