### ISSUE TITLE
Callout box for emailed update to donors

### ISSUE THREAD

**Issue by WillatMozFdn** [MozillaFoundation/Advocacy#908]
Detailed description of work: Need a callout box graphic for an emailed update to all of our donors from EOY 2016.  Email scheduled for Thursday 6/1.  Suggest 8-bit heart theme, with "Thanks Again!" as the overlaid text (but totally open to other options.)

@beccaklam @natalieworth @lovegushwa 

*Start date: May 30, 2017* 
*Due date: May 31, 2017* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by natalieworth** [comment]
hey @WillatMozFdn I've got 2 gif options and 2 static options for these (let me know if either could work depending on your copy):
![email-thankyou-callout-01 2x](https://cloud.githubusercontent.com/assets/14876567/26596798/cf3f41d0-4524-11e7-9a03-fccf66d6e790.gif)
![email-thankyou-callout-02 2x](https://cloud.githubusercontent.com/assets/14876567/26596799/cf424e02-4524-11e7-94fc-ff846d269e0b.gif)
![email-thankyou-callout-03 2x](https://cloud.githubusercontent.com/assets/14876567/26596801/cf47e100-4524-11e7-86f3-1d913a82b176.jpg)
![email-thankyou-callouts-04 2x](https://cloud.githubusercontent.com/assets/14876567/26596800/cf4508b8-4524-11e7-90ed-15e20a4a9cb8.jpg)

**Comment by WillatMozFdn** [comment]
Thanks, these work great!
