### ISSUE TITLE
Nationbuilder security review

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#91]
The Nationbuilder risk assessment bug in Bugzilla can be found here: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1277667

It's a private bug - if you need access please let @valianttry @cadecairos @ScottDowne or @damiankay know.

**Comment by damiankay** [comment]
@ScottDowne or @cadecairos could one of you please give Jonathan Claudius access to the Nationbuilder sandbox? He needs to assess their security controls.

**Comment by valianttry** [comment]
@ScottDowne granted him access and he's running vulnerability assessments this week. Once completed, we should be able to launch contract discussions with Nationbuilder.

**Comment by ScottDowne** [comment]
@damiankay is there anything left that's actionable for me in this bug?

**Comment by damiankay** [comment]
@ScottDowne I don't think so at the moment, but let's keep it open for now.

**Comment by ScottDowne** [comment]
Works for me. Moved it to you for now as requested :)

**Comment by valianttry** [comment]
We had a productive meeting with Nationbuilder yesterday. There are some final security Qs for them to answer, led by @simonwex and @cadecairos .

**Comment by cadecairos** [comment]
@valianttry I think we can call this completed! agreed?

**Comment by valianttry** [comment]
This is completed. Closing.
