### ISSUE TITLE
Design for first 3 videos

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#910]
- [x] Create "messaging" motion graphics for password manager video
-recreate the instant messaging messages to be more clear and consistent - make sure they look like multiple systems, though
-make the interviews look like they are taking place within video conferencing, like skype
-these should give impressions rather than recreations of an actual product - no logos

- [x] Consistent treatment when the "tips" appear

- [x] Consistent closing bumper

- [x] Change font to Antonio for all the videos

**Comment by natalieworth** [comment]
**Draft** Exports of Videos are here:
https://drive.google.com/drive/folders/0B20-0lpP23c0aGIwVDBnRzgzNmc

Things to adjust:
Me: add brett's music attribution: http://freemusicarchive.org/music/Ketsa/May_Starlight_Find_You/waxing_waning
- still working on bumper
@beccaklam change the link colour on the last slide from the orange to pink colour (#F793FB) (the template didn't seem to update across all of them from the orange to pink)

cc @hannahkane @HPaulJohnson @brettgaylor

**Comment by beccaklam** [comment]
@natalieworth Changed the colour of the last slide from orange to pink and updated the drive!

**Comment by natalieworth** [comment]
https://drive.google.com/drive/folders/0B20-0lpP23c0aGIwVDBnRzgzNmc

**Comment by natalieworth** [comment]
@brettgaylor wifi video is added in here (still have to add the bumper to it and add the 'mozilla' logo at the end to all 4 videos)
cc @beccaklam

**Comment by brettgaylor** [comment]
Hmm @natalieworth I think thats based on an old project.

I sent you a DM where I had adjust the music at the beginning and integrated Hannah's feedback, but I'm not seeing that here....

**Comment by natalieworth** [comment]
Dropping in the V2 exports of the videos here: https://drive.google.com/drive/folders/0B20-0lpP23c0Mlg2ZWpmM3c5WFU?usp=sharing

When/ if they are good to go for uploading, I'll change folder name to 'final' exports for YouTube.
