### ISSUE TITLE
Safety first video: WiFi

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#911]
Script
https://docs.google.com/document/d/16G4sv_24sPSQlgstQrDdz15ouhepo68ZJrmLuzGCrfs/edit

**Comment by brettgaylor** [comment]
First cut
https://drive.google.com/open?id=0B0bF99sa1fRJbDcxUGktZXVvQVU

@natalieworth @hannahkane @HPaulJohnson @beccaklam thoughts?

**Comment by hannahkane** [comment]
This looks great. A few things:
 * I wonder if "Public wifi is great" should be visible a second or two before "But it can be scary" - I think this would give the line more punch
 * Is it "insecure" or "unsecured"? I'm honestly not sure. Is one more correct?
 * I like how the encryption video tells you you're about to see three tips. Should this video have a similar marker to help people get oriented to what's coming?
 * I think "use a VPN" is the important part, not "If you use wifi often." Could the type be adjusted to reflect that?

**Comment by beccaklam** [comment]
I love the music, the pacing is really nice!
I agree with all of @hannahkane 's points listed above ^.
The only thing I noticed was we're using pretty tight leading for most of our all caps type and there are some pretty big gaps in some screens. I would tighten those up but otherwise looking so good!

**Comment by natalieworth** [comment]
@brettgaylor pacing is good with the music cuts! We could do a design pass when it's finalized if you want to adjust type spacing if that helps?

**Comment by brettgaylor** [comment]
Thanks for the notes!  Implementing.

@hannahkane one of the things i was trying to do in the copy editing of these was remove stuff that felt superflous - so I think when we can, we should avoid saying "you're about to get a tip", and instead, give them the tip!

Having said that @natalieworth I wonder if the "all is not lost" card in this one could be in the same format as the others, so that we re-inforce the solution part of the system you've designed?

**Comment by brettgaylor** [comment]
@natalieworth sent you updated premiere project via DM
