### ISSUE TITLE
Callout box for India AADHAAR email 

### ISSUE THREAD

**Issue by WillatMozFdn** [MozillaFoundation/Advocacy#912]
Detailed description of work: We need a square-shaped graphic to put in our India anti-AADHAAR email (launching EOD tomorrow).  One of the existing social graphics can be re-purposed for this, but we need to either a) remove Mitchell Baker's name & position OR b) add the co-author's name and position (Ankit Gadgil, Mozilla community member.)  I suspect the former will look better/less cluttered.  Following up with an email....

*Start date: May 30, 2017* 
*Due date: May 31, 2016* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @natalieworth

**Comment by natalieworth** [comment]
![aadhaar-callout 2x](https://cloud.githubusercontent.com/assets/14876567/26607416/408639c2-454b-11e7-87a0-16d6d0ad4e95.jpg)
posting here for reference @WillatMozFdn

**Comment by hannahkane** [comment]
@WillatMozFdn - are we good to close this ticket?
