### ISSUE TITLE
Safety First Build Design QA:

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Advocacy#913]
The build is looking so good!
Just some small nit-picky design QA:

- [ ]  height of .poster-item in the comps is around 300px, currently in the build it is around 228px

![screen shot 2017-06-01 at 10 33 10 am](https://cloud.githubusercontent.com/assets/20977376/26684718/d009b11c-46b5-11e7-902d-abc88487958c.png)

- [ ]  padding of .gallery-item should be 17px, currently is 18px

CC: @hannahkane

**Comment by ScottDowne** [comment]
@beccaklam I just define the image width, the height is implied via the aspect ratio. A new image shouldn't have this issue.

**Comment by ScottDowne** [comment]
@beccaklam I'm updating the padding on `gallery-item` from 18px to 0.77rem, which is 16.9333px, does that work?

**Comment by beccaklam** [comment]
@ScottDowne sounds good on both accounts!
