### ISSUE TITLE
Changes to modal

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#914]
- [x] Add an X
- [x] Make it so that if you click outside the modal, it dismisses it
- [x] Add a thank you state, with this copy: "Thanks!

If you haven’t previously confirmed a subscription to a Mozilla-related newsletter you may have to do so. Please check your inbox or your spam filter for an email from us."

**Comment by ScottDowne** [comment]
I added the copy, but @beccaklam is doing some design work on it, and once that's done, I'll close this ticket.

**Comment by beccaklam** [comment]
@hannahkane @natalieworth do you have a preference for colour?
<img width="641" alt="thank you modal black 2x" src="https://cloud.githubusercontent.com/assets/20977376/26695110/a0217b66-46d7-11e7-8f48-0bb555f7715f.png">
<img width="641" alt="thank you modal 2x" src="https://cloud.githubusercontent.com/assets/20977376/26695111/a0253288-46d7-11e7-9928-159b9edf3f48.png">

**Comment by hannahkane** [comment]
Man, this is a lot of words. @HPaulJohnson - what do you think about: "Thanks! Please check your inbox or your spam filter for an email from us to confirm your subscription." ?

In terms of color, I have a slight preference for the white text, but I defer to you @beccaklam and @natalieworth.

**Comment by ScottDowne** [comment]
Modal done, using the white one for now.

We can cut down the words, in this ticket or another. I should probably be unassigned.

**Comment by hannahkane** [comment]
Closing and filing copy change as separate ticket.
