### ISSUE TITLE
Add copy for tips for each video on site

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#915]
For each video we need accompanying copy for the site:
- [ ] Video title
- [ ] Subtitle / Title for the Tips section (you'll be able to choose which words are highlighted)
- [ ] 1 or more tips, pulled from the video; can include links

**Comment by HPaulJohnson** [comment]
Copy for video titles, descriptions + tips here: 

https://docs.google.com/a/mozilla.com/document/d/14VQ2vvdxgnX0RvTIIiKoUMyB-sucuvBYnqdk1cpts7E/edit?usp=sharing

**Comment by hannahkane** [comment]
Assigning @ScottDowne to implement this copy

**Comment by ScottDowne** [comment]
I think we're done here. Any future requests or changes in copy can be iterated on.

Still needs posters and vids.
