### ISSUE TITLE
Remove "Is this information helpful?" section

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#917]
Discussed on a call today with @HPaulJohnson @ScottDowne and @beccaklam.

Decision is to remove this section for launch. We'll focus initially on learnings we can glean from:
 - site visits / marketing channels
 - page views
 - video completion rates
 - shares
 - subscriptions

 Will file a separate ticket to think through methods of soliciting meaningful feedback from users, as an upcoming iteration.

**Comment by ScottDowne** [comment]
Removed.
