### ISSUE TITLE
Figure out how to solicit meaningful feedback from users about Safety First videos

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#918]
Perhaps the first thing to clarify is what we hope to learn from feedback. For example:
- what topics are useful/interesting to people
- what level is useful (e.g. intro stuff vs more advanced knowledge)
- what style of video is most compelling
- what topics people would like us to cover
- what meaningful actions people take as a result of watching these videos

Depending on what we want to learn, we can design the appropriate feedback mechanisms.

Mechanisms we've discussed for collecting feedback:
- Was this helpful? yes/no
- Was this helpful? yes/no w/ opportunity to include details
- Star rating
- Upvote/downvote

@vojtechmzl @HPaulJohnson @lovegushwa  - is this something you three might collaborate on?

**Comment by beccaklam** [comment]
**Proposal for order of learning along with mechanisms for feedback (rough)**
1. What topics are useful/interesting to people (like/dislike, upvote/downvote <-- this may be more niche)

2. What style of video is most compelling (like/dislike? are we planning on doing drastically different styles? Is this something we really want to tailor to user's preferences? Seems a bit odd, does anyone else do this?) 

3. What meaningful actions people take as a result of watching these videos (not sure this counts as feedback but we should figure this out) 

4. What topics people would like us to cover (survey? feedback box?)

5. What level is useful (e.g. intro stuff vs more advanced knowledge) (survey? feedback box?)

**Comment by hannahkane** [comment]
Thanks, @beccaklam. You're right that the style of video isn't necessarily something we'd tailor to user preferences. It's really more about us identifying our target audience and creating content specifically for them. Maybe we should remove that from the list?

Meaningful actions might not be feedback in the "ask people for their feedback" sense of the word, but it is an additional source of data for us to use to inform our content (and potentially something we'd add to the TEI or meaningful actions target?).

Regarding your top priority (what topics are interesting)—I'm wondering what we'll learn from the combination of shares + feedback from other platforms (e.g. Facebook likes, Reddit upvotes), vs what additional signal we get from adding a "like" or upvote to the site itself. On those platforms, there's an incentive to interact, whereas on our site, there's not going to be an obvious reason to "like" something.

Curious what additional questions you and others ( @HPaulJohnson @lovegushwa ) have that aren't in the list above.

**Comment by beccaklam** [comment]
@hannahkane 
I agree with your point about learning about what topics people like via our social channels (Facebook, Twitter, Reddit). They already have systems set up for liking/up-voting set up so we may be better off using that data and focus on some of these other questions we have.

I think the meaningful actions should flow from the videos and be actions we can count towards the TEI. 

The last two questions, what topics people would like us to cover and what level of advice is useful, seem tied to issue #903. I agree with @roseregina and @stephaniemcv that we should make a form for this, perhaps one that pops up on the site? Or one that @brettgaylor and @lovegushwa were saying that could be incorporated into the videos? I think setting something like this up will be more meaningful for us than adding the like/dislike feature as we already have some means of getting that data.

**Comment by beccaklam** [comment]
<img width="1439" alt="screen shot 2017-06-14 at 3 34 00 pm" src="https://user-images.githubusercontent.com/20977376/27150902-ec520958-5116-11e7-9825-ecbc1ff8cc13.png">
example of feedback box

**Comment by brettgaylor** [comment]
What about something like this form, but where users can ask us to make a video, ie "What tips do you need to feel safe online? Got a tip you want to share?  Let us know!"

The trick there I suppose would be that we'd need a way to contact them, which would require opt in etc etc

**Comment by brettgaylor** [comment]
wonder if we could solve that by it being a simple mailto link?  Ie it prompts them to send us an email?

**Comment by lovegushwa** [comment]
I agree with @brettgaylor about "What tips do you need to feel safe online? Got a tip you want to share? Let us know!" ... @beccaklam has some nice ideas, many of them could be implemented with a survey. The "what style" question is something that we can test on social as we continue to refine the format.

Also I already designed a simple feedback UX asking if users found a set of tips helpful:

<img width="971" alt="screen shot 2017-06-14 at 6 51 30 pm" src="https://user-images.githubusercontent.com/12228435/27161807-a0552762-5132-11e7-8fe8-10eea0983d57.png">

**Comment by stephaniemcv** [comment]
@brettgaylor I think if you ask them to submit via email, really clear expectations need to be set around if they will or will not get a response. And if we're going to respond, do we have the staff resources for it? And then prep yourself for the conflation between submitting a tip and requesting one on one tech support.

@lovegushwa love this design. What is supposed to happen if you click no?

**Comment by lovegushwa** [comment]
@stephaniemcv TBD' but would probably fire a simple form or survey.

**Comment by HPaulJohnson** [comment]
will revisit pending plans to continue using safety tips in 2017. closing for now.
