### ISSUE TITLE
Create user stories for EU Copyright petition site

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#92]
Is it possible to generate user stories so that we're clear about what functionality is required for the Petition site? I think this would be helpful for @ScottDowne 

Short notice, but ideally we would have this for Thursday this week. Let me know if this information exists already. 

CC @valianttry @shaghdoosti

**Comment by valianttry** [comment]
I'm going to work on drafting this tomorrow (WED) and will ask @shaghdoosti to weigh in. Then i'll share for more feedback from the media team including @brettgaylor . (I already have some of these user journeys across a few documents... just need to pull it all together.)

**Comment by valianttry** [comment]
Started here: https://docs.google.com/document/d/1Pz4cTK0_Nauo1I1bBubzEr4Gs8RlolMwbm2eeTpqD-Y/edit#

NOT COMPLETED (DRAFT)

**Comment by lovegushwa** [comment]
@lovegushwa (following this ticket)

**Comment by valianttry** [comment]
@natalieworth and @ScottDowne already added some thoughts to this user story doc, any others to add? @shaghdoosti is on it....

**Comment by damiankay** [comment]
Does anyone have additional comments on the User Stories document that Andrea created, or can I close this? 

We're into wireframing and design, so please add comments by July 27 if you have any. 

CC @shaghdoosti @brettgaylor @lovegushwa

**Comment by brettgaylor** [comment]
I only added one to see if we need coverage of watching video.  Really like the user story approach here.

**Comment by a-kilroy** [comment]
Can someone give me access to this doc?

**Comment by damiankay** [comment]
You should have access now @a-kilroy

**Comment by valianttry** [comment]
I believe this is finished... but anyone can re-open if they believe that not to be true.
