### ISSUE TITLE
Consider different Share flow for SafetyFirst videos

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#920]
Per #916, the initial flow for ShareProgress will be for users to share the homepage. Rationale here is that homepage will have a better subscription rate due to the auto-modal.

Downside is it dis-incentivizes users sharing multiple videos.

Should we consider a later iteration that lets users share a particular video, and solve for the potential loss of subscriptions in another way?

**Comment by HPaulJohnson** [comment]
closing. we will revisit safety first as a whole when we consider 2018 plans / roadmap
