### ISSUE TITLE
Shorten copy on Thank You modal

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#921]
@HPaulJohnson - what do you think about: "Thanks! Please check your inbox or your spam filter for an email from us to confirm your subscription." ?

Current version:

<img width="641" alt="thank you modal 2x" src="https://cloud.githubusercontent.com/assets/20977376/26695111/a0253288-46d7-11e7-9928-159b9edf3f48.png">

**Comment by HPaulJohnson** [comment]
Shortened copy here: 

https://docs.google.com/a/mozilla.com/document/d/14VQ2vvdxgnX0RvTIIiKoUMyB-sucuvBYnqdk1cpts7E/edit?usp=sharing

**Comment by ScottDowne** [comment]
This was done in a generic copy pass.
