### ISSUE TITLE
Create transcript for wifi video

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#922]
Provide a transcript of the interviews with Georgia + Harlo

**Comment by hannahkane** [comment]
@brettgaylor - is this done?

**Comment by brettgaylor** [comment]
The transcript is, but the videos haven't been put on facebook yet.

**Comment by brettgaylor** [comment]
oops I actually created another ticket for both videos, so we can close this one
https://github.com/MozillaFoundation/Advocacy/issues/936
