### ISSUE TITLE
Promotion plan for Safety First videos

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#923]
Social, paid?, what's the plan?

**Comment by HPaulJohnson** [comment]
Plan here: https://docs.google.com/document/d/1EbuobB6LhVqV3KUrrcrqYQ4etHBypPTcZ6w3jKk6Wg4/edit

We are going to spread this over 6 weeks with 1 featured vid per week with 3-5 supporting assets per video. We'll do some testing with the first few episodes and adjust approach with the remaining beats. Hoping to have 3-4 weeks worth in the can ahead of all-hands.

**Comment by hannahkane** [comment]
Closing this ticket, since the plan is done! Separate tickets filed for creating assets for each video.

Are there any other tickets that need to be filed?

**Comment by HPaulJohnson** [comment]
In addition to design assets (vids, clips and stills) we'll need copy for FB, twitter and instagram to start. Also, snippet. 

We also can/should explore formats for other platforms as well (reddit, pinterest, etc).
