### ISSUE TITLE
QA SafetyFirst website

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#924]
Staging server: https://advocacy-mozilla-org-staging.herokuapp.com/en-US/safety/

Environments to test:
 - [x] Mobile FF, Chrome, Safari
 - [x] Desktop FF, Chrome, Safari, IE/Edge

Things to test:
- [x] Video playback
- [x] Share
- [ ] Subscribe
- [x] Modal behavior
- [x] Copy (typos, stuff that's too long, stuff that reads weird)
- [x] Footer links
- [x] Navigation (e.g. getting from video to video)

**Comment by hannahkane** [comment]
@ScottDowne @beccaklam - anything to add to the above list?

**Comment by beccaklam** [comment]
Looks good to me! Maybe just Navigation? As in if it's easy for a user to navigate from video to video. Maybe we can get someone who hasn't seen the site before to test this.

**Comment by hannahkane** [comment]
@beccaklam - thanks! Added nav to the list.

I'll ask someone from the Network site team to help QA. Building bridges!

**Comment by hannahkane** [comment]
@ScottDowne - can you confirm that the subscription works on prod? If so, then I think we can close this ticket.

**Comment by ScottDowne** [comment]
Yup, it's working.
