### ISSUE TITLE
QA > background color - title of the page

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Advocacy#925]
**Issue:**
I find it is challenging to read the word "Safety" mainly because the background color (blue) is very bright and it doesn't contrast with the yellow. That could be potentially challenging for the audience to read as well.

<img width="985" alt="image" src="https://user-images.githubusercontent.com/22157921/26853421-c3a44c9c-4ac6-11e7-836e-ed36e7d6ce10.png">

**Comment by lovegushwa** [comment]
I know this is a little on the wild side but it's part of the fun, I want to keep it as is.
