### ISSUE TITLE
QA > Subscribe user flow 

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Advocacy#926]
**Issue**
Some seconds after the user land on the page they see the pop up to subscribe (1). After they give Mozilla their email and hit "Yes I got it" (2) they see the "subscribe" button still highlighted. In case they click on the button (3) they see the pop up (2) again because they already subscribed.
<img width="433" alt="image" src="https://user-images.githubusercontent.com/22157921/26853981-1114da58-4ac9-11e7-8235-62816ef03069.png">

**Potential Fix**
I was wondering if the "Subscribe" button could be toned down a bit once the users already subscribed? To remove this distraction from the interface so users can focus on content - which is very interesting, by the way :).

**Comment by hannahkane** [comment]
Closing this ticket as a won'tfix, but will consider filing a new ticket if we do a email promotion (blocking the modal from popping up for people who are arriving via email)
