### ISSUE TITLE
QA > Share this Page link

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Advocacy#927]
**Issue**
When I click on "Share This Page" in the footer, the page scrolls up and the pop up banner is displayed. The label "Share this Page" sets the expectation of having a link or another way to share this page with people.

![share-this-page](https://user-images.githubusercontent.com/22157921/26854325-8361f31a-4aca-11e7-9b36-254712a18511.gif)

**Comment by hannahkane** [comment]
Closing this as Share hasn't been implemented yet. Sorry, @taisdesouzalessa, I forgot to tell you this!
