### ISSUE TITLE
QA > Play Button

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Advocacy#928]
**Issue**
I find it adds a little friction for the users the fact that they have to click twice the play button to see the video. I would expect the video to play automatically once I hit "play" once. That could be as designed (I don't have the full context of this page) so please disregard this QA ticket if that was intentional.

![play-behaviour](https://user-images.githubusercontent.com/22157921/26854599-bf183efe-4acb-11e7-9a3e-e8821ca899e3.gif)

**Comment by ScottDowne** [comment]
I was sorting out an issue around mobile auto playing (for bandwidth reasons) before I was comfy with implementing this.

It should now auto play only when a play button has been hit, but not on initial load of a clip if on mobile.
