### ISSUE TITLE
QA > mobile: button labels

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Advocacy#929]
**Issue:**
The buttons are all caps on desktop but lowercase on mobile (tested on Safari and Firefox - iPhone7).

<img width="437" alt="image" src="https://user-images.githubusercontent.com/22157921/26854720-41f1e672-4acc-11e7-8433-2cf5c76f3e99.png">

**Comment by ScottDowne** [comment]
Fixed.
