### ISSUE TITLE
QA > mobile: pop up checkbox tappable area

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Advocacy#930]
**Issue**
The tappable area of the pop up checkbox is too close to the "privacy notice" link. When tapping one, the other can be activated by accident. Screenshot: iPhone 7, Safari

<img width="385" alt="image" src="https://user-images.githubusercontent.com/22157921/26854955-61e93772-4acd-11e7-9388-52c4ded5d2af.png">

**Potential Fix**
Maybe aligning "Privacy Notice" with "I am ok..." ? Apple recommends at least 44pt X 44pt as minimum tappable area, which means the elements can be smaller but the tappable area shouldn't.

**Comment by lovegushwa** [comment]
@taisdesouzalessa @ScottDowne works as designed in chrome, could be a safari issue

**Comment by ScottDowne** [comment]
I'm not seeing this on an iphone 7.

**Comment by taisdesouzalessa** [comment]
Just checked it now and it is working as designed in Safari as well...for some reason it didn't yesterday. Very weird. Anyways, closing this issue :).
