### ISSUE TITLE
QA > mobile: footer links - tappable area

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Advocacy#931]
**Issue:**
On mobile the footer links are very close to each other, making is difficult to tap in an individual link.
Screenshot: iPhone 7, Safari
<img width="375" alt="image" src="https://user-images.githubusercontent.com/22157921/26855169-5debee8e-4ace-11e7-92aa-89c731a126f6.png">

**Comment by HPaulJohnson** [comment]
closing / won't fix
