### ISSUE TITLE
QA > mobile: tappable social media buttons

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Advocacy#932]
**Issue:**
Social media buttons are very close to each other making it particularly challenging to tap the Twitter button on mobile. Screenshot: iPhone7, Safari

<img width="396" alt="image" src="https://user-images.githubusercontent.com/22157921/26855325-15fd9fe0-4acf-11e7-90a9-b108da2869e7.png">

**Comment by ScottDowne** [comment]
I can increase the space between and or size pretty easily. That's my vote.

**Comment by lovegushwa** [comment]
@ScottDowne I noticed this as well. I'm ok with either solution, can you ping me when your working on this so I can see a preview in Vidyo and we can make a decision together?
