### ISSUE TITLE
QA > mobile: top nav consistency

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/Advocacy#933]
**Issues:**
1. In the home page (1) the word "first" seems squished there. 
2. In the internal pages (2), the sentence "safety first" is cropped.
3. The differences from above make the top nav inconsistent. You can see a difference happening in height as well.
<img width="487" alt="image" src="https://user-images.githubusercontent.com/22157921/26855578-bec2da86-4ad0-11e7-9f9c-70605366fb6e.png">

**Comment by ScottDowne** [comment]
2 and 3 look like a bug to me (and look like the same issue). I'll take a look.

**Comment by lovegushwa** [comment]
@taisdesouzalessa @ScottDowne good catch, let fix this.

**Comment by ScottDowne** [comment]
Grumble grumble Safari.

2 and 3 should be fixed. 1 is intended.

**Comment by ScottDowne** [comment]
I forgot to actually merge this.

It's merging now.
