### ISSUE TITLE
Finalize design for 2FA video

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#934]
As discussed in the slacks:
1) fix the type - its a bit all over the place

2) put the interviews into same skype interface as password manager video - maybe different colour?

3) Anything you can do when harlo is explaining the text message with a code - and she also explains that sometimes 2FA happens with an app so something super simple like a phone getting a message, and then perhaps something that likes like the Duo app we use on our phones for Mozilla’s 2FA

Premiere project file is here (I've been having issues with team projects):

**Comment by brettgaylor** [comment]
Oops had the wrong link in there
https://adobe.ly/2sF7fkC

**Comment by natalieworth** [comment]
https://drive.google.com/file/d/0B20-0lpP23c0UmUzRDdmUmk2UG8/view
