### ISSUE TITLE
Upload transcripts to facebook for 2FA + password manager videos

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#936]
Hey Natalie - if you could take care of how this is done, I've made a transcript:

password manager video:

georgia;
My Skype account was spamming a bunch of other accounts…my Skype account was hacked.

Embarrased, confused, and then really worried that someone else was going to click on something from me!

My password wasn’t secure enough and so someone had built a program that was logging into not-secure-enough accounts and then spamming.”

Harlo
Hackers do know that its totally possible to take that one password, see where you’ve re-used it, and then get access to those accounts as well.  And that’s where the bigger danger happens.

Georgia
You know, its hard to keep track of how many accounts you have, or how many apps you’ve installed, let alone what your passwords to all of them are.  Again, that’s the nice thing about a password manager: they do a lot of that for you. They can pick more secure passwords and make sure you are not a vulnerability yourself in knowing your password to something.

Two Factor Authentication video:
Amira
“one thing I recommend to people when I run workshops is I encourage them to use two-factor authentication when logging into sites

so if you have one layer of security, it might be easy to crack those accounts. But two factor authentication allows you to have multiple layers that will make it much harder to crack those accounts”

Harlo
..and what that means is that its based off something that you know, which is your password, and something that you have, which is usually your phone - physical possession of your phone.  

You might get a code that comes in via a text message, or better yet an app that you have on your phone.

In the event that you as a human being give an attacker your password - because they don't have that 2nd factor, there is very little else they can do with it.

**Comment by natalieworth** [comment]
Hey @brettgaylor , I talked to Alex and he gave some tips for uploading this to facebook and said he could help out if needed. Wondering though if we should wait until we upload the revised legal changed versions so we don't have to re-do it?

**Comment by brettgaylor** [comment]
agree!

**Comment by hannahkane** [comment]
hey @natalieworth and @brettgaylor - can we close this ticket?

**Comment by hannahkane** [comment]
Closing, but please reopen if needed.
