### ISSUE TITLE
QA>use new mozilla favicon

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#937]
@ScottDowne replace old favicon with new one. The file was on https://mozilla.ninja/logosystem/ but they took them down. Can you pull it from mozilla.org?
<img width="63" alt="screen shot 2017-06-08 at 1 36 35 pm" src="https://user-images.githubusercontent.com/12228435/26994411-63d5a4de-4d1c-11e7-8348-d94b88ae0e2b.png">

**Comment by ScottDowne** [comment]
Building prod now.
