### ISSUE TITLE
QA>darker black for the "keeping you ..." headline

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#938]
@ScottDowne  Can you change the headline to 000000 ?

<img width="944" alt="screen shot 2017-06-09 at 9 15 38 am" src="https://user-images.githubusercontent.com/12228435/26994929-e84a0d3e-4d1e-11e7-85b5-e5c11507604d.png">

**Comment by ScottDowne** [comment]
Fixed
