### ISSUE TITLE
QA>button text should be upper case

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#939]
@ScottDowne the button text should be upper case, but is lower in Chrome and Safari but not FF.
<img width="1036" alt="screen shot 2017-06-09 at 9 52 16 am" src="https://user-images.githubusercontent.com/12228435/26995325-d269f158-4d20-11e7-961d-0cee086bab10.png">

**Comment by ScottDowne** [comment]
Should be fixed.
