### ISSUE TITLE
Share data sample with Andrew

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#94]
Hi @cadecairos - just checking to see if you were able to share a sample of the data from Blue State Digital for Andrew Morales to review. If not, could you please share as soon as possible? 

Thanks!

CC @valianttry

**Comment by damiankay** [comment]
Hey @stephaniemcv - do you have access to the data in BSD? Would you be able to extract a sample to share with Andrew?

**Comment by stephaniemcv** [comment]
Closing as samples were shared with Andrew and Chris
