### ISSUE TITLE
QA>change color surrounding video

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#940]
@ScottDowne ... when the video content is black it blends into the black background. Can we change the black background color to # 202428 and change the footer BG color to match?
<img width="1319" alt="screen shot 2017-06-09 at 9 17 18 am" src="https://user-images.githubusercontent.com/12228435/26995634-a0cb73f4-4d22-11e7-9fa1-8cafc5921950.png">

**Comment by ScottDowne** [comment]
Fixed.
