### ISSUE TITLE
QA>Next Tip image squished

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#941]
@ScottDowne the next tip image is a little squished. Aspect ratio should be 4:3

<img width="1179" alt="screen shot 2017-06-09 at 9 55 35 am" src="https://user-images.githubusercontent.com/12228435/26996821-f3dbbcd2-4d29-11e7-80a1-461ddeb9cc68.png">

**Comment by ScottDowne** [comment]
Should be fixed on prod soon. Just another relic from those pesky placeholder videos.
