### ISSUE TITLE
QA>90% scale for desktop

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#942]
@ScottDowne I'm regretting the scale on desktop a little. I think the site is nicer at 90% scale, especially on laptop screens. @beccaklam was saying changing the scale might be easy to do because of how you built this site. Without pulling your hair out and cursing my name, is this possible? 

<img width="1372" alt="screen shot 2017-06-09 at 6 55 34 pm" src="https://user-images.githubusercontent.com/12228435/26999066-ed579e32-4d45-11e7-93a1-126595a4a124.png">

(at 90%, less chunky and a little nicer on a laptop screen )
<img width="1372" alt="screen shot 2017-06-09 at 6 55 23 pm" src="https://user-images.githubusercontent.com/12228435/26999067-f1b31f38-4d45-11e7-832b-a995d422825a.png">

**Comment by ScottDowne** [comment]
Yup this can be pretty easily done because the site is in all rems.

**Comment by lovegushwa** [comment]
@ScottDowne I thought it was rads

**Comment by ScottDowne** [comment]
@lovegushwa I think we should do this one over vidyo until it's how you like it.

**Comment by lovegushwa** [comment]
Happy with where are are on desktop now. Thanks Scott!
