### ISSUE TITLE
QA>accounting for youtube video play size / aspect ratio

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#943]
@ScottDowne @beccaklam youtube squeezes our 4:3 video into a 16:9 shape (aka pillar box). While the poster image is a decent size, the actual video play area is small once the video gets going. Can we try scaling  up the size of the video so when it plays back it's not so small on the page? ... We could get on a call and do this together. 

<img width="1528" alt="screen shot 2017-06-09 at 9 15 00 am" src="https://user-images.githubusercontent.com/12228435/26999134-763d545c-4d47-11e7-8ada-b6bcab12fe92.png">

<img width="1528" alt="screen shot 2017-06-09 at 9 15 18 am" src="https://user-images.githubusercontent.com/12228435/26999124-2a8bd5ba-4d47-11e7-8133-894608686508.png">

**Comment by ScottDowne** [comment]
This might actually be a relic from the trailers I missed. I should be able
to fix.

**Comment by ScottDowne** [comment]
Fixed.
