### ISSUE TITLE
Password Manager video promotional assets (video #1)

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#944]
- [x] 30-second promo A
- [x] 30-second promo B
- [x] Still

**Comment by lovegushwa** [comment]
@natalieworth length can be up to 30 seconds but we should look at 5-15 second clips as well

**Comment by natalieworth** [comment]
Still (drafts) image options are here: https://redpen.io/p/bu0ed5364f15552e1a

Rough teaser scripts are here: https://docs.google.com/a/mozilla.com/document/d/1kHIO7b3Dn8NEgjr4aMv6PHs6bjlgWvLWJ_TJPxtt9us/edit?usp=sharing

with the teaser videos here (super rough exports): https://drive.google.com/drive/folders/0B20-0lpP23c0UnNtN19iLUlnUUE?usp=sharing

cc @HPaulJohnson @lovegushwa @brettgaylor @caltrider 
 🤘

**Comment by brettgaylor** [comment]
This seem awesome to me!  My only comment would be to fade music up at beginning and out at the end.

**Comment by natalieworth** [comment]
Final teaser videos for this are here: https://drive.google.com/drive/folders/0B20-0lpP23c0cjlzNmpSdVZMV3c
