### ISSUE TITLE
Ransomware video promotional assets (video #3)

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#946]
- [ ] 30-second promo A
- [ ] 30-second promo B
- [ ] Still

**Comment by natalieworth** [comment]
Still have to add the video promo—but have started adding static images in here https://drive.google.com/drive/folders/0B20-0lpP23c0X2I0LTdrZ1VlZDg?usp=sharing

**Comment by natalieworth** [comment]
@HPaulJohnson I have some different social options in here:https://drive.google.com/a/mozilla.com/file/d/0B20-0lpP23c0aW9GZFNuU0FsdlU/view?usp=sharing
There's 1 poster image, 1 teaser, and then I also threw in a 'meme-like' one of the Fry meme we feature in the video. I also created some Instagram specific ones based on some research (although we're not really selling a product other than free knowledge/ education :) — so I'm not sure if the conversion for them will be the same). For the instagram options though, I included a 'meme' themed option (with white space), one that shows the actual 'product' (or where people will be going to if they click the link), and a carousel option of 4 images that people can swipe through.
cc @lovegushwa @beccaklam if you want to take a look! Struggling with the instagram options

**Comment by natalieworth** [comment]
Oh! Does this make sense too? If you have something wittier I can make it. I was going off of this though: @HPaulJohnson @lovegushwa @beccaklam 
![ransomware-screen](https://user-images.githubusercontent.com/14876567/28144905-3150f1c8-6723-11e7-8dbc-87e9ebabd0c6.jpg)

<img width="483" alt="screen shot 2017-07-12 at 4 58 11 pm" src="https://user-images.githubusercontent.com/14876567/28144935-59b615c6-6723-11e7-9856-207b6ed83a5d.png">

**Comment by HPaulJohnson** [comment]
@natalieworth I think these are great. trying a meme and a carousel approach for instagram is a solid test to give us a directional sense of how different that content might need to be. 

I'm going to put attach some copy to each of these assets and get them into the paid media mix early next week. I think we are good to go for video #3.

**Comment by hannahkane** [comment]
@can we close this one?
