### ISSUE TITLE
Encryption video promotional assets (video #4)

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#947]
- [ ] 30-second promo A
- [ ] 30-second promo B
- [ ] Still

**Comment by hannahkane** [comment]
My understanding is we're holding off on this, as well as 5 and 6. Is that right, @HPaulJohnson? If so, I'll remove from the "pre work week" milestone.

**Comment by HPaulJohnson** [comment]
Yep. Let's finish with the assets we have in the can. Focus of this site in next phase will be: 

- Test using it as an evergreen call to action in a rapid response social campaign around privacy or security. 
- Evaluate optimizations to make to the UX to increase email capture conversion rate
- Evaluate how/where it can be integrated into the larger Safety campaign this Fall.

**Comment by HPaulJohnson** [comment]
also should add that we will be pushing traffic to the site next week via snippet to get another big sample of performance data.

**Comment by hannahkane** [comment]
OK, removing from "Pre work week" milestone

**Comment by natalieworth** [comment]
Wondering if we can close these @hannahkane ? Are we still promoting this?

**Comment by hannahkane** [comment]
Good call. :)
