### ISSUE TITLE
Create EU Copyright campaign creative brief

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#95]
Brett and Paul - I know you're already working on this, but wanted to document it in Github. 

Assuming this will cover goals, KPIs, audience segmentation, messaging, and more. 

We'll share with Policy to make sure that it fits with their approach. 

Draft 1 due July 13

**Comment by brettgaylor** [comment]
This is completed and approved

**Comment by damiankay** [comment]
Hey @brettgaylor - as per our conversation on the Heartbeat call today, can you link to the brief here? Thx!
