### ISSUE TITLE
Re-output videos for legal changes

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/Advocacy#950]
After review, we'll need to make changes to each video.

Passwords:
-remove giphy attribution

Ransomware:
-remove giphy attribution

Encryption:
-remove giphy attribution

Router:
-remove giphy attribution
-change survey slide to say "60% of surveyed people own 4+ devices"
-blur the cisco logo on the Atlantic article that shows a router

Wifi:
-remove giphy attribution

2FA:
-remove giphy attribution

**Comment by brettgaylor** [comment]
@natalieworth maybe hold off for a bit on these, jordan and i are just discussing with Mika re: other opportunities for attribution

**Comment by lovegushwa** [comment]
@natalieworth we met with Mika ... so plan is to go ahead and remove the .giphy attributions. Let's connect and fix the em dashes, punctuation while were at it.

**Comment by natalieworth** [comment]
@HPaulJohnson @brettgaylor I have the updated 6 video files here:
https://drive.google.com/drive/folders/0B20-0lpP23c0bWtTQnplS2lhWFk

If Youtube/ Facebook allows, there is also the Closed Captions that we'll have to add to the 2 interview videos (Videos 01 and 06). Transcript for those are here: https://github.com/MozillaFoundation/Advocacy/issues/936

Alex said he could help with it if it's difficult (as I haven't done it before).

**Comment by brettgaylor** [comment]
Hey @natalieworth looks like you missed the comments about the wifi router video:

-change survey slide to say "60% of surveyed people own 4+ devices"
-blur the cisco logo on the Atlantic article that shows a router

Lets fix those up before uploading that one.

**Comment by natalieworth** [comment]
@brettgaylor Yes! sry missed those! Just reuploaded the Video 05 if you want to check it out

**Comment by brettgaylor** [comment]
Works for me!

@HPaulJohnson since it looks like we need to update the URLs instead of just swapping the video, guess we should file seperate bugs for that and I can update upworthy manually.

**Comment by natalieworth** [comment]
these are good to go, so closing this tic
