### ISSUE TITLE
Net Neutrality: Summer of Social + Snippet

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/Advocacy#951]
We intend to keep a steady stream of Net Neutrality content in our social and snippet channels throughout the Summer. The goal is to maximize the number of comments submitted to the FCC by the end of the public comment period in early August. 

cc: @lovegushwa @natalieworth @levjoy

**Comment by HPaulJohnson** [comment]
Plan here: https://docs.google.com/document/d/1w_PhodZIvcD63lwWCdx34Fh7vYIeXdnNOk1wTpFfxyU/edit#

**Comment by HPaulJohnson** [comment]
[Doc](https://docs.google.com/document/d/1w_PhodZIvcD63lwWCdx34Fh7vYIeXdnNOk1wTpFfxyU/edit) updated with latest social assets for poll data and geo test. 

Snippet for day of action redpens here: https://redpen.io/sr9540d6796d833891

@beccaklam can you update the copy under the search box to read: 

> Today is the Internet-wide day of action to save net neutrality. You can help by leaving a comment to tell the FCC why net neutrality must be protected. 

Paid media plan for day of action promo (7/10-7/13) here: https://docs.google.com/document/d/1w_PhodZIvcD63lwWCdx34Fh7vYIeXdnNOk1wTpFfxyU/edit

**Comment by beccaklam** [comment]
@HPaulJohnson I updated the comps to have the new copy under the search box: 
https://redpen.io/p/jo88274f721407dbf3

**Comment by hannahkane** [comment]
@HPaulJohnson - are we good to close this ticket? Maybe we could file specific tickets for social assets needed.

**Comment by HPaulJohnson** [comment]
We can close. Phases 1 & 2 of Summer of Social are complete and we are wrapping up all the assets for next phase and can ticket additional work separately. To recap what's left to wrap and what will be available to use in Jul-Aug: 

- Geo-targeted social (for paid)
- Typeoutloud Poster project
- Something we can all agree on video series
