### ISSUE TITLE
QA>subhead in black rectangle not vertically centered 

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#953]
@ScottDowne can you fix this? 
<img width="875" alt="screen shot 2017-06-13 at 8 30 42 pm" src="https://user-images.githubusercontent.com/12228435/27114275-4c3ede72-5077-11e7-8b49-6935ca63a560.png">

**Comment by ScottDowne** [comment]
I see this: https://pageshot.net/XUa8lKf4SwSZgtVc/06cff24b.ngrok.io

And, while I think I could tweak it a few pixels maybe, I most likely won't actually be fixing what you see. You're seeing something that's pretty extreme in the not centered category.

What's the OS Browser combination you used for that?

**Comment by lovegushwa** [comment]
@ScottDowne weird bug, looks good in FF OS. Bug is in chrome, I'm running android 7.1.2

**Comment by ScottDowne** [comment]
I put the new one next to the old one, for comparison.

https://pageshot.net/yxxza0zCTXZddzaf/www.browserstack.com

Shipping the left one.

**Comment by lovegushwa** [comment]
perfect
