### ISSUE TITLE
QA>Increase the size of body copy on mobile

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#954]
Hey @ScottDowne the body copy is a little small on mobile to view comfortably. Can you increase it by 3-5% ... We can sit and do this together if easier 

<img width="531" alt="screen shot 2017-06-13 at 8 36 16 pm" src="https://user-images.githubusercontent.com/12228435/27114388-2b0e827e-5078-11e7-9a40-60816f58bb9a.png">

**Comment by ScottDowne** [comment]
I bumped it up a bit. We can keep this open and sit together and pump it up a bit more if needs be.

**Comment by ScottDowne** [comment]
We looked at it and now like it, closing.

**Comment by lovegushwa** [comment]
looks great
