### ISSUE TITLE
QA>tighten up line spacing on video titles

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#956]
@ScottDowne on desktop would like to tighten up the line spacing on video titles. 

1. Reduce the size of the play button 15-20%
2. Reduce the type 10-15% 
3. Make subhead type color # 9194b0

Let's work on this on vidyo together

<img width="956" alt="screen shot 2017-06-13 at 9 24 18 pm" src="https://user-images.githubusercontent.com/12228435/27115317-b7d4044e-507e-11e7-9fec-118b0ef0234f.png">

**Comment by ScottDowne** [comment]
Some of this is fixed, button size we're leaving as is. Closing.

**Comment by lovegushwa** [comment]
looking great now
