### ISSUE TITLE
QA>Replace 2FA poster

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/Advocacy#958]
https://github.com/MozillaFoundation/Advocacy/issues/new

@brettgaylor would like something a little better for this video. We need to replace the poster on the site and on youtube. Not sure if this is for @HPaulJohnson or @ScottDowne to do?

Replace this one:
![2fa old](https://user-images.githubusercontent.com/12228435/27208513-f6b8c6f4-51fa-11e7-800d-3a730b5655a0.jpg)

With this one:
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvWlBUX2ZoTEtGN0k/view?usp=sharing

![2fa](https://user-images.githubusercontent.com/12228435/27208529-04008c52-51fb-11e7-827a-4b41490719bd.jpg)

**Comment by ScottDowne** [comment]
I'm replacing the image on the site itself, I am guessing someone needs to update it in youtube too.

**Comment by lovegushwa** [comment]
@HPaulJohnson can you update the poster on youtube?

**Comment by ScottDowne** [comment]
New image is on prod now.

**Comment by HPaulJohnson** [comment]
updated on youtube

**Comment by brettgaylor** [comment]
![image](https://user-images.githubusercontent.com/345974/27238097-754e81ae-5280-11e7-84e5-7163f7d82575.png)

Great.  Think this looks better in the upworthy page
