### ISSUE TITLE
Build IOT survey

### ISSUE THREAD

**Issue by vojtechsedlak** [MozillaFoundation/Advocacy#959]
Just wanted to file this ticket to keep track of changes that need to be made to the survey, as well as any associated tasks, such as creating a new header or localization.

Outstanding items
- [X] replace header
- [x] update thank you page
- [x] export strings for localization
- [ ] QA

CC @caltrider @lovegushwa

**Comment by caltrider** [comment]
A few more items:
- [x] Snippet Copy Draft
- [x] Snippet Icon
- [x] Email Draft
- [x] Email Call Out Box
- [x] Blog Post Draft 
- [x] Blog Post Image
- [x] Social Copy
- [x] Social Image (if we don't just want to pull from blog post)

cc: @vojtechmzl @lovegushwa

**Comment by caltrider** [comment]
Link to the survey draft:  https://www.surveygizmo.com/s3/3643927/Mozilla-IOT-Survey-06-2017

**Comment by caltrider** [comment]
Thanks @beccaklam.  Here's the github ticket with the list of things needed.  And the link to the current survey with the old wrapper.  Holler if you have any questions.

**Comment by hannahkane** [comment]
Noting that this is scheduled for the week of the 24th, but is potentially moveable.

**Comment by beccaklam** [comment]
@caltrider Here is first draft of the header, let me know what you think:
https://redpen.io/qz9028ae606480c414 <-- redpen for comments
<img width="1300" alt="artboard 1 2x" src="https://user-images.githubusercontent.com/20977376/28230300-5574722c-68b4-11e7-989f-d3ce3f588819.png">
CC: @lovegushwa @hannahkane

**Comment by beccaklam** [comment]
Update to header image based on feedback from @caltrider 
https://redpen.io/qz9028ae606480c414 <-- redpen for comments
<img width="1300" alt="artboard 2 2x" src="https://user-images.githubusercontent.com/20977376/28275982-94b7d358-6ae3-11e7-92f6-ab0ee156c8b9.png">
CC: @lovegushwa @hannahkane

**Comment by beccaklam** [comment]
@caltrider @lovegushwa @hannahkane 
Header with title:
https://redpen.io/qz9028ae606480c414 <-- redpen for comments
<img width="1300" alt="artboard 4 2x" src="https://user-images.githubusercontent.com/20977376/28283739-b55ddba2-6afc-11e7-8b5f-4e9b9acc65aa.png">

**Comment by lovegushwa** [comment]
@beccaklam thank you, let's ship this!

**Comment by beccaklam** [comment]
**Second option:** Played around with the header image again this morning and I actually think this image is stronger for the survey. I feel like the above image is too heavy handed with the devices whereas the image below can pique the user's interest with the question of "what am i connected to?" @caltrider @lovegushwa @hannahkane Thoughts? We could save the devices for snippet or for the other assets.
<img width="1300" alt="artboard 6 2x" src="https://user-images.githubusercontent.com/20977376/28322872-41a47db6-6ba5-11e7-9821-528622a456e3.png">

**Comment by vojtechsedlak** [comment]
@caltrider @lovegushwa @beccaklam Just added the second option to the survey. I also changed the background to match the header. Let me know if I should swap in v1 header or if you'd like to see any further changes made. Thanks!

Here is the link: https://www.surveygizmo.com/s3/3643927/Mozilla-IOT-Survey-06-2017

**Comment by beccaklam** [comment]
Survey Assets here, includes Survey wrapper, snippet, social, email callout, and blog header:
@caltrider @lovegushwa @hannahkane 
https://redpen.io/p/hy7d91817ddaaa45bc <-- redpen for comments
**Survey header**
<img width="1300" alt="survey-wrapper-header" src="https://user-images.githubusercontent.com/20977376/28336672-ddf81814-6bd0-11e7-81f5-74e9dc85875a.png">
**Snippet Options**
<img width="41" alt="snippet-1" src="https://user-images.githubusercontent.com/20977376/28336682-e1dfbfd6-6bd0-11e7-9cda-a0263ca26d70.png">
<img width="40" alt="snippet-2" src="https://user-images.githubusercontent.com/20977376/28336683-e1e7e01c-6bd0-11e7-8dae-4bee0d0d6732.png">
**Social**
<img width="440" alt="social 2x" src="https://user-images.githubusercontent.com/20977376/28336692-ed91448a-6bd0-11e7-83d6-2dbd90f4381b.png">
**Email Callout**
<img width="600" alt="email-callout" src="https://user-images.githubusercontent.com/20977376/28336687-e72dc14a-6bd0-11e7-8473-374731517cc0.png">
**Blog Header**
<img width="1320" alt="blog-header 2x" src="https://user-images.githubusercontent.com/20977376/28336700-f4496d70-6bd0-11e7-8705-a4885b3d4509.png">

**Comment by hannahkane** [comment]
Looks great to me! @caltrider - if you're happy with these, can you check off the appropriate checkboxes above?

**Comment by caltrider** [comment]
Looks good to me. Checkboxes marked. @hannahkane @beccaklam

**Comment by TheoChevalier** [comment]
Unfortunately, I don’t think we can switch the survey wrapper based on the locale in Surveyguizmo, so it would be better not to include the title in English in the image, but rather move it in the survey page, if possible. Or otherwise we can try to integrate the translated titles alongside English, but I can’t tell if it’s something we would be okay with

**Comment by caltrider** [comment]
Good point @TheoChevalier. Just talked it through with @vojtechmzl and @beccaklam and we're going to take the title of "How Connected Are You?" out of the design header and Vojtech is going to add that in as a changeable title at the top of the survey

**Comment by beccaklam** [comment]
@vojtechmzl @caltrider @hannahkane Here is the updated header sans title:
<img width="1300" alt="survey-wrapper" src="https://user-images.githubusercontent.com/20977376/28430573-00887c64-6d4f-11e7-8919-169b5c81176d.png">

**Comment by TheoChevalier** [comment]
Quick l10n update on the ongoing translations:

Survey localization: https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=surveys/iot_survey.lang

Email localization: https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=emails/2017/iot_survey.lang

Snippets localization: https://l10n.mozilla-community.org/langchecker/?locale=all&website=6&file=snippets/2017/iot_survey.lang

**Comment by tlasadea** [comment]
@beccaklam @caltrider just bringing this back in 'To Do' because I think there's a few tiny creative additions? 

Re Slack group chat, was just double checking on social assets sizes:

Facebook - optimum image size is: 1024 x 512px.

**Comment by caltrider** [comment]
Also @tlasadea , did you want Rebecca to add the How Connected are You? text to any of the versions for social?

**Comment by tlasadea** [comment]
LOL talk about completely missing the point, Temi.

Yes can we have the text added to the social versions? I'm correct in
thinking that then there'll be different language ones?

**Comment by TheoChevalier** [comment]
> I'm correct in thinking that then there'll be different language ones?

Yes! For Twitter & Facebook: French, German, Spanish (International), Portuguese (Brazil)

“How Connected are You?” can be reused from here: https://l10n.mozilla-community.org/langchecker/?website=6&file=surveys/iot_survey.lang&action=translate&show#string2

**Comment by beccaklam** [comment]
@tlasadea & @caltrider Was working on this but then remembered something about social posts and words in the graphics. I did a quick survey of Facebook and Twitter and noticed that a lot of graphics are sans text as you can add titles in the text section of the post. Do we know if with text or without text images perform better in social? Did we still want to go ahead and add text to the images?

**Comment by tlasadea** [comment]
I don't know if we have any Mozilla insights from Alex on that. I know that
getting people to stop aka "pause the thumb" (while scrolling) means that
content on FB specifically has shifted to being easy to scan - so copy on
images would support that. Also - these posts won't be supported with any
paid spend, only the results will be...so for organic posts I'd hazard a
guess that any boost would be negligible.

*Temi Lasade-Anderson*
Social Media Specialist
Mozilla Foundation
Slack: tlasade | Twitter: @temilasade <http://www.twitter.com/temilasade>

**Comment by hannahkane** [comment]
Can this ticket be closed?

**Comment by TheoChevalier** [comment]
Yes!
