### ISSUE TITLE
Create EU Copyright campaign strategy brief

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#96]
Sara is putting this together with input from the Policy team. 

Due July 15

**Comment by valianttry** [comment]
@damiankay can we close this one?

**Comment by damiankay** [comment]
I'm not sure. @shaghdoosti would you say that the brief is complete and approved?

**Comment by shaghdoosti** [comment]
This is an evolving document - so wordsmithing is still happening but the top line (what we need to start work is done.) 

Link is here: https://docs.google.com/document/d/1NkHdwueX7MBUxRdanc7VlXuzv0mQqeLfL9V2P-yBOT0/edit
