### ISSUE TITLE
Test a pop up email capture on FCC comment page

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/Advocacy#960]
This would work like the popup on the/safety page and need to be testable.

There is copy that is needed, and I'll probably need to bug @beccaklam or someone to figure out how a popup in https://advocacy.mozilla.org/en-US/net-neutrality-comments/ would visually change from https://advocacy.mozilla.org/en-US/safety.

**Comment by ScottDowne** [comment]
There is an email thread with more info. I'm going to add as many of those people that I can find here, plus any more I feel are needed. Please update this ticket with required info.

@vojtechmzl @HPaulJohnson @hannahkane @beccaklam @lovegushwa

**Comment by beccaklam** [comment]
Potential signup modal:
![screen shot 2017-07-05 at 9 26 29 am](https://user-images.githubusercontent.com/20977376/27866372-10c4b95e-6164-11e7-85de-97628057f2a5.png)

**Comment by beccaklam** [comment]
@natalieworth Design feedback welcome! ^

**Comment by hannahkane** [comment]
UX question - if the user completes the email pop-up, do they still get the email checkbox when filling out the comment form?

**Comment by beccaklam** [comment]
@hannahkane They should not @ScottDowne

**Comment by hannahkane** [comment]
@HPaulJohnson - can you drop in copy if you have it, please?

**Comment by HPaulJohnson** [comment]
Main copy: 
Love the Web? Sign up for email updates and help us keep it open and free. 

Small print (w/ checkbox):
I'm ok with mozilla handling my info as explained in this privacy notice.

**Comment by beccaklam** [comment]
Design update: @ScottDowne 
![mockup](https://user-images.githubusercontent.com/20977376/27926754-7f522eee-6257-11e7-8440-a1ca3906c84f.png)

**Comment by beccaklam** [comment]
@ScottDowne Notes on colour, font size and line height if it helps:
![screen shot 2017-07-06 at 2 42 38 pm](https://user-images.githubusercontent.com/20977376/27927330-68372b36-6259-11e7-838f-07c40f25f1f4.png)

**Comment by ashleyboyd18** [comment]
So excited that this is moving forward!  Any updates on status?  We're launching social ads on Monday (Paul can clarify if I'm wrong) and I'd love to have this up on Monday or soon after to capture emails too.

**Comment by hannahkane** [comment]
We were focused on shipping the snippet this week, but were able to finalize the design for this so we can implement early next week.

**Comment by ashleyboyd18** [comment]
Hooray!  Thank you - and the snippet is amazing.

**Comment by ScottDowne** [comment]
Test can be setup now.

Test url is https://advocacy.mozilla.org/en-US/net-neutrality-comments/?test=signup-modal

@vojtechmzl ^^

**Comment by vojtechsedlak** [comment]
Thanks, Scott. I am trying to set up the test in Optimizely, but running into permission issues. Hopefully will hear back from MoCo by EOD so we can set the test up before tomorrow.

**Comment by ScottDowne** [comment]
@vojtechmzl this fell off my radar. Did everything end up happening? Can we close?

**Comment by vojtechsedlak** [comment]
Thanks for checking in, Scott. We ran the test and implemented the popup across the board, so good to close this ticket.
