### ISSUE TITLE
Select Ten Quotes for Net Neutrality Snippet

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/Advocacy#961]
Select ten quotes to rotate in the Net Neutrality snippet.
Selected from this [doc](https://docs.google.com/a/mozilla.com/spreadsheets/d/1G4_Bgt5msjvZUNzFhuzGlZf12XADOcn8Lj1a6pUVH1c/edit?usp=sharing):
*Some quotes have been shortened:

**Free Speech**

1. "Please leave the Internet open to one and all without limitations. Let the little guys keep their voice.” — Concerned Internet Citizen, Boxford MA

2. "Hands off the Internet. Free speech can only exist if the net remains neutral." 
— Concerned Internet Citizen, San Francisco CA

3. "I served to preserve freedom of the press and freedom of speech and that is what the internet is today!" — Concerned Internet Citizen, Aston PA

4. "Without Net Neutrality big companies could censor people and perspectives online."
— Concerned Internet Citizen, Malcom IA

**Innovation**

5. "Without Net Neutrality creators and entrepreneurs could struggle to reach new users." 
— Concerned Internet Citizen, Brooklyn, NY

6. "Without Net Neutrality creators will struggle to overcome the will of the large cable monopolies." 
— Concerned Internet Citizen, Longmont CO

7. "Please keep Net Neutrality. Small businesses and innovators need your protection. Please!"
— Concerned Internet Citizen, Highpoint NC

**User Choice**

8. "I prefer to choose what I see and not have someone else or some big company do it."
— Concerned Internet Citizen, Anchorage AK

9. "I want a fair choice for where I go online and not to be thwarted in my options by load times."
— Concerned Internet Citizen, Charles Town WV

10. "Net Neutrality allows consumers — not big companies — to choose what they do and watch online." — Concerned Internet Citizen, Lakeland FL

Redpen with quote mock ups: https://redpen.io/p/jo88274f721407dbf3

CC: @hannahkane @HPaulJohnson @ScottDowne

**Comment by HPaulJohnson** [comment]
looks good to me. shared with wes on snippet team to make sure he is ok with them. 

if we can't locate the specific quote jordan used for the original comp, we should remove that one.

**Comment by beccaklam** [comment]
@HPaulJohnson I found the quote, just changed the location from Arlington VA to Boxford MA to match the doc.

**Comment by beccaklam** [comment]
@ScottDowne ALSO: Copy under search bar (CTA) has been updated:

> Today is the Internet-wide day of action to save net neutrality. You can help by leaving a comment to [tell the FCC](https://advocacy.mozilla.org/en-US/net-neutrality-comments) why net neutrality must be protected.

**Comment by hannahkane** [comment]
@beccaklam - Can we close this ticket now?
