### ISSUE TITLE
Typeoutloud instance for Net Neutrality

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#964]
This ticket should encompass everything we need to do to set up a new typeoutloud instance. 
- [X] choose url (typeoutloud.org/net-neutrality)
  - [x] do we want query strings for the various channels like we've done in the past (i.e. to differentiate the instance for people who arrive via email) - NO
- [x] write copy (headline, prompt, pop-up, share progress)
  - [x] figure out what the CTA is - where are we sending people?
- [x] social images for share progress
- [X] choose color scheme
- [x] add metrics (is this a task, or does this come for free?)
- [x] resolve any bugs found in QA

**Comment by hannahkane** [comment]
@beccaklam @ScottDowne - these are the things I can think of to set up a new typeoutloud instance. What am I missing?

**Comment by beccaklam** [comment]
@hannahkane I think you got most of it, I just added social images to your list.

**Comment by lovegushwa** [comment]
@beccaklam @ScottDowne the copy for the new instance is "Without net neutrality ..."

**Comment by lovegushwa** [comment]
@HPaulJohnson a few notes for you: 
- can we repurpose social content we already have for share progress? we will need social copy.
- @beccaklam is going to take a crack at the popup copy and then run it by you.

**Comment by lovegushwa** [comment]
@hannahkane @HPaulJohnson for the url ... "/net-neutrality" ?

**Comment by beccaklam** [comment]
@lovegushwa Feedback on colour? Don't know if it's too similar to what we had for Internet Health but the choices were inspired by the Net Neutrality Comments page. Also the dark blue is more somber going along with the "without" theme:
<img width="1440" alt="screen shot 2017-07-14 at 10 05 46 am" src="https://user-images.githubusercontent.com/20977376/28215619-a2bc0096-687c-11e7-8ffd-aea95601a3cd.png">
@HPaulJohnson Feedback on copy:
Popup:
<img width="1440" alt="screen shot 2017-07-14 at 10 05 37 am" src="https://user-images.githubusercontent.com/20977376/28215707-e807f484-687c-11e7-8add-ae7e137704a8.png">
Abort page:
<img width="1440" alt="screen shot 2017-07-14 at 10 01 04 am" src="https://user-images.githubusercontent.com/20977376/28215713-eb8ecc7c-687c-11e7-8780-1d994ab90ffa.png">
CC: @hannahkane 
Still waiting on social copy and media for the share progress page.

**Comment by HPaulJohnson** [comment]
This is looking great @beccaklam. A few suggestions for the copy...

For the intro pop-up, some suggested edits

"What would the _be_ without Net Neutrality? Add your thoughts and we will turn some favorites into a set of Posters you can print out or share on social media. Follow us on Facebook, Twitter or Medium to see the final results!" 

For the post-submit pop-up: 

"Thank you for sharing your ideas! We'll be creating a set of posters from our favorites soon. Follow us on Facebook, Twitter or Medium to see the final results (and then print and share them)!"

(taking a look at the Share Progress piece next and will add thoughts in separate comment)

**Comment by lovegushwa** [comment]
Happy with this, ship it!

**Comment by hannahkane** [comment]
Just updated the list in the first comment. I believe we're still waiting on Share Progress copy. Are we good on metrics for this? @vojtechmzl - do you know of anything we need to do on this front?

I did a little QA on the staging server, and filed [one ticket](#974) that's definitely a blocker.

**Comment by vojtechsedlak** [comment]
GA seems to be firing off correctly, so all good on that front.

**Comment by HPaulJohnson** [comment]
Share Progress copy is done. 

NOTE: that when we figure the specific context we will be using this in - like "Go to a townhall in your community" - we may want to revisit the copy on both the popup and the share progress page to reinforce. 

For now, and without additional context, we are ready to ship this as is I believe.

**Comment by hannahkane** [comment]
QA passes, with the exception of the Medium link mentioned in #975. Once that's resolved, please push to production server.

**Comment by beccaklam** [comment]
Fixed the Medium link and pushed to prod, it should be up now: https://www.typeoutloud.org/net-neutrality

**Comment by hannahkane** [comment]
Awesome! I'm adding some content now, so it's not empty when we start directing traffic to it. Nice job, @beccaklam!

**Comment by HPaulJohnson** [comment]
@beccaklam one question re: Share Progress page. The wrapper is pretty old and has old Mozilla branding. Is there a more updated wrapper we can use instead and/or can we create one with the new branding?

**Comment by beccaklam** [comment]
@HPaulJohnson I updated the wrapper to something really basic with the new logo. Let me know if you want more pizzaz or anything else on it? http://share.mozilla.org/352/181993

**Comment by HPaulJohnson** [comment]
@beccaklam much better! The only thing we should add is a footer. That could either be the standard footer from our advocacy pages or something simpler that just has a single CTA back to the net neutrality page on advocacy.mozilla.org

**Comment by beccaklam** [comment]
@HPaulJohnson I added a simple CTA to the net neutrality comments page on advocacy.mozilla.org is that ok? http://share.mozilla.org/352/181993

**Comment by HPaulJohnson** [comment]
@beccaklam perfect. we can call this one done!

**Comment by beccaklam** [comment]
@HPaulJohnson Sweet!
