### ISSUE TITLE
NN typeoutloud promotional email

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#965]
In order to solicit NN comments to use for the posters, we'll need to promote the new typeoutloud instance (#964). Current plan is to send an email on Saturday, July 22nd.

**Comment by hannahkane** [comment]
@HPaulJohnson and @lovegushwa @beccaklam - who will be responsible for coming up with the plan, and who will be responsible for creating any necessary assets?

**Comment by hannahkane** [comment]
@HPaulJohnson @lovegushwa @WillatMozFdn - I started filling out the [email RASCI doc](https://docs.google.com/document/d/1hfQzc-y4QFq708G1HG6kqe63NSgBAcdzpAhXhIvkd8A/edit).

Who's the right person to draft the email?

**Comment by HPaulJohnson** [comment]
@WillatMozFdn is this something you could write? I'm not sure we have the capacity or person to do that at the moment.

**Comment by WillatMozFdn** [comment]
@HPaulJohnson Sure.  Pretty busy this week with fundraising stuff and picking up Rose's tasks, but I'll fit it in.  Do we have any more detail -- maybe just a few bullet points -- on what we want the central message of the email to say?  (That would help a lot.)

**Comment by HPaulJohnson** [comment]
The message of this is part of the continued Net Neutrality campaign so you all on the campaign team know as well as I do what the best message might be. Tagging @Melechuga to see if she has anything specific in mind. 

My understanding is that we are encouraging people to contribute sign ideas, we'll pick/design the best for posters and then people can come back and print/share them to take to their local townhalls during the August recess. For the overall CTA re: signs we should be able to copy what we did previously for science march in april; for the net neutrality message I look to you and Melissa for guidance on what our current, post-FCC position will be.

**Comment by hannahkane** [comment]
@HPaulJohnson @WillatMozFdn - Is there an update on this?

**Comment by Melechuga** [comment]
@hannahkane @HPaulJohnson @WillatMozFdn 
Josh and I are meeting about this tomorrow, and talking about this further with the larger team during our Thursday call. Will have more details on messaging for the posters and such then, which may help guide the email messaging. Thanks!

**Comment by hannahkane** [comment]
No longer part of plan.
