### ISSUE TITLE
Create Net Neutrality posters for congressional town halls

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#966]
The copy will come from the typeoutloud ( #964 ).

@HPaulJohnson - How many do we want?

@lovegushwa - thoughts about theme, look & feel?

@caltrider - you mentioned we might need poster-alternatives for those where the town hall organizers have banned posters. Something like cafepress t-shirts, right?

**Comment by lovegushwa** [comment]
@HPaulJohnson @caltrider @hannahkane @beccaklam @natalieworth  would be great if you could help decide how to move forward with the new typeoutloud poster prompt by the end of the day. Here are a few options for us to consider, I set these up just like how the madlib would appear/function on typeoutloud.org ... additional copy ideas in this [doc](https://docs.google.com/a/mozilla.com/document/d/1Tk7mkSWhasLQDlguyuk_LeytljB8gd9EeVs-kpR_N1E/edit?usp=sharing) feel free to add more ideas or surface a favorite in this ticket if your not happy with any of the options A-D.

<img width="1193" alt="screen shot 2017-07-12 at 11 34 29 am" src="https://user-images.githubusercontent.com/12228435/28133884-288ef6ca-66f6-11e7-8f60-6a9dac6fbb66.png">

**Comment by natalieworth** [comment]
My preference is either A or B. I like that A shows what we could loose without net neutrality (even if it feels negative—it stills feels pretty strong to me). I like B too though. It feels a bit lighter and almost 'cool/ hip' in the language and tone.

**Comment by hannahkane** [comment]
Did you nix the idea of the strikethrough? I actually quite liked that, though I think it might be clearer if the good thing was crossed out, rather than the bad thing - e.g. "<s>Freedom</s>" not "<s>Less freedom</s>". If we went with that model, the prompt might be something like, "If we lose net neutrality, we'd say goodbye to..."

(I also like that that version, along with "Defend Net Neutrality" clarifies that neutrality is the default.)

**Comment by lovegushwa** [comment]
@hannahkane no I didn't nix the strikethrough would still be how we make posters for option A. Just wanted to present these the way a user would see them on typeoutloud.org

**Comment by HPaulJohnson** [comment]
I think A is the most intuitive and will result in the strongest ideas/outputs. 

Thinking about this in the context of the other content we'll have in August, in particular the "something we can all agree on" videos, do any of these work better/worse as a complement to that part of the campaign? May not be relevant but just throwing it out as they will likely be in market around the same time.

**Comment by beccaklam** [comment]
I vote for option A! I think it's the clearest option still.

**Comment by lovegushwa** [comment]
@hannahkane @beccaklam looks like A. is the winner. We can move ahead with a new typeoutloud.org instance and start developing poster directions including the <s>strike through</s>

**Comment by hannahkane** [comment]
This is no longer part of the plan, so closing.
