### ISSUE TITLE
Promote net neutrality posters

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#967]
We'll need a plan to promote the net neutrality Town Hall posters ( #966 ) once we've created them.

Might include some combination of social, blog, and email.

**Comment by hannahkane** [comment]
@vojtechmzl @HPaulJohnson or @lovegushwa and @caltrider - what thoughts do you all have about how to best promote the net neutrality posters once we have them? I believe for the Science March we hosted them on imgur and linked to them from a blog post on Medium. Did that work well?

**Comment by caltrider** [comment]
@vojtechmzl @hannahkane @HPaulJohnson @lovegushwa The problem with Imgur was that it made FB and Twitter shares harder/not as effective.  I think we could do imgur for the blog/reddit, but maybe upload directly to to FB and Twitter to also have links to share on those platforms.

**Comment by hannahkane** [comment]
+1 to @caltrider's suggestion, though I can't remember if there was a reason we didn't do that with the Science posters.

As discussed on today's call - do we want to promote a specific hashtag along with the posters so we can potentially see photos of the posters in the wild?

**Comment by hannahkane** [comment]
No longer part of the plan, so closing.
