### ISSUE TITLE
Create EU Copyright campaign comms plan

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#97]
Kevin to create a comms plan with input from @HPaulJohnson @brettgaylor @valianttry @shaghdoosti @damiankay

**Comment by HPaulJohnson** [comment]
Current (draft) version of Comms Plan for Copyright EU here: 

https://docs.google.com/a/mozilla.com/document/d/1NAjP6VHh-2dsLjjnXoXg4CRcdObf7wHlkcDvRwUTMJM/edit?usp=sharing

**Comment by damiankay** [comment]
@KevZawacki @HPaulJohnson when will this need to be completed in order to have social and email assets ready in time for launch? 

Also, does this include our email comms planning (I.e. timing), or is that separate?

**Comment by HPaulJohnson** [comment]
@damiankay i created issue #154 to track marketing plan. The scope of Comms Plan is more just PR. 

This week, I'll add some detail to specific marketing assets needed for launch.

**Comment by damiankay** [comment]
Fantastic - thanks @HPaulJohnson

**Comment by KevZawacki** [comment]
Comms plan will continue to evolve as the campaign plays out, but we have a sound structure. Closing this ticket.
