### ISSUE TITLE
Update to Copyright Site

### ISSUE THREAD

**Issue by Melechuga** [MozillaFoundation/Advocacy#971]
Detailed description of work:

Proposed updates for the copyright site (changecopyright.org)
- integrate a call tool (Cade is demoing and reviewing in this ticket: https://github.com/MozillaFoundation/mofo-devops/issues/499#issuecomment-307403823)
- update landing page to be more useful: include timeline, changes in committees, events happening, links to relevant blogposts, etc.
- if possible, include twitter feed for #fixcopyright  
- sign-up can stay, but further down.
- update to resources site
- [Google Doc Here](https://docs.google.com/document/d/11R5oze6_1wl9CxpO25T6-N4NC8N2jdip-QU0TH8-A6Y/edit#bookmark=id.ed09qo3jhyi4)

Other sites for inspiration:
- https://juliareda.eu/eu-copyright-reform/
- https://medium.com/eu-copyright-reform

CC: @hannahkane

**Comment by hannahkane** [comment]
Awesome. Thanks, @Melechuga. Do you have a deadline? Do you have a content doc started? I'm wondering how much the content changes will affect the design and layout.

I'll see about finding people to work on this, perhaps from outside the Advocacy media team, since they are very occupied with the Net Neutrality campaign.

**Comment by Melechuga** [comment]
Getting Policy review this week; should have the content doc ready to go by next week!
Thanks again @hannahkane

**Comment by hannahkane** [comment]
Hey @Melechuga - I added a couple questions to the content doc. 

It looks like we're going to need not just engineering support (both front-end and back-end), but also design support. 

Can you clarify the timeline?

**Comment by TheoChevalier** [comment]
@Melechuga hey, do you mind sharing the content doc with me for a quick l10n sanity check?

**Comment by Melechuga** [comment]
@TheoChevalier [Here's the doc](https://docs.google.com/document/d/11R5oze6_1wl9CxpO25T6-N4NC8N2jdip-QU0TH8-A6Y/edit#bookmark=id.ed09qo3jhyi4)
Waiting for policy review.

**Comment by hannahkane** [comment]
OK, looking at the doc, I think this is going to require quite a bit of design work. It's a lot of content, and I don't think it will be as simple as switching out the content in the existing design.

We don't currently have any designers who aren't already booked on other projects, so we'll need to sync up with various others to problem-solve. I'll send an email.

**Comment by Melechuga** [comment]
@TheoChevalier 
I see that we localized this site into 23 different languages the first time; wow! I was hoping we could have a chat about prioritizing the languages for this next iteration. Would be great to get a sense of what you think is possible, and to line it up with the communities with which we're working closely. Sound ok?

**Comment by TheoChevalier** [comment]
@Melechuga Yup, we can totally make decisions based on the progress of a “Tier1” list of locales. We will need to communicate which locales are our Tier 1, then we can just expose the new content to all locales, and each team will catch up as they can, using this info to prioritize their work against other projects.
Once we have our tier1 locales completed, we can push the new content to production, and enable only the completed locales, the other ones will fall back to English until they are completed (we have the ability to enable them individually on production as soon as they are complete).
Was it what you had in mind? Happy to set up a quick call otherwise

**Comment by Melechuga** [comment]
@TheoChevalier 
Good to know we can control it so well! For this iteration of the copyright site, I'd like to prioritize 5 languages: French, German, Italian, Polish, and Spanish. No surprise that FR, DE, PL, ES are there, as our largest groups; I'm adding IT as they're a key community we're working with on the ground, and potentially having the website in Italian would help grow that subset. 

Does this sound realistic? The content has been reviewed and approved by Policy; what are the next steps?

**Comment by TheoChevalier** [comment]
@Melechuga Yup, the list makes sense.

Before we can start localizing, this needs to happen:
- Design works
- Building the new template, and potentially new page(s)

Then I can extract strings and expose them in Pontoon

**Comment by hannahkane** [comment]
@Melechuga - can you provide an overarching timeline for this? That will help with identifying design/dev staff for this.

**Comment by Melechuga** [comment]
Hi @hannahkane -- not totally sure what you mean, but I can try. The goal is to push engagement during the month of September, as there is a vote happening in early October. With this in mind, the timeline would look something like:
- Aug. 15: Soft launch of website, if possible
- Aug. 30: hard launch
- September 1 - Oct. 10: network/community engagement (calling, visiting site)
- Post Oct: review and revamp for Plenary vote, scheduled for Dec. 2017

**Comment by hannahkane** [comment]
Closing this ticket in lieu of separate implementation tickets
