### ISSUE TITLE
Snippet Icons for Safety First promo

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Advocacy#972]
Detailed description of work:
Create static and animated snippet icons for the Safety First promo on the Firefox snippet.

Start date: July 7, 2017
Due date: TBD (deliver with 3rd batch of social promotion)

Content here:
https://docs.google.com/document/d/1EbuobB6LhVqV3KUrrcrqYQ4etHBypPTcZ6w3jKk6Wg4/edit

**Comment by HPaulJohnson** [comment]
Thanks, @natalieworth! these look great and I've selected 3 options for possible testing: safety cone static, animated privacy heart and animated lock. 
 
These, along with the copy, have been sent to the snippet team: https://docs.google.com/document/d/1yxoYs-ksgRd-tRG3ZMqnNVN-U1_XnEivN9X88oTUmbU/edit

**Comment by hannahkane** [comment]
Can we close this?

**Comment by natalieworth** [comment]
Yep! Final files are here for reference https://drive.google.com/drive/folders/0B20-0lpP23c0NVlxOW9NWHIyTWc?usp=sharing
