### ISSUE TITLE
Add blurb explaining comment collection timeline to top of comment collection page

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#973]
Approved copy: "Keep commenting!  The FCC is continuing to take comments on net neutrality through August 16, though earlier comments were used in their first round of review."

cc @levjoy @HPaulJohnson

**Comment by hannahkane** [comment]
@beccaklam @HPaulJohnson - added approved copy from Ashley to the original comment.

@beccaklam - are you able to come up with a design for this, implement it, and push the changes, or do we need add'l help?

**Comment by HPaulJohnson** [comment]
thanks, @hannahkane - copy looks great to me.

**Comment by beccaklam** [comment]
I should be able to handle this! @hannahkane

**Comment by beccaklam** [comment]
@hannahkane just confirming, am I swapping out this current copy?

> Write your comment below to tell the FCC why net neutrality MUST be protected. We’ll deliver your comment straight to the agency.

**Comment by hannahkane** [comment]
Just checked with Ashely - she says the new sentence should go *after* the copy that's in that box now.

**Comment by beccaklam** [comment]
@hannahkane Like this?
![screen shot 2017-07-18 at 4 20 05 pm](https://user-images.githubusercontent.com/20977376/28337901-119453b4-6bd5-11e7-913b-ab2a23f0c5d9.png)

**Comment by ashleyboyd18** [comment]
Looks great - thank you!

**Comment by beccaklam** [comment]
This has been pushed to prod! https://advocacy.mozilla.org/en-US/net-neutrality-comments/

**Comment by hannahkane** [comment]
Woohoo! Thank you!
