### ISSUE TITLE
QA (net neutrality typeoutloud): my comment disappears

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#974]
Testing on staging server. 

STR:
Add a comment. 
It shows up briefly, and then disappears

**Comment by beccaklam** [comment]
This should be fixed now - it was a google sheets issue.

**Comment by beccaklam** [comment]
Can this be closed @hannahkane ?

**Comment by hannahkane** [comment]
Yes, fixed.
