### ISSUE TITLE
QA (net neutrality typeoutloud): Is it weird that we mention social accounts, but don't link to them?

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#975]
In the pop-up, we mention following us on Facebook, Twitter, and Medium, but don't provide links. I think we should.

**Comment by beccaklam** [comment]
OH we should definitely link them! Thanks for catching that @hannahkane!

**Comment by beccaklam** [comment]
@hannahkane Links have been added to staging: https://www-typeoutloud-org-staging.herokuapp.com/net-neutrality

**Comment by HPaulJohnson** [comment]
@beccaklam for the Medium link, can we actually change it to this: https://medium.com/mozilla-internet-citizen (That's the blog where the actual content will appear)

**Comment by beccaklam** [comment]
Changed the medium link to the internet citizen version.
