### ISSUE TITLE
Add "subscribed=1" code to home page of safety videos, to turn off email ask if we sent you there from email

### ISSUE THREAD

**Issue by WillatMozFdn** [MozillaFoundation/Advocacy#976]
Detailed description of work:  The individual safety videos have the code in there to turn off the "join our email list" popup ... but the home page of all the videos at https://advocacy.mozilla.org/en-US/safety/ unfortunately does not.  We should fix and standardize this, so that if we send someone to the videos page from an email (with the subscribed=1 querystring), the popup asking for their email address does NOT appear.

*Start date: July 18, 2017* 
*Due date: July 30, 2017* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC: @hannahkane

**Comment by hannahkane** [comment]
@WillatMozFdn - are we sending an email pointing to this page soon?

**Comment by WillatMozFdn** [comment]
@hannahkane  -- yes, MIH team would like to link to that page in their August newsletter, which is scheduled for the first week of August -- thus the "due date" I put on there.

**Comment by hannahkane** [comment]
@ScottDowne is out this week, so we'll have to check in with him next week.

**Comment by ScottDowne** [comment]
It's on staging: https://advocacy.mofostaging.net/en-US/safety/?subscribed=true

Should be on prod any moment now.

**Comment by ScottDowne** [comment]
Done. Closing.

https://advocacy.mozilla.org/en-US/safety/?subscribed=true
