### ISSUE TITLE
New test copy on donate.mozilla.org, triggered via querystring, for fundrsiaing snippet test

### ISSUE THREAD

**Issue by WillatMozFdn** [MozillaFoundation/Advocacy#979]
Detailed description of work:

When someone lands on donate.mozilla.org, **with a querystring including "?test=nnsnippet1707"**, we need for them to see -- instead of the default copy that's currently there -- this copy:

Mozilla is a global nonprofit that stands up for an open and healthy Internet, where telecom companies are not allowed to censor or throttle your access to the web based on the content you want to see. Will you give today?  

(This is part of a snippet test slated to launch July 31, thus the Sunday due date.)

@ScottDowne and @hannahkane 

*Start date: July 25, 2017* 
*Due date: July 30, 2017* 
Note: The dates need to be exactly in the format indicated above for proper integration with the Gantt chart.

CC:

**Comment by hannahkane** [comment]
@WillatMozFdn - I've told @ScottDowne that I'll remind him about this at stand-up after the work week. :)

**Comment by ScottDowne** [comment]
Should be on staging in a bit, link is here: https://donate.mofostaging.net/en-US/?test=nnsnippet1707

I'll double check in a bit, then push to prod, then close this once that's confirmed.

**Comment by ScottDowne** [comment]
@vojtechmzl and @WillatMozFdn just a heads up, the copy in this test is not localized, and I didn't enable it to be localized, so for the test, we need to limit it to en-US only.

**Comment by ScottDowne** [comment]
I'll push this to prod tomorrow.

**Comment by ScottDowne** [comment]
Done, closing, test url is https://donate.mozilla.org/en-US/?test=nnsnippet1707
