### ISSUE TITLE
Determine Press List

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#980]
The task here is to determine which members of the media/press will receive a physical kit as part of the Safety campaign.

- [ ] @HPaulJohnson @brettgaylor - are you able to determine the target number, based on the budget?
- [ ] Can we provide any guidance about the types of media we're targeting?
- [ ] My understanding is that we need physical addresses to ship to

Note: there is a separate ticket to [create an influencer list](https://github.com/MozillaFoundation/Advocacy/issues/981)

**Comment by hannahkane** [comment]
@KevZawacki - I'm going to assign some tickets to you that were discussed at this week's Advocacy   work week. Perhaps @brettgaylor or @caltrider will set up a time to brief you on the decisions made?

@HPaulJohnson - does Temi have a github account?

**Comment by KevZawacki** [comment]
@caltrider Can you book a time for us to discuss? I'd like to learn about kits' content, message, timing, etc.

**Comment by HPaulJohnson** [comment]
We need to get Temi signed up on Github. I believe she created an account but may need to provide her with some brief training on how we use it on Monday.

**Comment by caltrider** [comment]
Yes, @KevZawacki , I'll get a meeting on the calendar for next week.

**Comment by tlasadea** [comment]
@hannahkane @HPaulJohnson I'm here, I'm here! I just saw that Mandy just invited me to Mozilla + Mozilla Foundation so now I am a real person.

**Comment by HPaulJohnson** [comment]
plans changed and this is no longer relevant
