### ISSUE TITLE
Determine Influencer list

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#981]
The task here is to determine which influencers will receive a physical kit as part of the Safety campaign.

- [x] @HPaulJohnson @brettgaylor - are you able to determine the target number, based on the budget?
- [x] Can we provide any guidance about the types of influencers we're targeting?

Note: there is a separate ticket to [create a media list](https://github.com/MozillaFoundation/Advocacy/issues/980)

**Comment by HPaulJohnson** [comment]
Temi is going to start working on the one next week and will be able to speak to quantity. My guess is it's a few hundred at most.

**Comment by tlasadea** [comment]
Hey @brettgaylor, re above - is there any guidance/previous work on influencer stuff for MoFo? Or are we starting from scratch.

**Comment by tlasadea** [comment]
Update: MoCo social + @brettgaylor and I meeting scheduled for August 7th.

**Comment by tlasadea** [comment]
Further update - meeting with myself, @brettgaylor @caltrider @KevZawacki scheduled for 11/08.

Deliverable: have an agreed approach for using influencers, so that the discovery/listing of them can begin! (Ideally).

**Comment by tlasadea** [comment]
Update!

Influencers will be asked to create promotional content for the Buyer's Guide (video, written content). We want them to speak to their audience about connected toys/health/home and drive people to the buyer's guide site by learning more (finding out which products are 💯).

**Comment by tlasadea** [comment]
Hey @caltrider here is the list: https://docs.google.com/spreadsheets/d/1qtdbUTWoi5pAQo3oWTUD4mQFfDcoEayeTodOcRZ9prE/edit#gid=0 this isn't final, this is who I'm contacting. Please have a look before our meeting today (Friday)!

Would be super helpful to get a campaign overview blurb from you that I can included in emails!

**Comment by KevZawacki** [comment]
Press list is coming together [here](https://docs.google.com/spreadsheets/d/1Ae2uYDP_n1UqiTXLbSPUbbdeyuDZIjmgWP6hA_CwSho/edit#gid=0). These people are technically influencers, but can live in a separate, comms-managed spreadsheet.

**Comment by tlasadea** [comment]
Influencer list: [here](https://docs.google.com/presentation/d/14j3Tr549uhwab-lr6WmRjyq743qdlpQqR5LQxLTw4sg/edit#slide=id.g26ac73da4c_1_26)

Influencer brief: [here](https://docs.google.com/a/mozilla.com/presentation/d/1Z0Z_kxbBd-JoCksd5h_-EVfpa_BTjHxRNv2s5bk0iRQ/edit?usp=sharing)

**Comment by hannahkane** [comment]
Nice, @tlasadea. Should we consider this ticket done?

**Comment by tlasadea** [comment]
Oui!
