### ISSUE TITLE
Create press pack

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#982]
Contents TBD

**Comment by tlasadea** [comment]
@hannahkane I think this is likely going to be the same as #983, so could probably close this as it may be a duplication? @KevZawacki perhaps have a look at the issue ^ and see if there is anything else you may need?

**Comment by KevZawacki** [comment]
@hannahkane @tlasadea OK by me to close! We'll develop a press list for pitching, but that task is wrapped up in other comms tickets.
