### ISSUE TITLE
Create Influencer Pack

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#983]
Contents TBD

**Comment by hannahkane** [comment]
@tlasadea - is this still a thing we're going to need to create? Will there be design assets needed?

**Comment by tlasadea** [comment]
@hannahkane probably nothing additional/different than assets that'll need
to be created. Myself Paul and Jen are going over what's required for each
channel today. Will update this ticket later?

**Comment by tlasadea** [comment]
@hannahkane @HPaulJohnson I think this is just going to be:

- [ ] Ideally, access to staging or preview link for influencers
- [ ] Branding/logo/style guide for the guide (I guess the illustrations being used + some kind of signage for the title "Privacy Not Included?")
- [ ] Themes, talking points, main messages to be used when speaking about the guide.

**Comment by tlasadea** [comment]
@caltrider @HPaulJohnson we're going to need at least the 'Themes, talking points, main messages' document for this sooner rather than later - as contracts have been signed by channel mum & standard broadcast and will need to brief Influencers.

**Comment by tlasadea** [comment]
@HPaulJohnson @hannahkane this is done, so closing.
