### ISSUE TITLE
Pitching Safety campaign

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#987]
As a follow up to sending physical safety kits to media and influencers, we'll need to pitch stories.

Working assumption is that Ashley will be a spokesperson for the campaign.

**Comment by KevZawacki** [comment]
Yep, Ashley and Mark as spokespeople.

I've update @tlasadea's [Marketing and Channel Plan](https://docs.google.com/spreadsheets/d/1u21AWY4nhtNg1zJIquzrR6raDilpV-lcp1RpaoGpFhQ/edit#gid=759926306) to indicate when pitching will likely take place.

**Comment by hannahkane** [comment]
Thanks, @KevZawacki.

I'm going to close this ticket, as it doesn't seem useful at this point. Feel free to reopen if it's useful to you.
