### ISSUE TITLE
Style Guide v1

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#988]
To kickstart the project, we need a style guide with suggested messaging and copy that can be used in other aspects of the campaign (website, physical kit, promotional plan).

The style guide will be revised after message testing.

Jen to work with Kevin Fann on this ticket

**Comment by hannahkane** [comment]
@caltrider - given changes to the campaign scope, are you still planning to develop a style guide?

**Comment by caltrider** [comment]
@hannahkane This is something that's pushed to 2018

**Comment by hannahkane** [comment]
K. I'm going to close this for now then.
