### ISSUE TITLE
EU Copyright Petition: Design website V1.0

### ISSUE THREAD

**Issue by damiankay** [MozillaFoundation/Advocacy#99]
To complete once creative brief and wireframes are approved. 

Reference: 
#96 Strategy brief
#95 Creative brief
#97 Comms plan
#93 Wireframes

Due Aug 2

**Comment by lovegushwa** [comment]
@damiankay this is moving along, @natalieworth is wrapping up low fidelity wire frames this week.

**Comment by shaghdoosti** [comment]
Also see petition copy: https://github.com/MozillaFoundation/Advocacy/issues/181

**Comment by lovegushwa** [comment]
@valianttry see the final v1 petition page PSD files here:
https://drive.google.com/folderview?id=0B2qu3ExKWIlvd3k1aVVJY0l4MXc&usp=sharing

Annotation and links are in the redpen here:
https://redpen.io/dg0021f35a8cb63609

**Comment by valianttry** [comment]
@lovegushwa closing this. re-open if that's not correct. :)
