### ISSUE TITLE
Draft comms plan, including FAQ

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#992]
The [Influencer/Media Kit](https://github.com/MozillaFoundation/Advocacy/projects/17) seems particularly relevant. 

I'm not the right person to write this ticket - what are the requirements for the comms plan?

**Comment by hannahkane** [comment]
@caltrider - at stand today, did you say this is in progress?

**Comment by KevZawacki** [comment]
@hannahkane @caltrider 

Hi, current comms plan draft here:

https://docs.google.com/document/d/1suA9a5Vuk0Z_-LD4TKrsioRWP-WPutK8Eq5CWEOUUAc/edit

The IoT survey section will be the first to be built out.

**Comment by KevZawacki** [comment]
Based on recent conversations, we're going to use two comms plan: one for the [IoT Survey](https://docs.google.com/document/d/1suA9a5Vuk0Z_-LD4TKrsioRWP-WPutK8Eq5CWEOUUAc/edit#), and one for the [Holiday Buyers' Guide](https://docs.google.com/document/d/1N2_onI9kU8oMP-jCf1btT5I8nqG8UaoaAPvZjcgvMZs/edit#).

**Comment by hannahkane** [comment]
@KevZawacki - These look awesome. Are there additional steps to finalize these plans, or should we go ahead and close this ticket?

**Comment by KevZawacki** [comment]
@hannahkane The plans will continue to evolve, but I'll go ahead and close this ticket.
