### ISSUE TITLE
Internal deck

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#993]
The deck will be used to gain approvals within the org, and can also be adapted for the contractor brief.

**Comment by caltrider** [comment]
Heya @brettgaylor, @lovegushwa, @hannahkane.  Just talked about the plan for revising the internal deck with Paul.  I'll take the existing deck v3 and update it based on our conversation.  Then he suggested I work with @beccaklam to make it pretty and add in the visuals so we can have this ready to roll next week.  @beccaklam, I'll follow up with you on Monday if that works OK for you.

**Comment by beccaklam** [comment]
Works for me @caltrider !

**Comment by brettgaylor** [comment]
Hi all - meeting time is confirmed for 1:00 Pacific on Wednesday, so we'll need deck ready EOD Tuesday.  All good?

**Comment by caltrider** [comment]
@brettgaylor Yup, we're good.  I'm working on tweaking the deck now. @beccaklam and I have a meeting in the morning to go over it and find spots for visuals. Then she should have most of the day tomorrow to knock it out.

**Comment by hannahkane** [comment]
@caltrider - think we can close this ticket?

**Comment by hannahkane** [comment]
I believe this is done. Please re-open if we have further revisions to make.
