### ISSUE TITLE
Wireframes / IA

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#994]
First pass at 3 variations on wireframes (IA can come later), to be discussed on Thursday, September 7th, and quickly iterated on.

**Comment by beccaklam** [comment]
Rough Wireframes for Microsite
![microsite wireframes-100](https://user-images.githubusercontent.com/20977376/28781507-4e2e52ae-75d8-11e7-9eb2-dfff7ee58b09.jpg)

**Comment by hannahkane** [comment]
This looks great, @beccaklam, and captures the outstanding questions we have. Now we just need to figure out, in #1000, how to test the possible journeys. :)

**Comment by hannahkane** [comment]
hey @beccaklam and @natalieworth—I just moved this to "In Progress" and assigned both of you, as per our discussion earlier. As we said, let's aim to have rough versions for discussion on Thursday, so we can quickly move forward.

**Comment by hannahkane** [comment]
@beccaklam - I'm going to close this, but add follow-up tickets for desktop and any add'l changes that come out of the content conversations.
