### ISSUE TITLE
Website: Artwork

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#996]
Specific needs TBD in #995

**Comment by hannahkane** [comment]
@natalieworth - should we start a checklist here? Something like:

- [ ] homepage illustration
- [ ] category 1 illustration
- [ ] category 2 illustration
- [ ] category 3 illustration
- [ ] category 4 illustration
- [ ] category 5 illustration
- [ ] photos (?) for each item
- [ ] drop caps for category intro?

Anything else?

**Comment by natalieworth** [comment]
I think that's good for now @hannahkane

**Comment by hannahkane** [comment]
@natalieworth @beccaklam - do we have all the artwork now (for the site itself)? Can we close?

**Comment by hannahkane** [comment]
Closing as I believe this is done
