### ISSUE TITLE
Website: UI

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#997]
Specific needs TBD in #995

**Comment by natalieworth** [comment]
First UI direction for Buyers Guide here https://redpen.io/p/fn40d57f5c9bbcf379
cc @beccaklam @hannahkane @HPaulJohnson @caltrider @brettgaylor @tlasadea  if you want to take a look + leave feedback

**Comment by hannahkane** [comment]
also cc'ing @ScottDowne as there are implications for the build suggested in the UI

**Comment by natalieworth** [comment]
Newest UI versions are up here: https://redpen.io/p/rec0d73ec28aa94e6c
cc @ScottDowne @hannahkane @tlasadea @beccaklam 

I am going to hold off on doing the actual detailed product page until we get more refined copy as it takes a while to design (and I've got the social P1 for Paul to work on for now).

**Comment by natalieworth** [comment]
Revised and uploaded the most recent UI versions (V4) on redpen here:
https://redpen.io/p/qja38b769ebd5c0208

Let me know if you have any questions for the build @ScottDowne I need to get an icon for methodology still in the footer and mockup the individual product page on desktop and mobile once more clear content is completed for it.

cc @hannahkane @beccaklam @HPaulJohnson

**Comment by natalieworth** [comment]
Updated the UI to include the 'Edwin the duck' example product page overview: https://redpen.io/ncbea1ceace44f2489

cc @hannahkane @beccaklam @HPaulJohnson @caltrider

**Comment by natalieworth** [comment]
V1 of the product page overview for desktop is here cc @hannahkane @beccaklam @ScottDowne @HPaulJohnson @caltrider

**Comment by hannahkane** [comment]
@natalieworth - [here](https://redpen.io/pt78ffc07ee675e391)?

**Comment by natalieworth** [comment]
Updated the UI in redpen (V6) based off of the revised copy from Jen https://redpen.io/p/ur92903e15f884cf2d
cc @HPaulJohnson @beccaklam @caltrider @hannahkane @ScottDowne

**Comment by hannahkane** [comment]
@ScottDowne - do you have what you need to finish the UI?

**Comment by hannahkane** [comment]
@natalieworth - can we close this ticket now?

**Comment by hannahkane** [comment]
@ScottDowne @natalieworth - I think we can close this, right?

**Comment by ScottDowne** [comment]
Yeah probably. It's just QA stuff now anyway, so no need to track anything else here.
