### ISSUE TITLE
Website: copy deck

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#998]
Specific needs TBD in #995

**Comment by hannahkane** [comment]
@caltrider @HPaulJohnson - have we decided who is providing copy for the buyer's guide? I think considering how far along we are on the UX and UI, this person could start work ASAP.

**Comment by hannahkane** [comment]
@caltrider @HPaulJohnson - What would be useful in advancing this? Maybe this can be done through redpen annotations on the mockups?

**Comment by hannahkane** [comment]
Just noting this is on @caltrider's ToDo list for this week

**Comment by hannahkane** [comment]
@natalieworth and @HPaulJohnson - I see Jen left some copy comments in the redpen.

@caltrider - when you're back, let's figure out if there's another round on copy, or if we're good to close.

**Comment by hannahkane** [comment]
Are we done with all copy? Can we close this ticket?

**Comment by caltrider** [comment]
@hannahkane Yes, you can close this
