### ISSUE TITLE
Website: determine and capture metrics

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/Advocacy#999]
Working with @vojtechmzl to understand what meaningful actions we can measure, we'll ensure that we're capturing what we can about how members of the public are engaging with the campaign via the website

**Comment by hannahkane** [comment]
@vojtechmzl - sorry to tag you in here without a lot of context. We'll be sharing a deck detailing the Safety campaign plans made during this past work week soon, and perhaps we can schedule a conversation to catch you up on those plans?

**Comment by vojtechsedlak** [comment]
Thanks for the heads up @hannahkane. Sounds great!

**Comment by ScottDowne** [comment]
@vojtechmzl this is the staging link for the site: https://advocacy-mozilla-org-st-pr-395.herokuapp.com/en-US/privacynotincluded

So far it's tracking basic bounce rate and hits, and also has the normal signup component metrics.

Is there anything else you think we might want? I can think of a few if you want to punt this to me.

**Comment by vojtechsedlak** [comment]
Hey @ScottDowne, sorry for the delay, was out on PTO. I chatted with Alex around what we would like to see tracked on the site and here is the list we came up with:

Use UA-49796218-9 as the tracking ID
Implement the following custom events:
- Email popup
    - Popup shown
    - Email field focus
    - Checkbox clicked
    - Form submit
    - Maybe later click
    - Thank you page share click
- Clicks on share buttons in the header
- Clicks on Donate button

I can't see any tags firing on the staging site yet, but happy to help QA any of these. Let me know if I can help implement any of these.

Thanks!

**Comment by ScottDowne** [comment]
I'll probably call out QA next week. Also, that tracking ID, is that the same one used on advocacy.mozilla.org? because that's where this site lives.

**Comment by vojtechsedlak** [comment]
Yup the tracking ID is the same as advocacy.mozilla.org. Thanks Scott!

**Comment by ScottDowne** [comment]
@vojtechmzl do you want to provide any tracking query params to the donate link?

**Comment by ScottDowne** [comment]
@vojtechmzl so far I added these: https://github.com/mozilla/advocacy.mozilla.org/commit/ded81bc797f00ff28ecb1a323e6424d8e8afd8a9

No staging link yet.

**Comment by ScottDowne** [comment]
@vojtechmzl Should be live now and results from us clicking on this should be coming through.

**Comment by vojtechsedlak** [comment]
Sorry for the delay on getting back to you @ScottDowne, was out on PTO. Just checked the site and GA reports and everything looks great. Thanks for setting all this up!

**Comment by HPaulJohnson** [comment]
i think we are good to go on this one!
